import test from 'node:test';
import assert from 'node:assert/strict';
import { companyId, decimalAmount, sourceReference } from '@elhafez/contracts';
import type { StandaloneServicesApplicationService } from '@elhafez/standalone-services';
import type { TourismContractInventoryApplicationService } from '@elhafez/tourism-contract-inventory';
import { ServiceFulfillmentApplicationService, type ConfirmationEvidence, type DeliveryEvidence, type FulfillmentCase, type FulfillmentRepository } from './application/service-fulfillment.application-service.js';
const company=companyId('company-1');
function setup(){let value:FulfillmentCase|null=null;let completions=0;const confirmations:ConfirmationEvidence[]=[],deliveries:DeliveryEvidence[]=[];const receipts=new Map<string,{payloadHash:string;caseId:string}>();const repo:FulfillmentRepository={get:async()=>value,create:async v=>{value??=v},confirm:async(v,expected,e,key,hash)=>{assert.equal(value?.version,expected);value=v;confirmations.push(e);receipts.set(key,{payloadHash:hash,caseId:v.id})},deliver:async(v,expected,e,key,hash)=>{assert.equal(value?.version,expected);value=v;deliveries.push(e);receipts.set(key,{payloadHash:hash,caseId:v.id})},receipt:async(_,key)=>receipts.get(key)??null,confirmations:async()=>confirmations,deliveries:async()=>deliveries};
 const services={completeFromFulfillment:async()=>{completions+=1},getService:async()=>({service:{id:'service-1',number:'S1',companyId:company,branchId:'branch-1',status:'CONFIRMED',revision:1,supplyPlanId:'plan-1'},revision:{serviceId:'service-1',revision:1,quantity:decimalAmount('5'),category:'HOTEL',serviceDate:'2026-10-01',commercial:{currency:'SAR',netAmount:decimalAmount('500')}}})} as unknown as StandaloneServicesApplicationService;
 const inventory={getStandaloneSupplyPlan:async()=>({planId:'plan-1',companyId:company,branchId:'branch-1',service:sourceReference('TOURISM_SERVICE','service-1'),serviceRevision:1,lines:[{allocationQuantity:decimalAmount('3')}],residuals:[{supplierId:'supplier-1',quantity:decimalAmount('2')} ]})} as unknown as TourismContractInventoryApplicationService;
 return {app:new ServiceFulfillmentApplicationService(repo,services,inventory),completions:()=>completions}}
test('confirmation is bounded independently by internal coverage and quoted supplier residual; partial delivery stays partial',async()=>{const {app}=setup(),base={companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',at:'2026-09-24T12:00:00Z',referenceType:'BOOKING',reference:'confirmed'};
 await app.confirm({...base,commandKey:'internal',quantity:decimalAmount('3'),internalCoverage:true});
 await assert.rejects(app.confirm({...base,commandKey:'over-internal',quantity:decimalAmount('1'),internalCoverage:true}),/selected supply part/);
 await app.confirm({...base,commandKey:'supplier',quantity:decimalAmount('2'),supplierId:'supplier-1'});
 await assert.rejects(app.confirm({...base,commandKey:'other',quantity:decimalAmount('1'),supplierId:'supplier-2'}),/service quantity|selected supply part/);
 const partial=await app.deliver({companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',commandKey:'delivery-1',quantity:decimalAmount('2'),at:'2026-09-25T12:00:00Z',unit:'ROOM',note:'handover'});
 assert.equal(partial?.case.status,'PARTIALLY_DELIVERED');assert.deepEqual(await app.cancellationBlockers(company,'branch-1','service-1'),['SERVICE_DELIVERY_RECORDED']);
 const replay=await app.deliver({companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',commandKey:'delivery-1',quantity:decimalAmount('2'),at:'2026-09-25T12:00:00Z',unit:'ROOM',note:'handover'});assert.equal(replay?.deliveries.length,1);
 await assert.rejects(app.deliver({companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',commandKey:'too-much',quantity:decimalAmount('4'),at:'2026-09-25T12:00:00Z',unit:'ROOM',note:'handover'}),/confirmed quantity/);
});

test('full delivery marks the service complete and replays without duplicate evidence',async()=>{const {app,completions}=setup();const base={companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',at:'2026-09-24T12:00:00Z',referenceType:'BOOKING',reference:'confirmed'};await app.confirm({...base,commandKey:'stock',quantity:decimalAmount('3'),internalCoverage:true});await app.confirm({...base,commandKey:'external',quantity:decimalAmount('2'),supplierId:'supplier-1'});const delivery={companyId:company,branchId:'branch-1',serviceId:'service-1',actorId:'staff',commandKey:'full',quantity:decimalAmount('5'),at:'2026-09-25T12:00:00Z',unit:'ROOM',note:'handover'};assert.equal((await app.deliver(delivery))?.case.status,'DELIVERED');assert.equal(completions(),1);assert.equal((await app.deliver(delivery))?.deliveries.length,1);});
