import { Prisma, type PrismaClient } from '@prisma/client';
import { decimalAmount, type CompanyId } from '@elhafez/contracts';
import type { ConfirmationEvidence, DeliveryEvidence, FulfillmentCase, FulfillmentRepository } from '../application/service-fulfillment.application-service.js';
const rowCase=(row:{id:string;companyId:string;branchId:string;serviceId:string;revision:number;quantity:Prisma.Decimal;status:string;supplierId:string|null;internalCoverage:boolean;confirmedQuantity:Prisma.Decimal;deliveredQuantity:Prisma.Decimal;version:number}):FulfillmentCase=>({id:row.id,companyId:row.companyId as CompanyId,branchId:row.branchId,serviceId:row.serviceId,revision:row.revision,quantity:decimalAmount(row.quantity.toString()),status:row.status as FulfillmentCase['status'],...(row.supplierId?{supplierId:row.supplierId}:{}),internalCoverage:row.internalCoverage,confirmedQuantity:decimalAmount(row.confirmedQuantity.toString()),deliveredQuantity:decimalAmount(row.deliveredQuantity.toString()),version:row.version});
export class PrismaServiceFulfillmentRepository implements FulfillmentRepository {
 constructor(private readonly db:PrismaClient){}
 async get(companyId:CompanyId,branchId:string,serviceId:string){const row=await this.db.sfCase.findUnique({where:{companyId_branchId_serviceId:{companyId,branchId,serviceId}}});return row?rowCase(row):null}
 async create(value:FulfillmentCase){await this.db.sfCase.upsert({where:{companyId_branchId_serviceId:{companyId:value.companyId,branchId:value.branchId,serviceId:value.serviceId}},create:{...value,supplierId:null,internalCoverage:false},update:{}})}
 async receipt(companyId:CompanyId,key:string){return this.db.sfCommandReceipt.findUnique({where:{companyId_commandKey:{companyId,commandKey:key}}})}
 async confirm(value:FulfillmentCase,expectedVersion:number,evidence:ConfirmationEvidence,key:string,payloadHash:string){await this.db.$transaction(async tx=>{const updated=await tx.sfCase.updateMany({where:{id:value.id,companyId:value.companyId,branchId:value.branchId,version:expectedVersion},data:{status:value.status,version:value.version,confirmedQuantity:value.confirmedQuantity,supplierId:value.supplierId??null,internalCoverage:!!value.internalCoverage}});if(updated.count!==1)throw new Error('stale fulfillment');await tx.sfConfirmation.create({data:{...evidence}});await tx.sfCommandReceipt.create({data:{companyId:value.companyId,commandKey:key,payloadHash,caseId:value.id}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 async deliver(value:FulfillmentCase,expectedVersion:number,evidence:DeliveryEvidence,key:string,payloadHash:string){await this.db.$transaction(async tx=>{const updated=await tx.sfCase.updateMany({where:{id:value.id,companyId:value.companyId,branchId:value.branchId,version:expectedVersion},data:{status:value.status,version:value.version,deliveredQuantity:value.deliveredQuantity}});if(updated.count!==1)throw new Error('stale fulfillment');await tx.sfDeliveryEvidence.create({data:{...evidence}});await tx.sfCommandReceipt.create({data:{companyId:value.companyId,commandKey:key,payloadHash,caseId:value.id}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 async confirmations(caseId:string){return (await this.db.sfConfirmation.findMany({where:{caseId},orderBy:{at:'asc'}})).map(row=>({id:row.id,caseId:row.caseId,actorId:row.actorId,at:row.at.toISOString(),quantity:decimalAmount(row.quantity.toString()),referenceType:row.referenceType,reference:row.reference,internalCoverage:row.internalCoverage,...(row.supplierId?{supplierId:row.supplierId}:{}),...(row.fileId?{fileId:row.fileId}:{})} as ConfirmationEvidence))}
 async deliveries(caseId:string){return (await this.db.sfDeliveryEvidence.findMany({where:{caseId},orderBy:{at:'asc'}})).map(row=>({id:row.id,caseId:row.caseId,actorId:row.actorId,at:row.at.toISOString(),quantity:decimalAmount(row.quantity.toString()),unit:row.unit,note:row.note,...(row.fileId?{fileId:row.fileId}:{}),...(row.correctsId?{correctsId:row.correctsId}:{})} as DeliveryEvidence))}
}
