import{ContractValidationError,type CompanyId}from'@elhafez/contracts';
declare const supplierIdBrand:unique symbol;declare const bankIdBrand:unique symbol;
export type SupplierId=string&{readonly[supplierIdBrand]:'SupplierId'};export type SupplierBankAccountId=string&{readonly[bankIdBrand]:'SupplierBankAccountId'};
export type SupplierStatus='ACTIVE'|'INACTIVE'|'ON_HOLD';export type SupplierApprovalStatus='PENDING'|'APPROVED'|'REJECTED';export type SupplierCategoryCode='HOTEL'|'AIRLINE'|'TRANSPORT'|'VISA'|'OTHER'|string;
export interface SupplierProfile{readonly id:SupplierId;readonly companyId:CompanyId;readonly partyId:string;readonly supplierCode:string;readonly status:SupplierStatus;readonly approvalStatus:SupplierApprovalStatus;readonly defaultCurrency:string;readonly creditDays:number;readonly contactPerson:string|null;readonly notes:string|null;readonly createdAt:string;readonly updatedAt:string;}
export interface SupplierApproval{readonly id:string;readonly companyId:CompanyId;readonly supplierId:SupplierId;readonly decision:'APPROVED'|'REJECTED';readonly source:'HUMAN'|'LEGACY_MIGRATION';readonly actorId:string;readonly reason:string|null;readonly decidedAt:string;}
export interface SupplierBankAccount{readonly id:SupplierBankAccountId;readonly companyId:CompanyId;readonly supplierId:SupplierId;readonly bankName:string|null;readonly accountNumber:string|null;readonly iban:string|null;readonly currency:string|null;readonly active:boolean;readonly isDefault:boolean;readonly createdBy:string;readonly updatedBy:string;readonly createdAt:string;readonly updatedAt:string;}
export interface SupplierLegacyReference{readonly companyId:CompanyId;readonly source:string;readonly legacySupplierId:string;readonly supplierId:SupplierId;readonly partyId:string;readonly fingerprint:string;readonly createdAt:string;}
export const supplierId=(v:string):SupplierId=>required(v,'supplierId') as SupplierId;export const supplierBankAccountId=(v:string):SupplierBankAccountId=>required(v,'bankAccountId') as SupplierBankAccountId;export const required=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x;};export const currency=(v:string)=>{const x=required(v,'currency').toUpperCase();if(!/^[A-Z]{3}$/.test(x))throw new ContractValidationError('currency','must be a 3-letter code');return x;};export const creditDays=(v:number)=>{if(!Number.isInteger(v)||v<0)throw new ContractValidationError('creditDays','must be a non-negative integer');return v;};
