import {Prisma,type PrismaClient} from '@prisma/client';
import type {SaasRepository} from '../application/saas.repository.js';
import type {SaasControlEvent,SaasOwnerAccount,SaasOwnerSession,SaasPayment,SaasPlan,SaasSubscription,SaasSubscriptionEvent,SaasTenant} from '../domain/saas.types.js';
import {SaasError} from '../domain/saas.types.js';

const strings=(value:unknown):readonly string[]=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];
const tenant=(r:{companyId:string;companyCode:string;mode:string;createdAt:Date;updatedAt:Date}):SaasTenant=>({...r,mode:r.mode as SaasTenant['mode']});
const plan=(r:{id:string;code:string;name:string;intervalMonths:number;priceMinor:number;currency:string;entitlements:unknown;active:boolean;createdAt:Date}):SaasPlan=>({...r,entitlements:strings(r.entitlements)});
const subscription=(r:{id:string;companyId:string;planId:string;status:string;currentPeriodStart:Date;currentPeriodEnd:Date;gracePeriodEnd:Date|null;entitlementsSnapshot:unknown;version:number;createdAt:Date;updatedAt:Date}):SaasSubscription=>({id:r.id,companyId:r.companyId,planId:r.planId,status:r.status as SaasSubscription['status'],currentPeriodStart:r.currentPeriodStart,currentPeriodEnd:r.currentPeriodEnd,gracePeriodEnd:r.gracePeriodEnd,entitlements:strings(r.entitlementsSnapshot),version:r.version,createdAt:r.createdAt,updatedAt:r.updatedAt});
const owner=(r:{id:string;email:string;passwordHash:string;mfaSecretCipher:string;status:string;failedAttempts:number;lockedUntil:Date|null;createdAt:Date;updatedAt:Date}):SaasOwnerAccount=>({...r,status:r.status as SaasOwnerAccount['status']});
const payment=(r:{id:string;companyId:string;subscriptionId:string;provider:string;reference:string;amountMinor:number;currency:string;idempotencyKey:string;payloadHash:string;paidAt:Date;createdAt:Date}):SaasPayment=>({...r,provider:r.provider as SaasPayment['provider']});
const json=(v:Record<string,unknown>|readonly string[])=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue;
const control=(e:SaasControlEvent)=>({id:e.id,ownerId:e.ownerId,action:e.action,targetType:e.targetType,targetId:e.targetId,companyId:e.companyId,metadata:json(e.metadata),occurredAt:e.occurredAt});
const event=(e:SaasSubscriptionEvent)=>({id:e.id,companyId:e.companyId,subscriptionId:e.subscriptionId,kind:e.kind,fromStatus:e.fromStatus,toStatus:e.toStatus,ownerId:e.ownerId,paymentId:e.paymentId,periodStart:e.periodStart,periodEnd:e.periodEnd,metadata:json(e.metadata),occurredAt:e.occurredAt});

export class PrismaSaasRepository implements SaasRepository{
 constructor(private readonly db:PrismaClient){}
 async countOwners(){return this.db.saasOwnerAccount.count();}
 async findOwnerByEmail(email:string){const r=await this.db.saasOwnerAccount.findUnique({where:{email}});return r?owner(r):null;}
 async findOwnerById(id:string){const r=await this.db.saasOwnerAccount.findUnique({where:{id}});return r?owner(r):null;}
 async createOwner(v:SaasOwnerAccount,e:SaasControlEvent){await this.db.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(73300101)`;if(await tx.saasOwnerAccount.count())throw new SaasError('BOOTSTRAP_CLOSED','owner bootstrap is permanently closed');await tx.saasOwnerAccount.create({data:v});await tx.saasControlEvent.create({data:control(e)});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async recordOwnerFailure(ownerId:string,updatedAt:Date,e:SaasControlEvent){return this.db.$transaction(async tx=>{await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "saas_owner_accounts" WHERE "id" = ${ownerId} FOR UPDATE`;const current=await tx.saasOwnerAccount.findUniqueOrThrow({where:{id:ownerId}}),failedAttempts=current.failedAttempts+1,lockedUntil=failedAttempts>=5?new Date(updatedAt.getTime()+15*60_000):null;await tx.saasOwnerAccount.update({where:{id:ownerId},data:{failedAttempts,lockedUntil,updatedAt}});await tx.saasControlEvent.create({data:control({...e,metadata:{...e.metadata,failedAttempts,locked:Boolean(lockedUntil)}})});return{failedAttempts,lockedUntil};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async resetOwnerFailures(ownerId:string,updatedAt:Date){await this.db.saasOwnerAccount.update({where:{id:ownerId},data:{failedAttempts:0,lockedUntil:null,updatedAt}});}
 async recoverOwnerMfa(i:{ownerId:string;mfaSecretCipher:string;updatedAt:Date;event:SaasControlEvent}){return this.db.$transaction(async tx=>{await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "saas_owner_accounts" WHERE "id" = ${i.ownerId} FOR UPDATE`;await tx.saasOwnerAccount.update({where:{id:i.ownerId},data:{mfaSecretCipher:i.mfaSecretCipher,failedAttempts:0,lockedUntil:null,updatedAt:i.updatedAt}});const revoked=await tx.saasOwnerSession.updateMany({where:{ownerId:i.ownerId,revokedAt:null},data:{revokedAt:i.updatedAt}});await tx.saasControlEvent.create({data:control({...i.event,metadata:{...i.event.metadata,revokedSessions:revoked.count}})});return revoked.count;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async recoverOwnerPassword(i:{ownerId:string;passwordHash:string;updatedAt:Date;event:SaasControlEvent}){return this.db.$transaction(async tx=>{await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "saas_owner_accounts" WHERE "id" = ${i.ownerId} FOR UPDATE`;await tx.saasOwnerAccount.update({where:{id:i.ownerId},data:{passwordHash:i.passwordHash,failedAttempts:0,lockedUntil:null,updatedAt:i.updatedAt}});const revoked=await tx.saasOwnerSession.updateMany({where:{ownerId:i.ownerId,revokedAt:null},data:{revokedAt:i.updatedAt}});await tx.saasControlEvent.create({data:control({...i.event,metadata:{...i.event.metadata,revokedSessions:revoked.count}})});return revoked.count;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async createOwnerSession(v:SaasOwnerSession,e:SaasControlEvent){await this.db.$transaction(async tx=>{await tx.saasOwnerSession.create({data:v});await tx.saasControlEvent.create({data:control(e)});});}
 async findOwnerSessionByHash(tokenHash:string){return await this.db.saasOwnerSession.findUnique({where:{tokenHash}});}
 async revokeOwnerSession(sessionId:string,revokedAt:Date,e:SaasControlEvent){await this.db.$transaction(async tx=>{await tx.saasOwnerSession.updateMany({where:{id:sessionId,revokedAt:null},data:{revokedAt}});await tx.saasControlEvent.create({data:control(e)});});}
 async revokeAllOwnerSessions(revokedAt:Date,e:SaasControlEvent){return this.db.$transaction(async tx=>{const result=await tx.saasOwnerSession.updateMany({where:{revokedAt:null},data:{revokedAt}});await tx.saasControlEvent.create({data:control({...e,metadata:{...e.metadata,revokedSessions:result.count}})});return result.count;});}
 async createPlan(v:SaasPlan,e:SaasControlEvent){return this.db.$transaction(async tx=>{const r=await tx.saasPlan.create({data:{...v,entitlements:json(v.entitlements)}});await tx.saasControlEvent.create({data:control(e)});return plan(r);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async findPlan(id:string){const r=await this.db.saasPlan.findUnique({where:{id}});return r?plan(r):null;}
 async listPlans(){return(await this.db.saasPlan.findMany({orderBy:{createdAt:'asc'}})).map(plan);}
 async findTenant(companyId:string){const r=await this.db.saasTenant.findUnique({where:{companyId}});return r?tenant(r):null;}
 async findTenantByCode(companyCode:string){const r=await this.db.saasTenant.findUnique({where:{companyCode}});return r?tenant(r):null;}
 async listTenants(){return(await this.db.saasTenant.findMany({orderBy:{createdAt:'asc'}})).map(tenant);}
 async findSubscription(companyId:string){const r=await this.db.saasSubscription.findUnique({where:{companyId}});return r?subscription(r):null;}
 async activate(i:{tenant:SaasTenant;subscription:SaasSubscription;payment:SaasPayment;event:SaasSubscriptionEvent;controlEvent:SaasControlEvent}){return this.db.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${i.subscription.companyId}))`);const replayPayment=await tx.saasPayment.findUnique({where:{idempotencyKey:i.payment.idempotencyKey}});if(replayPayment){if(replayPayment.payloadHash!==i.payment.payloadHash)throw new SaasError('IDEMPOTENCY_CONFLICT','idempotency key belongs to another request');const replay=await tx.saasSubscription.findUnique({where:{companyId:i.subscription.companyId}});if(!replay)throw new SaasError('CONFLICT','activation replay is incomplete');return subscription(replay);}const referencePayment=await tx.saasPayment.findUnique({where:{companyId_provider_reference:{companyId:i.payment.companyId,provider:i.payment.provider,reference:i.payment.reference}}});if(referencePayment){if(referencePayment.payloadHash!==i.payment.payloadHash)throw new SaasError('PAYMENT_REFERENCE_REUSED','payment reference was already used');const replay=await tx.saasSubscription.findUnique({where:{companyId:i.subscription.companyId}});if(!replay)throw new SaasError('CONFLICT','payment replay is incomplete');return subscription(replay);}if(await tx.saasSubscription.findUnique({where:{companyId:i.subscription.companyId}}))throw new SaasError('CONFLICT','company already has a subscription');await tx.saasTenant.upsert({where:{companyId:i.tenant.companyId},create:i.tenant,update:{mode:i.tenant.mode,updatedAt:i.tenant.updatedAt}});const r=await tx.saasSubscription.create({data:{id:i.subscription.id,companyId:i.subscription.companyId,planId:i.subscription.planId,status:i.subscription.status,currentPeriodStart:i.subscription.currentPeriodStart,currentPeriodEnd:i.subscription.currentPeriodEnd,gracePeriodEnd:i.subscription.gracePeriodEnd,entitlementsSnapshot:json(i.subscription.entitlements),version:i.subscription.version,createdAt:i.subscription.createdAt,updatedAt:i.subscription.updatedAt}});await tx.saasPayment.create({data:i.payment});await tx.saasSubscriptionEvent.create({data:event(i.event)});await tx.saasControlEvent.create({data:control(i.controlEvent)});return subscription(r);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async findPaymentByIdempotencyKey(idempotencyKey:string){const r=await this.db.saasPayment.findUnique({where:{idempotencyKey}});return r?payment(r):null;}
 async renew(i:{expectedVersion:number;subscription:SaasSubscription;payment:SaasPayment;event:SaasSubscriptionEvent;controlEvent:SaasControlEvent}){return this.db.$transaction(async tx=>{await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "saas_subscriptions" WHERE "id" = ${i.subscription.id} FOR UPDATE`;const replayPayment=await tx.saasPayment.findUnique({where:{idempotencyKey:i.payment.idempotencyKey}});if(replayPayment){if(replayPayment.payloadHash!==i.payment.payloadHash)throw new SaasError('IDEMPOTENCY_CONFLICT','idempotency key belongs to another request');return subscription(await tx.saasSubscription.findUniqueOrThrow({where:{id:i.subscription.id}}));}const referencePayment=await tx.saasPayment.findUnique({where:{companyId_provider_reference:{companyId:i.payment.companyId,provider:i.payment.provider,reference:i.payment.reference}}});if(referencePayment){if(referencePayment.payloadHash!==i.payment.payloadHash)throw new SaasError('PAYMENT_REFERENCE_REUSED','payment reference was already used');return subscription(await tx.saasSubscription.findUniqueOrThrow({where:{id:i.subscription.id}}));}const changed=await tx.saasSubscription.updateMany({where:{id:i.subscription.id,companyId:i.subscription.companyId,version:i.expectedVersion},data:{status:i.subscription.status,currentPeriodStart:i.subscription.currentPeriodStart,currentPeriodEnd:i.subscription.currentPeriodEnd,gracePeriodEnd:null,entitlementsSnapshot:json(i.subscription.entitlements),version:i.subscription.version,updatedAt:i.subscription.updatedAt}});if(changed.count!==1)throw new SaasError('CONFLICT','subscription changed concurrently');await tx.saasPayment.create({data:i.payment});await tx.saasSubscriptionEvent.create({data:event(i.event)});await tx.saasControlEvent.create({data:control(i.controlEvent)});return subscription(await tx.saasSubscription.findUniqueOrThrow({where:{id:i.subscription.id}}));},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async changeStatus(i:{expectedVersion:number;subscription:SaasSubscription;event:SaasSubscriptionEvent;controlEvent:SaasControlEvent}){return this.db.$transaction(async tx=>{const changed=await tx.saasSubscription.updateMany({where:{id:i.subscription.id,companyId:i.subscription.companyId,version:i.expectedVersion},data:{status:i.subscription.status,version:i.subscription.version,updatedAt:i.subscription.updatedAt}});if(changed.count!==1)throw new SaasError('CONFLICT','subscription changed concurrently');await tx.saasSubscriptionEvent.create({data:event(i.event)});await tx.saasControlEvent.create({data:control(i.controlEvent)});return subscription(await tx.saasSubscription.findUniqueOrThrow({where:{id:i.subscription.id}}));},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async recordControlEvent(e:SaasControlEvent){await this.db.saasControlEvent.create({data:control(e)});}
}
