import assert from 'node:assert/strict';
import test from 'node:test';
import { companyId, currencyCode, decimalAmount, money } from '@elhafez/contracts';
import { CurrencyFxApplicationService } from './application/currency-fx.application-service.js';
import type { LiveFxRateProvider } from './application/live-fx-rate.provider.js';
import { InMemoryCurrencyFxRepository } from './infrastructure/in-memory-currency-fx.repository.js';

const company=companyId('company-1'),other=companyId('company-2'),EGP=currencyCode('EGP'),USD=currencyCode('USD'),SAR=currencyCode('SAR'),at='2026-09-18T00:00:00.000Z';
async function service(){const s=new CurrencyFxApplicationService(new InMemoryCurrencyFxRepository());for(const c of[company,other]){await s.configure({companyId:c,code:EGP,precision:2,isBase:true,status:'ACTIVE'});await s.configure({companyId:c,code:USD,precision:2,isBase:false,status:'ACTIVE'});}return s;}

test('validates currency metadata and inactive use',async()=>{const s=await service();await assert.rejects(s.configure({companyId:company,code:USD,precision:12,isBase:false,status:'ACTIVE'}));await s.configure({companyId:company,code:USD,precision:2,isBase:false,status:'INACTIVE'});await assert.rejects(s.resolveRate(company,USD,EGP,at),/not active/);});

test('lists all company currencies with one base currency instead of exposing only one configured code',async()=>{const s=await service();await s.configure({companyId:company,code:SAR,precision:2,isBase:false,status:'ACTIVE'});const rows=await s.listCurrencies(company);assert.deepEqual(rows.map(row=>row.code),[EGP,SAR,USD]);assert.equal(rows.filter(row=>row.isBase).length,1);assert.equal(rows.find(row=>row.isBase)?.code,EGP);assert.equal((await s.listCurrencies(other)).length,2);});

test('publishes, resolves deterministic rates and rejects conflicts and company leakage',async()=>{const s=await service();const input={id:'r1',companyId:company,fromCurrency:USD,toCurrency:EGP,effectiveAt:at,rate:decimalAmount('50.125'),source:'CENTRAL_BANK'};const snapshot=await s.publishRate(input);assert.ok(Object.isFrozen(snapshot));await s.publishRate(input);await assert.rejects(s.publishRate({...input,rate:decimalAmount('51')}),/conflicting/);assert.equal((await s.resolveRate(company,USD,EGP,'2026-09-19T00:00:00.000Z')).rate,'50.125');await assert.rejects(s.resolveRate(other,USD,EGP,at),/no rate/);});

test('refreshes a live quote through the provider and persists it as canonical FX evidence',async()=>{const repo=new InMemoryCurrencyFxRepository();const live:LiveFxRateProvider={async quote(from,to){return{fromCurrency:from,toCurrency:to,effectiveAt:'2026-10-01T05:00:00.000Z',rate:decimalAmount('13.25'),source:'LIVE:TEST'}}};const s=new CurrencyFxApplicationService(repo,live);await s.configure({companyId:company,code:EGP,precision:2,isBase:true,status:'ACTIVE'});await s.configure({companyId:company,code:SAR,precision:2,isBase:false,status:'ACTIVE'});const quote=await s.refreshLiveRate(company,SAR,EGP,'live-1');assert.equal(quote.rate,'13.25');assert.equal(quote.source,'LIVE:TEST');const stored=await s.resolveRate(company,SAR,EGP,'2026-10-01T06:00:00.000Z');assert.equal(stored.rateId,'live-1');assert.equal(stored.rate,'13.25');});

test('exact settlement and same currency never use floating point',async()=>{const s=await service();await s.publishRate({id:'r1',companyId:company,fromCurrency:USD,toCurrency:EGP,effectiveAt:at,rate:decimalAmount('50.125'),source:'BANK'});assert.equal((await s.calculateSettlement(company,money('9007199254740993.123',USD),EGP,at)).converted.amount,'451485862643892280.290375');assert.equal((await s.resolveRate(company,EGP,EGP,at)).rate,'1');});

test('BR-036 prepares only foreign monetary asset/liability positions',async()=>{const s=await service();await s.publishRate({id:'r1',companyId:company,fromCurrency:USD,toCurrency:EGP,effectiveAt:at,rate:decimalAmount('50'),source:'BANK'});for(const classification of['ASSET','LIABILITY']as const){const result=await s.prepareRevaluation({companyId:company,positionReference:'p',classification,monetary:true,foreignAmount:money('2',USD),priorBaseAmount:decimalAmount('90'),baseCurrency:EGP,at});assert.equal(result.status,'PREPARED');if(result.status==='PREPARED')assert.equal(result.baseDifference.amount,'10');}for(const classification of['REVENUE','EXPENSE','EQUITY']as const)assert.equal((await s.prepareRevaluation({companyId:company,positionReference:'p',classification,monetary:true,foreignAmount:money('2',USD),priorBaseAmount:decimalAmount('90'),baseCurrency:EGP,at})).status,'EXCLUDED');assert.equal((await s.prepareRevaluation({companyId:company,positionReference:'p',classification:'ASSET',monetary:true,foreignAmount:money('2',EGP),priorBaseAmount:decimalAmount('2'),baseCurrency:EGP,at})).status,'NO_REVALUATION');await assert.rejects((await service()).prepareRevaluation({companyId:company,positionReference:'p',classification:'ASSET',monetary:true,foreignAmount:money('2',USD),priorBaseAmount:decimalAmount('90'),baseCurrency:EGP,at}),/no rate/);});

test('BR-036 excludes non-monetary assets and liabilities',async()=>{const s=await service();for(const classification of['ASSET','LIABILITY']as const){const result=await s.prepareRevaluation({companyId:company,positionReference:'non-monetary',classification,monetary:false,foreignAmount:money('2',USD),priorBaseAmount:decimalAmount('90'),baseCurrency:EGP,at});assert.equal(result.status,'EXCLUDED');if(result.status==='EXCLUDED')assert.match(result.reason,/non-monetary/);}});
