import{Prisma,type PrismaClient}from'@prisma/client';
import{ContractValidationError}from'@elhafez/contracts';
import type{OperationalReportingRepository}from'../application/operational-reporting.repository.js';
import type{OperationalReportSchedule,SavedOperationalReport}from'../domain/operational-reporting.js';
function object(value:Prisma.JsonValue):Readonly<Record<string,unknown>>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Readonly<Record<string,unknown>>:{};}
export class PrismaOperationalReportingRepository implements OperationalReportingRepository{
 constructor(private readonly db:PrismaClient){}
 private savedReport(row:{id:string;companyId:string;ownerActorId:string;name:string;reportKey:string;filtersJson:Prisma.JsonValue;visibility:string;active:boolean;createdAt:Date;updatedAt:Date}):SavedOperationalReport{return{id:row.id,companyId:row.companyId,ownerActorId:row.ownerActorId,name:row.name,reportKey:row.reportKey as SavedOperationalReport['reportKey'],filters:object(row.filtersJson),visibility:row.visibility as SavedOperationalReport['visibility'],active:row.active,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
 private schedule(row:{id:string;companyId:string;savedReportId:string;cadence:string;hourUtc:number;weekday:number|null;dayOfMonth:number|null;channel:string;recipient:string|null;enabled:boolean;createdBy:string;createdAt:Date;updatedAt:Date}):OperationalReportSchedule{return{id:row.id,companyId:row.companyId,savedReportId:row.savedReportId,cadence:row.cadence as OperationalReportSchedule['cadence'],hourUtc:row.hourUtc,weekday:row.weekday,dayOfMonth:row.dayOfMonth,channel:row.channel as OperationalReportSchedule['channel'],recipient:row.recipient,enabled:row.enabled,createdBy:row.createdBy,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
 async createSavedReport(input:SavedOperationalReport){return this.savedReport(await this.db.orSavedReport.create({data:{id:input.id,companyId:input.companyId,ownerActorId:input.ownerActorId,name:input.name,reportKey:input.reportKey,filtersJson:input.filters as Prisma.InputJsonValue,visibility:input.visibility,active:input.active,createdAt:new Date(input.createdAt),updatedAt:new Date(input.updatedAt)}}));}
 async updateSavedReport(companyId:string,id:string,input:Pick<SavedOperationalReport,'name'|'filters'|'visibility'|'active'|'updatedAt'>){const existing=await this.db.orSavedReport.findFirst({where:{companyId,id}});if(!existing)throw new ContractValidationError('savedReportId','saved report was not found');return this.savedReport(await this.db.orSavedReport.update({where:{id},data:{name:input.name,filtersJson:input.filters as Prisma.InputJsonValue,visibility:input.visibility,active:input.active,updatedAt:new Date(input.updatedAt)}}));}
 async findSavedReport(companyId:string,id:string){const row=await this.db.orSavedReport.findFirst({where:{companyId,id}});return row?this.savedReport(row):undefined;}
 async listSavedReports(companyId:string){return(await this.db.orSavedReport.findMany({where:{companyId},orderBy:[{updatedAt:'desc'},{id:'asc'}]})).map(row=>this.savedReport(row));}
 async createSchedule(input:OperationalReportSchedule){try{return this.schedule(await this.db.orReportSchedule.create({data:{id:input.id,companyId:input.companyId,savedReportId:input.savedReportId,cadence:input.cadence,hourUtc:input.hourUtc,weekday:input.weekday,dayOfMonth:input.dayOfMonth,channel:input.channel,recipient:input.recipient,enabled:input.enabled,createdBy:input.createdBy,createdAt:new Date(input.createdAt),updatedAt:new Date(input.updatedAt)}}));}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2003')throw new ContractValidationError('savedReportId','saved report was not found');throw error;}}
 async updateSchedule(companyId:string,id:string,input:Pick<OperationalReportSchedule,'cadence'|'hourUtc'|'weekday'|'dayOfMonth'|'channel'|'recipient'|'enabled'|'updatedAt'>){const existing=await this.db.orReportSchedule.findFirst({where:{companyId,id}});if(!existing)throw new ContractValidationError('scheduleId','schedule was not found');return this.schedule(await this.db.orReportSchedule.update({where:{id},data:{cadence:input.cadence,hourUtc:input.hourUtc,weekday:input.weekday,dayOfMonth:input.dayOfMonth,channel:input.channel,recipient:input.recipient,enabled:input.enabled,updatedAt:new Date(input.updatedAt)}}));}
 async listSchedules(companyId:string,savedReportId?:string){return(await this.db.orReportSchedule.findMany({where:{companyId,...(savedReportId?{savedReportId}:{})},orderBy:[{updatedAt:'desc'},{id:'asc'}]})).map(row=>this.schedule(row));}
}
