import type { TreasuryRepository } from '../application/treasury.repository.js'; import type {BankLine,BankMatch,CashCount,Cheque,Transfer,Treasury,TreasuryPolicy,Voucher} from '../domain/treasury.js';
export class InMemoryTreasuryRepository implements TreasuryRepository {
 treasuriesValues:Treasury[]=[]; policies:TreasuryPolicy[]=[]; voucherValues:Voucher[]=[]; transferValues:Transfer[]=[]; cheques:Cheque[]=[]; counts:CashCount[]=[]; lines:BankLine[]=[]; matches:BankMatch[]=[];
 private put<T extends {companyId:string;id:string}>(a:T[],v:T){const i=a.findIndex(x=>x.companyId===v.companyId&&x.id===v.id);if(i<0)a.push(v);else a[i]=v}
 async treasury(c:string,id:string){return this.treasuriesValues.find(x=>x.companyId===c&&x.id===id)} async treasuries(c:string){return this.treasuriesValues.filter(x=>x.companyId===c)} async saveTreasury(v:Treasury){this.put(this.treasuriesValues,v)}
 async policy(c:string){return this.policies.find(x=>x.companyId===c)} async savePolicy(v:TreasuryPolicy){const i=this.policies.findIndex(x=>x.companyId===v.companyId);if(i<0)this.policies.push(v);else this.policies[i]=v}
 async voucher(c:string,id:string){return this.voucherValues.find(x=>x.companyId===c&&x.id===id)} async voucherBySource(c:string,t:string,id:string){return this.voucherValues.find(x=>x.companyId===c&&x.sourceType===t&&x.sourceId===id)} async vouchers(c:string,t?:string){return this.voucherValues.filter(x=>x.companyId===c&&(!t||x.treasuryId===t))} async saveVoucher(v:Voucher){this.put(this.voucherValues,v)}
 async transferBySource(c:string,t:string,id:string){return this.transferValues.find(x=>x.companyId===c&&x.sourceType===t&&x.sourceId===id)} async transfers(c:string){return this.transferValues.filter(x=>x.companyId===c)} async saveTransfer(v:Transfer){this.put(this.transferValues,v)}
 async saveCheque(v:Cheque){this.put(this.cheques,v)} async cheque(c:string,id:string){return this.cheques.find(x=>x.companyId===c&&x.id===id)} async saveCashCount(v:CashCount){this.put(this.counts,v)}
 async saveBankLine(v:BankLine){this.put(this.lines,v)} async bankLine(c:string,id:string){return this.lines.find(x=>x.companyId===c&&x.id===id)} async bankLines(c:string,t:string){return this.lines.filter(x=>x.companyId===c&&x.treasuryId===t)} async saveBankMatch(v:BankMatch){this.put(this.matches,v)} async bankMatch(c:string,l:string){return this.matches.find(x=>x.companyId===c&&x.lineId===l)}
}
