/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/consistent-type-imports */
import {PrismaClient,Prisma} from '@prisma/client'; import type {TreasuryRepository} from '../application/treasury.repository.js'; import type {BankLine,BankMatch,CashCount,Cheque,Transfer,Treasury,TreasuryPolicy,Voucher} from '../domain/treasury.js';
const dec=(v:unknown)=>String(v); const json=<T>(v:unknown)=>v as T;
export class PrismaTreasuryRepository implements TreasuryRepository {constructor(private readonly db:PrismaClient){}
 async treasury(companyId:string,id:string){const x=await this.db.treasuryTreasury.findUnique({where:{companyId_id:{companyId,id}}});return x?({...x,type:x.type as Treasury['type'],currency:x.currency as Treasury['currency']} as Treasury):undefined} async treasuries(companyId:string){return (await this.db.treasuryTreasury.findMany({where:{companyId}})) as Treasury[]}
 async saveTreasury(v:Treasury){await this.db.treasuryTreasury.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:v,update:{name:v.name,type:v.type,currency:v.currency,active:v.active,glAccountId:v.glAccountId}})} async policy(companyId:string){return ((await this.db.treasuryCompanyPolicy.findUnique({where:{companyId}})) as unknown as TreasuryPolicy)??undefined} async savePolicy(v:TreasuryPolicy){await this.db.treasuryCompanyPolicy.upsert({where:{companyId:v.companyId},create:v,update:{allowNegative:v.allowNegative}})}
 private V(x:any):Voucher{return {...x,amount:dec(x.amount),allocationIds:json<string[]>(x.allocationIds),carryingBaseAmount:x.carryingBaseAmount==null?undefined:dec(x.carryingBaseAmount),settlementBaseAmount:x.settlementBaseAmount==null?undefined:dec(x.settlementBaseAmount),realizedFx:x.realizedFx==null?undefined:dec(x.realizedFx)} as Voucher}
 async voucher(c:string,id:string){const x=await this.db.treasuryVoucher.findUnique({where:{companyId_id:{companyId:c,id}}});return x?this.V(x):undefined} async voucherBySource(c:string,t:string,id:string){const x=await this.db.treasuryVoucher.findUnique({where:{companyId_sourceType_sourceId:{companyId:c,sourceType:t,sourceId:id}}});return x?this.V(x):undefined} async vouchers(c:string,t?:string){return (await this.db.treasuryVoucher.findMany({where:{companyId:c,...(t?{treasuryId:t}:{})}})).map(x=>this.V(x))} async saveVoucher(v:Voucher){const data:any={...v,amount:new Prisma.Decimal(v.amount),allocationIds:v.allocationIds,carryingBaseAmount:v.carryingBaseAmount?new Prisma.Decimal(v.carryingBaseAmount):null,settlementBaseAmount:v.settlementBaseAmount?new Prisma.Decimal(v.settlementBaseAmount):null,realizedFx:v.realizedFx?new Prisma.Decimal(v.realizedFx):null};await this.db.treasuryVoucher.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:data,update:data})}
 private T(x:any):Transfer{return {...x,amount:dec(x.amount)} as Transfer} async transferBySource(c:string,t:string,id:string){const x=await this.db.treasuryTransfer.findUnique({where:{companyId_sourceType_sourceId:{companyId:c,sourceType:t,sourceId:id}}});return x?this.T(x):undefined} async transfers(c:string){return (await this.db.treasuryTransfer.findMany({where:{companyId:c}})).map(x=>this.T(x))} async saveTransfer(v:Transfer){const data:any={...v,amount:new Prisma.Decimal(v.amount)};await this.db.treasuryTransfer.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:data,update:data})}
 async saveCheque(v:Cheque){const data:any={...v,amount:new Prisma.Decimal(v.amount),history:v.history};await this.db.treasuryCheque.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:data,update:data})} async cheque(c:string,id:string){const x=await this.db.treasuryCheque.findUnique({where:{companyId_id:{companyId:c,id}}});return x?({...x,amount:dec(x.amount),history:json<Cheque['history']>(x.history)} as unknown as Cheque):undefined}
 async saveCashCount(v:CashCount){const data:any={...v,countedAmount:new Prisma.Decimal(v.countedAmount),bookAmount:new Prisma.Decimal(v.bookAmount),difference:new Prisma.Decimal(v.difference)};await this.db.treasuryCashCount.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:data,update:data})}
 private L(x:any):BankLine{return {...x,signedAmount:dec(x.signedAmount)} as BankLine} async saveBankLine(v:BankLine){const data:any={...v,signedAmount:new Prisma.Decimal(v.signedAmount)};await this.db.treasuryBankStatementLine.upsert({where:{companyId_id:{companyId:v.companyId,id:v.id}},create:data,update:data})} async bankLine(c:string,id:string){const x=await this.db.treasuryBankStatementLine.findUnique({where:{companyId_id:{companyId:c,id}}});return x?this.L(x):undefined} async bankLines(c:string,t:string){return (await this.db.treasuryBankStatementLine.findMany({where:{companyId:c,treasuryId:t}})).map(x=>this.L(x))}
 async saveBankMatch(v:BankMatch){await this.db.treasuryBankMatch.upsert({where:{companyId_lineId:{companyId:v.companyId,lineId:v.lineId}},create:v,update:v})}
 async bankMatch(c:string,l:string){const value=await this.db.treasuryBankMatch.findUnique({where:{companyId_lineId:{companyId:c,lineId:l}}});return value as unknown as BankMatch|undefined}
}
