import { createHash } from 'node:crypto';
import { ContractValidationError, decimalAmount, type CompanyId, type DecimalAmount } from '@elhafez/contracts';
import type { StandaloneServicesApplicationService } from '@elhafez/standalone-services';
import type { TourismContractInventoryApplicationService } from '@elhafez/tourism-contract-inventory';
export interface FulfillmentCase { id:string;companyId:CompanyId;branchId:string;serviceId:string;revision:number;quantity:DecimalAmount;status:'AWAITING_SUPPLIER'|'SUPPLIER_CONFIRMED'|'PARTIALLY_DELIVERED'|'DELIVERED';supplierId?:string;internalCoverage?:boolean;confirmedQuantity:DecimalAmount;deliveredQuantity:DecimalAmount;version:number }
export interface ConfirmationEvidence { id:string;caseId:string;actorId:string;at:string;quantity:DecimalAmount;supplierId?:string;referenceType:string;reference:string;fileId?:string;internalCoverage:boolean }
export interface DeliveryEvidence { id:string;caseId:string;actorId:string;at:string;quantity:DecimalAmount;unit:string;note:string;fileId?:string;correctsId?:string }
export interface FulfillmentRepository { get(companyId:CompanyId,branchId:string,serviceId:string):Promise<FulfillmentCase|null>;create(value:FulfillmentCase):Promise<void>;confirm(value:FulfillmentCase,expectedVersion:number,evidence:ConfirmationEvidence,key:string,payloadHash:string):Promise<void>;deliver(value:FulfillmentCase,expectedVersion:number,evidence:DeliveryEvidence,key:string,payloadHash:string):Promise<void>;receipt(companyId:CompanyId,key:string):Promise<{payloadHash:string;caseId:string}|null>;confirmations(caseId:string):Promise<ConfirmationEvidence[]>;deliveries(caseId:string):Promise<DeliveryEvidence[]> }
const required=(value:string,field:string)=>{if(!value?.trim())throw new ContractValidationError(field,'required');return value.trim()};
const units=(value:DecimalAmount)=>{const [w,f='']=decimalAmount(value).split('.');return BigInt(w!+f.padEnd(18,'0'))};
const amount=(value:bigint):DecimalAmount=>{const fraction=(value%10n**18n).toString().padStart(18,'0').replace(/0+$/,'');return decimalAmount(`${value/10n**18n}${fraction?`.${fraction}`:''}`)};
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export class ServiceFulfillmentApplicationService {
 constructor(private readonly repo:FulfillmentRepository,private readonly services:StandaloneServicesApplicationService,private readonly inventory:TourismContractInventoryApplicationService){}
 private async source(companyId:CompanyId,branchId:string,serviceId:string){const source=await this.services.getService(companyId,serviceId);if(source.service.branchId!==branchId||!['CONFIRMED','COMPLETED'].includes(source.service.status))throw new ContractValidationError('serviceId','confirmed service in this branch required');return source}
 async get(companyId:CompanyId,branchId:string,serviceId:string){const value=await this.repo.get(companyId,branchId,serviceId);return value?{case:value,confirmations:await this.repo.confirmations(value.id),deliveries:await this.repo.deliveries(value.id)}:null}
 async open(input:{companyId:CompanyId;branchId:string;serviceId:string}){const source=await this.source(input.companyId,input.branchId,input.serviceId);const prior=await this.repo.get(input.companyId,input.branchId,input.serviceId);if(prior){if(prior.revision!==source.revision.revision)throw new ContractValidationError('revision','fulfillment belongs to another revision');return prior}const value:FulfillmentCase={id:digest([input.companyId,input.serviceId,source.revision.revision]).slice(0,32),...input,revision:source.revision.revision,quantity:source.revision.quantity,status:'AWAITING_SUPPLIER',confirmedQuantity:decimalAmount('0'),deliveredQuantity:decimalAmount('0'),version:1};await this.repo.create(value);return value}
 async confirm(input:{companyId:CompanyId;branchId:string;serviceId:string;actorId:string;commandKey:string;quantity:DecimalAmount;at:string;referenceType:string;reference:string;supplierId?:string;fileId?:string;internalCoverage?:boolean}){
  const payloadHash=digest(input),prior=await this.repo.receipt(input.companyId,input.commandKey);if(prior){if(prior.payloadHash!==payloadHash)throw new ContractValidationError('commandKey','conflicting replay');return this.get(input.companyId,input.branchId,input.serviceId)}
  const source=await this.source(input.companyId,input.branchId,input.serviceId);
  if(!source.service.supplyPlanId)throw new ContractValidationError('plan','reviewed supply plan required');
  const plan=await this.inventory.getStandaloneSupplyPlan(input.companyId,source.service.supplyPlanId);
  if(!plan||plan.service.sourceId!==input.serviceId||plan.branchId!==input.branchId||plan.serviceRevision!==source.revision.revision)throw new ContractValidationError('plan','confirmed supply evidence missing');
  await this.open(input);const current=(await this.repo.get(input.companyId,input.branchId,input.serviceId))!;const quantity=decimalAmount(input.quantity);if(units(quantity)<=0n||units(current.confirmedQuantity)+units(quantity)>units(current.quantity))throw new ContractValidationError('quantity','exceeds service quantity');
  const confirmations=await this.repo.confirmations(current.id);
  const committed=confirmations.filter(item=>item.internalCoverage===!!input.internalCoverage && (input.internalCoverage||item.supplierId===input.supplierId)).reduce((sum,item)=>sum+units(item.quantity),0n);
  const capacity=input.internalCoverage?plan.lines.reduce((sum,line)=>sum+units(line.allocationQuantity),0n):plan.residuals.filter(item=>item.supplierId===input.supplierId).reduce((sum,item)=>sum+units(item.quantity),0n);
  if(committed+units(quantity)>capacity)throw new ContractValidationError('quantity','confirmation exceeds selected supply part');
  if(input.internalCoverage&&input.supplierId)throw new ContractValidationError('supplierId','internal coverage cannot carry an external supplier');
  if(!input.internalCoverage)required(input.supplierId??'','supplierId');required(input.referenceType,'referenceType');required(input.reference,'reference');if(Number.isNaN(Date.parse(input.at)))throw new ContractValidationError('at','invalid time');
  const evidence:ConfirmationEvidence={id:digest([current.id,input.commandKey]).slice(0,32),caseId:current.id,actorId:required(input.actorId,'actorId'),at:input.at,quantity,referenceType:input.referenceType,reference:input.reference,internalCoverage:!!input.internalCoverage,...(input.supplierId?{supplierId:input.supplierId}:{}),...(input.fileId?{fileId:input.fileId}:{})};
  const next={...current,version:current.version+1,status:'SUPPLIER_CONFIRMED' as const,confirmedQuantity:amount(units(current.confirmedQuantity)+units(quantity)),...(input.supplierId?{supplierId:input.supplierId}:{}),...(input.internalCoverage?{internalCoverage:true}:{})};await this.repo.confirm(next,current.version,evidence,input.commandKey,payloadHash);return this.get(input.companyId,input.branchId,input.serviceId)
 }
 async deliver(input:{companyId:CompanyId;branchId:string;serviceId:string;actorId:string;commandKey:string;quantity:DecimalAmount;at:string;unit:string;note:string;fileId?:string}){
  const payloadHash=digest(input),prior=await this.repo.receipt(input.companyId,input.commandKey);if(prior){if(prior.payloadHash!==payloadHash)throw new ContractValidationError('commandKey','conflicting replay');const value=await this.get(input.companyId,input.branchId,input.serviceId);if(value?.case.status==='DELIVERED')await this.complete(value.case,input.actorId);return value}
  await this.source(input.companyId,input.branchId,input.serviceId);const current=await this.repo.get(input.companyId,input.branchId,input.serviceId);if(!current)throw new ContractValidationError('confirmation','supplier/internal confirmation required');const quantity=decimalAmount(input.quantity),delivered=units(current.deliveredQuantity)+units(quantity);if(units(quantity)<=0n||delivered>units(current.confirmedQuantity)||delivered>units(current.quantity))throw new ContractValidationError('quantity','exceeds confirmed quantity');if(Number.isNaN(Date.parse(input.at)))throw new ContractValidationError('at','invalid time');
  const evidence:DeliveryEvidence={id:digest([current.id,input.commandKey]).slice(0,32),caseId:current.id,actorId:required(input.actorId,'actorId'),at:input.at,quantity,unit:required(input.unit,'unit'),note:required(input.note,'note'),...(input.fileId?{fileId:input.fileId}:{})};
  const next:FulfillmentCase={...current,version:current.version+1,status:delivered===units(current.quantity)?'DELIVERED':'PARTIALLY_DELIVERED',deliveredQuantity:amount(delivered)};await this.repo.deliver(next,current.version,evidence,input.commandKey,payloadHash);
  if(next.status==='DELIVERED')await this.complete(next,input.actorId);
  return this.get(input.companyId,input.branchId,input.serviceId)
 }
 private async complete(value:FulfillmentCase,actorId:string){await this.services.completeFromFulfillment({companyId:value.companyId,branchId:value.branchId,serviceId:value.serviceId,revision:value.revision,caseId:value.id,actorId,commandKey:`sf-completed:${value.id}`})}
 async cancellationBlockers(companyId:CompanyId,branchId:string,serviceId:string){const value=await this.repo.get(companyId,branchId,serviceId);return value&&units(value.deliveredQuantity)>0n?['SERVICE_DELIVERY_RECORDED']:[]}
}
