import { randomUUID } from 'node:crypto';
import { ContractValidationError, type ExecutionContext } from '@elhafez/contracts';
import { agentId, type AgentId } from '@elhafez/agent-management';
import { customerId, type CustomerId, type CustomerResolveResult } from '@elhafez/customer-management';
import type { CrmLeadsAccess } from './crm-leads-access.js';
import type { LeadAgentPort, LeadCustomerPort } from './crm-leads-dependencies.port.js';
import type { CrmLeadsRepository } from './crm-leads.repository.js';
import { currencyCode, exactDecimal, leadId, optionalText, requiredText, type CreateLeadInput, type Lead, type LeadHistory, type LeadHistoryKind, type LeadId, type LeadStatus, type UpdateLeadInput } from '../domain/lead.js';
import type{LeadConfiguration,LeadAssignmentRule,LeadScoringRule}from'../domain/lead-configuration.js';

export const CRM_LEAD_PERMISSIONS=Object.freeze({read:'crm.lead.read',manage:'crm.lead.manage',lifecycle:'crm.lead.lifecycle',convert:'crm.lead.convert',configure:'crm.lead.configure'});
export type LeadReviewCandidates = Extract<CustomerResolveResult,{status:'REVIEW_REQUIRED'}>['candidates'];
export type LeadConversionResult =
 | { readonly status:'CONVERTED'|'ALREADY_CONVERTED'; readonly customerId:CustomerId }
 | { readonly status:'REVIEW_REQUIRED'; readonly reason:'AMBIGUOUS_DUPLICATE'|'SUSPENDED_CUSTOMER'; readonly candidates?:LeadReviewCandidates; readonly customerId?:CustomerId };

const allowed:Readonly<Record<Exclude<LeadStatus,'LOST'|'QUOTED'|'WON'>,readonly LeadStatus[]>>=Object.freeze({NEW:['CONTACTED'],CONTACTED:['QUALIFIED'],QUALIFIED:[]});

export class CrmLeadsApplicationService {
 constructor(private readonly repository:CrmLeadsRepository,private readonly customers:LeadCustomerPort,private readonly agents:LeadAgentPort,private readonly access:CrmLeadsAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async branch(c:ExecutionContext){await this.access.requireBranch(c);}
 private async perm(c:ExecutionContext,p:string){await this.branch(c);await this.access.requirePermission(c,p);}
 async configuration(c:ExecutionContext){await this.perm(c,CRM_LEAD_PERMISSIONS.read);return this.repository.getConfiguration(c.companyId,c.branchId);}
 async configure(c:ExecutionContext,input:Omit<LeadConfiguration,'companyId'|'branchId'|'updatedAt'>){
  await this.perm(c,CRM_LEAD_PERMISSIONS.configure);
  if(!Number.isInteger(input.contactSlaMinutes)||input.contactSlaMinutes<0||input.contactSlaMinutes>525600)throw new ContractValidationError('contactSlaMinutes','must be 0..525600');
  const sourceCodes=new Set(input.sources.map(x=>requiredText(x.code,'source.code').toUpperCase()));if(sourceCodes.size!==input.sources.length)throw new ContractValidationError('sources','duplicate source code');
  const campaignIds=new Set(input.campaigns.map(x=>requiredText(x.id,'campaign.id')));if(campaignIds.size!==input.campaigns.length)throw new ContractValidationError('campaigns','duplicate campaign id');
  const stageKeys=new Set(input.pipelineStages.map(x=>requiredText(x.key,'pipelineStage.key')));if(stageKeys.size!==input.pipelineStages.length)throw new ContractValidationError('pipelineStages','duplicate stage key');
  for(const r of input.assignmentRules)this.validateAssignmentRule(r);for(const r of input.scoringRules)this.validateScoringRule(r);
  const value:LeadConfiguration={companyId:c.companyId,branchId:c.branchId,sources:input.sources.map(x=>({...x,code:x.code.trim().toUpperCase(),label:requiredText(x.label,'source.label')})),campaigns:input.campaigns.map(x=>({...x,id:x.id.trim(),name:requiredText(x.name,'campaign.name'),sourceCode:x.sourceCode?.trim().toUpperCase()||null})),pipelineStages:[...input.pipelineStages].map(x=>({...x,key:x.key.trim(),label:requiredText(x.label,'pipelineStage.label')})).sort((a,b)=>a.order-b.order),assignmentRules:input.assignmentRules.map(x=>({...x,id:x.id.trim(),sourceCode:x.sourceCode?.trim().toUpperCase()||null,requestedService:x.requestedService?.trim()||null,userIds:[...new Set(x.userIds.map(v=>requiredText(v,'assignment.userId')))]})),scoringRules:input.scoringRules.map(x=>({...x,id:x.id.trim(),value:x.value.trim()})),contactSlaMinutes:input.contactSlaMinutes,updatedAt:this.now().toISOString()};
  const saved=await this.repository.saveConfiguration(value);await this.access.audit(c,'lead.configuration.updated','lead-configuration',null,{sources:saved.sources.length,campaigns:saved.campaigns.length,stages:saved.pipelineStages.length});return saved;
 }
 private validateAssignmentRule(r:LeadAssignmentRule){requiredText(r.id,'assignment.id');if(!r.userIds.length)throw new ContractValidationError('assignment.userIds','at least one user is required');if(!Number.isInteger(r.nextIndex)||r.nextIndex<0)throw new ContractValidationError('assignment.nextIndex','must be non-negative integer');}
 private validateScoringRule(r:LeadScoringRule){requiredText(r.id,'scoring.id');if(!Number.isInteger(r.points)||r.points<-1000||r.points>1000)throw new ContractValidationError('scoring.points','must be integer -1000..1000');if(r.field==='EXPECTED_VALUE_MIN'&&(Number.isNaN(Number(r.value))||Number(r.value)<0))throw new ContractValidationError('scoring.value','invalid amount threshold');}
 private score(config:LeadConfiguration|null,input:{source:string;requestedService?:string|null;expectedValue?:string|null}){if(!config)return 0;let result=0;for(const r of config.scoringRules)if(r.active){if(r.field==='SOURCE'&&input.source.toUpperCase()===r.value.toUpperCase())result+=r.points;else if(r.field==='SERVICE'&&(input.requestedService??'').toLowerCase()===r.value.toLowerCase())result+=r.points;else if(r.field==='EXPECTED_VALUE_MIN'&&Number(input.expectedValue??0)>=Number(r.value))result+=r.points;}return result;}
 private stage(config:LeadConfiguration|null,status:LeadStatus){return config?.pipelineStages.filter(x=>x.active&&x.baseStatus===status).sort((a,b)=>a.order-b.order)[0]?.key??status;}
 private async commercialForCreate(c:ExecutionContext,input:CreateLeadInput,at:string){
  const config=await this.repository.getConfiguration(c.companyId,c.branchId),source=requiredText(input.source,'source').toUpperCase();
  if(config?.sources.some(x=>x.active)&&!config.sources.some(x=>x.active&&x.code===source))throw new ContractValidationError('source','lead source is not configured');
  const campaignId=input.campaignId?.trim()||null;if(campaignId&&!config?.campaigns.some(x=>x.id===campaignId&&x.active))throw new ContractValidationError('campaignId','campaign is not active');
  let responsible=optionalText(input.responsibleUserId);if(!responsible&&config){const index=config.assignmentRules.findIndex(r=>r.active&&(!r.sourceCode||r.sourceCode===source)&&(!r.requestedService||r.requestedService===(input.requestedService?.trim()||null)));if(index>=0){const rule=config.assignmentRules[index]!,pos=rule.nextIndex%rule.userIds.length;responsible=rule.userIds[pos]??null;const rules=config.assignmentRules.map((r,i)=>i===index?{...r,nextIndex:r.nextIndex+1}:r);await this.repository.saveConfiguration({...config,assignmentRules:rules,updatedAt:at});}}
  const expected=exactDecimal(input.expectedValue);return{source,campaignId,responsible,score:this.score(config,{source,requestedService:input.requestedService,expectedValue:expected}),tags:[...new Set((input.tags??[]).map(x=>x.trim()).filter(Boolean))],pipelineStage:this.stage(config,'NEW'),slaDueAt:config&&config.contactSlaMinutes>0?new Date(new Date(at).getTime()+config.contactSlaMinutes*60000).toISOString():null};
 }
 private async stageFor(c:ExecutionContext,status:LeadStatus){return this.stage(await this.repository.getConfiguration(c.companyId,c.branchId),status);}
 async create(c:ExecutionContext,input:CreateLeadInput):Promise<Lead>{
  await this.perm(c,CRM_LEAD_PERMISSIONS.manage);const referral=await this.activeAgent(c,input.referralAgentId),at=this.now().toISOString(),commercial=await this.commercialForCreate(c,input,at);const expected=exactDecimal(input.expectedValue),currency=currencyCode(input.currency,expected),seq=await this.repository.nextNumber(c.companyId,c.branchId);
  if(input.partyKind!=='PERSON'&&input.partyKind!=='ORGANIZATION')throw new ContractValidationError('partyKind','is invalid');
  const value:Lead={id:leadId(this.newId()),companyId:c.companyId,branchId:c.branchId,number:'LEAD-'+String(seq).padStart(6,'0'),partyKind:input.partyKind,displayName:requiredText(input.displayName,'displayName'),legalName:optionalText(input.legalName),phone:optionalText(input.phone),whatsappNumber:optionalText(input.whatsappNumber),email:optionalText(input.email)?.toLowerCase()??null,address:optionalText(input.address),nationalIdentity:optionalText(input.nationalIdentity),taxIdentity:optionalText(input.taxIdentity),source:commercial.source,campaignId:commercial.campaignId,requestedService:optionalText(input.requestedService),expectedValue:expected,currency,status:'NEW',responsibleUserId:commercial.responsible,referralAgentId:referral,tags:commercial.tags,pipelineStage:commercial.pipelineStage,score:commercial.score,slaDueAt:commercial.slaDueAt,notes:optionalText(input.notes),lostReason:null,preLostStatus:null,quotationReference:null,convertedCustomerId:null,createdAt:at,updatedAt:at};
  await this.repository.create(value,this.event(c,value,'CREATED',null,'NEW',null));if(referral)await this.agents.registerReferenceForIntegration(c,referral,'CRM_LEAD',value.id);await this.access.audit(c,'lead.created','lead',value.id,{number:value.number});return value;
 }
 async update(c:ExecutionContext,id:LeadId,input:UpdateLeadInput):Promise<Lead>{
  await this.perm(c,CRM_LEAD_PERMISSIONS.manage);const current=await this.require(c,id);if(current.status==='WON')throw new ContractValidationError('lead','won lead is immutable except historical reads');
  let referral=current.referralAgentId;if(input.referralAgentId!==undefined){const next=await this.activeAgent(c,input.referralAgentId);if(referral&&referral!==next)await this.agents.releaseReferenceForIntegration(c,agentId(referral),'CRM_LEAD',current.id);if(next&&next!==referral)await this.agents.registerReferenceForIntegration(c,next,'CRM_LEAD',current.id);referral=next;}
  const expected=input.expectedValue===undefined?current.expectedValue:exactDecimal(input.expectedValue),currency=input.expectedValue===undefined&&input.currency===undefined?current.currency:currencyCode(input.currency??current.currency,expected),config=await this.repository.getConfiguration(c.companyId,c.branchId),nextSource=input.source===undefined?current.source:requiredText(input.source,'source').toUpperCase(),campaignId=input.campaignId===undefined?(current.campaignId??null):optionalText(input.campaignId);if(config?.sources.some(x=>x.active)&&!config.sources.some(x=>x.active&&x.code===nextSource))throw new ContractValidationError('source','lead source is not configured');if(campaignId&&!config?.campaigns.some(x=>x.id===campaignId&&x.active))throw new ContractValidationError('campaignId','campaign is not active');
  const updated:Lead={...current,displayName:input.displayName===undefined?current.displayName:requiredText(input.displayName,'displayName'),legalName:input.legalName===undefined?current.legalName:optionalText(input.legalName),phone:input.phone===undefined?current.phone:optionalText(input.phone),whatsappNumber:input.whatsappNumber===undefined?current.whatsappNumber:optionalText(input.whatsappNumber),email:input.email===undefined?current.email:optionalText(input.email)?.toLowerCase()??null,address:input.address===undefined?current.address:optionalText(input.address),source:nextSource,campaignId,requestedService:input.requestedService===undefined?current.requestedService:optionalText(input.requestedService),expectedValue:expected,currency,responsibleUserId:input.responsibleUserId===undefined?current.responsibleUserId:optionalText(input.responsibleUserId),referralAgentId:referral,tags:input.tags===undefined?(current.tags??[]):[...new Set(input.tags.map(x=>x.trim()).filter(Boolean))],pipelineStage:input.pipelineStage===undefined?(current.pipelineStage??this.stage(config,current.status)):optionalText(input.pipelineStage),score:this.score(config,{source:nextSource,requestedService:input.requestedService===undefined?current.requestedService:optionalText(input.requestedService),expectedValue:expected}),notes:input.notes===undefined?current.notes:optionalText(input.notes),updatedAt:this.now().toISOString()};
  await this.repository.update(updated,this.event(c,updated,'UPDATED',current.status,current.status,null));await this.access.audit(c,'lead.updated','lead',id,{});return updated;
 }
 async get(c:ExecutionContext,id:LeadId):Promise<Lead>{await this.perm(c,CRM_LEAD_PERMISSIONS.read);return this.require(c,id);}
 async getForIntegration(c:ExecutionContext,id:LeadId):Promise<Lead>{await this.branch(c);return this.require(c,id);}
 async list(c:ExecutionContext,filter?:{status?:LeadStatus;query?:string;responsibleUserId?:string}){await this.perm(c,CRM_LEAD_PERMISSIONS.read);return this.repository.list(c.companyId,c.branchId,filter);}
 async history(c:ExecutionContext,id:LeadId){await this.perm(c,CRM_LEAD_PERMISSIONS.read);await this.require(c,id);return this.repository.history(c.companyId,c.branchId,id);}
 async advance(c:ExecutionContext,id:LeadId,to:Extract<LeadStatus,'CONTACTED'|'QUALIFIED'>):Promise<Lead>{await this.perm(c,CRM_LEAD_PERMISSIONS.lifecycle);const current=await this.require(c,id);if(current.status==='LOST'||current.status==='QUOTED'||current.status==='WON'||!allowed[current.status].includes(to))throw new ContractValidationError('status',`invalid lead transition ${current.status} -> ${to}`);return this.persistStatus(c,current,to,'STATUS_CHANGED',null);}
 async markQuoted(c:ExecutionContext,id:LeadId,externalQuotationReference:string):Promise<Lead>{await this.perm(c,CRM_LEAD_PERMISSIONS.lifecycle);const current=await this.require(c,id),ref=requiredText(externalQuotationReference,'quotationReference');if(current.status==='QUOTED'){if(current.quotationReference===ref)return current;throw new ContractValidationError('quotationReference','lead is already quoted with a different reference');}if(current.status!=='QUALIFIED')throw new ContractValidationError('status',`invalid lead transition ${current.status} -> QUOTED`);const updated={...current,status:'QUOTED' as const,pipelineStage:await this.stageFor(c,'QUOTED'),quotationReference:ref,lostReason:null,preLostStatus:null,updatedAt:this.now().toISOString()};await this.repository.update(updated,this.event(c,updated,'QUOTED',current.status,'QUOTED',ref));await this.access.audit(c,'lead.quoted','lead',id,{quotationReference:ref});return updated;}
 async lose(c:ExecutionContext,id:LeadId,reason:string):Promise<Lead>{await this.perm(c,CRM_LEAD_PERMISSIONS.lifecycle);const current=await this.require(c,id),why=requiredText(reason,'lostReason');if(current.status==='WON')throw new ContractValidationError('status','won lead cannot be lost');if(current.status==='LOST'){if(current.lostReason===why)return current;throw new ContractValidationError('status','lost lead must be reopened before changing the loss decision');}const updated={...current,status:'LOST' as const,pipelineStage:await this.stageFor(c,'LOST'),lostReason:why,preLostStatus:current.status as Exclude<LeadStatus,'LOST'>,updatedAt:this.now().toISOString()};await this.repository.update(updated,this.event(c,updated,'LOST',current.status,'LOST',why));await this.access.audit(c,'lead.lost','lead',id,{reason:why});return updated;}
 async reopen(c:ExecutionContext,id:LeadId):Promise<Lead>{await this.perm(c,CRM_LEAD_PERMISSIONS.lifecycle);const current=await this.require(c,id);if(current.status!=='LOST')throw new ContractValidationError('status','only a lost lead can be reopened');const restored=current.preLostStatus??'NEW';if(restored==='WON')throw new ContractValidationError('status','won lifecycle cannot be reopened');const updated={...current,status:restored,pipelineStage:await this.stageFor(c,restored),lostReason:null,preLostStatus:null,updatedAt:this.now().toISOString()};await this.repository.update(updated,this.event(c,updated,'REOPENED','LOST',restored,null));await this.access.audit(c,'lead.reopened','lead',id,{restoredStatus:restored});return updated;}
 async convertToCustomer(c:ExecutionContext,id:LeadId):Promise<LeadConversionResult>{
  await this.perm(c,CRM_LEAD_PERMISSIONS.convert);const current=await this.require(c,id);if(current.convertedCustomerId){const existingId=customerId(current.convertedCustomerId);await this.customers.requireActiveForIntegration(c,existingId);return{status:'ALREADY_CONVERTED',customerId:existingId};}if(current.status!=='QUOTED')throw new ContractValidationError('status','lead must be QUOTED before customer conversion');
  const resolved=await this.customers.resolveOrCreateForLead(c,{party:{kind:current.partyKind,displayName:current.displayName,...(current.legalName?{legalName:current.legalName}:{}),...(current.phone?{phone:current.phone}:{}),...(current.whatsappNumber?{whatsappNumber:current.whatsappNumber}:{}),...(current.email?{email:current.email}:{}),...(current.address?{address:current.address}:{}),...(current.nationalIdentity?{nationalIdentity:current.nationalIdentity}:{}),...(current.taxIdentity?{taxIdentity:current.taxIdentity}:{})},...(current.referralAgentId?{assignedAgentId:agentId(current.referralAgentId)}:{})});
  if(resolved.status==='REVIEW_REQUIRED')return{status:'REVIEW_REQUIRED',reason:'AMBIGUOUS_DUPLICATE',candidates:resolved.candidates};
  if(resolved.status==='EXISTING_SUSPENDED')return{status:'REVIEW_REQUIRED',reason:'SUSPENDED_CUSTOMER',customerId:resolved.value.customer.id};
  const customer=resolved.value.customer;await this.customers.registerReferenceForIntegration(c,customer.id,'CRM_LEAD',current.id);
  const updated={...current,status:'WON' as const,pipelineStage:await this.stageFor(c,'WON'),convertedCustomerId:customer.id,lostReason:null,preLostStatus:null,updatedAt:this.now().toISOString()};await this.repository.update(updated,this.event(c,updated,'CONVERTED','QUOTED','WON',customer.id));await this.access.audit(c,'lead.converted','lead',id,{customerId:customer.id});return{status:'CONVERTED',customerId:customer.id};
 }
 private async activeAgent(c:ExecutionContext,value:string|undefined|null):Promise<AgentId|null>{if(!value?.trim())return null;const id=agentId(value);await this.agents.requireActiveForIntegration(c,id);return id;}
 private async require(c:ExecutionContext,id:LeadId):Promise<Lead>{const value=await this.repository.find(c.companyId,c.branchId,id);if(!value)throw new ContractValidationError('leadId','lead was not found in this company/branch');return value;}
 private async persistStatus(c:ExecutionContext,current:Lead,to:LeadStatus,kind:LeadHistoryKind,detail:string|null){const updated={...current,status:to,pipelineStage:await this.stageFor(c,to),lostReason:null,preLostStatus:null,updatedAt:this.now().toISOString()};await this.repository.update(updated,this.event(c,updated,kind,current.status,to,detail));await this.access.audit(c,'lead.status_changed','lead',current.id,{from:current.status,to});return updated;}
 private event(c:ExecutionContext,lead:Lead,kind:LeadHistoryKind,fromStatus:LeadStatus|null,toStatus:LeadStatus|null,detail:string|null):LeadHistory{return{id:this.newId(),companyId:c.companyId,branchId:c.branchId,leadId:lead.id,kind,fromStatus,toStatus,detail,actorId:c.actorId,occurredAt:this.now().toISOString()};}
}
