CREATE TABLE "tci_service_inventory" (
 "id" TEXT NOT NULL, "company_id" TEXT NOT NULL, "contract_id" TEXT NOT NULL,
 "category" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "unit" TEXT NOT NULL,
 "service_start" TIMESTAMP(3) NOT NULL, "service_end" TIMESTAMP(3) NOT NULL,
 "capacity" DECIMAL(38,18) NOT NULL, "allocated_quantity" DECIMAL(38,18) NOT NULL,
 "available_quantity" DECIMAL(38,18) NOT NULL, "release_deadline" TIMESTAMP(3), "status" TEXT NOT NULL,
 CONSTRAINT "tci_service_inventory_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "tci_service_inventory_company_id_id_key" ON "tci_service_inventory"("company_id","id");
CREATE UNIQUE INDEX "tci_service_inventory_identity_key" ON "tci_service_inventory"("company_id","contract_id","category","name","service_start","service_end");
CREATE INDEX "tci_service_inventory_window_idx" ON "tci_service_inventory"("company_id","category","service_start","service_end","status");
ALTER TABLE "tci_service_inventory" ADD CONSTRAINT "tci_service_inventory_contract_fkey" FOREIGN KEY ("company_id","contract_id") REFERENCES "tci_contracts"("company_id","id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "hus_seasons" ("id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"branch_id" TEXT NOT NULL,"code" TEXT NOT NULL,"arabic_name" TEXT NOT NULL,"english_name" TEXT,"hijri_label" TEXT,"operating_start" DATE NOT NULL,"operating_end" DATE NOT NULL,"sales_start" DATE NOT NULL,"sales_end" DATE NOT NULL,"notes" TEXT,"status" TEXT NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"created_at" TIMESTAMP(3) NOT NULL,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "hus_seasons_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "hus_seasons_scope_id_key" ON "hus_seasons"("id","company_id","branch_id");
CREATE UNIQUE INDEX "hus_seasons_code_key" ON "hus_seasons"("company_id","branch_id","code");
CREATE INDEX "hus_seasons_status_idx" ON "hus_seasons"("company_id","branch_id","status","operating_start");
CREATE TABLE "hus_season_history" ("id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"branch_id" TEXT NOT NULL,"season_id" TEXT NOT NULL,"action" TEXT NOT NULL,"reason" TEXT,"actor_id" TEXT NOT NULL,"occurred_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "hus_season_history_pkey" PRIMARY KEY("id"));
CREATE INDEX "hus_season_history_idx" ON "hus_season_history"("company_id","branch_id","season_id","occurred_at");
ALTER TABLE "hus_season_history" ADD CONSTRAINT "hus_season_history_season_fkey" FOREIGN KEY("season_id","company_id","branch_id") REFERENCES "hus_seasons"("id","company_id","branch_id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "hup_programs" ("id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"branch_id" TEXT NOT NULL,"code" TEXT NOT NULL,"type" TEXT NOT NULL,"season_id" TEXT NOT NULL,"arabic_name" TEXT NOT NULL,"english_name" TEXT,"group_number" TEXT,"group_description" TEXT,"snapshot" JSONB NOT NULL,"temporary_hold_minutes" INTEGER NOT NULL,"minimum_deposit_policy" TEXT,"notes" TEXT,"operations_manager" TEXT,"group_leader" TEXT,"guide" TEXT,"contact" TEXT,"status" TEXT NOT NULL,"booking_open" BOOLEAN NOT NULL,"current_version" INTEGER NOT NULL,"current_version_id" TEXT NOT NULL,"departure_recorded_at" TIMESTAMP(3),"return_recorded_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "hup_programs_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "hup_programs_scope_id_key" ON "hup_programs"("id","company_id","branch_id");CREATE UNIQUE INDEX "hup_programs_code_key" ON "hup_programs"("company_id","branch_id","code");CREATE INDEX "hup_programs_status_idx" ON "hup_programs"("company_id","branch_id","status","type");CREATE INDEX "hup_programs_season_idx" ON "hup_programs"("company_id","branch_id","season_id");
CREATE TABLE "hup_program_versions" ("id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"branch_id" TEXT NOT NULL,"program_id" TEXT NOT NULL,"version" INTEGER NOT NULL,"snapshot" JSONB NOT NULL,"effective_at" TIMESTAMP(3) NOT NULL,"reason" TEXT NOT NULL,"actor_id" TEXT NOT NULL,"supersedes_id" TEXT,CONSTRAINT "hup_program_versions_pkey" PRIMARY KEY("id"));CREATE UNIQUE INDEX "hup_program_versions_number_key" ON "hup_program_versions"("company_id","branch_id","program_id","version");CREATE INDEX "hup_program_versions_effective_idx" ON "hup_program_versions"("company_id","branch_id","program_id","effective_at");ALTER TABLE "hup_program_versions" ADD CONSTRAINT "hup_program_versions_program_fkey" FOREIGN KEY("program_id","company_id","branch_id") REFERENCES "hup_programs"("id","company_id","branch_id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "hup_program_history" ("id" TEXT NOT NULL,"company_id" TEXT NOT NULL,"branch_id" TEXT NOT NULL,"program_id" TEXT NOT NULL,"action" TEXT NOT NULL,"reason" TEXT,"actor_id" TEXT NOT NULL,"occurred_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "hup_program_history_pkey" PRIMARY KEY("id"));CREATE INDEX "hup_program_history_idx" ON "hup_program_history"("company_id","branch_id","program_id","occurred_at");ALTER TABLE "hup_program_history" ADD CONSTRAINT "hup_program_history_program_fkey" FOREIGN KEY("program_id","company_id","branch_id") REFERENCES "hup_programs"("id","company_id","branch_id") ON DELETE RESTRICT ON UPDATE CASCADE;
