import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import type{CustomerServiceAccess,CustomerServiceCustomerPort}from'./customer-service.ports.js';import type{CustomerServiceRepository}from'./customer-service.repository.js';import{isoDateTime,required,type ServiceCase,type ServiceCaseCategory,type ServiceCaseHistory,type ServiceCaseNote,type ServiceCasePriority,type ServiceCaseStatus}from'../domain/customer-service.js';
export const CUSTOMER_SERVICE_PERMISSIONS=Object.freeze({read:'crm.service.read',manage:'crm.service.manage',assign:'crm.service.assign',resolve:'crm.service.resolve'});
const allowed:Record<ServiceCaseStatus,readonly ServiceCaseStatus[]>={OPEN:['IN_PROGRESS','WAITING_CUSTOMER','RESOLVED'],IN_PROGRESS:['WAITING_CUSTOMER','RESOLVED'],WAITING_CUSTOMER:['IN_PROGRESS','RESOLVED'],RESOLVED:['IN_PROGRESS','CLOSED'],CLOSED:[]};
export class CustomerServiceApplicationService{
 constructor(private readonly repo:CustomerServiceRepository,private readonly customers:CustomerServiceCustomerPort,private readonly access:CustomerServiceAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async perm(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p)}
 private h(c:ExecutionContext,caseId:string,action:string,detail:string|null=null):ServiceCaseHistory{return{id:this.newId(),companyId:c.companyId,branchId:c.branchId,caseId,action,actorId:c.actorId,detail,occurredAt:this.now().toISOString()}}
 private async req(c:ExecutionContext,id:string){const v=await this.repo.get(c.companyId,c.branchId,id);if(!v)throw new ContractValidationError('caseId','service case was not found');return v}
 async create(c:ExecutionContext,input:{customerId:string;category:ServiceCaseCategory;priority?:ServiceCasePriority;subject:string;description:string;assigneeUserId?:string;slaDueAt?:string}){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.manage);const customerId=required(input.customerId,'customerId');await this.customers.requireActive(c,customerId);const now=this.now().toISOString(),seq=await this.repo.nextNumber(c.companyId,c.branchId),value:ServiceCase={id:this.newId(),companyId:c.companyId,branchId:c.branchId,number:'CASE-'+String(seq).padStart(6,'0'),customerId,category:input.category,priority:input.priority??'NORMAL',subject:required(input.subject,'subject'),description:required(input.description,'description'),status:'OPEN',assigneeUserId:input.assigneeUserId?.trim()||null,slaDueAt:isoDateTime(input.slaDueAt,'slaDueAt'),resolvedAt:null,closedAt:null,createdAt:now,updatedAt:now};const out=await this.repo.create(value,this.h(c,value.id,'CREATED'));await this.access.audit(c,'customer-service.case.created',out.id,{number:out.number});return out}
 async list(c:ExecutionContext,status?:ServiceCaseStatus){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.read);return this.repo.list(c.companyId,c.branchId,status)}
 async get(c:ExecutionContext,id:string){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.read);return this.req(c,id)}
 async assign(c:ExecutionContext,id:string,userId:string|null){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.assign);const old=await this.req(c,id);if(old.status==='CLOSED')throw new ContractValidationError('status','closed case is immutable');const value={...old,assigneeUserId:userId?.trim()||null,updatedAt:this.now().toISOString()};return this.repo.save(value,this.h(c,id,'ASSIGNED',value.assigneeUserId))}
 async transition(c:ExecutionContext,id:string,status:ServiceCaseStatus,detail?:string){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.resolve);const old=await this.req(c,id);if(old.status===status)return old;if(!allowed[old.status].includes(status))throw new ContractValidationError('status',old.status+' cannot transition to '+status);const at=this.now().toISOString(),value:ServiceCase={...old,status,resolvedAt:status==='RESOLVED'?at:status==='IN_PROGRESS'&&old.status==='RESOLVED'?null:old.resolvedAt,closedAt:status==='CLOSED'?at:old.closedAt,updatedAt:at};const out=await this.repo.save(value,this.h(c,id,'STATUS_'+status,detail?.trim()||null));await this.access.audit(c,'customer-service.case.status',id,{from:old.status,to:status});return out}
 async addNote(c:ExecutionContext,id:string,input:{body:string;visibility?:'INTERNAL'|'CUSTOMER'}){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.manage);const current=await this.req(c,id);if(current.status==='CLOSED')throw new ContractValidationError('status','closed case cannot receive notes');const value:ServiceCaseNote={id:this.newId(),companyId:c.companyId,branchId:c.branchId,caseId:id,authorId:c.actorId,visibility:input.visibility??'INTERNAL',body:required(input.body,'body'),createdAt:this.now().toISOString()};return this.repo.addNote(value)}
 async notes(c:ExecutionContext,id:string){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.read);await this.req(c,id);return this.repo.notes(c.companyId,c.branchId,id)}
 async history(c:ExecutionContext,id:string){await this.perm(c,CUSTOMER_SERVICE_PERMISSIONS.read);await this.req(c,id);return this.repo.history(c.companyId,c.branchId,id)}
}
