import{Prisma,type PrismaClient}from'@prisma/client';
import{ContractValidationError,type BranchId,type CompanyId}from'@elhafez/contracts';
import type{ProcurementSourcingRepository}from'../application/procurement-sourcing.repository.js';
import type{PurchaseRequisition,RequestForQuotation,SourcingAward,SupplierBid}from'../domain/procurement-sourcing.js';

type ReqRow=Prisma.PsRequisitionGetPayload<{include:{lines:true}}>;
type RfqRow=Prisma.PsRfqGetPayload<{include:{suppliers:true}}>;
type BidRow=Prisma.PsSupplierBidGetPayload<{include:{lines:true}}>;
type AwardRow=Prisma.PsAwardGetPayload<Record<string,never>>;

const date=(value:Date|null)=>value?value.toISOString().slice(0,10):null;
const iso=(value:string|null)=>value?new Date(value+'T00:00:00.000Z'):null;
function mapReq(row:ReqRow):PurchaseRequisition{return{id:row.id,companyId:row.companyId as CompanyId,branchId:row.branchId as BranchId,number:row.number,status:row.status as PurchaseRequisition['status'],requestedBy:row.requestedBy,needByDate:date(row.needByDate),currency:row.currency,notes:row.notes,approvedBy:row.approvedBy,approvedAt:row.approvedAt?.toISOString()??null,approvalReason:row.approvalReason,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString(),lines:row.lines.map(line=>({id:line.id,requisitionId:line.requisitionId,itemReference:line.itemReference,description:line.description,quantity:String(line.quantity) as PurchaseRequisition['lines'][number]['quantity'],targetUnitPrice:line.targetUnitPrice===null?null:String(line.targetUnitPrice) as PurchaseRequisition['lines'][number]['targetUnitPrice'],requiredDate:date(line.requiredDate)}))};}
function mapRfq(row:RfqRow):RequestForQuotation{return{id:row.id,companyId:row.companyId as CompanyId,branchId:row.branchId as BranchId,requisitionId:row.requisitionId,number:row.number,status:row.status as RequestForQuotation['status'],responseDeadline:date(row.responseDeadline)!,notes:row.notes,createdBy:row.createdBy,createdAt:row.createdAt.toISOString(),sentAt:row.sentAt?.toISOString()??null,closedAt:row.closedAt?.toISOString()??null,supplierPartyIds:row.suppliers.map(value=>value.supplierPartyId).sort()};}
function mapBid(row:BidRow):SupplierBid{return{id:row.id,companyId:row.companyId as CompanyId,branchId:row.branchId as BranchId,rfqId:row.rfqId,supplierPartyId:row.supplierPartyId,currency:row.currency,validUntil:date(row.validUntil),deliveryDate:date(row.deliveryDate),terms:row.terms,status:row.status as SupplierBid['status'],submittedAt:row.submittedAt.toISOString(),lines:row.lines.map(line=>({id:line.id,bidId:line.bidId,requisitionLineId:line.requisitionLineId,quantity:String(line.quantity) as SupplierBid['lines'][number]['quantity'],unitPrice:String(line.unitPrice) as SupplierBid['lines'][number]['unitPrice'],taxCode:line.taxCode}))};}
function mapAward(row:AwardRow):SourcingAward{return{id:row.id,companyId:row.companyId as CompanyId,branchId:row.branchId as BranchId,requisitionId:row.requisitionId,rfqId:row.rfqId,bidId:row.bidId,supplierPartyId:row.supplierPartyId,reason:row.reason,awardedBy:row.awardedBy,awardedAt:row.awardedAt.toISOString(),purchaseOrderId:row.purchaseOrderId};}
function reqScalar(v:PurchaseRequisition){return{number:v.number,status:v.status,requestedBy:v.requestedBy,needByDate:iso(v.needByDate),currency:v.currency,notes:v.notes,approvedBy:v.approvedBy,approvedAt:v.approvedAt?new Date(v.approvedAt):null,approvalReason:v.approvalReason,createdAt:new Date(v.createdAt),updatedAt:new Date(v.updatedAt)};}
function reqLines(v:PurchaseRequisition){return v.lines.map(line=>({id:line.id,companyId:v.companyId,branchId:v.branchId,requisitionId:v.id,itemReference:line.itemReference,description:line.description,quantity:line.quantity,targetUnitPrice:line.targetUnitPrice,requiredDate:iso(line.requiredDate)}));}
function rfqScalar(v:RequestForQuotation){return{requisitionId:v.requisitionId,number:v.number,status:v.status,responseDeadline:iso(v.responseDeadline)!,notes:v.notes,createdBy:v.createdBy,createdAt:new Date(v.createdAt),sentAt:v.sentAt?new Date(v.sentAt):null,closedAt:v.closedAt?new Date(v.closedAt):null};}
function bidScalar(v:SupplierBid){return{rfqId:v.rfqId,supplierPartyId:v.supplierPartyId,currency:v.currency,validUntil:iso(v.validUntil),deliveryDate:iso(v.deliveryDate),terms:v.terms,status:v.status,submittedAt:new Date(v.submittedAt)};}
function bidLines(v:SupplierBid){return v.lines.map(line=>({id:line.id,companyId:v.companyId,branchId:v.branchId,bidId:v.id,requisitionLineId:line.requisitionLineId,quantity:line.quantity,unitPrice:line.unitPrice,taxCode:line.taxCode}));}
function awardData(v:SourcingAward){return{id:v.id,companyId:v.companyId,branchId:v.branchId,requisitionId:v.requisitionId,rfqId:v.rfqId,bidId:v.bidId,supplierPartyId:v.supplierPartyId,reason:v.reason,awardedBy:v.awardedBy,awardedAt:new Date(v.awardedAt),purchaseOrderId:v.purchaseOrderId};}

export class PrismaProcurementSourcingRepository implements ProcurementSourcingRepository{
 constructor(private readonly db:PrismaClient){}
 async nextNumber(c:CompanyId,b:BranchId,kind:'PR'|'RFQ'){const row=await this.db.psNumberCounter.upsert({where:{companyId_branchId_kind:{companyId:c,branchId:b,kind}},create:{companyId:c,branchId:b,kind,nextValue:1},update:{nextValue:{increment:1}}});return row.nextValue;}
 async createRequisition(v:PurchaseRequisition){const row=await this.db.psRequisition.create({data:{id:v.id,companyId:v.companyId,branchId:v.branchId,...reqScalar(v),lines:{create:reqLines(v)}},include:{lines:true}});return mapReq(row);}
 async updateRequisition(v:PurchaseRequisition){await this.db.$transaction(async tx=>{const found=await tx.psRequisition.findUnique({where:{companyId_branchId_id:{companyId:v.companyId,branchId:v.branchId,id:v.id}}});if(!found)throw new ContractValidationError('requisitionId','was not found');await tx.psRequisitionLine.deleteMany({where:{companyId:v.companyId,branchId:v.branchId,requisitionId:v.id}});await tx.psRequisition.update({where:{id:v.id},data:reqScalar(v)});if(v.lines.length)await tx.psRequisitionLine.createMany({data:reqLines(v)});});return(await this.findRequisition(v.companyId,v.branchId,v.id))!;}
 async findRequisition(c:CompanyId,b:BranchId,id:string){const row=await this.db.psRequisition.findUnique({where:{companyId_branchId_id:{companyId:c,branchId:b,id}},include:{lines:{orderBy:{id:'asc'}}}});return row?mapReq(row):undefined;}
 async listRequisitions(c:CompanyId,b:BranchId){return(await this.db.psRequisition.findMany({where:{companyId:c,branchId:b},include:{lines:{orderBy:{id:'asc'}}},orderBy:[{createdAt:'desc'},{id:'asc'}]})).map(mapReq);}
 async createRfq(v:RequestForQuotation,requisition:PurchaseRequisition){await this.db.$transaction(async tx=>{await tx.psRequisition.update({where:{id:requisition.id},data:reqScalar(requisition)});await tx.psRfq.create({data:{id:v.id,companyId:v.companyId,branchId:v.branchId,...rfqScalar(v),suppliers:{create:v.supplierPartyIds.map(supplierPartyId=>({companyId:v.companyId,branchId:v.branchId,supplierPartyId}))}}});});return(await this.findRfq(v.companyId,v.branchId,v.id))!;}
 async updateRfq(v:RequestForQuotation){await this.db.$transaction(async tx=>{const found=await tx.psRfq.findUnique({where:{companyId_branchId_id:{companyId:v.companyId,branchId:v.branchId,id:v.id}}});if(!found)throw new ContractValidationError('rfqId','was not found');await tx.psRfqSupplier.deleteMany({where:{companyId:v.companyId,branchId:v.branchId,rfqId:v.id}});await tx.psRfq.update({where:{id:v.id},data:rfqScalar(v)});if(v.supplierPartyIds.length)await tx.psRfqSupplier.createMany({data:v.supplierPartyIds.map(supplierPartyId=>({companyId:v.companyId,branchId:v.branchId,rfqId:v.id,supplierPartyId}))});});return(await this.findRfq(v.companyId,v.branchId,v.id))!;}
 async findRfq(c:CompanyId,b:BranchId,id:string){const row=await this.db.psRfq.findUnique({where:{companyId_branchId_id:{companyId:c,branchId:b,id}},include:{suppliers:true}});return row?mapRfq(row):undefined;}
 async listRfqs(c:CompanyId,b:BranchId){return(await this.db.psRfq.findMany({where:{companyId:c,branchId:b},include:{suppliers:true},orderBy:[{createdAt:'desc'},{id:'asc'}]})).map(mapRfq);}
 async saveBid(v:SupplierBid){await this.db.$transaction(async tx=>{await tx.psSupplierBid.upsert({where:{id:v.id},create:{id:v.id,companyId:v.companyId,branchId:v.branchId,...bidScalar(v)},update:bidScalar(v)});await tx.psSupplierBidLine.deleteMany({where:{companyId:v.companyId,branchId:v.branchId,bidId:v.id}});if(v.lines.length)await tx.psSupplierBidLine.createMany({data:bidLines(v)});});return(await this.findBid(v.companyId,v.branchId,v.id))!;}
 async findBid(c:CompanyId,b:BranchId,id:string){const row=await this.db.psSupplierBid.findUnique({where:{companyId_branchId_id:{companyId:c,branchId:b,id}},include:{lines:{orderBy:{id:'asc'}}}});return row?mapBid(row):undefined;}
 async listBids(c:CompanyId,b:BranchId,rfqId:string){return(await this.db.psSupplierBid.findMany({where:{companyId:c,branchId:b,rfqId},include:{lines:{orderBy:{id:'asc'}}},orderBy:[{submittedAt:'asc'},{id:'asc'}]})).map(mapBid);}
 async commitAward(input:{award:SourcingAward;requisition:PurchaseRequisition;rfq:RequestForQuotation;bids:readonly SupplierBid[]}){const prior=await this.findAwardByRfq(input.award.companyId,input.award.branchId,input.award.rfqId);if(prior){if(prior.bidId===input.award.bidId)return prior;throw new ContractValidationError('award','RFQ already has an award');}try{await this.db.$transaction(async tx=>{await tx.psRequisition.update({where:{id:input.requisition.id},data:reqScalar(input.requisition)});await tx.psRfq.update({where:{id:input.rfq.id},data:rfqScalar(input.rfq)});for(const bid of input.bids)await tx.psSupplierBid.update({where:{id:bid.id},data:bidScalar(bid)});await tx.psAward.create({data:awardData(input.award)});});return input.award;}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const found=await this.findAwardByRfq(input.award.companyId,input.award.branchId,input.award.rfqId);if(found?.bidId===input.award.bidId)return found;}throw error;}}
 async updateAward(v:SourcingAward){const found=await this.db.psAward.findUnique({where:{companyId_branchId_id:{companyId:v.companyId,branchId:v.branchId,id:v.id}}});if(!found)throw new ContractValidationError('awardId','was not found');return mapAward(await this.db.psAward.update({where:{id:v.id},data:{purchaseOrderId:v.purchaseOrderId}}));}
 async findAward(c:CompanyId,b:BranchId,id:string){const row=await this.db.psAward.findUnique({where:{companyId_branchId_id:{companyId:c,branchId:b,id}}});return row?mapAward(row):undefined;}
 async findAwardByRfq(c:CompanyId,b:BranchId,rfqId:string){const row=await this.db.psAward.findUnique({where:{companyId_branchId_rfqId:{companyId:c,branchId:b,rfqId}}});return row?mapAward(row):undefined;}
 async listAwards(c:CompanyId,b:BranchId){return(await this.db.psAward.findMany({where:{companyId:c,branchId:b},orderBy:[{awardedAt:'desc'},{id:'asc'}]})).map(mapAward);}
}
