import { randomUUID } from 'node:crypto';
import ExcelJS from 'exceljs';
export type ExchangeStatus='UPLOADED'|'VALIDATED'|'READY'|'PROCESSING'|'COMPLETED'|'COMPLETED_WITH_ERRORS'|'FAILED';
export interface ExchangeRow { readonly rowNumber:number; readonly source:Readonly<Record<string,string>>; outcome:'PENDING'|'IMPORTED'|'DUPLICATE'|'FAILED'; error?:string }
export interface ExchangeJob { readonly id:string;readonly companyId:string;readonly branchId:string|null;readonly direction:'IMPORT'|'EXPORT';status:ExchangeStatus;readonly fileName:string;readonly format:'CSV'|'XLSX'|'GENERATED';readonly mapping:Readonly<Record<string,string>>;readonly idempotencyKey:string;readonly rows:ExchangeRow[];resultKey?:string;readonly createdAt:Date;updatedAt:Date }
export interface ImportTarget { importRow(input:{companyId:string;branchId:string|null;values:Readonly<Record<string,string>>;idempotencyKey:string}):Promise<'IMPORTED'|'DUPLICATE'> }
export interface ExportSource { read(input:{companyId:string;branchId:string|null}):Promise<ReadonlyArray<Readonly<Record<string,string>>>> }
export interface ExportStorage { write(input:{jobId:string;format:'CSV'|'XLSX';rows:ReadonlyArray<Readonly<Record<string,string>>>}):Promise<string> }
export interface TabularParser { readonly format:'CSV'|'XLSX'; parse(content:Uint8Array):Promise<ReadonlyArray<Readonly<Record<string,string>>>> }
export class CsvParser implements TabularParser { readonly format='CSV' as const;async parse(content:Uint8Array){const text=new TextDecoder().decode(content).replace(/^\uFEFF/,'');const records=parseCsv(text);if(!records.length)return[];const headers=records[0];if(!headers) return [];const rows=records.slice(1);if(headers.some(x=>!x.trim()))throw new DataExchangeError('CSV headers are required');return rows.filter(row=>row.some(Boolean)).map(row=>Object.fromEntries(headers.map((header,index)=>[header.trim(),row[index]??''])))} }
/** Production XLSX parser backed by ExcelJS; formulas are imported using their cached result. */
export class XlsxParser implements TabularParser {readonly format='XLSX' as const;async parse(content:Uint8Array){const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(Buffer.from(content));const worksheet=workbook.worksheets[0];if(!worksheet)throw new DataExchangeError('XLSX workbook has no worksheet');const values:string[][]=[];worksheet.eachRow({includeEmpty:false},(row:ExcelJS.Row)=>{const cells:string[]=[];for(let column=1;column<=row.cellCount;column++){const value=row.getCell(column).value;cells.push(xlsxCell(value))}values.push(cells)});const [headers,...rows]=values;if(!headers?.length||headers.some(header=>!header.trim()))throw new DataExchangeError('XLSX headers are required');return rows.filter(row=>row.some(Boolean)).map(row=>Object.fromEntries(headers.map((header,index)=>[header.trim(),row[index]??''])))} }
function xlsxCell(value:ExcelJS.CellValue):string {if(value===null||value===undefined)return'';if(value instanceof Date)return value.toISOString();if(typeof value==='object'){if('result'in value)return xlsxCell(value.result??'');if('text'in value)return value.text;if('richText'in value)return value.richText.map((part:ExcelJS.RichText)=>part.text).join('');if('error'in value)return value.error}return String(value)}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(cell);cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=char}if(quoted)throw new DataExchangeError('CSV contains an unterminated quoted field');if(cell||row.length){row.push(cell);rows.push(row)}return rows}
export class DataExchangeError extends Error{}
export interface DataExchangeRepository { save(job:ExchangeJob):Promise<void>; find(companyId:string,id:string):Promise<ExchangeJob|undefined>; findByKey(companyId:string,key:string):Promise<ExchangeJob|undefined>; list(companyId:string):Promise<readonly ExchangeJob[]> }
export class DataExchangeApplicationService {
 constructor(private readonly repository:DataExchangeRepository,private readonly parsers:readonly TabularParser[]=[new CsvParser()]){}
 async ingest(input:{companyId:string;branchId?:string;fileName:string;format:'CSV'|'XLSX';content:Uint8Array;mapping:Readonly<Record<string,string>>;idempotencyKey:string}){const parser=this.parsers.find(x=>x.format===input.format);if(!parser)throw new DataExchangeError(`${input.format} parser is unavailable`);return this.upload({...input,rows:await parser.parse(input.content)})}
 async upload(input:{companyId:string;branchId?:string;fileName:string;format:'CSV'|'XLSX';rows:ReadonlyArray<Readonly<Record<string,string>>>;mapping:Readonly<Record<string,string>>;idempotencyKey:string}){if(!input.fileName.trim()||!input.idempotencyKey.trim())throw new DataExchangeError('source and idempotency key are required');const prior=await this.repository.findByKey(input.companyId,input.idempotencyKey);if(prior)return prior;const now=new Date();const job:ExchangeJob={id:randomUUID(),companyId:input.companyId,branchId:input.branchId??null,direction:'IMPORT',status:'UPLOADED',fileName:input.fileName,format:input.format,mapping:{...input.mapping},idempotencyKey:input.idempotencyKey,rows:input.rows.map((source,rowNumber)=>({rowNumber:rowNumber+1,source:{...source},outcome:'PENDING'})),createdAt:now,updatedAt:now};await this.repository.save(job);return job}
 async preview(companyId:string,id:string,required:readonly string[]){const job=await this.require(companyId,id);for(const row of job.rows){const missing=required.find(field=>!row.source[field]?.trim());if(missing){row.outcome='FAILED';row.error=`Missing ${missing}`}else if(row.outcome==='FAILED'&&row.error?.startsWith('Missing ')){row.outcome='PENDING';delete row.error}}job.status=job.rows.some(x=>x.outcome==='FAILED')?'VALIDATED':'READY';job.updatedAt=new Date();await this.repository.save(job);return job}
 async execute(companyId:string,id:string,target:ImportTarget){const job=await this.require(companyId,id);if(!['READY','VALIDATED','COMPLETED_WITH_ERRORS','FAILED'].includes(job.status))throw new DataExchangeError('job is not executable');job.status='PROCESSING';await this.repository.save(job);for(const row of job.rows){if(row.outcome==='IMPORTED'||row.outcome==='DUPLICATE'||(row.outcome==='FAILED'&&row.error?.startsWith('Missing ')))continue;try{row.outcome=await target.importRow({companyId:job.companyId,branchId:job.branchId,values:Object.fromEntries(Object.entries(job.mapping).map(([source,targetField])=>[targetField,row.source[source]??''])),idempotencyKey:`${job.id}:${row.rowNumber}`});delete row.error}catch(error){row.outcome='FAILED';row.error=error instanceof Error?error.message:'Unknown row failure'}await this.repository.save(job)}job.status=job.rows.some(x=>x.outcome==='FAILED')?'COMPLETED_WITH_ERRORS':'COMPLETED';job.updatedAt=new Date();await this.repository.save(job);return job}
 async createExport(input:{companyId:string;branchId?:string;fileName:string;format:'CSV'|'XLSX';idempotencyKey:string},source:ExportSource,storage:ExportStorage){const prior=await this.repository.findByKey(input.companyId,input.idempotencyKey);if(prior)return prior;const now=new Date();const job:ExchangeJob={id:randomUUID(),companyId:input.companyId,branchId:input.branchId??null,direction:'EXPORT',status:'PROCESSING',fileName:input.fileName,format:input.format,mapping:{},idempotencyKey:input.idempotencyKey,rows:[],createdAt:now,updatedAt:now};await this.repository.save(job);try{job.resultKey=await storage.write({jobId:job.id,format:input.format,rows:await source.read({companyId:job.companyId,branchId:job.branchId})});job.status='COMPLETED'}catch{job.status='FAILED'}job.updatedAt=new Date();await this.repository.save(job);return job}
 async get(companyId:string,id:string){return this.require(companyId,id)} async list(companyId:string){return this.repository.list(companyId)} private async require(companyId:string,id:string){const job=await this.repository.find(companyId,id);if(!job)throw new DataExchangeError('job not found');return job}
}
export class InMemoryDataExchangeRepository implements DataExchangeRepository { private readonly jobs=new Map<string,ExchangeJob>();async save(job:ExchangeJob){this.jobs.set(job.id,structuredClone(job))}async find(companyId:string,id:string){const x=this.jobs.get(id);return x?.companyId===companyId?structuredClone(x):undefined}async findByKey(companyId:string,key:string){const x=[...this.jobs.values()].find(x=>x.companyId===companyId&&x.idempotencyKey===key);return x&&structuredClone(x)}async list(companyId:string){return [...this.jobs.values()].filter(x=>x.companyId===companyId).map(x=>structuredClone(x))} }
