import { randomUUID } from 'node:crypto';
export type ExchangeStatus='UPLOADED'|'VALIDATED'|'READY'|'PROCESSING'|'COMPLETED'|'COMPLETED_WITH_ERRORS'|'FAILED';
export interface ExchangeRow { readonly rowNumber:number; readonly source:Readonly<Record<string,string>>; outcome:'PENDING'|'IMPORTED'|'DUPLICATE'|'FAILED'; error?:string }
export interface ExchangeJob { readonly id:string;readonly companyId:string;readonly branchId:string|null;readonly direction:'IMPORT'|'EXPORT';status:ExchangeStatus;readonly fileName:string;readonly format:'CSV'|'XLSX'|'GENERATED';readonly mapping:Readonly<Record<string,string>>;readonly idempotencyKey:string;readonly rows:ExchangeRow[];resultKey?:string;readonly createdAt:Date;updatedAt:Date }
export interface ImportTarget { importRow(input:{companyId:string;branchId:string|null;values:Readonly<Record<string,string>>;idempotencyKey:string}):Promise<'IMPORTED'|'DUPLICATE'> }
export class DataExchangeError extends Error{}
/** Durable repositories implement this contract; the application service never writes a target owner's tables. */
export interface DataExchangeRepository { save(job:ExchangeJob):Promise<void>; find(companyId:string,id:string):Promise<ExchangeJob|undefined>; findByKey(companyId:string,key:string):Promise<ExchangeJob|undefined>; list(companyId:string):Promise<readonly ExchangeJob[]> }
export class DataExchangeApplicationService {
 constructor(private readonly repository:DataExchangeRepository){}
 async upload(input:{companyId:string;branchId?:string;fileName:string;format:'CSV'|'XLSX';rows:ReadonlyArray<Readonly<Record<string,string>>>;mapping:Readonly<Record<string,string>>;idempotencyKey:string}){if(!input.fileName.trim()||!input.idempotencyKey.trim())throw new DataExchangeError('source and idempotency key are required');const prior=await this.repository.findByKey(input.companyId,input.idempotencyKey);if(prior)return prior;const now=new Date();const job:ExchangeJob={id:randomUUID(),companyId:input.companyId,branchId:input.branchId??null,direction:'IMPORT',status:'UPLOADED',fileName:input.fileName,format:input.format,mapping:{...input.mapping},idempotencyKey:input.idempotencyKey,rows:input.rows.map((source,rowNumber)=>({rowNumber:rowNumber+1,source:{...source},outcome:'PENDING'})),createdAt:now,updatedAt:now};await this.repository.save(job);return job}
 async preview(companyId:string,id:string,required:readonly string[]){const job=await this.require(companyId,id);for(const row of job.rows){const missing=required.find(field=>!row.source[field]?.trim());if(missing){row.outcome='FAILED';row.error=`Missing ${missing}`}}job.status=job.rows.some(x=>x.outcome==='FAILED')?'VALIDATED':'READY';job.updatedAt=new Date();await this.repository.save(job);return job}
 async execute(companyId:string,id:string,target:ImportTarget){const job=await this.require(companyId,id);if(!['READY','VALIDATED','COMPLETED_WITH_ERRORS'].includes(job.status))throw new DataExchangeError('job is not executable');job.status='PROCESSING';await this.repository.save(job);for(const row of job.rows){if(row.outcome==='FAILED'||row.outcome==='IMPORTED'||row.outcome==='DUPLICATE')continue;try{row.outcome=await target.importRow({companyId:job.companyId,branchId:job.branchId,values:Object.fromEntries(Object.entries(job.mapping).map(([source,targetField])=>[targetField,row.source[source]??''])),idempotencyKey:`${job.id}:${row.rowNumber}`})}catch(error){row.outcome='FAILED';row.error=error instanceof Error?error.message:'Unknown row failure'}await this.repository.save(job)}job.status=job.rows.some(x=>x.outcome==='FAILED')?'COMPLETED_WITH_ERRORS':'COMPLETED';job.updatedAt=new Date();await this.repository.save(job);return job}
 async list(companyId:string){return this.repository.list(companyId)} private async require(companyId:string,id:string){const job=await this.repository.find(companyId,id);if(!job)throw new DataExchangeError('job not found');return job}
}
export class InMemoryDataExchangeRepository implements DataExchangeRepository { private readonly jobs=new Map<string,ExchangeJob>();async save(job:ExchangeJob){this.jobs.set(job.id,structuredClone(job))}async find(companyId:string,id:string){const x=this.jobs.get(id);return x?.companyId===companyId?structuredClone(x):undefined}async findByKey(companyId:string,key:string){const x=[...this.jobs.values()].find(x=>x.companyId===companyId&&x.idempotencyKey===key);return x&&structuredClone(x)}async list(companyId:string){return [...this.jobs.values()].filter(x=>x.companyId===companyId).map(x=>structuredClone(x))} }
