import{createHash}from'node:crypto';import{ContractValidationError,currencyCode,decimalAmount,type CompanyId,type DecimalAmount}from'@elhafez/contracts';import type{BillingSubledgersApplicationService,CreateInvoiceInput}from'@elhafez/billing-subledgers';import type{ProcurementRepository}from'./procurement.repository.js';import type{ProcurementHistory,ProcurementPolicy,PurchaseOrder,SupplierCommitment}from'../domain/procurement.js';
const SCALE=10n**18n;const scaled=(v:DecimalAmount)=>{const s=decimalAmount(v),n=s.startsWith('-'),u=n?s.slice(1):s,[w,f='']=u.split('.');if(f.length>18)throw new ContractValidationError('quantity','supports at most 18 fractional digits');const x=BigInt(w+f.padEnd(18,'0'));return n?-x:x};const amount=(v:bigint)=>{const n=v<0n,u=n?-v:v,w=u/SCALE,f=u%SCALE,s=f===0n?w.toString():`${w}.${f.toString().padStart(18,'0').replace(/0+$/,'')}`;return decimalAmount((n?'-':'')+s)};const positive=(v:DecimalAmount)=>{const x=decimalAmount(v);if(scaled(x)<=0n)throw new ContractValidationError('quantity','must be positive');return x};const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');const now=()=>new Date().toISOString();
const history=(companyId:CompanyId,aggregateId:string,kind:string,sourceReference?:string):ProcurementHistory=>({id:`${aggregateId}:${kind}:${sourceReference??'once'}`,companyId,aggregateId,kind,sourceReference,createdAt:now()});
export interface CreateSupplierCommitmentInput{id:string;companyId:CompanyId;supplierId:string;sourceType:string;sourceId:string;effectiveDate:string}
export interface CreatePurchaseOrderInput{id:string;companyId:CompanyId;commitmentId?:string;supplierId:string;number:string;origin:'MANUAL'|'AUTO';lines:{id:string;itemReference:string;orderedQuantity:DecimalAmount}[]}
export interface ConvertToSupplierInvoiceInput{id:string;companyId:CompanyId;purchaseOrderId:string;lineId:string;quantity:DecimalAmount;billing:{invoiceId:string;number:string;externalInvoiceNumber:string;postingDate:string;currency:string;controlAccountId:string;accountId:string}}
export class ProcurementFinanceApplicationService{
 constructor(private readonly repo:ProcurementRepository,private readonly billing:Pick<BillingSubledgersApplicationService,'createDraft'>){}
 async setPolicy(input:{companyId:CompanyId;commitmentTiming:string;version:number;effectiveFrom:string}){if(input.commitmentTiming!=='ON_PO_APPROVAL')throw new ContractValidationError('commitmentTiming','unsupported; UNKNOWN / NEEDS EVIDENCE');const value={...input,commitmentTiming:'ON_PO_APPROVAL',requestHash:hash(input)} as ProcurementPolicy;return this.repo.savePolicy(value)}
 async createSupplierCommitment(input:CreateSupplierCommitmentInput){if(!input.supplierId||!input.sourceType||!input.sourceId)throw new ContractValidationError('commitment','supplier and source required');const requestHash=hash(input),old=await this.repo.commitmentBySource(input.companyId,input.sourceType,input.sourceId);if(old){if(old.requestHash!==requestHash)throw new ContractValidationError('source','conflicting replay');return old}const value:SupplierCommitment={...input,status:'DRAFT',requestHash,createdAt:now()};return this.repo.saveCommitment(value,history(input.companyId,input.id,'CREATED',`${input.sourceType}:${input.sourceId}`))}
 async cancelSupplierCommitment(companyId:CompanyId,id:string,reason:string){const blockers=await this.getCancellationBlockers(companyId,{commitmentId:id});if(blockers.length)throw new ContractValidationError('commitment','supplier execution blocks cancellation');return this.repo.cancelCommitment(companyId,id,reason,now())}
 async createPurchaseOrder(input:CreatePurchaseOrderInput){if(!input.number||!input.supplierId||!input.lines.length)throw new ContractValidationError('purchaseOrder','number, supplier and lines required');for(const line of input.lines)positive(line.orderedQuantity);if(input.commitmentId){const c=await this.repo.commitment(input.companyId,input.commitmentId);if(!c||c.supplierId!==input.supplierId)throw new ContractValidationError('commitment','same-company matching commitment required')}const requestHash=hash(input),prior=await this.repo.po(input.companyId,input.id);if(prior){if(prior.requestHash!==requestHash)throw new ContractValidationError('purchaseOrder','conflicting replay');return prior}const number=await this.repo.poByNumber(input.companyId,input.number);if(number)throw new ContractValidationError('number','already used');const value:PurchaseOrder={...input,status:'DRAFT',requestHash,createdAt:now(),lines:input.lines.map(x=>({...x,companyId:input.companyId,purchaseOrderId:input.id,orderedQuantity:positive(x.orderedQuantity),receivedQuantity:decimalAmount('0'),invoicedQuantity:decimalAmount('0')}))};return this.repo.savePo(value,history(input.companyId,input.id,'CREATED'))}
 async approvePurchaseOrder(companyId:CompanyId,id:string){const policy=await this.repo.policy(companyId);if(!policy)throw new ContractValidationError('policy','company procurement policy required');return this.repo.transitionPo(companyId,id,['DRAFT'],'APPROVED',history(companyId,id,'APPROVED',String(policy.version)))}
 async receivePurchaseOrder(input:{companyId:CompanyId;purchaseOrderId:string;lineId:string;quantity:DecimalAmount;commandId:string}){return this.repo.receive(input.companyId,input.purchaseOrderId,input.lineId,positive(input.quantity),input.commandId,hash(input))}
 async cancelPurchaseOrder(companyId:CompanyId,id:string){const blockers=await this.getCancellationBlockers(companyId,{purchaseOrderId:id});if(blockers.length)throw new ContractValidationError('purchaseOrder','supplier execution blocks cancellation');return this.repo.transitionPo(companyId,id,['DRAFT','APPROVED'],'CANCELLED',history(companyId,id,'CANCELLED'))}
 async disposeDraftAutoPurchaseOrder(companyId:CompanyId,id:string){const po=await this.getPurchaseOrder(companyId,id);if(po.origin==='AUTO'&&po.status==='DISPOSED')return po;if(po.origin!=='AUTO'||po.status!=='DRAFT'||po.lines.some(x=>scaled(x.receivedQuantity)>0n||scaled(x.invoicedQuantity)>0n))throw new ContractValidationError('purchaseOrder','only economically empty draft auto PO can be disposed');return this.repo.transitionPo(companyId,id,['DRAFT'],'DISPOSED',history(companyId,id,'DISPOSED'))}
 async convertToSupplierInvoice(input:ConvertToSupplierInvoiceInput){const quantity=positive(input.quantity),requestHash=hash(input);let conversion=await this.repo.conversion(input.companyId,input.id);if(conversion&&conversion.requestHash!==requestHash)throw new ContractValidationError('conversion','conflicting replay');if(!conversion)conversion=await this.repo.reserveConversion({id:input.id,companyId:input.companyId,purchaseOrderId:input.purchaseOrderId,lineId:input.lineId,billingInvoiceId:input.billing.invoiceId,quantity,reopenedQuantity:decimalAmount('0'),requestHash,status:'RESERVED',createdAt:now()});if(conversion.status==='INVOICED')return conversion;const po=await this.getPurchaseOrder(input.companyId,input.purchaseOrderId);const line=po.lines.find(x=>x.id===input.lineId);if(!line)throw new ContractValidationError('line','not found');const invoice:CreateInvoiceInput={id:input.billing.invoiceId,companyId:input.companyId,type:'SUPPLIER',partyId:po.supplierId,number:input.billing.number,externalInvoiceNumber:input.billing.externalInvoiceNumber,postingDate:input.billing.postingDate,currency:currencyCode(input.billing.currency),sourceType:'PROCUREMENT_PO',sourceId:input.id,controlAccountId:input.billing.controlAccountId,lines:[{id:`${input.billing.invoiceId}:1`,accountId:input.billing.accountId,amount:quantity}]};await this.billing.createDraft(invoice);return this.repo.completeConversion(input.companyId,input.id,input.billing.invoiceId)}
 async reopenAfterSupplierInvoiceCancellation(input:{companyId:CompanyId;conversionId:string;billingInvoiceId:string;eventId:string}){return this.repo.reopenConversion(input.companyId,input.conversionId,input.billingInvoiceId,input.eventId,hash(input))}
 async getPurchaseOrder(companyId:CompanyId,id:string){const value=await this.repo.po(companyId,id);if(!value)throw new ContractValidationError('purchaseOrder','not found');return value}
 async getSupplierCommitment(companyId:CompanyId,id:string){const value=await this.repo.commitment(companyId,id);if(!value)throw new ContractValidationError('commitment','not found');return value}
 async getRemainingUninvoicedQuantities(companyId:CompanyId,id:string){const po=await this.getPurchaseOrder(companyId,id);return po.lines.map(x=>({lineId:x.id,quantity:amount(scaled(x.receivedQuantity)-scaled(x.invoicedQuantity))}))}
 async getCancellationBlockers(companyId:CompanyId,q:{purchaseOrderId?:string;commitmentId?:string}){let pos=q.purchaseOrderId?[await this.getPurchaseOrder(companyId,q.purchaseOrderId)]:[];if(q.commitmentId){await this.getSupplierCommitment(companyId,q.commitmentId);pos=await this.repo.posByCommitment(companyId,q.commitmentId)}return pos.flatMap(po=>po.lines.filter(x=>scaled(x.receivedQuantity)>0n||scaled(x.invoicedQuantity)>0n).map(x=>({type:'SUPPLIER_EXECUTION' as const,purchaseOrderId:po.id,lineId:x.id})))}
 async getHistory(companyId:CompanyId,id:string){return this.repo.history(companyId,id)}
}
