import{randomUUID}from'node:crypto';
import{ContractValidationError}from'@elhafez/contracts';
import type{OperationalReportingAccess}from'./operational-reporting.ports.js';
import type{OperationalReportingRepository}from'./operational-reporting.repository.js';
import{REPORT_KEYS,type OperationalReportKey,type OperationalReportSchedule,type ReportDeliveryChannel,type ReportScheduleCadence,type SavedOperationalReport,type SavedReportVisibility}from'../domain/operational-reporting.js';

export const OPERATIONAL_REPORTING_PERMISSIONS=Object.freeze({read:'management.control.read',manage:'platform.configuration.manage'}as const);
export interface OperationalReportingContext{readonly companyId:string;readonly actorId:string}
export interface CreateSavedReportInput{readonly name:string;readonly reportKey:OperationalReportKey;readonly filters?:Readonly<Record<string,unknown>>;readonly visibility?:SavedReportVisibility}
export interface UpdateSavedReportInput{readonly name?:string;readonly filters?:Readonly<Record<string,unknown>>;readonly visibility?:SavedReportVisibility;readonly active?:boolean}
export interface CreateReportScheduleInput{readonly savedReportId:string;readonly cadence:ReportScheduleCadence;readonly hourUtc:number;readonly weekday?:number|null;readonly dayOfMonth?:number|null;readonly channel:ReportDeliveryChannel;readonly recipient?:string|null}
export interface UpdateReportScheduleInput{readonly cadence?:ReportScheduleCadence;readonly hourUtc?:number;readonly weekday?:number|null;readonly dayOfMonth?:number|null;readonly channel?:ReportDeliveryChannel;readonly recipient?:string|null;readonly enabled?:boolean}

function required(value:string,field:string){const normalized=value.trim();if(!normalized)throw new ContractValidationError(field,'is required');return normalized;}
function reportName(value:string){const normalized=required(value,'name');if(normalized.length>120)throw new ContractValidationError('name','must not exceed 120 characters');return normalized;}
function reportKey(value:OperationalReportKey){if(!REPORT_KEYS.includes(value))throw new ContractValidationError('reportKey','unsupported report key');return value;}
function visibility(value:SavedReportVisibility){if(value!=='PRIVATE'&&value!=='COMPANY')throw new ContractValidationError('visibility','must be PRIVATE or COMPANY');return value;}
function filters(value:Readonly<Record<string,unknown>>|undefined){if(value===undefined)return{};if(!value||typeof value!=='object'||Array.isArray(value))throw new ContractValidationError('filters','must be an object');try{return structuredClone(value);}catch{throw new ContractValidationError('filters','must be serializable');}}
function scheduleValues(input:{cadence:ReportScheduleCadence;hourUtc:number;weekday?:number|null;dayOfMonth?:number|null;channel:ReportDeliveryChannel;recipient?:string|null}){
 if(!['DAILY','WEEKLY','MONTHLY'].includes(input.cadence))throw new ContractValidationError('cadence','unsupported cadence');
 if(!Number.isInteger(input.hourUtc)||input.hourUtc<0||input.hourUtc>23)throw new ContractValidationError('hourUtc','must be an integer from 0 to 23');
 const weekday=input.cadence==='WEEKLY'?input.weekday??null:null,dayOfMonth=input.cadence==='MONTHLY'?input.dayOfMonth??null:null;
 if(input.cadence==='WEEKLY'&&(!Number.isInteger(weekday)||Number(weekday)<0||Number(weekday)>6))throw new ContractValidationError('weekday','must be an integer from 0 to 6 for weekly schedules');
 if(input.cadence==='MONTHLY'&&(!Number.isInteger(dayOfMonth)||Number(dayOfMonth)<1||Number(dayOfMonth)>28))throw new ContractValidationError('dayOfMonth','must be an integer from 1 to 28 for monthly schedules');
 if(input.channel!=='IN_APP'&&input.channel!=='EMAIL')throw new ContractValidationError('channel','unsupported delivery channel');
 const recipient=input.channel==='EMAIL'?required(input.recipient??'','recipient'):null;
 return{cadence:input.cadence,hourUtc:input.hourUtc,weekday,dayOfMonth,channel:input.channel,recipient};
}
export class OperationalReportingApplicationService{
 constructor(private readonly repo:OperationalReportingRepository,private readonly access:OperationalReportingAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async permission(context:OperationalReportingContext,permission:string){if(!context.companyId||!context.actorId)throw new ContractValidationError('context','company and actor are required');await this.access.requirePermission(context,permission);}
 async createSavedReport(context:OperationalReportingContext,input:CreateSavedReportInput){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.read);const vis=visibility(input.visibility??'PRIVATE');if(vis==='COMPANY')await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.manage);const now=this.now().toISOString();const saved=await this.repo.createSavedReport({id:this.newId(),companyId:context.companyId,ownerActorId:context.actorId,name:reportName(input.name),reportKey:reportKey(input.reportKey),filters:filters(input.filters),visibility:vis,active:true,createdAt:now,updatedAt:now});await this.access.auditOnce(context,'operational-reporting.saved.created:'+saved.id,'operational-reporting.saved.created',saved.id,{reportKey:saved.reportKey,visibility:saved.visibility});return saved;}
 async updateSavedReport(context:OperationalReportingContext,id:string,input:UpdateSavedReportInput){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.read);const current=await this.requireVisible(context,id);const nextVisibility=input.visibility===undefined?current.visibility:visibility(input.visibility);if(current.visibility==='COMPANY'||nextVisibility==='COMPANY'||current.ownerActorId!==context.actorId)await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.manage);const updated=await this.repo.updateSavedReport(context.companyId,current.id,{name:input.name===undefined?current.name:reportName(input.name),filters:input.filters===undefined?current.filters:filters(input.filters),visibility:nextVisibility,active:input.active??current.active,updatedAt:this.now().toISOString()});await this.access.auditOnce(context,'operational-reporting.saved.updated:'+updated.id+':'+updated.updatedAt,'operational-reporting.saved.updated',updated.id,{visibility:updated.visibility,active:updated.active});return updated;}
 async listSavedReports(context:OperationalReportingContext){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.read);return(await this.repo.listSavedReports(context.companyId)).filter(row=>row.visibility==='COMPANY'||row.ownerActorId===context.actorId);}
 async createSchedule(context:OperationalReportingContext,input:CreateReportScheduleInput){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.manage);const report=await this.requireVisible(context,input.savedReportId),values=scheduleValues(input),now=this.now().toISOString();const schedule=await this.repo.createSchedule({id:this.newId(),companyId:context.companyId,savedReportId:report.id,...values,enabled:true,createdBy:context.actorId,createdAt:now,updatedAt:now});await this.access.auditOnce(context,'operational-reporting.schedule.created:'+schedule.id,'operational-reporting.schedule.created',schedule.id,{savedReportId:report.id,cadence:schedule.cadence,channel:schedule.channel});return schedule;}
 async updateSchedule(context:OperationalReportingContext,id:string,input:UpdateReportScheduleInput){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.manage);const current=(await this.repo.listSchedules(context.companyId)).find(row=>row.id===required(id,'scheduleId'));if(!current)throw new ContractValidationError('scheduleId','schedule was not found');const values=scheduleValues({cadence:input.cadence??current.cadence,hourUtc:input.hourUtc??current.hourUtc,weekday:input.weekday===undefined?current.weekday:input.weekday,dayOfMonth:input.dayOfMonth===undefined?current.dayOfMonth:input.dayOfMonth,channel:input.channel??current.channel,recipient:input.recipient===undefined?current.recipient:input.recipient});const updated=await this.repo.updateSchedule(context.companyId,current.id,{...values,enabled:input.enabled??current.enabled,updatedAt:this.now().toISOString()});await this.access.auditOnce(context,'operational-reporting.schedule.updated:'+updated.id+':'+updated.updatedAt,'operational-reporting.schedule.updated',updated.id,{enabled:updated.enabled,cadence:updated.cadence,channel:updated.channel});return updated;}
 async listSchedules(context:OperationalReportingContext,savedReportId?:string){await this.permission(context,OPERATIONAL_REPORTING_PERMISSIONS.read);const visible=new Set((await this.listSavedReports(context)).map(row=>row.id));return(await this.repo.listSchedules(context.companyId,savedReportId?.trim()||undefined)).filter(row=>visible.has(row.savedReportId));}
 private async requireVisible(context:OperationalReportingContext,id:string):Promise<SavedOperationalReport>{const report=await this.repo.findSavedReport(context.companyId,required(id,'savedReportId'));if(!report||(report.visibility==='PRIVATE'&&report.ownerActorId!==context.actorId))throw new ContractValidationError('savedReportId','saved report was not found');return report;}
}
