import{ContractValidationError}from'@elhafez/contracts';
import type{WorkflowCondition,WorkflowSpec,WorkflowStep}from'../domain/automation-workflow.js';

export function validateSpec(spec:WorkflowSpec):WorkflowSpec{
 if(!spec||!Array.isArray(spec.conditions)||!Array.isArray(spec.steps)||!spec.steps.length)throw new ContractValidationError('spec','conditions and at least one step are required');
 if(!Number.isInteger(spec.retry?.maxAttempts)||spec.retry.maxAttempts<0||spec.retry.maxAttempts>20)throw new ContractValidationError('retry.maxAttempts','must be an integer from 0 to 20');
 if(!Number.isInteger(spec.retry?.backoffSeconds)||spec.retry.backoffSeconds<0||spec.retry.backoffSeconds>604800)throw new ContractValidationError('retry.backoffSeconds','must be an integer from 0 to 604800');
 for(const condition of spec.conditions){if(!condition.path.trim())throw new ContractValidationError('condition.path','is required');if(!['EQ','NE','GT','GTE','LT','LTE','EXISTS'].includes(condition.operator))throw new ContractValidationError('condition.operator','is unsupported');}
 spec.steps.forEach((step,index)=>validateStep(step,index));
 if(spec.retry.deadLetterAction)validateStep(spec.retry.deadLetterAction,-1);
 return structuredClone(spec);
}
function validateStep(step:WorkflowStep,index:number){if(step.kind==='DELAY'){if(!Number.isInteger(step.seconds)||step.seconds<1||step.seconds>31536000)throw new ContractValidationError('spec.steps['+index+'].seconds','must be an integer from 1 to 31536000');return;}if(step.kind==='APPROVAL'){if(!step.signal.trim())throw new ContractValidationError('spec.steps['+index+'].signal','is required');return;}if(!step.action.trim())throw new ContractValidationError('spec.steps['+index+'].action','is required');}
function pathValue(payload:Readonly<Record<string,unknown>>,path:string):unknown{return path.split('.').reduce<unknown>((value,key)=>value&&typeof value==='object'&&!Array.isArray(value)?(value as Record<string,unknown>)[key]:undefined,payload);}
export function conditionsMatch(conditions:readonly WorkflowCondition[],payload:Readonly<Record<string,unknown>>){return conditions.every(condition=>{const actual=pathValue(payload,condition.path);switch(condition.operator){case'EXISTS':return condition.value===false?actual===undefined:actual!==undefined;case'EQ':return actual===condition.value;case'NE':return actual!==condition.value;case'GT':return typeof actual==='number'&&typeof condition.value==='number'&&actual>condition.value;case'GTE':return typeof actual==='number'&&typeof condition.value==='number'&&actual>=condition.value;case'LT':return typeof actual==='number'&&typeof condition.value==='number'&&actual<condition.value;case'LTE':return typeof actual==='number'&&typeof condition.value==='number'&&actual<=condition.value;}});}
export function resolveInput(input:Readonly<Record<string,unknown>>|undefined,payload:Readonly<Record<string,unknown>>):Readonly<Record<string,unknown>>{const resolve=(value:unknown):unknown=>{if(typeof value==='string'){const match=/^\{\{([a-zA-Z0-9_.-]+)\}\}$/.exec(value);if(!match)return value;const path=match[1]??'';const resolved=pathValue(payload,path);if(resolved===undefined)throw new ContractValidationError('action.input','template path was not found: '+path);return resolved;}if(Array.isArray(value))return value.map(resolve);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,resolve(item)]));return value;};return resolve(input??{}) as Readonly<Record<string,unknown>>;}
