import { randomUUID } from 'node:crypto';
import { Prisma, type PrismaClient } from '@prisma/client';
import { decimalAmount, type CompanyId, type DecimalAmount, type SourceReference } from '@elhafez/contracts';
import type { Allocation, ContractType, ContractVersion, FlightBlock, FlightBlockConsumption, HotelInventory, ProcurementRequest, StopSale, TourismContract, TransportCapacity, VisaQuota } from '../domain/inventory.js';
import type { AdjustAllocationInput, AllocateCapacityInput, AllocationResult, AmendContractInput, AvailabilityResult, CheckAvailabilityInput, ConsumeFlightBlockInput, CreateFlightBlockInput, CreateHotelInventoryInput, CreateStopSaleInput, CreateTourismContractInput, CreateTransportCapacityInput, CreateVisaQuotaInput, InternalFirstFulfillmentInput, ReleaseAllocationInput, ReleaseResult } from '../application/inventory.application-service.js';
import type { TourismInventoryRepository } from './inventory.repository.js';

type Tx=Prisma.TransactionClient;
const json=(v:unknown)=>v as Prisma.InputJsonValue;
const source=(v:Prisma.JsonValue|null):SourceReference|undefined=>v===null?undefined:v as unknown as SourceReference;
const amount=(v:{toString():string}):DecimalAmount=>decimalAmount(v.toString());
const iso=(v:Date)=>v.toISOString();
const contract=(r:{id:string;companyId:string;type:string;status:string;supplierId:string|null;effectiveFrom:Date;effectiveTo:Date;createdAt:Date;sourceReference:Prisma.JsonValue|null}):TourismContract=>({id:r.id,companyId:r.companyId as CompanyId,type:r.type as ContractType,status:r.status as TourismContract['status'],supplierId:r.supplierId??undefined,effectiveFrom:iso(r.effectiveFrom),effectiveTo:iso(r.effectiveTo),createdAt:iso(r.createdAt),sourceReference:source(r.sourceReference)});
const version=(r:{id:string;companyId:string;contractId:string;versionNumber:number;effectiveFrom:Date;effectiveTo:Date|null;terms:Prisma.JsonValue;createdAt:Date;isCurrent:boolean}):ContractVersion=>({id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,versionNumber:r.versionNumber,effectiveFrom:iso(r.effectiveFrom),effectiveTo:r.effectiveTo?iso(r.effectiveTo):undefined,terms:r.terms as Record<string,unknown>,createdAt:iso(r.createdAt),isCurrent:r.isCurrent});
const allocation=(r:{id:string;companyId:string;contractId:string;contractVersionId:string;resourceType:string;resourceId:string;program:Prisma.JsonValue;serviceDate:Date;periodEnd:Date|null;quantity:{toString():string};status:string;releaseBlockerReason:string|null;createdAt:Date;sourceReference:Prisma.JsonValue|null}):Allocation=>({id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,contractVersionId:r.contractVersionId,resourceType:r.resourceType as ContractType,resourceId:r.resourceId,program:r.program as unknown as SourceReference,serviceDate:iso(r.serviceDate),periodEnd:r.periodEnd?iso(r.periodEnd):undefined,quantity:amount(r.quantity),status:r.status as Allocation['status'],releaseBlockerReason:r.releaseBlockerReason??undefined,createdAt:iso(r.createdAt),sourceReference:source(r.sourceReference)});

export class PrismaTourismInventoryRepository implements TourismInventoryRepository {
 constructor(private readonly db:PrismaClient){}
 private async command<T>(companyId:CompanyId,key:string|undefined,hash:string,work:(tx:Tx)=>Promise<T>):Promise<T>{
  return this.db.$transaction(async tx=>{if(key){const old=await tx.tciIdempotencyKey.findUnique({where:{companyId_key:{companyId,key}}});if(old){if(old.requestHash!==hash)throw new Error(`Idempotency conflict for '${key}'`);return old.result as unknown as T}}
   const result=await work(tx);if(key)await tx.tciIdempotencyKey.create({data:{id:randomUUID(),companyId,key,requestHash:hash,result:json(result)}});return result},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }
 async createContract(i:CreateTourismContractInput,k:string|undefined,h:string){return this.command(i.companyId,k,h,async tx=>{const id=randomUUID(),created=await tx.tciContract.create({data:{id,companyId:i.companyId,type:i.type,status:'ACTIVE',supplierId:i.supplierId,effectiveFrom:new Date(i.effectiveFrom),effectiveTo:new Date(i.effectiveTo),sourceReference:i.sourceReference?json(i.sourceReference):Prisma.JsonNull}});const v=await tx.tciContractVersion.create({data:{id:randomUUID(),companyId:i.companyId,contractId:id,versionNumber:1,effectiveFrom:new Date(i.effectiveFrom),effectiveTo:new Date(i.effectiveTo),terms:json({type:i.type,supplierId:i.supplierId??null}),isCurrent:true}});await this.history(tx,i.companyId,id,'CONTRACT_CREATED',v.id);return contract(created)})}
 async amendContract(i:AmendContractInput,k:string|undefined,h:string){return this.command(i.companyId,k,h,async tx=>{const c=await tx.tciContract.findUnique({where:{companyId_id:{companyId:i.companyId,id:i.contractId}}});if(!c)throw new Error('contract not found for company');const current=await tx.tciContractVersion.findFirst({where:{companyId:i.companyId,contractId:i.contractId,isCurrent:true}});if(!current)throw new Error('current contract version not found');const uncovered=await tx.tciAllocation.count({where:{companyId:i.companyId,contractId:i.contractId,status:{in:['CONFIRMED','PARTIALLY_RELEASED']},OR:[{serviceDate:{lt:new Date(i.effectiveFrom)}},...(i.effectiveTo?[{serviceDate:{gt:new Date(i.effectiveTo)}}]:[])]}});if(uncovered)throw new Error('amendment would remove required active program coverage');await tx.tciContractVersion.updateMany({where:{companyId:i.companyId,contractId:i.contractId,isCurrent:true},data:{isCurrent:false}});const created=await tx.tciContractVersion.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,versionNumber:current.versionNumber+1,effectiveFrom:new Date(i.effectiveFrom),effectiveTo:i.effectiveTo?new Date(i.effectiveTo):null,terms:json(i.terms),isCurrent:true}});await tx.tciContract.update({where:{companyId_id:{companyId:i.companyId,id:i.contractId}},data:{status:'AMENDED'}});await this.history(tx,i.companyId,i.contractId,'CONTRACT_AMENDED',created.id);return version(created)})}
 async contract(c:CompanyId,id:string){const r=await this.db.tciContract.findUnique({where:{companyId_id:{companyId:c,id}}});return r?contract(r):null}
 async versions(c:CompanyId,id:string){return (await this.db.tciContractVersion.findMany({where:{companyId:c,contractId:id},orderBy:{versionNumber:'asc'}})).map(version)}
 async createHotel(i:CreateHotelInventoryInput,k:string|undefined,h:string):Promise<HotelInventory>{return this.command(i.companyId,k,h,async tx=>{await this.requireContract(tx,i.companyId,i.contractId,'HOTEL');const r=await tx.tciHotelInventory.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,hotelId:i.hotelId,roomId:i.roomId,serviceDate:new Date(i.serviceDate),contractedQuantity:i.contractedQuantity,allocatedQuantity:'0',availableQuantity:i.contractedQuantity,status:'ACTIVE'}});await this.history(tx,i.companyId,i.contractId,'HOTEL_INVENTORY_CREATED',r.id);return {id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,hotelId:r.hotelId,roomId:r.roomId??undefined,serviceDate:iso(r.serviceDate),contractedQuantity:amount(r.contractedQuantity),allocatedQuantity:amount(r.allocatedQuantity),availableQuantity:amount(r.availableQuantity),status:'ACTIVE'}})}
 async createFlight(i:CreateFlightBlockInput,k:string|undefined,h:string):Promise<FlightBlock>{return this.command(i.companyId,k,h,async tx=>{await this.requireContract(tx,i.companyId,i.contractId,'FLIGHT_BLOCK');const r=await tx.tciFlightBlock.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,flightNumber:i.flightNumber,origin:i.origin,destination:i.destination,departureDate:new Date(i.departureDate),totalSeats:i.totalSeats,consumedSeats:'0',availableSeats:i.totalSeats}});return {id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,flightNumber:r.flightNumber,origin:r.origin,destination:r.destination,departureDate:iso(r.departureDate),totalSeats:amount(r.totalSeats),consumedSeats:amount(r.consumedSeats),availableSeats:amount(r.availableSeats)}})}
 async createTransport(i:CreateTransportCapacityInput,k:string|undefined,h:string):Promise<TransportCapacity>{return this.command(i.companyId,k,h,async tx=>{await this.requireContract(tx,i.companyId,i.contractId,'TRANSPORT');const r=await tx.tciTransportCapacity.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,vehicleId:i.vehicleId,capacityUnits:i.capacityUnits,periodStart:new Date(i.periodStart),periodEnd:new Date(i.periodEnd),consumedUnits:'0'}});return {id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,vehicleId:r.vehicleId,capacityUnits:amount(r.capacityUnits),periodStart:iso(r.periodStart),periodEnd:iso(r.periodEnd),consumedUnits:amount(r.consumedUnits)}})}
 async createVisa(i:CreateVisaQuotaInput,k:string|undefined,h:string):Promise<VisaQuota>{return this.command(i.companyId,k,h,async tx=>{await this.requireContract(tx,i.companyId,i.contractId,'VISA');const r=await tx.tciVisaQuota.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,visaType:i.visaType,nationality:i.nationality,quotaTotal:i.quotaTotal,quotaConsumed:'0',quotaRemaining:i.quotaTotal,effectiveFrom:new Date(i.effectiveFrom),effectiveTo:new Date(i.effectiveTo)}});return {id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,visaType:r.visaType,nationality:r.nationality??undefined,quotaTotal:amount(r.quotaTotal),quotaConsumed:amount(r.quotaConsumed),quotaRemaining:amount(r.quotaRemaining),effectiveFrom:iso(r.effectiveFrom),effectiveTo:iso(r.effectiveTo)}})}
 async createStopSale(i:CreateStopSaleInput,k:string|undefined,h:string):Promise<StopSale>{return this.command(i.companyId,k,h,async tx=>{await this.requireContract(tx,i.companyId,i.contractId);const r=await tx.tciStopSale.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,reason:i.reason,effectiveFrom:new Date(i.effectiveFrom),effectiveTo:new Date(i.effectiveTo),isActive:true}});return {id:r.id,companyId:r.companyId as CompanyId,contractId:r.contractId,reason:r.reason,effectiveFrom:iso(r.effectiveFrom),effectiveTo:iso(r.effectiveTo),createdAt:iso(r.createdAt),isActive:r.isActive}})}
 async availability(i:CheckAvailabilityInput):Promise<AvailabilityResult>{const stop=await this.db.tciStopSale.findFirst({where:{companyId:i.companyId,contractId:i.contractId,isActive:true,effectiveFrom:{lte:new Date(i.serviceDate)},effectiveTo:{gte:new Date(i.serviceDate)}}});if(stop)return {available:false,availableQuantity:decimalAmount('0'),blockerReason:`Stop sale: ${stop.reason}`};const q=await this.resourceAvailable(this.db,i);return {available:q!=='0',availableQuantity:q}}
 async allocate(i:AllocateCapacityInput,k:string|undefined,h:string):Promise<AllocationResult>{return this.command(i.companyId,k,h,tx=>this.allocateTx(tx,i))}
 private async allocateTx(tx:Tx,i:AllocateCapacityInput):Promise<AllocationResult>{const stop=await tx.tciStopSale.findFirst({where:{companyId:i.companyId,contractId:i.contractId,isActive:true,effectiveFrom:{lte:new Date(i.serviceDate)},effectiveTo:{gte:new Date(i.serviceDate)}}});if(stop)throw new Error(`stop sale in effect: ${stop.reason}`);const current=await tx.tciContractVersion.findFirst({where:{companyId:i.companyId,contractId:i.contractId,isCurrent:true}});if(!current)throw new Error('current contract version not found');await this.consume(tx,i);const r=await tx.tciAllocation.create({data:{id:randomUUID(),companyId:i.companyId,contractId:i.contractId,contractVersionId:current.id,resourceType:i.resourceType,resourceId:i.resourceId,program:json(i.program),serviceDate:new Date(i.serviceDate),periodEnd:i.periodEnd?new Date(i.periodEnd):null,quantity:i.quantity,status:'CONFIRMED',sourceReference:i.sourceReference?json(i.sourceReference):Prisma.JsonNull}});await this.history(tx,i.companyId,i.contractId,'ALLOCATION_CREATED',r.id);return {allocation:allocation(r)}}
 private async consume(tx:Tx,i:AllocateCapacityInput):Promise<void>{let n=0;if(i.resourceType==='HOTEL')n=(await tx.tciHotelInventory.updateMany({where:{companyId:i.companyId,id:i.resourceId,contractId:i.contractId,serviceDate:new Date(i.serviceDate),status:'ACTIVE',availableQuantity:{gte:i.quantity}},data:{allocatedQuantity:{increment:i.quantity},availableQuantity:{decrement:i.quantity}}})).count;else if(i.resourceType==='FLIGHT_BLOCK')n=(await tx.tciFlightBlock.updateMany({where:{companyId:i.companyId,id:i.resourceId,contractId:i.contractId,departureDate:new Date(i.serviceDate),availableSeats:{gte:i.quantity}},data:{consumedSeats:{increment:i.quantity},availableSeats:{decrement:i.quantity}}})).count;else if(i.resourceType==='VISA')n=(await tx.tciVisaQuota.updateMany({where:{companyId:i.companyId,id:i.resourceId,contractId:i.contractId,effectiveFrom:{lte:new Date(i.serviceDate)},effectiveTo:{gte:new Date(i.serviceDate)},quotaRemaining:{gte:i.quantity}},data:{quotaConsumed:{increment:i.quantity},quotaRemaining:{decrement:i.quantity}}})).count;else {if(!i.periodEnd)throw new Error('transport periodEnd is required');const cap=await tx.tciTransportCapacity.findUnique({where:{companyId_id:{companyId:i.companyId,id:i.resourceId}}});if(cap&&cap.contractId===i.contractId&&cap.periodStart<=new Date(i.serviceDate)&&cap.periodEnd>=new Date(i.periodEnd)){const used=await tx.tciAllocation.aggregate({_sum:{quantity:true},where:{companyId:i.companyId,resourceType:'TRANSPORT',resourceId:i.resourceId,status:{in:['CONFIRMED','PARTIALLY_RELEASED','CONSUMED']},serviceDate:{lt:new Date(i.periodEnd)},periodEnd:{gt:new Date(i.serviceDate)}}});const sum=new Prisma.Decimal(used._sum.quantity??0).add(i.quantity);if(sum.lte(cap.capacityUnits))n=1}}if(n!==1)throw new Error(`insufficient ${i.resourceType} capacity or resource mismatch`)}
 async release(i:ReleaseAllocationInput,k:string|undefined,h:string):Promise<ReleaseResult>{return this.command(i.companyId,k,h,async tx=>{const r=await tx.tciAllocation.findUnique({where:{companyId_id:{companyId:i.companyId,id:i.allocationId}}});if(!r)throw new Error('allocation not found for company');if(r.status==='CONSUMED'||i.downstreamEvidence){const evidence=i.downstreamEvidence?JSON.stringify(i.downstreamEvidence):'allocation has downstream economic history';await tx.tciAllocationRelease.create({data:{id:randomUUID(),companyId:i.companyId,allocationId:r.id,releasedQuantity:'0',blockerEvidence:evidence,status:'BLOCKED'}});return {success:false,blockerEvidence:evidence,releasedQuantity:decimalAmount('0')}}if(new Prisma.Decimal(i.quantity).gt(r.quantity))throw new Error('release exceeds allocated quantity');await this.restore(tx,r.resourceType as ContractType,r.resourceId,i.companyId,i.quantity);const left=r.quantity.sub(i.quantity),status=left.isZero()?'RELEASED':'PARTIALLY_RELEASED';await tx.tciAllocation.update({where:{companyId_id:{companyId:i.companyId,id:r.id}},data:{quantity:left,status}});await tx.tciAllocationRelease.create({data:{id:randomUUID(),companyId:i.companyId,allocationId:r.id,releasedQuantity:i.quantity,status:'SUCCESS'}});return {success:true,releasedQuantity:i.quantity}})}
 async adjust(i:AdjustAllocationInput,k:string|undefined,h:string){const prior=k?await this.idempotency(i.companyId,k):null;const result=await this.command(i.companyId,k,h,async tx=>{const r=await tx.tciAllocation.findUnique({where:{companyId_id:{companyId:i.companyId,id:i.allocationId}}});if(!r)throw new Error('allocation not found for company');const old=amount(r.quantity),next=new Prisma.Decimal(i.newQuantity),delta=next.sub(r.quantity);if(delta.gt(0))await this.consume(tx,{companyId:i.companyId,contractId:r.contractId,resourceType:r.resourceType as ContractType,resourceId:r.resourceId,program:r.program as unknown as SourceReference,serviceDate:iso(r.serviceDate),periodEnd:r.periodEnd?iso(r.periodEnd):undefined,quantity:amount(delta),sourceReference:i.sourceReference});else if(delta.lt(0))await this.restore(tx,r.resourceType as ContractType,r.resourceId,i.companyId,amount(delta.negated()));const updated=await tx.tciAllocation.update({where:{companyId_id:{companyId:i.companyId,id:r.id}},data:{quantity:i.newQuantity}});await this.history(tx,i.companyId,r.contractId,'ALLOCATION_ADJUSTED',r.id);return {allocation:allocation(updated),previousQuantity:old,replayed:false}});return prior?{...result,replayed:true}:result}
 async consumeFlight(i:ConsumeFlightBlockInput,k:string|undefined,h:string):Promise<FlightBlockConsumption>{return this.command(i.companyId,k,h,async tx=>{const block=await tx.tciFlightBlock.findUnique({where:{companyId_id:{companyId:i.companyId,id:i.flightBlockId}}});if(!block)throw new Error('flight block not found for company');const updated=await tx.tciFlightBlock.updateMany({where:{companyId:i.companyId,id:i.flightBlockId,availableSeats:{gte:i.seats}},data:{consumedSeats:{increment:i.seats},availableSeats:{decrement:i.seats}}});if(updated.count!==1)throw new Error('insufficient shared flight seats');const r=await tx.tciFlightBlockConsumption.create({data:{id:randomUUID(),companyId:i.companyId,flightBlockId:i.flightBlockId,program:json(i.program),consumedSeats:i.seats,sourceReference:json(i.flightSegmentReference)}});return {id:r.id,companyId:r.companyId as CompanyId,flightBlockId:r.flightBlockId,program:r.program as unknown as SourceReference,consumedSeats:amount(r.consumedSeats),consumedAt:iso(r.consumedAt),sourceReference:source(r.sourceReference)}})}
 async internalFirst(i:InternalFirstFulfillmentInput,k:string|undefined,h:string):Promise<AllocationResult>{return this.command(i.companyId,k,h,async tx=>{const available=await this.resourceAvailable(tx,{companyId:i.companyId,contractId:'',resourceType:i.contractType,resourceId:i.resourceId,serviceDate:i.serviceDate,periodEnd:i.periodEnd},false),take=Prisma.Decimal.min(new Prisma.Decimal(available),new Prisma.Decimal(i.requiredQuantity)),result:AllocationResult={};if(take.gt(0)){const resource=await this.resourceContract(tx,i.companyId,i.contractType,i.resourceId);if(!resource)throw new Error('internal resource not found');Object.assign(result,await this.allocateTx(tx,{...i,contractId:resource,resourceType:i.contractType,quantity:amount(take)}))}const residual=new Prisma.Decimal(i.requiredQuantity).sub(take);if(residual.gt(0)){const request:ProcurementRequest={id:randomUUID(),companyId:i.companyId,program:i.program,residualQuantity:amount(residual),procurementType:i.contractType,externalReference:'',referenceData:i.referenceData,createdAt:new Date().toISOString(),sourceReference:i.sourceReference};await tx.tciProcurementRequest.create({data:{id:request.id,companyId:i.companyId,program:json(i.program),residualQuantity:request.residualQuantity,procurementType:i.contractType,externalReference:null,referenceData:json(i.referenceData),sourceReference:i.sourceReference?json(i.sourceReference):Prisma.JsonNull}});return {...result,procurementRequest:request}}return result})}
 async attachProcurementReference(c:CompanyId,id:string,ref:string){const r=await this.db.tciProcurementRequest.updateMany({where:{companyId:c,id},data:{externalReference:ref}});if(r.count!==1)throw new Error('procurement evidence not found for company')}
 async idempotency(c:CompanyId,k:string){const r=await this.db.tciIdempotencyKey.findUnique({where:{companyId_key:{companyId:c,key:k}}});return r?{requestHash:r.requestHash,result:r.result as Record<string,unknown>}:null}
 private async restore(tx:Tx,type:ContractType,id:string,c:CompanyId,q:DecimalAmount){if(type==='HOTEL')await tx.tciHotelInventory.update({where:{companyId_id:{companyId:c,id}},data:{allocatedQuantity:{decrement:q},availableQuantity:{increment:q}}});else if(type==='FLIGHT_BLOCK')await tx.tciFlightBlock.update({where:{companyId_id:{companyId:c,id}},data:{consumedSeats:{decrement:q},availableSeats:{increment:q}}});else if(type==='VISA')await tx.tciVisaQuota.update({where:{companyId_id:{companyId:c,id}},data:{quotaConsumed:{decrement:q},quotaRemaining:{increment:q}}})}
 private async resourceAvailable(db:Tx|PrismaClient,i:CheckAvailabilityInput,matchContract=true):Promise<DecimalAmount>{const base={companyId:i.companyId,id:i.resourceId,...(matchContract?{contractId:i.contractId}:{})};if(i.resourceType==='HOTEL'){const r=await db.tciHotelInventory.findFirst({where:{...base,serviceDate:new Date(i.serviceDate),status:'ACTIVE'}});return r?amount(r.availableQuantity):decimalAmount('0')}if(i.resourceType==='FLIGHT_BLOCK'){const r=await db.tciFlightBlock.findFirst({where:{...base,departureDate:new Date(i.serviceDate)}});return r?amount(r.availableSeats):decimalAmount('0')}if(i.resourceType==='VISA'){const r=await db.tciVisaQuota.findFirst({where:{...base,effectiveFrom:{lte:new Date(i.serviceDate)},effectiveTo:{gte:new Date(i.serviceDate)}}});return r?amount(r.quotaRemaining):decimalAmount('0')}const r=await db.tciTransportCapacity.findFirst({where:base});if(!r||!i.periodEnd)return decimalAmount('0');const used=await db.tciAllocation.aggregate({_sum:{quantity:true},where:{companyId:i.companyId,resourceType:'TRANSPORT',resourceId:i.resourceId,status:{in:['CONFIRMED','PARTIALLY_RELEASED','CONSUMED']},serviceDate:{lt:new Date(i.periodEnd)},periodEnd:{gt:new Date(i.serviceDate)}}});return amount(Prisma.Decimal.max(new Prisma.Decimal(0),r.capacityUnits.sub(used._sum.quantity??0)))}
 private async resourceContract(tx:Tx,c:CompanyId,t:ContractType,id:string){if(t==='HOTEL')return (await tx.tciHotelInventory.findUnique({where:{companyId_id:{companyId:c,id}}}))?.contractId;if(t==='FLIGHT_BLOCK')return (await tx.tciFlightBlock.findUnique({where:{companyId_id:{companyId:c,id}}}))?.contractId;if(t==='TRANSPORT')return (await tx.tciTransportCapacity.findUnique({where:{companyId_id:{companyId:c,id}}}))?.contractId;return (await tx.tciVisaQuota.findUnique({where:{companyId_id:{companyId:c,id}}}))?.contractId}
 private async requireContract(tx:Tx,c:CompanyId,id:string,type?:ContractType){const r=await tx.tciContract.findUnique({where:{companyId_id:{companyId:c,id}}});if(!r||type&&r.type!==type)throw new Error('matching contract not found for company')}
 private history(tx:Tx,c:CompanyId,contractId:string,kind:string,aggregateId:string){return tx.tciContractHistory.create({data:{id:randomUUID(),companyId:c,contractId,kind,aggregateId,evidence:json({})}})}
}
