import { createHash } from 'node:crypto';
import type { Prisma, PrismaClient } from '@prisma/client';
import type { HistoricalEquivalence, HistoricalImportRecord } from '../application/historical-import.application-service.js';
import type { HistoricalImportRepository } from '../application/historical-import.repository.js';
const s=(v:unknown,f='')=>typeof v==='string'&&v?v:f; const d=(v:unknown)=>new Date(s(v,'1970-01-01')); const o=(v:unknown)=>typeof v==='string'&&v?v:undefined;
const add=(a:string,b:string)=>{const z=Math.max((a.split('.')[1]??'').length,(b.split('.')[1]??'').length),u=10n**BigInt(z),p=(v:string)=>{const q=v.startsWith('-'),[w='0',f='']=(q?v.slice(1):v).split('.'),x=BigInt(w)*u+BigInt(f.padEnd(z,'0'));return q?-x:x},x=p(a)+p(b),q=x<0n,y=q?-x:x,t=y.toString().padStart(z+1,'0');return `${q?'-':''}${z?`${t.slice(0,-z)}.${t.slice(-z)}`:t}`};
export class PrismaHistoricalImportRepository implements HistoricalImportRepository {
 constructor(private readonly db:PrismaClient){}
 async find(runId:string,collection:string,sourceId:string){const v=await this.db.tourismFinanceOrchestrationHistoricalImport.findUnique({where:{runId_collection_sourceId:{runId,collection,sourceId}}});return v?{...v,owner:'TourismFinance',payload:v.payload as Record<string,unknown>,branchId:v.branchId??undefined,debit:v.debit.toString(),credit:v.credit.toString(),amount:v.amount.toString()} as HistoricalImportRecord:undefined}
 async create(r:HistoricalImportRecord){await this.db.$transaction(async tx=>{await this.restore(tx,r);await tx.tourismFinanceOrchestrationHistoricalImport.create({data:{id:r.id,runId:r.runId,collection:r.collection,sourceId:r.sourceId,sourcePayloadHash:r.sourcePayloadHash,companyId:r.companyId,branchId:r.branchId,payload:r.payload as object,payloadJson:r.payloadJson,debit:r.debit,credit:r.credit,amount:r.amount}})})}
 private async restore(tx:Prisma.TransactionClient,r:HistoricalImportRecord){const p=r.payload,c=r.collection;
if(c==='bookingFinancialSetups')await tx.tfoFinancialSetup.create({data:{id:r.sourceId,companyId:r.companyId,category:s(p.category,r.sourceId),receivableAccountId:s(p.receivableAccountId,'historical'),customerAdvanceAccountId:s(p.customerAdvanceAccountId,'historical'),revenueAccountId:s(p.revenueAccountId,'historical'),costAccountId:s(p.costAccountId,'historical'),commissionExpenseAccountId:o(p.commissionExpenseAccountId),commissionLiabilityAccountId:o(p.commissionLiabilityAccountId),active:p.active!==false}});else if(['bookingFinancialWorkflows','programFinancialWorkflows'].includes(c))await tx.tfoWorkflow.create({data:{id:r.sourceId,companyId:r.companyId,branchId:r.branchId,kind:s(p.kind,c==='bookingFinancialWorkflows'?'BOOKING':'PROGRAM'),commandKey:s(p.commandKey,r.sourceId),payloadHash:s(p.payloadHash,r.sourcePayloadHash),sourceType:s(p.sourceType,'HISTORICAL'),sourceId:s(p.sourceId,r.sourceId),status:s(p.status,'COMPLETE'),payload:(p.payload??p) as object,result:p.result as object|undefined,createdAt:d(p.createdAt??p.date),updatedAt:d(p.updatedAt??p.createdAt??p.date)}});else throw new Error(`unsupported TourismFinance historical collection ${c}`)}
 async equivalence(runId:string,companyId:string):Promise<HistoricalEquivalence>{const provenance=await this.db.tourismFinanceOrchestrationHistoricalImport.findMany({where:{runId,companyId},orderBy:[{collection:'asc'},{sourceId:'asc'}]});const ids=(c:string)=>provenance.filter(x=>x.collection===c).map(x=>x.sourceId);const [setups,workflows]=await Promise.all([this.db.tfoFinancialSetup.findMany({where:{companyId,id:{in:ids('bookingFinancialSetups')}}}),this.db.tfoWorkflow.findMany({where:{companyId,id:{in:[...ids('bookingFinancialWorkflows'),...ids('programFinancialWorkflows')]}}})]);const rows=[...setups.map(x=>({value:x,amount:'0'})),...workflows.map(x=>({value:x,amount:'0'}))];return{records:String(rows.length),payloadDigest:createHash('sha256').update(rows.map(x=>JSON.stringify(x,(_,v)=>typeof v==='object'&&v?.constructor?.name==='Decimal'?v.toString():v)).join('\n')).digest('hex'),debit: "0", credit: "0", amount:rows.reduce((a,x)=>add(a,x.amount),'0')}}
}
