import { ContractValidationError, type BranchId, type CompanyId, type DecimalAmount } from '@elhafez/contracts';
declare const quotationIdBrand:unique symbol; export type QuotationId=string&{readonly[quotationIdBrand]:'QuotationId'};
export type QuotationStatus='DRAFT'|'SENT'|'REJECTED'|'ACCEPTED'|'CONVERTED'|'EXPIRED';
export type ApprovalStatus='NOT_REQUIRED'|'PENDING'|'APPROVED'|'REJECTED';
export interface CustomerSnapshot{readonly displayName:string;readonly contactName:string|null;readonly phone:string|null;readonly email:string|null;}
export interface QuotationLine{readonly id:string;readonly description:string;readonly quantity:DecimalAmount;readonly unitPrice:DecimalAmount;readonly discount:DecimalAmount;readonly taxCode:string|null;readonly total:DecimalAmount;readonly manualPriceOverride:boolean;readonly discountRequiresApproval:boolean;}
export interface QuotationRevision{readonly id:string;readonly quotationId:QuotationId;readonly number:number;readonly validityDate:string;readonly notes:string|null;readonly terms:string|null;readonly lines:readonly QuotationLine[];readonly subtotal:DecimalAmount;readonly discountTotal:DecimalAmount;readonly total:DecimalAmount;readonly createdAt:string;readonly sentAt:string|null;}
export interface Quotation{readonly id:QuotationId;readonly companyId:CompanyId;readonly branchId:BranchId;readonly number:string;readonly sourceLeadId:string|null;readonly customerId:string|null;readonly customerSnapshot:CustomerSnapshot;readonly currency:string;readonly status:QuotationStatus;readonly approvalStatus:ApprovalStatus;readonly approvalActorId:string|null;readonly approvalAt:string|null;readonly approvalReason:string|null;readonly currentRevisionId:string;readonly acceptedRevisionId:string|null;readonly rejectedRevisionId:string|null;readonly rejectionReason:string|null;readonly billingInvoiceId:string|null;readonly createdAt:string;readonly updatedAt:string;readonly revisions:readonly QuotationRevision[];}
export interface QuotationHistory{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly quotationId:QuotationId;readonly kind:string;readonly revisionId:string|null;readonly actorId:string;readonly detail:string|null;readonly occurredAt:string;}
export interface LineInput{readonly id?:string;readonly description:string;readonly quantity:string;readonly unitPrice:string;readonly discount?:string;readonly taxCode?:string|null;readonly manualPriceOverride?:boolean;readonly discountRequiresApproval?:boolean;}
export interface CreateQuotationInput{readonly customerId?:string;readonly sourceLeadId?:string;readonly customerSnapshot?:Partial<CustomerSnapshot>;readonly currency:string;readonly validityDate:string;readonly notes?:string;readonly terms?:string;readonly lines:readonly LineInput[];}
export interface EditQuotationInput{readonly validityDate:string;readonly notes?:string|null;readonly terms?:string|null;readonly lines:readonly LineInput[];}
export const quotationId=(v:string):QuotationId=>{const x=v.trim();if(!x)throw new ContractValidationError('quotationId','is required');return x as QuotationId;};
const SCALE=1000000n;
function scaled(value:string,field:string,positive=false):bigint{const x=value.trim();if(!/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(x))throw new ContractValidationError(field,'must be a non-negative decimal with up to 6 decimals');const[w,f='']=x.split('.');const n=BigInt(w!)*SCALE+BigInt(f.padEnd(6,'0'));if(positive&&n<=0n)throw new ContractValidationError(field,'must be positive');return n;}
function decimal(n:bigint):DecimalAmount{const w=n/SCALE,f=n%SCALE;return (f===0n?w.toString():`${w}.${f.toString().padStart(6,'0').replace(/0+$/,'')}`) as DecimalAmount;}
export function buildLines(inputs:readonly LineInput[],newId:()=>string):{lines:QuotationLine[];subtotal:DecimalAmount;discountTotal:DecimalAmount;total:DecimalAmount;approvalRequired:boolean}{if(!inputs.length)throw new ContractValidationError('lines','at least one line is required');let subtotal=0n,discounts=0n;const lines=inputs.map((v,i)=>{const q=scaled(v.quantity,`lines.${i}.quantity`,true),p=scaled(v.unitPrice,`lines.${i}.unitPrice`),d=scaled(v.discount??'0',`lines.${i}.discount`);const gross=q*p/SCALE;if(d>gross)throw new ContractValidationError(`lines.${i}.discount`,'cannot exceed gross amount');subtotal+=gross;discounts+=d;return{id:v.id?.trim()||newId(),description:required(v.description,`lines.${i}.description`),quantity:decimal(q),unitPrice:decimal(p),discount:decimal(d),taxCode:v.taxCode?.trim()||null,total:decimal(gross-d),manualPriceOverride:v.manualPriceOverride===true,discountRequiresApproval:v.discountRequiresApproval===true};});return{lines,subtotal:decimal(subtotal),discountTotal:decimal(discounts),total:decimal(subtotal-discounts),approvalRequired:lines.some(x=>x.manualPriceOverride||x.discountRequiresApproval)};}
export function required(v:string,field:string){const x=v.trim();if(!x)throw new ContractValidationError(field,'is required');return x;}
export function validDate(v:string,field:string){const x=required(v,field);if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw new ContractValidationError(field,'must be a valid ISO date');return x;}
