import type { AuditEntry, Branch, Company, Id, Notification, Permission, Role, Session, StoredFile, User } from '../domain/platform.types.js';

/** Module-private persistence port; infrastructure adapters implement it. */
export interface PlatformCoreRepository {
  transaction<T>(work: () => Promise<T>): Promise<T>;
  findUserById(id: Id): Promise<User | undefined>; findUserByEmail(email: string): Promise<User | undefined>; createUser(user: User): Promise<User>; updateUser(user: User): Promise<User>;
  listUsers(companyId: Id): Promise<readonly User[]>;
  createSession(session: Session): Promise<void>; findSessionByTokenHash(hash: string): Promise<Session | undefined>; findSessionById(id:Id):Promise<Session|undefined>; revokeSession(id: Id, revokedAt: Date): Promise<void>; revokeUserSessions(userId: Id, revokedAt: Date): Promise<void>; revokeCompanySessions(companyId:Id,revokedAt:Date):Promise<void>; revokeAllSessions(revokedAt:Date):Promise<void>; listSessions(userId: Id): Promise<readonly Session[]>;
  createRole(id: Id, name: string): Promise<void>; findRoleByName(name: string): Promise<Id | undefined>; listRoles():Promise<readonly Role[]>; listPermissions():Promise<readonly Permission[]>; createPermission(id: Id, name: string): Promise<void>; assignRole(userId: Id, companyId: Id, roleId: Id): Promise<void>; revokeRole(userId:Id,companyId:Id,roleId:Id):Promise<void>; grantPermission(companyId:Id,roleId: Id, permissionId: Id): Promise<void>; revokePermission(companyId:Id,roleId:Id,permissionId:Id):Promise<void>; hasPermission(userId: Id, companyId: Id, permission: string): Promise<boolean>; saveRecoveryToken(userId: Id, tokenHash: string, expiresAt: Date): Promise<void>; consumeRecoveryToken(tokenHash: string, now: Date): Promise<Id | undefined>; updatePassword(userId: Id, passwordHash: string, updatedAt: Date): Promise<void>;
  createCompany(company: Company): Promise<Company>; bootstrapCompany(input:{company:Company;branch:Branch;actorId:Id;administratorRoleId:Id;administratorRoleName:string}):Promise<{company:Company;branch:Branch;administratorRoleId:Id}>; findCompany(id: Id): Promise<Company | undefined>; listCompanies(userId:Id):Promise<readonly Company[]>; updateCompany(company:Company):Promise<Company>; createBranch(branch: Branch): Promise<Branch>; findBranch(id: Id): Promise<Branch | undefined>; listBranches(companyId:Id):Promise<readonly Branch[]>; updateBranch(branch:Branch):Promise<Branch>; grantBranchAccess(userId: Id, branchId: Id): Promise<void>; revokeBranchAccess(userId:Id,branchId:Id):Promise<void>; hasBranchAccess(userId: Id, branchId: Id): Promise<boolean>;
  recordAudit(entry: AuditEntry): Promise<void>; recordAuditOnce(entry: AuditEntry): Promise<void>; listAudit(companyId?:Id): Promise<readonly AuditEntry[]>; userHasCompanyAccess(userId:Id,companyId:Id):Promise<boolean>; registerFile(file: StoredFile): Promise<StoredFile>; listFiles(companyId:Id):Promise<readonly StoredFile[]>; findFile(companyId:Id,id:Id):Promise<StoredFile|undefined>; retireFile(companyId:Id,id:Id):Promise<void>; notify(notification: Notification): Promise<Notification>; listNotifications(userId:Id):Promise<readonly Notification[]>; markNotificationRead(userId:Id,id:Id,at:Date):Promise<Notification|undefined>; setConfiguration(key: string, value: unknown): Promise<void>; getConfiguration(key: string): Promise<unknown>;
}
export const PLATFORM_CORE_REPOSITORY = Symbol('PLATFORM_CORE_REPOSITORY');
