import { createHash, randomBytes, randomUUID, scrypt as nodeScrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import type { EventPublisher } from '@elhafez/contracts';
import { fail, PlatformError, type AuditEntry, type Branch, type Company, type Id, type Notification, type SessionProjection, type StoredFile, type StoredFileContent, type User, type UserProjection } from '../domain/platform.types.js';
import type { PlatformCoreRepository } from './platform-core.repository.js';

const scrypt = async (password:string,salt:string):Promise<Buffer> => (await promisify(nodeScrypt)(password,salt,64)) as Buffer;
const id = () => randomUUID();
const digest = (value:string) => createHash('sha256').update(value).digest('base64url');
const GENERIC_CONFIGURATION_KEYS = new Set(['locale','timezone','dateFormat','theme','companyName','companyLogo','address','phone','email','notificationPrefs','retention.days']);
export const COMPANY_ADMINISTRATOR_ROLE = 'company-administrator';
export const PLATFORM_CORE_PERMISSIONS = Object.freeze({managementControlRead:'management.control.read',accountingFinanceRead:'accounting.finance.read',accountingFinanceOperate:'accounting.finance.operate'} as const);
export interface RecoveryDeliveryPort { deliver(input:{recipient:string;token:string;expiresAt:Date}):Promise<void> }
export interface FileStoragePort { put(input:{content:Uint8Array;contentType:string}):Promise<{key:string;size:number;checksum:string}>; get(key:string):Promise<Uint8Array>; delete(key:string):Promise<void> }
export class NoopEventPublisher implements EventPublisher { async publish():Promise<void>{} }

export class PlatformCoreApplicationService {
  constructor(private readonly repository:PlatformCoreRepository,private readonly events:EventPublisher=new NoopEventPublisher(),private readonly now:()=>Date=()=>new Date(),private readonly recoveryDelivery:RecoveryDeliveryPort={deliver:async()=>{throw new PlatformError('DELIVERY_UNAVAILABLE','recovery delivery is unavailable')}},private readonly fileStorage?:FileStoragePort){}
  private required(value:string,field:string){if(!value.trim())fail('VALIDATION_ERROR',`${field} is required`,{field});return value.trim()}
  private async password(value:string){if(value.length<12)fail('VALIDATION_ERROR','password must have at least 12 characters',{field:'password'});const salt=randomBytes(16).toString('base64url');return `${salt}:${(await scrypt(value,salt)).toString('base64url')}`}
  private async valid(password:string,stored:string){const [salt,expected]=stored.split(':');if(!salt||!expected)return false;const actual=(await scrypt(password,salt)).toString('base64url');return actual.length===expected.length&&timingSafeEqual(Buffer.from(actual),Buffer.from(expected))}
  private async audit(entry:Omit<AuditEntry,'id'|'occurredAt'>){await this.repository.recordAudit({...entry,id:id(),occurredAt:this.now()})}
  private async user(userId:Id){return await this.repository.findUserById(userId)??fail('NOT_FOUND','user was not found')}
  private publicUser(user:User):UserProjection{return{id:user.id,email:user.email,status:user.status,displayName:user.displayName,createdAt:user.createdAt,updatedAt:user.updatedAt}}

  async createUser(input:{email:string;password:string;displayName:string;actorId?:Id}):Promise<UserProjection>{return this.repository.transaction(async()=>{const email=this.required(input.email,'email').toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))fail('VALIDATION_ERROR','email is invalid');if(await this.repository.findUserByEmail(email))fail('CONFLICT','email already exists');const now=this.now();const user:User={id:id(),email,passwordHash:await this.password(input.password),displayName:this.required(input.displayName,'displayName'),status:'ACTIVE',createdAt:now,updatedAt:now};await this.repository.createUser(user);await this.audit({actorId:input.actorId??null,action:'user.created',resource:'user',entityId:user.id,companyId:null,branchId:null,metadata:{}});await this.events.publish({name:'platform.user.created.v1',occurredAt:now.toISOString(),payload:{userId:user.id}});return this.publicUser(user)})}
  async listUsers(companyId:Id):Promise<readonly UserProjection[]>{return (await this.repository.listUsers(companyId)).map(x=>this.publicUser(x))}
  async getUser(companyId:Id,userId:Id):Promise<UserProjection>{await this.requireUserCompanyAccess(userId,companyId);return this.publicUser(await this.user(userId))}
  async updateUser(actorId:Id,userId:Id,input:{displayName?:string;email?:string}):Promise<UserProjection>{const user=await this.user(userId);if(input.email)user.email=this.required(input.email,'email').toLowerCase();if(input.displayName)user.displayName=this.required(input.displayName,'displayName');user.updatedAt=this.now();await this.repository.updateUser(user);await this.audit({actorId,action:'user.updated',resource:'user',entityId:userId,companyId:null,branchId:null,metadata:{}});return this.publicUser(user)}
  async setUserActive(actorId:Id,userId:Id,active:boolean){const user=await this.user(userId);user.status=active?'ACTIVE':'INACTIVE';user.updatedAt=this.now();await this.repository.updateUser(user);if(!active)await this.repository.revokeUserSessions(userId,this.now());await this.audit({actorId,action:active?'user.activated':'user.deactivated',resource:'user',entityId:userId,companyId:null,branchId:null,metadata:{}});return this.publicUser(user)}

  async login(email:string,password:string){const user=await this.repository.findUserByEmail(email.trim().toLowerCase());if(!user||user.status!=='ACTIVE'||!(await this.valid(password,user.passwordHash)))throw new PlatformError('INVALID_CREDENTIALS','invalid credentials');const token=randomBytes(32).toString('base64url');const expiresAt=new Date(this.now().getTime()+28_800_000);const session={id:id(),userId:user.id,tokenHash:digest(token),expiresAt,revokedAt:null,createdAt:this.now()};await this.repository.createSession(session);await this.audit({actorId:user.id,action:'auth.logged_in',resource:'session',entityId:session.id,companyId:null,branchId:null,metadata:{}});return{token,userId:user.id,expiresAt}}
  async currentUser(token:string){const session=await this.repository.findSessionByTokenHash(digest(token));if(!session||session.revokedAt||session.expiresAt<=this.now())throw new PlatformError('UNAUTHENTICATED','valid session required');const user=await this.user(session.userId);if(user.status!=='ACTIVE')fail('UNAUTHENTICATED','user is inactive');return this.publicUser(user)}
  async logout(token:string){const session=await this.repository.findSessionByTokenHash(digest(token));if(session&&!session.revokedAt){await this.repository.revokeSession(session.id,this.now());await this.audit({actorId:session.userId,action:'auth.logged_out',resource:'session',entityId:session.id,companyId:null,branchId:null,metadata:{}})}}
  async requestPasswordRecovery(email:string){const user=await this.repository.findUserByEmail(email.trim().toLowerCase());if(!user)return;const token=randomBytes(32).toString('base64url');const expiresAt=new Date(this.now().getTime()+900_000);await this.repository.saveRecoveryToken(user.id,digest(token),expiresAt);await this.recoveryDelivery.deliver({recipient:user.email,token,expiresAt});await this.audit({actorId:user.id,action:'auth.recovery.requested',resource:'user',entityId:user.id,companyId:null,branchId:null,metadata:{}})}
  async resetPassword(token:string,password:string){const userId=(await this.repository.consumeRecoveryToken(digest(token),this.now()))??fail('INVALID_RECOVERY_TOKEN','recovery token is invalid or expired');await this.repository.updatePassword(userId,await this.password(password),this.now());await this.repository.revokeUserSessions(userId,this.now());await this.audit({actorId:userId,action:'auth.password.reset',resource:'user',entityId:userId,companyId:null,branchId:null,metadata:{sessionsRevoked:true}})}
  async listSessions(userId:Id):Promise<readonly SessionProjection[]>{return (await this.repository.listSessions(userId)).map(session=>({id:session.id,userId:session.userId,expiresAt:session.expiresAt,revokedAt:session.revokedAt,createdAt:session.createdAt,status:session.revokedAt?'REVOKED':session.expiresAt<=this.now()?'EXPIRED':'ACTIVE'}))}
  async revokeSession(actorId:Id,companyId:Id,sessionId:Id){const session=await this.repository.findSessionById(sessionId)??fail('NOT_FOUND','session was not found');await this.requireUserCompanyAccess(session.userId,companyId);await this.repository.revokeSession(sessionId,this.now());await this.audit({actorId,action:'session.revoked',resource:'session',entityId:sessionId,companyId:null,branchId:null,metadata:{}})}
  async revokeUserSessions(actorId:Id,userId:Id){await this.repository.revokeUserSessions(userId,this.now());await this.audit({actorId,action:'sessions.revoked',resource:'user',entityId:userId,companyId:null,branchId:null,metadata:{}})}
  async revokeCompanySessions(companyId:Id){await this.repository.revokeCompanySessions(companyId,this.now())}
  async revokeAllSessions(){await this.repository.revokeAllSessions(this.now())}

  async createRole(name:string){name=this.required(name,'role');if(await this.repository.findRoleByName(name))fail('CONFLICT','role already exists');const roleId=id();await this.repository.createRole(roleId,name);return roleId}
  async listRoles(){return this.repository.listRoles()} async listPermissions(){return this.repository.listPermissions()}
  async createPermission(name:string){const permissionId=id();await this.repository.createPermission(permissionId,this.required(name,'permission'));return permissionId}
  async assignRole(userId:Id,companyId:Id,roleId:Id){await this.user(userId);if(!await this.repository.findCompany(companyId))fail('NOT_FOUND','company was not found');await this.repository.assignRole(userId,companyId,roleId)}
  async revokeRole(userId:Id,companyId:Id,roleId:Id){await this.repository.revokeRole(userId,companyId,roleId)}
  async grantPermission(companyId:Id,roleId:Id,permissionId:Id){await this.repository.grantPermission(companyId,roleId,permissionId)} async revokePermission(companyId:Id,roleId:Id,permissionId:Id){await this.repository.revokePermission(companyId,roleId,permissionId)}
  async authorize(userId:Id,companyId:Id,permission:string){if(!await this.repository.hasPermission(userId,companyId,permission))fail('FORBIDDEN','permission denied',{permission})}

  async provisionCompanyForPlatformControl(input:{name:string;administratorEmail:string;administratorDisplayName:string}){
    const email=this.required(input.administratorEmail,'administratorEmail').toLowerCase();
    let administrator=await this.repository.findUserByEmail(email),created=false;
    if(!administrator){
      const projection=await this.createUser({email,password:randomBytes(36).toString('base64url'),displayName:this.required(input.administratorDisplayName,'administratorDisplayName')});
      administrator=await this.user(projection.id);created=true;
    }
    const company=await this.createCompany(administrator.id,input.name);
    let invitationStatus:'SENT'|'EXISTING_USER'|'DELIVERY_UNAVAILABLE'=created?'SENT':'EXISTING_USER';
    if(created){try{await this.requestPasswordRecovery(email);}catch(error){if(error instanceof PlatformError&&['DELIVERY_FAILED','DELIVERY_UNAVAILABLE'].includes(error.code))invitationStatus='DELIVERY_UNAVAILABLE';else throw error;}}
    return{company,administrator:this.publicUser(administrator),invitationStatus};
  }
  async createCompany(actorId:Id,name:string){const company:Company={id:id(),name:this.required(name,'company'),active:true,createdAt:this.now()};const branch:Branch={id:id(),companyId:company.id,name:'الرئيسي',active:true,createdAt:this.now()};const boot=await this.repository.bootstrapCompany({company,branch,actorId,administratorRoleId:id(),administratorRoleName:COMPANY_ADMINISTRATOR_ROLE});await this.audit({actorId,action:'company.created',resource:'company',entityId:company.id,companyId:company.id,branchId:boot.branch.id,metadata:{administratorRoleId:boot.administratorRoleId}});return{...boot.company,initialBranchId:boot.branch.id}}
  async listCompanies(userId:Id){return this.repository.listCompanies(userId)} async listAllCompaniesForPlatformControl(){return this.repository.listAllCompanies()} async getCompany(userId:Id,companyId:Id){await this.requireUserCompanyAccess(userId,companyId);return await this.repository.findCompany(companyId)??fail('NOT_FOUND','company was not found')}
  async updateCompany(actorId:Id,companyId:Id,input:{name?:string;active?:boolean}){const company=await this.repository.findCompany(companyId)??fail('NOT_FOUND','company was not found'),previous={name:company.name,active:company.active};if(input.name!==undefined)company.name=this.required(input.name,'company');if(input.active!==undefined){company.active=input.active;if(!input.active)await this.repository.revokeCompanySessions(companyId,this.now())}const updated=await this.repository.updateCompany(company);await this.audit({actorId,action:input.active===false?'company.deactivated':input.active===true?'company.activated':'company.updated',resource:'company',entityId:companyId,companyId,branchId:null,metadata:{previous,next:{name:updated.name,active:updated.active}}});return updated}
  async createBranch(actorId:Id,companyId:Id,name:string){if(!await this.repository.findCompany(companyId))fail('NOT_FOUND','company was not found');const branch:Branch={id:id(),companyId,name:this.required(name,'branch'),active:true,createdAt:this.now()};await this.repository.createBranch(branch);await this.audit({actorId,action:'branch.created',resource:'branch',entityId:branch.id,companyId,branchId:branch.id,metadata:{}});return branch}
  async listBranches(companyId:Id){return this.repository.listBranches(companyId)} async listAccessibleBranches(userId:Id,companyId:Id){await this.requireUserCompanyAccess(userId,companyId);const branches=await this.repository.listBranches(companyId),allowed:Branch[]=[];for(const branch of branches)if(branch.active&&await this.repository.hasBranchAccess(userId,branch.id))allowed.push(branch);return allowed} async getBranch(companyId:Id,branchId:Id):Promise<Branch>{const branch=await this.repository.findBranch(branchId);if(!branch||branch.companyId!==companyId)throw new PlatformError('NOT_FOUND','branch was not found');return branch}
  async updateBranch(actorId:Id,companyId:Id,branchId:Id,input:{name?:string;active?:boolean}){const branch=await this.getBranch(companyId,branchId);const next:Branch={...branch};if(input.name!==undefined)next.name=this.required(input.name,'branch');if(input.active!==undefined)next.active=input.active;return this.repository.updateBranch(next)}
  async grantBranchAccess(userId:Id,branchId:Id){await this.user(userId);if(!await this.repository.findBranch(branchId))fail('NOT_FOUND','branch was not found');await this.repository.grantBranchAccess(userId,branchId)} async revokeBranchAccess(userId:Id,branchId:Id){await this.repository.revokeBranchAccess(userId,branchId)}
  async requireBranchAccess(userId:Id,companyId:Id,branchId:Id){const [branch,company]=await Promise.all([this.repository.findBranch(branchId),this.repository.findCompany(companyId)]);if(!company?.active||!branch||branch.companyId!==companyId||!branch.active||!await this.repository.hasBranchAccess(userId,branchId))fail('FORBIDDEN','branch access denied')}

  async recordAudit(entry:Omit<AuditEntry,'id'|'occurredAt'>){await this.audit(entry)} async recordAuditOnce(key:string,entry:Omit<AuditEntry,'id'|'occurredAt'>){const scope=JSON.stringify([this.required(key,'idempotencyKey'),entry.companyId,entry.branchId,entry.action,entry.resource,entry.entityId]);await this.repository.recordAuditOnce({...entry,id:`audit:${digest(scope)}`,occurredAt:this.now()})}
  async listAudit(companyId?:Id){return this.repository.listAudit(companyId)} async requireUserCompanyAccess(userId:Id,companyId:Id){if(!await this.repository.userHasCompanyAccess(userId,companyId))fail('FORBIDDEN','target user is outside company scope')}
  async registerFile(input:Omit<StoredFile,'id'|'createdAt'|'checksum'>&{checksum?:string|null}){if(input.size<0||!input.key||!input.contentType||input.checksum!==undefined&&input.checksum!==null&&!/^[0-9a-f]{64}$/.test(input.checksum))fail('VALIDATION_ERROR','invalid file metadata');return this.repository.registerFile({...input,checksum:input.checksum??null,id:id(),createdAt:this.now()})}
  async uploadFile(input:{companyId:Id;createdBy:Id;contentType:string;content:Uint8Array}){const storage=this.fileStorage??fail('STORAGE_UNAVAILABLE','file storage is unavailable');const stored=await storage.put({content:input.content,contentType:input.contentType});return this.registerFile({companyId:input.companyId,createdBy:input.createdBy,contentType:input.contentType,key:stored.key,size:stored.size,checksum:stored.checksum})}
  async listFiles(companyId:Id){return this.repository.listFiles(companyId)}
  async getFile(companyId:Id,fileId:Id,includeContent:true):Promise<StoredFileContent>;
  async getFile(companyId:Id,fileId:Id,includeContent?:false):Promise<StoredFile>;
  async getFile(companyId:Id,fileId:Id,includeContent=false):Promise<StoredFile|StoredFileContent>{const metadata=await this.repository.findFile(companyId,fileId)??fail('NOT_FOUND','file was not found');if(!includeContent)return metadata;const content=await (this.fileStorage??fail('STORAGE_UNAVAILABLE','file storage is unavailable')).get(metadata.key);if(!metadata.checksum)fail('FILE_INTEGRITY_UNVERIFIED','stored file has no trusted checksum');const actual=createHash('sha256').update(content).digest('hex');if(actual!==metadata.checksum)fail('FILE_INTEGRITY_ERROR','stored file checksum mismatch');return{metadata,content}}
  async retireFile(companyId:Id,fileId:Id){const file=await this.repository.findFile(companyId,fileId)??fail('NOT_FOUND','file was not found');await (this.fileStorage??fail('STORAGE_UNAVAILABLE','file storage is unavailable')).delete(file.key);await this.repository.retireFile(companyId,fileId)}
  async notify(userId:Id,type:string,payload:Record<string,unknown>):Promise<Notification>{await this.user(userId);return this.repository.notify({id:id(),userId,type:this.required(type,'type'),payload,readAt:null,createdAt:this.now()})}
  async listNotifications(userId:Id){return this.repository.listNotifications(userId)} async markNotificationRead(userId:Id,notificationId:Id){return await this.repository.markNotificationRead(userId,notificationId,this.now())??fail('NOT_FOUND','notification was not found')}
  async setConfiguration(key:string,value:unknown,companyId?:Id){if(!GENERIC_CONFIGURATION_KEYS.has(key))fail('VALIDATION_ERROR','configuration key is not owned by platform-core',{key});await this.repository.setConfiguration(`${companyId??'platform'}:${key}`,value)} async getConfiguration<T>(key:string,companyId?:Id){if(!GENERIC_CONFIGURATION_KEYS.has(key))fail('VALIDATION_ERROR','configuration key is not owned by platform-core',{key});return await this.repository.getConfiguration(`${companyId??'platform'}:${key}`) as T|undefined}
  toError(error:unknown){if(error instanceof PlatformError)return{status:error.code==='VALIDATION_ERROR'?400:error.code==='UNAUTHENTICATED'?401:error.code==='FORBIDDEN'?403:error.code==='NOT_FOUND'?404:error.code==='CONFLICT'?409:500,body:{code:error.code,message:error.message,details:error.details}};return{status:500,body:{code:'INTERNAL_ERROR',message:'an unexpected error occurred'}}}
}
