import { createHash, randomBytes, randomUUID, scrypt as nodeScrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import type { EventPublisher } from '@elhafez/contracts';
import { fail, PlatformError, type AuditEntry, type Branch, type Company, type Id, type Notification, type StoredFile, type User } from '../domain/platform.types.js';
import { InMemoryPlatformRepository } from '../infrastructure/platform.repository.js';

const scrypt = async (password: string, salt: string): Promise<Buffer> => (await promisify(nodeScrypt)(password, salt, 64)) as Buffer;
const ID = () => randomUUID();
/** Tokens are never persisted in recoverable form. */
const hashToken = (token: string) => createHash('sha256').update(token).digest('base64url');
export class NoopEventPublisher implements EventPublisher { async publish(): Promise<void> {} }

export class PlatformCoreApplicationService {
  constructor(private readonly repository = new InMemoryPlatformRepository(), private readonly events: EventPublisher = new NoopEventPublisher(), private readonly now: () => Date = () => new Date()) {}
  private validate(value: string, field: string): string { if (!value.trim()) fail('VALIDATION_ERROR', `${field} is required`, { field }); return value.trim(); }
  private async password(password: string): Promise<string> { if (password.length < 12) fail('VALIDATION_ERROR', 'password must have at least 12 characters', { field: 'password' }); const salt = randomBytes(16).toString('base64url'); return `${salt}:${(await scrypt(password, salt)).toString('base64url')}`; }
  private async verify(password: string, stored: string): Promise<boolean> { const [salt, expected] = stored.split(':'); if (!salt || !expected) return false; const actual = (await scrypt(password, salt)).toString('base64url'); return actual.length === expected.length && timingSafeEqual(Buffer.from(actual), Buffer.from(expected)); }
  private async emit(name: string, payload: Record<string, unknown>): Promise<void> { await this.events.publish({ name, occurredAt: this.now().toISOString(), payload }); }
  private audit(input: Omit<AuditEntry, 'id' | 'occurredAt'>): void { this.repository.audits.push({ ...input, id: ID(), occurredAt: this.now() }); }
  private user(id: Id): User { const user = this.repository.users.get(id); return user ?? fail('NOT_FOUND', 'user was not found'); }

  async createUser(input: { email: string; password: string; displayName: string; actorId?: Id }): Promise<User> { return this.repository.transaction(async () => { const email = this.validate(input.email, 'email').toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email)) fail('VALIDATION_ERROR', 'email is invalid', { field: 'email' }); if ([...this.repository.users.values()].some((u) => u.email === email)) fail('CONFLICT', 'email already exists'); const now = this.now(); const user: User = { id: ID(), email, passwordHash: await this.password(input.password), displayName: this.validate(input.displayName, 'displayName'), status: 'ACTIVE', createdAt: now, updatedAt: now }; this.repository.users.set(user.id, user); this.audit({ actorId: input.actorId ?? null, action: 'user.created', resource: 'user', entityId: user.id, companyId: null, branchId: null, metadata: {} }); await this.emit('platform.user.created.v1', { userId: user.id }); return user; }); }
  async updateUser(actorId: Id, id: Id, input: { displayName?: string; email?: string }): Promise<User> { const user = this.user(id); if (input.email) user.email = this.validate(input.email, 'email').toLowerCase(); if (input.displayName) user.displayName = this.validate(input.displayName, 'displayName'); user.updatedAt = this.now(); this.audit({ actorId, action: 'user.updated', resource: 'user', entityId: id, companyId: null, branchId: null, metadata: {} }); return user; }
  async setUserActive(actorId: Id, id: Id, active: boolean): Promise<User> { const user = this.user(id); user.status = active ? 'ACTIVE' : 'INACTIVE'; user.updatedAt = this.now(); this.audit({ actorId, action: active ? 'user.activated' : 'user.deactivated', resource: 'user', entityId: id, companyId: null, branchId: null, metadata: {} }); return user; }
  async login(email: string, password: string): Promise<{ token: string; userId: Id; expiresAt: Date }> { const candidate = [...this.repository.users.values()].find((item) => item.email === email.trim().toLowerCase()); if (!candidate) throw new PlatformError('INVALID_CREDENTIALS', 'invalid credentials'); const user: User = candidate; if (user.status !== 'ACTIVE' || !(await this.verify(password, user.passwordHash))) throw new PlatformError('INVALID_CREDENTIALS', 'invalid credentials'); const token = randomBytes(32).toString('base64url'); const expiresAt = new Date(this.now().getTime() + 1000 * 60 * 60 * 8); const sessionId = ID(); this.repository.sessions.set(sessionId, { id: sessionId, userId: user.id, tokenHash: hashToken(token), expiresAt, revokedAt: null, createdAt: this.now() }); this.audit({ actorId: user.id, action: 'auth.logged_in', resource: 'session', entityId: null, companyId: null, branchId: null, metadata: {} }); return { token, userId: user.id, expiresAt }; }
  currentUser(token: string): User { const candidate = [...this.repository.sessions.values()].find((item) => item.tokenHash === hashToken(token)); if (!candidate) throw new PlatformError('UNAUTHENTICATED', 'valid session required'); const session = candidate; if (session.revokedAt || session.expiresAt <= this.now()) throw new PlatformError('UNAUTHENTICATED', 'valid session required'); const user = this.user(session.userId); if (user.status !== 'ACTIVE') fail('UNAUTHENTICATED', 'user is inactive'); return user; }
  logout(token: string): void { const session = [...this.repository.sessions.values()].find((item) => item.tokenHash === hashToken(token)); if (session && !session.revokedAt) { session.revokedAt = this.now(); this.audit({ actorId: session.userId, action: 'auth.logged_out', resource: 'session', entityId: session.id, companyId: null, branchId: null, metadata: {} }); } }
  createRole(name: string): Id { name = this.validate(name, 'role'); if ([...this.repository.roles.values()].some((role) => role === name)) fail('CONFLICT', 'role already exists'); const id = ID(); this.repository.roles.set(id, name); return id; }
  createPermission(name: string): Id { name = this.validate(name, 'permission'); const id = ID(); this.repository.permissions.set(id, name); return id; }
  assignRole(userId: Id, roleId: Id): void { this.user(userId); if (!this.repository.roles.has(roleId)) fail('NOT_FOUND', 'role was not found'); (this.repository.userRoles.get(userId) ?? this.repository.userRoles.set(userId, new Set()).get(userId)!).add(roleId); }
  grantPermission(roleId: Id, permissionId: Id): void { if (!this.repository.roles.has(roleId) || !this.repository.permissions.has(permissionId)) fail('NOT_FOUND', 'role or permission was not found'); (this.repository.rolePermissions.get(roleId) ?? this.repository.rolePermissions.set(roleId, new Set()).get(roleId)!).add(permissionId); }
  authorize(userId: Id, permission: string): void { const roles = this.repository.userRoles.get(userId) ?? new Set(); const authorized = [...roles].some((roleId) => [...(this.repository.rolePermissions.get(roleId) ?? new Set())].some((permissionId) => this.repository.permissions.get(permissionId) === permission)); if (!authorized) fail('FORBIDDEN', 'permission denied', { permission }); }
  createCompany(actorId: Id, name: string): Company { const company = { id: ID(), name: this.validate(name, 'company'), active: true, createdAt: this.now() }; this.repository.companies.set(company.id, company); this.audit({ actorId, action: 'company.created', resource: 'company', entityId: company.id, companyId: company.id, branchId: null, metadata: {} }); return company; }
  createBranch(actorId: Id, companyId: Id, name: string): Branch { if (!this.repository.companies.has(companyId)) fail('NOT_FOUND', 'company was not found'); const branch = { id: ID(), companyId, name: this.validate(name, 'branch'), active: true, createdAt: this.now() }; this.repository.branches.set(branch.id, branch); this.audit({ actorId, action: 'branch.created', resource: 'branch', entityId: branch.id, companyId, branchId: branch.id, metadata: {} }); return branch; }
  grantBranchAccess(userId: Id, branchId: Id): void { this.user(userId); if (!this.repository.branches.has(branchId)) fail('NOT_FOUND', 'branch was not found'); (this.repository.branchAccess.get(userId) ?? this.repository.branchAccess.set(userId, new Set()).get(userId)!).add(branchId); }
  requireBranchAccess(userId: Id, companyId: Id, branchId: Id): void { const branch = this.repository.branches.get(branchId); if (!branch || branch.companyId !== companyId || !branch.active) fail('FORBIDDEN', 'branch is outside company scope'); if (!(this.repository.branchAccess.get(userId)?.has(branchId))) fail('FORBIDDEN', 'branch access denied'); }
  recordAudit(entry: Omit<AuditEntry, 'id' | 'occurredAt'>): void { this.audit(entry); }
  listAudit(): readonly AuditEntry[] { return this.repository.audits; }
  registerFile(input: Omit<StoredFile, 'id' | 'createdAt'>): StoredFile { if (input.size < 0 || !input.key || !input.contentType) fail('VALIDATION_ERROR', 'invalid file metadata'); const file = { ...input, id: ID(), createdAt: this.now() }; this.repository.files.set(file.id, file); return file; }
  notify(userId: Id, type: string, payload: Record<string, unknown>): Notification { this.user(userId); const notification = { id: ID(), userId, type: this.validate(type, 'type'), payload, readAt: null, createdAt: this.now() }; this.repository.notifications.set(notification.id, notification); return notification; }
  setConfiguration(key: string, value: unknown): void { this.repository.config.set(this.validate(key, 'key'), value); }
  getConfiguration<T>(key: string): T | undefined { return this.repository.config.get(key) as T | undefined; }
  toError(error: unknown): { status: number; body: { code: string; message: string; details?: Record<string, unknown> } } { if (error instanceof PlatformError) return { status: error.code === 'VALIDATION_ERROR' ? 400 : error.code === 'UNAUTHENTICATED' ? 401 : error.code === 'FORBIDDEN' ? 403 : error.code === 'NOT_FOUND' ? 404 : error.code === 'CONFLICT' ? 409 : 500, body: { code: error.code, message: error.message, details: error.details } }; return { status: 500, body: { code: 'INTERNAL_ERROR', message: 'an unexpected error occurred' } }; }
}
