import{type FormEvent,useEffect,useState}from'react';
import{accountingApi,type AccountingCapabilities,type AccountingOverview,type AccountClassification,type FinancialAction}from'./accounting-client.js';
import{ActionBar,Badge,Button,Card,DataGrid,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select,Tabs,Toast}from'./ui.js';
import{AssetsFinancingSection,CostBudgetSection,CurrencyFxSection,ExpenseCommissionSection,PartyAccountingSection}from'./advanced-accounting-sections.js';

const emptyOverview:AccountingOverview={
 fiscalYears:[],periods:[],accounts:[],journals:[],invoices:[],treasuries:[],vouchers:[],taxPolicies:[],approvalPolicies:[],approvalRequests:[],controlIssues:[],
 reports:{trialBalance:{rows:[]},incomeStatement:{rows:[]},balanceSheet:{rows:[]},treasury:{totals:[]},tax:{totals:[],facts:[]}},
};
const classLabel:Record<AccountClassification,string>={ASSET:'أصول',LIABILITY:'التزامات',EQUITY:'حقوق ملكية',REVENUE:'إيرادات',EXPENSE:'مصروفات'};
const actionLabel:Record<FinancialAction,string>={PAYMENT:'دفعة',PAID_EXPENSE:'مصروف مدفوع',PARTY_NETTING:'مقاصة طرف',COMMISSION_APPROVAL:'اعتماد عمولة',BOOKING_DISCOUNT:'خصم حجز',SERVICE_DISCOUNT:'خصم خدمة'};
const tabs=[
 {id:'overview',label:'نظرة عامة'},{id:'accounts',label:'دليل الحسابات'},{id:'journals',label:'القيود'},{id:'periods',label:'الفترات'},
 {id:'billing',label:'الذمم والفواتير'},{id:'treasury',label:'الخزائن والبنوك'},{id:'currency-fx',label:'العملات والصرف'},{id:'cost-budget',label:'مراكز التكلفة والموازنات'},
 {id:'party-accounting',label:'حسابات الأطراف والمقاصة'},{id:'expense-commission',label:'المصروفات والعمولات'},{id:'assets-financing',label:'الأصول والتمويل'},
 {id:'tax',label:'الضرائب'},{id:'controls',label:'الرقابة والاعتمادات'},{id:'reports',label:'التقارير'},
];

export function AccountingWorkspacePage(){
 const[data,setData]=useState<AccountingOverview>(emptyOverview),[cap,setCap]=useState<AccountingCapabilities>({read:false,operate:false}),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function reload(){setLoading(true);setError('');try{const[c,o]=await Promise.all([accountingApi.capabilities(),accountingApi.overview()]);setCap(c);setData(o);}catch(value){setError(value instanceof Error?value.message:'تعذر تحميل المحاسبة.');}finally{setLoading(false);}}
 async function done(message:string){setNotice(message);await reload();}
 useEffect(()=>{void reload();},[]);
 if(loading)return <LoadingState/>;if(error)return <ErrorState message={error}/>;if(!cap.read)return <EmptyState title="لا توجد صلاحية للمحاسبة"/>;
 return <section dir="rtl" className="ui-page-stack">
  {notice?<Toast tone="success">{notice}</Toast>:null}
  <Card title="المحاسبة والمالية"><p>مساحة تشغيل موحدة تعتمد مباشرة على مصادر الحقيقة المحاسبية المعتمدة؛ لا تحتفظ بأي أرصدة أو قيود مكررة.</p><ActionBar><Button variant="secondary" onClick={()=>void reload()}>تحديث</Button></ActionBar></Card>
  <Tabs tabs={tabs} active={tab} onChange={setTab}/>
  {tab==='overview'?<Overview data={data}/>:null}
  {tab==='accounts'?<Accounts data={data} operate={cap.operate} done={done}/>:null}
  {tab==='journals'?<Journals data={data} operate={cap.operate} done={done}/>:null}
  {tab==='periods'?<Periods data={data} operate={cap.operate} done={done}/>:null}
  {tab==='billing'?<Billing data={data} operate={cap.operate} done={done}/>:null}
  {tab==='treasury'?<Treasury data={data} operate={cap.operate} done={done}/>:null}
  {tab==='currency-fx'?<CurrencyFxSection/>:null}
  {tab==='cost-budget'?<CostBudgetSection/>:null}
  {tab==='party-accounting'?<PartyAccountingSection/>:null}
  {tab==='expense-commission'?<ExpenseCommissionSection/>:null}
  {tab==='assets-financing'?<AssetsFinancingSection/>:null}
  {tab==='tax'?<Tax data={data} operate={cap.operate} done={done}/>:null}
  {tab==='controls'?<Controls data={data} operate={cap.operate} done={done}/>:null}
  {tab==='reports'?<Reports data={data}/>:null}
 </section>;
}

function Overview({data}:{data:AccountingOverview}){return <div className="ui-grid-md">
 <MetricCard label="الحسابات" value={data.accounts.length}/><MetricCard label="القيود" value={data.journals.length}/><MetricCard label="الفواتير المفتوحة" value={data.invoices.filter(x=>x.status==='POSTED'&&x.outstanding!=='0').length}/><MetricCard label="الخزائن والبنوك" value={data.treasuries.filter(x=>x.active).length}/>
 <MetricCard label="سياسات الضرائب" value={data.taxPolicies.length}/><MetricCard label="طلبات اعتماد معلقة" value={data.approvalRequests.filter(x=>x.status==='PENDING').length}/>
</div>}

function Accounts({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState({code:'',name:'',classification:'ASSET' as AccountClassification,parentId:'',controlType:''});
 async function submit(e:FormEvent){e.preventDefault();await accountingApi.createAccount({...form,postable:true,...(form.parentId?{parentId:form.parentId}:{}),...(form.controlType?{controlType:form.controlType}:{})});setForm({code:'',name:'',classification:'ASSET',parentId:'',controlType:''});await done('تم إنشاء الحساب من خلال دفتر الأستاذ العام.');}
 return <><Card title="دليل الحسابات">{operate?<form className="ui-filter-grid" onSubmit={submit}><FormField label="الكود" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField><FormField label="اسم الحساب" required><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FormField><FormField label="التصنيف"><Select value={form.classification} onChange={e=>setForm({...form,classification:e.target.value as AccountClassification})}>{Object.entries(classLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="الحساب الأب"><Input value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}/></FormField><Button type="submit">إنشاء حساب</Button></form>:null}</Card>
 <DataGrid columns={['الكود','الحساب','التصنيف','الحالة']}>{data.accounts.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{classLabel[x.classification]}</td><td><Badge tone={x.active?'success':'neutral'}>{x.active?'نشط':'غير نشط'}</Badge></td></tr>)}</DataGrid></>;
}

function Journals({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState({number:'',postingDate:'',debitAccount:'',creditAccount:'',amount:''});
 async function submit(e:FormEvent){e.preventDefault();await accountingApi.postManualJournal({commandKey:crypto.randomUUID(),number:form.number,postingDate:form.postingDate,lines:[{accountId:form.debitAccount,debit:form.amount},{accountId:form.creditAccount,credit:form.amount}]});setForm({number:'',postingDate:'',debitAccount:'',creditAccount:'',amount:''});await done('تم ترحيل القيد عبر General Ledger.');}
 return <><Card title="قيد يدوي متوازن">{operate?<form className="ui-filter-grid" onSubmit={submit}><FormField label="رقم القيد" required><Input required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={form.postingDate} onChange={e=>setForm({...form,postingDate:e.target.value})}/></FormField><FormField label="الحساب المدين" required><Select required value={form.debitAccount} onChange={e=>setForm({...form,debitAccount:e.target.value})}><option value="">اختر</option>{data.accounts.filter(x=>x.active&&x.postable).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="الحساب الدائن" required><Select required value={form.creditAccount} onChange={e=>setForm({...form,creditAccount:e.target.value})}><option value="">اختر</option>{data.accounts.filter(x=>x.active&&x.postable).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></FormField><Button type="submit">ترحيل القيد</Button></form>:null}</Card>
 <DataGrid columns={['الرقم','التاريخ','النوع','المصدر']}>{data.journals.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.postingDate}</td><td>{x.kind}</td><td>{x.sourceType}</td></tr>)}</DataGrid></>;
}

function Periods({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[year,setYear]=useState({startDate:'',endDate:''}),[period,setPeriod]=useState({fiscalYearId:'',startDate:'',endDate:''});
 async function addYear(e:FormEvent){e.preventDefault();await accountingApi.createFiscalYear(year);setYear({startDate:'',endDate:''});await done('تم إنشاء السنة المالية.');}
 async function addPeriod(e:FormEvent){e.preventDefault();await accountingApi.createPeriod(period);setPeriod({fiscalYearId:'',startDate:'',endDate:''});await done('تم إنشاء الفترة المحاسبية.');}
 async function toggle(id:string,status:'OPEN'|'CLOSED'){await accountingApi.setPeriodStatus(id,status);await done(status==='CLOSED'?'تم إغلاق الفترة.':'تم إعادة فتح الفترة.');}
 return <><div className="ui-grid-md">{operate?<Card title="سنة مالية"><form onSubmit={addYear}><FormField label="من"><Input required type="date" value={year.startDate} onChange={e=>setYear({...year,startDate:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={year.endDate} onChange={e=>setYear({...year,endDate:e.target.value})}/></FormField><Button type="submit">إنشاء</Button></form></Card>:null}{operate?<Card title="فترة محاسبية"><form onSubmit={addPeriod}><FormField label="السنة"><Select required value={period.fiscalYearId} onChange={e=>setPeriod({...period,fiscalYearId:e.target.value})}><option value="">اختر</option>{data.fiscalYears.map(x=><option key={x.id} value={x.id}>{x.startDate} — {x.endDate}</option>)}</Select></FormField><FormField label="من"><Input required type="date" value={period.startDate} onChange={e=>setPeriod({...period,startDate:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={period.endDate} onChange={e=>setPeriod({...period,endDate:e.target.value})}/></FormField><Button type="submit">إنشاء</Button></form></Card>:null}</div>
 <DataGrid columns={['السنة','من','إلى','الحالة','الإجراء']}>{data.periods.map(x=><tr key={x.id}><td>{x.fiscalYearId}</td><td>{x.startDate}</td><td>{x.endDate}</td><td><Badge tone={x.status==='OPEN'?'success':'neutral'}>{x.status==='OPEN'?'مفتوحة':'مغلقة'}</Badge></td><td>{operate?<Button variant="secondary" onClick={()=>void toggle(x.id,x.status==='OPEN'?'CLOSED':'OPEN')}>{x.status==='OPEN'?'إغلاق':'إعادة فتح'}</Button>:null}</td></tr>)}</DataGrid></>;
}

function Billing({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState({type:'CUSTOMER' as 'CUSTOMER'|'SUPPLIER',partyId:'',number:'',postingDate:'',dueDate:'',currency:'EGP',controlAccountId:'',lineAccountId:'',amount:'',taxCode:'',deferred:false});
 const[cancel,setCancel]=useState({invoiceId:'',postingDate:'',number:''});
 async function create(e:FormEvent){e.preventDefault();await accountingApi.createInvoice({commandKey:crypto.randomUUID(),type:form.type,partyId:form.partyId,number:form.number,postingDate:form.postingDate,...(form.dueDate?{dueDate:form.dueDate}:{}),currency:form.currency,controlAccountId:form.controlAccountId,deferred:form.deferred,lines:[{accountId:form.lineAccountId,amount:form.amount,...(form.taxCode?{taxCode:form.taxCode}:{})}]});setForm({type:'CUSTOMER',partyId:'',number:'',postingDate:'',dueDate:'',currency:'EGP',controlAccountId:'',lineAccountId:'',amount:'',taxCode:'',deferred:false});await done('تم إنشاء الفاتورة وترحيلها عبر Billing/Subledgers.');}
 async function cancelInvoice(e:FormEvent){e.preventDefault();await accountingApi.cancelInvoice(cancel.invoiceId,{postingDate:cancel.postingDate,number:cancel.number});setCancel({invoiceId:'',postingDate:'',number:''});await done('تم إلغاء الفاتورة بقيد عكسي من المالك المحاسبي.');}
 return <><div className="ui-grid-md">{operate?<Card title="فاتورة محاسبية"><form className="ui-filter-grid" onSubmit={create}><FormField label="النوع"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value as 'CUSTOMER'|'SUPPLIER'})}><option value="CUSTOMER">عميل</option><option value="SUPPLIER">مورد</option></Select></FormField><FormField label="معرف الطرف" required><Input required value={form.partyId} onChange={e=>setForm({...form,partyId:e.target.value})}/></FormField><FormField label="رقم الفاتورة" required><Input required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={form.postingDate} onChange={e=>setForm({...form,postingDate:e.target.value})}/></FormField><FormField label="الاستحقاق"><Input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></FormField><FormField label="العملة"><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="حساب الرقابة" required><Select required value={form.controlAccountId} onChange={e=>setForm({...form,controlAccountId:e.target.value})}><option value="">اختر</option>{data.accounts.filter(x=>x.active&&x.postable).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="حساب البند" required><Select required value={form.lineAccountId} onChange={e=>setForm({...form,lineAccountId:e.target.value})}><option value="">اختر</option>{data.accounts.filter(x=>x.active&&x.postable).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></FormField><FormField label="كود الضريبة"><Input value={form.taxCode} onChange={e=>setForm({...form,taxCode:e.target.value.toUpperCase()})}/></FormField><Button type="submit">إنشاء وترحيل</Button></form></Card>:null}
 {operate?<Card title="إلغاء فاتورة"><form onSubmit={cancelInvoice}><FormField label="الفاتورة" required><Select required value={cancel.invoiceId} onChange={e=>setCancel({...cancel,invoiceId:e.target.value})}><option value="">اختر فاتورة مرحّلة</option>{data.invoices.filter(x=>x.status==='POSTED').map(x=><option key={x.id} value={x.id}>{x.number} — {x.partyId}</option>)}</Select></FormField><FormField label="تاريخ الإلغاء" required><Input required type="date" value={cancel.postingDate} onChange={e=>setCancel({...cancel,postingDate:e.target.value})}/></FormField><FormField label="رقم القيد العكسي" required><Input required value={cancel.number} onChange={e=>setCancel({...cancel,number:e.target.value})}/></FormField><Button variant="danger" type="submit">إلغاء محاسبي</Button></form></Card>:null}</div>
 <DataGrid columns={['الفاتورة','النوع','الطرف','العملة','الإجمالي','المتبقي','الحالة']}>{data.invoices.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.type}</td><td>{x.partyId}</td><td>{x.currency}</td><td>{x.baseTotal}</td><td>{x.outstanding}</td><td>{x.status}</td></tr>)}</DataGrid></>;
}

function Treasury({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState({code:'',name:'',type:'CASH' as 'CASH'|'BANK',currency:'EGP',glAccountId:''});
 const[settlement,setSettlement]=useState({invoiceId:'',treasuryId:'',number:'',postingDate:'',amount:''});
 async function submit(e:FormEvent){e.preventDefault();await accountingApi.createTreasury(form);setForm({code:'',name:'',type:'CASH',currency:'EGP',glAccountId:''});await done('تم إنشاء الخزينة/الحساب البنكي.');}
 async function settle(e:FormEvent){e.preventDefault();await accountingApi.postSettlement({commandKey:crypto.randomUUID(),...settlement});setSettlement({invoiceId:'',treasuryId:'',number:'',postingDate:'',amount:''});await done('تم تسجيل التحصيل/السداد وتسويته على الفاتورة.');}
 return <><div className="ui-grid-md"><Card title="الخزائن والبنوك">{operate?<form className="ui-filter-grid" onSubmit={submit}><FormField label="الكود"><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField><FormField label="الاسم"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FormField><FormField label="النوع"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value as 'CASH'|'BANK'})}><option value="CASH">خزينة</option><option value="BANK">بنك</option></Select></FormField><FormField label="العملة"><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="حساب الأستاذ"><Select required value={form.glAccountId} onChange={e=>setForm({...form,glAccountId:e.target.value})}><option value="">اختر</option>{data.accounts.filter(x=>x.active&&x.postable).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><Button type="submit">إنشاء</Button></form>:null}</Card>
 {operate?<Card title="تحصيل / سداد فاتورة"><form onSubmit={settle}><FormField label="الفاتورة" required><Select required value={settlement.invoiceId} onChange={e=>setSettlement({...settlement,invoiceId:e.target.value})}><option value="">اختر فاتورة مفتوحة</option>{data.invoices.filter(x=>x.status==='POSTED'&&x.outstanding!=='0').map(x=><option key={x.id} value={x.id}>{x.number} — {x.outstanding} {x.currency}</option>)}</Select></FormField><FormField label="الخزينة / البنك" required><Select required value={settlement.treasuryId} onChange={e=>setSettlement({...settlement,treasuryId:e.target.value})}><option value="">اختر</option>{data.treasuries.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="رقم المستند" required><Input required value={settlement.number} onChange={e=>setSettlement({...settlement,number:e.target.value})}/></FormField><FormField label="التاريخ" required><Input required type="date" value={settlement.postingDate} onChange={e=>setSettlement({...settlement,postingDate:e.target.value})}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={settlement.amount} onChange={e=>setSettlement({...settlement,amount:e.target.value})}/></FormField><Button type="submit">ترحيل التسوية</Button></form></Card>:null}</div>
 <DataGrid columns={['الكود','الاسم','النوع','العملة','الحالة']}>{data.treasuries.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.type==='BANK'?'بنك':'خزينة'}</td><td>{x.currency}</td><td>{x.active?'نشط':'غير نشط'}</td></tr>)}</DataGrid>
 <Card title="الحركة"><DataGrid columns={['المستند','النوع','التاريخ','العملة','المبلغ','الحالة']}>{data.vouchers.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.kind}</td><td>{x.postingDate}</td><td>{x.currency}</td><td>{x.amount}</td><td>{x.status}</td></tr>)}</DataGrid></Card></>;
}

function Tax({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState({code:'',effectiveFrom:'',rate:'',outputAccountId:'',inputAccountId:''});
 async function submit(e:FormEvent){e.preventDefault();await accountingApi.configureTax(form);setForm({code:'',effectiveFrom:'',rate:'',outputAccountId:'',inputAccountId:''});await done('تم حفظ سياسة الضريبة من خلال Tax owner.');}
 return <><Card title="إعداد ضريبة">{operate?<form className="ui-filter-grid" onSubmit={submit}><FormField label="الكود" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></FormField><FormField label="سارية من" required><Input required type="date" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})}/></FormField><FormField label="المعدل" hint="مثال: 0.14"><Input required inputMode="decimal" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></FormField><FormField label="حساب ضريبة المخرجات" required><Select required value={form.outputAccountId} onChange={e=>setForm({...form,outputAccountId:e.target.value})}><option value="">اختر</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><FormField label="حساب ضريبة المدخلات" required><Select required value={form.inputAccountId} onChange={e=>setForm({...form,inputAccountId:e.target.value})}><option value="">اختر</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></FormField><Button type="submit">حفظ السياسة</Button></form>:null}</Card>
 <DataGrid columns={['الكود','سارية من','المعدل','مخرجات','مدخلات']}>{data.taxPolicies.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.effectiveFrom}</td><td>{x.rate}</td><td>{x.outputAccountId}</td><td>{x.inputAccountId}</td></tr>)}</DataGrid></>;
}

function Controls({data,operate,done}:{data:AccountingOverview;operate:boolean;done:(message:string)=>Promise<void>}){
 const[policy,setPolicy]=useState({action:'PAYMENT' as FinancialAction,threshold:'0',active:true,forbidSelfApproval:true,requiredAuthority:''});
 const[decision,setDecision]=useState({requestId:'',outcome:'APPROVED' as 'APPROVED'|'REJECTED',reason:''});
 async function save(e:FormEvent){e.preventDefault();await accountingApi.configureApprovalPolicy(policy);await done('تم حفظ سياسة الاعتماد المالي.');}
 async function decide(e:FormEvent){e.preventDefault();await accountingApi.decideApproval(decision.requestId,{outcome:decision.outcome,...(decision.reason?{reason:decision.reason}:{})});setDecision({requestId:'',outcome:'APPROVED',reason:''});await done('تم تسجيل قرار الاعتماد من خلال Financial Controls.');}
 return <><div className="ui-grid-md">{operate?<Card title="سياسة اعتماد"><form onSubmit={save}><FormField label="الإجراء"><Select value={policy.action} onChange={e=>setPolicy({...policy,action:e.target.value as FinancialAction})}>{Object.entries(actionLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="حد الاعتماد"><Input required inputMode="decimal" value={policy.threshold} onChange={e=>setPolicy({...policy,threshold:e.target.value})}/></FormField><FormField label="الصلاحية المطلوبة"><Input required value={policy.requiredAuthority} onChange={e=>setPolicy({...policy,requiredAuthority:e.target.value})}/></FormField><Button type="submit">حفظ السياسة</Button></form></Card>:null}
 {operate?<Card title="قرار اعتماد"><form onSubmit={decide}><FormField label="الطلب"><Select required value={decision.requestId} onChange={e=>setDecision({...decision,requestId:e.target.value})}><option value="">اختر طلبًا معلقًا</option>{data.approvalRequests.filter(x=>x.status==='PENDING').map(x=><option key={x.id} value={x.id}>{actionLabel[x.action]} — {x.amount}</option>)}</Select></FormField><FormField label="القرار"><Select value={decision.outcome} onChange={e=>setDecision({...decision,outcome:e.target.value as 'APPROVED'|'REJECTED'})}><option value="APPROVED">موافقة</option><option value="REJECTED">رفض</option></Select></FormField><FormField label="السبب"><Input value={decision.reason} onChange={e=>setDecision({...decision,reason:e.target.value})}/></FormField><Button type="submit">تسجيل القرار</Button></form></Card>:null}</div>
 <Card title="سياسات الاعتماد"><DataGrid columns={['الإجراء','الحد','الصلاحية','الحالة']}>{data.approvalPolicies.map(x=><tr key={x.id}><td>{actionLabel[x.action]}</td><td>{x.threshold}</td><td>{x.requiredAuthority}</td><td>{x.active?'نشطة':'متوقفة'}</td></tr>)}</DataGrid></Card>
 <Card title="مشكلات الرقابة"><DataGrid columns={['المفتاح','المصدر','الأستاذ','الفرق','الحالة']}>{data.controlIssues.map(x=><tr key={x.id}><td>{x.evidenceKey}</td><td>{x.sourceAmount}</td><td>{x.ledgerAmount}</td><td>{x.difference}</td><td>{x.resolvedAt?'مغلقة':'مفتوحة'}</td></tr>)}</DataGrid></Card></>;
}

function Reports({data}:{data:AccountingOverview}){return <div className="ui-grid-md"><Card title="ميزان المراجعة"><ReportTable rows={data.reports.trialBalance.rows}/></Card><Card title="قائمة الدخل"><ReportTable rows={data.reports.incomeStatement.rows}/></Card><Card title="المركز المالي"><ReportTable rows={data.reports.balanceSheet.rows}/></Card><Card title="إجمالي الخزائن"><DataGrid columns={['العملة','الإجمالي']}>{data.reports.treasury.totals.map(x=><tr key={x.currency}><td>{x.currency}</td><td>{x.amount}</td></tr>)}</DataGrid></Card><Card title="الضرائب"><DataGrid columns={['العملة','الإجمالي']}>{data.reports.tax.totals.map(x=><tr key={x.currency}><td>{x.currency}</td><td>{x.amount}</td></tr>)}</DataGrid></Card></div>}
function ReportTable({rows}:{rows:{accountId?:string;accountClass?:string;currency:string;amount:string}[]}){return <DataGrid columns={['البند','العملة','القيمة']}>{rows.map((x,i)=><tr key={(x.accountId??x.accountClass??'row')+i}><td>{x.accountId??x.accountClass??'—'}</td><td>{x.currency}</td><td>{x.amount}</td></tr>)}</DataGrid>}
