import{useEffect,useRef,useState,type FormEvent}from'react';
import{crmGet}from'./crm-core-client.js';
import{accountingApi,type AccountRow,type BankLineRow,type ChequeRow,type FiscalYearCloseResult,type FiscalYearRow,type OpeningLineInput,type TreasuryRow,type VoucherRow}from'./accounting-client.js';
import{Badge,Button,Card,DataGrid,FormField,Input,Select,Toast}from'./ui.js';
import{PeriodClosePanel}from'./period-close-panel.js';

type Done=(message:string)=>Promise<void>;
type CustomerReference={customer:{id:string;partyId:string;number:string;status:string};party:{id:string;displayName:string}};
const errorMessage=(value:unknown)=>value instanceof Error?value.message:'تعذر تنفيذ العملية.';
function useCommandKey(){const ref=useRef<string|null>(null);return{get:()=>ref.current??(ref.current=crypto.randomUUID()),reset:()=>{ref.current=null;}};}
const accountLabel=(value:AccountRow)=>`${value.code} — ${value.name}`;

export function FiscalYearClosePanel({fiscalYears,accounts,operate,done}:{fiscalYears:readonly FiscalYearRow[];accounts:readonly AccountRow[];operate:boolean;done:Done}){
 const[yearId,setYearId]=useState(''),[equityId,setEquityId]=useState(''),[number,setNumber]=useState(''),[reopenDate,setReopenDate]=useState(''),[result,setResult]=useState<FiscalYearCloseResult|null>(null),[error,setError]=useState('');
 const key=useCommandKey(),year=fiscalYears.find(value=>value.id===yearId),equity=accounts.filter(value=>value.active&&value.postable&&value.classification==='EQUITY'&&!value.controlType);
 async function close(event:FormEvent){event.preventDefault();setError('');try{const value=await accountingApi.closeFiscalYear(yearId,{commandKey:key.get(),retainedEarningsAccountId:equityId,number});setResult(value);key.reset();if(value.closed)await done(value.alreadyClosed?'السنة المالية مغلقة بالفعل.':'تم إقفال السنة المالية.');}catch(value){setError(errorMessage(value));}}
 async function reopen(){setError('');try{const value=await accountingApi.reopenFiscalYear(yearId,{number,...(reopenDate?{postingDate:reopenDate}:{})});setResult(null);await done(value.reopened?'تمت إعادة فتح السنة المالية بالقيد العكسي.':'السنة المالية مفتوحة بالفعل.');}catch(value){setError(errorMessage(value));}}
 return <Card title="إقفال السنة المالية وإعادة فتحها">
  {error?<Toast tone="error">{error}</Toast>:null}
  <form className="ui-filter-grid" onSubmit={close}>
   <FormField label="السنة المالية" required><Select required value={yearId} onChange={event=>setYearId(event.target.value)}><option value="">اختر</option>{fiscalYears.map(value=><option key={value.id} value={value.id}>{value.startDate} — {value.endDate} ({value.status==='OPEN'?'مفتوحة':'مغلقة'})</option>)}</Select></FormField>
   <FormField label="حساب الأرباح المحتجزة" required><Select required value={equityId} onChange={event=>setEquityId(event.target.value)}><option value="">اختر</option>{equity.map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField>
   <FormField label="رقم قيد الإقفال" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField>
   <Button type="submit" disabled={!operate||!year||year.status!=='OPEN'}>إقفال السنة</Button>
  </form>
  <div className="ui-filter-grid">
   <FormField label="تاريخ القيد العكسي"><Input type="date" value={reopenDate} onChange={event=>setReopenDate(event.target.value)}/></FormField>
   <Button variant="secondary" disabled={!operate||!year||year.status!=='CLOSED'||!number} onClick={()=>void reopen()}>إعادة فتح السنة</Button>
  </div>
  <PeriodClosePanel outcome={result}/>
 </Card>;
}

export function OpeningBalancesPanel({accounts,operate,done}:{accounts:readonly AccountRow[];operate:boolean;done:Done}){
 const[date,setDate]=useState(''),[number,setNumber]=useState(''),[lines,setLines]=useState<OpeningLineInput[]>([{accountId:''},{accountId:''}]),[customers,setCustomers]=useState<CustomerReference[]>([]),[customer,setCustomer]=useState({partyId:'',number:'',postingDate:'',dueDate:'',currency:'EGP',controlAccountId:'',lineAccountId:'',amount:''}),[error,setError]=useState('');
 const glKey=useCommandKey(),customerKey=useCommandKey();
 useEffect(()=>{void crmGet<CustomerReference[]>('/crm/customers?status=ACTIVE').then(setCustomers).catch(value=>setError(errorMessage(value)));},[]);
 const balanceAccounts=accounts.filter(value=>value.active&&value.postable&&value.classification!=='REVENUE'&&value.classification!=='EXPENSE'&&!value.controlType);
 const patch=(index:number,value:Partial<OpeningLineInput>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...value}:line));
 async function postGl(event:FormEvent){event.preventDefault();setError('');try{await accountingApi.postOpeningBalances({commandKey:glKey.get(),number,postingDate:date,lines:lines.map(line=>({accountId:line.accountId,...(line.debit?{debit:line.debit}:{}),...(line.credit?{credit:line.credit}:{})}))});glKey.reset();setLines([{accountId:''},{accountId:''}]);await done('تم ترحيل الأرصدة الافتتاحية إلى دفتر الأستاذ.');}catch(value){setError(errorMessage(value));}}
 async function postCustomer(event:FormEvent){event.preventDefault();setError('');try{await accountingApi.postCustomerOpeningBalance({commandKey:customerKey.get(),partyId:customer.partyId,number:customer.number,postingDate:customer.postingDate,...(customer.dueDate?{dueDate:customer.dueDate}:{}),currency:customer.currency,controlAccountId:customer.controlAccountId,lines:[{accountId:customer.lineAccountId,amount:customer.amount}]});customerKey.reset();setCustomer({partyId:'',number:'',postingDate:'',dueDate:'',currency:'EGP',controlAccountId:'',lineAccountId:'',amount:''});await done('تم ترحيل رصيد العميل الافتتاحي عبر Billing/Subledgers.');}catch(value){setError(errorMessage(value));}}
 return <div className="ui-grid-md">
  {error?<Toast tone="error">{error}</Toast>:null}
  <Card title="أرصدة افتتاحية — دفتر الأستاذ"><form className="ui-filter-grid" onSubmit={postGl}>
   <FormField label="تاريخ الترحيل" required><Input required type="date" value={date} onChange={event=>setDate(event.target.value)}/></FormField><FormField label="رقم القيد" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField>
   {lines.map((line,index)=><div key={index} className="ui-filter-grid"><FormField label={`الحساب ${index+1}`} required><Select required value={line.accountId} onChange={event=>patch(index,{accountId:event.target.value})}><option value="">اختر</option>{balanceAccounts.map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="مدين"><Input inputMode="decimal" value={line.debit??''} onChange={event=>patch(index,{debit:event.target.value||undefined,credit:undefined})}/></FormField><FormField label="دائن"><Input inputMode="decimal" value={line.credit??''} onChange={event=>patch(index,{credit:event.target.value||undefined,debit:undefined})}/></FormField></div>)}
   <Button type="button" variant="secondary" onClick={()=>setLines(current=>[...current,{accountId:''}])}>إضافة سطر</Button><Button type="submit" disabled={!operate}>ترحيل الافتتاحي</Button>
  </form></Card>
  <Card title="رصيد عميل افتتاحي"><form className="ui-filter-grid" onSubmit={postCustomer}>
   <FormField label="العميل" required><Select required value={customer.partyId} onChange={event=>setCustomer({...customer,partyId:event.target.value})}><option value="">اختر</option>{customers.map(value=><option key={value.customer.id} value={value.customer.partyId}>{value.customer.number} — {value.party.displayName}</option>)}</Select></FormField>
   <FormField label="رقم المستند" required><Input required value={customer.number} onChange={event=>setCustomer({...customer,number:event.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={customer.postingDate} onChange={event=>setCustomer({...customer,postingDate:event.target.value})}/></FormField><FormField label="الاستحقاق"><Input type="date" value={customer.dueDate} onChange={event=>setCustomer({...customer,dueDate:event.target.value})}/></FormField>
   <FormField label="العملة" required><Input required value={customer.currency} onChange={event=>setCustomer({...customer,currency:event.target.value.toUpperCase()})}/></FormField><FormField label="حساب العملاء" required><Select required value={customer.controlAccountId} onChange={event=>setCustomer({...customer,controlAccountId:event.target.value})}><option value="">اختر</option>{accounts.filter(value=>value.active&&value.postable&&value.controlType==='CUSTOMER').map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="الحساب المقابل" required><Select required value={customer.lineAccountId} onChange={event=>setCustomer({...customer,lineAccountId:event.target.value})}><option value="">اختر</option>{balanceAccounts.map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={customer.amount} onChange={event=>setCustomer({...customer,amount:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>ترحيل رصيد العميل</Button>
  </form><p>رصيد المورد الافتتاحي غير مضاف كنوع مستقل لأن Billing لا يملك هذا النوع حاليًا.</p></Card>
 </div>;
}

export function TreasuryOperationsPanel({treasuries,vouchers,accounts,operate,done}:{treasuries:readonly TreasuryRow[];vouchers:readonly VoucherRow[];accounts:readonly AccountRow[];operate:boolean;done:Done}){
 const[transfer,setTransfer]=useState({sourceTreasuryId:'',destinationTreasuryId:'',amount:'',postingDate:'',number:''}),[count,setCount]=useState({treasuryId:'',countedAmount:'',countDate:'',adjustmentAccountId:'',number:''}),[bankTreasuryId,setBankTreasuryId]=useState(''),[bank,setBank]=useState({signedAmount:'',valueDate:'',reference:''}),[lines,setLines]=useState<BankLineRow[]>([]),[match,setMatch]=useState({lineId:'',voucherId:''}),[cheques,setCheques]=useState<ChequeRow[]>([]),[cheque,setCheque]=useState({voucherId:'',direction:'OUTGOING' as'INCOMING'|'OUTGOING',bankTreasuryId:'',number:'',amount:'',issueDate:'',dueDate:''}),[transition,setTransition]=useState({id:'',status:'CLEARED' as ChequeRow['status'],reference:''}),[error,setError]=useState('');
 const transferKey=useCommandKey(),countKey=useCommandKey(),bankKey=useCommandKey(),chequeKey=useCommandKey();
 const active=treasuries.filter(value=>value.active),banks=active.filter(value=>value.type==='BANK'),cash=active.filter(value=>value.type==='CASH');
 async function loadBankLines(id:string){if(!id){setLines([]);return;}try{setLines(await accountingApi.listBankLines(id));}catch(value){setError(errorMessage(value));}}
 async function loadCheques(){try{setCheques(await accountingApi.listCheques());}catch(value){setError(errorMessage(value));}}
 useEffect(()=>{void loadCheques();},[]);
 async function run(action:()=>Promise<unknown>,message:string,reset?:()=>void){setError('');try{await action();reset?.();await done(message);}catch(value){setError(errorMessage(value));}}
 const voucherOptions=vouchers.filter(value=>!bankTreasuryId||value.treasuryId===bankTreasuryId);
 return <div className="ui-grid-md">
  {error?<Toast tone="error">{error}</Toast>:null}
  <Card title="تحويل بين الخزائن"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(()=>accountingApi.transferBetweenTreasuries({commandKey:transferKey.get(),...transfer}),'تم تنفيذ التحويل.',transferKey.reset);}}><FormField label="من" required><Select required value={transfer.sourceTreasuryId} onChange={event=>setTransfer({...transfer,sourceTreasuryId:event.target.value})}><option value="">اختر</option>{active.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField><FormField label="إلى" required><Select required value={transfer.destinationTreasuryId} onChange={event=>setTransfer({...transfer,destinationTreasuryId:event.target.value})}><option value="">اختر</option>{active.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={transfer.amount} onChange={event=>setTransfer({...transfer,amount:event.target.value})}/></FormField><FormField label="التاريخ" required><Input required type="date" value={transfer.postingDate} onChange={event=>setTransfer({...transfer,postingDate:event.target.value})}/></FormField><FormField label="رقم المستند" required><Input required value={transfer.number} onChange={event=>setTransfer({...transfer,number:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>تحويل</Button></form></Card>
  <Card title="جرد الخزينة"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(()=>accountingApi.recordCashCount({commandKey:countKey.get(),treasuryId:count.treasuryId,countedAmount:count.countedAmount,countDate:count.countDate,...(count.adjustmentAccountId?{adjustmentAccountId:count.adjustmentAccountId}:{}),...(count.number?{number:count.number}:{})}),'تم تسجيل الجرد.',countKey.reset);}}><FormField label="الخزينة" required><Select required value={count.treasuryId} onChange={event=>setCount({...count,treasuryId:event.target.value})}><option value="">اختر</option>{cash.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField><FormField label="المبلغ المعدود" required><Input required inputMode="decimal" value={count.countedAmount} onChange={event=>setCount({...count,countedAmount:event.target.value})}/></FormField><FormField label="تاريخ الجرد" required><Input required type="date" value={count.countDate} onChange={event=>setCount({...count,countDate:event.target.value})}/></FormField><FormField label="حساب فروق الجرد"><Select value={count.adjustmentAccountId} onChange={event=>setCount({...count,adjustmentAccountId:event.target.value})}><option value="">بدون فرق</option>{accounts.filter(value=>value.active&&value.postable&&!value.controlType).map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="رقم قيد الفرق"><Input value={count.number} onChange={event=>setCount({...count,number:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>تسجيل الجرد</Button></form></Card>
  <Card title="التسوية البنكية"><div className="ui-filter-grid"><FormField label="الحساب البنكي"><Select value={bankTreasuryId} onChange={event=>{setBankTreasuryId(event.target.value);setMatch({lineId:'',voucherId:''});void loadBankLines(event.target.value);}}><option value="">اختر</option>{banks.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField></div><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();const currency=banks.find(value=>value.id===bankTreasuryId)?.currency??'';void run(async()=>{await accountingApi.importBankLine({commandKey:bankKey.get(),treasuryId:bankTreasuryId,currency,signedAmount:bank.signedAmount,valueDate:bank.valueDate,...(bank.reference?{reference:bank.reference}:{})});await loadBankLines(bankTreasuryId);},'تم تسجيل سطر كشف الحساب.',bankKey.reset);}}><FormField label="المبلغ" required><Input required inputMode="decimal" value={bank.signedAmount} onChange={event=>setBank({...bank,signedAmount:event.target.value})}/></FormField><FormField label="تاريخ القيمة" required><Input required type="date" value={bank.valueDate} onChange={event=>setBank({...bank,valueDate:event.target.value})}/></FormField><FormField label="المرجع"><Input value={bank.reference} onChange={event=>setBank({...bank,reference:event.target.value})}/></FormField><Button type="submit" disabled={!operate||!bankTreasuryId}>إضافة السطر</Button></form>
   <DataGrid columns={['التاريخ','المبلغ','المرجع','الحالة']}>{lines.map(value=><tr key={value.id}><td>{value.valueDate}</td><td>{value.signedAmount} {value.currency}</td><td>{value.reference??'—'}</td><td><Badge tone={value.status==='MATCHED'?'success':'neutral'}>{value.status}</Badge></td></tr>)}</DataGrid>
   <form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(async()=>{await accountingApi.manualMatchBankLine(match.lineId,match.voucherId);await loadBankLines(bankTreasuryId);},'تمت المطابقة اليدوية.');}}><FormField label="سطر البنك" required><Select required value={match.lineId} onChange={event=>setMatch({...match,lineId:event.target.value})}><option value="">اختر</option>{lines.filter(value=>value.status!=='MATCHED').map(value=><option key={value.id} value={value.id}>{value.valueDate} — {value.signedAmount} {value.currency}</option>)}</Select></FormField><FormField label="الحركة المحاسبية" required><Select required value={match.voucherId} onChange={event=>setMatch({...match,voucherId:event.target.value})}><option value="">اختر</option>{voucherOptions.filter(value=>value.status==='POSTED').map(value=><option key={value.id} value={value.id}>{value.number} — {value.amount} {value.currency}</option>)}</Select></FormField><Button type="submit" disabled={!operate}>مطابقة</Button></form>
  </Card>
  <Card title="الشيكات"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();const voucher=vouchers.find(value=>value.id===cheque.voucherId);void run(async()=>{await accountingApi.issueCheque({commandKey:chequeKey.get(),voucherId:cheque.voucherId,direction:cheque.direction,...(cheque.bankTreasuryId?{bankTreasuryId:cheque.bankTreasuryId}:{}),number:cheque.number,amount:cheque.amount,currency:voucher?.currency??'',issueDate:cheque.issueDate,...(cheque.dueDate?{dueDate:cheque.dueDate}:{})});chequeKey.reset();await loadCheques();},'تم إصدار الشيك.');}}><FormField label="الحركة المرتبطة" required><Select required value={cheque.voucherId} onChange={event=>setCheque({...cheque,voucherId:event.target.value})}><option value="">اختر</option>{vouchers.filter(value=>value.status==='POSTED').map(value=><option key={value.id} value={value.id}>{value.number} — {value.amount} {value.currency}</option>)}</Select></FormField><FormField label="الاتجاه"><Select value={cheque.direction} onChange={event=>setCheque({...cheque,direction:event.target.value as'INCOMING'|'OUTGOING'})}><option value="OUTGOING">صادر</option><option value="INCOMING">وارد</option></Select></FormField><FormField label="البنك"><Select value={cheque.bankTreasuryId} onChange={event=>setCheque({...cheque,bankTreasuryId:event.target.value})}><option value="">بدون تحديد</option>{banks.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField><FormField label="رقم الشيك" required><Input required value={cheque.number} onChange={event=>setCheque({...cheque,number:event.target.value})}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={cheque.amount} onChange={event=>setCheque({...cheque,amount:event.target.value})}/></FormField><FormField label="تاريخ الإصدار" required><Input required type="date" value={cheque.issueDate} onChange={event=>setCheque({...cheque,issueDate:event.target.value})}/></FormField><FormField label="تاريخ الاستحقاق"><Input type="date" value={cheque.dueDate} onChange={event=>setCheque({...cheque,dueDate:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>إصدار شيك</Button></form>
   <DataGrid columns={['الشيك','الاتجاه','المبلغ','الاستحقاق','الحالة']}>{cheques.map(value=><tr key={value.id}><td>{value.number}</td><td>{value.direction==='OUTGOING'?'صادر':'وارد'}</td><td>{value.amount} {value.currency}</td><td>{value.dueDate??'—'}</td><td>{value.status}</td></tr>)}</DataGrid>
   <form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(async()=>{await accountingApi.transitionCheque(transition.id,{status:transition.status,...(transition.reference?{reference:transition.reference}:{})});await loadCheques();},'تم تحديث حالة الشيك.');}}><FormField label="الشيك" required><Select required value={transition.id} onChange={event=>setTransition({...transition,id:event.target.value})}><option value="">اختر</option>{cheques.map(value=><option key={value.id} value={value.id}>{value.number} — {value.status}</option>)}</Select></FormField><FormField label="الحالة الجديدة"><Select value={transition.status} onChange={event=>setTransition({...transition,status:event.target.value as ChequeRow['status']})}><option value="DEPOSITED">مودع</option><option value="CLEARED">محصل</option><option value="BOUNCED">مرتد</option><option value="VOIDED">ملغي</option></Select></FormField><FormField label="المرجع"><Input value={transition.reference} onChange={event=>setTransition({...transition,reference:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>تحديث الحالة</Button></form>
  </Card>
 </div>;
}
