import{type FormEvent,useEffect,useState}from'react';
import{TenantAuthClient}from'./tenant-auth-client.js';
import{clearTenantSession,readTenantSession,writeTenantSession}from'./tenant-session.js';
import{ActionBar,Badge,Button,Card,FormField,Input,Toast}from'./ui.js';

export function AccountSettingsPage({client=new TenantAuthClient()}:{client?:TenantAuthClient}={}){
 const session=readTenantSession();
 const[username,setUsername]=useState(session?.username??''),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{tone:'success'|'error';text:string}|null>(null),[mfaEnabled,setMfaEnabled]=useState(session?.mfaEnabled??false),[enrollment,setEnrollment]=useState<{secret:string;otpauthUri:string}|null>(null),[mfaCode,setMfaCode]=useState(''),[disablePassword,setDisablePassword]=useState(''),[disableCode,setDisableCode]=useState('');
 if(!session)return <Card title="بيانات الدخول"><p>يلزم تسجيل الدخول أولًا.</p></Card>;
 const activeSession=session;
 useEffect(()=>{client.mfaStatus(activeSession.token,activeSession.companyId).then(v=>setMfaEnabled(v.enabled)).catch(()=>undefined);},[activeSession.token,activeSession.companyId]);
 function relogin(){clearTenantSession();window.location.href='/';}
 async function beginMfa(){setBusy(true);setNotice(null);try{setEnrollment(await client.beginMfa(activeSession.token,activeSession.companyId));setMfaCode('');setNotice({tone:'success',text:'تم إنشاء مفتاح التحقق. أضفه إلى تطبيق المصادقة ثم أكد الرمز.'});}catch(error){setNotice({tone:'error',text:error instanceof Error?error.message:'تعذر بدء التحقق الثنائي.'});}finally{setBusy(false);}}
 async function confirmMfa(){if(!/^\\d{6}$/.test(mfaCode)){setNotice({tone:'error',text:'أدخل رمز تحقق مكوّنًا من 6 أرقام.'});return;}setBusy(true);setNotice(null);try{await client.confirmMfa(activeSession.token,activeSession.companyId,mfaCode);setMfaEnabled(true);setEnrollment(null);setNotice({tone:'success',text:'تم تفعيل التحقق الثنائي. سيتم تسجيل خروجك الآن لتسجيل الدخول بالرمز الجديد.'});setTimeout(relogin,500);}catch(error){setNotice({tone:'error',text:error instanceof Error?error.message:'تعذر تأكيد التحقق الثنائي.'});}finally{setBusy(false);}}
 async function disableMfa(){if(!disablePassword||!/^\\d{6}$/.test(disableCode)){setNotice({tone:'error',text:'أدخل كلمة المرور الحالية ورمز التحقق المكوّن من 6 أرقام.'});return;}setBusy(true);setNotice(null);try{await client.disableMfa(activeSession.token,activeSession.companyId,disablePassword,disableCode);setMfaEnabled(false);setNotice({tone:'success',text:'تم إلغاء التحقق الثنائي. سيتم تسجيل خروجك لحماية الجلسات.'});setTimeout(relogin,500);}catch(error){setNotice({tone:'error',text:error instanceof Error?error.message:'تعذر إلغاء التحقق الثنائي.'});}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();setNotice(null);const normalized=username.trim();if(newPassword&&newPassword!==confirm){setNotice({tone:'error',text:'كلمتا المرور الجديدتان غير متطابقتين.'});return;}const usernameChanged=normalized!==activeSession.username;if(!usernameChanged&&!newPassword){setNotice({tone:'error',text:'لم يتم إدخال أي تغيير.'});return;}setBusy(true);try{const result=await client.updateCredentials(activeSession.token,activeSession.companyId,{currentPassword,newUsername:usernameChanged?normalized:undefined,newPassword:newPassword||undefined});writeTenantSession({...activeSession,username:result.username,mustChangePassword:false});setUsername(result.username);setCurrentPassword('');setNewPassword('');setConfirm('');setNotice({tone:'success',text:'تم تحديث بيانات الدخول بنجاح.'});}catch(error){setNotice({tone:'error',text:error instanceof Error?error.message:'تعذر تحديث بيانات الدخول.'});}finally{setBusy(false);}}
 return <section dir="rtl" className="ui-page-stack"><Card title="بيانات الدخول"><form onSubmit={submit}><p>اسم المستخدم الحالي: <strong>{activeSession.username}</strong></p><FormField label="اسم المستخدم"><Input required minLength={3} maxLength={40} autoCapitalize="none" autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)}/></FormField><FormField label="كلمة المرور الحالية" required><Input required type="password" autoComplete="current-password" minLength={12} value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></FormField><FormField label="كلمة مرور جديدة — اختياري"><Input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={event=>setNewPassword(event.target.value)}/></FormField><FormField label="تأكيد كلمة المرور الجديدة"><Input type="password" autoComplete="new-password" minLength={newPassword?12:undefined} value={confirm} onChange={event=>setConfirm(event.target.value)}/></FormField><Button type="submit" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ بيانات الدخول'}</Button></form></Card>
 <Card title="التحقق الثنائي MFA"><p>الحالة: <Badge tone={mfaEnabled?'success':'neutral'}>{mfaEnabled?'مفعّل':'غير مفعّل'}</Badge></p>{!mfaEnabled&&!enrollment?<Button type="button" onClick={()=>void beginMfa()} disabled={busy}>تفعيل MFA</Button>:null}{enrollment?<><p>أضف الحساب إلى تطبيق مصادقة TOTP باستخدام الرابط أو المفتاح التالي. لا تشارك المفتاح مع أي شخص.</p><FormField label="المفتاح"><Input readOnly value={enrollment.secret}/></FormField><FormField label="رابط الإعداد"><Input readOnly value={enrollment.otpauthUri}/></FormField><ActionBar><Button type="button" variant="secondary" onClick={()=>void navigator.clipboard.writeText(enrollment.secret)}>نسخ المفتاح</Button><Button type="button" variant="secondary" onClick={()=>void navigator.clipboard.writeText(enrollment.otpauthUri)}>نسخ رابط الإعداد</Button></ActionBar><FormField label="رمز التحقق" required><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={mfaCode} onChange={event=>setMfaCode(event.target.value.replace(/\D/g,'').slice(0,6))}/></FormField><Button type="button" disabled={busy||mfaCode.length!==6} onClick={()=>void confirmMfa()}>تأكيد وتفعيل</Button></>:null}{mfaEnabled?<><p>إلغاء MFA يتطلب كلمة المرور الحالية ورمزًا صالحًا، ثم تُلغى جلسات الشركة لحماية الحساب.</p><FormField label="كلمة المرور الحالية"><Input type="password" autoComplete="current-password" value={disablePassword} onChange={event=>setDisablePassword(event.target.value)}/></FormField><FormField label="رمز MFA الحالي"><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={disableCode} onChange={event=>setDisableCode(event.target.value.replace(/\D/g,'').slice(0,6))}/></FormField><Button type="button" variant="secondary" disabled={busy} onClick={()=>void disableMfa()}>إلغاء MFA</Button></>:null}</Card>{notice?<Toast tone={notice.tone}>{notice.text}</Toast>:null}</section>;
}
