import{type FormEvent,useState}from'react';
import{TenantAuthClient}from'./tenant-auth-client.js';
import{readTenantSession,writeTenantSession}from'./tenant-session.js';
import{Button,Card,FormField,Input,Toast}from'./ui.js';

export function AccountSettingsPage({client=new TenantAuthClient()}:{client?:TenantAuthClient}={}){
 const session=readTenantSession();
 const[username,setUsername]=useState(session?.username??''),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{tone:'success'|'error';text:string}|null>(null);
 if(!session)return <Card title="بيانات الدخول"><p>يلزم تسجيل الدخول أولًا.</p></Card>;
 async function submit(event:FormEvent){event.preventDefault();setNotice(null);const normalized=username.trim();if(newPassword&&newPassword!==confirm){setNotice({tone:'error',text:'كلمتا المرور الجديدتان غير متطابقتين.'});return;}const usernameChanged=normalized!==session.username;if(!usernameChanged&&!newPassword){setNotice({tone:'error',text:'لم يتم إدخال أي تغيير.'});return;}setBusy(true);try{const result=await client.updateCredentials(session.token,session.companyId,{currentPassword,newUsername:usernameChanged?normalized:undefined,newPassword:newPassword||undefined});writeTenantSession({...session,username:result.username,mustChangePassword:false});setUsername(result.username);setCurrentPassword('');setNewPassword('');setConfirm('');setNotice({tone:'success',text:'تم تحديث بيانات الدخول بنجاح.'});}catch(error){setNotice({tone:'error',text:error instanceof Error?error.message:'تعذر تحديث بيانات الدخول.'});}finally{setBusy(false);}}
 return <Card title="بيانات الدخول"><form onSubmit={submit}><p>اسم المستخدم الحالي: <strong>{session.username}</strong></p><FormField label="اسم المستخدم"><Input required minLength={3} maxLength={40} autoCapitalize="none" autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)}/></FormField><FormField label="كلمة المرور الحالية" required><Input required type="password" autoComplete="current-password" minLength={12} value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></FormField><FormField label="كلمة مرور جديدة — اختياري"><Input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={event=>setNewPassword(event.target.value)}/></FormField><FormField label="تأكيد كلمة المرور الجديدة"><Input type="password" autoComplete="new-password" minLength={newPassword?12:undefined} value={confirm} onChange={event=>setConfirm(event.target.value)}/></FormField>{notice?<Toast tone={notice.tone}>{notice.text}</Toast>:null}<Button type="submit" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ بيانات الدخول'}</Button></form></Card>;
}
