import type { AppRoute } from './routes.js';
import { AccountingLegacyRoutePage } from './accounting-legacy-route-page.js';

export const accountingLegacyRoutes: readonly AppRoute[] = [
  { id: 'accounting-workspace', path: '/accounting', label: 'المحاسبة والمالية', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'dashboard', reference: 'financial-reporting-center' }, element: <AccountingLegacyRoutePage initialSection="overview" screen="workspace" /> },
  { id: 'accounting-invoices', path: '/accounting/invoices', label: 'الفواتير', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'billing-invoicing' }, element: <AccountingLegacyRoutePage initialSection="billing" screen="invoices" /> },
  { id: 'accounting-receipts', path: '/accounting/receipts', label: 'سندات القبض', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'form', reference: 'treasury-settlement' }, element: <AccountingLegacyRoutePage initialSection="treasury" screen="receipts" /> },
  { id: 'accounting-payments', path: '/accounting/payments', label: 'سندات الصرف', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'form', reference: 'treasury-settlement' }, element: <AccountingLegacyRoutePage initialSection="treasury" screen="payments" /> },
  { id: 'accounting-expenses', path: '/accounting/expenses', label: 'المصروفات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'module', reference: 'master-module-template' }, element: <AccountingLegacyRoutePage initialSection="expense-commission" screen="expenses" /> },
  { id: 'accounting-settlements', path: '/accounting/settlements', label: 'التسويات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'master-detail', reference: 'account-statement' }, element: <AccountingLegacyRoutePage initialSection="party-accounting" screen="settlements" /> },
  { id: 'accounting-accruals', path: '/accounting/accruals', label: 'الاستحقاقات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'data-table' }, element: <AccountingLegacyRoutePage initialSection="recognition-accrual" screen="accruals" /> },
  { id: 'accounting-cheques', path: '/accounting/cheques', label: 'الشيكات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'treasury-settlement' }, element: <AccountingLegacyRoutePage initialSection="treasury" screen="cheques" /> },
  { id: 'accounting-treasury', path: '/accounting/treasury', label: 'الخزينة والبنوك', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'master-detail', reference: 'treasury-settlement' }, element: <AccountingLegacyRoutePage initialSection="treasury" screen="treasury" /> },
  { id: 'accounting-currencies', path: '/accounting/currencies', label: 'العملات وأسعار الصرف', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'currency-fx' }, element: <AccountingLegacyRoutePage initialSection="currency-fx" screen="currencies" /> },
  { id: 'accounting-taxes', path: '/accounting/taxes', label: 'الضرائب', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'vat-tax-returns' }, element: <AccountingLegacyRoutePage initialSection="tax" screen="taxes" /> },
  { id: 'accounting-periods', path: '/accounting/periods', label: 'الفترات المالية', group: 'المحاسبة والمالية', icon: 'calendar', design: { blueprint: 'module', reference: 'master-module-template' }, element: <AccountingLegacyRoutePage initialSection="periods" screen="periods" /> },
  { id: 'accounting-journal', path: '/accounting/journal', label: 'القيود اليومية', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'form', reference: 'journal-entry-form' }, element: <AccountingLegacyRoutePage initialSection="journals" screen="journal" /> },
  { id: 'accounting-accounts', path: '/accounting/accounts', label: 'دليل الحسابات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'master-detail', reference: 'chart-of-accounts' }, element: <AccountingLegacyRoutePage initialSection="accounts" screen="accounts" /> },
  { id: 'accounting-trial', path: '/accounting/trial', label: 'ميزان المراجعة', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'financial-reporting-center' }, element: <AccountingLegacyRoutePage initialSection="reports" screen="trial" /> },
  { id: 'accounting-cost-centers', path: '/accounting/cost-centers', label: 'مراكز التكلفة', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'master-detail', reference: 'cost-centers-budgets' }, element: <AccountingLegacyRoutePage initialSection="cost-budget" screen="cost-centers" /> },
  { id: 'accounting-assets', path: '/accounting/assets', label: 'الأصول', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'assets-depreciation' }, element: <AccountingLegacyRoutePage initialSection="assets-financing" screen="assets" /> },
  { id: 'accounting-loans', path: '/accounting/loans', label: 'القروض والتمويل', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'assets-depreciation' }, element: <AccountingLegacyRoutePage initialSection="assets-financing" screen="loans" /> },
  { id: 'accounting-budgets', path: '/accounting/budgets', label: 'الموازنات', group: 'المحاسبة والمالية', icon: 'analytics', design: { blueprint: 'data-table', reference: 'cost-centers-budgets' }, element: <AccountingLegacyRoutePage initialSection="cost-budget" screen="budgets" /> },
];
