import test from'node:test';
import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{CONFIG_FIELD_KEYS,CompanyProfileValidationError,TIMEZONE_OPTIONS,changedConfigEntries,emptyCompanyProfileForm,loadCompanyProfile,operationsStatusRows,saveCompanyProfile,validateCompanyProfile,withCurrentOption}from'./company-profile-model.js';
import type{AdministrationContext}from'./system-administration-client.js';

const ctx:AdministrationContext={token:'t',companyId:'c 1',branchId:'b'};
const PLATFORM_CORE_WHITELIST=new Set(['locale','timezone','dateFormat','theme','companyName','companyLogo','address','phone','email','notificationPrefs','retention.days']);
const read=(name:string)=>readFileSync(new URL(name,import.meta.url),'utf8');
function fake(reads:Record<string,unknown>={}){const calls:Array<{verb:string;path:string;body?:unknown}>=[];return{calls,async read(path:string,context:AdministrationContext){void context;calls.push({verb:'read',path});if(path in reads)return reads[path];throw new Error('missing');},async action(path:string,context:AdministrationContext,body?:unknown){void context;calls.push({verb:'action',path,body});return{};},async patch(path:string,context:AdministrationContext,body?:unknown){void context;calls.push({verb:'patch',path,body});return{};}};}

test('company profile writes only keys owned by Platform Core',()=>{for(const key of CONFIG_FIELD_KEYS)assert.ok(PLATFORM_CORE_WHITELIST.has(key),key);});
test('validation rejects bad email, phone, retention and empty changed name',()=>{const base={...emptyCompanyProfileForm};assert.equal(validateCompanyProfile({...base,email:'bad'}).ok,false);assert.equal(validateCompanyProfile({...base,phone:'abc'}).ok,false);for(const value of ['0','abc','1.5','-3'])assert.equal(validateCompanyProfile({...base,retentionDays:value}).ok,false,value);assert.equal(validateCompanyProfile({...base,name:' '},{...base,name:'X Co'}).ok,false);assert.equal(validateCompanyProfile({...base,email:'a@b.co',phone:'+20 100 123 4567',retentionDays:'30'}).ok,true);});
test('only changed fields are sent; contact fields may be cleared, mandatory settings may not',()=>{const initial={...emptyCompanyProfileForm,address:'A',locale:'ar',retentionDays:'7'},next={...initial,address:'',locale:'',retentionDays:'30',phone:'123456'};assert.deepEqual(changedConfigEntries(next,initial),[['address',''],['phone','123456'],['retention.days',30]]);});
test('save patches the company entity once and posts changed configuration keys',async()=>{const client=fake(),initial={...emptyCompanyProfileForm,name:'Old'};const result=await saveCompanyProfile(client,ctx,{...initial,name:'New Co',timezone:'Africa/Cairo'},initial);assert.deepEqual(result.saved,['name','timezone']);assert.deepEqual(client.calls,[{verb:'patch',path:'companies/c%201',body:{name:'New Co'}},{verb:'action',path:'configuration/timezone',body:{value:'Africa/Cairo'}}]);const idle=fake();await saveCompanyProfile(idle,ctx,initial,initial);assert.equal(idle.calls.length,0);});
test('invalid input performs no backend call',async()=>{const client=fake(),initial={...emptyCompanyProfileForm,name:'Old'};await assert.rejects(saveCompanyProfile(client,ctx,{...initial,email:'x'},initial),CompanyProfileValidationError);assert.equal(client.calls.length,0);});
test('load tolerates failed reads and extracts owner values',async()=>{const client=fake({'companies/c%201':{name:'Co'},'configuration/retention.days':{key:'retention.days',value:14},'configuration/phone':{key:'phone',value:null}});const form=await loadCompanyProfile(client,ctx);assert.equal(form.name,'Co');assert.equal(form.retentionDays,'14');assert.equal(form.phone,'');assert.equal(form.locale,'');});
test('operations status is honest',()=>{const rows=operationsStatusRows({database:'UNAVAILABLE',backupProvider:'UNAVAILABLE',restoreReady:false,maintenance:false,schemaCompatibility:'UNAVAILABLE',runtimeVersion:'v22'},''),by=Object.fromEntries(rows.map(row=>[row.key,row]));assert.equal(by.backupProvider?.kind,'UNAVAILABLE');assert.equal(by.restoreReady?.kind,'UNAVAILABLE');assert.equal(by.retention?.kind,'CONFIGURATION_REQUIRED');assert.equal(operationsStatusRows({backupProvider:'UNKNOWN_CODE'},'7').find(row=>row.key==='backupProvider')?.kind,'INFO');assert.equal(operationsStatusRows(undefined,'7').length,1);});
test('current stored value stays selectable even if not a preset',()=>{assert.equal(withCurrentOption(TIMEZONE_OPTIONS,'Asia/Tokyo').length,TIMEZONE_OPTIONS.length+1);assert.equal(withCurrentOption(TIMEZONE_OPTIONS,'UTC'),TIMEZONE_OPTIONS);});
test('administration page composes typed profile and removes generic key value UX',()=>{const page=read('./system-administration-page.tsx');assert.match(page,/<CompanyProfilePanel client=\{client\} context=\{ctx\}\/>/);assert.doesNotMatch(page,/configKey|مفتاح الإعداد|القيمة \(JSON أو نص\)/);});
test('panel has no tenant restore action or browser dialogs',()=>{const panel=read('./company-profile-panel.tsx'),model=read('./company-profile-model.ts');assert.match(panel,/حفظ الإعدادات/);assert.match(panel,/مركز تحكم المالك/);assert.doesNotMatch(panel+model,/operations\/restores|بدء الاستعادة/);assert.doesNotMatch(panel+model,/window\.(prompt|confirm|alert)|\bprompt\(|\bconfirm\(|\balert\(/);});
test('platform foundations use canonical branch and user selectors',()=>{const page=read('./platform-foundations-page.tsx');assert.match(page,/administration\.list\('branches',context\)/);assert.match(page,/administration\.list\('users',context\)/);assert.match(page,/كل الفروع/);assert.match(page,/اختيار المستخدم المستلم/);assert.match(page,/اختيار مستخدم التصعيد/);assert.doesNotMatch(page,/معرّف الفرع/);assert.doesNotMatch(page,/window\.(prompt|confirm|alert)|\bprompt\(|\bconfirm\(|\balert\(/);});
