import { type FormEvent, useEffect, useState } from 'react';
import { ActionBar, Badge, Button, Card, Checkbox, DataGrid, EntityPicker, FormField, Input, MetricCard, Select, Toast } from './ui.js';
import type {AccountRow,InvoiceRow,TreasuryRow} from './accounting-client.js';
import {businessReferenceApi,type CostCenterReference} from './business-reference-client.js';
import { advancedAccountingApi, type AdvancedResult } from './advanced-accounting-client.js';

const today=()=>new Date().toISOString().slice(0,10);
const isoNow=()=>new Date().toISOString();
const msg=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية.';
type ExpenseFormUi='DIRECT_PAID'|'PREPAID'|'SUPPLIER_PAYABLE';

type AccountingChoices={accounts?:readonly AccountRow[];invoices?:readonly InvoiceRow[];treasuries?:readonly TreasuryRow[]};
function AccountChoice({label,value,onChange,accounts=[],required=false}:{label:string;value:string;onChange:(id:string)=>void;accounts:readonly AccountRow[];required?:boolean}){
 return <FormField label={label} required={required}><EntityPicker required={required} value={value} onChange={onChange} placeholder="اختر حسابًا" options={accounts.filter(item=>item.active&&item.postable).map(item=>({id:item.id,code:item.code,label:item.name}))}/></FormField>;
}
function TreasuryChoice({label,value,onChange,treasuries=[]}:{label:string;value:string;onChange:(id:string)=>void;treasuries:readonly TreasuryRow[]}){
 return <FormField label={label} required><EntityPicker required value={value} onChange={onChange} placeholder="اختر خزينة أو بنكًا" options={treasuries.filter(item=>item.active).map(item=>({id:item.id,code:item.code,label:item.name,description:item.currency}))}/></FormField>;
}
function InvoiceChoice({label,value,onChange,invoices=[],type}:{label:string;value:string;onChange:(id:string)=>void;invoices:readonly InvoiceRow[];type:'CUSTOMER'|'SUPPLIER'}){
 return <FormField label={label}><EntityPicker value={value} onChange={onChange} placeholder="اختر فاتورة" options={invoices.filter(item=>item.type===type&&item.status==='POSTED').map(item=>({id:item.id,code:item.number,label:`${item.outstanding} ${item.currency}`}))}/></FormField>;
}

function ResultCard({title,value}:{title:string;value:AdvancedResult|null}){
 if(!value)return null;
 const entries=Object.entries(value).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v));
 return <Card title={title}>{entries.length?<DataGrid columns={['البيان','القيمة']}>{entries.map(([key,value])=><tr key={key}><td>{key}</td><td>{value===null?'—':String(value)}</td></tr>)}</DataGrid>:<p>تمت العملية بنجاح وحُفظت النتيجة لدى المالك المعتمد.</p>}</Card>;
}
function Notice({text}:{text:string}){return text?<Toast tone={text.startsWith('تم')?'success':'error'}>{text}</Toast>:null;}

export function CurrencyFxSection(){
 const[base,setBase]=useState<AdvancedResult|null>(null),[notice,setNotice]=useState(''),[result,setResult]=useState<AdvancedResult|null>(null);
 const[code,setCode]=useState('EGP'),[precision,setPrecision]=useState('2'),[isBase,setIsBase]=useState(true);
 const[from,setFrom]=useState('USD'),[to,setTo]=useState('EGP'),[rate,setRate]=useState(''),[effectiveAt,setEffectiveAt]=useState(isoNow()),[source,setSource]=useState('MANUAL');
 useEffect(()=>{advancedAccountingApi.baseCurrency().then(setBase).catch(()=>setBase(null));},[]);
 async function configure(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.configureCurrency({code:code.toUpperCase(),precision:Number(precision),isBase,status:'ACTIVE'});setBase(value);setResult(value);setNotice('تم حفظ إعداد العملة.')}catch(e){setNotice(msg(e));}}
 async function publish(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.publishRate({fromCurrency:from.toUpperCase(),toCurrency:to.toUpperCase(),effectiveAt:new Date(effectiveAt).toISOString(),rate,source});setResult(value);setNotice('تم نشر سعر الصرف.')}catch(e){setNotice(msg(e));}}
 async function resolve(){try{const value=await advancedAccountingApi.resolveRate(from.toUpperCase(),to.toUpperCase(),new Date(effectiveAt).toISOString());setResult(value);setNotice('تم جلب سعر الصرف الفعلي.')}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack">
  <Notice text={notice}/>
  <div className="ui-metric-grid"><MetricCard label="العملة الأساسية" value={String(base?.code??'غير محددة')}/><MetricCard label="الدقة" value={String(base?.precision??'—')}/><MetricCard label="الحالة" value={String(base?.status??'—')}/></div>
  <div className="ui-grid-md">
   <Card title="إعداد عملة"><form onSubmit={configure}><FormField label="كود العملة" required><Input required maxLength={3} value={code} onChange={e=>setCode(e.target.value)}/></FormField><FormField label="عدد الكسور" required><Input required inputMode="numeric" value={precision} onChange={e=>setPrecision(e.target.value)}/></FormField><label className="ui-checkbox-field"><Checkbox checked={isBase} onChange={e=>setIsBase(e.target.checked)}/><span>عملة أساسية للشركة</span></label><Button type="submit">حفظ العملة</Button></form></Card>
   <Card title="أسعار الصرف"><form onSubmit={publish}><FormField label="من" required><Input required maxLength={3} value={from} onChange={e=>setFrom(e.target.value)}/></FormField><FormField label="إلى" required><Input required maxLength={3} value={to} onChange={e=>setTo(e.target.value)}/></FormField><FormField label="السعر" required><Input required inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)}/></FormField><FormField label="ساري من" required><Input required type="datetime-local" value={effectiveAt.slice(0,16)} onChange={e=>setEffectiveAt(e.target.value)}/></FormField><FormField label="المصدر"><Input value={source} onChange={e=>setSource(e.target.value)}/></FormField><ActionBar><Button type="submit">نشر السعر</Button><Button type="button" variant="secondary" onClick={()=>void resolve()}>عرض السعر الساري</Button></ActionBar></form></Card>
  </div>
  <ResultCard title="آخر نتيجة" value={result}/>
 </section>;
}

export function CostBudgetSection(){
 const[notice,setNotice]=useState(''),[result,setResult]=useState<AdvancedResult|null>(null);
 const[centers,setCenters]=useState<readonly CostCenterReference[]>([]);
 useEffect(()=>{void businessReferenceApi.costCenters().then(setCenters).catch(error=>setNotice(msg(error)));},[]);
 const[cc,setCc]=useState({code:'',name:'',parentId:''}),[lookup,setLookup]=useState('');
 const[budget,setBudget]=useState({costCenterId:'',periodStart:today(),periodEnd:today(),currency:'EGP',amount:''}),[budgetId,setBudgetId]=useState('');
 async function createCenter(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createCostCenter({...cc,...(cc.parentId?{parentId:cc.parentId}:{})});setResult(value);setLookup(String(value.id??''));setBudget(v=>({...v,costCenterId:String(value.id??'')}));setCenters(await businessReferenceApi.costCenters());setNotice('تم إنشاء مركز التكلفة.')}catch(e){setNotice(msg(e));}}
 async function getCenter(){try{setResult(await advancedAccountingApi.getCostCenter(lookup));setNotice('تم تحميل مركز التكلفة.')}catch(e){setNotice(msg(e));}}
 async function createBudget(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createBudget(budget);setResult(value);setBudgetId(String(value.id??''));setNotice('تم إنشاء الموازنة كمسودة.')}catch(e){setNotice(msg(e));}}
 async function budgetAction(kind:'check'|'authorize'){try{const value=kind==='check'?await advancedAccountingApi.checkBudget(budgetId):await advancedAccountingApi.authorizeBudget(budgetId);setResult(value);setNotice(kind==='check'?'تم فحص الموازنة.':'تم اعتماد الموازنة.')}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack"><Notice text={notice}/><div className="ui-grid-md">
  <Card title="مراكز التكلفة"><form onSubmit={createCenter}><FormField label="الكود" required><Input required value={cc.code} onChange={e=>setCc({...cc,code:e.target.value.toUpperCase()})}/></FormField><FormField label="الاسم" required><Input required value={cc.name} onChange={e=>setCc({...cc,name:e.target.value})}/></FormField><FormField label="المركز الأب"><EntityPicker value={cc.parentId} onChange={parentId=>setCc({...cc,parentId})} placeholder="بدون مركز أب" options={centers.filter(item=>item.status==='ACTIVE').map(item=>({id:item.id,code:item.code,label:item.name}))}/></FormField><Button type="submit">إنشاء مركز تكلفة</Button></form><hr/><FormField label="فتح مركز"><EntityPicker value={lookup} onChange={setLookup} placeholder="اختر مركز تكلفة" options={centers.map(item=>({id:item.id,code:item.code,label:item.name}))}/></FormField><Button variant="secondary" onClick={()=>void getCenter()}>عرض المركز</Button></Card>
  <Card title="الموازنات"><form onSubmit={createBudget}><FormField label="مركز التكلفة" required><EntityPicker required value={budget.costCenterId} onChange={costCenterId=>setBudget({...budget,costCenterId})} placeholder="اختر مركز تكلفة" options={centers.filter(item=>item.status==='ACTIVE').map(item=>({id:item.id,code:item.code,label:item.name}))}/></FormField><FormField label="من"><Input required type="date" value={budget.periodStart} onChange={e=>setBudget({...budget,periodStart:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={budget.periodEnd} onChange={e=>setBudget({...budget,periodEnd:e.target.value})}/></FormField><FormField label="العملة"><Input required value={budget.currency} onChange={e=>setBudget({...budget,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={budget.amount} onChange={e=>setBudget({...budget,amount:e.target.value})}/></FormField><Button type="submit">إنشاء الموازنة</Button></form><hr/><FormField label="معرّف الموازنة"><Input value={budgetId} onChange={e=>setBudgetId(e.target.value)}/></FormField><ActionBar><Button variant="secondary" onClick={()=>void budgetAction('check')}>فحص الفعلي والمتبقي</Button><Button onClick={()=>void budgetAction('authorize')}>اعتماد الموازنة</Button></ActionBar></Card>
 </div><ResultCard title="آخر نتيجة" value={result}/></section>;
}

export function PartyAccountingSection(){
 const[notice,setNotice]=useState(''),[result,setResult]=useState<AdvancedResult|null>(null),[groupId,setGroupId]=useState('');
 const[group,setGroup]=useState({name:'',customerId:'',supplierId:''});
 const[net,setNet]=useState({groupId:'',customerInvoiceId:'',supplierInvoiceId:'',amount:'',postingDate:today(),number:'',approvalRequestId:''}),[netId,setNetId]=useState('');
 async function createGroup(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createPartyGroup({name:group.name,members:[{role:'CUSTOMER',partyId:group.customerId},{role:'SUPPLIER',partyId:group.supplierId}]});setResult(value);const id=String(value.id??'');setGroupId(id);setNet(v=>({...v,groupId:id}));setNotice('تم إنشاء مجموعة الأطراف.')}catch(e){setNotice(msg(e));}}
 async function propose(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.proposeNetting({...net,...(net.approvalRequestId?{approvalRequestId:net.approvalRequestId}:{})});setResult(value);setNetId(String(value.id??''));setNotice('تم إنشاء مقترح المقاصة.')}catch(e){setNotice(msg(e));}}
 async function act(kind:'execute'|'reverse'){try{const value=kind==='execute'?await advancedAccountingApi.executeNetting(netId):await advancedAccountingApi.reverseNetting(netId,{postingDate:today(),number:'REV-'+Date.now()});setResult(value);setNotice(kind==='execute'?'تم تنفيذ المقاصة.':'تم عكس المقاصة.')}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack"><Notice text={notice}/><div className="ui-grid-md">
  <Card title="مجموعة عميل / مورد"><form onSubmit={createGroup}><FormField label="اسم المجموعة" required><Input required value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></FormField><FormField label="معرّف العميل" required><Input required value={group.customerId} onChange={e=>setGroup({...group,customerId:e.target.value})}/></FormField><FormField label="معرّف المورد" required><Input required value={group.supplierId} onChange={e=>setGroup({...group,supplierId:e.target.value})}/></FormField><Button type="submit">إنشاء المجموعة</Button></form>{groupId&&<p>المجموعة الحالية: <Badge tone="success">{groupId}</Badge></p>}</Card>
  <Card title="المقاصة الرسمية"><form onSubmit={propose}><FormField label="مجموعة الأطراف" required><Input required value={net.groupId} onChange={e=>setNet({...net,groupId:e.target.value})}/></FormField><FormField label="فاتورة العميل" required><Input required value={net.customerInvoiceId} onChange={e=>setNet({...net,customerInvoiceId:e.target.value})}/></FormField><FormField label="فاتورة المورد" required><Input required value={net.supplierInvoiceId} onChange={e=>setNet({...net,supplierInvoiceId:e.target.value})}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={net.amount} onChange={e=>setNet({...net,amount:e.target.value})}/></FormField><FormField label="تاريخ الترحيل"><Input required type="date" value={net.postingDate} onChange={e=>setNet({...net,postingDate:e.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={net.number} onChange={e=>setNet({...net,number:e.target.value})}/></FormField><FormField label="طلب الاعتماد — إن وجد"><Input value={net.approvalRequestId} onChange={e=>setNet({...net,approvalRequestId:e.target.value})}/></FormField><Button type="submit">إنشاء المقاصة</Button></form><FormField label="معرّف المقاصة"><Input value={netId} onChange={e=>setNetId(e.target.value)}/></FormField><ActionBar><Button onClick={()=>void act('execute')}>تنفيذ</Button><Button variant="danger" onClick={()=>void act('reverse')}>عكس</Button></ActionBar></Card>
 </div><ResultCard title="آخر نتيجة" value={result}/></section>;
}

export function ExpenseCommissionSection({accounts=[],invoices=[],treasuries=[]}:AccountingChoices){
 const[notice,setNotice]=useState(''),[result,setResult]=useState<AdvancedResult|null>(null),[expenseId,setExpenseId]=useState(''),[claimId,setClaimId]=useState('');
 const[expense,setExpense]=useState({form:'DIRECT_PAID' as ExpenseFormUi,sourceType:'MANUAL_EXPENSE',sourceId:'',currency:'EGP',amount:'',baseAmount:'',expenseAccountId:'',prepaidAccountId:'',billingInvoiceId:''});
 const[payment,setPayment]=useState({treasuryId:'',paymentCurrency:'EGP',postingDate:today(),number:''});
 const[claim,setClaim]=useState({agentPartyId:'',sourceType:'COMMISSION',sourceId:'',currency:'EGP',amount:'',baseCarryingAmount:'',expenseAccountId:'',liabilityAccountId:''});
 async function createExpense(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createExpense(expense);setResult(value);setExpenseId(String(value.id??''));setNotice('تم إنشاء المصروف.')}catch(e){setNotice(msg(e));}}
 async function payExpense(){try{const value=await advancedAccountingApi.payExpense(expenseId,payment);setResult(value);setNotice('تم ترحيل سداد المصروف.')}catch(e){setNotice(msg(e));}}
 async function createClaim(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createCommission(claim);setResult(value);setClaimId(String(value.id??''));setNotice('تم إنشاء مطالبة العمولة.')}catch(e){setNotice(msg(e));}}
 async function claimAction(kind:'approve'|'pay'){try{const value=kind==='approve'?await advancedAccountingApi.approveCommission(claimId,{postingDate:payment.postingDate,number:payment.number||'COM-'+Date.now()}):await advancedAccountingApi.payCommission(claimId,{treasuryId:payment.treasuryId,amount:claim.amount,paymentCurrency:payment.paymentCurrency,postingDate:payment.postingDate,number:payment.number||'PAY-'+Date.now()});setResult(value);setNotice(kind==='approve'?'تم اعتماد العمولة.':'تم سداد العمولة.')}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack"><Notice text={notice}/><div className="ui-grid-md">
  <Card title="المصروفات"><form onSubmit={createExpense}><FormField label="نوع المصروف"><Select value={expense.form} onChange={e=>setExpense({...expense,form:e.target.value as ExpenseFormUi})}><option value="DIRECT_PAID">مدفوع مباشر</option><option value="PREPAID">مصروف مقدم</option><option value="SUPPLIER_PAYABLE">مستحق مورد</option></Select></FormField><FormField label="مرجع المصدر" required><Input required value={expense.sourceId} onChange={e=>setExpense({...expense,sourceId:e.target.value})}/></FormField><FormField label="العملة"><Input required value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value,baseAmount:e.target.value})}/></FormField><AccountChoice label="حساب المصروف" value={expense.expenseAccountId} onChange={expenseAccountId=>setExpense({...expense,expenseAccountId})} accounts={accounts}/><AccountChoice label="حساب المصروف المقدم" value={expense.prepaidAccountId} onChange={prepaidAccountId=>setExpense({...expense,prepaidAccountId})} accounts={accounts}/><InvoiceChoice label="فاتورة المورد" value={expense.billingInvoiceId} onChange={billingInvoiceId=>setExpense({...expense,billingInvoiceId})} invoices={invoices} type="SUPPLIER"/><Button type="submit">إنشاء المصروف</Button></form><FormField label="معرّف المصروف"><Input value={expenseId} onChange={e=>setExpenseId(e.target.value)}/></FormField><Button variant="secondary" onClick={()=>void payExpense()}>سداد المصروف</Button></Card>
  <Card title="العمولات"><form onSubmit={createClaim}><FormField label="الوكيل / الطرف" required><Input required value={claim.agentPartyId} onChange={e=>setClaim({...claim,agentPartyId:e.target.value})}/></FormField><FormField label="مرجع العملية" required><Input required value={claim.sourceId} onChange={e=>setClaim({...claim,sourceId:e.target.value})}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={claim.amount} onChange={e=>setClaim({...claim,amount:e.target.value,baseCarryingAmount:e.target.value})}/></FormField><AccountChoice label="حساب المصروف" required value={claim.expenseAccountId} onChange={expenseAccountId=>setClaim({...claim,expenseAccountId})} accounts={accounts}/><AccountChoice label="حساب الالتزام" required value={claim.liabilityAccountId} onChange={liabilityAccountId=>setClaim({...claim,liabilityAccountId})} accounts={accounts}/><Button type="submit">إنشاء مطالبة عمولة</Button></form><FormField label="معرّف المطالبة"><Input value={claimId} onChange={e=>setClaimId(e.target.value)}/></FormField><ActionBar><Button onClick={()=>void claimAction('approve')}>اعتماد</Button><Button variant="secondary" onClick={()=>void claimAction('pay')}>سداد</Button></ActionBar></Card>
  <Card title="بيانات السداد المشتركة"><TreasuryChoice label="الخزينة / البنك" value={payment.treasuryId} onChange={treasuryId=>setPayment({...payment,treasuryId})} treasuries={treasuries}/><FormField label="عملة السداد"><Input value={payment.paymentCurrency} onChange={e=>setPayment({...payment,paymentCurrency:e.target.value.toUpperCase()})}/></FormField><FormField label="التاريخ"><Input type="date" value={payment.postingDate} onChange={e=>setPayment({...payment,postingDate:e.target.value})}/></FormField><FormField label="رقم المستند"><Input value={payment.number} onChange={e=>setPayment({...payment,number:e.target.value})}/></FormField></Card>
 </div><ResultCard title="آخر نتيجة" value={result}/></section>;
}

export function AssetsFinancingSection({accounts=[],treasuries=[]}:AccountingChoices){
 const[notice,setNotice]=useState(''),[result,setResult]=useState<AdvancedResult|null>(null),[assetId,setAssetId]=useState(''),[loanId,setLoanId]=useState(''),[installmentId,setInstallmentId]=useState(''),[provisionId,setProvisionId]=useState('');
 const[asset,setAsset]=useState({code:'',name:'',description:'',acquisitionValue:'',baseValue:'',currency:'EGP',acquisitionDate:today(),capitalizationDate:today(),inServiceDate:today(),residualValue:'0',usefulLifeMonths:'12',assetAccountId:'',capitalizationOffsetAccountId:'',accumulatedDepreciationAccountId:'',depreciationExpenseAccountId:'',number:''});
 const[loan,setLoan]=useState({lenderId:'',reference:'',principal:'',currency:'EGP',liabilityAccountId:'',interestExpenseAccountId:'',fundingTreasuryId:'',postingDate:today(),number:'',dueDate:today(),interest:'0'});
 const[provision,setProvision]=useState({name:'',provisionAccountId:'',expenseAccountId:'',releaseAccountId:''}),[movement,setMovement]=useState({kind:'RECOGNIZE' as 'RECOGNIZE'|'INCREASE'|'USE'|'RELEASE',amount:'',sourceType:'MANUAL',sourceId:'',postingDate:today(),number:'',useOffsetAccountId:''});
 async function createAsset(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.registerAsset({...asset,usefulLifeMonths:Number(asset.usefulLifeMonths),method:'STRAIGHT_LINE'});setResult(value);setAssetId(String(value.id??''));setNotice('تم تسجيل الأصل وترحيل رسملته.')}catch(e){setNotice(msg(e));}}
 async function depreciate(){try{const value=await advancedAccountingApi.depreciateAsset(assetId,{period:1,postingDate:today(),number:'DEP-'+Date.now()});setResult(value);setNotice('تم ترحيل الإهلاك.')}catch(e){setNotice(msg(e));}}
 async function createLoan(e:FormEvent){e.preventDefault();try{const installment=crypto.randomUUID();const value=await advancedAccountingApi.originateLoan({...loan,baseAmount:loan.principal,installments:[{id:installment,dueDate:loan.dueDate,principal:loan.principal,interest:loan.interest}]});setResult(value);setLoanId(String(value.id??''));setInstallmentId(installment);setNotice('تم إنشاء القرض وجدول السداد.')}catch(e){setNotice(msg(e));}}
 async function payInstallment(){try{const value=await advancedAccountingApi.payLoanInstallment(loanId,installmentId,{treasuryId:loan.fundingTreasuryId,postingDate:today(),number:'LP-'+Date.now()});setResult(value);setNotice('تم سداد القسط.')}catch(e){setNotice(msg(e));}}
 async function createProvision(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.createProvision(provision);setResult(value);setProvisionId(String(value.id??''));setNotice('تم إنشاء المخصص.')}catch(e){setNotice(msg(e));}}
 async function moveProvision(e:FormEvent){e.preventDefault();try{const value=await advancedAccountingApi.moveProvision(provisionId,{...movement,...(movement.useOffsetAccountId?{useOffsetAccountId:movement.useOffsetAccountId}:{})});setResult(value);setNotice('تم ترحيل حركة المخصص.')}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack"><Notice text={notice}/><div className="ui-grid-md">
  <Card title="الأصول الثابتة"><form onSubmit={createAsset}><FormField label="كود الأصل" required><Input required value={asset.code} onChange={e=>setAsset({...asset,code:e.target.value})}/></FormField><FormField label="اسم الأصل" required><Input required value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})}/></FormField><FormField label="قيمة الاقتناء" required><Input required inputMode="decimal" value={asset.acquisitionValue} onChange={e=>setAsset({...asset,acquisitionValue:e.target.value,baseValue:e.target.value})}/></FormField><FormField label="القيمة التخريدية"><Input inputMode="decimal" value={asset.residualValue} onChange={e=>setAsset({...asset,residualValue:e.target.value})}/></FormField><FormField label="العمر بالشهور"><Input inputMode="numeric" value={asset.usefulLifeMonths} onChange={e=>setAsset({...asset,usefulLifeMonths:e.target.value})}/></FormField><AccountChoice label="حساب الأصل" required value={asset.assetAccountId} onChange={assetAccountId=>setAsset({...asset,assetAccountId})} accounts={accounts}/><AccountChoice label="مقابل الرسملة" required value={asset.capitalizationOffsetAccountId} onChange={capitalizationOffsetAccountId=>setAsset({...asset,capitalizationOffsetAccountId})} accounts={accounts}/><AccountChoice label="مجمع الإهلاك" required value={asset.accumulatedDepreciationAccountId} onChange={accumulatedDepreciationAccountId=>setAsset({...asset,accumulatedDepreciationAccountId})} accounts={accounts}/><AccountChoice label="مصروف الإهلاك" required value={asset.depreciationExpenseAccountId} onChange={depreciationExpenseAccountId=>setAsset({...asset,depreciationExpenseAccountId})} accounts={accounts}/><FormField label="رقم القيد" required><Input required value={asset.number} onChange={e=>setAsset({...asset,number:e.target.value})}/></FormField><Button type="submit">تسجيل الأصل</Button></form><FormField label="معرّف الأصل"><Input value={assetId} onChange={e=>setAssetId(e.target.value)}/></FormField><Button variant="secondary" onClick={()=>void depreciate()}>ترحيل إهلاك فترة</Button></Card>
  <Card title="القروض والتمويل"><form onSubmit={createLoan}><FormField label="الممول" required><Input required value={loan.lenderId} onChange={e=>setLoan({...loan,lenderId:e.target.value})}/></FormField><FormField label="المرجع" required><Input required value={loan.reference} onChange={e=>setLoan({...loan,reference:e.target.value})}/></FormField><FormField label="أصل القرض" required><Input required inputMode="decimal" value={loan.principal} onChange={e=>setLoan({...loan,principal:e.target.value})}/></FormField><AccountChoice label="حساب القرض" required value={loan.liabilityAccountId} onChange={liabilityAccountId=>setLoan({...loan,liabilityAccountId})} accounts={accounts}/><AccountChoice label="حساب الفائدة" required value={loan.interestExpenseAccountId} onChange={interestExpenseAccountId=>setLoan({...loan,interestExpenseAccountId})} accounts={accounts}/><TreasuryChoice label="خزينة التمويل" value={loan.fundingTreasuryId} onChange={fundingTreasuryId=>setLoan({...loan,fundingTreasuryId})} treasuries={treasuries}/><FormField label="استحقاق القسط" required><Input required type="date" value={loan.dueDate} onChange={e=>setLoan({...loan,dueDate:e.target.value})}/></FormField><FormField label="فائدة القسط"><Input inputMode="decimal" value={loan.interest} onChange={e=>setLoan({...loan,interest:e.target.value})}/></FormField><FormField label="رقم مستند التمويل" required><Input required value={loan.number} onChange={e=>setLoan({...loan,number:e.target.value})}/></FormField><Button type="submit">تسجيل القرض</Button></form><ActionBar><Input aria-label="معرّف القرض" placeholder="معرّف القرض" value={loanId} onChange={e=>setLoanId(e.target.value)}/><Input aria-label="معرّف القسط" placeholder="معرّف القسط" value={installmentId} onChange={e=>setInstallmentId(e.target.value)}/><Button variant="secondary" onClick={()=>void payInstallment()}>سداد القسط</Button></ActionBar></Card>
  <Card title="المخصصات"><form onSubmit={createProvision}><FormField label="اسم المخصص" required><Input required value={provision.name} onChange={e=>setProvision({...provision,name:e.target.value})}/></FormField><AccountChoice label="حساب المخصص" required value={provision.provisionAccountId} onChange={provisionAccountId=>setProvision({...provision,provisionAccountId})} accounts={accounts}/><AccountChoice label="حساب المصروف" required value={provision.expenseAccountId} onChange={expenseAccountId=>setProvision({...provision,expenseAccountId})} accounts={accounts}/><AccountChoice label="حساب رد المخصص" required value={provision.releaseAccountId} onChange={releaseAccountId=>setProvision({...provision,releaseAccountId})} accounts={accounts}/><Button type="submit">إنشاء المخصص</Button></form><FormField label="معرّف المخصص"><Input value={provisionId} onChange={e=>setProvisionId(e.target.value)}/></FormField><form onSubmit={moveProvision}><FormField label="نوع الحركة"><Select value={movement.kind} onChange={e=>setMovement({...movement,kind:e.target.value as typeof movement.kind})}><option value="RECOGNIZE">تكوين</option><option value="INCREASE">زيادة</option><option value="USE">استخدام</option><option value="RELEASE">رد</option></Select></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={movement.amount} onChange={e=>setMovement({...movement,amount:e.target.value})}/></FormField><FormField label="مرجع المصدر"><Input required value={movement.sourceId} onChange={e=>setMovement({...movement,sourceId:e.target.value})}/></FormField><FormField label="رقم القيد"><Input required value={movement.number} onChange={e=>setMovement({...movement,number:e.target.value})}/></FormField>{movement.kind==='USE'?<AccountChoice label="حساب التسوية" required value={movement.useOffsetAccountId} onChange={useOffsetAccountId=>setMovement({...movement,useOffsetAccountId})} accounts={accounts}/>:null}<Button type="submit">ترحيل الحركة</Button></form></Card>
 </div><ResultCard title="آخر نتيجة" value={result}/></section>;
}
