import{useRef,useState,type FormEvent}from'react';
import{advancedAccountingApi,type RevaluationInput}from'./advanced-accounting-client.js';
import{type AccountRow,type TreasuryRow}from'./accounting-client.js';
import{Button,Card,FormField,Input,Select,Toast}from'./ui.js';

type Done=(message:string)=>Promise<void>;
const errorMessage=(value:unknown)=>value instanceof Error?value.message:'تعذر تنفيذ العملية.';
function useCommandKey(){const ref=useRef<string|null>(null);return{get:()=>ref.current??(ref.current=crypto.randomUUID()),reset:()=>{ref.current=null;}};}
const accountLabel=(value:AccountRow)=>`${value.code} — ${value.name}`;

export function FxRevaluationPanel({operate}:{operate:boolean}){
 const[form,setForm]=useState<RevaluationInput>({positionReference:'',classification:'ASSET',monetary:true,foreignAmount:{amount:'',currency:'USD'},priorBaseAmount:'',baseCurrency:'EGP',at:''});
 const[result,setResult]=useState<Record<string,unknown>|null>(null),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();setError('');try{setResult(await advancedAccountingApi.prepareRevaluation(form));}catch(value){setError(errorMessage(value));}}
 return <Card title="إعادة تقييم العملات">
  {error?<Toast tone="error">{error}</Toast>:null}
  <form className="ui-filter-grid" onSubmit={submit}>
   <FormField label="مرجع المركز" required><Input required value={form.positionReference} onChange={event=>setForm({...form,positionReference:event.target.value})}/></FormField>
   <FormField label="التصنيف"><Select value={form.classification} onChange={event=>setForm({...form,classification:event.target.value as RevaluationInput['classification']})}><option value="ASSET">أصل</option><option value="LIABILITY">التزام</option><option value="REVENUE">إيراد</option><option value="EXPENSE">مصروف</option><option value="EQUITY">حقوق ملكية</option></Select></FormField>
   <FormField label="المبلغ الأجنبي" required><Input required inputMode="decimal" value={form.foreignAmount.amount} onChange={event=>setForm({...form,foreignAmount:{...form.foreignAmount,amount:event.target.value}})}/></FormField>
   <FormField label="عملة المركز" required><Input required value={form.foreignAmount.currency} onChange={event=>setForm({...form,foreignAmount:{...form.foreignAmount,currency:event.target.value.toUpperCase()}})}/></FormField>
   <FormField label="القيمة الدفترية بالأساس" required><Input required inputMode="decimal" value={form.priorBaseAmount} onChange={event=>setForm({...form,priorBaseAmount:event.target.value})}/></FormField>
   <FormField label="العملة الأساسية" required><Input required value={form.baseCurrency} onChange={event=>setForm({...form,baseCurrency:event.target.value.toUpperCase()})}/></FormField>
   <FormField label="وقت التقييم" required><Input required type="datetime-local" value={form.at} onChange={event=>setForm({...form,at:event.target.value})}/></FormField>
   <Button type="submit" disabled={!operate}>حساب إعادة التقييم</Button>
  </form>
  {result?<pre>{JSON.stringify(result,null,2)}</pre>:null}
 </Card>;
}

export function AssetPayrollParityPanel({accounts,treasuries,operate,done}:{accounts:readonly AccountRow[];treasuries:readonly TreasuryRow[];operate:boolean;done:Done}){
 const[error,setError]=useState(''),disposeKey=useCommandKey(),payrollKey=useCommandKey();
 const[disposal,setDisposal]=useState({assetId:'',postingDate:'',proceeds:'0',proceedsMode:'NON_CASH' as'TREASURY'|'NON_CASH',treasuryId:'',proceedsClearingAccountId:'',number:''});
 const[payroll,setPayroll]=useState({sourceId:'',payrollPeriod:'',postingDate:'',currency:'EGP',expenseTotal:'',expenseAccountId:'',liabilityAccountId:'',liabilityAmount:'',liabilityLabel:'صافي الرواتب',number:''});
 const[payment,setPayment]=useState({runId:'',treasuryId:'',postingDate:'',number:''});
 async function run(action:()=>Promise<unknown>,message:string,reset?:()=>void){setError('');try{await action();reset?.();await done(message);}catch(value){setError(errorMessage(value));}}
 const postable=accounts.filter(value=>value.active&&value.postable),activeTreasuries=treasuries.filter(value=>value.active);
 return <div className="ui-grid-md">
  {error?<Toast tone="error">{error}</Toast>:null}
  <Card title="استبعاد أصل"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(()=>advancedAccountingApi.disposeAsset({commandKey:disposeKey.get(),assetId:disposal.assetId,postingDate:disposal.postingDate,proceeds:disposal.proceeds,proceedsMode:disposal.proceedsMode,...(disposal.treasuryId?{treasuryId:disposal.treasuryId}:{}),...(disposal.proceedsClearingAccountId?{proceedsClearingAccountId:disposal.proceedsClearingAccountId}:{}),number:disposal.number}),'تم استبعاد الأصل.',disposeKey.reset);}}>
   <FormField label="معرف الأصل" required><Input required value={disposal.assetId} onChange={event=>setDisposal({...disposal,assetId:event.target.value})}/></FormField><FormField label="تاريخ الاستبعاد" required><Input required type="date" value={disposal.postingDate} onChange={event=>setDisposal({...disposal,postingDate:event.target.value})}/></FormField><FormField label="المقابل" required><Input required inputMode="decimal" value={disposal.proceeds} onChange={event=>setDisposal({...disposal,proceeds:event.target.value})}/></FormField><FormField label="طريقة المقابل"><Select value={disposal.proceedsMode} onChange={event=>setDisposal({...disposal,proceedsMode:event.target.value as'TREASURY'|'NON_CASH'})}><option value="NON_CASH">غير نقدي</option><option value="TREASURY">خزينة/بنك</option></Select></FormField>
   {disposal.proceedsMode==='TREASURY'?<FormField label="الخزينة/البنك" required><Select required value={disposal.treasuryId} onChange={event=>setDisposal({...disposal,treasuryId:event.target.value})}><option value="">اختر</option>{activeTreasuries.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField>:null}
   <FormField label="حساب المقابل"><Select value={disposal.proceedsClearingAccountId} onChange={event=>setDisposal({...disposal,proceedsClearingAccountId:event.target.value})}><option value="">اختر</option>{postable.map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="رقم القيد" required><Input required value={disposal.number} onChange={event=>setDisposal({...disposal,number:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>استبعاد الأصل</Button>
  </form></Card>
  <Card title="استحقاق الرواتب"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(()=>advancedAccountingApi.accruePayroll({commandKey:payrollKey.get(),sourceId:payroll.sourceId,payrollPeriod:payroll.payrollPeriod,postingDate:payroll.postingDate,currency:payroll.currency,expenseTotal:payroll.expenseTotal,expenseAccountId:payroll.expenseAccountId,liabilities:[{accountId:payroll.liabilityAccountId,amount:payroll.liabilityAmount,label:payroll.liabilityLabel}],number:payroll.number}),'تم ترحيل استحقاق الرواتب.',payrollKey.reset);}}>
   <FormField label="مرجع المصدر" required><Input required value={payroll.sourceId} onChange={event=>setPayroll({...payroll,sourceId:event.target.value})}/></FormField><FormField label="فترة الرواتب" required><Input required value={payroll.payrollPeriod} onChange={event=>setPayroll({...payroll,payrollPeriod:event.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={payroll.postingDate} onChange={event=>setPayroll({...payroll,postingDate:event.target.value})}/></FormField><FormField label="العملة" required><Input required value={payroll.currency} onChange={event=>setPayroll({...payroll,currency:event.target.value.toUpperCase()})}/></FormField><FormField label="إجمالي المصروف" required><Input required inputMode="decimal" value={payroll.expenseTotal} onChange={event=>setPayroll({...payroll,expenseTotal:event.target.value})}/></FormField>
   <FormField label="حساب المصروف" required><Select required value={payroll.expenseAccountId} onChange={event=>setPayroll({...payroll,expenseAccountId:event.target.value})}><option value="">اختر</option>{postable.filter(value=>value.classification==='EXPENSE').map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="حساب الالتزام" required><Select required value={payroll.liabilityAccountId} onChange={event=>setPayroll({...payroll,liabilityAccountId:event.target.value})}><option value="">اختر</option>{postable.filter(value=>value.classification==='LIABILITY').map(value=><option key={value.id} value={value.id}>{accountLabel(value)}</option>)}</Select></FormField><FormField label="قيمة الالتزام" required><Input required inputMode="decimal" value={payroll.liabilityAmount} onChange={event=>setPayroll({...payroll,liabilityAmount:event.target.value})}/></FormField><FormField label="وصف الالتزام" required><Input required value={payroll.liabilityLabel} onChange={event=>setPayroll({...payroll,liabilityLabel:event.target.value})}/></FormField><FormField label="رقم القيد" required><Input required value={payroll.number} onChange={event=>setPayroll({...payroll,number:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>ترحيل الاستحقاق</Button>
  </form></Card>
  <Card title="سداد الرواتب"><form className="ui-filter-grid" onSubmit={event=>{event.preventDefault();void run(()=>advancedAccountingApi.payPayroll(payment),'تم سداد الرواتب.');}}><FormField label="معرف تشغيل الرواتب" required><Input required value={payment.runId} onChange={event=>setPayment({...payment,runId:event.target.value})}/></FormField><FormField label="الخزينة/البنك" required><Select required value={payment.treasuryId} onChange={event=>setPayment({...payment,treasuryId:event.target.value})}><option value="">اختر</option>{activeTreasuries.map(value=><option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</Select></FormField><FormField label="تاريخ السداد" required><Input required type="date" value={payment.postingDate} onChange={event=>setPayment({...payment,postingDate:event.target.value})}/></FormField><FormField label="رقم المستند" required><Input required value={payment.number} onChange={event=>setPayment({...payment,number:event.target.value})}/></FormField><Button type="submit" disabled={!operate}>سداد الرواتب</Button></form></Card>
 </div>;
}
