import{useEffect,useMemo,useState}from'react';
import{ActionBar,Badge,Button,Card,DataGrid,EmptyState,ErrorState,FormField,LoadingState,MasterDetailWorkspace,MetricCard,Select,SettingsWorkspace,Textarea,Toast,WorkspaceNavigation}from'./ui.js';
import{HttpApprovalCenterClient,type ApprovalCenterClient,type FinancialApprovalAction,type FinancialApprovalPolicy,type FinancialApprovalRequest,type QuotationApproval}from'./approval-center-client.js';

type Tab='pending'|'history'|'policies';
type Source='ALL'|'FINANCIAL'|'QUOTATION';
type CenterItem=
 |{readonly key:string;readonly source:'FINANCIAL';readonly id:string;readonly title:string;readonly subtitle:string;readonly amount:string;readonly status:'PENDING'|'APPROVED'|'REJECTED';readonly requestedAt:string;readonly action:FinancialApprovalAction;readonly sourceType:string;readonly sourceId:string;readonly requester:string;readonly drillDown:string}
 |{readonly key:string;readonly source:'QUOTATION';readonly id:string;readonly title:string;readonly subtitle:string;readonly amount:string;readonly status:'PENDING'|'APPROVED'|'REJECTED';readonly requestedAt:string;readonly drillDown:string};

const actionLabel:Record<FinancialApprovalAction,string>={PAYMENT:'دفعة / سداد',PAID_EXPENSE:'مصروف مدفوع',PARTY_NETTING:'مقاصة طرف',COMMISSION_APPROVAL:'اعتماد عمولة',BOOKING_DISCOUNT:'خصم حجز',SERVICE_DISCOUNT:'خصم خدمة'};
const statusLabel:Record<CenterItem['status'],string>={PENDING:'بانتظار القرار',APPROVED:'تمت الموافقة',REJECTED:'مرفوض'};
const navigation=[
 {id:'pending',label:'بانتظار القرار',description:'طلبات تحتاج قرارًا الآن'},
 {id:'history',label:'سجل القرارات',description:'الموافقات والرفض السابقة'},
 {id:'policies',label:'سياسات الموافقة',description:'قواعد الاعتماد المالي الحالية'},
] as const;
function statusTone(status:CenterItem['status']){return status==='APPROVED'?'success':status==='REJECTED'?'warning':'info' as const;}
function latestRevision(quotation:QuotationApproval){return quotation.revisions.find(row=>row.id===quotation.currentRevisionId)??quotation.revisions.at(-1);}
function financialItems(rows:readonly FinancialApprovalRequest[]):CenterItem[]{return rows.map(row=>({key:'financial:'+row.id,source:'FINANCIAL',id:row.id,title:actionLabel[row.action]??row.action,subtitle:row.sourceType+' — '+row.sourceId,amount:row.amount,status:row.status,requestedAt:row.requestedAt,action:row.action,sourceType:row.sourceType,sourceId:row.sourceId,requester:row.requesterActorId,drillDown:'/accounting'}));}
function quotationItems(rows:readonly QuotationApproval[]):CenterItem[]{return rows.filter(row=>row.approvalStatus!=='NOT_REQUIRED').map(row=>{const revision=latestRevision(row);return{key:'quotation:'+row.id,source:'QUOTATION' as const,id:row.id,title:'عرض سعر '+row.number,subtitle:row.customerSnapshot.displayName,amount:(revision?.total??'0')+' '+row.currency,status:row.approvalStatus as CenterItem['status'],requestedAt:row.updatedAt??revision?.createdAt??'',drillDown:'/crm/quotations'};});}
function message(error:unknown){return error instanceof Error?error.message:'تعذر تنفيذ العملية.';}

export function ApprovalCenterPage({client=new HttpApprovalCenterClient()}:{client?:ApprovalCenterClient}={}){
 const[financial,setFinancial]=useState<readonly FinancialApprovalRequest[]>([]),[quotations,setQuotations]=useState<readonly QuotationApproval[]>([]),[policies,setPolicies]=useState<readonly FinancialApprovalPolicy[]>([]);
 const[tab,setTab]=useState<Tab>('pending'),[source,setSource]=useState<Source>('ALL'),[selected,setSelected]=useState<CenterItem|null>(null),[reason,setReason]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const data=await client.load();setFinancial(data.financial);setPolicies(data.policies);setQuotations(data.quotations);}catch(e){setError(message(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const items=useMemo(()=>[...financialItems(financial),...quotationItems(quotations)].sort((a,b)=>(b.requestedAt??'').localeCompare(a.requestedAt??'')||a.key.localeCompare(b.key)),[financial,quotations]);
 const filtered=items.filter(item=>(source==='ALL'||item.source===source)&&(tab==='pending'?item.status==='PENDING':tab==='history'?item.status!=='PENDING':true));
 const pending=items.filter(item=>item.status==='PENDING');
 async function decide(outcome:'APPROVED'|'REJECTED'){if(!selected)return;if(outcome==='REJECTED'&&!reason.trim()){setError('سبب الرفض مطلوب.');return;}setLoading(true);setError('');setNotice('');try{if(selected.source==='FINANCIAL')await client.decideFinancial(selected.id,outcome,reason);else await client.decideQuotation(selected.id,outcome==='APPROVED',reason||'تمت المراجعة من مركز الموافقات');setNotice(outcome==='APPROVED'?'تم تسجيل الموافقة عند المالك الأصلي.':'تم تسجيل الرفض عند المالك الأصلي.');setSelected(null);setReason('');await load();}catch(e){setError(message(e));}finally{setLoading(false);}}
 const requestList=<section aria-label={tab==='pending'?'الطلبات المعلقة':'سجل القرارات'}>
  <div className="ui-inline"><div><h3>{tab==='pending'?'الطلبات المعلقة':'سجل القرارات'}</h3><p className="ui-page-intro">اختر الطلب لمراجعته مع إبقاء القرار والحفظ عند المالك الأصلي.</p></div><FormField label="مصدر الموافقة"><Select value={source} onChange={e=>setSource(e.target.value as Source)}><option value="ALL">كل المصادر</option><option value="FINANCIAL">المالية والرقابة</option><option value="QUOTATION">عروض الأسعار</option></Select></FormField></div>
  {!filtered.length?<EmptyState title={tab==='pending'?'لا توجد طلبات موافقة معلقة':'لا توجد قرارات سابقة'}/>:<DataGrid columns={['المصدر','الطلب','القيمة','الحالة','الوقت','إجراء']}>{filtered.map(item=><tr key={item.key}><td>{item.source==='FINANCIAL'?'الرقابة المالية':'عرض سعر'}</td><td><strong>{item.title}</strong><small className="ui-block">{item.subtitle}</small></td><td>{item.amount}</td><td><Badge tone={statusTone(item.status)}>{statusLabel[item.status]}</Badge></td><td>{item.requestedAt?new Date(item.requestedAt).toLocaleString('ar-EG'):'—'}</td><td><ActionBar>{item.status==='PENDING'?<Button type="button" onClick={()=>{setSelected(item);setReason('');}}>مراجعة</Button>:null}<Button type="button" variant="secondary" onClick={()=>{window.location.href=item.drillDown;}}>فتح المصدر</Button></ActionBar></td></tr>)}</DataGrid>}
 </section>;
 const requestDetail=selected?<section aria-label="تفاصيل قرار الموافقة"><h3>{'مراجعة القرار — '+selected.title}</h3><p>{selected.subtitle}</p><p><strong>القيمة:</strong> {selected.amount}</p><p><strong>الحالة:</strong> <Badge tone={statusTone(selected.status)}>{statusLabel[selected.status]}</Badge></p>{selected.source==='FINANCIAL'?<p>طالب الإجراء: {selected.requester}<br/>المصدر: {selected.sourceType}/{selected.sourceId}</p>:null}<FormField label="ملاحظة / سبب القرار" hint="سبب الرفض إلزامي، ويمكن تسجيل ملاحظة عند الموافقة."><Textarea value={reason} onChange={e=>setReason(e.target.value)}/></FormField><ActionBar><Button type="button" onClick={()=>void decide('APPROVED')} disabled={loading}>موافقة</Button><Button type="button" variant="danger" onClick={()=>void decide('REJECTED')} disabled={loading}>رفض</Button><Button type="button" variant="secondary" onClick={()=>{setSelected(null);setReason('');}}>إغلاق</Button></ActionBar></section>:<EmptyState title="اختر طلبًا للمراجعة">ستظهر هنا بيانات الطلب ومصدره وإجراءات الموافقة أو الرفض.</EmptyState>;
 const content=tab==='policies'?<Card title="سياسات الاعتماد المالي">{!policies.length?<EmptyState title="لا توجد سياسات اعتماد معرفة"/>:<DataGrid columns={['الإجراء','الحد','منع اعتماد النفس','الصلاحية','الحالة']}>{policies.map(policy=><tr key={policy.id}><td>{actionLabel[policy.action]??policy.action}</td><td>{policy.threshold}</td><td>{policy.forbidSelfApproval?'نعم':'لا'}</td><td>{policy.requiredAuthority}</td><td><Badge tone={policy.active?'success':'warning'}>{policy.active?'نشطة':'متوقفة'}</Badge></td></tr>)}</DataGrid>}</Card>:<MasterDetailWorkspace master={requestList} detail={requestDetail}/>;
 return <section dir="rtl" className="ui-dashboard" aria-label="مركز الموافقات">
  <Card title="مركز الموافقات"><p>صندوق موحد لمراجعة القرارات مع إبقاء التنفيذ والحفظ داخل الموديول المالك للعملية.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>void load()} disabled={loading}>تحديث البيانات</Button></ActionBar></Card>
  <div className="ui-metric-grid" aria-label="مؤشرات الموافقات"><MetricCard label="بانتظار القرار" value={pending.length} tone={pending.length?'warning':'success'}/><MetricCard label="موافقات مالية معلقة" value={pending.filter(x=>x.source==='FINANCIAL').length}/><MetricCard label="عروض سعر معلقة" value={pending.filter(x=>x.source==='QUOTATION').length}/><MetricCard label="قرارات مكتملة" value={items.length-pending.length}/></div>
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}{loading?<LoadingState/>:null}
  <SettingsWorkspace navigation={<WorkspaceNavigation items={navigation} active={tab} onChange={id=>{setTab(id as Tab);setSelected(null);setReason('');}} ariaLabel="أقسام مركز الموافقات"/>} content={content}/>
 </section>;
}
