import{type FormEvent,useEffect,useState}from'react';
import{ActionBar,Button,Card,Checkbox,DisclosureCard,FormField,Input,MetricCard,PageHeader,Select,Tabs,Textarea,Toast}from'./ui.js';
import{capabilityApi,type ContractType,type OperationResult,type ServiceCategory}from'./capability-coverage-client.js';

const errorMessage=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية.';
const today=()=>new Date().toISOString().slice(0,10);
const nowIso=()=>new Date().toISOString();

function valueText(value:unknown):string{
 if(value===null||value===undefined)return'—';
 if(typeof value==='boolean')return value?'نعم':'لا';
 if(typeof value==='object')return Array.isArray(value)?`${value.length} سجل`:'بيانات محفوظة';
 return String(value);
}
function ResultPanel({title,result}:{title:string;result:OperationResult|null}){
 if(!result)return null;
 const entries=Object.entries(result).filter(([,value])=>typeof value!=='object'||value===null).slice(0,12);
 return <Card title={title}><div className="ui-grid-md">{entries.map(([key,value])=><div key={key}><small className="ui-block">{key}</small><strong>{valueText(value)}</strong></div>)}</div></Card>;
}
function useOperation(){
 const[result,setResult]=useState<OperationResult|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function run(label:string,operation:()=>Promise<OperationResult>){setError('');setNotice('');try{const value=await operation();setResult(value);setNotice(label);return value}catch(reason){setError(errorMessage(reason));throw reason}}
 return{result,notice,error,run,setResult};
}
const typeLabel:Record<ContractType,string>={HOTEL:'فندق',FLIGHT_BLOCK:'طيران',TRANSPORT:'نقل',VISA:'تأشيرات',SERVICE:'خدمة'};
const categoryLabel:Record<ServiceCategory,string>={CAMP:'مخيم',MEAL:'وجبات',VISIT:'زيارة',GUIDE:'مرشد',RAWDA:'روضة',INSURANCE:'تأمين',OTHER:'أخرى'};

export function TourismContractsInventoryPage(){
 const[tab,setTab]=useState('contracts');
 const op=useOperation();
 const[contract,setContract]=useState({type:'HOTEL' as ContractType,supplierId:'',effectiveFrom:today(),effectiveTo:today()});
 const[lookupId,setLookupId]=useState('');
 const[contractView,setContractView]=useState<{contract:OperationResult|null;versions:OperationResult[]}|null>(null);
 const[amend,setAmend]=useState({contractId:'',effectiveFrom:today(),effectiveTo:'',terms:'{}'});
 const[kind,setKind]=useState<ContractType>('HOTEL');
 const[stock,setStock]=useState({contractId:'',resourceId:'',secondary:'',from:today(),to:today(),quantity:'1',category:'OTHER' as ServiceCategory,name:'',unit:'وحدة',releaseDeadline:''});
 const[availability,setAvailability]=useState({contractId:'',resourceType:'HOTEL' as ContractType,resourceId:'',serviceDate:today(),periodEnd:''});
 const[allocation,setAllocation]=useState({contractId:'',resourceType:'HOTEL' as ContractType,resourceId:'',programType:'TOURISM_PROGRAM',programId:'',serviceDate:today(),periodEnd:'',quantity:'1',flightType:'FLIGHT_SEGMENT',flightId:'',visaType:'VISA_BATCH',visaId:''});
 const[allocationId,setAllocationId]=useState(''),[releaseQuantity,setReleaseQuantity]=useState('1');
 const[allocationView,setAllocationView]=useState<{allocation:OperationResult|null;blockers:OperationResult[]}|null>(null);

 async function createContract(event:FormEvent){event.preventDefault();await op.run('تم إنشاء العقد من خلال المالك المعتمد للتعاقدات والمخزون.',()=>capabilityApi.createContract(contract));}
 async function lookup(event:FormEvent){event.preventDefault();await op.run('تم تحميل العقد وإصداراته.',async()=>{const value=await capabilityApi.contract(lookupId.trim());setContractView(value);return value.contract??{};});}
 async function amendContract(event:FormEvent){event.preventDefault();await op.run('تم حفظ إصدار تعاقدي جديد مع الاحتفاظ بتاريخ الإصدارات.',()=>capabilityApi.amendContract(amend.contractId,{effectiveFrom:amend.effectiveFrom,...(amend.effectiveTo?{effectiveTo:amend.effectiveTo}:{}),terms:JSON.parse(amend.terms)}));}
 async function createInventory(event:FormEvent){event.preventDefault();const base={contractId:stock.contractId};
  if(kind==='HOTEL')await op.run('تمت إضافة سعة الفندق.',()=>capabilityApi.createHotel({...base,hotelId:stock.resourceId,...(stock.secondary?{roomId:stock.secondary}:{}),serviceDate:stock.from,contractedQuantity:stock.quantity}));
  if(kind==='FLIGHT_BLOCK')await op.run('تمت إضافة بلوك الطيران.',()=>capabilityApi.createFlight({...base,flightNumber:stock.resourceId,origin:stock.secondary.split('→')[0]?.trim()||'',destination:stock.secondary.split('→')[1]?.trim()||'',departureDate:stock.from,totalSeats:stock.quantity}));
  if(kind==='TRANSPORT')await op.run('تمت إضافة سعة النقل.',()=>capabilityApi.createTransport({...base,vehicleId:stock.resourceId,capacityUnits:stock.quantity,periodStart:stock.from,periodEnd:stock.to}));
  if(kind==='VISA')await op.run('تمت إضافة حصة التأشيرات.',()=>capabilityApi.createVisa({...base,visaType:stock.resourceId,...(stock.secondary?{nationality:stock.secondary}:{}),quotaTotal:stock.quantity,effectiveFrom:stock.from,effectiveTo:stock.to}));
  if(kind==='SERVICE')await op.run('تمت إضافة مخزون الخدمة.',()=>capabilityApi.createService({...base,category:stock.category,name:stock.name,unit:stock.unit,serviceStart:stock.from,serviceEnd:stock.to,capacity:stock.quantity,...(stock.releaseDeadline?{releaseDeadline:stock.releaseDeadline}:{})}));
 }
 async function checkAvailability(event:FormEvent){event.preventDefault();await op.run('تم فحص الإتاحة من المخزون الحقيقي.',()=>capabilityApi.availability({...availability,...(availability.periodEnd?{periodEnd:availability.periodEnd}:{})}));}
 async function allocate(event:FormEvent){event.preventDefault();await op.run('تم إنشاء التخصيص من المخزون المعتمد.',()=>capabilityApi.allocate({...allocation,program:{sourceType:allocation.programType,sourceId:allocation.programId},...(allocation.periodEnd?{periodEnd:allocation.periodEnd}:{}),...(allocation.resourceType==='FLIGHT_BLOCK'?{flightSegment:{sourceType:allocation.flightType,sourceId:allocation.flightId}}:{}),...(allocation.resourceType==='VISA'?{visaBatch:{sourceType:allocation.visaType,sourceId:allocation.visaId}}:{})}));}
 async function loadAllocation(event:FormEvent){event.preventDefault();await op.run('تم تحميل التخصيص وموانع التحرير.',async()=>{const value=await capabilityApi.allocation(allocationId.trim());setAllocationView(value);return value.allocation??{};});}
 async function release(event:FormEvent){event.preventDefault();await op.run('تم تنفيذ طلب تحرير السعة وفق موانع المخزون المسجلة.',()=>capabilityApi.release(allocationId,{quantity:releaseQuantity}));}

 return <section dir="rtl" className="ui-page-stack" aria-label="التعاقدات والمخزون">
  <PageHeader eyebrow="السياحة والخدمات" title="التعاقدات والمخزون" description="إدارة العقود والسعات والتخصيصات من المصدر المعتمد المشترك بين السياحة والحج والعمرة."/>
  <div className="ui-metric-grid"><MetricCard label="مالك الحقيقة" value="Tourism Contract Inventory"/><MetricCard label="النطاق" value="عقود · سعات · تخصيص"/><MetricCard label="الاستخدام" value="السياحة + الحج والعمرة"/></div>
  {op.notice?<Toast tone="success">{op.notice}</Toast>:null}{op.error?<Toast tone="error">{op.error}</Toast>:null}
  <Tabs tabs={[{id:'contracts',label:'العقود'},{id:'inventory',label:'السعات والمخزون'},{id:'allocations',label:'التخصيصات'}]} active={tab} onChange={setTab}/>
  {tab==='contracts'?<>
   <DisclosureCard title="عقد جديد" description="سجل العقد التجاري الأساسي؛ التعديلات اللاحقة تحفظ كإصدارات."><form className="ui-filter-grid" onSubmit={createContract}>
    <FormField label="نوع العقد"><Select value={contract.type} onChange={e=>setContract({...contract,type:e.target.value as ContractType})}>{Object.entries(typeLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField>
    <FormField label="المورد"><Input value={contract.supplierId} onChange={e=>setContract({...contract,supplierId:e.target.value})}/></FormField>
    <FormField label="ساري من" required><Input required type="date" value={contract.effectiveFrom} onChange={e=>setContract({...contract,effectiveFrom:e.target.value})}/></FormField>
    <FormField label="ساري إلى" required><Input required type="date" value={contract.effectiveTo} onChange={e=>setContract({...contract,effectiveTo:e.target.value})}/></FormField><Button type="submit">إنشاء العقد</Button>
   </form></DisclosureCard>
   <Card title="فتح عقد"><form className="ui-filter-grid" onSubmit={lookup}><FormField label="معرّف العقد" required><Input required value={lookupId} onChange={e=>setLookupId(e.target.value)}/></FormField><Button type="submit">عرض العقد</Button></form>{contractView?.contract?<div className="ui-grid-md"><MetricCard label="الحالة" value={valueText(contractView.contract.status)}/><MetricCard label="النوع" value={valueText(contractView.contract.type)}/><MetricCard label="عدد الإصدارات" value={contractView.versions.length}/></div>:null}</Card>
   <DisclosureCard title="تعديل تعاقدي" description="ينشئ إصدارًا جديدًا بدل الكتابة فوق التاريخ."><form className="ui-filter-grid" onSubmit={amendContract}><FormField label="معرّف العقد" required><Input required value={amend.contractId} onChange={e=>setAmend({...amend,contractId:e.target.value})}/></FormField><FormField label="ساري من" required><Input required type="date" value={amend.effectiveFrom} onChange={e=>setAmend({...amend,effectiveFrom:e.target.value})}/></FormField><FormField label="ساري إلى"><Input type="date" value={amend.effectiveTo} onChange={e=>setAmend({...amend,effectiveTo:e.target.value})}/></FormField><FormField label="الشروط (JSON)"><Textarea value={amend.terms} onChange={e=>setAmend({...amend,terms:e.target.value})}/></FormField><Button type="submit">حفظ إصدار جديد</Button></form></DisclosureCard>
  </>:null}
  {tab==='inventory'?<>
   <DisclosureCard title="إضافة سعة / مخزون" description="السعة ترتبط بعقد قائم ولا تنشئ مصدر حقيقة جديدًا."><form className="ui-filter-grid" onSubmit={createInventory}>
    <FormField label="نوع المخزون"><Select value={kind} onChange={e=>setKind(e.target.value as ContractType)}>{Object.entries(typeLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField>
    <FormField label="معرّف العقد" required><Input required value={stock.contractId} onChange={e=>setStock({...stock,contractId:e.target.value})}/></FormField>
    {kind==='SERVICE'?<><FormField label="تصنيف الخدمة"><Select value={stock.category} onChange={e=>setStock({...stock,category:e.target.value as ServiceCategory})}>{Object.entries(categoryLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="اسم الخدمة" required><Input required value={stock.name} onChange={e=>setStock({...stock,name:e.target.value})}/></FormField><FormField label="الوحدة"><Input value={stock.unit} onChange={e=>setStock({...stock,unit:e.target.value})}/></FormField></>:<FormField label={kind==='HOTEL'?'معرّف الفندق':kind==='FLIGHT_BLOCK'?'رقم الرحلة':kind==='TRANSPORT'?'معرّف المركبة':'نوع التأشيرة'} required><Input required value={stock.resourceId} onChange={e=>setStock({...stock,resourceId:e.target.value})}/></FormField>}
    {kind==='HOTEL'?<FormField label="الغرفة / الفئة"><Input value={stock.secondary} onChange={e=>setStock({...stock,secondary:e.target.value})}/></FormField>:kind==='FLIGHT_BLOCK'?<FormField label="المسار"><Input placeholder="CAI → JED" value={stock.secondary} onChange={e=>setStock({...stock,secondary:e.target.value})}/></FormField>:kind==='VISA'?<FormField label="الجنسية"><Input value={stock.secondary} onChange={e=>setStock({...stock,secondary:e.target.value})}/></FormField>:null}
    <FormField label={kind==='HOTEL'||kind==='FLIGHT_BLOCK'?'التاريخ':'من'} required><Input required type="date" value={stock.from} onChange={e=>setStock({...stock,from:e.target.value})}/></FormField>
    {kind!=='HOTEL'&&kind!=='FLIGHT_BLOCK'?<FormField label="إلى" required><Input required type="date" value={stock.to} onChange={e=>setStock({...stock,to:e.target.value})}/></FormField>:null}
    <FormField label="الكمية / السعة" required><Input required inputMode="decimal" value={stock.quantity} onChange={e=>setStock({...stock,quantity:e.target.value})}/></FormField>
    {kind==='SERVICE'?<FormField label="آخر موعد للتحرير"><Input type="date" value={stock.releaseDeadline} onChange={e=>setStock({...stock,releaseDeadline:e.target.value})}/></FormField>:null}
    <Button type="submit">حفظ المخزون</Button>
   </form></DisclosureCard>
   <Card title="فحص الإتاحة"><form className="ui-filter-grid" onSubmit={checkAvailability}><FormField label="العقد" required><Input required value={availability.contractId} onChange={e=>setAvailability({...availability,contractId:e.target.value})}/></FormField><FormField label="النوع"><Select value={availability.resourceType} onChange={e=>setAvailability({...availability,resourceType:e.target.value as ContractType})}>{Object.entries(typeLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="المورد/السعة" required><Input required value={availability.resourceId} onChange={e=>setAvailability({...availability,resourceId:e.target.value})}/></FormField><FormField label="التاريخ" required><Input required type="date" value={availability.serviceDate} onChange={e=>setAvailability({...availability,serviceDate:e.target.value})}/></FormField><Button type="submit">فحص الإتاحة</Button></form></Card>
  </>:null}
  {tab==='allocations'?<>
   <DisclosureCard title="تخصيص سعة لبرنامج" description="يخصم من السعة المتاحة مع الاحتفاظ بدليل البرنامج."><form className="ui-filter-grid" onSubmit={allocate}><FormField label="العقد" required><Input required value={allocation.contractId} onChange={e=>setAllocation({...allocation,contractId:e.target.value})}/></FormField><FormField label="نوع السعة"><Select value={allocation.resourceType} onChange={e=>setAllocation({...allocation,resourceType:e.target.value as ContractType})}>{Object.entries(typeLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="معرّف السعة" required><Input required value={allocation.resourceId} onChange={e=>setAllocation({...allocation,resourceId:e.target.value})}/></FormField><FormField label="نوع البرنامج"><Input value={allocation.programType} onChange={e=>setAllocation({...allocation,programType:e.target.value.toUpperCase()})}/></FormField><FormField label="معرّف البرنامج" required><Input required value={allocation.programId} onChange={e=>setAllocation({...allocation,programId:e.target.value})}/></FormField><FormField label="تاريخ الخدمة" required><Input required type="date" value={allocation.serviceDate} onChange={e=>setAllocation({...allocation,serviceDate:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={allocation.quantity} onChange={e=>setAllocation({...allocation,quantity:e.target.value})}/></FormField>{allocation.resourceType==='FLIGHT_BLOCK'?<FormField label="مرجع قطاع الطيران" required><Input required value={allocation.flightId} onChange={e=>setAllocation({...allocation,flightId:e.target.value})}/></FormField>:null}{allocation.resourceType==='VISA'?<FormField label="مرجع دفعة التأشيرة" required><Input required value={allocation.visaId} onChange={e=>setAllocation({...allocation,visaId:e.target.value})}/></FormField>:null}<Button type="submit">تخصيص</Button></form></DisclosureCard>
   <Card title="فتح تخصيص / تحرير سعة"><form className="ui-filter-grid" onSubmit={loadAllocation}><FormField label="معرّف التخصيص" required><Input required value={allocationId} onChange={e=>setAllocationId(e.target.value)}/></FormField><Button type="submit">عرض</Button></form>{allocationView?<div className="ui-grid-md"><MetricCard label="حالة التخصيص" value={valueText(allocationView.allocation?.status)}/><MetricCard label="الكمية" value={valueText(allocationView.allocation?.quantity)}/><MetricCard label="موانع التحرير" value={allocationView.blockers.length} tone={allocationView.blockers.length?'warning':'neutral'}/></div>:null}<form className="ui-filter-grid" onSubmit={release}><FormField label="الكمية المطلوب تحريرها" required><Input required inputMode="decimal" value={releaseQuantity} onChange={e=>setReleaseQuantity(e.target.value)}/></FormField><Button type="submit" variant="secondary">تحرير السعة</Button></form></Card>
  </>:null}
  <ResultPanel title="آخر نتيجة" result={op.result}/>
 </section>;
}

export type AccountingCapabilityTab='currency'|'cost'|'parties'|'expenses'|'assets';
const accountingTabs=[{id:'currency',label:'العملات وأسعار الصرف'},{id:'cost',label:'مراكز التكلفة والموازنات'},{id:'parties',label:'حسابات الأطراف والمقاصة'},{id:'expenses',label:'المصروفات والعمولات'},{id:'assets',label:'الأصول والتمويل'}];

export function AccountingCapabilitiesPage({initialTab='currency'}:{initialTab?:AccountingCapabilityTab}){
 const[tab,setTab]=useState(initialTab);useEffect(()=>setTab(initialTab),[initialTab]);
 const op=useOperation();
 const[currency,setCurrency]=useState({code:'EGP',precision:'2',isBase:true,status:'ACTIVE' as 'ACTIVE'|'INACTIVE'});
 const[rate,setRate]=useState({fromCurrency:'USD',toCurrency:'EGP',effectiveAt:nowIso(),rate:'1',source:'BANK'});
 const[resolve,setResolve]=useState({fromCurrency:'USD',toCurrency:'EGP',at:nowIso()});
 const[cost,setCost]=useState({id:'',code:'',name:'',parentId:''}),[costLookup,setCostLookup]=useState('');
 const[budget,setBudget]=useState({id:'',costCenterId:'',periodStart:today(),periodEnd:today(),currency:'EGP',amount:'0'}),[budgetActionId,setBudgetActionId]=useState('');
 const[group,setGroup]=useState({name:'',customerPartyId:'',supplierPartyId:''});
 const[netting,setNetting]=useState({id:'',groupId:'',customerInvoiceId:'',supplierInvoiceId:'',amount:'0',postingDate:today(),number:'',approvalRequestId:''}),[nettingActionId,setNettingActionId]=useState('');
 const[expense,setExpense]=useState({form:'DIRECT_PAID',sourceType:'MANUAL_EXPENSE',sourceId:'',currency:'EGP',amount:'0',baseAmount:'0',expenseAccountId:'',prepaidAccountId:'',billingInvoiceId:'',approvalRequestId:''});
 const[expensePay,setExpensePay]=useState({expenseId:'',treasuryId:'',paymentCurrency:'EGP',postingDate:today(),number:''});
 const[commission,setCommission]=useState({agentPartyId:'',sourceType:'SALE',sourceId:'',currency:'EGP',amount:'0',baseCarryingAmount:'0',expenseAccountId:'',liabilityAccountId:'',approvalRequestId:''});
 const[commissionAction,setCommissionAction]=useState({claimId:'',treasuryId:'',amount:'0',paymentCurrency:'EGP',postingDate:today(),number:''});
 const[asset,setAsset]=useState({number:'',code:'',name:'',acquisitionValue:'0',baseValue:'0',currency:'EGP',acquisitionDate:today(),capitalizationDate:today(),inServiceDate:today(),residualValue:'0',usefulLifeMonths:'36',assetAccountId:'',capitalizationOffsetAccountId:'',accumulatedDepreciationAccountId:'',depreciationExpenseAccountId:''});
 const[depr,setDepr]=useState({assetId:'',period:'1',postingDate:today(),number:''});
 const[loan,setLoan]=useState({lenderId:'',reference:'',principal:'0',currency:'EGP',baseAmount:'0',liabilityAccountId:'',interestExpenseAccountId:'',fundingTreasuryId:'',postingDate:today(),number:'',installments:''});
 const[loanPay,setLoanPay]=useState({loanId:'',installmentId:'',treasuryId:'',postingDate:today(),number:''});

 async function configureCurrency(e:FormEvent){e.preventDefault();await op.run('تم حفظ إعداد العملة.',()=>capabilityApi.configureCurrency({...currency,precision:Number(currency.precision)}));}
 async function publishRate(e:FormEvent){e.preventDefault();await op.run('تم نشر سعر الصرف.',()=>capabilityApi.publishRate(rate));}
 async function resolveRate(e:FormEvent){e.preventDefault();await op.run('تم استرجاع سعر الصرف المعتمد.',()=>capabilityApi.resolveRate(resolve));}
 async function createCost(e:FormEvent){e.preventDefault();await op.run('تم إنشاء مركز التكلفة.',()=>capabilityApi.createCostCenter({...cost,...(cost.id?{id:cost.id}:{}),...(cost.parentId?{parentId:cost.parentId}:{})}));}
 async function lookupCost(){await op.run('تم تحميل مركز التكلفة.',()=>capabilityApi.costCenter(costLookup));}
 async function createBudget(e:FormEvent){e.preventDefault();await op.run('تم إنشاء الموازنة.',()=>capabilityApi.createBudget({...budget,...(budget.id?{id:budget.id}:{})}));}
 async function budgetAction(action:'authorize'|'check'){await op.run(action==='authorize'?'تم اعتماد الموازنة.':'تم فحص الموازنة مقابل الفعلي.',()=>action==='authorize'?capabilityApi.authorizeBudget(budgetActionId):capabilityApi.checkBudget(budgetActionId));}
 async function createGroup(e:FormEvent){e.preventDefault();await op.run('تم إنشاء مجموعة أطراف للمقاصة.',()=>capabilityApi.createPartyGroup({name:group.name,members:[{role:'CUSTOMER',partyId:group.customerPartyId},{role:'SUPPLIER',partyId:group.supplierPartyId}]}));}
 async function proposeNetting(e:FormEvent){e.preventDefault();await op.run('تم إنشاء مقترح المقاصة.',()=>capabilityApi.proposeNetting({...netting,...(netting.id?{id:netting.id}:{}),...(netting.approvalRequestId?{approvalRequestId:netting.approvalRequestId}:{})}));}
 async function nettingActionFn(action:'execute'|'reverse'){await op.run(action==='execute'?'تم تنفيذ المقاصة.':'تم عكس المقاصة.',()=>action==='execute'?capabilityApi.executeNetting(nettingActionId):capabilityApi.reverseNetting(nettingActionId,{postingDate:today(),number:'REV-'+nettingActionId.slice(0,8)}));}
 async function createExpense(e:FormEvent){e.preventDefault();await op.run('تم إنشاء المصروف في المالك المحاسبي.',()=>capabilityApi.createExpense({...expense,...(expense.expenseAccountId?{expenseAccountId:expense.expenseAccountId}:{}),...(expense.prepaidAccountId?{prepaidAccountId:expense.prepaidAccountId}:{}),...(expense.billingInvoiceId?{billingInvoiceId:expense.billingInvoiceId}:{}),...(expense.approvalRequestId?{approvalRequestId:expense.approvalRequestId}:{})}));}
 async function payExpense(e:FormEvent){e.preventDefault();await op.run('تم ترحيل المصروف المدفوع.',()=>capabilityApi.payExpense(expensePay.expenseId,expensePay));}
 async function createCommission(e:FormEvent){e.preventDefault();await op.run('تم إنشاء مطالبة العمولة.',()=>capabilityApi.createCommission({...commission,...(commission.approvalRequestId?{approvalRequestId:commission.approvalRequestId}:{})}));}
 async function commissionActionFn(action:'approve'|'pay'){await op.run(action==='approve'?'تم اعتماد العمولة.':'تم سداد العمولة.',()=>action==='approve'?capabilityApi.approveCommission(commissionAction.claimId,{postingDate:commissionAction.postingDate,number:commissionAction.number}):capabilityApi.payCommission(commissionAction.claimId,commissionAction));}
 async function registerAsset(e:FormEvent){e.preventDefault();await op.run('تم تسجيل الأصل وترحيل رسملته.',()=>capabilityApi.registerAsset({...asset,usefulLifeMonths:Number(asset.usefulLifeMonths)}));}
 async function depreciate(e:FormEvent){e.preventDefault();await op.run('تم ترحيل إهلاك الأصل.',()=>capabilityApi.depreciateAsset(depr.assetId,{period:Number(depr.period),postingDate:depr.postingDate,number:depr.number}));}
 async function originateLoan(e:FormEvent){e.preventDefault();const installments=loan.installments.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const[dueDate,principal,interest]=line.split(',').map(v=>v.trim());return{dueDate,principal,interest}});await op.run('تم إنشاء التمويل وجدول الأقساط.',()=>capabilityApi.originateLoan({...loan,installments}));}
 async function payInstallment(e:FormEvent){e.preventDefault();await op.run('تم سداد قسط التمويل.',()=>capabilityApi.payLoanInstallment(loanPay.loanId,loanPay.installmentId,loanPay));}

 return <section dir="rtl" className="ui-page-stack" aria-label="القدرات المحاسبية">
  <PageHeader eyebrow="المحاسبة والمالية" title={accountingTabs.find(x=>x.id===tab)?.label??'القدرات المحاسبية'} description="واجهة تشغيل مباشرة فوق أصحاب الحقيقة المحاسبيين المعتمدين؛ لا أرصدة ولا قيود مكررة في الواجهة."/>
  {op.notice?<Toast tone="success">{op.notice}</Toast>:null}{op.error?<Toast tone="error">{op.error}</Toast>:null}
  <Tabs tabs={accountingTabs} active={tab} onChange={id=>setTab(id as AccountingCapabilityTab)}/>
  {tab==='currency'?<>
   <div className="ui-grid-md"><DisclosureCard title="إعداد عملة"><form onSubmit={configureCurrency}><FormField label="الكود"><Input required value={currency.code} onChange={e=>setCurrency({...currency,code:e.target.value.toUpperCase()})}/></FormField><FormField label="الدقة"><Input required inputMode="numeric" value={currency.precision} onChange={e=>setCurrency({...currency,precision:e.target.value})}/></FormField><FormField label="الحالة"><Select value={currency.status} onChange={e=>setCurrency({...currency,status:e.target.value as 'ACTIVE'|'INACTIVE'})}><option value="ACTIVE">نشطة</option><option value="INACTIVE">غير نشطة</option></Select></FormField><label className="ui-checkbox-field"><Checkbox checked={currency.isBase} onChange={e=>setCurrency({...currency,isBase:e.target.checked})}/><span>العملة الأساسية</span></label><Button type="submit">حفظ العملة</Button></form></DisclosureCard>
   <DisclosureCard title="نشر سعر صرف"><form onSubmit={publishRate}><FormField label="من"><Input required value={rate.fromCurrency} onChange={e=>setRate({...rate,fromCurrency:e.target.value.toUpperCase()})}/></FormField><FormField label="إلى"><Input required value={rate.toCurrency} onChange={e=>setRate({...rate,toCurrency:e.target.value.toUpperCase()})}/></FormField><FormField label="السعر"><Input required inputMode="decimal" value={rate.rate} onChange={e=>setRate({...rate,rate:e.target.value})}/></FormField><FormField label="المصدر"><Input required value={rate.source} onChange={e=>setRate({...rate,source:e.target.value})}/></FormField><Button type="submit">نشر السعر</Button></form></DisclosureCard></div>
   <Card title="استعلام سعر"><form className="ui-filter-grid" onSubmit={resolveRate}><FormField label="من"><Input required value={resolve.fromCurrency} onChange={e=>setResolve({...resolve,fromCurrency:e.target.value.toUpperCase()})}/></FormField><FormField label="إلى"><Input required value={resolve.toCurrency} onChange={e=>setResolve({...resolve,toCurrency:e.target.value.toUpperCase()})}/></FormField><Button type="submit">استعلام</Button></form></Card>
  </>:null}
  {tab==='cost'?<>
   <div className="ui-grid-md"><DisclosureCard title="مركز تكلفة جديد"><form onSubmit={createCost}><FormField label="الكود"><Input required value={cost.code} onChange={e=>setCost({...cost,code:e.target.value.toUpperCase()})}/></FormField><FormField label="الاسم"><Input required value={cost.name} onChange={e=>setCost({...cost,name:e.target.value})}/></FormField><FormField label="المركز الأب"><Input value={cost.parentId} onChange={e=>setCost({...cost,parentId:e.target.value})}/></FormField><Button type="submit">إنشاء المركز</Button></form></DisclosureCard>
   <DisclosureCard title="موازنة"><form onSubmit={createBudget}><FormField label="مركز التكلفة"><Input required value={budget.costCenterId} onChange={e=>setBudget({...budget,costCenterId:e.target.value})}/></FormField><FormField label="من"><Input required type="date" value={budget.periodStart} onChange={e=>setBudget({...budget,periodStart:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={budget.periodEnd} onChange={e=>setBudget({...budget,periodEnd:e.target.value})}/></FormField><FormField label="العملة"><Input required value={budget.currency} onChange={e=>setBudget({...budget,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="القيمة"><Input required inputMode="decimal" value={budget.amount} onChange={e=>setBudget({...budget,amount:e.target.value})}/></FormField><Button type="submit">إنشاء الموازنة</Button></form></DisclosureCard></div>
   <Card title="استعلام وتشغيل"><div className="ui-filter-grid"><FormField label="مركز تكلفة"><Input value={costLookup} onChange={e=>setCostLookup(e.target.value)}/></FormField><Button onClick={()=>void lookupCost()}>عرض المركز</Button><FormField label="معرّف الموازنة"><Input value={budgetActionId} onChange={e=>setBudgetActionId(e.target.value)}/></FormField><Button onClick={()=>void budgetAction('check')}>فحص</Button><Button variant="secondary" onClick={()=>void budgetAction('authorize')}>اعتماد</Button></div></Card>
  </>:null}
  {tab==='parties'?<>
   <div className="ui-grid-md"><DisclosureCard title="مجموعة أطراف"><form onSubmit={createGroup}><FormField label="اسم المجموعة"><Input required value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></FormField><FormField label="طرف العميل"><Input required value={group.customerPartyId} onChange={e=>setGroup({...group,customerPartyId:e.target.value})}/></FormField><FormField label="طرف المورد"><Input required value={group.supplierPartyId} onChange={e=>setGroup({...group,supplierPartyId:e.target.value})}/></FormField><Button type="submit">إنشاء المجموعة</Button></form></DisclosureCard>
   <DisclosureCard title="مقاصة عميل / مورد"><form onSubmit={proposeNetting}><FormField label="المجموعة"><Input required value={netting.groupId} onChange={e=>setNetting({...netting,groupId:e.target.value})}/></FormField><FormField label="فاتورة العميل"><Input required value={netting.customerInvoiceId} onChange={e=>setNetting({...netting,customerInvoiceId:e.target.value})}/></FormField><FormField label="فاتورة المورد"><Input required value={netting.supplierInvoiceId} onChange={e=>setNetting({...netting,supplierInvoiceId:e.target.value})}/></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={netting.amount} onChange={e=>setNetting({...netting,amount:e.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={netting.number} onChange={e=>setNetting({...netting,number:e.target.value})}/></FormField><Button type="submit">اقتراح المقاصة</Button></form></DisclosureCard></div>
   <Card title="تنفيذ / عكس المقاصة"><ActionBar><Input placeholder="معرّف المقاصة" value={nettingActionId} onChange={e=>setNettingActionId(e.target.value)}/><Button onClick={()=>void nettingActionFn('execute')}>تنفيذ</Button><Button variant="secondary" onClick={()=>void nettingActionFn('reverse')}>عكس</Button></ActionBar></Card>
  </>:null}
  {tab==='expenses'?<>
   <div className="ui-grid-md"><DisclosureCard title="مصروف جديد"><form onSubmit={createExpense}><FormField label="النوع"><Select value={expense.form} onChange={e=>setExpense({...expense,form:e.target.value})}><option value="DIRECT_PAID">مدفوع مباشر</option><option value="SUPPLIER_PAYABLE">مستحق مورد</option><option value="PREPAID">مصروف مقدم</option><option value="CANCELLATION_PENALTY">غرامة إلغاء</option></Select></FormField><FormField label="مرجع المصدر"><Input required value={expense.sourceId} onChange={e=>setExpense({...expense,sourceId:e.target.value})}/></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value,baseAmount:e.target.value})}/></FormField><FormField label="حساب المصروف"><Input value={expense.expenseAccountId} onChange={e=>setExpense({...expense,expenseAccountId:e.target.value})}/></FormField><Button type="submit">إنشاء المصروف</Button></form></DisclosureCard>
   <DisclosureCard title="مطالبة عمولة"><form onSubmit={createCommission}><FormField label="الوكيل / الطرف"><Input required value={commission.agentPartyId} onChange={e=>setCommission({...commission,agentPartyId:e.target.value})}/></FormField><FormField label="مرجع العملية"><Input required value={commission.sourceId} onChange={e=>setCommission({...commission,sourceId:e.target.value})}/></FormField><FormField label="المبلغ"><Input required inputMode="decimal" value={commission.amount} onChange={e=>setCommission({...commission,amount:e.target.value,baseCarryingAmount:e.target.value})}/></FormField><FormField label="حساب المصروف"><Input required value={commission.expenseAccountId} onChange={e=>setCommission({...commission,expenseAccountId:e.target.value})}/></FormField><FormField label="حساب الالتزام"><Input required value={commission.liabilityAccountId} onChange={e=>setCommission({...commission,liabilityAccountId:e.target.value})}/></FormField><Button type="submit">إنشاء المطالبة</Button></form></DisclosureCard></div>
   <Card title="سداد مصروف"><form className="ui-filter-grid" onSubmit={payExpense}><FormField label="المصروف"><Input required value={expensePay.expenseId} onChange={e=>setExpensePay({...expensePay,expenseId:e.target.value})}/></FormField><FormField label="الخزينة"><Input required value={expensePay.treasuryId} onChange={e=>setExpensePay({...expensePay,treasuryId:e.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={expensePay.number} onChange={e=>setExpensePay({...expensePay,number:e.target.value})}/></FormField><Button type="submit">ترحيل السداد</Button></form></Card>
   <Card title="اعتماد / سداد عمولة"><div className="ui-filter-grid"><FormField label="المطالبة"><Input value={commissionAction.claimId} onChange={e=>setCommissionAction({...commissionAction,claimId:e.target.value})}/></FormField><FormField label="الخزينة"><Input value={commissionAction.treasuryId} onChange={e=>setCommissionAction({...commissionAction,treasuryId:e.target.value})}/></FormField><FormField label="المبلغ"><Input inputMode="decimal" value={commissionAction.amount} onChange={e=>setCommissionAction({...commissionAction,amount:e.target.value})}/></FormField><FormField label="رقم المستند"><Input value={commissionAction.number} onChange={e=>setCommissionAction({...commissionAction,number:e.target.value})}/></FormField><Button onClick={()=>void commissionActionFn('approve')}>اعتماد</Button><Button variant="secondary" onClick={()=>void commissionActionFn('pay')}>سداد</Button></div></Card>
  </>:null}
  {tab==='assets'?<>
   <DisclosureCard title="تسجيل أصل ثابت"><form className="ui-filter-grid" onSubmit={registerAsset}><FormField label="الكود"><Input required value={asset.code} onChange={e=>setAsset({...asset,code:e.target.value})}/></FormField><FormField label="الاسم"><Input required value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})}/></FormField><FormField label="رقم القيد"><Input required value={asset.number} onChange={e=>setAsset({...asset,number:e.target.value})}/></FormField><FormField label="القيمة"><Input required inputMode="decimal" value={asset.acquisitionValue} onChange={e=>setAsset({...asset,acquisitionValue:e.target.value,baseValue:e.target.value})}/></FormField><FormField label="القيمة التخريدية"><Input required inputMode="decimal" value={asset.residualValue} onChange={e=>setAsset({...asset,residualValue:e.target.value})}/></FormField><FormField label="العمر بالشهور"><Input required inputMode="numeric" value={asset.usefulLifeMonths} onChange={e=>setAsset({...asset,usefulLifeMonths:e.target.value})}/></FormField><FormField label="حساب الأصل"><Input required value={asset.assetAccountId} onChange={e=>setAsset({...asset,assetAccountId:e.target.value})}/></FormField><FormField label="حساب مقابل الرسملة"><Input required value={asset.capitalizationOffsetAccountId} onChange={e=>setAsset({...asset,capitalizationOffsetAccountId:e.target.value})}/></FormField><FormField label="مجمع الإهلاك"><Input required value={asset.accumulatedDepreciationAccountId} onChange={e=>setAsset({...asset,accumulatedDepreciationAccountId:e.target.value})}/></FormField><FormField label="مصروف الإهلاك"><Input required value={asset.depreciationExpenseAccountId} onChange={e=>setAsset({...asset,depreciationExpenseAccountId:e.target.value})}/></FormField><Button type="submit">تسجيل الأصل</Button></form></DisclosureCard>
   <Card title="إهلاك أصل"><form className="ui-filter-grid" onSubmit={depreciate}><FormField label="الأصل"><Input required value={depr.assetId} onChange={e=>setDepr({...depr,assetId:e.target.value})}/></FormField><FormField label="الفترة"><Input required inputMode="numeric" value={depr.period} onChange={e=>setDepr({...depr,period:e.target.value})}/></FormField><FormField label="رقم القيد"><Input required value={depr.number} onChange={e=>setDepr({...depr,number:e.target.value})}/></FormField><Button type="submit">ترحيل الإهلاك</Button></form></Card>
   <DisclosureCard title="تمويل / قرض جديد"><form className="ui-filter-grid" onSubmit={originateLoan}><FormField label="الممول"><Input required value={loan.lenderId} onChange={e=>setLoan({...loan,lenderId:e.target.value})}/></FormField><FormField label="المرجع"><Input required value={loan.reference} onChange={e=>setLoan({...loan,reference:e.target.value})}/></FormField><FormField label="أصل التمويل"><Input required inputMode="decimal" value={loan.principal} onChange={e=>setLoan({...loan,principal:e.target.value,baseAmount:e.target.value})}/></FormField><FormField label="حساب الالتزام"><Input required value={loan.liabilityAccountId} onChange={e=>setLoan({...loan,liabilityAccountId:e.target.value})}/></FormField><FormField label="مصروف الفائدة"><Input required value={loan.interestExpenseAccountId} onChange={e=>setLoan({...loan,interestExpenseAccountId:e.target.value})}/></FormField><FormField label="خزينة التمويل"><Input required value={loan.fundingTreasuryId} onChange={e=>setLoan({...loan,fundingTreasuryId:e.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={loan.number} onChange={e=>setLoan({...loan,number:e.target.value})}/></FormField><FormField label="الأقساط" hint="كل سطر: YYYY-MM-DD, principal, interest"><Textarea required value={loan.installments} onChange={e=>setLoan({...loan,installments:e.target.value})}/></FormField><Button type="submit">إنشاء التمويل</Button></form></DisclosureCard>
   <Card title="سداد قسط"><form className="ui-filter-grid" onSubmit={payInstallment}><FormField label="القرض"><Input required value={loanPay.loanId} onChange={e=>setLoanPay({...loanPay,loanId:e.target.value})}/></FormField><FormField label="القسط"><Input required value={loanPay.installmentId} onChange={e=>setLoanPay({...loanPay,installmentId:e.target.value})}/></FormField><FormField label="الخزينة"><Input required value={loanPay.treasuryId} onChange={e=>setLoanPay({...loanPay,treasuryId:e.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={loanPay.number} onChange={e=>setLoanPay({...loanPay,number:e.target.value})}/></FormField><Button type="submit">سداد القسط</Button></form></Card>
  </>:null}
  <ResultPanel title="آخر نتيجة" result={op.result}/>
 </section>;
}
