import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{Badge,Button,Card,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,Select,Textarea,Toast}from'./ui.js';

type Channel='IN_APP'|'EMAIL'|'WHATSAPP'|'SMS';
type Template={id:string;code:string;channel:Channel;language:string;subject:string|null;body:string;active:boolean;createdAt:string;updatedAt:string};
type Delivery={id:string;channel:Channel;userId:string|null;recipient:string;language:string;subject:string|null;body:string;status:'SCHEDULED'|'PENDING'|'SENDING'|'SENT'|'RETRY'|'DEAD_LETTER'|'CANCELLED';scheduledAt:string;attempt:number;maxAttempts:number;providerReference:string|null;lastError:string|null;createdAt:string;updatedAt:string};
function message(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}
function variables(text:string){if(!text.trim())return{};try{const value=JSON.parse(text) as unknown;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,String(v)]));}catch{throw new Error('المتغيرات يجب أن تكون JSON صحيحًا.');}}

export function CommunicationCenterPage(){
 const[templates,setTemplates]=useState<Template[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[template,setTemplate]=useState({code:'',channel:'EMAIL' as Channel,language:'ar',subject:'',body:''}),[queue,setQueue]=useState({templateCode:'',channel:'EMAIL' as Channel,language:'ar',recipient:'',userId:'',variables:'{}',scheduledAt:''}),[preference,setPreference]=useState({userId:'',channel:'EMAIL' as Channel,enabled:'true'});
 async function load(){try{const[t,d]=await Promise.all([crmGet<Template[]>('/communications/templates'),crmGet<Delivery[]>('/communications/deliveries')]);setTemplates(t);setDeliveries(d);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[]);
 async function saveTemplate(event:FormEvent){event.preventDefault();try{await crmPost('/communications/templates',{code:template.code,channel:template.channel,language:template.language,...template.subject?{subject:template.subject}:{},body:template.body,active:true});setTemplate({code:'',channel:'EMAIL',language:'ar',subject:'',body:''});setNotice('تم حفظ قالب الرسالة.');await load();}catch(e){setNotice(message(e));}}
 async function setPref(event:FormEvent){event.preventDefault();try{await crmPost('/communications/preferences',{userId:preference.userId,channel:preference.channel,enabled:preference.enabled==='true'});setNotice('تم حفظ تفضيل القناة للمستخدم.');}catch(e){setNotice(message(e));}}
 async function send(event:FormEvent){event.preventDefault();try{await crmPost('/communications/queue',{templateCode:queue.templateCode,channel:queue.channel,language:queue.language,recipient:queue.recipient,...queue.userId?{userId:queue.userId}:{},variables:variables(queue.variables),...queue.scheduledAt?{scheduledAt:new Date(queue.scheduledAt).toISOString()}:{}});setQueue({...queue,recipient:'',userId:'',variables:'{}',scheduledAt:''});setNotice('تمت إضافة الرسالة إلى طابور التسليم الموثوق.');await load();}catch(e){setNotice(message(e));}}
 return <section dir="rtl" className="ui-page-stack" aria-label="مركز الاتصالات">
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="مركز الاتصالات"><p>قوالب موحدة ورسائل داخل النظام وبريد وواتساب وSMS مع جدولة وإعادة محاولة وحالة تسليم. الاتصال بالمزود يتم من مركز التكاملات.</p></Card>
  <div className="ui-grid-md">
   <DisclosureCard title="قالب رسالة جديد" description="استخدم {{variable}} داخل النص للحقول التي يجب توفيرها عند الإرسال."><form onSubmit={saveTemplate}><FormField label="كود القالب" required><Input required value={template.code} onChange={e=>setTemplate({...template,code:e.target.value.toUpperCase()})}/></FormField><FormField label="القناة"><Select value={template.channel} onChange={e=>setTemplate({...template,channel:e.target.value as Channel})}>{['IN_APP','EMAIL','WHATSAPP','SMS'].map(v=><option key={v} value={v}>{v}</option>)}</Select></FormField><FormField label="اللغة"><Input required value={template.language} onChange={e=>setTemplate({...template,language:e.target.value})}/></FormField><FormField label="العنوان — اختياري"><Input value={template.subject} onChange={e=>setTemplate({...template,subject:e.target.value})}/></FormField><FormField label="النص" required><Textarea required value={template.body} onChange={e=>setTemplate({...template,body:e.target.value})}/></FormField><Button type="submit">حفظ القالب</Button></form></DisclosureCard>
   <DisclosureCard title="تفضيلات مستخدم" description="تعطيل قناة لمستخدم يمنع إرسال الرسائل الموجهة له عبر هذه القناة."><form onSubmit={setPref}><FormField label="معرّف المستخدم" required><Input required value={preference.userId} onChange={e=>setPreference({...preference,userId:e.target.value})}/></FormField><FormField label="القناة"><Select value={preference.channel} onChange={e=>setPreference({...preference,channel:e.target.value as Channel})}>{['IN_APP','EMAIL','WHATSAPP','SMS'].map(v=><option key={v} value={v}>{v}</option>)}</Select></FormField><FormField label="الحالة"><Select value={preference.enabled} onChange={e=>setPreference({...preference,enabled:e.target.value})}><option value="true">مسموح</option><option value="false">متوقف</option></Select></FormField><Button type="submit">حفظ التفضيل</Button></form></DisclosureCard>
  </div>
  <Card title="القوالب">{!templates.length?<EmptyState title="لا توجد قوالب"/>:<DataGrid columns={['الكود','القناة','اللغة','العنوان','الحالة']}>{templates.map(t=><tr key={t.id}><td>{t.code}</td><td>{t.channel}</td><td>{t.language}</td><td>{t.subject??'—'}</td><td>{t.active?'نشط':'متوقف'}</td></tr>)}</DataGrid>}</Card>
  <DisclosureCard title="إرسال / جدولة رسالة" description="يتم التحقق من كل متغيرات القالب قبل دخول الرسالة إلى الطابور."><form onSubmit={send}><FormField label="القالب" required><Select required value={queue.templateCode} onChange={e=>{const t=templates.find(x=>x.code===e.target.value);setQueue({...queue,templateCode:e.target.value,...t?{channel:t.channel,language:t.language}:{}})}}><option value="">اختر القالب</option>{templates.filter(t=>t.active).map(t=><option key={t.id} value={t.code}>{t.code} — {t.channel}</option>)}</Select></FormField><FormField label="القناة"><Select value={queue.channel} onChange={e=>setQueue({...queue,channel:e.target.value as Channel})}>{['IN_APP','EMAIL','WHATSAPP','SMS'].map(v=><option key={v} value={v}>{v}</option>)}</Select></FormField><FormField label="المستلم" required><Input required value={queue.recipient} onChange={e=>setQueue({...queue,recipient:e.target.value})}/></FormField><FormField label="معرّف المستخدم — للرسائل المرتبطة بمستخدم"><Input value={queue.userId} onChange={e=>setQueue({...queue,userId:e.target.value})}/></FormField><FormField label="المتغيرات JSON"><Textarea value={queue.variables} onChange={e=>setQueue({...queue,variables:e.target.value})}/></FormField><FormField label="موعد الإرسال — اختياري"><Input type="datetime-local" value={queue.scheduledAt} onChange={e=>setQueue({...queue,scheduledAt:e.target.value})}/></FormField><Button type="submit">إضافة للطابور</Button></form></DisclosureCard>
  <Card title="سجل التسليم">{!deliveries.length?<EmptyState title="لا توجد رسائل بعد"/>:<DataGrid columns={['القناة','المستلم','العنوان','الحالة','المحاولة','الموعد','الخطأ']}>{deliveries.map(d=><tr key={d.id}><td>{d.channel}</td><td>{d.recipient}</td><td>{d.subject??'—'}</td><td><Badge tone={d.status==='SENT'?'success':d.status==='DEAD_LETTER'?'warning':'info'}>{d.status}</Badge></td><td>{d.attempt}/{d.maxAttempts}</td><td>{new Date(d.scheduledAt).toLocaleString('ar-EG')}</td><td>{d.lastError??'—'}</td></tr>)}</DataGrid>}</Card>
 </section>;
}
