import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, LoadingState, MetricCard, Select, Tabs, Textarea } from './ui.js';
import { crmDelete, crmGet, crmPatch, crmPost } from './crm-core-client.js';
import { accountingApi, type TreasuryRow } from './accounting-client.js';
import { advancedAccountingApi } from './advanced-accounting-client.js';

type Party={id:string;displayName:string;phone:string|null;email:string|null;whatsappNumber:string|null};
type Agent={id:string;number:string;status:'ACTIVE'|'SUSPENDED';notes:string|null;commission:{kind:'FIXED'|'PERCENT';value:string;currency:string|null}};
type AgentView={agent:Agent;party:Party};
type AgentWorkspaceView=AgentView&{commissionSummaryByCurrency:Array<{currency:string;amount:string;paid:string;outstanding:string}>;pendingCommissionCount:number;hasPendingCommission:boolean};
type CustomerView={customer:{id:string;number:string;status:string};party:Party};
type Lead={id:string;number:string;displayName:string;source:string;status:string};
type Quote={id:string;number:string;status:string;currency:string;customerSnapshot:{displayName:string};currentRevisionId:string;acceptedRevisionId:string|null;revisions:Array<{id:string;total:string}>};
type CommissionPosition={id:string;agentPartyId:string;sourceType:string;sourceId:string;currency:string;amount:string;paid:string;outstanding:string;status:'DRAFT'|'APPROVED'|'PARTIALLY_PAID'|'PAID'|'REVERSED'};
type Agent360={agent:AgentView;customers:CustomerView[];leads:Lead[];quotations:Quote[];commissionPositions:CommissionPosition[];commissionSummaryByCurrency:Array<{currency:string;amount:string;paid:string;outstanding:string}>;pendingCommissionPositions:CommissionPosition[]};
const msg=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const today=()=>new Date().toISOString().slice(0,10);
const queryParam=(name:string)=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}
function quoteTotal(q:Quote){const revision=q.revisions.find(item=>item.id===(q.acceptedRevisionId??q.currentRevisionId));return revision?.total??'0';}
function commissionText(value:AgentWorkspaceView|undefined){if(!value?.commissionSummaryByCurrency.length)return '—';const text=value.commissionSummaryByCurrency.filter(item=>item.outstanding!=='0').map(item=>`${item.outstanding} ${item.currency}`).join(' | ');return text||'لا توجد مستحقات';}

export function AgentsPage(){
 const[q,setQ]=useState(''),[status,setStatus]=useState(''),[rows,setRows]=useState<AgentView[]>([]),[financial,setFinancial]=useState<AgentWorkspaceView[]>([]),[error,setError]=useState(''),[financeError,setFinanceError]=useState(''),[editing,setEditing]=useState<AgentView|null>(null),[name,setName]=useState(''),[phone,setPhone]=useState(''),[wa,setWa]=useState(''),[email,setEmail]=useState(''),[notes,setNotes]=useState(''),[kind,setKind]=useState<'PERCENT'|'FIXED'>('PERCENT'),[value,setValue]=useState(''),[currency,setCurrency]=useState('EGP'),[notice,setNotice]=useState('');
 const path=useMemo(()=>`/crm/agents?${new URLSearchParams({...status&&{status},...q&&{q}})}`,[q,status]);
 async function load(){try{setRows(await crmGet<AgentView[]>(path));setError('');}catch(error){setError(msg(error));}try{setFinancial(await crmGet<AgentWorkspaceView[]>('/crm/insights/agents'));setFinanceError('');}catch(error){setFinancial([]);setFinanceError(msg(error));}}
 useEffect(()=>{void load();},[path]);
 const financeMap=useMemo(()=>new Map(financial.map(item=>[item.agent.id,item])),[financial]);
 const totals=useMemo(()=>({total:rows.length,active:rows.filter(item=>item.agent.status==='ACTIVE').length,suspended:rows.filter(item=>item.agent.status==='SUSPENDED').length,pending:financial.filter(item=>item.hasPendingCommission).length}),[rows,financial]);
 function reset(){setEditing(null);setName('');setPhone('');setWa('');setEmail('');setNotes('');setKind('PERCENT');setValue('');setCurrency('EGP');}
 function edit(item:AgentView){setEditing(item);setName(item.party.displayName);setPhone(item.party.phone??'');setWa(item.party.whatsappNumber??'');setEmail(item.party.email??'');setNotes(item.agent.notes??'');setKind(item.agent.commission.kind);setValue(item.agent.commission.value);setCurrency(item.agent.commission.currency??'EGP');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(event:FormEvent){event.preventDefault();try{const body={party:{kind:'PERSON',displayName:name,...phone&&{phone},...wa&&{whatsappNumber:wa},...email&&{email}},notes,commission:{kind,value,currency:kind==='FIXED'?currency:null}};if(editing)await crmPatch(`/crm/agents/${editing.agent.id}`,body);else await crmPost('/crm/agents',body);setNotice(editing?'تم تحديث بيانات المندوب.':'تم إنشاء المندوب.');reset();await load();}catch(error){setNotice(msg(error));}}
 async function lifecycle(id:string,action:'suspend'|'reactivate'){try{await crmPost(`/crm/agents/${id}/${action}`,{});await load();}catch(error){setNotice(msg(error));}}
 async function remove(id:string){if(!window.confirm('الحذف الآمن متاح فقط للمندوب المعلّق وغير المرتبط بأي عمليات. متابعة؟'))return;try{await crmDelete(`/crm/agents/${id}`);setNotice('تم الحذف الآمن للمندوب.');await load();}catch(error){setNotice(msg(error));}}
 return <section aria-label="إدارة المندوبين" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="إجمالي المندوبين" value={totals.total}/><MetricCard label="نشط" value={totals.active} tone="success"/><MetricCard label="لهم عمولات مستحقة" value={totals.pending} tone={totals.pending?'warning':'neutral'}/><MetricCard label="موقوف / معلّق" value={totals.suspended} tone={totals.suspended?'warning':'neutral'}/></div>
  <Card title="المندوبون"><div className="ui-filter-row"><Input placeholder="بحث بالاسم أو الهاتف أو الرقم" value={q} onChange={event=>setQ(event.target.value)}/><Select value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل الحالات</option><option value="ACTIVE">نشط</option><option value="SUSPENDED">معلّق</option></Select></div>{financeError?<small>بيانات المندوبين متاحة، لكن عرض العمولات يحتاج صلاحية القراءة المالية.</small>:null}</Card>
  <DisclosureCard title={editing?'تعديل المندوب':'إضافة مندوب'} description="الهوية في Party Registry وشروط العمولة الافتراضية في ملف المندوب؛ المطالبات المالية تبقى لدى محاسبة العمولات." open={Boolean(editing)}><form onSubmit={save}><FormField label="الاسم" required><Input required value={name} onChange={event=>setName(event.target.value)}/></FormField><FormField label="الهاتف"><Input value={phone} onChange={event=>setPhone(event.target.value)}/></FormField><FormField label="واتساب"><Input value={wa} onChange={event=>setWa(event.target.value)}/></FormField><FormField label="البريد الإلكتروني"><Input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></FormField><FormField label="نوع العمولة الافتراضية"><Select value={kind} onChange={event=>setKind(event.target.value as 'PERCENT'|'FIXED')}><option value="PERCENT">نسبة %</option><option value="FIXED">مبلغ ثابت</option></Select></FormField><FormField label="القيمة" required><Input required inputMode="decimal" value={value} onChange={event=>setValue(event.target.value)}/></FormField>{kind==='FIXED'?<FormField label="العملة"><Input value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField>:null}<FormField label="ملاحظات"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></FormField><Button type="submit">{editing?'حفظ التعديل':'حفظ المندوب'}</Button>{editing?<Button type="button" onClick={reset}>إلغاء</Button>:null}</form>{notice?<p role="status">{notice}</p>:null}</DisclosureCard>
  <Card title="قائمة المندوبين">{error?<ErrorState message={error}/>:!rows.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','الهاتف','العمولة الافتراضية','المستحق فعليًا','الحالة','الإجراءات']}>{rows.map(item=>{const f=financeMap.get(item.agent.id);return <tr key={item.agent.id}><td>{item.agent.number}</td><td>{item.party.displayName}</td><td>{item.party.phone??'—'}</td><td>{item.agent.commission.kind==='PERCENT'?`${item.agent.commission.value}%`:`${item.agent.commission.value} ${item.agent.commission.currency??''}`}</td><td>{commissionText(f)}{f?.pendingCommissionCount?<><br/><Badge tone="warning">{f.pendingCommissionCount} مطالبة</Badge></>:null}</td><td><Badge tone={item.agent.status==='ACTIVE'?'success':'warning'}>{item.agent.status==='ACTIVE'?'نشط':'معلّق'}</Badge></td><td><details><summary>الإجراءات</summary><div><Button onClick={()=>window.location.href=`/crm/agent-360?agentId=${encodeURIComponent(item.agent.id)}#commissions`}>العمولات المستحقة</Button><Button disabled title="يتطلب إكمال دعم Agent receivable داخل Billing قبل التفعيل">سند قبض من المندوب</Button><Button disabled title="يتطلب إكمال دعم Agent receivable داخل Billing قبل التفعيل">فاتورة على المندوب</Button><Button disabled title="يتطلب إكمال دعم Agent advance داخل Billing قبل التفعيل">رد مقدم</Button></div></details><details><summary>المزيد</summary><div><Button onClick={()=>window.location.href=`/crm/agent-360?agentId=${encodeURIComponent(item.agent.id)}`}>ملف 360°</Button><Button onClick={()=>edit(item)}>تعديل</Button><Button onClick={()=>whatsapp(item.party.whatsappNumber??item.party.phone)} disabled={!item.party.whatsappNumber&&!item.party.phone}>واتساب</Button>{item.agent.status==='ACTIVE'?<Button onClick={()=>void lifecycle(item.agent.id,'suspend')}>تعليق</Button>:<><Button onClick={()=>void lifecycle(item.agent.id,'reactivate')}>إعادة تنشيط</Button><Button onClick={()=>void remove(item.agent.id)}>حذف آمن</Button></>}</div></details></td></tr>})}</DataGrid>}</Card>
 </section>;
}

const tabs=[{id:'summary',label:'الملخص'},{id:'customers',label:'العملاء'},{id:'pipeline',label:'المبيعات والمتابعة'},{id:'commissions',label:'العمولات المالية'}];
export function Agent360Page(){
 const[id,setId]=useState(()=>queryParam('agentId')),[data,setData]=useState<Agent360|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tab,setTab]=useState(()=>typeof window!=='undefined'&&window.location.hash==='#commissions'?'commissions':'summary'),[treasuries,setTreasuries]=useState<TreasuryRow[]>([]),[notice,setNotice]=useState(''),[paying,setPaying]=useState<CommissionPosition|null>(null),[payment,setPayment]=useState({treasuryId:'',amount:'',paymentCurrency:'EGP',postingDate:today(),number:''});
 async function load(){if(!id.trim())return;setLoading(true);try{const[next,accounting]=await Promise.all([crmGet<Agent360>(`/crm/insights/agents/${encodeURIComponent(id.trim())}`),accountingApi.overview()]);setData(next);setTreasuries(accounting.treasuries.filter(item=>item.active));setError('');}catch(error){setError(msg(error));setData(null);}finally{setLoading(false);}}
 useEffect(()=>{if(id)void load();},[]);
 function beginPay(position:CommissionPosition){setPaying(position);setPayment({treasuryId:'',amount:position.outstanding,paymentCurrency:position.currency,postingDate:today(),number:`COM-${Date.now()}`});}
 async function pay(event:FormEvent){event.preventDefault();if(!paying)return;try{await advancedAccountingApi.payCommission(paying.id,payment);setNotice('تم سداد العمولة من خلال مالك محاسبة العمولات.');setPaying(null);await load();}catch(error){setNotice(msg(error));}}
 return <section aria-label="ملف المندوب 360 درجة" className="ui-page-stack"><Card title="ملف المندوب 360°"><FormField label="معرّف المندوب"><Input value={id} onChange={event=>setId(event.target.value)}/></FormField><Button onClick={()=>void load()}>عرض الملف</Button></Card>{loading?<LoadingState label="جارٍ تحميل ملف المندوب…"/>:null}{error?<ErrorState message={error}/>:null}{notice?<p role="status">{notice}</p>:null}{data?<><Card title={`${data.agent.agent.number} — ${data.agent.party.displayName}`}><p>الحالة: <Badge tone={data.agent.agent.status==='ACTIVE'?'success':'warning'}>{data.agent.agent.status==='ACTIVE'?'نشط':'معلّق'}</Badge></p><p>الهاتف: {data.agent.party.phone??'—'} | البريد: {data.agent.party.email??'—'}</p><p>الشروط التجارية الافتراضية: {data.agent.agent.commission.kind==='PERCENT'?`${data.agent.agent.commission.value}%`:`${data.agent.agent.commission.value} ${data.agent.agent.commission.currency??''}`}</p><Button onClick={()=>whatsapp(data.agent.party.whatsappNumber??data.agent.party.phone)} disabled={!data.agent.party.whatsappNumber&&!data.agent.party.phone}>واتساب</Button></Card><div className="ui-metric-grid"><MetricCard label="العملاء المسندون" value={data.customers.length}/><MetricCard label="عملاء محتملون محالون" value={data.leads.length}/><MetricCard label="عروض مرتبطة" value={data.quotations.length}/><MetricCard label="عمولات مستحقة" value={data.pendingCommissionPositions.length} tone={data.pendingCommissionPositions.length?'warning':'neutral'}/></div><Tabs tabs={tabs} active={tab} onChange={setTab}/>
 {tab==='summary'?<div className="ui-grid-md"><Card title="بيانات الاتصال"><p>{data.agent.party.phone??'—'}</p><p>{data.agent.party.email??'—'}</p></Card><Card title="ملاحظات"><p>{data.agent.agent.notes??'—'}</p></Card></div>:null}
 {tab==='customers'?<Card title="العملاء المسندون">{!data.customers.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','الهاتف','الحالة','الملف']}>{data.customers.map(customer=><tr key={customer.customer.id}><td>{customer.customer.number}</td><td>{customer.party.displayName}</td><td>{customer.party.phone??'—'}</td><td>{customer.customer.status}</td><td><Button onClick={()=>window.location.href=`/crm/customer-360?customerId=${encodeURIComponent(customer.customer.id)}`}>360°</Button></td></tr>)}</DataGrid>}</Card>:null}
 {tab==='pipeline'?<><Card title="العملاء المحتملون المحالون">{!data.leads.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','المصدر','المرحلة']}>{data.leads.map(lead=><tr key={lead.id}><td>{lead.number}</td><td>{lead.displayName}</td><td>{lead.source}</td><td>{lead.status}</td></tr>)}</DataGrid>}</Card><Card title="عروض الأسعار المرتبطة">{!data.quotations.length?<EmptyState/>:<DataGrid columns={['الرقم','العميل','الحالة','القيمة']}>{data.quotations.map(quote=><tr key={quote.id}><td>{quote.number}</td><td>{quote.customerSnapshot.displayName}</td><td>{quote.status}</td><td>{quoteTotal(quote)} {quote.currency}</td></tr>)}</DataGrid>}</Card></>:null}
 {tab==='commissions'?<><Card title="ملخص العمولات حسب العملة">{!data.commissionSummaryByCurrency.length?<EmptyState/>:<DataGrid columns={['العملة','إجمالي المطالبات','المدفوع','المتبقي']}>{data.commissionSummaryByCurrency.map(item=><tr key={item.currency}><td>{item.currency}</td><td>{item.amount}</td><td>{item.paid}</td><td>{item.outstanding}</td></tr>)}</DataGrid>}</Card><Card title="مطالبات العمولات">{!data.commissionPositions.length?<EmptyState/>:<DataGrid columns={['المطالبة','المصدر','العملة','القيمة','المدفوع','المتبقي','الحالة','إجراء']}>{data.commissionPositions.map(position=><tr key={position.id}><td>{position.id}</td><td>{position.sourceType} / {position.sourceId}</td><td>{position.currency}</td><td>{position.amount}</td><td>{position.paid}</td><td>{position.outstanding}</td><td><Badge tone={position.status==='PAID'?'success':position.status==='REVERSED'?'warning':'info'}>{position.status}</Badge></td><td>{['APPROVED','PARTIALLY_PAID'].includes(position.status)&&position.outstanding!=='0'?<Button onClick={()=>beginPay(position)}>سداد عمولة</Button>:'—'}</td></tr>)}</DataGrid>}</Card></>:null}
 {paying?<Card title={`سداد العمولة ${paying.id}`}><form onSubmit={pay}><FormField label="الخزينة" required><Select required value={payment.treasuryId} onChange={event=>{const treasury=treasuries.find(item=>item.id===event.target.value);setPayment({...payment,treasuryId:event.target.value,paymentCurrency:treasury?.currency??payment.paymentCurrency});}}><option value="">اختر الخزينة</option>{treasuries.map(item=><option key={item.id} value={item.id}>{item.code} — {item.name} ({item.currency})</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={payment.amount} onChange={event=>setPayment({...payment,amount:event.target.value})}/></FormField><FormField label="عملة السداد"><Input required value={payment.paymentCurrency} onChange={event=>setPayment({...payment,paymentCurrency:event.target.value.toUpperCase()})}/></FormField><FormField label="تاريخ السداد"><Input required type="date" value={payment.postingDate} onChange={event=>setPayment({...payment,postingDate:event.target.value})}/></FormField><FormField label="رقم المستند"><Input required value={payment.number} onChange={event=>setPayment({...payment,number:event.target.value})}/></FormField><Button type="submit">تأكيد السداد</Button><Button type="button" onClick={()=>setPaying(null)}>إلغاء</Button></form></Card>:null}
 </>:null}</section>;
}
