import { useEffect, useMemo, useState } from 'react';
import { ActionBar, Badge, Button, Card, DataGrid, EmptyState, ErrorState, FormField, Input, LoadingState, MetricCard, Tabs } from './ui.js';
import { crmGet } from './crm-core-client.js';

type Party={id:string;kind:'PERSON'|'ORGANIZATION';displayName:string;legalName:string|null;phone:string|null;email:string|null;whatsappNumber:string|null;address:string|null;nationalIdentity:string|null;taxIdentity:string|null};
type CustomerView={customer:{id:string;number:string;status:string;assignedAgentId:string|null;commercialNotes:string|null};party:Party};
type Lead={id:string;number:string;displayName:string;phone:string|null;source:string;requestedService:string|null;expectedValue:string|null;currency:string|null;status:string;lostReason:string|null};
type Followup={id:string;leadId:string;interactionType:string;scheduledAt:string;status:string;outcome:string|null;nextAction:string|null};
type Quote={id:string;number:string;status:string;approvalStatus:string;currency:string;customerId:string|null;sourceLeadId:string|null;customerSnapshot:{displayName:string};currentRevisionId:string;acceptedRevisionId:string|null;billingInvoiceId:string|null;revisions:Array<{id:string;validityDate:string;total:string}>};
type Traveler={id:string;fullName:string;dateOfBirth:string|null;gender:string|null;nationality:string|null;customerId:string|null;status:'ACTIVE'|'ARCHIVED'};
type QuotationPosition={invoiceId:string;currency:string;documentTotal:string;outstanding:string;status:string};
type FinancialPosition={invoiceId:string;number:string;postingDate:string;dueDate:string|null;currency:string;documentTotal:string;outstanding:string;status:string;overdue:boolean;sourceType:string;sourceId:string};
type FinancialSummary={currency:string;documentTotal:string;outstanding:string};
type Customer360={customer:CustomerView;leads:Lead[];followups:Followup[];quotations:Quote[];travelers:Traveler[];financialPositions:FinancialPosition[];financialSummaryByCurrency:FinancialSummary[];overdueFinancialPositions:FinancialPosition[];quotationLinkedFinancialPositions:QuotationPosition[];quotationLinkedFinancialSummaryByCurrency:FinancialSummary[]};

const customerTabs=[{id:'summary',label:'الملخص'},{id:'finance',label:'المالية'},{id:'operations',label:'العمليات'},{id:'activity',label:'المرفقات والنشاط'},{id:'statement',label:'الحساب الشامل'}];
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
function queryParam(name:string){return typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';}
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}
function quoteTotal(quote:Quote){const revision=quote.revisions.find(item=>item.id===(quote.acceptedRevisionId??quote.currentRevisionId));return revision?.total??'0';}

export function Customer360Page(){
 const[id,setId]=useState(()=>queryParam('customerId')),[data,setData]=useState<Customer360|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tab,setTab]=useState(()=>typeof window!=='undefined'&&window.location.hash==='#attachments'?'activity':'summary');
 async function load(){if(!id.trim())return;setLoading(true);try{setData(await crmGet<Customer360>(`/crm/insights/customers/${encodeURIComponent(id.trim())}`));setError('');}catch(error){setError(errorMessage(error));setData(null);}finally{setLoading(false);}}
 useEffect(()=>{if(id)void load();},[]);
 const outstandingCurrencies=useMemo(()=>data?.financialSummaryByCurrency.filter(item=>item.outstanding!=='0').length??0,[data]);
 return <section aria-label="ملف العميل 360 درجة" className="ui-dashboard">
  <Card title="ملف العميل 360°"><div className="ui-filter-row"><FormField label="معرّف العميل"><Input value={id} onChange={event=>setId(event.target.value)}/></FormField><Button onClick={()=>void load()}>عرض الملف الموحد</Button></div></Card>
  {loading?<LoadingState label="جارٍ تحميل ملف العميل…"/>:null}{error?<ErrorState message={error}/>:null}
  {data?<>
   <Card title={`${data.customer.customer.number} — ${data.customer.party.displayName}`}><section className="ui-dashboard-grid"><div><strong>{data.customer.party.kind==='ORGANIZATION'?'شركة / جهة':'فرد'}</strong><p>{data.customer.party.legalName??''}</p><p><Badge tone={data.customer.customer.status==='ACTIVE'?'success':'warning'}>{data.customer.customer.status==='ACTIVE'?'نشط':'معلّق'}</Badge></p></div><div><p><strong>الهاتف:</strong> {data.customer.party.phone??'—'}</p><p><strong>البريد:</strong> {data.customer.party.email??'—'}</p></div></section><ActionBar><Button variant="secondary" onClick={()=>window.location.href=`/crm/customers?q=${encodeURIComponent(data.customer.customer.number)}`}>العودة للعملاء</Button><Button variant="secondary" onClick={()=>whatsapp(data.customer.party.whatsappNumber??data.customer.party.phone)} disabled={!data.customer.party.whatsappNumber&&!data.customer.party.phone}>واتساب</Button><Button onClick={()=>window.location.href=`/crm/quotations?customerId=${encodeURIComponent(data.customer.customer.id)}`}>عرض سعر جديد</Button><Button onClick={()=>window.location.href=`/tourism/services?customerPartyId=${encodeURIComponent(data.customer.party.id)}`}>خدمة جديدة</Button></ActionBar></Card>
   <div className="ui-metric-grid"><MetricCard label="العملاء المحتملون المرتبطون" value={data.leads.length}/><MetricCard label="المتابعات" value={data.followups.length}/><MetricCard label="عروض الأسعار" value={data.quotations.length}/><MetricCard label="المسافرون" value={data.travelers.length}/><MetricCard label="عملات بها رصيد مفتوح" value={outstandingCurrencies} tone={outstandingCurrencies?'warning':'neutral'}/><MetricCard label="استحقاقات متأخرة" value={data.overdueFinancialPositions.length} tone={data.overdueFinancialPositions.length?'warning':'neutral'}/></div>
   <Tabs tabs={customerTabs} active={tab} onChange={setTab}/>
   {tab==='summary'?<section className="ui-dashboard-grid"><Card title="بيانات الاتصال والهوية"><p><strong>واتساب:</strong> {data.customer.party.whatsappNumber??'—'}</p><p><strong>العنوان:</strong> {data.customer.party.address??'—'}</p><p><strong>الهوية:</strong> {data.customer.party.nationalIdentity??'—'}</p><p><strong>الرقم الضريبي:</strong> {data.customer.party.taxIdentity??'—'}</p></Card><Card title="البيانات التجارية"><p><strong>المندوب المسؤول:</strong> {data.customer.customer.assignedAgentId??'—'}</p><p><strong>ملاحظات:</strong> {data.customer.customer.commercialNotes??'—'}</p></Card></section>:null}
   {tab==='finance'?<section className="ui-dashboard-grid"><Card title="المركز المالي الكامل من Billing"><p><small>CRM يعرض الحقيقة المالية المملوكة لـ Billing فقط ولا يحتفظ بأي رصيد مستقل.</small></p>{!data.financialSummaryByCurrency.length?<EmptyState title="لا توجد حركة مالية للعميل"/>:<DataGrid columns={['العملة','إجمالي المستندات','المتبقي']}>{data.financialSummaryByCurrency.map(item=><tr key={item.currency}><td>{item.currency}</td><td>{item.documentTotal}</td><td><strong>{item.outstanding}</strong></td></tr>)}</DataGrid>}</Card><Card title="استحقاقات متأخرة">{!data.overdueFinancialPositions.length?<EmptyState title="لا توجد استحقاقات متأخرة"/>:<DataGrid columns={['الفاتورة','تاريخ القيد','الاستحقاق','العملة','المتبقي']}>{data.overdueFinancialPositions.map(item=><tr key={item.invoiceId}><td>{item.number}</td><td>{item.postingDate}</td><td>{item.dueDate??'—'}</td><td>{item.currency}</td><td><strong>{item.outstanding}</strong></td></tr>)}</DataGrid>}</Card><Card title="فواتير ناشئة من عروض الأسعار">{!data.quotationLinkedFinancialPositions.length?<EmptyState/>:<DataGrid columns={['الفاتورة','العملة','الإجمالي','المتبقي','الحالة']}>{data.quotationLinkedFinancialPositions.map(item=><tr key={item.invoiceId}><td>{item.invoiceId}</td><td>{item.currency}</td><td>{item.documentTotal}</td><td>{item.outstanding}</td><td>{item.status}</td></tr>)}</DataGrid>}</Card></section>:null}
   {tab==='operations'?<section className="ui-dashboard-grid"><Card title="عروض الأسعار">{!data.quotations.length?<EmptyState/>:<DataGrid columns={['الرقم','الحالة','العملة','القيمة','الفاتورة']}>{data.quotations.map(quote=><tr key={quote.id}><td><strong>{quote.number}</strong></td><td>{quote.status}</td><td>{quote.currency}</td><td>{quoteTotal(quote)}</td><td>{quote.billingInvoiceId??'—'}</td></tr>)}</DataGrid>}</Card><Card title="المسافرون المرتبطون">{!data.travelers.length?<EmptyState/>:<DataGrid columns={['الاسم','الجنسية','تاريخ الميلاد','النوع','الحالة']}>{data.travelers.map(traveler=><tr key={traveler.id}><td><strong>{traveler.fullName}</strong></td><td>{traveler.nationality??'—'}</td><td>{traveler.dateOfBirth??'—'}</td><td>{traveler.gender??'—'}</td><td>{traveler.status}</td></tr>)}</DataGrid>}</Card></section>:null}
   {tab==='activity'?<section className="ui-dashboard-grid"><Card title="المرفقات والنشاط"><p>ملف العميل يجمع النشاط من مصادره الأصلية. المرفقات تظهر من مالك المستندات دون نسخها إلى CRM.</p><ActionBar><Button variant="secondary" onClick={()=>window.location.href=`/crm/customer-documents?customerId=${encodeURIComponent(data.customer.customer.id)}`}>فتح المستندات</Button></ActionBar></Card><Card title="العملاء المحتملون المرتبطون">{!data.leads.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','المصدر','الخدمة','المرحلة']}>{data.leads.map(lead=><tr key={lead.id}><td>{lead.number}</td><td>{lead.displayName}</td><td>{lead.source}</td><td>{lead.requestedService??'—'}</td><td>{lead.status}</td></tr>)}</DataGrid>}</Card><Card title="المتابعات">{!data.followups.length?<EmptyState/>:<DataGrid columns={['النوع','الموعد','الحالة','النتيجة','الإجراء التالي']}>{data.followups.map(followup=><tr key={followup.id}><td>{followup.interactionType}</td><td>{new Date(followup.scheduledAt).toLocaleString('ar-EG')}</td><td>{followup.status}</td><td>{followup.outcome??'—'}</td><td>{followup.nextAction??'—'}</td></tr>)}</DataGrid>}</Card></section>:null}
   {tab==='statement'?<Card title="الحساب الشامل"><p><small>كل المراكز أدناه تأتي من Billing وتُعرض حسب العملة دون جمع عملات مختلفة.</small></p>{!data.financialPositions.length?<EmptyState title="لا توجد مستندات مالية"/>:<DataGrid columns={['الفاتورة','تاريخ القيد','الاستحقاق','العملة','الإجمالي','المتبقي','الحالة','المصدر']}>{data.financialPositions.map(item=><tr key={item.invoiceId}><td>{item.number}</td><td>{item.postingDate}</td><td>{item.dueDate??'—'}</td><td>{item.currency}</td><td>{item.documentTotal}</td><td><strong>{item.outstanding}</strong></td><td>{item.overdue?'متأخر':item.status}</td><td>{item.sourceType}</td></tr>)}</DataGrid>}</Card>:null}
  </>:null}
 </section>;
}
