import {type FormEvent,useEffect,useMemo,useState} from 'react';
import {ActionBar,Badge,Button,Card,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select} from './ui.js';
import {accountingApi,type AccountingOverview} from './accounting-client.js';
import {crmFinancialApi,type CrmFinancialPartyKind,type CrmFinancialState} from './crm-financial-client.js';

const queryParam=(name:string)=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';
const today=()=>new Date().toISOString().slice(0,10);
const msg=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية المالية.';
const newKey=()=>crypto.randomUUID();
export function CrmFinancialActionPage(){
 const action=queryParam('action') as'invoice'|'receipt'|'advance-refund',rawKind=queryParam('partyKind'),partyKind:CrmFinancialPartyKind=rawKind==='AGENT'?'AGENT':'CUSTOMER',partyId=queryParam('partyId'),partyLabel=partyKind==='AGENT'?'المندوب':'العميل';
 const[data,setData]=useState<AccountingOverview|null>(null),[finance,setFinance]=useState<CrmFinancialState|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[commandKey,setCommandKey]=useState(newKey);
 const[number,setNumber]=useState(''),[postingDate,setPostingDate]=useState(today()),[dueDate,setDueDate]=useState(today()),[currency,setCurrency]=useState('EGP'),[controlAccountId,setControlAccountId]=useState(''),[revenueAccountId,setRevenueAccountId]=useState(''),[amount,setAmount]=useState(''),[taxCode,setTaxCode]=useState('');
 const[invoiceId,setInvoiceId]=useState(''),[advanceId,setAdvanceId]=useState(''),[treasuryId,setTreasuryId]=useState(''),[advanceAccountId,setAdvanceAccountId]=useState(''),[approvalRequestId,setApprovalRequestId]=useState(''),[approvalStatus,setApprovalStatus]=useState('');
 async function load(){if(!partyId){setError(`لم يتم تحديد طرف ${partyLabel}.`);setLoading(false);return;}setLoading(true);try{const[overview,state]=await Promise.all([accountingApi.overview(),crmFinancialApi.state(partyKind,partyId)]);setData(overview);setFinance(state);setCurrency(state.baseCurrency);setError('');}catch(value){setError(msg(value));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const selectedInvoice=finance?.invoices.find(invoice=>invoice.id===invoiceId),selectedAdvance=finance?.advances.find(advance=>advance.id===advanceId);
 const assetAccounts=data?.accounts.filter(account=>account.active&&account.postable&&account.classification==='ASSET')??[],liabilityAccounts=data?.accounts.filter(account=>account.active&&account.postable&&account.classification==='LIABILITY')??[],revenueAccounts=data?.accounts.filter(account=>account.active&&account.postable&&account.classification==='REVENUE')??[],treasuries=data?.treasuries.filter(treasury=>treasury.active)??[];
 const matchingTreasuries=useMemo(()=>treasuries.filter(treasury=>(partyKind==='AGENT'||action==='advance-refund')?treasury.currency===finance?.baseCurrency:!selectedInvoice||treasury.currency===selectedInvoice.currency),[treasuries,partyKind,action,finance?.baseCurrency,selectedInvoice]);
 function succeeded(text:string){setNotice(text);setAmount('');setNumber('');setInvoiceId('');setAdvanceId('');setApprovalRequestId('');setApprovalStatus('');setCommandKey(newKey());void load();}
 async function createInvoice(event:FormEvent){event.preventDefault();try{if(partyKind==='CUSTOMER'){const result=await accountingApi.createInvoice({commandKey,type:'CUSTOMER',partyId,number,postingDate,dueDate,currency,controlAccountId,lines:[{accountId:revenueAccountId,amount,...taxCode.trim()?{taxCode:taxCode.trim()}:{}}]});succeeded(`تم إنشاء وترحيل الفاتورة ${result.number}.`);}else{const result=await crmFinancialApi.createInvoice({commandKey,partyKind,partyId,number,postingDate,dueDate,currency,controlAccountId,lines:[{accountId:revenueAccountId,amount,...taxCode.trim()?{taxCode:taxCode.trim()}:{}}]});succeeded(`تم إنشاء وترحيل فاتورة المندوب ${result.number}.`);}}catch(value){setNotice(msg(value));}}
 async function receive(event:FormEvent){event.preventDefault();if(!selectedInvoice)return;try{if(partyKind==='CUSTOMER'){const result=await accountingApi.postSettlement({commandKey,invoiceId:selectedInvoice.id,treasuryId,number,postingDate,amount});succeeded(`تم ترحيل سند القبض ${result.number}.`);}else{const result=await crmFinancialApi.postReceipt({commandKey,partyKind,partyId,invoiceId:selectedInvoice.id,treasuryId,number,postingDate,amount});succeeded(`تم ترحيل سند القبض ${result.voucher.number}.`);}}catch(value){setNotice(msg(value));}}
 async function requestApproval(){if(!amount.trim())return setNotice('أدخل مبلغ الرد أولًا.');try{const result=await crmFinancialApi.requestRefundApproval({commandKey,partyKind,amount});setApprovalStatus(result.status);if(result.status==='NOT_REQUIRED'){setApprovalRequestId('');setNotice('قيمة رد المقدم لا تحتاج موافقة وفق السياسة الحالية. يمكنك تنفيذ الرد مباشرة.');return;}if(result.request){setApprovalRequestId(result.request.id);}setNotice(result.status==='APPROVED'?'الموافقة معتمدة ويمكن تنفيذ رد المقدم.':result.status==='REJECTED'?'تم رفض طلب الموافقة؛ لا يمكن تنفيذ الرد بهذا الطلب.':`تم إنشاء طلب الموافقة ${result.request?.id??''}. اعتمده من مركز الموافقات ثم اضغط تحديث حالة الموافقة.`);}catch(value){setNotice(msg(value));}}
 async function refund(event:FormEvent){event.preventDefault();if(!selectedAdvance)return;try{const result=await crmFinancialApi.refundAdvance({commandKey,partyKind,partyId,advanceId:selectedAdvance.id,treasuryId,advanceAccountId,number,postingDate,amount,...approvalRequestId.trim()?{approvalRequestId:approvalRequestId.trim()}:{}});succeeded(`تم رد المقدم وترحيل سند الصرف ${result.voucher.number}.`);}catch(value){setNotice(msg(value));}}
 if(loading)return <LoadingState label="جارٍ تحميل بيانات المحاسبة…"/>;if(error)return <ErrorState message={error}/>;if(!data||!finance)return <ErrorState message="تعذر تحميل البيانات المالية."/>;
 const actionLabel=action==='invoice'?(partyKind==='AGENT'?'فاتورة على المندوب':'فاتورة مبيعات'):action==='receipt'?`سند قبض من ${partyLabel}`:`رد مقدم ${partyLabel}`;
 return <section className="ui-dashboard" aria-label={`إجراء مالي لـ${partyLabel}`}>
  <Card title={`إجراء مالي — ${partyLabel}`}><p>تنفيذ مالي مباشر مرتبط بالطرف الحالي مع بقاء الفواتير والمستحقات في Billing، وحركة النقد في Treasury، والموافقات في Financial Controls.</p><ActionBar><Button variant="secondary" onClick={()=>history.back()}>العودة</Button></ActionBar></Card>
  <div className="ui-metric-grid"><MetricCard label="نوع العملية" value={actionLabel}/><MetricCard label="العملة الأساسية" value={finance.baseCurrency}/><MetricCard label="فواتير مفتوحة" value={finance.invoices.length}/><MetricCard label="مقدمات متاحة" value={finance.advances.length}/><MetricCard label="خزائن متاحة" value={matchingTreasuries.length}/></div>
  <section className="ui-dashboard-grid" aria-label="العملية والملخص المالي">
   <Card title={actionLabel}>
    {action==='invoice'?<form onSubmit={createInvoice} className="ui-filter-grid"><FormField label="رقم الفاتورة" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={postingDate} onChange={event=>setPostingDate(event.target.value)}/></FormField><FormField label="تاريخ الاستحقاق" required><Input required type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/></FormField><FormField label="العملة" required><Input required value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField><FormField label="حساب مراقبة المدينين" required><Select required value={controlAccountId} onChange={event=>setControlAccountId(event.target.value)}><option value="">اختر الحساب</option>{assetAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="حساب الإيراد" required><Select required value={revenueAccountId} onChange={event=>setRevenueAccountId(event.target.value)}><option value="">اختر الحساب</option>{revenueAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></FormField><FormField label="كود الضريبة (اختياري)"><Input value={taxCode} onChange={event=>setTaxCode(event.target.value)}/></FormField><ActionBar><Button type="submit">إنشاء وترحيل الفاتورة</Button></ActionBar></form>:null}
    {action==='receipt'?(!finance.invoices.length?<EmptyState title="لا توجد فواتير مفتوحة للتحصيل"/>:<form onSubmit={receive} className="ui-filter-grid"><FormField label="الفاتورة" required><Select required value={invoiceId} onChange={event=>{const id=event.target.value;setInvoiceId(id);const invoice=finance.invoices.find(item=>item.id===id);if(invoice){setAmount(invoice.outstanding);setCurrency(invoice.currency);}}}><option value="">اختر الفاتورة</option>{finance.invoices.map(invoice=><option key={invoice.id} value={invoice.id}>{invoice.number} — متبقي {invoice.outstanding} {invoice.currency}</option>)}</Select></FormField>{selectedInvoice?<p>الرصيد الحالي: <Badge tone="warning">{selectedInvoice.outstanding} {selectedInvoice.currency}</Badge></p>:null}<FormField label="الخزينة" required><Select required value={treasuryId} onChange={event=>setTreasuryId(event.target.value)}><option value="">اختر الخزينة</option>{matchingTreasuries.map(treasury=><option key={treasury.id} value={treasury.id}>{treasury.code} — {treasury.name} ({treasury.currency})</option>)}</Select></FormField><FormField label="رقم السند" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField><FormField label="تاريخ القبض" required><Input required type="date" value={postingDate} onChange={event=>setPostingDate(event.target.value)}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></FormField>{partyKind==='AGENT'&&selectedInvoice?.currency!==finance.baseCurrency?<p role="alert">تحصيل المندوب بعملة أجنبية يتم من شاشة التسوية المحاسبية المتخصصة حتى تتوفر أدلة FX كاملة.</p>:null}<ActionBar><Button type="submit" disabled={partyKind==='AGENT'&&selectedInvoice?.currency!==finance.baseCurrency}>ترحيل سند القبض</Button></ActionBar></form>):null}
    {action==='advance-refund'?(!finance.advances.length?<EmptyState title="لا توجد مقدمات متاحة للرد"/>:<form onSubmit={refund} className="ui-filter-grid"><FormField label="المقدم" required><Select required value={advanceId} onChange={event=>{const id=event.target.value;setAdvanceId(id);const advance=finance.advances.find(item=>item.id===id);if(advance)setAmount(advance.available);setApprovalRequestId('');setApprovalStatus('');}}><option value="">اختر المقدم</option>{finance.advances.map(advance=><option key={advance.id} value={advance.id}>متاح {advance.available} — {advance.sourceType}</option>)}</Select></FormField>{selectedAdvance?<p>المتاح للرد: <Badge tone="warning">{selectedAdvance.available} {finance.baseCurrency}</Badge></p>:null}<FormField label="الخزينة" required><Select required value={treasuryId} onChange={event=>setTreasuryId(event.target.value)}><option value="">اختر خزينة {finance.baseCurrency}</option>{matchingTreasuries.map(treasury=><option key={treasury.id} value={treasury.id}>{treasury.code} — {treasury.name}</option>)}</Select></FormField><FormField label="حساب المقدمات" required><Select required value={advanceAccountId} onChange={event=>setAdvanceAccountId(event.target.value)}><option value="">اختر حساب الالتزام</option>{liabilityAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="رقم سند الصرف" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField><FormField label="تاريخ الرد" required><Input required type="date" value={postingDate} onChange={event=>setPostingDate(event.target.value)}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setApprovalRequestId('');setApprovalStatus('');}}/></FormField><ActionBar><Button type="button" variant="secondary" onClick={()=>void requestApproval()}>{approvalRequestId?'تحديث حالة الموافقة':'فحص / طلب الموافقة'}</Button>{approvalRequestId?<Button type="button" variant="secondary" onClick={()=>window.location.href='/management/approvals'}>فتح مركز الموافقات</Button>:null}</ActionBar>{approvalStatus?<p>حالة الموافقة: <Badge tone={approvalStatus==='APPROVED'||approvalStatus==='NOT_REQUIRED'?'success':approvalStatus==='REJECTED'?'warning':'info'}>{approvalStatus}</Badge>{approvalRequestId?` — ${approvalRequestId}`:''}</p>:null}<ActionBar><Button type="submit" disabled={approvalStatus==='PENDING'||approvalStatus==='REJECTED'}>رد المقدم وترحيل سند الصرف</Button></ActionBar></form>):null}
    {notice?<p role="status">{notice}</p>:null}
   </Card>
   <Card title="ملخص الطرف المالي"><p><strong>معرّف الطرف:</strong> {partyId}</p><p><strong>نوع الطرف:</strong> {partyLabel}</p><p><strong>الفواتير المفتوحة:</strong> {finance.invoices.length}</p><p><strong>المقدمات المتاحة:</strong> {finance.advances.length}</p><p><strong>الخزائن المتوافقة:</strong> {matchingTreasuries.length}</p>{selectedInvoice?<><h3>الفاتورة المختارة</h3><p>{selectedInvoice.number} — متبقي <Badge tone="warning">{selectedInvoice.outstanding} {selectedInvoice.currency}</Badge></p></>:null}{selectedAdvance?<><h3>المقدم المختار</h3><p>المتاح <Badge tone="warning">{selectedAdvance.available} {finance.baseCurrency}</Badge></p></>:null}</Card>
  </section>
 </section>;
}
