import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { ActionBar, Badge, Button, Card, DataGrid, Dialog, DisclosureCard, EmptyState, ErrorState, FormField, Input, MetricCard, Select, Textarea, Toast } from './ui.js';
import { crmGet, crmPatch, crmPost } from './crm-core-client.js';

type PartyKind='PERSON'|'ORGANIZATION';
type LeadStatus='NEW'|'CONTACTED'|'QUALIFIED'|'QUOTED'|'WON'|'LOST';
type Lead={id:string;number:string;partyKind:PartyKind;displayName:string;legalName:string|null;phone:string|null;whatsappNumber:string|null;email:string|null;address:string|null;nationalIdentity:string|null;taxIdentity:string|null;source:string;requestedService:string|null;expectedValue:string|null;currency:string|null;status:LeadStatus;responsibleUserId:string|null;referralAgentId:string|null;notes:string|null;lostReason:string|null;quotationReference:string|null;convertedCustomerId:string|null};
type LeadHistory={id:string;kind:string;fromStatus:LeadStatus|null;toStatus:LeadStatus|null;detail:string|null;occurredAt:string;actorId:string};
type AgentView={agent:{id:string;number:string;status:'ACTIVE'|'SUSPENDED'};party:{displayName:string}};
type UserOption={id:string;displayName:string};
type FollowupStatus='SCHEDULED'|'COMPLETED'|'CANCELLED';
type Followup={id:string;leadId:string;responsibleUserId:string;interactionType:string;scheduledAt:string;status:FollowupStatus;outcome:string|null;nextAction:string|null;previousFollowupId:string|null;completedAt:string|null;cancelledAt:string|null;completionVoidedAt:string|null;completionVoidReason:string|null};
type FollowupHistory={id:string;kind:string;detail:string|null;previousScheduledAt:string|null;scheduledAt:string|null;occurredAt:string;actorId:string};

const leadLabels:Record<LeadStatus,string>={NEW:'جديد',CONTACTED:'تم التواصل',QUALIFIED:'مؤهل',QUOTED:'تم عرض السعر',WON:'ناجح',LOST:'مفقود'};
const leadStages=Object.keys(leadLabels) as LeadStatus[];
const interactionLabels:Record<string,string>={CALL:'مكالمة',WHATSAPP:'واتساب',MEETING:'اجتماع',EMAIL:'بريد إلكتروني',OTHER:'أخرى'};
const followupLabels:Record<FollowupStatus,string>={SCHEDULED:'مجدولة',COMPLETED:'مكتملة',CANCELLED:'ملغاة'};
const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const tone=(status:string)=>status==='WON'||status==='COMPLETED'?'success' as const:status==='LOST'||status==='CANCELLED'?'warning' as const:'info' as const;
const userLabel=(value:UserOption)=>value.displayName;
const toLocalInput=(date:Date)=>{const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16);};
const defaultThrough=()=>toLocalInput(new Date(Date.now()+7*24*60*60*1000));
const toIso=(value:string)=>new Date(value).toISOString();
function go(path:string){window.location.href=path;}
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}

export function LeadsPage(){
 const[q,setQ]=useState(''),[status,setStatus]=useState(''),[responsibleFilter,setResponsibleFilter]=useState(''),[editing,setEditing]=useState<Lead|null>(null),[notice,setNotice]=useState('');
 const[kind,setKind]=useState<PartyKind>('PERSON'),[name,setName]=useState(''),[legalName,setLegalName]=useState(''),[phone,setPhone]=useState(''),[wa,setWa]=useState(''),[email,setEmail]=useState(''),[address,setAddress]=useState(''),[nationalId,setNationalId]=useState(''),[taxId,setTaxId]=useState(''),[source,setSource]=useState(''),[service,setService]=useState(''),[expected,setExpected]=useState(''),[currency,setCurrency]=useState('EGP'),[responsible,setResponsible]=useState(''),[referralAgent,setReferralAgent]=useState(''),[notes,setNotes]=useState('');
 const[losingId,setLosingId]=useState(''),[lostReason,setLostReason]=useState(''),[historyLead,setHistoryLead]=useState<Lead|null>(null),[history,setHistory]=useState<LeadHistory[]>([]);
 const[list,setList]=useState<Lead[]>([]),[all,setAll]=useState<Lead[]>([]),[agents,setAgents]=useState<AgentView[]>([]),[users,setUsers]=useState<UserOption[]>([]),[error,setError]=useState('');
 const listPath=useMemo(()=>`/crm/leads?${new URLSearchParams({...status&&{status},...q&&{q},...responsibleFilter&&{responsibleUserId:responsibleFilter}})}`,[q,status,responsibleFilter]);
 async function load(){try{const[rows,everyAgent,everyUser,total]=await Promise.all([crmGet<Lead[]>(listPath),crmGet<AgentView[]>('/crm/agents?status=ACTIVE'),crmGet<UserOption[]>('/crm/insights/assignees'),crmGet<Lead[]>('/crm/leads')]);setList(rows);setAgents(everyAgent);setUsers(everyUser);setAll(total);setError('');}catch(value){setError(message(value));}}
 useEffect(()=>{void load();},[listPath]);
 const counts=useMemo(()=>Object.fromEntries(leadStages.map(key=>[key,all.filter(item=>item.status===key).length])) as Record<LeadStatus,number>,[all]);
 function reset(){setEditing(null);setKind('PERSON');setName('');setLegalName('');setPhone('');setWa('');setEmail('');setAddress('');setNationalId('');setTaxId('');setSource('');setService('');setExpected('');setCurrency('EGP');setResponsible('');setReferralAgent('');setNotes('');}
 function edit(value:Lead){setEditing(value);setKind(value.partyKind);setName(value.displayName);setLegalName(value.legalName??'');setPhone(value.phone??'');setWa(value.whatsappNumber??'');setEmail(value.email??'');setAddress(value.address??'');setNationalId(value.nationalIdentity??'');setTaxId(value.taxIdentity??'');setSource(value.source);setService(value.requestedService??'');setExpected(value.expectedValue??'');setCurrency(value.currency??'EGP');setResponsible(value.responsibleUserId??'');setReferralAgent(value.referralAgentId??'');setNotes(value.notes??'');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(event:FormEvent){event.preventDefault();const common={partyKind:kind,displayName:name,legalName:legalName||null,phone:phone||null,whatsappNumber:wa||null,email:email||null,address:address||null,nationalIdentity:nationalId||null,taxIdentity:taxId||null,source,requestedService:service||null,expectedValue:expected||null,currency:expected?currency:null,responsibleUserId:responsible||null,referralAgentId:referralAgent||null,notes:notes||null};try{if(editing)await crmPatch(`/crm/leads/${editing.id}`,common);else await crmPost('/crm/leads',common);setNotice(editing?'تم تحديث العميل المحتمل.':'تم إنشاء العميل المحتمل.');reset();await load();}catch(value){setNotice(message(value));}}
 async function transition(id:string,action:'contacted'|'qualified'|'reopen'){try{await crmPost(`/crm/leads/${id}/${action}`,{});await load();}catch(value){setNotice(message(value));}}
 async function lose(id:string){if(!lostReason.trim())return;try{await crmPost(`/crm/leads/${id}/lost`,{reason:lostReason.trim()});setLosingId('');setLostReason('');await load();}catch(value){setNotice(message(value));}}
 async function convert(id:string){try{const result=await crmPost<{status:string;reason?:string;customerId?:string}>(`/crm/leads/${id}/convert`,{});setNotice(result.status==='REVIEW_REQUIRED'?'تحويل العميل يحتاج مراجعة التطابق قبل إنشاء/ربط العميل.':'تم تحويل العميل المحتمل وربطه بالعميل دون إنشاء سجل مكرر.');await load();}catch(value){setNotice(message(value));}}
 async function showHistory(value:Lead){try{setHistoryLead(value);setHistory(await crmGet<LeadHistory[]>(`/crm/leads/${value.id}/history`));}catch(error){setNotice(message(error));}}
 const leadActions=(value:Lead)=><ActionBar><Button variant="secondary" onClick={()=>edit(value)}>تعديل</Button><Button variant="secondary" onClick={()=>void showHistory(value)}>السجل</Button><Button variant="secondary" onClick={()=>whatsapp(value.whatsappNumber??value.phone)} disabled={!value.whatsappNumber&&!value.phone}>واتساب</Button>{value.status==='NEW'?<Button onClick={()=>void transition(value.id,'contacted')}>تم التواصل</Button>:null}{value.status==='CONTACTED'?<Button onClick={()=>void transition(value.id,'qualified')}>تأهيل</Button>:null}{value.status==='QUALIFIED'?<Button onClick={()=>go(`/crm/quotations?leadId=${encodeURIComponent(value.id)}`)}>إنشاء عرض سعر</Button>:null}{value.status==='QUOTED'?<Button onClick={()=>void convert(value.id)}>تحويل إلى عميل</Button>:null}{value.status==='LOST'?<Button onClick={()=>void transition(value.id,'reopen')}>إعادة فتح</Button>:value.status!=='WON'?<Button variant="danger" onClick={()=>{setLosingId(value.id);setLostReason('');}}>تسجيل كمفقود</Button>:null}<Button variant="secondary" onClick={()=>go(`/crm/followups?leadId=${encodeURIComponent(value.id)}`)}>متابعة</Button></ActionBar>;
 return <section aria-label="إدارة العملاء المحتملين" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="جديد" value={counts.NEW}/><MetricCard label="تم التواصل" value={counts.CONTACTED}/><MetricCard label="مؤهل" value={counts.QUALIFIED}/><MetricCard label="عروض سعر" value={counts.QUOTED}/><MetricCard label="ناجح" value={counts.WON} tone="success"/><MetricCard label="مفقود" value={counts.LOST} tone={counts.LOST?'warning':'neutral'}/></div>
  {notice?<Toast tone="info">{notice}</Toast>:null}
  <section className="ui-dashboard-grid"><Card title="فلترة مسار المبيعات"><div className="ui-filter-grid"><FormField label="بحث"><Input aria-label="بحث العملاء المحتملين" value={q} onChange={event=>setQ(event.target.value)} placeholder="الرقم أو الاسم أو الهاتف"/></FormField><FormField label="المرحلة"><Select aria-label="مرحلة العميل المحتمل" value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل المراحل</option>{leadStages.map(key=><option key={key} value={key}>{leadLabels[key]}</option>)}</Select></FormField><FormField label="المسؤول"><Select aria-label="المسؤول" value={responsibleFilter} onChange={event=>setResponsibleFilter(event.target.value)}><option value="">كل المسؤولين</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField></div></Card><Card title="CRM Lead Pipeline"><div className="ui-inline"><Badge tone="info">Kanban</Badge><Badge>{list.length} / {all.length}</Badge></div><p>جديد ← تم التواصل ← مؤهل ← عرض سعر ← ناجح / مفقود.</p></Card></section>
  <DisclosureCard title={editing?'تعديل العميل المحتمل':'إضافة عميل محتمل'} description="ملف بيع كامل قبل التحويل لعميل، مع الاحتفاظ بمصدر الفرصة والمسؤول والمندوب المحيل." open={Boolean(editing)}><form className="ui-filter-grid" onSubmit={save}><FormField label="نوع الطرف" required><Select value={kind} onChange={event=>setKind(event.target.value as PartyKind)}><option value="PERSON">فرد</option><option value="ORGANIZATION">شركة / جهة</option></Select></FormField><FormField label="الاسم" required><Input required value={name} onChange={event=>setName(event.target.value)}/></FormField>{kind==='ORGANIZATION'?<FormField label="الاسم القانوني"><Input value={legalName} onChange={event=>setLegalName(event.target.value)}/></FormField>:null}<FormField label="الهاتف"><Input value={phone} onChange={event=>setPhone(event.target.value)}/></FormField><FormField label="واتساب"><Input value={wa} onChange={event=>setWa(event.target.value)}/></FormField><FormField label="البريد الإلكتروني"><Input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></FormField><FormField label="العنوان"><Textarea value={address} onChange={event=>setAddress(event.target.value)}/></FormField>{kind==='PERSON'?<FormField label="الرقم القومي / الهوية"><Input value={nationalId} onChange={event=>setNationalId(event.target.value)}/></FormField>:<FormField label="الرقم الضريبي"><Input value={taxId} onChange={event=>setTaxId(event.target.value)}/></FormField>}<FormField label="مصدر العميل المحتمل" required><Input required value={source} onChange={event=>setSource(event.target.value)}/></FormField><FormField label="الخدمة المطلوبة"><Input value={service} onChange={event=>setService(event.target.value)}/></FormField><FormField label="القيمة المتوقعة"><Input inputMode="decimal" value={expected} onChange={event=>setExpected(event.target.value)}/></FormField>{expected?<FormField label="العملة"><Input value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField>:null}<FormField label="المسؤول"><Select value={responsible} onChange={event=>setResponsible(event.target.value)}><option value="">بدون مسؤول محدد</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField><FormField label="المندوب المحيل"><Select value={referralAgent} onChange={event=>setReferralAgent(event.target.value)}><option value="">بدون مندوب محيل</option>{agents.map(value=><option key={value.agent.id} value={value.agent.id}>{value.agent.number} — {value.party.displayName}</option>)}</Select></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></FormField><ActionBar><Button type="submit">{editing?'حفظ التعديل':'حفظ العميل المحتمل'}</Button>{editing?<Button type="button" variant="secondary" onClick={reset}>إلغاء</Button>:null}</ActionBar></form></DisclosureCard>
  {error?<ErrorState message={error}/>:<Card title="لوحة مراحل المبيعات"><div className="ui-grid-md" role="list" aria-label="مراحل مسار المبيعات">{leadStages.map(stage=>{const stageRows=list.filter(value=>value.status===stage);return <section key={stage} className="ui-record-card" role="listitem" aria-label={leadLabels[stage]}><div className="ui-inline"><strong>{leadLabels[stage]}</strong><Badge tone={tone(stage)}>{stageRows.length}</Badge></div>{!stageRows.length?<EmptyState title="لا توجد فرص في هذه المرحلة"/>:<div className="ui-flow">{stageRows.map(value=><article key={value.id} className="ui-record-card"><div className="ui-inline"><strong>{value.displayName}</strong><Badge tone={tone(value.status)}>{value.number}</Badge></div><p>{value.requestedService??value.source}</p><p><strong>{value.expectedValue?`${value.expectedValue} ${value.currency??''}`:'بدون قيمة متوقعة'}</strong></p><small>{value.phone??value.email??'بدون وسيلة اتصال'} · {users.find(user=>user.id===value.responsibleUserId)?.displayName??'بدون مسؤول'}</small>{value.lostReason?<p>{value.lostReason}</p>:null}{leadActions(value)}</article>)}</div>}</section>;})}</div></Card>}
  <Dialog open={Boolean(losingId)} title="سبب فقد العميل المحتمل" onClose={()=>{setLosingId('');setLostReason('');}}><FormField label="السبب" required><Textarea value={lostReason} onChange={event=>setLostReason(event.target.value)}/></FormField><ActionBar><Button variant="danger" onClick={()=>void lose(losingId)} disabled={!lostReason.trim()}>تأكيد الفقد</Button><Button variant="secondary" onClick={()=>{setLosingId('');setLostReason('');}}>إلغاء</Button></ActionBar></Dialog>
  <Dialog open={Boolean(historyLead)} title={historyLead?`سجل ${historyLead.number} — ${historyLead.displayName}`:'سجل العميل المحتمل'} onClose={()=>setHistoryLead(null)}>{!history.length?<EmptyState/>:<DataGrid columns={['الحدث','من','إلى','التفصيل','الوقت']}>{history.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.fromStatus?leadLabels[item.fromStatus]:'—'}</td><td>{item.toStatus?leadLabels[item.toStatus]:'—'}</td><td>{item.detail??'—'}</td><td>{new Date(item.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Dialog>
 </section>;
}

export function FollowupsPage(){
 const[leads,setLeads]=useState<Lead[]>([]),[users,setUsers]=useState<UserOption[]>([]),[rows,setRows]=useState<Followup[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[lead,setLead]=useState(()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('leadId')??''),[responsible,setResponsible]=useState(''),[interactionType,setInteractionType]=useState('CALL'),[scheduledAt,setScheduledAt]=useState(''),[nextAction,setNextAction]=useState('');
 const[mode,setMode]=useState<'due'|'overdue'>('due'),[through,setThrough]=useState(defaultThrough),[responsibleFilter,setResponsibleFilter]=useState(''),[selectedLead,setSelectedLead]=useState(()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('leadId')??''),[leadTimeline,setLeadTimeline]=useState<Followup[]>([]);
 const[completeId,setCompleteId]=useState(''),[outcome,setOutcome]=useState(''),[completionNextAction,setCompletionNextAction]=useState(''),[nextScheduledAt,setNextScheduledAt]=useState(''),[nextInteraction,setNextInteraction]=useState('CALL'),[nextResponsible,setNextResponsible]=useState('');
 const[rescheduleId,setRescheduleId]=useState(''),[rescheduledAt,setRescheduledAt]=useState(''),[cancelId,setCancelId]=useState(''),[cancelReason,setCancelReason]=useState(''),[voidId,setVoidId]=useState(''),[voidReason,setVoidReason]=useState(''),[history,setHistory]=useState<FollowupHistory[]>([]),[historyId,setHistoryId]=useState('');
 async function loadReferences(){try{const[l,u]=await Promise.all([crmGet<Lead[]>('/crm/leads'),crmGet<UserOption[]>('/crm/insights/assignees')]);setLeads(l);setUsers(u);}catch(value){setError(message(value));}}
 async function loadQueue(){try{const params=new URLSearchParams({...responsibleFilter&&{responsibleUserId:responsibleFilter}});const path=mode==='overdue'?`/crm/followups/overdue?${params}`:`/crm/followups/due?${new URLSearchParams({through:toIso(through),...responsibleFilter&&{responsibleUserId:responsibleFilter}})}`;setRows(await crmGet<Followup[]>(path));setError('');}catch(value){setError(message(value));}}
 async function loadLeadTimeline(id=selectedLead){if(!id){setLeadTimeline([]);return;}try{setLeadTimeline(await crmGet<Followup[]>(`/crm/followups/lead/${encodeURIComponent(id)}`));}catch(value){setNotice(message(value));}}
 useEffect(()=>{void loadReferences();},[]);useEffect(()=>{void loadQueue();},[mode,through,responsibleFilter]);useEffect(()=>{if(selectedLead)void loadLeadTimeline(selectedLead);},[selectedLead]);
 const queueCounts=useMemo(()=>({shown:rows.length,late:rows.filter(item=>new Date(item.scheduledAt).getTime()<Date.now()).length,timeline:leadTimeline.length,completed:leadTimeline.filter(item=>item.status==='COMPLETED'&&!item.completionVoidedAt).length}),[rows,leadTimeline]);
 async function schedule(event:FormEvent){event.preventDefault();try{await crmPost('/crm/followups',{leadId:lead,responsibleUserId:responsible,interactionType,scheduledAt:toIso(scheduledAt),nextAction:nextAction||undefined});setNotice('تمت جدولة المتابعة.');setScheduledAt('');setNextAction('');await loadQueue();if(selectedLead===lead)await loadLeadTimeline(lead);}catch(value){setNotice(message(value));}}
 async function complete(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${completeId}/complete`,{outcome,nextAction:completionNextAction||undefined,...nextScheduledAt?{nextScheduledAt:toIso(nextScheduledAt),nextInteractionType:nextInteraction,nextResponsibleUserId:nextResponsible||undefined}:{}});setNotice('تم إكمال المتابعة وحفظ النتيجة.');setCompleteId('');setOutcome('');setCompletionNextAction('');setNextScheduledAt('');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function reschedule(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${rescheduleId}/reschedule`,{scheduledAt:toIso(rescheduledAt)});setRescheduleId('');setRescheduledAt('');setNotice('تمت إعادة جدولة المتابعة.');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function cancel(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${cancelId}/cancel`,{reason:cancelReason||undefined});setCancelId('');setCancelReason('');setNotice('تم إلغاء المتابعة مع حفظ السبب.');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function voidCompletion(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${voidId}/void-completion`,{reason:voidReason});setVoidId('');setVoidReason('');setNotice('تم إبطال تسجيل الإكمال كتصحيح مع الاحتفاظ بالتاريخ.');await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function showHistory(id:string){try{setHistoryId(id);setHistory(await crmGet<FollowupHistory[]>(`/crm/followups/${id}/history`));}catch(value){setNotice(message(value));}}
 const leadName=(id:string)=>{const value=leads.find(item=>item.id===id);return value?`${value.number} — ${value.displayName}`:id;};const responsibleName=(id:string)=>{const value=users.find(item=>item.id===id);return value?userLabel(value):id;};
 const actionButtons=(value:Followup)=><ActionBar>{value.status==='SCHEDULED'?<><Button onClick={()=>{setCompleteId(value.id);setOutcome('');setCompletionNextAction(value.nextAction??'');setNextResponsible(value.responsibleUserId);setNextInteraction(value.interactionType);}}>إكمال</Button><Button variant="secondary" onClick={()=>{setRescheduleId(value.id);setRescheduledAt(toLocalInput(new Date(value.scheduledAt)));}}>إعادة جدولة</Button><Button variant="danger" onClick={()=>{setCancelId(value.id);setCancelReason('');}}>إلغاء</Button></>:null}{value.status==='COMPLETED'&&!value.completionVoidedAt?<Button variant="secondary" onClick={()=>{setVoidId(value.id);setVoidReason('');}}>تصحيح الإكمال</Button>:null}<Button variant="secondary" onClick={()=>void showHistory(value.id)}>السجل</Button></ActionBar>;
 return <section aria-label="إدارة المتابعات" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="المعروضة" value={queueCounts.shown}/><MetricCard label="متأخرة ضمن العرض" value={queueCounts.late} tone={queueCounts.late?'warning':'neutral'}/><MetricCard label="سجل العميل المحدد" value={queueCounts.timeline}/><MetricCard label="مكتملة للعميل" value={queueCounts.completed} tone="success"/></div>
  {notice?<Toast tone="info">{notice}</Toast>:null}
  <section className="ui-dashboard-grid"><DisclosureCard title="جدولة متابعة" description="اختر العميل المحتمل والمسؤول بدل إدخال المعرفات الداخلية." open={Boolean(lead)}><form className="ui-filter-grid" onSubmit={schedule}><FormField label="العميل المحتمل" required><Select required value={lead} onChange={event=>setLead(event.target.value)}><option value="">اختر العميل المحتمل</option>{leads.filter(item=>item.status!=='WON'&&item.status!=='LOST').map(item=><option key={item.id} value={item.id}>{item.number} — {item.displayName}</option>)}</Select></FormField><FormField label="المسؤول" required><Select required value={responsible} onChange={event=>setResponsible(event.target.value)}><option value="">اختر المسؤول</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField><FormField label="نوع التواصل"><Select value={interactionType} onChange={event=>setInteractionType(event.target.value)}>{Object.entries(interactionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="الموعد" required><Input required type="datetime-local" value={scheduledAt} onChange={event=>setScheduledAt(event.target.value)}/></FormField><FormField label="الإجراء التالي"><Input value={nextAction} onChange={event=>setNextAction(event.target.value)}/></FormField><Button type="submit">جدولة المتابعة</Button></form></DisclosureCard><Card title="فلترة قائمة العمل"><div className="ui-filter-grid"><FormField label="القائمة"><Select value={mode} onChange={event=>setMode(event.target.value as 'due'|'overdue')}><option value="due">المستحقة حتى تاريخ</option><option value="overdue">المتأخرة الآن</option></Select></FormField>{mode==='due'?<FormField label="حتى"><Input type="datetime-local" value={through} onChange={event=>setThrough(event.target.value)}/></FormField>:null}<FormField label="المسؤول"><Select value={responsibleFilter} onChange={event=>setResponsibleFilter(event.target.value)}><option value="">كل المسؤولين</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField></div></Card></section>
  <section className="ui-dashboard-grid"><Card title="قائمة المتابعات">{error?<ErrorState message={error}/>:!rows.length?<EmptyState title="لا توجد متابعات في قائمة العمل"/>:<DataGrid columns={['العميل المحتمل','النوع','المسؤول','الموعد','الحالة','الإجراء التالي','إجراءات']}>{rows.map(value=><tr key={value.id}><td>{leadName(value.leadId)}</td><td>{interactionLabels[value.interactionType]??value.interactionType}</td><td>{responsibleName(value.responsibleUserId)}</td><td>{new Date(value.scheduledAt).toLocaleString('ar-EG')}</td><td><Badge tone={tone(value.status)}>{followupLabels[value.status]}</Badge></td><td>{value.nextAction??'—'}</td><td>{actionButtons(value)}</td></tr>)}</DataGrid>}</Card><Card title="Timeline العميل المحتمل"><FormField label="العميل"><Select value={selectedLead} onChange={event=>setSelectedLead(event.target.value)}><option value="">اختر العميل المحتمل</option>{leads.map(item=><option key={item.id} value={item.id}>{item.number} — {item.displayName}</option>)}</Select></FormField>{selectedLead&&!leadTimeline.length?<EmptyState title="لا توجد متابعات لهذا العميل"/>:leadTimeline.length?<DataGrid columns={['النوع','الموعد','الحالة','النتيجة','إجراءات']}>{leadTimeline.map(value=><tr key={value.id}><td>{interactionLabels[value.interactionType]??value.interactionType}</td><td>{new Date(value.scheduledAt).toLocaleString('ar-EG')}</td><td><Badge tone={tone(value.status)}>{followupLabels[value.status]}{value.completionVoidedAt?' — مصحح':''}</Badge></td><td>{value.outcome??'—'}</td><td>{actionButtons(value)}</td></tr>)}</DataGrid>:null}</Card></section>
  <Dialog open={Boolean(completeId)} title="إكمال المتابعة" onClose={()=>setCompleteId('')}><form className="ui-filter-grid" onSubmit={complete}><FormField label="النتيجة" required><Textarea required value={outcome} onChange={event=>setOutcome(event.target.value)}/></FormField><FormField label="الإجراء التالي"><Input value={completionNextAction} onChange={event=>setCompletionNextAction(event.target.value)}/></FormField><FormField label="موعد متابعة تالية (اختياري)"><Input type="datetime-local" value={nextScheduledAt} onChange={event=>setNextScheduledAt(event.target.value)}/></FormField>{nextScheduledAt?<><FormField label="نوع التواصل التالي"><Select value={nextInteraction} onChange={event=>setNextInteraction(event.target.value)}>{Object.entries(interactionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="المسؤول التالي"><Select value={nextResponsible} onChange={event=>setNextResponsible(event.target.value)}>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField></>:null}<ActionBar><Button type="submit">حفظ الإكمال</Button><Button type="button" variant="secondary" onClick={()=>setCompleteId('')}>إلغاء</Button></ActionBar></form></Dialog>
  <Dialog open={Boolean(rescheduleId)} title="إعادة جدولة" onClose={()=>setRescheduleId('')}><form onSubmit={reschedule}><FormField label="الموعد الجديد" required><Input required type="datetime-local" value={rescheduledAt} onChange={event=>setRescheduledAt(event.target.value)}/></FormField><ActionBar><Button type="submit">حفظ الموعد</Button><Button type="button" variant="secondary" onClick={()=>setRescheduleId('')}>إلغاء</Button></ActionBar></form></Dialog>
  <Dialog open={Boolean(cancelId)} title="إلغاء المتابعة" onClose={()=>setCancelId('')}><form onSubmit={cancel}><FormField label="سبب الإلغاء"><Textarea value={cancelReason} onChange={event=>setCancelReason(event.target.value)}/></FormField><ActionBar><Button type="submit" variant="danger">تأكيد الإلغاء</Button><Button type="button" variant="secondary" onClick={()=>setCancelId('')}>رجوع</Button></ActionBar></form></Dialog>
  <Dialog open={Boolean(voidId)} title="تصحيح إكمال متابعة" onClose={()=>setVoidId('')}><form onSubmit={voidCompletion}><FormField label="سبب التصحيح" required><Textarea required value={voidReason} onChange={event=>setVoidReason(event.target.value)}/></FormField><ActionBar><Button type="submit">تسجيل التصحيح</Button><Button type="button" variant="secondary" onClick={()=>setVoidId('')}>إلغاء</Button></ActionBar></form></Dialog>
  <Dialog open={Boolean(historyId)} title={historyId?`تاريخ المتابعة ${historyId}`:'تاريخ المتابعة'} onClose={()=>setHistoryId('')}>{!history.length?<EmptyState/>:<DataGrid columns={['الحدث','التفصيل','الموعد السابق','الموعد','الوقت']}>{history.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.detail??'—'}</td><td>{item.previousScheduledAt?new Date(item.previousScheduledAt).toLocaleString('ar-EG'):'—'}</td><td>{item.scheduledAt?new Date(item.scheduledAt).toLocaleString('ar-EG'):'—'}</td><td>{new Date(item.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Dialog>
 </section>;
}
