import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, DataGrid, EmptyState, ErrorState, FormField, Input, LoadingState, MetricCard, Tabs } from './ui.js';
import { crmGet } from './crm-core-client.js';

type Party={id:string;kind:'PERSON'|'ORGANIZATION';displayName:string;legalName:string|null;phone:string|null;email:string|null;whatsappNumber:string|null;address:string|null;nationalIdentity:string|null;taxIdentity:string|null};
type CustomerView={customer:{id:string;number:string;status:string;assignedAgentId:string|null;commercialNotes:string|null};party:Party};
type AgentView={agent:{id:string;number:string;status:string;notes:string|null;commission:{kind:string;value:string;currency:string|null}};party:Party};
type Lead={id:string;number:string;displayName:string;phone:string|null;source:string;requestedService:string|null;expectedValue:string|null;currency:string|null;status:string;lostReason:string|null};
type Followup={id:string;leadId:string;interactionType:string;scheduledAt:string;status:string;outcome:string|null;nextAction:string|null};
type Quote={id:string;number:string;status:string;approvalStatus:string;currency:string;customerId:string|null;sourceLeadId:string|null;customerSnapshot:{displayName:string};currentRevisionId:string;acceptedRevisionId:string|null;billingInvoiceId:string|null;revisions:Array<{id:string;validityDate:string;total:string}>};
type Traveler={id:string;fullName:string;dateOfBirth:string|null;gender:string|null;nationality:string|null;customerId:string|null;status:'ACTIVE'|'ARCHIVED'};
type Position={invoiceId:string;currency:string;documentTotal:string;outstanding:string;status:string};
type Customer360={customer:CustomerView;leads:Lead[];followups:Followup[];quotations:Quote[];travelers:Traveler[];quotationLinkedFinancialPositions:Position[];quotationLinkedFinancialSummaryByCurrency:Array<{currency:string;documentTotal:string;outstanding:string}>};
type Agent360={agent:AgentView;customers:CustomerView[];leads:Lead[];quotations:Quote[]};

const customerTabs=[{id:'summary',label:'الملخص'},{id:'finance',label:'المالية'},{id:'operations',label:'العمليات'},{id:'activity',label:'النشاط'}];
const agentTabs=[{id:'summary',label:'الملخص'},{id:'customers',label:'العملاء'},{id:'pipeline',label:'المبيعات والمتابعة'}];
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
function queryParam(name:string){return typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';}
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}
function quoteTotal(quote:Quote){const revision=quote.revisions.find(item=>item.id===(quote.acceptedRevisionId??quote.currentRevisionId));return revision?.total??'0';}

export function Customer360Page(){
 const[id,setId]=useState(()=>queryParam('customerId')),[data,setData]=useState<Customer360|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tab,setTab]=useState('summary');
 async function load(){if(!id.trim())return;setLoading(true);try{setData(await crmGet<Customer360>(`/crm/insights/customers/${encodeURIComponent(id.trim())}`));setError('');}catch(error){setError(errorMessage(error));setData(null);}finally{setLoading(false);}}
 useEffect(()=>{if(id)void load();},[]);
 const outstandingCurrencies=useMemo(()=>data?.quotationLinkedFinancialSummaryByCurrency.filter(item=>item.outstanding!=='0').length??0,[data]);
 return <section aria-label="ملف العميل 360 درجة" className="ui-page-stack">
  <Card title="ملف العميل 360°"><div className="ui-filter-row"><FormField label="معرّف العميل"><Input value={id} onChange={event=>setId(event.target.value)}/></FormField><Button onClick={()=>void load()}>عرض الملف الموحد</Button></div></Card>
  {loading?<LoadingState label="جارٍ تحميل ملف العميل…"/>:null}{error?<ErrorState message={error}/>:null}
  {data?<>
   <Card title={`${data.customer.customer.number} — ${data.customer.party.displayName}`}><div className="ui-grid-md"><div><strong>{data.customer.party.kind==='ORGANIZATION'?'شركة / جهة':'فرد'}</strong><p>{data.customer.party.legalName??''}</p></div><div><strong>الحالة</strong><p><Badge tone={data.customer.customer.status==='ACTIVE'?'success':'warning'}>{data.customer.customer.status==='ACTIVE'?'نشط':'معلّق'}</Badge></p></div><div><strong>الهاتف</strong><p>{data.customer.party.phone??'—'}</p></div><div><strong>البريد</strong><p>{data.customer.party.email??'—'}</p></div></div><div><Button onClick={()=>window.location.href=`/crm/customers?q=${encodeURIComponent(data.customer.customer.number)}`}>العودة للعملاء</Button><Button onClick={()=>whatsapp(data.customer.party.whatsappNumber??data.customer.party.phone)} disabled={!data.customer.party.whatsappNumber&&!data.customer.party.phone}>واتساب</Button><Button onClick={()=>window.location.href=`/crm/quotations?customerId=${encodeURIComponent(data.customer.customer.id)}`}>عرض سعر جديد</Button></div></Card>
   <div className="ui-metric-grid"><MetricCard label="العملاء المحتملون المرتبطون" value={data.leads.length}/><MetricCard label="المتابعات" value={data.followups.length}/><MetricCard label="عروض الأسعار" value={data.quotations.length}/><MetricCard label="المسافرون" value={data.travelers.length}/><MetricCard label="عملات بها رصيد عرض/فاتورة مفتوح" value={outstandingCurrencies} tone={outstandingCurrencies?'warning':'neutral'}/></div>
   <Tabs tabs={customerTabs} active={tab} onChange={setTab}/>
   {tab==='summary'?<div className="ui-grid-md"><Card title="بيانات الاتصال والهوية"><p><strong>واتساب:</strong> {data.customer.party.whatsappNumber??'—'}</p><p><strong>العنوان:</strong> {data.customer.party.address??'—'}</p><p><strong>الهوية:</strong> {data.customer.party.nationalIdentity??'—'}</p><p><strong>الرقم الضريبي:</strong> {data.customer.party.taxIdentity??'—'}</p></Card><Card title="البيانات التجارية"><p><strong>المندوب المسؤول:</strong> {data.customer.customer.assignedAgentId??'—'}</p><p><strong>ملاحظات:</strong> {data.customer.customer.commercialNotes??'—'}</p></Card></div>:null}
   {tab==='finance'?<><Card title="المراكز المالية المرتبطة بعروض الأسعار"><p><small>هذه الأرقام تأتي من Billing للفواتير الناتجة عن عروض الأسعار فقط، وليست رصيد حساب CRM مستقلًا.</small></p>{!data.quotationLinkedFinancialSummaryByCurrency.length?<EmptyState title="لا توجد فواتير محولة مرتبطة بعروض الأسعار"/>:<DataGrid columns={['العملة','إجمالي المستندات','المتبقي']}>{data.quotationLinkedFinancialSummaryByCurrency.map(item=><tr key={item.currency}><td>{item.currency}</td><td>{item.documentTotal}</td><td>{item.outstanding}</td></tr>)}</DataGrid>}</Card><Card title="الفواتير المرتبطة بالعروض">{!data.quotationLinkedFinancialPositions.length?<EmptyState/>:<DataGrid columns={['الفاتورة','العملة','الإجمالي','المتبقي','الحالة']}>{data.quotationLinkedFinancialPositions.map(item=><tr key={item.invoiceId}><td>{item.invoiceId}</td><td>{item.currency}</td><td>{item.documentTotal}</td><td>{item.outstanding}</td><td>{item.status}</td></tr>)}</DataGrid>}</Card></>:null}
   {tab==='operations'?<><Card title="عروض الأسعار">{!data.quotations.length?<EmptyState/>:<DataGrid columns={['الرقم','الحالة','العملة','القيمة','الفاتورة']}>{data.quotations.map(quote=><tr key={quote.id}><td>{quote.number}</td><td>{quote.status}</td><td>{quote.currency}</td><td>{quoteTotal(quote)}</td><td>{quote.billingInvoiceId??'—'}</td></tr>)}</DataGrid>}</Card><Card title="المسافرون المرتبطون">{!data.travelers.length?<EmptyState/>:<DataGrid columns={['الاسم','الجنسية','تاريخ الميلاد','النوع','الحالة']}>{data.travelers.map(traveler=><tr key={traveler.id}><td>{traveler.fullName}</td><td>{traveler.nationality??'—'}</td><td>{traveler.dateOfBirth??'—'}</td><td>{traveler.gender??'—'}</td><td>{traveler.status}</td></tr>)}</DataGrid>}</Card></>:null}
   {tab==='activity'?<><Card title="العملاء المحتملون المرتبطون">{!data.leads.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','المصدر','الخدمة','المرحلة']}>{data.leads.map(lead=><tr key={lead.id}><td>{lead.number}</td><td>{lead.displayName}</td><td>{lead.source}</td><td>{lead.requestedService??'—'}</td><td>{lead.status}</td></tr>)}</DataGrid>}</Card><Card title="المتابعات">{!data.followups.length?<EmptyState/>:<DataGrid columns={['النوع','الموعد','الحالة','النتيجة','الإجراء التالي']}>{data.followups.map(followup=><tr key={followup.id}><td>{followup.interactionType}</td><td>{new Date(followup.scheduledAt).toLocaleString('ar-EG')}</td><td>{followup.status}</td><td>{followup.outcome??'—'}</td><td>{followup.nextAction??'—'}</td></tr>)}</DataGrid>}</Card></>:null}
  </>:null}
 </section>;
}

export function Agent360Page(){
 const[id,setId]=useState(()=>queryParam('agentId')),[data,setData]=useState<Agent360|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tab,setTab]=useState('summary');
 async function load(){if(!id.trim())return;setLoading(true);try{setData(await crmGet<Agent360>(`/crm/insights/agents/${encodeURIComponent(id.trim())}`));setError('');}catch(error){setError(errorMessage(error));setData(null);}finally{setLoading(false);}}
 useEffect(()=>{if(id)void load();},[]);
 return <section aria-label="ملف المندوب 360 درجة" className="ui-page-stack"><Card title="ملف المندوب 360°"><div className="ui-filter-row"><FormField label="معرّف المندوب"><Input value={id} onChange={event=>setId(event.target.value)}/></FormField><Button onClick={()=>void load()}>عرض الملف الموحد</Button></div></Card>{loading?<LoadingState label="جارٍ تحميل ملف المندوب…"/>:null}{error?<ErrorState message={error}/>:null}{data?<><Card title={`${data.agent.agent.number} — ${data.agent.party.displayName}`}><p>الحالة: <Badge tone={data.agent.agent.status==='ACTIVE'?'success':'warning'}>{data.agent.agent.status==='ACTIVE'?'نشط':'معلّق'}</Badge></p><p>الهاتف: {data.agent.party.phone??'—'} | واتساب: {data.agent.party.whatsappNumber??'—'}</p><p>العمولة التجارية الافتراضية: {data.agent.agent.commission.kind==='PERCENT'?`${data.agent.agent.commission.value}%`:`${data.agent.agent.commission.value} ${data.agent.agent.commission.currency??''}`}</p><small>القيمة أعلاه شرط تجاري افتراضي وليست مطالبة عمولة محاسبية.</small></Card><div className="ui-metric-grid"><MetricCard label="العملاء المسندون" value={data.customers.length}/><MetricCard label="عملاء محتملون محالون" value={data.leads.length}/><MetricCard label="عروض مرتبطة" value={data.quotations.length}/></div><Tabs tabs={agentTabs} active={tab} onChange={setTab}/>{tab==='summary'?<div className="ui-grid-md"><Card title="الاتصال"><p>{data.agent.party.phone??'—'}</p><p>{data.agent.party.email??'—'}</p><Button onClick={()=>whatsapp(data.agent.party.whatsappNumber??data.agent.party.phone)} disabled={!data.agent.party.whatsappNumber&&!data.agent.party.phone}>واتساب</Button></Card><Card title="ملاحظات"><p>{data.agent.agent.notes??'—'}</p></Card></div>:null}{tab==='customers'?<Card title="العملاء المسندون">{!data.customers.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','الهاتف','الحالة','الملف']}>{data.customers.map(customer=><tr key={customer.customer.id}><td>{customer.customer.number}</td><td>{customer.party.displayName}</td><td>{customer.party.phone??'—'}</td><td>{customer.customer.status}</td><td><Button onClick={()=>window.location.href=`/crm/customer-360?customerId=${encodeURIComponent(customer.customer.id)}`}>360°</Button></td></tr>)}</DataGrid>}</Card>:null}{tab==='pipeline'?<><Card title="العملاء المحتملون">{!data.leads.length?<EmptyState/>:<DataGrid columns={['الرقم','الاسم','المصدر','المرحلة']}>{data.leads.map(lead=><tr key={lead.id}><td>{lead.number}</td><td>{lead.displayName}</td><td>{lead.source}</td><td>{lead.status}</td></tr>)}</DataGrid>}</Card><Card title="عروض الأسعار المرتبطة">{!data.quotations.length?<EmptyState/>:<DataGrid columns={['الرقم','العميل','الحالة','القيمة']}>{data.quotations.map(quote=><tr key={quote.id}><td>{quote.number}</td><td>{quote.customerSnapshot.displayName}</td><td>{quote.status}</td><td>{quoteTotal(quote)} {quote.currency}</td></tr>)}</DataGrid>}</Card></>:null}</>:null}</section>;
}
