import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, MetricCard, Select, Textarea } from './ui.js';
import { crmGet, crmPatch, crmPost } from './crm-core-client.js';

type PartyKind='PERSON'|'ORGANIZATION';
type LeadStatus='NEW'|'CONTACTED'|'QUALIFIED'|'QUOTED'|'WON'|'LOST';
type Lead={
 id:string;number:string;partyKind:PartyKind;displayName:string;legalName:string|null;phone:string|null;whatsappNumber:string|null;email:string|null;address:string|null;
 nationalIdentity:string|null;taxIdentity:string|null;source:string;requestedService:string|null;expectedValue:string|null;currency:string|null;status:LeadStatus;
 responsibleUserId:string|null;referralAgentId:string|null;notes:string|null;lostReason:string|null;quotationReference:string|null;convertedCustomerId:string|null;
};
type LeadHistory={id:string;kind:string;fromStatus:LeadStatus|null;toStatus:LeadStatus|null;detail:string|null;occurredAt:string;actorId:string};
type AgentView={agent:{id:string;number:string;status:'ACTIVE'|'SUSPENDED'};party:{displayName:string}};
type UserOption={id:string;displayName?:string;name?:string;username?:string;active?:boolean};
type FollowupStatus='SCHEDULED'|'COMPLETED'|'CANCELLED';
type Followup={id:string;leadId:string;responsibleUserId:string;interactionType:string;scheduledAt:string;status:FollowupStatus;outcome:string|null;nextAction:string|null;previousFollowupId:string|null;completedAt:string|null;cancelledAt:string|null;completionVoidedAt:string|null;completionVoidReason:string|null};
type FollowupHistory={id:string;kind:string;detail:string|null;previousScheduledAt:string|null;scheduledAt:string|null;occurredAt:string;actorId:string};

const leadLabels:Record<LeadStatus,string>={NEW:'جديد',CONTACTED:'تم التواصل',QUALIFIED:'مؤهل',QUOTED:'تم عرض السعر',WON:'ناجح',LOST:'مفقود'};
const interactionLabels:Record<string,string>={CALL:'مكالمة',WHATSAPP:'واتساب',MEETING:'اجتماع',EMAIL:'بريد إلكتروني',OTHER:'أخرى'};
const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const tone=(status:string)=>status==='WON'||status==='COMPLETED'?'success':status==='LOST'||status==='CANCELLED'?'warning':'info';
const userLabel=(value:UserOption)=>value.displayName||value.name||value.username||value.id;
const toLocalInput=(date:Date)=>{const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16);};
const defaultThrough=()=>toLocalInput(new Date(Date.now()+7*24*60*60*1000));
const toIso=(value:string)=>new Date(value).toISOString();
function go(path:string){window.location.href=path;}
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}

export function LeadsPage(){
 const[q,setQ]=useState(''),[status,setStatus]=useState(''),[responsibleFilter,setResponsibleFilter]=useState(''),[editing,setEditing]=useState<Lead|null>(null),[notice,setNotice]=useState('');
 const[kind,setKind]=useState<PartyKind>('PERSON'),[name,setName]=useState(''),[legalName,setLegalName]=useState(''),[phone,setPhone]=useState(''),[wa,setWa]=useState(''),[email,setEmail]=useState(''),[address,setAddress]=useState(''),[nationalId,setNationalId]=useState(''),[taxId,setTaxId]=useState(''),[source,setSource]=useState(''),[service,setService]=useState(''),[expected,setExpected]=useState(''),[currency,setCurrency]=useState('EGP'),[responsible,setResponsible]=useState(''),[referralAgent,setReferralAgent]=useState(''),[notes,setNotes]=useState('');
 const[losingId,setLosingId]=useState(''),[lostReason,setLostReason]=useState(''),[historyLead,setHistoryLead]=useState<Lead|null>(null),[history,setHistory]=useState<LeadHistory[]>([]);
 const[list,setList]=useState<Lead[]>([]),[all,setAll]=useState<Lead[]>([]),[agents,setAgents]=useState<AgentView[]>([]),[users,setUsers]=useState<UserOption[]>([]),[error,setError]=useState('');
 const listPath=useMemo(()=>`/crm/leads?${new URLSearchParams({...status&&{status},...q&&{q},...responsibleFilter&&{responsibleUserId:responsibleFilter}})}`,[q,status,responsibleFilter]);
 async function load(){try{const[rows,everyAgent,everyUser,total]=await Promise.all([crmGet<Lead[]>(listPath),crmGet<AgentView[]>('/crm/agents?status=ACTIVE'),crmGet<UserOption[]>('/system-administration/users'),crmGet<Lead[]>('/crm/leads')]);setList(rows);setAgents(everyAgent);setUsers(everyUser.filter(user=>user.active!==false));setAll(total);setError('');}catch(value){setError(message(value));}}
 useEffect(()=>{void load();},[listPath]);
 const counts=useMemo(()=>Object.fromEntries((Object.keys(leadLabels) as LeadStatus[]).map(key=>[key,all.filter(item=>item.status===key).length])) as Record<LeadStatus,number>,[all]);
 function reset(){setEditing(null);setKind('PERSON');setName('');setLegalName('');setPhone('');setWa('');setEmail('');setAddress('');setNationalId('');setTaxId('');setSource('');setService('');setExpected('');setCurrency('EGP');setResponsible('');setReferralAgent('');setNotes('');}
 function edit(value:Lead){setEditing(value);setKind(value.partyKind);setName(value.displayName);setLegalName(value.legalName??'');setPhone(value.phone??'');setWa(value.whatsappNumber??'');setEmail(value.email??'');setAddress(value.address??'');setNationalId(value.nationalIdentity??'');setTaxId(value.taxIdentity??'');setSource(value.source);setService(value.requestedService??'');setExpected(value.expectedValue??'');setCurrency(value.currency??'EGP');setResponsible(value.responsibleUserId??'');setReferralAgent(value.referralAgentId??'');setNotes(value.notes??'');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(event:FormEvent){event.preventDefault();const common={partyKind:kind,displayName:name,legalName:legalName||null,phone:phone||null,whatsappNumber:wa||null,email:email||null,address:address||null,nationalIdentity:nationalId||null,taxIdentity:taxId||null,source,requestedService:service||null,expectedValue:expected||null,currency:expected?currency:null,responsibleUserId:responsible||null,referralAgentId:referralAgent||null,notes:notes||null};try{if(editing)await crmPatch(`/crm/leads/${editing.id}`,common);else await crmPost('/crm/leads',common);setNotice(editing?'تم تحديث العميل المحتمل.':'تم إنشاء العميل المحتمل.');reset();await load();}catch(value){setNotice(message(value));}}
 async function transition(id:string,action:'contacted'|'qualified'|'reopen'){try{await crmPost(`/crm/leads/${id}/${action}`,{});await load();}catch(value){setNotice(message(value));}}
 async function lose(id:string){if(!lostReason.trim())return;try{await crmPost(`/crm/leads/${id}/lost`,{reason:lostReason.trim()});setLosingId('');setLostReason('');await load();}catch(value){setNotice(message(value));}}
 async function convert(id:string){try{const result=await crmPost<{status:string;reason?:string;customerId?:string}>(`/crm/leads/${id}/convert`,{});setNotice(result.status==='REVIEW_REQUIRED'?'تحويل العميل يحتاج مراجعة التطابق قبل إنشاء/ربط العميل.':'تم تحويل العميل المحتمل وربطه بالعميل دون إنشاء سجل مكرر.');await load();}catch(value){setNotice(message(value));}}
 async function showHistory(value:Lead){try{setHistoryLead(value);setHistory(await crmGet<LeadHistory[]>(`/crm/leads/${value.id}/history`));}catch(error){setNotice(message(error));}}
 return <section aria-label="إدارة العملاء المحتملين" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="جديد" value={counts.NEW}/><MetricCard label="تم التواصل" value={counts.CONTACTED}/><MetricCard label="مؤهل" value={counts.QUALIFIED}/><MetricCard label="عروض سعر" value={counts.QUOTED}/><MetricCard label="ناجح" value={counts.WON} tone="success"/><MetricCard label="مفقود" value={counts.LOST} tone={counts.LOST?'warning':'neutral'}/></div>
  <Card title="العملاء المحتملون والمتابعة"><div className="ui-filter-row"><Input aria-label="بحث العملاء المحتملين" value={q} onChange={event=>setQ(event.target.value)} placeholder="بحث بالرقم أو الاسم أو الهاتف"/><Select aria-label="مرحلة العميل المحتمل" value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل المراحل</option>{(Object.keys(leadLabels) as LeadStatus[]).map(key=><option key={key} value={key}>{leadLabels[key]}</option>)}</Select><Select aria-label="المسؤول" value={responsibleFilter} onChange={event=>setResponsibleFilter(event.target.value)}><option value="">كل المسؤولين</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></div></Card>
  <DisclosureCard title={editing?'تعديل العميل المحتمل':'إضافة عميل محتمل'} description="ملف بيع كامل قبل التحويل لعميل، مع الاحتفاظ بمصدر الفرصة والمسؤول والمندوب المحيل." open={Boolean(editing)}><form onSubmit={save}>
   <FormField label="نوع الطرف" required><Select value={kind} onChange={event=>setKind(event.target.value as PartyKind)}><option value="PERSON">فرد</option><option value="ORGANIZATION">شركة / جهة</option></Select></FormField><FormField label="الاسم" required><Input required value={name} onChange={event=>setName(event.target.value)}/></FormField>{kind==='ORGANIZATION'?<FormField label="الاسم القانوني"><Input value={legalName} onChange={event=>setLegalName(event.target.value)}/></FormField>:null}
   <FormField label="الهاتف"><Input value={phone} onChange={event=>setPhone(event.target.value)}/></FormField><FormField label="واتساب"><Input value={wa} onChange={event=>setWa(event.target.value)}/></FormField><FormField label="البريد الإلكتروني"><Input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></FormField><FormField label="العنوان"><Textarea value={address} onChange={event=>setAddress(event.target.value)}/></FormField>{kind==='PERSON'?<FormField label="الرقم القومي / الهوية"><Input value={nationalId} onChange={event=>setNationalId(event.target.value)}/></FormField>:<FormField label="الرقم الضريبي"><Input value={taxId} onChange={event=>setTaxId(event.target.value)}/></FormField>}
   <FormField label="مصدر العميل المحتمل" required><Input required value={source} onChange={event=>setSource(event.target.value)}/></FormField><FormField label="الخدمة المطلوبة"><Input value={service} onChange={event=>setService(event.target.value)}/></FormField><FormField label="القيمة المتوقعة"><Input inputMode="decimal" value={expected} onChange={event=>setExpected(event.target.value)}/></FormField>{expected?<FormField label="العملة"><Input value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField>:null}
   <FormField label="المسؤول"><Select value={responsible} onChange={event=>setResponsible(event.target.value)}><option value="">بدون مسؤول محدد</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField><FormField label="المندوب المحيل"><Select value={referralAgent} onChange={event=>setReferralAgent(event.target.value)}><option value="">بدون مندوب محيل</option>{agents.map(value=><option key={value.agent.id} value={value.agent.id}>{value.agent.number} — {value.party.displayName}</option>)}</Select></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></FormField>
   <Button type="submit">{editing?'حفظ التعديل':'حفظ العميل المحتمل'}</Button>{editing?<Button type="button" onClick={reset}>إلغاء</Button>:null}
  </form>{notice?<p role="status">{notice}</p>:null}</DisclosureCard>
  <Card title="مسار المبيعات">{error?<ErrorState message={error}/>:!list.length?<EmptyState/>:<DataGrid columns={['الرقم','العميل المحتمل','المصدر','القيمة','المسؤول','المرحلة','الإجراءات']}>{list.map(value=><tr key={value.id}><td>{value.number}</td><td><strong>{value.displayName}</strong><br/><small>{value.phone??value.email??'—'}</small></td><td>{value.source}</td><td>{value.expectedValue?`${value.expectedValue} ${value.currency??''}`:'—'}</td><td>{users.find(user=>user.id===value.responsibleUserId)?userLabel(users.find(user=>user.id===value.responsibleUserId)!):'—'}</td><td><Badge tone={tone(value.status)}>{leadLabels[value.status]}</Badge>{value.lostReason?<><br/><small>{value.lostReason}</small></>:null}</td><td><details><summary>الإجراءات</summary><div><Button onClick={()=>edit(value)}>تعديل</Button><Button onClick={()=>void showHistory(value)}>السجل</Button><Button onClick={()=>whatsapp(value.whatsappNumber??value.phone)} disabled={!value.whatsappNumber&&!value.phone}>واتساب</Button>{value.status==='NEW'?<Button onClick={()=>void transition(value.id,'contacted')}>تم التواصل</Button>:null}{value.status==='CONTACTED'?<Button onClick={()=>void transition(value.id,'qualified')}>تأهيل</Button>:null}{value.status==='QUALIFIED'?<Button onClick={()=>go(`/crm/quotations?leadId=${encodeURIComponent(value.id)}`)}>إنشاء عرض سعر</Button>:null}{value.status==='QUOTED'?<Button onClick={()=>void convert(value.id)}>تحويل إلى عميل</Button>:null}{value.status==='LOST'?<Button onClick={()=>void transition(value.id,'reopen')}>إعادة فتح</Button>:value.status!=='WON'?<Button onClick={()=>{setLosingId(value.id);setLostReason('');}}>تسجيل كمفقود</Button>:null}<Button onClick={()=>go(`/crm/followups?leadId=${encodeURIComponent(value.id)}`)}>متابعة</Button></div></details></td></tr>)}</DataGrid>}</Card>
  {losingId?<Card title="سبب فقد العميل المحتمل"><FormField label="السبب" required><Textarea value={lostReason} onChange={event=>setLostReason(event.target.value)}/></FormField><Button onClick={()=>void lose(losingId)} disabled={!lostReason.trim()}>تأكيد الفقد</Button><Button onClick={()=>{setLosingId('');setLostReason('');}}>إلغاء</Button></Card>:null}
  {historyLead?<Card title={`سجل ${historyLead.number} — ${historyLead.displayName}`}>{!history.length?<EmptyState/>:<DataGrid columns={['الحدث','من','إلى','التفصيل','الوقت']}>{history.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.fromStatus?leadLabels[item.fromStatus]: '—'}</td><td>{item.toStatus?leadLabels[item.toStatus]:'—'}</td><td>{item.detail??'—'}</td><td>{new Date(item.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>:null}
 </section>;
}

export function FollowupsPage(){
 const[leads,setLeads]=useState<Lead[]>([]),[users,setUsers]=useState<UserOption[]>([]),[rows,setRows]=useState<Followup[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[lead,setLead]=useState(()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('leadId')??''),[responsible,setResponsible]=useState(''),[interactionType,setInteractionType]=useState('CALL'),[scheduledAt,setScheduledAt]=useState(''),[nextAction,setNextAction]=useState('');
 const[mode,setMode]=useState<'due'|'overdue'>('due'),[through,setThrough]=useState(defaultThrough),[responsibleFilter,setResponsibleFilter]=useState(''),[selectedLead,setSelectedLead]=useState(()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('leadId')??''),[leadTimeline,setLeadTimeline]=useState<Followup[]>([]);
 const[completeId,setCompleteId]=useState(''),[outcome,setOutcome]=useState(''),[completionNextAction,setCompletionNextAction]=useState(''),[nextScheduledAt,setNextScheduledAt]=useState(''),[nextInteraction,setNextInteraction]=useState('CALL'),[nextResponsible,setNextResponsible]=useState('');
 const[rescheduleId,setRescheduleId]=useState(''),[rescheduledAt,setRescheduledAt]=useState(''),[cancelId,setCancelId]=useState(''),[cancelReason,setCancelReason]=useState(''),[voidId,setVoidId]=useState(''),[voidReason,setVoidReason]=useState(''),[history,setHistory]=useState<FollowupHistory[]>([]),[historyId,setHistoryId]=useState('');
 async function loadReferences(){try{const[l,u]=await Promise.all([crmGet<Lead[]>('/crm/leads'),crmGet<UserOption[]>('/system-administration/users')]);setLeads(l);setUsers(u.filter(user=>user.active!==false));}catch(value){setError(message(value));}}
 async function loadQueue(){try{const params=new URLSearchParams({...responsibleFilter&&{responsibleUserId:responsibleFilter}});const path=mode==='overdue'?`/crm/followups/overdue?${params}`:`/crm/followups/due?${new URLSearchParams({through:toIso(through),...responsibleFilter&&{responsibleUserId:responsibleFilter}})}`;setRows(await crmGet<Followup[]>(path));setError('');}catch(value){setError(message(value));}}
 async function loadLeadTimeline(id=selectedLead){if(!id){setLeadTimeline([]);return;}try{setLeadTimeline(await crmGet<Followup[]>(`/crm/followups/lead/${encodeURIComponent(id)}`));}catch(value){setNotice(message(value));}}
 useEffect(()=>{void loadReferences();},[]);useEffect(()=>{void loadQueue();},[mode,through,responsibleFilter]);useEffect(()=>{if(selectedLead)void loadLeadTimeline(selectedLead);},[selectedLead]);
 const queueCounts=useMemo(()=>({due:rows.length,late:rows.filter(item=>new Date(item.scheduledAt).getTime()<Date.now()).length}),[rows]);
 async function schedule(event:FormEvent){event.preventDefault();try{await crmPost('/crm/followups',{leadId:lead,responsibleUserId:responsible,interactionType,scheduledAt:toIso(scheduledAt),nextAction:nextAction||undefined});setNotice('تمت جدولة المتابعة.');setScheduledAt('');setNextAction('');await loadQueue();if(selectedLead===lead)await loadLeadTimeline(lead);}catch(value){setNotice(message(value));}}
 async function complete(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${completeId}/complete`,{outcome,nextAction:completionNextAction||undefined,...nextScheduledAt?{nextScheduledAt:toIso(nextScheduledAt),nextInteractionType:nextInteraction,nextResponsibleUserId:nextResponsible||undefined}:{}});setNotice('تم إكمال المتابعة وحفظ النتيجة.');setCompleteId('');setOutcome('');setCompletionNextAction('');setNextScheduledAt('');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function reschedule(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${rescheduleId}/reschedule`,{scheduledAt:toIso(rescheduledAt)});setRescheduleId('');setRescheduledAt('');setNotice('تمت إعادة جدولة المتابعة.');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function cancel(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${cancelId}/cancel`,{reason:cancelReason||undefined});setCancelId('');setCancelReason('');setNotice('تم إلغاء المتابعة مع حفظ السبب.');await loadQueue();await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function voidCompletion(event:FormEvent){event.preventDefault();try{await crmPost(`/crm/followups/${voidId}/void-completion`,{reason:voidReason});setVoidId('');setVoidReason('');setNotice('تم إبطال تسجيل الإكمال كتصحيح مع الاحتفاظ بالتاريخ.');await loadLeadTimeline();}catch(value){setNotice(message(value));}}
 async function showHistory(id:string){try{setHistoryId(id);setHistory(await crmGet<FollowupHistory[]>(`/crm/followups/${id}/history`));}catch(value){setNotice(message(value));}}
 const leadName=(id:string)=>{const value=leads.find(item=>item.id===id);return value?`${value.number} — ${value.displayName}`:id;};const responsibleName=(id:string)=>{const value=users.find(item=>item.id===id);return value?userLabel(value):id;};
 const actionButtons=(value:Followup)=><>{value.status==='SCHEDULED'?<><Button onClick={()=>{setCompleteId(value.id);setOutcome('');setCompletionNextAction(value.nextAction??'');setNextResponsible(value.responsibleUserId);setNextInteraction(value.interactionType);}}>إكمال</Button><Button onClick={()=>{setRescheduleId(value.id);setRescheduledAt(toLocalInput(new Date(value.scheduledAt)));}}>إعادة جدولة</Button><Button onClick={()=>{setCancelId(value.id);setCancelReason('');}}>إلغاء</Button></>:null}{value.status==='COMPLETED'&&!value.completionVoidedAt?<Button onClick={()=>{setVoidId(value.id);setVoidReason('');}}>تصحيح الإكمال</Button>:null}<Button onClick={()=>void showHistory(value.id)}>السجل</Button></>;
 return <section aria-label="إدارة المتابعات" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="المعروضة" value={queueCounts.due}/><MetricCard label="متأخرة ضمن العرض" value={queueCounts.late} tone={queueCounts.late?'warning':'neutral'}/></div>
  <DisclosureCard title="جدولة متابعة" description="اختر العميل المحتمل والمسؤول بدل إدخال المعرفات الداخلية." open={Boolean(lead)}><form onSubmit={schedule}><FormField label="العميل المحتمل" required><Select required value={lead} onChange={event=>setLead(event.target.value)}><option value="">اختر العميل المحتمل</option>{leads.filter(item=>item.status!=='WON'&&item.status!=='LOST').map(item=><option key={item.id} value={item.id}>{item.number} — {item.displayName}</option>)}</Select></FormField><FormField label="المسؤول" required><Select required value={responsible} onChange={event=>setResponsible(event.target.value)}><option value="">اختر المسؤول</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField><FormField label="نوع التواصل"><Select value={interactionType} onChange={event=>setInteractionType(event.target.value)}>{Object.entries(interactionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="الموعد" required><Input required type="datetime-local" value={scheduledAt} onChange={event=>setScheduledAt(event.target.value)}/></FormField><FormField label="الإجراء التالي"><Input value={nextAction} onChange={event=>setNextAction(event.target.value)}/></FormField><Button type="submit">جدولة المتابعة</Button></form>{notice?<p role="status">{notice}</p>:null}</DisclosureCard>
  <Card title="قائمة المتابعات"><div className="ui-filter-row"><Select value={mode} onChange={event=>setMode(event.target.value as 'due'|'overdue')}><option value="due">المستحقة حتى تاريخ</option><option value="overdue">المتأخرة الآن</option></Select>{mode==='due'?<Input type="datetime-local" value={through} onChange={event=>setThrough(event.target.value)}/>:null}<Select value={responsibleFilter} onChange={event=>setResponsibleFilter(event.target.value)}><option value="">كل المسؤولين</option>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></div>{error?<ErrorState message={error}/>:!rows.length?<EmptyState/>:<DataGrid columns={['العميل المحتمل','النوع','المسؤول','الموعد','الحالة','الإجراء التالي','إجراءات']}>{rows.map(value=><tr key={value.id}><td>{leadName(value.leadId)}</td><td>{interactionLabels[value.interactionType]??value.interactionType}</td><td>{responsibleName(value.responsibleUserId)}</td><td>{new Date(value.scheduledAt).toLocaleString('ar-EG')}</td><td><Badge tone={tone(value.status)}>{value.status}</Badge></td><td>{value.nextAction??'—'}</td><td>{actionButtons(value)}</td></tr>)}</DataGrid>}</Card>
  <Card title="سجل متابعات عميل محتمل"><Select value={selectedLead} onChange={event=>setSelectedLead(event.target.value)}><option value="">اختر العميل المحتمل</option>{leads.map(item=><option key={item.id} value={item.id}>{item.number} — {item.displayName}</option>)}</Select>{selectedLead&&!leadTimeline.length?<EmptyState/>:leadTimeline.length?<DataGrid columns={['النوع','المسؤول','الموعد','الحالة','النتيجة','إجراءات']}>{leadTimeline.map(value=><tr key={value.id}><td>{interactionLabels[value.interactionType]??value.interactionType}</td><td>{responsibleName(value.responsibleUserId)}</td><td>{new Date(value.scheduledAt).toLocaleString('ar-EG')}</td><td><Badge tone={tone(value.status)}>{value.status}{value.completionVoidedAt?' — مصحح':''}</Badge></td><td>{value.outcome??'—'}</td><td>{actionButtons(value)}</td></tr>)}</DataGrid>:null}</Card>
  {completeId?<Card title="إكمال المتابعة"><form onSubmit={complete}><FormField label="النتيجة" required><Textarea required value={outcome} onChange={event=>setOutcome(event.target.value)}/></FormField><FormField label="الإجراء التالي"><Input value={completionNextAction} onChange={event=>setCompletionNextAction(event.target.value)}/></FormField><FormField label="موعد متابعة تالية (اختياري)"><Input type="datetime-local" value={nextScheduledAt} onChange={event=>setNextScheduledAt(event.target.value)}/></FormField>{nextScheduledAt?<><FormField label="نوع التواصل التالي"><Select value={nextInteraction} onChange={event=>setNextInteraction(event.target.value)}>{Object.entries(interactionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></FormField><FormField label="المسؤول التالي"><Select value={nextResponsible} onChange={event=>setNextResponsible(event.target.value)}>{users.map(user=><option key={user.id} value={user.id}>{userLabel(user)}</option>)}</Select></FormField></>:null}<Button type="submit">حفظ الإكمال</Button><Button type="button" onClick={()=>setCompleteId('')}>إلغاء</Button></form></Card>:null}
  {rescheduleId?<Card title="إعادة جدولة"><form onSubmit={reschedule}><FormField label="الموعد الجديد" required><Input required type="datetime-local" value={rescheduledAt} onChange={event=>setRescheduledAt(event.target.value)}/></FormField><Button type="submit">حفظ الموعد</Button><Button type="button" onClick={()=>setRescheduleId('')}>إلغاء</Button></form></Card>:null}
  {cancelId?<Card title="إلغاء المتابعة"><form onSubmit={cancel}><FormField label="سبب الإلغاء"><Textarea value={cancelReason} onChange={event=>setCancelReason(event.target.value)}/></FormField><Button type="submit">تأكيد الإلغاء</Button><Button type="button" onClick={()=>setCancelId('')}>رجوع</Button></form></Card>:null}
  {voidId?<Card title="تصحيح إكمال متابعة"><form onSubmit={voidCompletion}><FormField label="سبب التصحيح" required><Textarea required value={voidReason} onChange={event=>setVoidReason(event.target.value)}/></FormField><Button type="submit">تسجيل التصحيح</Button><Button type="button" onClick={()=>setVoidId('')}>إلغاء</Button></form></Card>:null}
  {historyId?<Card title={`تاريخ المتابعة ${historyId}`}>{!history.length?<EmptyState/>:<DataGrid columns={['الحدث','التفصيل','الموعد السابق','الموعد','الوقت']}>{history.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.detail??'—'}</td><td>{item.previousScheduledAt?new Date(item.previousScheduledAt).toLocaleString('ar-EG'):'—'}</td><td>{item.scheduledAt?new Date(item.scheduledAt).toLocaleString('ar-EG'):'—'}</td><td>{new Date(item.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>:null}
 </section>;
}
