import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, EmptyState, ErrorState, FormField, Input, LoadingState, Select } from './ui.js';
import { accountingApi, type AccountingOverview, type InvoiceRow } from './accounting-client.js';

const queryParam=(name:string)=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';
const today=()=>new Date().toISOString().slice(0,10);
const msg=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية المالية.';
export function CrmFinancialActionPage(){
 const action=queryParam('action') as 'invoice'|'receipt'|'advance-refund';
 const partyId=queryParam('partyId');
 const[data,setData]=useState<AccountingOverview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[number,setNumber]=useState(''),[postingDate,setPostingDate]=useState(today()),[dueDate,setDueDate]=useState(today()),[currency,setCurrency]=useState('EGP'),[controlAccountId,setControlAccountId]=useState(''),[revenueAccountId,setRevenueAccountId]=useState(''),[amount,setAmount]=useState(''),[taxCode,setTaxCode]=useState('');
 const[invoiceId,setInvoiceId]=useState(''),[treasuryId,setTreasuryId]=useState('');
 async function load(){setLoading(true);try{setData(await accountingApi.overview());setError('');}catch(value){setError(msg(value));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const customerInvoices=useMemo(()=>data?.invoices.filter(invoice=>invoice.partyId===partyId&&(invoice.type==='CUSTOMER'||invoice.type==='OPENING_CUSTOMER_BALANCE')&&invoice.status==='POSTED'&&invoice.outstanding!=='0')??[],[data,partyId]);
 const selectedInvoice=customerInvoices.find(invoice=>invoice.id===invoiceId);
 const assetAccounts=data?.accounts.filter(account=>account.active&&account.postable&&account.classification==='ASSET')??[];
 const revenueAccounts=data?.accounts.filter(account=>account.active&&account.postable&&account.classification==='REVENUE')??[];
 const treasuries=data?.treasuries.filter(treasury=>treasury.active)??[];
 async function createInvoice(event:FormEvent){event.preventDefault();try{const result=await accountingApi.createInvoice({commandKey:crypto.randomUUID(),type:'CUSTOMER',partyId,number,postingDate,dueDate,currency,controlAccountId,lines:[{accountId:revenueAccountId,amount,...taxCode.trim()?{taxCode:taxCode.trim()}:{}}]});setNotice(`تم إنشاء وترحيل الفاتورة ${result.number}.`);setAmount('');setNumber('');await load();}catch(value){setNotice(msg(value));}}
 async function receive(event:FormEvent){event.preventDefault();if(!selectedInvoice)return;try{const result=await accountingApi.postSettlement({commandKey:crypto.randomUUID(),invoiceId:selectedInvoice.id,treasuryId,number,postingDate,amount});setNotice(`تم ترحيل سند القبض ${result.number}.`);setAmount('');setNumber('');setInvoiceId('');await load();}catch(value){setNotice(msg(value));}}
 if(loading)return <LoadingState label="جارٍ تحميل بيانات المحاسبة…"/>;
 if(error)return <ErrorState message={error}/>;
 if(!partyId)return <ErrorState message="لم يتم تحديد طرف العميل."/>;
 return <section className="ui-page-stack" aria-label="إجراء مالي للعميل"><Card title="إجراء مالي من CRM"><p>طرف العميل: <strong>{partyId}</strong></p><p><small>التنفيذ يتم مباشرة في Billing/Treasury؛ CRM لا يخزن فاتورة أو رصيد أو سند مستقل.</small></p><Button onClick={()=>history.back()}>العودة لملف العميل</Button></Card>
  {action==='invoice'?<Card title="فاتورة مبيعات"><form onSubmit={createInvoice}><FormField label="رقم الفاتورة" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={postingDate} onChange={event=>setPostingDate(event.target.value)}/></FormField><FormField label="تاريخ الاستحقاق" required><Input required type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/></FormField><FormField label="العملة" required><Input required value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField><FormField label="حساب مراقبة العملاء" required><Select required value={controlAccountId} onChange={event=>setControlAccountId(event.target.value)}><option value="">اختر الحساب</option>{assetAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="حساب الإيراد" required><Select required value={revenueAccountId} onChange={event=>setRevenueAccountId(event.target.value)}><option value="">اختر الحساب</option>{revenueAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></FormField><FormField label="كود الضريبة (اختياري)"><Input value={taxCode} onChange={event=>setTaxCode(event.target.value)}/></FormField><Button type="submit">إنشاء وترحيل الفاتورة</Button></form></Card>:null}
  {action==='receipt'?<Card title="سند قبض من العميل">{!customerInvoices.length?<EmptyState title="لا توجد فواتير عميل مفتوحة للتحصيل"/>:<form onSubmit={receive}><FormField label="الفاتورة" required><Select required value={invoiceId} onChange={event=>{const id=event.target.value;setInvoiceId(id);const invoice=customerInvoices.find(item=>item.id===id);if(invoice){setAmount(invoice.outstanding);setCurrency(invoice.currency);}}}><option value="">اختر الفاتورة</option>{customerInvoices.map(invoice=><option key={invoice.id} value={invoice.id}>{invoice.number} — متبقي {invoice.outstanding} {invoice.currency}</option>)}</Select></FormField>{selectedInvoice?<p>الرصيد الحالي: <Badge tone="warning">{selectedInvoice.outstanding} {selectedInvoice.currency}</Badge></p>:null}<FormField label="الخزينة" required><Select required value={treasuryId} onChange={event=>setTreasuryId(event.target.value)}><option value="">اختر الخزينة</option>{treasuries.filter(treasury=>!selectedInvoice||treasury.currency===selectedInvoice.currency).map(treasury=><option key={treasury.id} value={treasury.id}>{treasury.code} — {treasury.name} ({treasury.currency})</option>)}</Select></FormField><FormField label="رقم السند" required><Input required value={number} onChange={event=>setNumber(event.target.value)}/></FormField><FormField label="تاريخ القبض" required><Input required type="date" value={postingDate} onChange={event=>setPostingDate(event.target.value)}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></FormField><Button type="submit">ترحيل سند القبض</Button></form>}</Card>:null}
  {action==='advance-refund'?<Card title="رد مقدم العميل"><p>المقدمات مملوكة لـ Billing. مسار الرد النقدي يحتاج workflow ذريًا بين Billing وTreasury حتى لا يتم تخفيض المقدم بدون خروج النقد أو العكس.</p><p><strong>لن يتم تنفيذ قيد ناقص أو حل مؤقت من CRM.</strong></p></Card>:null}
  {notice?<p role="status">{notice}</p>:null}
 </section>;
}
