import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{ActionBar,Badge,Button,Card,Checkbox,DataGrid,EmptyState,ErrorState,FormField,Input,Select,Tabs,Toast}from'./ui.js';

type Source={code:string;label:string;active:boolean};
type Campaign={id:string;name:string;sourceCode:string|null;active:boolean};
type Stage={key:string;label:string;baseStatus:'NEW'|'CONTACTED'|'QUALIFIED'|'QUOTED'|'WON'|'LOST';order:number;active:boolean};
type Assignment={id:string;sourceCode:string|null;requestedService:string|null;userIds:string[];nextIndex:number;active:boolean};
type Scoring={id:string;field:'SOURCE'|'SERVICE'|'EXPECTED_VALUE_MIN';value:string;points:number;active:boolean};
type Config={sources:Source[];campaigns:Campaign[];pipelineStages:Stage[];assignmentRules:Assignment[];scoringRules:Scoring[];contactSlaMinutes:number;updatedAt?:string};
type Tab='sources'|'campaigns'|'pipeline'|'assignment'|'scoring'|'sla';
const empty:Config={sources:[],campaigns:[],pipelineStages:[],assignmentRules:[],scoringRules:[],contactSlaMinutes:0};
const baseLabels={NEW:'جديد',CONTACTED:'تم التواصل',QUALIFIED:'مؤهل',QUOTED:'عرض سعر',WON:'ناجح',LOST:'مفقود'} as const;
function msg(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}

export function CrmConfigurationPage(){
 const[tab,setTab]=useState<Tab>('sources'),[value,setValue]=useState<Config>(empty),[loading,setLoading]=useState(true),[notice,setNotice]=useState<{tone:'success'|'error';text:string}|null>(null),[error,setError]=useState('');
 async function load(){setLoading(true);try{const c=await crmGet<Config|null>('/crm/leads/configuration');setValue(c?{...empty,...c,sources:[...c.sources],campaigns:[...c.campaigns],pipelineStages:[...c.pipelineStages],assignmentRules:c.assignmentRules.map(r=>({...r,userIds:[...r.userIds]})),scoringRules:[...c.scoringRules]}:empty);setError('');}catch(e){setError(msg(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(event?:FormEvent){event?.preventDefault();setNotice(null);try{const saved=await crmPost<Config>('/crm/leads/configuration',value);setValue({...saved,sources:[...saved.sources],campaigns:[...saved.campaigns],pipelineStages:[...saved.pipelineStages],assignmentRules:saved.assignmentRules.map(r=>({...r,userIds:[...r.userIds]})),scoringRules:[...saved.scoringRules]});setNotice({tone:'success',text:'تم حفظ إعدادات CRM وتطبيقها على إنشاء العملاء المحتملين الجدد.'});}catch(e){setNotice({tone:'error',text:msg(e)});}}
 function patchSource(i:number,p:Partial<Source>){setValue(v=>({...v,sources:v.sources.map((x,n)=>n===i?{...x,...p}:x)}));}
 function patchCampaign(i:number,p:Partial<Campaign>){setValue(v=>({...v,campaigns:v.campaigns.map((x,n)=>n===i?{...x,...p}:x)}));}
 function patchStage(i:number,p:Partial<Stage>){setValue(v=>({...v,pipelineStages:v.pipelineStages.map((x,n)=>n===i?{...x,...p}:x)}));}
 function patchAssignment(i:number,p:Partial<Assignment>){setValue(v=>({...v,assignmentRules:v.assignmentRules.map((x,n)=>n===i?{...x,...p}:x)}));}
 function patchScoring(i:number,p:Partial<Scoring>){setValue(v=>({...v,scoringRules:v.scoringRules.map((x,n)=>n===i?{...x,...p}:x)}));}
 if(loading)return <Card title="إعداد CRM"><p>جارٍ التحميل…</p></Card>;
 return <section dir="rtl" className="ui-page-stack" aria-label="إعداد CRM">
  {notice?<Toast tone={notice.tone}>{notice.text}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="إعداد CRM"><p>مصادر العملاء المحتملين والحملات ومراحل الـPipeline والتوزيع الآلي وScoring وSLA. الإعدادات فرعية حسب الفرع حتى لا تختلط فرق المبيعات.</p><Tabs tabs={[{id:'sources',label:'المصادر'},{id:'campaigns',label:'الحملات'},{id:'pipeline',label:'Pipeline'},{id:'assignment',label:'التوزيع'},{id:'scoring',label:'Scoring'},{id:'sla',label:'SLA'}]} active={tab} onChange={id=>setTab(id as Tab)}/></Card>
  {tab==='sources'?<Card title="مصادر العملاء المحتملين">{!value.sources.length?<EmptyState title="لا توجد مصادر معرفة"/>:<DataGrid columns={['الكود','الاسم','الحالة','إجراء']}>{value.sources.map((x,i)=><tr key={i}><td><Input value={x.code} onChange={e=>patchSource(i,{code:e.target.value.toUpperCase()})}/></td><td><Input value={x.label} onChange={e=>patchSource(i,{label:e.target.value})}/></td><td><label className="ui-checkbox-field"><Checkbox checked={x.active} onChange={e=>patchSource(i,{active:e.target.checked})}/><span>{x.active?'نشط':'متوقف'}</span></label></td><td><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,sources:v.sources.filter((_,n)=>n!==i)}))}>حذف</Button></td></tr>)}</DataGrid>}<ActionBar><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,sources:[...v.sources,{code:'',label:'',active:true}]}))}>إضافة مصدر</Button><Button type="button" onClick={()=>void save()}>حفظ</Button></ActionBar></Card>:null}
  {tab==='campaigns'?<Card title="الحملات">{!value.campaigns.length?<EmptyState title="لا توجد حملات"/>:<DataGrid columns={['الاسم','المصدر','الحالة','إجراء']}>{value.campaigns.map((x,i)=><tr key={x.id}><td><Input value={x.name} onChange={e=>patchCampaign(i,{name:e.target.value})}/></td><td><Select value={x.sourceCode??''} onChange={e=>patchCampaign(i,{sourceCode:e.target.value||null})}><option value="">كل المصادر</option>{value.sources.map(s=><option key={s.code} value={s.code}>{s.label||s.code}</option>)}</Select></td><td><label className="ui-checkbox-field"><Checkbox checked={x.active} onChange={e=>patchCampaign(i,{active:e.target.checked})}/><span>{x.active?'نشطة':'متوقفة'}</span></label></td><td><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,campaigns:v.campaigns.filter((_,n)=>n!==i)}))}>حذف</Button></td></tr>)}</DataGrid>}<ActionBar><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,campaigns:[...v.campaigns,{id:crypto.randomUUID(),name:'',sourceCode:null,active:true}]}))}>إضافة حملة</Button><Button type="button" onClick={()=>void save()}>حفظ</Button></ActionBar></Card>:null}
  {tab==='pipeline'?<Card title="مراحل Pipeline"><p role="note">كل مرحلة مخصصة ترتبط بحالة أساسية معروفة للنظام حتى تظل دورة العميل المحتمل منضبطة.</p>{!value.pipelineStages.length?<EmptyState title="لا توجد مراحل مخصصة"/>:<DataGrid columns={['المفتاح','الاسم','الحالة الأساسية','الترتيب','الحالة','إجراء']}>{value.pipelineStages.map((x,i)=><tr key={i}><td><Input value={x.key} onChange={e=>patchStage(i,{key:e.target.value.toUpperCase()})}/></td><td><Input value={x.label} onChange={e=>patchStage(i,{label:e.target.value})}/></td><td><Select value={x.baseStatus} onChange={e=>patchStage(i,{baseStatus:e.target.value as Stage['baseStatus']})}>{Object.entries(baseLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></td><td><Input type="number" min="0" value={x.order} onChange={e=>patchStage(i,{order:Number(e.target.value)})}/></td><td><Checkbox checked={x.active} onChange={e=>patchStage(i,{active:e.target.checked})}/></td><td><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,pipelineStages:v.pipelineStages.filter((_,n)=>n!==i)}))}>حذف</Button></td></tr>)}</DataGrid>}<ActionBar><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,pipelineStages:[...v.pipelineStages,{key:'',label:'',baseStatus:'NEW',order:v.pipelineStages.length+1,active:true}]}))}>إضافة مرحلة</Button><Button type="button" onClick={()=>void save()}>حفظ</Button></ActionBar></Card>:null}
  {tab==='assignment'?<Card title="قواعد التوزيع الآلي"><p>يتم اختيار المستخدمين Round-Robin داخل كل قاعدة مطابقة.</p>{!value.assignmentRules.length?<EmptyState title="لا توجد قواعد توزيع"/>:<DataGrid columns={['المصدر','الخدمة','المستخدمون','المؤشر','الحالة','إجراء']}>{value.assignmentRules.map((x,i)=><tr key={x.id}><td><Select value={x.sourceCode??''} onChange={e=>patchAssignment(i,{sourceCode:e.target.value||null})}><option value="">أي مصدر</option>{value.sources.map(s=><option key={s.code} value={s.code}>{s.label||s.code}</option>)}</Select></td><td><Input value={x.requestedService??''} onChange={e=>patchAssignment(i,{requestedService:e.target.value||null})}/></td><td><Input value={x.userIds.join(', ')} onChange={e=>patchAssignment(i,{userIds:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})} placeholder="user-1, user-2"/></td><td>{x.nextIndex}</td><td><Checkbox checked={x.active} onChange={e=>patchAssignment(i,{active:e.target.checked})}/></td><td><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,assignmentRules:v.assignmentRules.filter((_,n)=>n!==i)}))}>حذف</Button></td></tr>)}</DataGrid>}<ActionBar><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,assignmentRules:[...v.assignmentRules,{id:crypto.randomUUID(),sourceCode:null,requestedService:null,userIds:[],nextIndex:0,active:true}]}))}>إضافة قاعدة</Button><Button type="button" onClick={()=>void save()}>حفظ</Button></ActionBar></Card>:null}
  {tab==='scoring'?<Card title="قواعد Scoring">{!value.scoringRules.length?<EmptyState title="لا توجد قواعد Scoring"/>:<DataGrid columns={['الحقل','القيمة','النقاط','الحالة','إجراء']}>{value.scoringRules.map((x,i)=><tr key={x.id}><td><Select value={x.field} onChange={e=>patchScoring(i,{field:e.target.value as Scoring['field']})}><option value="SOURCE">المصدر</option><option value="SERVICE">الخدمة</option><option value="EXPECTED_VALUE_MIN">حد أدنى للقيمة المتوقعة</option></Select></td><td><Input value={x.value} onChange={e=>patchScoring(i,{value:e.target.value})}/></td><td><Input type="number" min="-1000" max="1000" value={x.points} onChange={e=>patchScoring(i,{points:Number(e.target.value)})}/></td><td><Checkbox checked={x.active} onChange={e=>patchScoring(i,{active:e.target.checked})}/></td><td><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,scoringRules:v.scoringRules.filter((_,n)=>n!==i)}))}>حذف</Button></td></tr>)}</DataGrid>}<ActionBar><Button type="button" variant="secondary" onClick={()=>setValue(v=>({...v,scoringRules:[...v.scoringRules,{id:crypto.randomUUID(),field:'SOURCE',value:'',points:0,active:true}]}))}>إضافة قاعدة</Button><Button type="button" onClick={()=>void save()}>حفظ</Button></ActionBar></Card>:null}
  {tab==='sla'?<Card title="SLA التواصل الأول"><form onSubmit={save}><FormField label="مهلة التواصل بالدقائق" hint="0 يعني عدم فرض SLA افتراضي"><Input type="number" min="0" max="525600" value={value.contactSlaMinutes} onChange={e=>setValue(v=>({...v,contactSlaMinutes:Number(e.target.value)}))}/></FormField><p>القيمة الحالية: {value.contactSlaMinutes?Math.round(value.contactSlaMinutes/60*10)/10+' ساعة':'غير مفعّل'}</p><Button type="submit">حفظ SLA</Button></form></Card>:null}
 </section>;
}
