import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, MetricCard, Select, Textarea } from './ui.js';
import { crmDelete, crmGet, crmPatch, crmPost } from './crm-core-client.js';

type PartyKind='PERSON'|'ORGANIZATION';
type Party={id:string;kind:PartyKind;displayName:string;legalName:string|null;phone:string|null;email:string|null;whatsappNumber:string|null;address:string|null;nationalIdentity:string|null;taxIdentity:string|null};
type Customer={id:string;number:string;status:'ACTIVE'|'SUSPENDED';assignedAgentId:string|null;commercialNotes:string|null};
type CustomerView={customer:Customer;party:Party};
type CustomerWorkspaceView=CustomerView&{financialSummaryByCurrency:Array<{currency:string;documentTotal:string;outstanding:string}>;openPositionCount:number;overduePositionCount:number;hasOutstanding:boolean};
type AgentView={agent:{id:string;number:string;status:'ACTIVE'|'SUSPENDED'};party:{displayName:string}};
type DuplicateCandidate={party:Party;evidence:string[]};
type CustomerCreateResult={status:'CREATED'|'EXISTING'|'EXISTING_SUSPENDED'|'REVIEW_REQUIRED';value?:CustomerView;candidates?:DuplicateCandidate[]};

const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const tone=(status:string)=>status==='ACTIVE'?'success':'warning';
function useLoad<T>(path:string){const[data,setData]=useState<T|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0);useEffect(()=>{let alive=true;crmGet<T>(path).then(value=>{if(alive){setData(value);setError('');}}).catch(error=>{if(alive)setError(message(error));});return()=>{alive=false;};},[path,version]);return{data,error,reload:()=>setVersion(value=>value+1)};}
function open(path:string){window.location.href=path;}
function whatsapp(phone:string|null){if(!phone)return;const normalized=phone.replace(/[^0-9]/g,'');if(normalized)window.open(`https://wa.me/${normalized}`,'_blank','noopener,noreferrer');}
function accountingAction(action:'receipt'|'invoice'|'advance-refund',partyId:string){open(`/crm/financial-action?action=${action}&partyKind=CUSTOMER&partyId=${encodeURIComponent(partyId)}`);}
function financialText(value:CustomerWorkspaceView|undefined){if(!value?.financialSummaryByCurrency.length)return '—';return value.financialSummaryByCurrency.filter(item=>item.outstanding!=='0').map(item=>`${item.outstanding} ${item.currency}`).join(' | ')||'مسدد';}

export function CustomersPage(){
 const[query,setQuery]=useState(''),[status,setStatus]=useState(''),[editing,setEditing]=useState<CustomerView|null>(null),[kind,setKind]=useState<PartyKind>('PERSON'),[name,setName]=useState(''),[legalName,setLegalName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[whatsappNumber,setWhatsappNumber]=useState(''),[address,setAddress]=useState(''),[nationalIdentity,setNationalIdentity]=useState(''),[taxIdentity,setTaxIdentity]=useState(''),[notes,setNotes]=useState(''),[assignedAgentId,setAssignedAgentId]=useState(''),[notice,setNotice]=useState('');
 const path=useMemo(()=>`/crm/customers?${new URLSearchParams({...status&&{status},...query&&{q:query}})}`,[query,status]);
 const list=useLoad<CustomerView[]>(path),all=useLoad<CustomerView[]>('/crm/customers'),agents=useLoad<AgentView[]>('/crm/agents?status=ACTIVE'),financial=useLoad<CustomerWorkspaceView[]>('/crm/insights/customers');
 const totals=useMemo(()=>({total:all.data?.length??0,active:all.data?.filter(v=>v.customer.status==='ACTIVE').length??0,suspended:all.data?.filter(v=>v.customer.status==='SUSPENDED').length??0,outstanding:financial.data?.filter(v=>v.hasOutstanding).length??0,overdue:financial.data?.filter(v=>v.overduePositionCount>0).length??0}),[all.data,financial.data]);
 const financialByCustomer=useMemo(()=>new Map((financial.data??[]).map(value=>[value.customer.id,value])),[financial.data]);
 function reload(){list.reload();all.reload();financial.reload();}
 function reset(){setEditing(null);setKind('PERSON');setName('');setLegalName('');setPhone('');setEmail('');setWhatsappNumber('');setAddress('');setNationalIdentity('');setTaxIdentity('');setNotes('');setAssignedAgentId('');}
 function edit(v:CustomerView){setEditing(v);setKind(v.party.kind);setName(v.party.displayName);setLegalName(v.party.legalName??'');setPhone(v.party.phone??'');setEmail(v.party.email??'');setWhatsappNumber(v.party.whatsappNumber??'');setAddress(v.party.address??'');setNationalIdentity(v.party.nationalIdentity??'');setTaxIdentity(v.party.taxIdentity??'');setNotes(v.customer.commercialNotes??'');setAssignedAgentId(v.customer.assignedAgentId??'');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(event:FormEvent){event.preventDefault();setNotice('');const party={kind,displayName:name,...legalName&&{legalName},...phone&&{phone},...whatsappNumber&&{whatsappNumber},...email&&{email},...address&&{address},...nationalIdentity&&{nationalIdentity},...taxIdentity&&{taxIdentity}};const body={party,assignedAgentId:assignedAgentId||null,commercialNotes:notes};try{if(editing){await crmPatch(`/crm/customers/${editing.customer.id}`,body);setNotice('تم تحديث بيانات العميل.');}else{const result=await crmPost<CustomerCreateResult>('/crm/customers',body);if(result.status==='REVIEW_REQUIRED'){const names=result.candidates?.map(candidate=>`${candidate.party.displayName} (${candidate.evidence.join('، ')})`).join(' — ');setNotice(`يوجد تطابق محتمل ويجب مراجعته قبل إنشاء سجل جديد${names?`: ${names}`:''}.`);return;}setNotice(result.status==='EXISTING'?'تم ربط البيانات بسجل العميل الموجود دون إنشاء تكرار.':result.status==='EXISTING_SUSPENDED'?'العميل موجود لكنه معلّق؛ لم يتم إنشاء نسخة مكررة.':'تم إنشاء العميل بنجاح.');}reset();reload();}catch(error){setNotice(message(error));}}
 async function lifecycle(id:string,action:'suspend'|'reactivate'){try{await crmPost(`/crm/customers/${id}/${action}`,{});setNotice(action==='suspend'?'تم تعليق العميل.':'تم إعادة تنشيط العميل.');reload();}catch(error){setNotice(message(error));}}
 async function remove(id:string){if(!window.confirm('الحذف الآمن متاح فقط للعميل المعلّق وغير المرتبط بأي عمليات. متابعة؟'))return;try{await crmDelete(`/crm/customers/${id}`);setNotice('تم الحذف الآمن للعميل.');reload();}catch(error){setNotice(message(error));}}
 return <section aria-label="إدارة العملاء" className="ui-dashboard">
  <div className="ui-metric-grid" aria-label="مؤشرات العملاء"><MetricCard label="إجمالي العملاء" value={totals.total}/><MetricCard label="نشط" value={totals.active} tone="success"/><MetricCard label="عليهم مستحقات" value={totals.outstanding} tone={totals.outstanding?'warning':'neutral'}/><MetricCard label="لديهم متأخرات" value={totals.overdue} tone={totals.overdue?'warning':'neutral'}/><MetricCard label="موقوف / معلّق" value={totals.suspended} tone={totals.suspended?'warning':'neutral'}/></div>
  <Card title="العملاء"><div className="ui-filter-row"><Input aria-label="بحث العملاء" placeholder="بحث بالاسم أو الهاتف أو الرقم أو الهوية" value={query} onChange={event=>setQuery(event.target.value)}/><Select aria-label="حالة العميل" value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل الحالات</option><option value="ACTIVE">نشط</option><option value="SUSPENDED">معلّق</option></Select></div>{financial.error?<small>تعذر تحميل المؤشرات المالية أو لا توجد صلاحية قراءة مالية؛ بيانات العميل نفسها ما زالت متاحة.</small>:null}</Card>
  <DisclosureCard title={editing?'تعديل العميل':'إضافة عميل'} description="بيانات الهوية والاتصال تُحفظ في سجل الطرف المركزي، والبيانات التجارية فقط في ملف العميل." open={Boolean(editing)}><form onSubmit={save}>
   <FormField label="نوع العميل" required><Select value={kind} onChange={event=>setKind(event.target.value as PartyKind)}><option value="PERSON">فرد</option><option value="ORGANIZATION">شركة / جهة</option></Select></FormField>
   <FormField label="الاسم" required><Input required value={name} onChange={event=>setName(event.target.value)}/></FormField>
   {kind==='ORGANIZATION'?<FormField label="الاسم القانوني"><Input value={legalName} onChange={event=>setLegalName(event.target.value)}/></FormField>:null}
   <FormField label="الهاتف"><Input value={phone} onChange={event=>setPhone(event.target.value)}/></FormField><FormField label="واتساب"><Input value={whatsappNumber} onChange={event=>setWhatsappNumber(event.target.value)}/></FormField><FormField label="البريد الإلكتروني"><Input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></FormField><FormField label="العنوان"><Textarea value={address} onChange={event=>setAddress(event.target.value)}/></FormField>
   {kind==='PERSON'?<FormField label="الرقم القومي / الهوية"><Input value={nationalIdentity} onChange={event=>setNationalIdentity(event.target.value)}/></FormField>:<FormField label="الرقم الضريبي"><Input value={taxIdentity} onChange={event=>setTaxIdentity(event.target.value)}/></FormField>}
   <FormField label="المندوب المسؤول"><Select value={assignedAgentId} onChange={event=>setAssignedAgentId(event.target.value)}><option value="">بدون مندوب</option>{(agents.data??[]).map(v=><option key={v.agent.id} value={v.agent.id}>{v.agent.number} — {v.party.displayName}</option>)}</Select></FormField>
   <FormField label="ملاحظات تجارية"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></FormField>
   <Button type="submit">{editing?'حفظ التعديل':'حفظ العميل'}</Button>{editing?<Button type="button" onClick={reset}>إلغاء التعديل</Button>:null}
  </form>{notice?<p role="status">{notice}</p>:null}</DisclosureCard>
  <Card title="قائمة العملاء">{list.error?<ErrorState message={list.error}/>:!list.data?.length?<EmptyState/>:<DataGrid columns={['الرقم','العميل','الهاتف','المندوب','المستحقات','الحالة','الإجراءات']}>{list.data.map(v=>{const money=financialByCustomer.get(v.customer.id);return <tr key={v.customer.id}><td>{v.customer.number}</td><td><strong>{v.party.displayName}</strong>{v.party.kind==='ORGANIZATION'?<small> — شركة</small>:null}</td><td>{v.party.phone??'—'}</td><td>{v.customer.assignedAgentId?(agents.data?.find(a=>a.agent.id===v.customer.assignedAgentId)?.party.displayName??v.customer.assignedAgentId):'—'}</td><td>{financialText(money)}{money?.overduePositionCount?<><br/><Badge tone="warning">{money.overduePositionCount} متأخر</Badge></>:null}</td><td><Badge tone={tone(v.customer.status)}>{v.customer.status==='ACTIVE'?'نشط':'معلّق'}</Badge></td><td>
    <details><summary>الإجراءات</summary><div><Button onClick={()=>open(`/crm/quotations?customerId=${encodeURIComponent(v.customer.id)}`)}>عرض سعر</Button><Button onClick={()=>open(`/tourism/services?customerPartyId=${encodeURIComponent(v.party.id)}`)}>خدمة جديدة</Button><Button onClick={()=>accountingAction('receipt',v.party.id)}>سند قبض</Button><Button onClick={()=>accountingAction('invoice',v.party.id)}>فاتورة مبيعات</Button><Button onClick={()=>accountingAction('advance-refund',v.party.id)}>رد مقدم</Button></div></details>
    <details><summary>المزيد</summary><div><Button onClick={()=>open(`/crm/customer-360?customerId=${encodeURIComponent(v.customer.id)}`)}>ملف 360°</Button><Button onClick={()=>edit(v)}>تعديل</Button><Button onClick={()=>open(`/crm/customer-360?customerId=${encodeURIComponent(v.customer.id)}#attachments`)}>المستندات</Button><Button onClick={()=>whatsapp(v.party.whatsappNumber??v.party.phone)} disabled={!v.party.whatsappNumber&&!v.party.phone}>واتساب</Button>{v.customer.status==='ACTIVE'?<Button onClick={()=>lifecycle(v.customer.id,'suspend')}>تعليق</Button>:<><Button onClick={()=>lifecycle(v.customer.id,'reactivate')}>إعادة تنشيط</Button><Button onClick={()=>remove(v.customer.id)}>حذف آمن</Button></>}</div></details>
   </td></tr>})}</DataGrid>}</Card>
 </section>;
}
