import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{ActionBar,Badge,Button,Card,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,Select,Toast}from'./ui.js';

type Requirement={id:string;entityType:string;documentType:string;label:string;required:boolean;expiryRequired:boolean;warningDays:number;active:boolean};
type DocumentRow={id:string;entityType:string;entityId:string;documentType:string;title:string;ownerUserId:string|null;issueDate:string|null;expiryDate:string|null;tags:string[];required:boolean;currentVersion:number;status:'ACTIVE'|'EXPIRED'|'RETIRED';createdAt:string;updatedAt:string};
type Version={id:string;documentId:string;version:number;fileId:string;note:string|null;actorId:string;createdAt:string};
type Uploaded={id:string;contentType:string;size:number};
type FilePayload={metadata:{id:string;contentType:string;size:number};contentBase64:string};
function message(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}
function readBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('تعذر قراءة الملف.'));r.onload=()=>{const value=String(r.result??'');resolve(value.includes(',')?value.slice(value.indexOf(',')+1):value);};r.readAsDataURL(file);});}
function download(payload:FilePayload,name:string){const binary=atob(payload.contentBase64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:payload.metadata.contentType})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function DocumentManagementPage(){
 const[requirements,setRequirements]=useState<Requirement[]>([]),[expiring,setExpiring]=useState<DocumentRow[]>([]),[records,setRecords]=useState<DocumentRow[]>([]),[versions,setVersions]=useState<Version[]>([]),[selected,setSelected]=useState<DocumentRow|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[lookup,setLookup]=useState({entityType:'CUSTOMER',entityId:''}),[req,setReq]=useState({entityType:'CUSTOMER',documentType:'ID',label:'بطاقة الهوية',required:'true',expiryRequired:'false',warningDays:'30'});
 const[form,setForm]=useState({entityType:'CUSTOMER',entityId:'',documentType:'',title:'',issueDate:'',expiryDate:'',tags:'',note:'',fileId:'',fileName:''}),[versionFile,setVersionFile]=useState({fileId:'',fileName:'',note:''});
 async function load(){try{const[r,e]=await Promise.all([crmGet<Requirement[]>('/documents/requirements'),crmGet<DocumentRow[]>('/documents/expiry/upcoming?days=60')]);setRequirements(r);setExpiring(e);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[]);
 async function upload(file:File,version=false){try{const payload=await crmPost<Uploaded>('/documents/files',{contentType:file.type||'application/octet-stream',contentBase64:await readBase64(file)});if(version)setVersionFile(v=>({...v,fileId:payload.id,fileName:file.name}));else setForm(v=>({...v,fileId:payload.id,fileName:file.name}));setNotice('تم رفع الملف إلى التخزين الموثوق وجاهز للربط بالمستند.');}catch(e){setNotice(message(e));}}
 async function saveRequirement(event:FormEvent){event.preventDefault();try{await crmPost('/documents/requirements',{entityType:req.entityType,documentType:req.documentType,label:req.label,required:req.required==='true',expiryRequired:req.expiryRequired==='true',warningDays:Number(req.warningDays),active:true});setNotice('تم حفظ متطلب المستند.');await load();}catch(e){setNotice(message(e));}}
 async function attach(event:FormEvent){event.preventDefault();try{await crmPost('/documents',{entityType:form.entityType,entityId:form.entityId,documentType:form.documentType,title:form.title,fileId:form.fileId,...form.issueDate?{issueDate:form.issueDate}:{},...form.expiryDate?{expiryDate:form.expiryDate}:{},tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),note:form.note});setNotice('تم إرفاق المستند وربط نسخته الأولى بالسجل.');setLookup({entityType:form.entityType,entityId:form.entityId});setForm({entityType:form.entityType,entityId:form.entityId,documentType:'',title:'',issueDate:'',expiryDate:'',tags:'',note:'',fileId:'',fileName:''});await find();await load();}catch(e){setNotice(message(e));}}
 async function find(event?:FormEvent){event?.preventDefault();if(!lookup.entityId.trim())return;try{setRecords(await crmGet<DocumentRow[]>('/documents/record/'+encodeURIComponent(lookup.entityType)+'/'+encodeURIComponent(lookup.entityId)));setError('');}catch(e){setError(message(e));}}
 async function choose(row:DocumentRow){setSelected(row);try{setVersions(await crmGet<Version[]>('/documents/'+row.id+'/versions'));}catch(e){setNotice(message(e));}}
 async function addVersion(event:FormEvent){event.preventDefault();if(!selected)return;try{await crmPost('/documents/'+selected.id+'/versions',{fileId:versionFile.fileId,note:versionFile.note});setVersionFile({fileId:'',fileName:'',note:''});setNotice('تم حفظ نسخة جديدة مع الاحتفاظ بتاريخ النسخ السابقة.');await choose(selected);await find();}catch(e){setNotice(message(e));}}
 async function retire(){if(!selected)return;try{await crmPost('/documents/'+selected.id+'/retire',{});setNotice('تم إلغاء المستند دون حذف تاريخ نسخه.');setSelected(null);await find();await load();}catch(e){setNotice(message(e));}}
 async function downloadVersion(v:Version){try{const payload=await crmGet<FilePayload>('/documents/files/'+v.fileId);download(payload,(selected?.title??'document')+'-v'+v.version);}catch(e){setNotice(message(e));}}
 return <section dir="rtl" className="ui-page-stack" aria-label="إدارة المستندات">
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="إدارة المستندات DMS"><p>مستندات مرتبطة بالسجلات التجارية مع متطلبات، انتهاء صلاحية، نسخ تاريخية، وملفات محفوظة في مخزن المنصة بدل تكرار بيانات الملف داخل الموديولات.</p></Card>
  <div className="ui-grid-md">
   <DisclosureCard title="تعريف متطلب مستند" description="مثال: جواز السفر مطلوب للمسافر وله تاريخ انتهاء."><form onSubmit={saveRequirement}><FormField label="نوع السجل"><Input required value={req.entityType} onChange={e=>setReq({...req,entityType:e.target.value.toUpperCase()})}/></FormField><FormField label="كود المستند"><Input required value={req.documentType} onChange={e=>setReq({...req,documentType:e.target.value.toUpperCase()})}/></FormField><FormField label="الاسم"><Input required value={req.label} onChange={e=>setReq({...req,label:e.target.value})}/></FormField><FormField label="مطلوب؟"><Select value={req.required} onChange={e=>setReq({...req,required:e.target.value})}><option value="true">نعم</option><option value="false">لا</option></Select></FormField><FormField label="له انتهاء صلاحية؟"><Select value={req.expiryRequired} onChange={e=>setReq({...req,expiryRequired:e.target.value})}><option value="false">لا</option><option value="true">نعم</option></Select></FormField><FormField label="التنبيه قبل الانتهاء (يوم)"><Input type="number" min="0" value={req.warningDays} onChange={e=>setReq({...req,warningDays:e.target.value})}/></FormField><Button type="submit">حفظ المتطلب</Button></form></DisclosureCard>
   <Card title="المتطلبات">{!requirements.length?<EmptyState/>:<DataGrid columns={['السجل','المستند','الاسم','إلزامي','انتهاء','تنبيه']}>{requirements.map(r=><tr key={r.id}><td>{r.entityType}</td><td>{r.documentType}</td><td>{r.label}</td><td>{r.required?'نعم':'لا'}</td><td>{r.expiryRequired?'نعم':'لا'}</td><td>{r.warningDays} يوم</td></tr>)}</DataGrid>}</Card>
  </div>
  <DisclosureCard title="إرفاق مستند" description="ارفع الملف أولًا ثم اربطه بالسجل المطلوب."><form onSubmit={attach}><FormField label="نوع السجل" required><Input required value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value.toUpperCase()})}/></FormField><FormField label="معرّف السجل" required><Input required value={form.entityId} onChange={e=>setForm({...form,entityId:e.target.value})}/></FormField><FormField label="نوع المستند" required><Input required value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value.toUpperCase()})}/></FormField><FormField label="العنوان" required><Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></FormField><FormField label="تاريخ الإصدار"><Input type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></FormField><FormField label="تاريخ الانتهاء"><Input type="date" value={form.expiryDate} onChange={e=>setForm({...form,expiryDate:e.target.value})}/></FormField><FormField label="وسوم — مفصولة بفاصلة"><Input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></FormField><FormField label="الملف" required><Input type="file" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/><small>{form.fileName||'لم يتم رفع ملف بعد'}</small></FormField><FormField label="ملاحظة النسخة الأولى"><Input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></FormField><Button type="submit" disabled={!form.fileId}>إرفاق المستند</Button></form></DisclosureCard>
  <Card title="البحث في مستندات سجل"><form onSubmit={find}><FormField label="نوع السجل"><Input value={lookup.entityType} onChange={e=>setLookup({...lookup,entityType:e.target.value.toUpperCase()})}/></FormField><FormField label="معرّف السجل"><Input value={lookup.entityId} onChange={e=>setLookup({...lookup,entityId:e.target.value})}/></FormField><Button type="submit">عرض المستندات</Button></form>{!records.length?<EmptyState title="لا توجد مستندات للسجل المحدد"/>:<DataGrid columns={['العنوان','النوع','الإصدار','الانتهاء','الحالة','فتح']}>{records.map(d=><tr key={d.id}><td>{d.title}</td><td>{d.documentType}</td><td>{d.currentVersion}</td><td>{d.expiryDate??'—'}</td><td><Badge tone={d.status==='ACTIVE'?'success':d.status==='EXPIRED'?'warning':'neutral'}>{d.status}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void choose(d)}>إدارة</Button></td></tr>)}</DataGrid>}</Card>
  <Card title="ينتهي خلال 60 يومًا">{!expiring.length?<EmptyState title="لا توجد مستندات قريبة الانتهاء"/>:<DataGrid columns={['السجل','العنوان','الانتهاء','الحالة']}>{expiring.map(d=><tr key={d.id}><td>{d.entityType} / {d.entityId}</td><td>{d.title}</td><td>{d.expiryDate??'—'}</td><td>{d.status}</td></tr>)}</DataGrid>}</Card>
  {selected?<><Card title={'نسخ '+selected.title}><ActionBar><Button type="button" variant="secondary" onClick={()=>void retire()}>إلغاء المستند</Button></ActionBar>{!versions.length?<EmptyState/>:<DataGrid columns={['الإصدار','الملف','الملاحظة','الوقت','تنزيل']}>{versions.map(v=><tr key={v.id}><td>{v.version}</td><td>{v.fileId}</td><td>{v.note??'—'}</td><td>{new Date(v.createdAt).toLocaleString('ar-EG')}</td><td><Button type="button" variant="secondary" onClick={()=>void downloadVersion(v)}>تنزيل</Button></td></tr>)}</DataGrid>}</Card><DisclosureCard title="إضافة نسخة جديدة" description="تظل النسخ السابقة محفوظة كدليل تاريخي."><form onSubmit={addVersion}><FormField label="الملف" required><Input type="file" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,true);}}/><small>{versionFile.fileName||'لم يتم رفع ملف بعد'}</small></FormField><FormField label="ملاحظة"><Input value={versionFile.note} onChange={e=>setVersionFile({...versionFile,note:e.target.value})}/></FormField><Button type="submit" disabled={!versionFile.fileId}>حفظ النسخة</Button></form></DisclosureCard></>:null}
 </section>;
}
