export type DocumentCatalogKind='DOCUMENT'|'REPORT';
export type DocumentOwner='ACCOUNTING'|'CRM'|'PROCUREMENT'|'HAJJ_UMRAH'|'TOURISM'|'REPORTING';
export interface DocumentCatalogItem{readonly legacyId:string;readonly kind:DocumentCatalogKind;readonly name:string;readonly owner:DocumentOwner;readonly path:string;readonly description:string}

export const documentCatalog:readonly DocumentCatalogItem[]=[
 {legacyId:'LEG-PRINT-001',kind:'DOCUMENT',name:'فاتورة مبيعات',owner:'ACCOUNTING',path:'/accounting',description:'فاتورة العميل من بيانات Billing ودفتر الأستاذ.'},
 {legacyId:'LEG-PRINT-002',kind:'DOCUMENT',name:'فاتورة مورد',owner:'ACCOUNTING',path:'/accounting',description:'فاتورة المورد من Billing/AP بدون إعادة احتساب.'},
 {legacyId:'LEG-PRINT-003',kind:'DOCUMENT',name:'إشعار دائن',owner:'ACCOUNTING',path:'/accounting',description:'تعديل فاتورة مع أثر محاسبي معتمد.'},
 {legacyId:'LEG-PRINT-004',kind:'DOCUMENT',name:'إشعار مدين',owner:'ACCOUNTING',path:'/accounting',description:'تعديل فاتورة مع أثر محاسبي معتمد.'},
 {legacyId:'LEG-PRINT-005',kind:'DOCUMENT',name:'سند قبض',owner:'ACCOUNTING',path:'/accounting',description:'سند قبض من Treasury & Settlement.'},
 {legacyId:'LEG-PRINT-006',kind:'DOCUMENT',name:'سند صرف',owner:'ACCOUNTING',path:'/accounting',description:'سند صرف من Treasury & Settlement.'},
 {legacyId:'LEG-PRINT-007',kind:'DOCUMENT',name:'قيد يومية',owner:'ACCOUNTING',path:'/accounting',description:'قيد من General Ledger.'},
 {legacyId:'LEG-PRINT-008',kind:'DOCUMENT',name:'مستند مصروف',owner:'ACCOUNTING',path:'/accounting',description:'مصروف من Expense/Commission/Recognition.'},
 {legacyId:'LEG-PRINT-009',kind:'DOCUMENT',name:'عرض سعر',owner:'CRM',path:'/crm/quotations',description:'آخر مراجعة معتمدة من عرض السعر.'},
 {legacyId:'LEG-PRINT-010',kind:'DOCUMENT',name:'أمر شراء',owner:'PROCUREMENT',path:'/procurement/purchase-orders',description:'أمر الشراء من Procurement.'},
 {legacyId:'LEG-PRINT-011',kind:'DOCUMENT',name:'تحويل بين الخزن',owner:'ACCOUNTING',path:'/accounting',description:'تحويل خزينة/بنك من Treasury & Settlement.'},
 {legacyId:'LEG-PRINT-012',kind:'DOCUMENT',name:'كشف حساب عميل',owner:'CRM',path:'/crm/customers',description:'كشف حساب العميل من الذمة المحاسبية مع رابط ملف 360°.'},
 {legacyId:'LEG-PRINT-013',kind:'DOCUMENT',name:'كشف حساب مورد',owner:'PROCUREMENT',path:'/procurement/suppliers',description:'كشف حساب المورد من AP مع بيانات المورد.'},
 {legacyId:'LEG-PRINT-014',kind:'DOCUMENT',name:'كشف حساب مندوب',owner:'CRM',path:'/crm/agents',description:'كشف المندوب والعمولات من المالك المحاسبي.'},
 {legacyId:'LEG-PRINT-015',kind:'DOCUMENT',name:'كشف حساب شامل للطرف',owner:'CRM',path:'/crm/customers',description:'عرض موحد للأدوار مع فصل AR/AP/المندوب محاسبيًا.'},
 {legacyId:'LEG-PRINT-016',kind:'DOCUMENT',name:'كشف حركة خزنة / بنك',owner:'ACCOUNTING',path:'/accounting',description:'حركة الخزنة أو البنك من Treasury.'},
 {legacyId:'LEG-PRINT-017',kind:'DOCUMENT',name:'كشف حساب أستاذ',owner:'ACCOUNTING',path:'/accounting',description:'حركة الحساب من General Ledger.'},
 {legacyId:'LEG-PRINT-018',kind:'REPORT',name:'قائمة الدخل',owner:'REPORTING',path:'/management/reports',description:'Financial Reporting.'},
 {legacyId:'LEG-PRINT-019',kind:'REPORT',name:'الميزانية العمومية',owner:'REPORTING',path:'/management/reports',description:'Financial Reporting.'},
 {legacyId:'LEG-PRINT-020',kind:'REPORT',name:'تقرير الضرائب',owner:'REPORTING',path:'/management/reports',description:'Tax reporting.'},
 {legacyId:'LEG-PRINT-021',kind:'REPORT',name:'قائمة التدفقات النقدية',owner:'REPORTING',path:'/management/reports',description:'تقرير مالي مشتق من الأدلة المحاسبية المنشورة.'},
 {legacyId:'LEG-PRINT-022',kind:'REPORT',name:'ربحية برنامج عمرة',owner:'REPORTING',path:'/management/reports',description:'إيراد وتكلفة البرنامج من GL/Cost Center.'},
 {legacyId:'LEG-PRINT-023',kind:'REPORT',name:'كشف توزيع الغرف',owner:'HAJJ_UMRAH',path:'/hajj-umrah/rooming',description:'توزيع الغرف من Rooming owner.'},
 {legacyId:'LEG-PRINT-024',kind:'REPORT',name:'أعمار مديونية العملاء',owner:'REPORTING',path:'/management/reports',description:'Customer aging من Billing/Subledgers.'},
 {legacyId:'LEG-PRINT-025',kind:'REPORT',name:'أعمار مديونية الموردين',owner:'REPORTING',path:'/management/reports',description:'Supplier aging من Billing/Subledgers.'},
 {legacyId:'LEG-PRINT-026',kind:'REPORT',name:'ربحية الخدمات',owner:'REPORTING',path:'/management/reports',description:'ربحية الخدمات من الأدلة المالية والتشغيلية.'},
 {legacyId:'LEG-PRINT-027',kind:'REPORT',name:'تقرير العمولات',owner:'REPORTING',path:'/management/reports',description:'Commission reporting.'},
 {legacyId:'LEG-PRINT-028',kind:'REPORT',name:'تحليل المصروفات',owner:'REPORTING',path:'/management/reports',description:'Expense analysis.'},
 {legacyId:'LEG-PRINT-029',kind:'REPORT',name:'أرباح وخسائر فروق العملة',owner:'REPORTING',path:'/management/reports',description:'FX gains/losses من القيود الفعلية.'},
 {legacyId:'LEG-PRINT-030',kind:'REPORT',name:'التعرض للعملات الأجنبية',owner:'REPORTING',path:'/management/reports',description:'مراكز العملات المفتوحة.'},
 {legacyId:'LEG-PRINT-031',kind:'REPORT',name:'تقرير التحصيلات',owner:'REPORTING',path:'/management/reports',description:'التحصيلات من Treasury/Settlement.'},
 {legacyId:'LEG-PRINT-032',kind:'REPORT',name:'تقرير المدفوعات',owner:'REPORTING',path:'/management/reports',description:'المدفوعات من Treasury/Settlement.'},
 {legacyId:'LEG-PRINT-033',kind:'REPORT',name:'قائمة المسافرين',owner:'HAJJ_UMRAH',path:'/crm/travelers',description:'المسافرون من Traveler Management.'},
 {legacyId:'LEG-PRINT-034',kind:'REPORT',name:'حالات الحجوزات',owner:'HAJJ_UMRAH',path:'/hajj-umrah/bookings',description:'Booking lifecycle وfinancial state.'},
 {legacyId:'LEG-PRINT-035',kind:'REPORT',name:'تقرير القيود',owner:'REPORTING',path:'/management/reports',description:'Journal reporting من GL.'},
 {legacyId:'LEG-PRINT-036',kind:'REPORT',name:'دفتر الأستاذ العام',owner:'REPORTING',path:'/management/reports',description:'General Ledger.'},
 {legacyId:'LEG-PRINT-037',kind:'REPORT',name:'تفاصيل الضرائب',owner:'REPORTING',path:'/management/reports',description:'Tax facts and ledger evidence.'},
 {legacyId:'LEG-PRINT-038',kind:'REPORT',name:'المبيعات حسب العميل',owner:'REPORTING',path:'/management/reports',description:'مبيعات مجمعة حسب العميل من Billing.'},
 {legacyId:'LEG-PRINT-039',kind:'REPORT',name:'المبيعات على المندوبين',owner:'REPORTING',path:'/management/reports',description:'مبيعات وعمولات حسب المندوب.'},
 {legacyId:'LEG-PRINT-040',kind:'REPORT',name:'تكاليف الموردين',owner:'REPORTING',path:'/management/reports',description:'تكاليف حسب المورد من AP/Cost.'},
 {legacyId:'LEG-PRINT-041',kind:'REPORT',name:'الحركة اليومية للخزن والبنوك',owner:'REPORTING',path:'/management/reports',description:'Daily treasury activity.'},
 {legacyId:'LEG-PRINT-042',kind:'REPORT',name:'انتهاء الجوازات',owner:'HAJJ_UMRAH',path:'/crm/travelers',description:'صلاحية وثائق السفر من Traveler Management.'},
 {legacyId:'LEG-PRINT-043',kind:'REPORT',name:'حالات التأشيرات',owner:'HAJJ_UMRAH',path:'/hajj-umrah/visas',description:'Visa operations status.'},
 {legacyId:'LEG-PRINT-044',kind:'REPORT',name:'إشغال برامج العمرة',owner:'HAJJ_UMRAH',path:'/hajj-umrah/programs',description:'السعة والحجوزات من برنامج العمرة.'},
] as const;
