import { type FormEvent, type ReactNode, useEffect, useState } from 'react';
import {
  Badge, Button, Card, DataGrid, Dialog, EmptyState, ErrorState, FormField, Input, LoadingState, Select, Tabs, Textarea, Toast,
} from './ui.js';
import {
  emptyOperationsCapabilities, hajjUmrahOperationsApi,
  type CreateIncidentInput, type CreateTaskInput, type CreateTransportRunInput, type HajjUmrahOperationsApi,
  type Incident, type IncidentStatus, type ManifestAssignment, type OperationTask, type OperationsCapabilities,
  type RecordServiceInput, type ServiceExecution, type TaskStatus, type TicketIssueInput, type TicketRecord, type TicketStatus,
  type TransportRun, type TransportRunStatus,
} from './hajj-umrah-operations-client.js';
import { makeOperationCommandKey } from './hajj-umrah-operations-primary-pages.js';

const errorMessage=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية.';
const ticketLabels:Record<TicketStatus,string>={RESERVED:'محجوز',ISSUED:'صادر',REISSUED:'معاد الإصدار',VOIDED:'مبطل',CANCELLED:'ملغي'};
const runLabels:Record<TransportRunStatus,string>={SCHEDULED:'مجدول',DISPATCHED:'تحرك',COMPLETED:'مكتمل',CANCELLED:'ملغي'};
const taskLabels:Record<TaskStatus,string>={OPEN:'مفتوحة',COMPLETED:'مكتملة',CANCELLED:'ملغاة'};
const incidentLabels:Record<IncidentStatus,string>={OPEN:'مفتوح',RESOLVED:'تم الحل',CANCELLED:'ملغي'};
const statusTone=(status:string)=>status==='ISSUED'||status==='REISSUED'||status==='COMPLETED'||status==='RESOLVED'?'success' as const:status==='CANCELLED'||status==='VOIDED'?'error' as const:status==='DISPATCHED'?'info' as const:'warning' as const;

function PermissionState({allowed,children}:{readonly allowed:boolean;readonly children:ReactNode}){
  return allowed?<>{children}</>:<EmptyState title="لا توجد صلاحية لهذا الجزء"><p>الصلاحية تُحسم من الخادم وفق الشركة والفرع والمستخدم الحالي.</p></EmptyState>;
}

export async function loadTickets(api:HajjUmrahOperationsApi){return api.listTickets();}
export async function loadTransportRuns(api:HajjUmrahOperationsApi){return api.listRuns();}
export async function loadTripOperations(api:HajjUmrahOperationsApi){return Promise.all([api.listTasks(),api.listIncidents(),api.listServices()]);}

export function TicketingPage({api=hajjUmrahOperationsApi}:{readonly api?:HajjUmrahOperationsApi}={}){
  const [rows,setRows]=useState<TicketRecord[]>([]),[cap,setCap]=useState<OperationsCapabilities>(emptyOperationsCapabilities);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [form,setForm]=useState({bookingId:'',travelerId:'',allocationId:'',pnr:'',seat:'',baggage:'',fareClass:''});
  const [selected,setSelected]=useState<TicketRecord|null>(null),[action,setAction]=useState<'issue'|'reissue'|'void'|'cancel'>('issue');
  const [actionForm,setActionForm]=useState({ticketNumber:'',amount:'0',postingDate:'',pnr:'',seat:'',baggage:'',fareClass:'',reason:''});
  async function reload(){setLoading(true);try{const[r,c]=await Promise.all([api.listTickets(),api.capabilities()]);setRows(r);setCap(c);setError('')}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[api]);
  async function reserve(e:FormEvent){e.preventDefault();try{await api.reserveTicket({bookingId:form.bookingId,travelerId:form.travelerId,allocationId:form.allocationId,pnr:form.pnr,...(form.seat?{seat:form.seat}:{}),...(form.baggage?{baggage:form.baggage}:{}),...(form.fareClass?{fareClass:form.fareClass}:{})});setForm({bookingId:'',travelerId:'',allocationId:'',pnr:'',seat:'',baggage:'',fareClass:''});setNotice('تم تسجيل حجز التذكرة من تخصيص الطيران المعتمد.');await reload()}catch(e){setNotice(errorMessage(e))}}
  function open(row:TicketRecord,next:typeof action){setSelected(row);setAction(next);setActionForm({ticketNumber:row.ticketNumber??'',amount:'0',postingDate:'',pnr:row.pnr,seat:row.seat??'',baggage:row.baggage??'',fareClass:row.fareClass??'',reason:''})}
  async function perform(e:FormEvent){e.preventDefault();if(!selected)return;try{
    if(action==='issue'||action==='reissue'){const input:TicketIssueInput={commandKey:makeOperationCommandKey(`ticket-${action}`,selected.id,`${selected.revision}:${actionForm.ticketNumber}:${actionForm.postingDate}`),ticketNumber:actionForm.ticketNumber,amount:actionForm.amount,postingDate:actionForm.postingDate,...(actionForm.pnr?{pnr:actionForm.pnr}:{}),...(actionForm.seat?{seat:actionForm.seat}:{}),...(actionForm.baggage?{baggage:actionForm.baggage}:{}),...(actionForm.fareClass?{fareClass:actionForm.fareClass}:{})};if(action==='issue')await api.issueTicket(selected.id,input);else await api.reissueTicket(selected.id,input)}
    else if(action==='void')await api.voidTicket(selected.id,actionForm.reason);else await api.cancelTicket(selected.id,actionForm.reason);
    setSelected(null);setNotice('تم تحديث حالة التذكرة وحفظ الأثر التشغيلي.');await reload();
  }catch(e){setNotice(errorMessage(e))}}
  return <section aria-label="التذاكر والطيران"><PermissionState allowed={cap.ticketView||loading}>
    {cap.ticketManage&&<Card title="حجز تذكرة"><form onSubmit={reserve}>
      <FormField label="الحجز" required><Input required value={form.bookingId} onChange={e=>setForm({...form,bookingId:e.target.value})}/></FormField>
      <FormField label="المسافر" required><Input required value={form.travelerId} onChange={e=>setForm({...form,travelerId:e.target.value})}/></FormField>
      <FormField label="تخصيص الطيران من TCI" required><Input required value={form.allocationId} onChange={e=>setForm({...form,allocationId:e.target.value})}/></FormField>
      <FormField label="PNR" required><Input required value={form.pnr} onChange={e=>setForm({...form,pnr:e.target.value})}/></FormField>
      <FormField label="المقعد"><Input value={form.seat} onChange={e=>setForm({...form,seat:e.target.value})}/></FormField>
      <FormField label="الأمتعة"><Input value={form.baggage} onChange={e=>setForm({...form,baggage:e.target.value})}/></FormField>
      <FormField label="درجة الحجز"><Input value={form.fareClass} onChange={e=>setForm({...form,fareClass:e.target.value})}/></FormField>
      <Button type="submit">حفظ الحجز</Button>
    </form></Card>}
    <Card title="سجل التذاكر">{loading?<LoadingState/>:error?<ErrorState message={error}/>:!rows.length?<EmptyState title="لا توجد تذاكر"/>:<DataGrid columns={['الحجز','المسافر','PNR','رقم التذكرة','المقعد','الحالة','إجراءات']}>{rows.map(row=><tr key={row.id}><td>{row.bookingId}</td><td>{row.travelerId}</td><td>{row.pnr}</td><td>{row.ticketNumber??'—'}</td><td>{row.seat??'—'}</td><td><Badge tone={statusTone(row.status)}>{ticketLabels[row.status]}</Badge></td><td>
      {cap.ticketIssue&&row.status==='RESERVED'&&<Button type="button" onClick={()=>open(row,'issue')}>إصدار</Button>}
      {cap.ticketIssue&&(row.status==='ISSUED'||row.status==='REISSUED')&&<Button type="button" onClick={()=>open(row,'reissue')}>إعادة إصدار</Button>}
      {cap.ticketManage&&(row.status==='ISSUED'||row.status==='REISSUED')&&<Button type="button" onClick={()=>open(row,'void')}>إبطال</Button>}
      {cap.ticketManage&&!['VOIDED','CANCELLED'].includes(row.status)&&<Button type="button" onClick={()=>open(row,'cancel')}>إلغاء</Button>}
    </td></tr>)}</DataGrid>}</Card>
  </PermissionState>{notice&&<Toast tone={notice.startsWith('تعذر')?'error':'info'}>{notice}</Toast>}
  <Dialog open={Boolean(selected)} title={action==='issue'?'إصدار التذكرة':action==='reissue'?'إعادة إصدار التذكرة':action==='void'?'إبطال التذكرة':'إلغاء التذكرة'} onClose={()=>setSelected(null)}>
    <form onSubmit={perform}>{(action==='issue'||action==='reissue')?<><FormField label="رقم التذكرة" required><Input required value={actionForm.ticketNumber} onChange={e=>setActionForm({...actionForm,ticketNumber:e.target.value})}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={actionForm.amount} onChange={e=>setActionForm({...actionForm,amount:e.target.value})}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={actionForm.postingDate} onChange={e=>setActionForm({...actionForm,postingDate:e.target.value})}/></FormField><FormField label="PNR"><Input value={actionForm.pnr} onChange={e=>setActionForm({...actionForm,pnr:e.target.value})}/></FormField><FormField label="المقعد"><Input value={actionForm.seat} onChange={e=>setActionForm({...actionForm,seat:e.target.value})}/></FormField><FormField label="الأمتعة"><Input value={actionForm.baggage} onChange={e=>setActionForm({...actionForm,baggage:e.target.value})}/></FormField><FormField label="الدرجة"><Input value={actionForm.fareClass} onChange={e=>setActionForm({...actionForm,fareClass:e.target.value})}/></FormField></>:<FormField label="السبب" required><Textarea required value={actionForm.reason} onChange={e=>setActionForm({...actionForm,reason:e.target.value})}/></FormField>}<Button type="submit">حفظ</Button></form>
  </Dialog></section>;
}

export function TransportPage({api=hajjUmrahOperationsApi}:{readonly api?:HajjUmrahOperationsApi}={}){
  const [rows,setRows]=useState<TransportRun[]>([]),[cap,setCap]=useState<OperationsCapabilities>(emptyOperationsCapabilities),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [form,setForm]=useState<CreateTransportRunInput>({programId:'',allocationId:'',code:'',route:'',startsAt:'',endsAt:''});
  const [manifestRun,setManifestRun]=useState<TransportRun|null>(null),[manifest,setManifest]=useState<ManifestAssignment[]>([]),[manifestForm,setManifestForm]=useState({bookingId:'',travelerId:''});
  const [cancelRun,setCancelRun]=useState<TransportRun|null>(null),[cancelReason,setCancelReason]=useState('');
  async function reload(){setLoading(true);try{const[r,c]=await Promise.all([api.listRuns(),api.capabilities()]);setRows(r);setCap(c);setError('')}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[api]);
  async function create(e:FormEvent){e.preventDefault();try{await api.createRun({...form,...(form.vehicleReference?{vehicleReference:form.vehicleReference}:{}),...(form.driverReference?{driverReference:form.driverReference}:{})});setForm({programId:'',allocationId:'',code:'',route:'',startsAt:'',endsAt:''});setNotice('تم إنشاء رحلة النقل من تخصيص النقل المعتمد.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function openManifest(run:TransportRun){setManifestRun(run);try{setManifest(await api.manifest(run.id))}catch(e){setNotice(errorMessage(e))}}
  async function addTraveler(e:FormEvent){e.preventDefault();if(!manifestRun)return;try{await api.assignRun(manifestRun.id,manifestForm.bookingId,manifestForm.travelerId);setManifestForm({bookingId:'',travelerId:''});setManifest(await api.manifest(manifestRun.id));setNotice('تمت إضافة المسافر إلى كشف التفويج.')}catch(e){setNotice(errorMessage(e))}}
  async function removeTraveler(assignmentId:string){if(!manifestRun)return;try{await api.removeRunTraveler(manifestRun.id,assignmentId);setManifest(await api.manifest(manifestRun.id));setNotice('تمت إزالة المسافر من كشف التفويج.')}catch(e){setNotice(errorMessage(e))}}
  async function lifecycle(run:TransportRun,next:'dispatch'|'complete'){try{if(next==='dispatch')await api.dispatchRun(run.id);else await api.completeRun(run.id);setNotice(next==='dispatch'?'تم تسجيل تحرك الرحلة.':'تم إكمال رحلة النقل.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function cancel(e:FormEvent){e.preventDefault();if(!cancelRun)return;try{await api.cancelRun(cancelRun.id,cancelReason);setCancelRun(null);setCancelReason('');setNotice('تم إلغاء رحلة النقل.');await reload()}catch(e){setNotice(errorMessage(e))}}
  return <section aria-label="النقل والتفويج"><PermissionState allowed={cap.transportView||loading}>
    {cap.transportManage&&<Card title="رحلة نقل جديدة"><form onSubmit={create}>
      <FormField label="البرنامج" required><Input required value={form.programId} onChange={e=>setForm({...form,programId:e.target.value})}/></FormField><FormField label="تخصيص النقل من TCI" required><Input required value={form.allocationId} onChange={e=>setForm({...form,allocationId:e.target.value})}/></FormField><FormField label="كود الرحلة" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField><FormField label="المسار" required><Input required value={form.route} onChange={e=>setForm({...form,route:e.target.value})}/></FormField><FormField label="التحرك" required><Input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></FormField><FormField label="الوصول" required><Input required type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></FormField><FormField label="مرجع المركبة"><Input value={form.vehicleReference??''} onChange={e=>setForm({...form,vehicleReference:e.target.value})}/></FormField><FormField label="مرجع السائق"><Input value={form.driverReference??''} onChange={e=>setForm({...form,driverReference:e.target.value})}/></FormField><Button type="submit">إنشاء الرحلة</Button>
    </form></Card>}
    <Card title="رحلات النقل">{loading?<LoadingState/>:error?<ErrorState message={error}/>:!rows.length?<EmptyState title="لا توجد رحلات نقل"/>:<DataGrid columns={['الكود','البرنامج','المسار','التحرك','الحالة','إجراءات']}>{rows.map(run=><tr key={run.id}><td>{run.code}</td><td>{run.programId}</td><td>{run.route}</td><td>{new Date(run.startsAt).toLocaleString('ar-EG')}</td><td><Badge tone={statusTone(run.status)}>{runLabels[run.status]}</Badge></td><td><Button type="button" onClick={()=>void openManifest(run)}>كشف التفويج</Button>{cap.transportDispatch&&run.status==='SCHEDULED'&&<Button type="button" onClick={()=>void lifecycle(run,'dispatch')}>تحرك</Button>}{cap.transportDispatch&&run.status==='DISPATCHED'&&<Button type="button" onClick={()=>void lifecycle(run,'complete')}>إكمال</Button>}{cap.transportManage&&run.status==='SCHEDULED'&&<Button type="button" onClick={()=>setCancelRun(run)}>إلغاء</Button>}</td></tr>)}</DataGrid>}</Card>
  </PermissionState>{notice&&<Toast tone={notice.startsWith('تعذر')?'error':'info'}>{notice}</Toast>}
  <Dialog open={Boolean(manifestRun)} title={manifestRun?'كشف التفويج — '+manifestRun.code:'كشف التفويج'} onClose={()=>setManifestRun(null)}>{cap.transportManage&&<form onSubmit={addTraveler}><FormField label="الحجز" required><Input required value={manifestForm.bookingId} onChange={e=>setManifestForm({...manifestForm,bookingId:e.target.value})}/></FormField><FormField label="المسافر" required><Input required value={manifestForm.travelerId} onChange={e=>setManifestForm({...manifestForm,travelerId:e.target.value})}/></FormField><Button type="submit">إضافة للكشف</Button></form>}{!manifest.length?<EmptyState title="كشف التفويج فارغ"/>:<DataGrid columns={['الحجز','المسافر','الحالة','إجراء']}>{manifest.map(item=><tr key={item.id}><td>{item.bookingId}</td><td>{item.travelerId}</td><td>{item.status==='ASSIGNED'?'مضاف':'تمت الإزالة'}</td><td>{cap.transportManage&&item.status==='ASSIGNED'&&<Button type="button" onClick={()=>void removeTraveler(item.id)}>إزالة</Button>}</td></tr>)}</DataGrid>}</Dialog>
  <Dialog open={Boolean(cancelRun)} title="إلغاء رحلة النقل" onClose={()=>setCancelRun(null)}><form onSubmit={cancel}><FormField label="السبب" required><Textarea required value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/></FormField><Button type="submit">تأكيد الإلغاء</Button></form></Dialog>
  </section>;
}

export function TripOperationsPage({api=hajjUmrahOperationsApi}:{readonly api?:HajjUmrahOperationsApi}={}){
  const [tab,setTab]=useState('tasks'),[cap,setCap]=useState<OperationsCapabilities>(emptyOperationsCapabilities),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [tasks,setTasks]=useState<OperationTask[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[services,setServices]=useState<ServiceExecution[]>([]);
  const [taskForm,setTaskForm]=useState<CreateTaskInput>({programId:'',title:'',dueAt:''});
  const [incidentForm,setIncidentForm]=useState<CreateIncidentInput>({programId:'',severity:'MEDIUM',summary:''});
  const [serviceForm,setServiceForm]=useState<RecordServiceInput>({programId:'',bookingId:'',allocationId:'',category:'MEAL',executedAt:''});
  const [taskCancel,setTaskCancel]=useState<OperationTask|null>(null),[incidentAction,setIncidentAction]=useState<{row:Incident;mode:'resolve'|'cancel'}|null>(null),[reason,setReason]=useState('');
  async function reload(){setLoading(true);try{const[[t,i,s],c]=await Promise.all([loadTripOperations(api),api.capabilities()]);setTasks(t);setIncidents(i);setServices(s);setCap(c);setError('')}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[api]);
  async function createTask(e:FormEvent){e.preventDefault();try{await api.createTask({...taskForm,...(taskForm.bookingId?{bookingId:taskForm.bookingId}:{}),...(taskForm.travelerId?{travelerId:taskForm.travelerId}:{}),...(taskForm.assignedTo?{assignedTo:taskForm.assignedTo}:{})});setTaskForm({programId:'',title:'',dueAt:''});setNotice('تم إنشاء المهمة التشغيلية.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function completeTask(row:OperationTask){try{await api.completeTask(row.id);setNotice('تم إكمال المهمة.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function cancelTask(e:FormEvent){e.preventDefault();if(!taskCancel)return;try{await api.cancelTask(taskCancel.id,reason);setTaskCancel(null);setReason('');setNotice('تم إلغاء المهمة.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function createIncident(e:FormEvent){e.preventDefault();try{await api.createIncident({...incidentForm,...(incidentForm.bookingId?{bookingId:incidentForm.bookingId}:{}),...(incidentForm.travelerId?{travelerId:incidentForm.travelerId}:{}),...(incidentForm.details?{details:incidentForm.details}:{})});setIncidentForm({programId:'',severity:'MEDIUM',summary:''});setNotice('تم تسجيل الحادثة.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function incidentPerform(e:FormEvent){e.preventDefault();if(!incidentAction)return;try{if(incidentAction.mode==='resolve')await api.resolveIncident(incidentAction.row.id,reason);else await api.cancelIncident(incidentAction.row.id,reason);setIncidentAction(null);setReason('');setNotice('تم تحديث الحادثة وحفظ التاريخ.');await reload()}catch(e){setNotice(errorMessage(e))}}
  async function recordService(e:FormEvent){e.preventDefault();try{await api.recordService({...serviceForm,...(serviceForm.travelerId?{travelerId:serviceForm.travelerId}:{}),...(serviceForm.notes?{notes:serviceForm.notes}:{})});setServiceForm({programId:'',bookingId:'',allocationId:'',category:'MEAL',executedAt:''});setNotice('تم تسجيل تنفيذ الخدمة من دليل TCI المعتمد.');await reload()}catch(e){setNotice(errorMessage(e))}}
  return <section aria-label="تشغيل الرحلة"><PermissionState allowed={cap.tripView||loading}>
    <Card title="تشغيل الرحلة"><Tabs tabs={[{id:'tasks',label:'المهام'},{id:'incidents',label:'الحوادث'},{id:'services',label:'تنفيذ الخدمات'}]} active={tab} onChange={setTab}/></Card>
    {loading?<LoadingState/>:error?<ErrorState message={error}/>:tab==='tasks'?<>
      {cap.tripManage&&<Card title="مهمة تشغيلية جديدة"><form onSubmit={createTask}><FormField label="البرنامج" required><Input required value={taskForm.programId} onChange={e=>setTaskForm({...taskForm,programId:e.target.value})}/></FormField><FormField label="الحجز"><Input value={taskForm.bookingId??''} onChange={e=>setTaskForm({...taskForm,bookingId:e.target.value})}/></FormField><FormField label="المسافر"><Input value={taskForm.travelerId??''} onChange={e=>setTaskForm({...taskForm,travelerId:e.target.value})}/></FormField><FormField label="المهمة" required><Input required value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/></FormField><FormField label="المسؤول"><Input value={taskForm.assignedTo??''} onChange={e=>setTaskForm({...taskForm,assignedTo:e.target.value})}/></FormField><FormField label="موعد الاستحقاق" required><Input required type="datetime-local" value={taskForm.dueAt} onChange={e=>setTaskForm({...taskForm,dueAt:e.target.value})}/></FormField><Button type="submit">إنشاء المهمة</Button></form></Card>}
      <Card title="المهام">{!tasks.length?<EmptyState title="لا توجد مهام"/>:<DataGrid columns={['المهمة','البرنامج','الاستحقاق','الحالة','إجراءات']}>{tasks.map(row=><tr key={row.id}><td>{row.title}</td><td>{row.programId}</td><td>{new Date(row.dueAt).toLocaleString('ar-EG')}</td><td><Badge tone={statusTone(row.status)}>{taskLabels[row.status]}</Badge></td><td>{cap.tripManage&&row.status==='OPEN'&&<><Button type="button" onClick={()=>void completeTask(row)}>إكمال</Button><Button type="button" onClick={()=>{setTaskCancel(row);setReason('')}}>إلغاء</Button></>}</td></tr>)}</DataGrid>}</Card>
    </>:tab==='incidents'?<>
      {cap.tripManage&&<Card title="تسجيل حادثة"><form onSubmit={createIncident}><FormField label="البرنامج" required><Input required value={incidentForm.programId} onChange={e=>setIncidentForm({...incidentForm,programId:e.target.value})}/></FormField><FormField label="الحجز"><Input value={incidentForm.bookingId??''} onChange={e=>setIncidentForm({...incidentForm,bookingId:e.target.value})}/></FormField><FormField label="المسافر"><Input value={incidentForm.travelerId??''} onChange={e=>setIncidentForm({...incidentForm,travelerId:e.target.value})}/></FormField><FormField label="الخطورة"><Select value={incidentForm.severity} onChange={e=>setIncidentForm({...incidentForm,severity:e.target.value as Incident['severity']})}><option value="LOW">منخفضة</option><option value="MEDIUM">متوسطة</option><option value="HIGH">عالية</option><option value="CRITICAL">حرجة</option></Select></FormField><FormField label="الملخص" required><Input required value={incidentForm.summary} onChange={e=>setIncidentForm({...incidentForm,summary:e.target.value})}/></FormField><FormField label="التفاصيل"><Textarea value={incidentForm.details??''} onChange={e=>setIncidentForm({...incidentForm,details:e.target.value})}/></FormField><Button type="submit">تسجيل الحادثة</Button></form></Card>}
      <Card title="الحوادث">{!incidents.length?<EmptyState title="لا توجد حوادث"/>:<DataGrid columns={['الملخص','البرنامج','الخطورة','الحالة','إجراءات']}>{incidents.map(row=><tr key={row.id}><td>{row.summary}</td><td>{row.programId}</td><td>{row.severity}</td><td><Badge tone={statusTone(row.status)}>{incidentLabels[row.status]}</Badge></td><td>{cap.tripManage&&row.status==='OPEN'&&<><Button type="button" onClick={()=>{setIncidentAction({row,mode:'resolve'});setReason('')}}>حل</Button><Button type="button" onClick={()=>{setIncidentAction({row,mode:'cancel'});setReason('')}}>إلغاء</Button></>}</td></tr>)}</DataGrid>}</Card>
    </>:<>
      {cap.tripManage&&<Card title="تسجيل تنفيذ خدمة"><form onSubmit={recordService}><FormField label="البرنامج" required><Input required value={serviceForm.programId} onChange={e=>setServiceForm({...serviceForm,programId:e.target.value})}/></FormField><FormField label="الحجز" required><Input required value={serviceForm.bookingId} onChange={e=>setServiceForm({...serviceForm,bookingId:e.target.value})}/></FormField><FormField label="المسافر"><Input value={serviceForm.travelerId??''} onChange={e=>setServiceForm({...serviceForm,travelerId:e.target.value})}/></FormField><FormField label="تخصيص الخدمة من TCI" required><Input required value={serviceForm.allocationId} onChange={e=>setServiceForm({...serviceForm,allocationId:e.target.value})}/></FormField><FormField label="نوع الخدمة"><Select value={serviceForm.category} onChange={e=>setServiceForm({...serviceForm,category:e.target.value as RecordServiceInput['category']})}><option value="CAMP">مخيم</option><option value="MEAL">وجبة</option><option value="VISIT">زيارة</option><option value="GUIDE">إرشاد</option><option value="RAWDA">روضة</option><option value="INSURANCE">تأمين</option></Select></FormField><FormField label="وقت التنفيذ" required><Input required type="datetime-local" value={serviceForm.executedAt} onChange={e=>setServiceForm({...serviceForm,executedAt:e.target.value})}/></FormField><FormField label="ملاحظات"><Textarea value={serviceForm.notes??''} onChange={e=>setServiceForm({...serviceForm,notes:e.target.value})}/></FormField><Button type="submit">تسجيل التنفيذ</Button></form></Card>}
      <Card title="الخدمات المنفذة">{!services.length?<EmptyState title="لا توجد خدمات منفذة"/>:<DataGrid columns={['البرنامج','الحجز','المسافر','الخدمة','وقت التنفيذ']}>{services.map(row=><tr key={row.id}><td>{row.programId}</td><td>{row.bookingId}</td><td>{row.travelerId??'—'}</td><td>{row.category}</td><td>{new Date(row.executedAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>
    </>}
  </PermissionState>{notice&&<Toast tone={notice.startsWith('تعذر')?'error':'info'}>{notice}</Toast>}
  <Dialog open={Boolean(taskCancel)} title="إلغاء المهمة" onClose={()=>setTaskCancel(null)}><form onSubmit={cancelTask}><FormField label="السبب" required><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></FormField><Button type="submit">تأكيد الإلغاء</Button></form></Dialog>
  <Dialog open={Boolean(incidentAction)} title={incidentAction?.mode==='resolve'?'حل الحادثة':'إلغاء الحادثة'} onClose={()=>setIncidentAction(null)}><form onSubmit={incidentPerform}><FormField label={incidentAction?.mode==='resolve'?'الحل':'السبب'} required><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></FormField><Button type="submit">حفظ</Button></form></Dialog>
  </section>;
}
