import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{ActionBar,Badge,Button,Card,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,Select,Textarea,Toast}from'./ui.js';

type Kind='EMAIL'|'WHATSAPP'|'SMS'|'PAYMENT'|'BANK'|'GDS'|'GOVERNMENT'|'EXTERNAL_CRM'|'CLOUD_STORAGE'|'WEBHOOK';
type Connection={id:string;kind:Kind;name:string;enabled:boolean;endpoint:string|null;credentialRef:string|null;config:Record<string,unknown>;createdAt:string;updatedAt:string};
type ApiKey={id:string;actorUserId:string;name:string;keyPrefix:string;scopes:string[];rateLimitPerMinute:number;expiresAt:string|null;revokedAt:string|null;createdAt:string};
type IssueResult={record:ApiKey;secret:string};
type Hook={id:string;event:string;url:string;secretRef:string|null;active:boolean;createdAt:string;updatedAt:string};
type Delivery={id:string;subscriptionId:string;event:string;status:'PENDING'|'SENDING'|'DELIVERED'|'RETRY'|'DEAD_LETTER';attempt:number;maxAttempts:number;nextAttemptAt:string;responseCode:number|null;lastError:string|null;createdAt:string};
function message(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}
function json(text:string){if(!text.trim())return{};try{const value=JSON.parse(text) as unknown;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();return value as Record<string,unknown>;}catch{throw new Error('إعدادات الاتصال يجب أن تكون JSON صحيحًا.');}}

export function IntegrationCenterPage(){
 const[connections,setConnections]=useState<Connection[]>([]),[keys,setKeys]=useState<ApiKey[]>([]),[hooks,setHooks]=useState<Hook[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState(''),[secret,setSecret]=useState('');
 const[conn,setConn]=useState({kind:'EMAIL' as Kind,name:'',endpoint:'',credentialRef:'',config:'{}'}),[keyForm,setKeyForm]=useState({name:'',scopes:'customers.read,quotations.read,tourism.bookings.read,hajj-umrah.bookings.read',rateLimit:'60',expiresAt:''}),[hook,setHook]=useState({event:'*',url:'',secretRef:''});
 async function load(){try{const[c,k,h,d]=await Promise.all([crmGet<Connection[]>('/integrations/connections'),crmGet<ApiKey[]>('/integrations/api-keys'),crmGet<Hook[]>('/integrations/webhooks'),crmGet<Delivery[]>('/integrations/webhooks/deliveries')]);setConnections(c);setKeys(k);setHooks(h);setDeliveries(d);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[]);
 async function saveConnection(event:FormEvent){event.preventDefault();try{await crmPost('/integrations/connections',{kind:conn.kind,name:conn.name,...conn.endpoint?{endpoint:conn.endpoint}:{},...conn.credentialRef?{credentialRef:conn.credentialRef}:{},config:json(conn.config),enabled:true});setConn({kind:'EMAIL',name:'',endpoint:'',credentialRef:'',config:'{}'});setNotice('تم حفظ الاتصال. الأسرار نفسها تظل خارج جداول الأعمال ويُحفظ مرجعها فقط.');await load();}catch(e){setNotice(message(e));}}
 async function test(id:string){try{const result=await crmPost<{ok?:boolean;detail?:string}>('/integrations/connections/'+id+'/test',{});setNotice(result.detail??(result.ok?'نجح اختبار الاتصال.':'تعذر اختبار الاتصال.'));}catch(e){setNotice(message(e));}}
 async function issueKey(event:FormEvent){event.preventDefault();try{const result=await crmPost<IssueResult>('/integrations/api-keys',{name:keyForm.name,scopes:keyForm.scopes.split(',').map(x=>x.trim()).filter(Boolean),rateLimitPerMinute:Number(keyForm.rateLimit),...keyForm.expiresAt?{expiresAt:new Date(keyForm.expiresAt).toISOString()}:{}});setSecret(result.secret);setKeyForm({name:'',scopes:keyForm.scopes,rateLimit:'60',expiresAt:''});setNotice('تم إنشاء المفتاح. انسخه الآن؛ لن يعرض النظام القيمة السرية مرة أخرى.');await load();}catch(e){setNotice(message(e));}}
 async function revoke(id:string){try{await crmPost('/integrations/api-keys/'+id+'/revoke',{});setNotice('تم إلغاء المفتاح.');await load();}catch(e){setNotice(message(e));}}
 async function saveHook(event:FormEvent){event.preventDefault();try{await crmPost('/integrations/webhooks',{event:hook.event,url:hook.url,...hook.secretRef?{secretRef:hook.secretRef}:{},active:true});setHook({event:'*',url:'',secretRef:''});setNotice('تم حفظ Webhook.');await load();}catch(e){setNotice(message(e));}}
 return <section dir="rtl" className="ui-page-stack" aria-label="مركز التكاملات">
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="مركز التكاملات"><p>إدارة قنوات البريد وواتساب وSMS والدفع والبنوك وGDS والجهات الحكومية والتخزين الخارجي، إضافة إلى Public API وWebhooks.</p></Card>
  <DisclosureCard title="اتصال جديد" description="Credential Ref هو مرجع سر محفوظ خارج جداول الأعمال؛ لا تضع كلمات مرور أو مفاتيح خام في حقل الإعدادات."><form onSubmit={saveConnection}><FormField label="النوع"><Select value={conn.kind} onChange={e=>setConn({...conn,kind:e.target.value as Kind})}>{['EMAIL','WHATSAPP','SMS','PAYMENT','BANK','GDS','GOVERNMENT','EXTERNAL_CRM','CLOUD_STORAGE','WEBHOOK'].map(v=><option key={v} value={v}>{v}</option>)}</Select></FormField><FormField label="الاسم" required><Input required value={conn.name} onChange={e=>setConn({...conn,name:e.target.value})}/></FormField><FormField label="Endpoint HTTPS — اختياري"><Input type="url" value={conn.endpoint} onChange={e=>setConn({...conn,endpoint:e.target.value})}/></FormField><FormField label="Credential Ref — اختياري"><Input value={conn.credentialRef} onChange={e=>setConn({...conn,credentialRef:e.target.value})}/></FormField><FormField label="Config JSON"><Textarea value={conn.config} onChange={e=>setConn({...conn,config:e.target.value})}/></FormField><Button type="submit">حفظ الاتصال</Button></form></DisclosureCard>
  <Card title="الاتصالات">{!connections.length?<EmptyState title="لا توجد اتصالات مهيأة"/>:<DataGrid columns={['النوع','الاسم','Endpoint','الحالة','اختبار']}>{connections.map(row=><tr key={row.id}><td>{row.kind}</td><td>{row.name}</td><td>{row.endpoint??'—'}</td><td><Badge tone={row.enabled?'success':'warning'}>{row.enabled?'نشط':'متوقف'}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void test(row.id)}>اختبار</Button></td></tr>)}</DataGrid>}</Card>
  <DisclosureCard title="Public API Key" description="المفتاح يرتبط بالمستخدم الذي أنشأه، ويظل خاضعًا لنفس صلاحيات الشركة والفرع مع Rate Limit."><form onSubmit={issueKey}><FormField label="اسم المفتاح" required><Input required value={keyForm.name} onChange={e=>setKeyForm({...keyForm,name:e.target.value})}/></FormField><FormField label="Scopes — مفصولة بفاصلة" required><Input required value={keyForm.scopes} onChange={e=>setKeyForm({...keyForm,scopes:e.target.value})}/></FormField><FormField label="الحد في الدقيقة"><Input type="number" min="1" max="10000" value={keyForm.rateLimit} onChange={e=>setKeyForm({...keyForm,rateLimit:e.target.value})}/></FormField><FormField label="تاريخ الانتهاء — اختياري"><Input type="datetime-local" value={keyForm.expiresAt} onChange={e=>setKeyForm({...keyForm,expiresAt:e.target.value})}/></FormField><Button type="submit">إنشاء المفتاح</Button></form>{secret?<Card title="القيمة السرية — تظهر مرة واحدة"><Input readOnly value={secret}/><ActionBar><Button type="button" variant="secondary" onClick={()=>void navigator.clipboard.writeText(secret)}>نسخ</Button><Button type="button" variant="secondary" onClick={()=>setSecret('')}>إخفاء</Button></ActionBar></Card>:null}</DisclosureCard>
  <Card title="مفاتيح API">{!keys.length?<EmptyState/>:<DataGrid columns={['الاسم','Prefix','Scopes','Rate Limit','الانتهاء','الحالة','إجراء']}>{keys.map(k=><tr key={k.id}><td>{k.name}</td><td>{k.keyPrefix}</td><td>{k.scopes.join('، ')}</td><td>{k.rateLimitPerMinute}/دقيقة</td><td>{k.expiresAt?new Date(k.expiresAt).toLocaleString('ar-EG'):'—'}</td><td>{k.revokedAt?'ملغي':'نشط'}</td><td>{!k.revokedAt?<Button type="button" variant="secondary" onClick={()=>void revoke(k.id)}>إلغاء</Button>:'—'}</td></tr>)}</DataGrid>}</Card>
  <DisclosureCard title="Webhook جديد" description="العنوان يجب أن يكون HTTPS عامًا. يمكن الاشتراك في حدث محدد أو * لكل الأحداث."><form onSubmit={saveHook}><FormField label="الحدث" required><Input required value={hook.event} onChange={e=>setHook({...hook,event:e.target.value})}/></FormField><FormField label="URL" required><Input required type="url" value={hook.url} onChange={e=>setHook({...hook,url:e.target.value})}/></FormField><FormField label="Secret Ref — اختياري"><Input value={hook.secretRef} onChange={e=>setHook({...hook,secretRef:e.target.value})}/></FormField><Button type="submit">حفظ Webhook</Button></form></DisclosureCard>
  <Card title="Webhooks">{!hooks.length?<EmptyState/>:<DataGrid columns={['الحدث','العنوان','الحالة','آخر تحديث']}>{hooks.map(h=><tr key={h.id}><td>{h.event}</td><td>{h.url}</td><td>{h.active?'نشط':'متوقف'}</td><td>{new Date(h.updatedAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>
  <Card title="تسليمات Webhook">{!deliveries.length?<EmptyState title="لا توجد محاولات تسليم بعد"/>:<DataGrid columns={['الحدث','الحالة','المحاولة','HTTP','المحاولة التالية','الخطأ']}>{deliveries.map(d=><tr key={d.id}><td>{d.event}</td><td><Badge tone={d.status==='DELIVERED'?'success':d.status==='DEAD_LETTER'?'warning':'info'}>{d.status}</Badge></td><td>{d.attempt}/{d.maxAttempts}</td><td>{d.responseCode??'—'}</td><td>{new Date(d.nextAttemptAt).toLocaleString('ar-EG')}</td><td>{d.lastError??'—'}</td></tr>)}</DataGrid>}</Card>
 </section>;
}
