import{useEffect,useState,type FormEvent}from'react';
import{ActionBar,Badge,Button,Card,Checkbox,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,LoadingState,Select,Tabs,Toast}from'./ui.js';
import{HttpPlatformFoundationsClient,type PlatformFoundationsClient}from'./platform-foundations-client.js';
import{tenantApiContext}from'./tenant-session.js';

type Tab='custom-fields'|'numbering'|'automation';
interface FieldRow{id:string;entityType:string;key:string;label:string;fieldType:string;required:boolean;active:boolean;options:readonly string[]}
interface NumberingRow{id:string;documentType:string;branchId:string|null;prefixTemplate:string;padding:number;resetPeriod:string;active:boolean}
interface WorkflowRow{id:string;code:string;name:string;triggerEvent:string;status:string;version:number}
interface RunRow{id:string;workflowId:string;triggerEvent:string;status:string;correlationKey:string;currentStep:number;lastError:string|null;createdAt:string}
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function fields(value:readonly unknown[]):FieldRow[]{return value.filter(record).map(v=>({id:String(v.id??''),entityType:String(v.entityType??''),key:String(v.key??''),label:String(v.label??''),fieldType:String(v.fieldType??''),required:Boolean(v.required),active:Boolean(v.active),options:Array.isArray(v.options)?v.options.map(String):[]})).filter(v=>v.id);}
function numbering(value:readonly unknown[]):NumberingRow[]{return value.filter(record).map(v=>({id:String(v.id??''),documentType:String(v.documentType??''),branchId:v.branchId?String(v.branchId):null,prefixTemplate:String(v.prefixTemplate??''),padding:Number(v.padding??0),resetPeriod:String(v.resetPeriod??''),active:Boolean(v.active)})).filter(v=>v.id);}
function workflows(value:readonly unknown[]):WorkflowRow[]{return value.filter(record).map(v=>({id:String(v.id??''),code:String(v.code??''),name:String(v.name??''),triggerEvent:String(v.triggerEvent??''),status:String(v.status??''),version:Number(v.version??0)})).filter(v=>v.id);}
function runs(value:readonly unknown[]):RunRow[]{return value.filter(record).map(v=>({id:String(v.id??''),workflowId:String(v.workflowId??''),triggerEvent:String(v.triggerEvent??''),status:String(v.status??''),correlationKey:String(v.correlationKey??''),currentStep:Number(v.currentStep??0),lastError:v.lastError?String(v.lastError):null,createdAt:String(v.createdAt??'')})).filter(v=>v.id);}
const tabs=[{id:'custom-fields',label:'الحقول المخصصة'},{id:'numbering',label:'ترقيم المستندات'},{id:'automation',label:'الأتمتة وسير العمل'}] as const;
function errorMessage(error:unknown){return error instanceof Error?error.message:'تعذر تنفيذ العملية.'}
function statusTone(status:string){return status==='ACTIVE'||status==='COMPLETED'?'success':status==='DEAD_LETTER'||status==='CANCELLED'?'warning':'info' as const;}

export function PlatformFoundationsPage({initialTab='custom-fields',client=new HttpPlatformFoundationsClient()}:{initialTab?:Tab;client?:PlatformFoundationsClient}={}){
 const context=tenantApiContext(),[tab,setTab]=useState<Tab>(initialTab),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[fieldRows,setFieldRows]=useState<FieldRow[]>([]),[numberRows,setNumberRows]=useState<NumberingRow[]>([]),[workflowRows,setWorkflowRows]=useState<WorkflowRow[]>([]),[runRows,setRunRows]=useState<RunRow[]>([]);
 const[fieldForm,setFieldForm]=useState({entityType:'customer',key:'',label:'',fieldType:'TEXT',required:false,options:''});
 const[numberForm,setNumberForm]=useState({documentType:'INVOICE',branchId:'',prefixTemplate:'INV-{YYYY}-',padding:'6',resetPeriod:'YEARLY'});
 const[workflowForm,setWorkflowForm]=useState({code:'',name:'',triggerEvent:'',conditionPath:'',conditionOperator:'EQ',conditionValue:'',delaySeconds:'',approvalSignal:'',actionType:'NOTIFICATION',recipientUserId:'',notificationType:'automation.notice',webhookEvent:'',webhookPayload:'{}',retryAttempts:'2',backoffSeconds:'60',escalationUserId:''});

 async function load(){
  if(!context.token)return;setLoading(true);setError('');
  try{
   if(tab==='custom-fields')setFieldRows(fields(await client.customFields(context)));
   if(tab==='numbering')setNumberRows(numbering(await client.numberingPolicies(context)));
   if(tab==='automation'){const[data,runData]=await Promise.all([client.workflows(context),client.workflowRuns(context)]);setWorkflowRows(workflows(data));setRunRows(runs(runData));}
  }catch(e){setError(errorMessage(e));}finally{setLoading(false);}
 }
 useEffect(()=>{void load();},[tab,context.token,context.companyId,context.branchId]);

 async function perform(success:string,task:()=>Promise<unknown>){setLoading(true);setError('');setNotice('');try{await task();setNotice(success);await load();}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 async function createField(event:FormEvent){event.preventDefault();await perform('تم إنشاء الحقل المخصص.',()=>client.createCustomField(context,{entityType:fieldForm.entityType,key:fieldForm.key,label:fieldForm.label,fieldType:fieldForm.fieldType,required:fieldForm.required,...(fieldForm.fieldType==='SELECT'?{options:fieldForm.options.split(',').map(v=>v.trim()).filter(Boolean)}:{})}));}
 async function createNumbering(event:FormEvent){event.preventDefault();await perform('تم إنشاء سياسة الترقيم.',()=>client.createNumberingPolicy(context,{documentType:numberForm.documentType,branchId:numberForm.branchId||null,prefixTemplate:numberForm.prefixTemplate,padding:Number(numberForm.padding),resetPeriod:numberForm.resetPeriod}));}
 function parseValue(value:string){const numeric=Number(value);return value!==''&&Number.isFinite(numeric)?numeric:value;}
 async function createWorkflow(event:FormEvent){event.preventDefault();const conditions=workflowForm.conditionPath?[{path:workflowForm.conditionPath,operator:workflowForm.conditionOperator,value:parseValue(workflowForm.conditionValue)}]:[];const steps:Array<Record<string,unknown>>=[];if(Number(workflowForm.delaySeconds)>0)steps.push({kind:'DELAY',seconds:Number(workflowForm.delaySeconds)});if(workflowForm.approvalSignal.trim())steps.push({kind:'APPROVAL',signal:workflowForm.approvalSignal.trim()});if(workflowForm.actionType==='WEBHOOK'){let payload:Record<string,unknown>;try{const parsed=JSON.parse(workflowForm.webhookPayload||'{}') as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();payload=parsed as Record<string,unknown>;}catch{setError('Webhook Payload يجب أن يكون JSON object صحيحًا.');return;}steps.push({kind:'ACTION',action:'integration.webhook',input:{event:workflowForm.webhookEvent,payload}});}else{steps.push({kind:'ACTION',action:'platform.notify',input:{userId:workflowForm.recipientUserId,type:workflowForm.notificationType,payload:{message:'إشعار آلي من منصة الحافظ'}}});}await perform('تم إنشاء سير العمل كمسودة. راجعه ثم فعّله.',()=>client.createWorkflow(context,{code:workflowForm.code,name:workflowForm.name,triggerEvent:workflowForm.triggerEvent,spec:{conditions,steps,retry:{maxAttempts:Number(workflowForm.retryAttempts),backoffSeconds:Number(workflowForm.backoffSeconds),...(workflowForm.escalationUserId?{deadLetterAction:{kind:'ESCALATION',action:'platform.notify',input:{userId:workflowForm.escalationUserId,type:'automation.escalation',payload:{message:'فشل سير عمل ويحتاج تدخلًا'}}}}:{})}}}));}

 return <section dir="rtl" className="ui-page-stack" aria-label="إعدادات المنصة المتقدمة">
  <Card title="إعدادات المنصة المتقدمة"><p>أدوات مركزية قابلة لإعادة الاستخدام داخل كل الأقسام بدون تكرار منطق الأعمال.</p><Tabs tabs={tabs} active={tab} onChange={id=>setTab(id as Tab)}/><ActionBar><Button type="button" variant="secondary" onClick={()=>void load()} disabled={loading}>تحديث</Button></ActionBar></Card>
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}{loading?<LoadingState/>:null}
  {tab==='custom-fields'?<><DisclosureCard title="إنشاء حقل مخصص" description="أضف حقولًا إضافية لملفات الأعمال بدون تعديل جداول الموديولات الأصلية."><form onSubmit={createField}>
   <FormField label="نوع السجل" required><Select value={fieldForm.entityType} onChange={e=>setFieldForm({...fieldForm,entityType:e.target.value})}><option value="customer">عميل</option><option value="supplier">مورد</option><option value="traveler">مسافر</option><option value="booking">حجز</option><option value="quotation">عرض سعر</option></Select></FormField>
   <FormField label="المفتاح" required><Input required value={fieldForm.key} onChange={e=>setFieldForm({...fieldForm,key:e.target.value})} placeholder="مثال: vip_level"/></FormField>
   <FormField label="الاسم الظاهر" required><Input required value={fieldForm.label} onChange={e=>setFieldForm({...fieldForm,label:e.target.value})}/></FormField>
   <FormField label="نوع الحقل"><Select value={fieldForm.fieldType} onChange={e=>setFieldForm({...fieldForm,fieldType:e.target.value})}><option value="TEXT">نص</option><option value="NUMBER">رقم</option><option value="BOOLEAN">نعم / لا</option><option value="DATE">تاريخ</option><option value="SELECT">قائمة اختيار</option></Select></FormField>
   {fieldForm.fieldType==='SELECT'?<FormField label="الاختيارات"><Input value={fieldForm.options} onChange={e=>setFieldForm({...fieldForm,options:e.target.value})} placeholder="VIP, Corporate, Retail"/></FormField>:null}
   <label className="ui-checkbox-field"><Checkbox checked={fieldForm.required} onChange={e=>setFieldForm({...fieldForm,required:e.target.checked})}/><span>حقل إلزامي</span></label><Button type="submit" disabled={loading}>إنشاء الحقل</Button>
  </form></DisclosureCard><Card title="الحقول الحالية">{!fieldRows.length?<EmptyState title="لا توجد حقول مخصصة"/>:<DataGrid columns={['السجل','الحقل','النوع','إلزامي','الحالة','إجراء']}>{fieldRows.map(row=><tr key={row.id}><td>{row.entityType}</td><td>{row.label}<small>{row.key}</small></td><td>{row.fieldType}</td><td>{row.required?'نعم':'لا'}</td><td><Badge tone={row.active?'success':'warning'}>{row.active?'نشط':'متوقف'}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void perform(row.active?'تم إيقاف الحقل.':'تم تفعيل الحقل.',()=>client.updateCustomField(context,row.id,{active:!row.active}))}>{row.active?'إيقاف':'تفعيل'}</Button></td></tr>)}</DataGrid>}</Card></>:null}
  {tab==='numbering'?<><DisclosureCard title="سياسة ترقيم جديدة" description="ترقيم مركزي آمن للمستندات على مستوى الشركة أو فرع محدد."><form onSubmit={createNumbering}>
   <FormField label="نوع المستند" required><Input required value={numberForm.documentType} onChange={e=>setNumberForm({...numberForm,documentType:e.target.value.toUpperCase()})} placeholder="INVOICE"/></FormField>
   <FormField label="معرّف الفرع — اختياري"><Input value={numberForm.branchId} onChange={e=>setNumberForm({...numberForm,branchId:e.target.value})}/></FormField>
   <FormField label="بادئة الرقم"><Input value={numberForm.prefixTemplate} onChange={e=>setNumberForm({...numberForm,prefixTemplate:e.target.value})} placeholder="INV-{YYYY}-"/></FormField>
   <FormField label="عدد خانات التسلسل"><Input inputMode="numeric" value={numberForm.padding} onChange={e=>setNumberForm({...numberForm,padding:e.target.value})}/></FormField>
   <FormField label="إعادة التسلسل"><Select value={numberForm.resetPeriod} onChange={e=>setNumberForm({...numberForm,resetPeriod:e.target.value})}><option value="YEARLY">سنويًا</option><option value="NEVER">مستمر بدون إعادة</option></Select></FormField><Button type="submit" disabled={loading}>حفظ السياسة</Button>
  </form></DisclosureCard><Card title="سياسات الترقيم">{!numberRows.length?<EmptyState title="لا توجد سياسات ترقيم"/>:<DataGrid columns={['المستند','النطاق','النمط','إعادة','الحالة','إجراء']}>{numberRows.map(row=><tr key={row.id}><td>{row.documentType}</td><td>{row.branchId??'كل الفروع'}</td><td>{row.prefixTemplate}{'0'.repeat(Math.min(row.padding,8))}</td><td>{row.resetPeriod==='YEARLY'?'سنوي':'مستمر'}</td><td><Badge tone={row.active?'success':'warning'}>{row.active?'نشط':'متوقف'}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void perform(row.active?'تم إيقاف السياسة.':'تم تفعيل السياسة.',()=>client.updateNumberingPolicy(context,row.id,{active:!row.active}))}>{row.active?'إيقاف':'تفعيل'}</Button></td></tr>)}</DataGrid>}</Card></>:null}
  {tab==='automation'?<><DisclosureCard title="إنشاء أتمتة" description="Trigger → Conditions → Delay/Approval → Action → Retry/Escalation. تُحفظ أولًا كمسودة ولا تعمل حتى تفعيلها."><form onSubmit={createWorkflow}>
   <FormField label="كود سير العمل" required><Input required value={workflowForm.code} onChange={e=>setWorkflowForm({...workflowForm,code:e.target.value.toUpperCase()})} placeholder="INVOICE_DUE_REMINDER"/></FormField>
   <FormField label="الاسم" required><Input required value={workflowForm.name} onChange={e=>setWorkflowForm({...workflowForm,name:e.target.value})}/></FormField>
   <FormField label="حدث التشغيل" required><Input required value={workflowForm.triggerEvent} onChange={e=>setWorkflowForm({...workflowForm,triggerEvent:e.target.value.toLowerCase()})} placeholder="invoice.due"/></FormField>
   <FormField label="مسار شرط اختياري"><Input value={workflowForm.conditionPath} onChange={e=>setWorkflowForm({...workflowForm,conditionPath:e.target.value})} placeholder="amount"/></FormField>
   {workflowForm.conditionPath?<><FormField label="المقارنة"><Select value={workflowForm.conditionOperator} onChange={e=>setWorkflowForm({...workflowForm,conditionOperator:e.target.value})}><option value="EQ">يساوي</option><option value="NE">لا يساوي</option><option value="GT">أكبر من</option><option value="GTE">أكبر أو يساوي</option><option value="LT">أقل من</option><option value="LTE">أقل أو يساوي</option></Select></FormField><FormField label="القيمة"><Input value={workflowForm.conditionValue} onChange={e=>setWorkflowForm({...workflowForm,conditionValue:e.target.value})}/></FormField></>:null}
   <FormField label="تأخير بالثواني — اختياري"><Input inputMode="numeric" value={workflowForm.delaySeconds} onChange={e=>setWorkflowForm({...workflowForm,delaySeconds:e.target.value})}/></FormField>
   <FormField label="إشارة موافقة — اختياري"><Input value={workflowForm.approvalSignal} onChange={e=>setWorkflowForm({...workflowForm,approvalSignal:e.target.value})} placeholder="manager-approved"/></FormField>
   <FormField label="الإجراء"><Select value={workflowForm.actionType} onChange={e=>setWorkflowForm({...workflowForm,actionType:e.target.value})}><option value="NOTIFICATION">إشعار داخل النظام</option><option value="WEBHOOK">Webhook Event</option></Select></FormField>
   {workflowForm.actionType==='WEBHOOK'?<><FormField label="اسم حدث Webhook" required><Input required value={workflowForm.webhookEvent} onChange={e=>setWorkflowForm({...workflowForm,webhookEvent:e.target.value.toLowerCase()})} placeholder="booking.confirmed"/></FormField><FormField label="Webhook Payload JSON"><Input value={workflowForm.webhookPayload} onChange={e=>setWorkflowForm({...workflowForm,webhookPayload:e.target.value})} placeholder='{"source":"workflow"}'/></FormField></>:<><FormField label="المستخدم المستلم للإشعار" required><Input required value={workflowForm.recipientUserId} onChange={e=>setWorkflowForm({...workflowForm,recipientUserId:e.target.value})}/></FormField><FormField label="نوع الإشعار"><Input value={workflowForm.notificationType} onChange={e=>setWorkflowForm({...workflowForm,notificationType:e.target.value})}/></FormField></>}
   <FormField label="عدد محاولات الإعادة"><Input inputMode="numeric" value={workflowForm.retryAttempts} onChange={e=>setWorkflowForm({...workflowForm,retryAttempts:e.target.value})}/></FormField>
   <FormField label="فاصل إعادة المحاولة بالثواني"><Input inputMode="numeric" value={workflowForm.backoffSeconds} onChange={e=>setWorkflowForm({...workflowForm,backoffSeconds:e.target.value})}/></FormField>
   <FormField label="مستخدم التصعيد عند الفشل — اختياري"><Input value={workflowForm.escalationUserId} onChange={e=>setWorkflowForm({...workflowForm,escalationUserId:e.target.value})}/></FormField><Button type="submit" disabled={loading}>حفظ كمسودة</Button>
  </form></DisclosureCard>
  <Card title="تعريفات الأتمتة">{!workflowRows.length?<EmptyState title="لا توجد أتمتة"/>:<DataGrid columns={['الكود','الاسم','الحدث','الإصدار','الحالة','إجراء']}>{workflowRows.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td>{row.triggerEvent}</td><td>{row.version}</td><td><Badge tone={statusTone(row.status)}>{row.status}</Badge></td><td>{row.status==='ACTIVE'?<Button type="button" variant="secondary" onClick={()=>void perform('تم إيقاف سير العمل مؤقتًا.',()=>client.updateWorkflowStatus(context,row.id,'PAUSED'))}>إيقاف مؤقت</Button>:row.status!=='RETIRED'?<><Button type="button" onClick={()=>void perform('تم تفعيل سير العمل.',()=>client.updateWorkflowStatus(context,row.id,'ACTIVE'))}>تفعيل</Button><Button type="button" variant="secondary" onClick={()=>void perform('تم إنهاء سير العمل.',()=>client.updateWorkflowStatus(context,row.id,'RETIRED'))}>إنهاء</Button></>:null}</td></tr>)}</DataGrid>}</Card>
  <Card title="آخر عمليات التنفيذ">{!runRows.length?<EmptyState title="لا توجد عمليات تنفيذ بعد"/>:<DataGrid columns={['الحدث','المفتاح','الحالة','الخطوة','الوقت','ملاحظة']}>{runRows.slice(0,50).map(row=><tr key={row.id}><td>{row.triggerEvent}</td><td>{row.correlationKey}</td><td><Badge tone={statusTone(row.status)}>{row.status}</Badge></td><td>{row.currentStep}</td><td>{row.createdAt?new Date(row.createdAt).toLocaleString('ar-EG'):'—'}</td><td>{row.lastError??'—'}</td></tr>)}</DataGrid>}</Card></>:null}
 </section>;
}
