import{type FormEvent,useEffect,useMemo,useState}from'react';
import{Badge,Button,Card,DataGrid,EmptyState,ErrorState,FormField,Input,Select,Textarea}from'./ui.js';
import{procurementGet,procurementPatch,procurementPost}from'./procurement-client.js';

type SupplierView={supplier:{id:string;supplierCode:string;status:string;approvalStatus:string};party:{id:string;displayName:string}};
type PoLine={id:string;itemReference:string;description?:string;orderedQuantity:string;unitPrice?:string;taxCode?:string;receivedQuantity:string;invoicedQuantity:string};
type PurchaseOrder={id:string;branchId:string;supplierId:string;number:string;origin:string;status:string;orderDate?:string;expectedDate?:string;currency?:string;externalReference?:string;notes?:string;lines:PoLine[]};
type Fulfillment={id:string;kind:string;status:string;lineId:string;requestedQuantity:string;previousReceivedQuantity:string;resultingReceivedQuantity?:string;reason?:string;note?:string;createdAt:string};
type DraftLine={id:string;itemReference:string;description:string;orderedQuantity:string;unitPrice:string;taxCode:string};
const freshLine=():DraftLine=>({id:crypto.randomUUID(),itemReference:'',description:'',orderedQuantity:'1',unitPrice:'0',taxCode:''});
const message=(e:unknown)=>e instanceof Error?e.message:'حدث خطأ غير متوقع';

export function ProcurementOperationsPage(){
 const[rows,setRows]=useState<PurchaseOrder[]>([]),[suppliers,setSuppliers]=useState<SupplierView[]>([]),[selected,setSelected]=useState<PurchaseOrder|null>(null),[evidence,setEvidence]=useState<Fulfillment[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[q,setQ]=useState('');
 const[editingId,setEditingId]=useState<string|null>(null),[supplierId,setSupplierId]=useState(''),[orderDate,setOrderDate]=useState(''),[expectedDate,setExpectedDate]=useState(''),[currency,setCurrency]=useState('EGP'),[externalReference,setExternalReference]=useState(''),[notes,setNotes]=useState(''),[lines,setLines]=useState<DraftLine[]>([freshLine()]);
 const[directSupplier,setDirectSupplier]=useState(''),[directNumber,setDirectNumber]=useState(''),[directExternal,setDirectExternal]=useState(''),[directDate,setDirectDate]=useState(''),[directCurrency,setDirectCurrency]=useState('EGP'),[controlAccount,setControlAccount]=useState(''),[expenseAccount,setExpenseAccount]=useState(''),[directAmount,setDirectAmount]=useState('');

 async function load(){try{const[p,s]=await Promise.all([procurementGet<PurchaseOrder[]>('/procurement/purchase-orders'),procurementGet<SupplierView[]>('/suppliers')]);setRows(p);setSuppliers(s.filter(x=>x.supplier.status==='ACTIVE'&&x.supplier.approvalStatus==='APPROVED'));setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>!q||x.number.toLowerCase().includes(q.toLowerCase())||x.supplierId.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 function patchLine(index:number,patch:Partial<DraftLine>){setLines(v=>v.map((x,i)=>i===index?{...x,...patch}:x));}
 function resetForm(){setEditingId(null);setSupplierId('');setOrderDate('');setExpectedDate('');setCurrency('EGP');setExternalReference('');setNotes('');setLines([freshLine()]);}
 async function choose(po:PurchaseOrder){try{const detail=await procurementGet<PurchaseOrder>(`/procurement/purchase-orders/${po.id}`);setSelected(detail);setEvidence(await procurementGet<Fulfillment[]>(`/procurement/purchase-orders/${po.id}/fulfillments`));}catch(e){setNotice(message(e));}}
 function edit(po:PurchaseOrder){setEditingId(po.id);setSupplierId(po.supplierId);setOrderDate(po.orderDate??'');setExpectedDate(po.expectedDate??'');setCurrency(po.currency??'EGP');setExternalReference(po.externalReference??'');setNotes(po.notes??'');setLines(po.lines.map(x=>({id:x.id,itemReference:x.itemReference,description:x.description??'',orderedQuantity:x.orderedQuantity,unitPrice:x.unitPrice??'0',taxCode:x.taxCode??''})));window.scrollTo({top:0,behavior:'smooth'});}
 async function savePo(e:FormEvent){e.preventDefault();try{const normalized=lines.map(x=>({id:x.id,itemReference:x.itemReference,description:x.description||undefined,orderedQuantity:x.orderedQuantity,unitPrice:x.unitPrice,taxCode:x.taxCode||undefined}));if(editingId){await procurementPatch(`/procurement/purchase-orders/${editingId}`,{commandId:crypto.randomUUID(),supplierId,orderDate,expectedDate:expectedDate||undefined,currency,externalReference:externalReference||undefined,notes:notes||undefined,lines:normalized});setNotice('تم تحديث أمر الشراء Draft.');}else{await procurementPost('/procurement/purchase-orders',{id:crypto.randomUUID(),supplierId,orderDate,expectedDate:expectedDate||undefined,currency,externalReference:externalReference||undefined,notes:notes||undefined,lines:normalized});setNotice('تم إنشاء أمر الشراء Draft.');}resetForm();await load();}catch(e){setNotice(message(e));}}
 async function action(po:PurchaseOrder,name:'approve'|'cancel'){try{let body:Record<string,unknown>={};if(name==='cancel'){const reason=window.prompt('سبب إلغاء أمر الشراء');if(!reason?.trim())return;body={reason:reason.trim()};}await procurementPost(`/procurement/purchase-orders/${po.id}/${name}`,body);setNotice(name==='approve'?'تم اعتماد أمر الشراء.':'تم إلغاء أمر الشراء مع حفظ السبب.');await load();await choose(po);}catch(e){setNotice(message(e));}}
 async function receive(line:PoLine){if(!selected)return;const value=window.prompt('الكمية المنفذة الآن');if(!value)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/fulfillments`,{id:crypto.randomUUID(),lineId:line.id,quantity:value});setNotice('تم تسجيل التنفيذ.');await load();await choose(selected);}catch(e){setNotice(message(e));}}
 async function correct(item:Fulfillment){if(!selected)return;const target=window.prompt('إجمالي الكمية الصحيحة المستلمة الآن',item.resultingReceivedQuantity??item.requestedQuantity);if(target===null)return;const reason=window.prompt('سبب التصحيح');if(!reason)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/fulfillment-corrections`,{id:crypto.randomUUID(),correctionOfId:item.id,lineId:item.lineId,targetReceivedQuantity:target,reason});setNotice('تم تسجيل تصحيح التنفيذ مع الحفاظ على الدليل السابق.');await load();await choose(selected);}catch(e){setNotice(message(e));}}
 async function invoiceLine(line:PoLine){if(!selected)return;const available=String(Number(line.receivedQuantity)-Number(line.invoicedQuantity));if(Number(available)<=0)return;const quantity=window.prompt('الكمية المراد تحويلها إلى فاتورة مورد',available);if(!quantity)return;const number=window.prompt('رقم الفاتورة الداخلي');if(!number)return;const externalInvoiceNumber=window.prompt('رقم فاتورة المورد');if(!externalInvoiceNumber)return;const postingDate=window.prompt('تاريخ القيد YYYY-MM-DD',new Date().toISOString().slice(0,10));if(!postingDate)return;const controlAccountId=window.prompt('حساب الدائنين');if(!controlAccountId)return;const accountId=window.prompt('حساب المصروف/التكلفة');if(!accountId)return;const amount=window.prompt('قيمة الجزء المفوتر');if(!amount)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/lines/${line.id}/supplier-invoices`,{id:crypto.randomUUID(),quantity,billing:{invoiceId:crypto.randomUUID(),number,externalInvoiceNumber,postingDate,currency:selected.currency??'EGP',controlAccountId,accountId,amount}});setNotice('تم إنشاء وترحيل فاتورة المورد من الكمية المنفذة.');await load();await choose(selected);}catch(e){setNotice(message(e));}}
 async function direct(e:FormEvent){e.preventDefault();try{await procurementPost('/procurement/direct-purchases',{id:crypto.randomUUID(),supplierId:directSupplier,invoiceId:crypto.randomUUID(),number:directNumber,externalInvoiceNumber:directExternal,postingDate:directDate,currency:directCurrency,controlAccountId:controlAccount,lines:[{id:crypto.randomUUID(),accountId:expenseAccount,amount:directAmount}]});setNotice('تم ترحيل الشراء المباشر كفاتورة مورد من خلال Billing.');setDirectNumber('');setDirectExternal('');setDirectAmount('');}catch(e){setNotice(message(e));}}
 const supplierOptions=<><option value="">اختر المورد</option>{suppliers.map(s=><option key={s.party.id} value={s.party.id}>{s.supplier.supplierCode} — {s.party.displayName}</option>)}</>;
 return <section aria-label="تشغيل المشتريات">
  <Card title={editingId?'تعديل أمر شراء Draft':'أمر شراء جديد'}><form onSubmit={savePo}><FormField label="المورد" required><Select required value={supplierId} onChange={e=>setSupplierId(e.target.value)}>{supplierOptions}</Select></FormField>${!editingId?<p role="note">رقم أمر الشراء يُنشأ تلقائيًا حسب الشركة والفرع والسنة.</p>:<p role="note">رقم أمر الشراء: {selected?.id===editingId?selected.number:'محفوظ'}</p>}<FormField label="التاريخ" required><Input required type="date" value={orderDate} onChange={e=>setOrderDate(e.target.value)}/></FormField><FormField label="التاريخ المتوقع"><Input type="date" value={expectedDate} onChange={e=>setExpectedDate(e.target.value)}/></FormField><FormField label="العملة" required><Input required value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></FormField><FormField label="مرجع خارجي"><Input value={externalReference} onChange={e=>setExternalReference(e.target.value)}/></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></FormField><h3>البنود</h3>{lines.map((line,index)=><div key={line.id} className="ui-card"><FormField label="البند" required><Input required value={line.itemReference} onChange={e=>patchLine(index,{itemReference:e.target.value})}/></FormField><FormField label="الوصف"><Input value={line.description} onChange={e=>patchLine(index,{description:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={line.orderedQuantity} onChange={e=>patchLine(index,{orderedQuantity:e.target.value})}/></FormField><FormField label="سعر الوحدة" required><Input required inputMode="decimal" value={line.unitPrice} onChange={e=>patchLine(index,{unitPrice:e.target.value})}/></FormField><FormField label="كود الضريبة"><Input value={line.taxCode} onChange={e=>patchLine(index,{taxCode:e.target.value})}/></FormField>{lines.length>1&&<Button type="button" onClick={()=>setLines(v=>v.filter((_,i)=>i!==index))}>حذف البند</Button>}</div>)}<Button type="button" onClick={()=>setLines(v=>[...v,freshLine()])}>إضافة بند</Button><Button type="submit">{editingId?'حفظ التعديل':'إنشاء أمر الشراء'}</Button>{editingId&&<Button type="button" onClick={resetForm}>إلغاء التعديل</Button>}</form></Card>
  {notice&&<p role="status">{notice}</p>}
  <Card title="أوامر الشراء"><Input aria-label="بحث أوامر الشراء" placeholder="بحث بالرقم أو المورد" value={q} onChange={e=>setQ(e.target.value)}/>{error?<ErrorState message={error}/>:!filtered.length?<EmptyState/>:<DataGrid columns={['الرقم','المورد','الحالة','التاريخ','إجراءات']}>{filtered.map(po=><tr key={po.id}><td>{po.number}</td><td>{suppliers.find(s=>s.party.id===po.supplierId)?.party.displayName??po.supplierId}</td><td><Badge tone={po.status==='INVOICED'||po.status==='RECEIVED'?'success':po.status==='CANCELLED'?'error':'warning'}>{po.status}</Badge></td><td>{po.orderDate??'—'}</td><td><Button onClick={()=>void choose(po)}>تفاصيل</Button>{po.status==='DRAFT'&&<Button onClick={()=>edit(po)}>تعديل</Button>}{po.status==='DRAFT'&&<Button onClick={()=>void action(po,'approve')}>اعتماد</Button>}{['DRAFT','APPROVED'].includes(po.status)&&<Button onClick={()=>void action(po,'cancel')}>إلغاء</Button>}</td></tr>)}</DataGrid>}</Card>
  {selected&&<Card title={`أمر الشراء ${selected.number}`}><Button onClick={()=>window.print()}>طباعة</Button><p>الحالة: {selected.status} — العملة: {selected.currency??'—'}</p><DataGrid columns={['البند','المطلوب','المستلم','المفوتر','تنفيذ']}>{selected.lines.map(line=><tr key={line.id}><td>{line.itemReference}</td><td>{line.orderedQuantity}</td><td>{line.receivedQuantity}</td><td>{line.invoicedQuantity}</td><td>{['APPROVED','PARTIALLY_RECEIVED','PARTIALLY_INVOICED'].includes(selected.status)&&<Button onClick={()=>void receive(line)}>تسجيل تنفيذ</Button>}{Number(line.receivedQuantity)>Number(line.invoicedQuantity)&&<Button onClick={()=>void invoiceLine(line)}>فاتورة مورد</Button>}</td></tr>)}</DataGrid><h3>سجل التنفيذ</h3>{!evidence.length?<EmptyState/>:<DataGrid columns={['النوع','البند','قبل','بعد','الحالة','إجراء']}>{evidence.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.lineId}</td><td>{item.previousReceivedQuantity}</td><td>{item.resultingReceivedQuantity??'—'}</td><td>{item.status}</td><td>{item.status==='APPLIED'&&<Button onClick={()=>void correct(item)}>تصحيح</Button>}</td></tr>)}</DataGrid>}</Card>}
  <Card title="شراء مباشر"><form onSubmit={direct}><FormField label="المورد" required><Select required value={directSupplier} onChange={e=>setDirectSupplier(e.target.value)}>{supplierOptions}</Select></FormField><FormField label="رقم الفاتورة الداخلي" required><Input required value={directNumber} onChange={e=>setDirectNumber(e.target.value)}/></FormField><FormField label="رقم فاتورة المورد" required><Input required value={directExternal} onChange={e=>setDirectExternal(e.target.value)}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={directDate} onChange={e=>setDirectDate(e.target.value)}/></FormField><FormField label="العملة" required><Input required value={directCurrency} onChange={e=>setDirectCurrency(e.target.value.toUpperCase())}/></FormField><FormField label="حساب الدائنين" required><Input required value={controlAccount} onChange={e=>setControlAccount(e.target.value)}/></FormField><FormField label="حساب المصروف/التكلفة" required><Input required value={expenseAccount} onChange={e=>setExpenseAccount(e.target.value)}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={directAmount} onChange={e=>setDirectAmount(e.target.value)}/></FormField><Button type="submit">ترحيل الشراء المباشر</Button></form></Card>
 </section>;
}
