import { type FormEvent, useEffect, useMemo, useState } from 'react';
import {
  ActionBar, Badge, Button, Card, DataGrid, DisclosureCard, Dialog, EmptyState, ErrorState,
  FormField, Input, MetricCard, Select, Tabs, Textarea, Toast,
} from './ui.js';
import { procurementGet, procurementPatch, procurementPost } from './procurement-client.js';

type SupplierView={supplier:{id:string;supplierCode:string;status:string;approvalStatus:string};party:{id:string;displayName:string}};
type PoLine={id:string;itemReference:string;description?:string;orderedQuantity:string;unitPrice?:string;taxCode?:string;receivedQuantity:string;invoicedQuantity:string};
type PurchaseOrder={id:string;branchId:string;supplierId:string;number:string;origin:string;status:string;orderDate?:string;expectedDate?:string;currency?:string;externalReference?:string;notes?:string;lines:PoLine[]};
type Fulfillment={id:string;kind:string;status:string;lineId:string;requestedQuantity:string;previousReceivedQuantity?:string;resultingReceivedQuantity?:string;reason?:string;note?:string;createdAt:string};
type DraftLine={id:string;itemReference:string;description:string;orderedQuantity:string;unitPrice:string;taxCode:string};
type Tab='orders'|'direct';

const freshLine=():DraftLine=>({id:crypto.randomUUID(),itemReference:'',description:'',orderedQuantity:'1',unitPrice:'0',taxCode:''});
const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const statusLabel:Record<string,string>={DRAFT:'مسودة',APPROVED:'معتمد',PARTIALLY_RECEIVED:'استلام جزئي',RECEIVED:'مستلم',PARTIALLY_INVOICED:'فوترة جزئية',INVOICED:'مفوتر',CANCELLED:'ملغي'};
const statusTone=(status:string)=>status==='RECEIVED'||status==='INVOICED'?'success' as const:status==='CANCELLED'?'error' as const:status==='APPROVED'?'info' as const:'warning' as const;

export function ProcurementOperationsPage(){
 const[tab,setTab]=useState<Tab>('orders'),[rows,setRows]=useState<PurchaseOrder[]>([]),[suppliers,setSuppliers]=useState<SupplierView[]>([]),[selected,setSelected]=useState<PurchaseOrder|null>(null),[evidence,setEvidence]=useState<Fulfillment[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
 const[editingId,setEditingId]=useState<string|null>(null),[createPoId,setCreatePoId]=useState(()=>crypto.randomUUID()),[editCommandId,setEditCommandId]=useState(()=>crypto.randomUUID()),[supplierId,setSupplierId]=useState(''),[orderDate,setOrderDate]=useState(''),[expectedDate,setExpectedDate]=useState(''),[currency,setCurrency]=useState('EGP'),[externalReference,setExternalReference]=useState(''),[notes,setNotes]=useState(''),[lines,setLines]=useState<DraftLine[]>([freshLine()]);
 const[cancelTarget,setCancelTarget]=useState<PurchaseOrder|null>(null),[cancelReason,setCancelReason]=useState('');
 const[receiptTarget,setReceiptTarget]=useState<PoLine|null>(null),[receiptId,setReceiptId]=useState(()=>crypto.randomUUID()),[receiptQuantity,setReceiptQuantity]=useState(''),[receiptNote,setReceiptNote]=useState('');
 const[correctionTarget,setCorrectionTarget]=useState<Fulfillment|null>(null),[correctionId,setCorrectionId]=useState(()=>crypto.randomUUID()),[correctionQuantity,setCorrectionQuantity]=useState(''),[correctionReason,setCorrectionReason]=useState(''),[correctionNote,setCorrectionNote]=useState('');
 const[invoiceTarget,setInvoiceTarget]=useState<PoLine|null>(null),[invoiceConversionId,setInvoiceConversionId]=useState(()=>crypto.randomUUID()),[invoiceBillingId,setInvoiceBillingId]=useState(()=>crypto.randomUUID()),[invoiceQuantity,setInvoiceQuantity]=useState(''),[invoiceNumber,setInvoiceNumber]=useState(''),[supplierInvoiceNumber,setSupplierInvoiceNumber]=useState(''),[invoicePostingDate,setInvoicePostingDate]=useState(''),[invoiceControlAccount,setInvoiceControlAccount]=useState(''),[invoiceExpenseAccount,setInvoiceExpenseAccount]=useState(''),[invoiceAmount,setInvoiceAmount]=useState('');
 const[directId,setDirectId]=useState(()=>crypto.randomUUID()),[directInvoiceId,setDirectInvoiceId]=useState(()=>crypto.randomUUID()),[directLineId,setDirectLineId]=useState(()=>crypto.randomUUID()),[directSupplier,setDirectSupplier]=useState(''),[directNumber,setDirectNumber]=useState(''),[directExternal,setDirectExternal]=useState(''),[directDate,setDirectDate]=useState(''),[directCurrency,setDirectCurrency]=useState('EGP'),[controlAccount,setControlAccount]=useState(''),[expenseAccount,setExpenseAccount]=useState(''),[directAmount,setDirectAmount]=useState('');

 async function load(){try{const[purchaseOrders,supplierRows]=await Promise.all([procurementGet<PurchaseOrder[]>('/procurement/purchase-orders'),procurementGet<SupplierView[]>('/suppliers')]);setRows(purchaseOrders);setSuppliers(supplierRows.filter(row=>row.supplier.status==='ACTIVE'&&row.supplier.approvalStatus==='APPROVED'));setError('');}catch(reason){setError(message(reason));}}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>rows.filter(row=>!query||row.number.toLowerCase().includes(query.toLowerCase())||row.supplierId.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const metrics=useMemo(()=>({total:rows.length,draft:rows.filter(row=>row.status==='DRAFT').length,approved:rows.filter(row=>row.status==='APPROVED').length,receiving:rows.filter(row=>['PARTIALLY_RECEIVED','PARTIALLY_INVOICED'].includes(row.status)).length,closed:rows.filter(row=>['RECEIVED','INVOICED'].includes(row.status)).length,cancelled:rows.filter(row=>row.status==='CANCELLED').length}),[rows]);
 const supplierOptions=<><option value="">اختر المورد</option>{suppliers.map(supplier=><option key={supplier.party.id} value={supplier.party.id}>{supplier.supplier.supplierCode} — {supplier.party.displayName}</option>)}</>;
 const supplierName=(id:string)=>suppliers.find(supplier=>supplier.party.id===id)?.party.displayName??id;
 function patchLine(index:number,patch:Partial<DraftLine>){setLines(value=>value.map((line,i)=>i===index?{...line,...patch}:line));}
 function resetForm(){setEditingId(null);setCreatePoId(crypto.randomUUID());setEditCommandId(crypto.randomUUID());setSupplierId('');setOrderDate('');setExpectedDate('');setCurrency('EGP');setExternalReference('');setNotes('');setLines([freshLine()]);}
 async function choose(po:PurchaseOrder){try{const[detail,records]=await Promise.all([procurementGet<PurchaseOrder>(`/procurement/purchase-orders/${po.id}`),procurementGet<Fulfillment[]>(`/procurement/purchase-orders/${po.id}/fulfillments`)]);setSelected(detail);setEvidence(records);setNotice('');}catch(reason){setNotice(message(reason));}}
 function edit(po:PurchaseOrder){setEditingId(po.id);setEditCommandId(crypto.randomUUID());setSupplierId(po.supplierId);setOrderDate(po.orderDate??'');setExpectedDate(po.expectedDate??'');setCurrency(po.currency??'EGP');setExternalReference(po.externalReference??'');setNotes(po.notes??'');setLines(po.lines.map(line=>({id:line.id,itemReference:line.itemReference,description:line.description??'',orderedQuantity:line.orderedQuantity,unitPrice:line.unitPrice??'0',taxCode:line.taxCode??''})));window.scrollTo({top:0,behavior:'smooth'});}
 async function savePo(event:FormEvent){event.preventDefault();try{const normalizedLines=lines.map(line=>({id:line.id,itemReference:line.itemReference,description:line.description||undefined,orderedQuantity:line.orderedQuantity,unitPrice:line.unitPrice,taxCode:line.taxCode||undefined}));if(editingId){await procurementPatch(`/procurement/purchase-orders/${editingId}`,{commandId:editCommandId,supplierId,orderDate,expectedDate:expectedDate||undefined,currency,externalReference:externalReference||undefined,notes:notes||undefined,lines:normalizedLines});setNotice('تم تحديث أمر الشراء Draft.');}else{await procurementPost('/procurement/purchase-orders',{id:createPoId,supplierId,orderDate,expectedDate:expectedDate||undefined,currency,externalReference:externalReference||undefined,notes:notes||undefined,lines:normalizedLines});setNotice('تم إنشاء أمر الشراء بالترقيم التلقائي.');}resetForm();await load();}catch(reason){setNotice(message(reason));}}
 async function approve(po:PurchaseOrder){try{await procurementPost(`/procurement/purchase-orders/${po.id}/approve`,{});setNotice('تم اعتماد أمر الشراء.');await load();await choose(po);}catch(reason){setNotice(message(reason));}}
 async function cancel(){if(!cancelTarget||!cancelReason.trim())return;try{await procurementPost(`/procurement/purchase-orders/${cancelTarget.id}/cancel`,{reason:cancelReason.trim()});setNotice('تم إلغاء أمر الشراء مع حفظ السبب.');const target=cancelTarget;setCancelTarget(null);setCancelReason('');await load();await choose(target);}catch(reason){setNotice(message(reason));}}
 async function recordReceipt(event:FormEvent){event.preventDefault();if(!selected||!receiptTarget)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/fulfillments`,{id:receiptId,lineId:receiptTarget.id,quantity:receiptQuantity,note:receiptNote||undefined});setNotice('تم تسجيل التنفيذ.');setReceiptTarget(null);setReceiptId(crypto.randomUUID());setReceiptQuantity('');setReceiptNote('');await load();await choose(selected);}catch(reason){setNotice(message(reason));}}
 async function correctReceipt(event:FormEvent){event.preventDefault();if(!selected||!correctionTarget)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/fulfillment-corrections`,{id:correctionId,correctionOfId:correctionTarget.id,lineId:correctionTarget.lineId,targetReceivedQuantity:correctionQuantity,reason:correctionReason,note:correctionNote||undefined});setNotice('تم تسجيل تصحيح التنفيذ مع الاحتفاظ بالدليل السابق.');setCorrectionTarget(null);setCorrectionId(crypto.randomUUID());setCorrectionQuantity('');setCorrectionReason('');setCorrectionNote('');await load();await choose(selected);}catch(reason){setNotice(message(reason));}}
 function openInvoice(line:PoLine){setInvoiceTarget(line);setInvoiceConversionId(crypto.randomUUID());setInvoiceBillingId(crypto.randomUUID());setInvoiceQuantity(String(Number(line.receivedQuantity)-Number(line.invoicedQuantity)));setInvoicePostingDate(new Date().toISOString().slice(0,10));setInvoiceNumber('');setSupplierInvoiceNumber('');setInvoiceControlAccount('');setInvoiceExpenseAccount('');setInvoiceAmount('');}
 async function invoiceLine(event:FormEvent){event.preventDefault();if(!selected||!invoiceTarget)return;try{await procurementPost(`/procurement/purchase-orders/${selected.id}/lines/${invoiceTarget.id}/supplier-invoices`,{id:invoiceConversionId,quantity:invoiceQuantity,billing:{invoiceId:invoiceBillingId,number:invoiceNumber,externalInvoiceNumber:supplierInvoiceNumber,postingDate:invoicePostingDate,currency:selected.currency??'EGP',controlAccountId:invoiceControlAccount,accountId:invoiceExpenseAccount,amount:invoiceAmount}});setNotice('تم إنشاء وترحيل فاتورة المورد من الكمية المنفذة.');setInvoiceTarget(null);setInvoiceConversionId(crypto.randomUUID());setInvoiceBillingId(crypto.randomUUID());await load();await choose(selected);}catch(reason){setNotice(message(reason));}}
 async function direct(event:FormEvent){event.preventDefault();try{await procurementPost('/procurement/direct-purchases',{id:directId,supplierId:directSupplier,invoiceId:directInvoiceId,number:directNumber,externalInvoiceNumber:directExternal,postingDate:directDate,currency:directCurrency,controlAccountId:controlAccount,lines:[{id:directLineId,accountId:expenseAccount,amount:directAmount}]});setNotice('تم ترحيل الشراء المباشر كفاتورة مورد من خلال Billing.');setDirectId(crypto.randomUUID());setDirectInvoiceId(crypto.randomUUID());setDirectLineId(crypto.randomUUID());setDirectNumber('');setDirectExternal('');setDirectAmount('');}catch(reason){setNotice(message(reason));}}

 return <section aria-label="تشغيل المشتريات" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="أوامر الشراء" value={metrics.total}/><MetricCard label="مسودات" value={metrics.draft}/><MetricCard label="معتمدة" value={metrics.approved} tone="info"/><MetricCard label="قيد التنفيذ" value={metrics.receiving} tone={metrics.receiving?'warning':'neutral'}/><MetricCard label="مستلمة / مفوترة" value={metrics.closed} tone="success"/><MetricCard label="ملغاة" value={metrics.cancelled} tone={metrics.cancelled?'warning':'neutral'}/></div>
  <Card title="تشغيل المشتريات"><p>إدارة أمر الشراء من المسودة حتى الاستلام والفوترة، مع شراء مباشر منفصل للحالات غير المرتبطة بأمر شراء.</p><Tabs tabs={[{id:'orders',label:'أوامر الشراء'},{id:'direct',label:'الشراء المباشر'}]} active={tab} onChange={id=>setTab(id as Tab)}/></Card>
  {notice?<Toast tone={notice.startsWith('تعذر')?'error':'info'}>{notice}</Toast>:null}
  {tab==='orders'?<>
   <section className="ui-dashboard-grid" aria-label="إنشاء وبحث أوامر الشراء">
    <DisclosureCard title={editingId?'تعديل أمر شراء':'أمر شراء جديد'} description="افتح النموذج عند إنشاء أمر جديد أو تعديل مسودة قائمة." open={Boolean(editingId)}><form className="ui-filter-grid" onSubmit={savePo}><FormField label="المورد" required><Select required value={supplierId} onChange={event=>setSupplierId(event.target.value)}>{supplierOptions}</Select></FormField><FormField label="التاريخ" required><Input required type="date" value={orderDate} onChange={event=>setOrderDate(event.target.value)}/></FormField><FormField label="التاريخ المتوقع"><Input type="date" value={expectedDate} onChange={event=>setExpectedDate(event.target.value)}/></FormField><FormField label="العملة" required><Input required value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></FormField><FormField label="مرجع خارجي"><Input value={externalReference} onChange={event=>setExternalReference(event.target.value)}/></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></FormField><Card title="بنود أمر الشراء">{lines.map((line,index)=><div key={line.id} className="ui-card"><FormField label="البند" required><Input required value={line.itemReference} onChange={event=>patchLine(index,{itemReference:event.target.value})}/></FormField><FormField label="الوصف"><Input value={line.description} onChange={event=>patchLine(index,{description:event.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={line.orderedQuantity} onChange={event=>patchLine(index,{orderedQuantity:event.target.value})}/></FormField><FormField label="سعر الوحدة" required><Input required inputMode="decimal" value={line.unitPrice} onChange={event=>patchLine(index,{unitPrice:event.target.value})}/></FormField><FormField label="كود الضريبة"><Input value={line.taxCode} onChange={event=>patchLine(index,{taxCode:event.target.value})}/></FormField>{lines.length>1?<Button type="button" variant="secondary" onClick={()=>setLines(value=>value.filter((_,i)=>i!==index))}>حذف البند</Button>:null}</div>)}</Card><ActionBar><Button type="button" variant="secondary" onClick={()=>setLines(value=>[...value,freshLine()])}>إضافة بند</Button><Button type="submit">{editingId?'حفظ التعديل':'إنشاء أمر الشراء'}</Button>{editingId?<Button type="button" variant="secondary" onClick={resetForm}>إلغاء التعديل</Button>:null}</ActionBar></form></DisclosureCard>
    <Card title="البحث والمتابعة"><FormField label="بحث"><Input aria-label="بحث أوامر الشراء" placeholder="بحث بالرقم أو المورد" value={query} onChange={event=>setQuery(event.target.value)}/></FormField><p>عدد النتائج: <strong>{filtered.length}</strong></p><p>اختر أمرًا من القائمة لفتح لوحة التنفيذ والاستلام والفوترة.</p></Card>
   </section>
   <Card title="أوامر الشراء">{error?<ErrorState message={error}/>:!filtered.length?<EmptyState title="لا توجد أوامر شراء مطابقة"/>:<DataGrid columns={['الرقم','المورد','الحالة','التاريخ','الإجراءات']}>{filtered.map(po=><tr key={po.id}><td><strong>{po.number}</strong></td><td>{supplierName(po.supplierId)}</td><td><Badge tone={statusTone(po.status)}>{statusLabel[po.status]??po.status}</Badge></td><td>{po.orderDate??'—'}</td><td><ActionBar><Button onClick={()=>void choose(po)}>تفاصيل</Button>{po.status==='DRAFT'?<Button variant="secondary" onClick={()=>edit(po)}>تعديل</Button>:null}{po.status==='DRAFT'?<Button onClick={()=>void approve(po)}>اعتماد</Button>:null}{['DRAFT','APPROVED'].includes(po.status)?<Button variant="danger" onClick={()=>{setCancelTarget(po);setCancelReason('');}}>إلغاء</Button>:null}</ActionBar></td></tr>)}</DataGrid>}</Card>
   {selected?<Card title={`أمر الشراء ${selected.number}`}><ActionBar><Button variant="secondary" onClick={()=>window.print()}>طباعة</Button><Button variant="secondary" onClick={()=>setSelected(null)}>إغلاق التفاصيل</Button></ActionBar><div className="ui-metric-grid"><MetricCard label="الحالة" value={statusLabel[selected.status]??selected.status}/><MetricCard label="العملة" value={selected.currency??'—'}/><MetricCard label="البنود" value={selected.lines.length}/><MetricCard label="سجلات التنفيذ" value={evidence.length}/></div><DataGrid columns={['البند','المطلوب','المستلم','المفوتر','الإجراءات']}>{selected.lines.map(line=><tr key={line.id}><td>{line.itemReference}</td><td>{line.orderedQuantity}</td><td>{line.receivedQuantity}</td><td>{line.invoicedQuantity}</td><td><ActionBar>{['APPROVED','PARTIALLY_RECEIVED','PARTIALLY_INVOICED'].includes(selected.status)?<Button onClick={()=>{setReceiptTarget(line);setReceiptId(crypto.randomUUID());setReceiptQuantity('');setReceiptNote('');}}>تسجيل تنفيذ</Button>:null}{Number(line.receivedQuantity)>Number(line.invoicedQuantity)?<Button variant="secondary" onClick={()=>openInvoice(line)}>فاتورة مورد</Button>:null}</ActionBar></td></tr>)}</DataGrid><Card title="سجل التنفيذ">{!evidence.length?<EmptyState title="لا توجد سجلات تنفيذ بعد"/>:<DataGrid columns={['النوع','البند','قبل','بعد','الحالة','الإجراء']}>{evidence.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.lineId}</td><td>{item.previousReceivedQuantity??'—'}</td><td>{item.resultingReceivedQuantity??'—'}</td><td><Badge tone={item.status==='APPLIED'?'success':'neutral'}>{item.status}</Badge></td><td>{item.status==='APPLIED'?<Button variant="secondary" onClick={()=>{setCorrectionTarget(item);setCorrectionId(crypto.randomUUID());setCorrectionQuantity(item.resultingReceivedQuantity??item.requestedQuantity);setCorrectionReason('');setCorrectionNote('');}}>تصحيح</Button>:'—'}</td></tr>)}</DataGrid>}</Card></Card>:null}
  </>:null}
  {tab==='direct'?<section className="ui-dashboard-grid"><Card title="شراء مباشر"><form className="ui-filter-grid" onSubmit={direct}><FormField label="المورد" required><Select required value={directSupplier} onChange={event=>setDirectSupplier(event.target.value)}>{supplierOptions}</Select></FormField><FormField label="رقم الفاتورة الداخلي" required><Input required value={directNumber} onChange={event=>setDirectNumber(event.target.value)}/></FormField><FormField label="رقم فاتورة المورد" required><Input required value={directExternal} onChange={event=>setDirectExternal(event.target.value)}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={directDate} onChange={event=>setDirectDate(event.target.value)}/></FormField><FormField label="العملة" required><Input required value={directCurrency} onChange={event=>setDirectCurrency(event.target.value.toUpperCase())}/></FormField><FormField label="حساب الدائنين" required><Input required value={controlAccount} onChange={event=>setControlAccount(event.target.value)}/></FormField><FormField label="حساب المصروف/التكلفة" required><Input required value={expenseAccount} onChange={event=>setExpenseAccount(event.target.value)}/></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={directAmount} onChange={event=>setDirectAmount(event.target.value)}/></FormField><Button type="submit">ترحيل الشراء المباشر</Button></form></Card><Card title="متى تستخدم الشراء المباشر؟"><p>استخدمه عندما تكون فاتورة المورد غير مرتبطة بدورة أمر شراء واستلام. الفاتورة تظل مملوكة لـBilling ولا يتم إنشاء رصيد موازٍ داخل المشتريات.</p></Card></section>:null}
  <Dialog open={!!cancelTarget} title="إلغاء أمر الشراء" onClose={()=>setCancelTarget(null)}><FormField label="سبب الإلغاء" required><Textarea required value={cancelReason} onChange={event=>setCancelReason(event.target.value)}/></FormField><Button variant="danger" disabled={!cancelReason.trim()} onClick={()=>void cancel()}>تأكيد الإلغاء</Button></Dialog>
  <Dialog open={!!receiptTarget} title="تسجيل تنفيذ / استلام" onClose={()=>setReceiptTarget(null)}><form onSubmit={recordReceipt}><FormField label="الكمية المنفذة الآن" required><Input required inputMode="decimal" value={receiptQuantity} onChange={event=>setReceiptQuantity(event.target.value)}/></FormField><FormField label="ملاحظة"><Textarea value={receiptNote} onChange={event=>setReceiptNote(event.target.value)}/></FormField><Button type="submit">حفظ التنفيذ</Button></form></Dialog>
  <Dialog open={!!correctionTarget} title="تصحيح سجل التنفيذ" onClose={()=>setCorrectionTarget(null)}><form onSubmit={correctReceipt}><FormField label="إجمالي الكمية الصحيحة المستلمة" required><Input required inputMode="decimal" value={correctionQuantity} onChange={event=>setCorrectionQuantity(event.target.value)}/></FormField><FormField label="سبب التصحيح" required><Textarea required value={correctionReason} onChange={event=>setCorrectionReason(event.target.value)}/></FormField><FormField label="ملاحظة"><Textarea value={correctionNote} onChange={event=>setCorrectionNote(event.target.value)}/></FormField><Button type="submit">حفظ التصحيح</Button></form></Dialog>
  <Dialog open={!!invoiceTarget} title="تحويل التنفيذ إلى فاتورة مورد" onClose={()=>setInvoiceTarget(null)}><form className="ui-filter-grid" onSubmit={invoiceLine}><FormField label="الكمية المفوترة" required><Input required inputMode="decimal" value={invoiceQuantity} onChange={event=>setInvoiceQuantity(event.target.value)}/></FormField><FormField label="رقم الفاتورة الداخلي" required><Input required value={invoiceNumber} onChange={event=>setInvoiceNumber(event.target.value)}/></FormField><FormField label="رقم فاتورة المورد" required><Input required value={supplierInvoiceNumber} onChange={event=>setSupplierInvoiceNumber(event.target.value)}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={invoicePostingDate} onChange={event=>setInvoicePostingDate(event.target.value)}/></FormField><FormField label="حساب الدائنين" required><Input required value={invoiceControlAccount} onChange={event=>setInvoiceControlAccount(event.target.value)}/></FormField><FormField label="حساب المصروف/التكلفة" required><Input required value={invoiceExpenseAccount} onChange={event=>setInvoiceExpenseAccount(event.target.value)}/></FormField><FormField label="قيمة الجزء المفوتر" required><Input required inputMode="decimal" value={invoiceAmount} onChange={event=>setInvoiceAmount(event.target.value)}/></FormField><Button type="submit">إنشاء وترحيل الفاتورة</Button></form></Dialog>
 </section>;
}
