import{type FormEvent,useEffect,useState}from'react';
import{accountingApi,type AccountingOverview,type InvoiceRow}from'./accounting-client.js';
import{procurementGet,procurementPost}from'./procurement-client.js';
import{ActionBar,Badge,Button,Card,DataGrid,EmptyState,ErrorState,FormField,Input,Select,Toast}from'./ui.js';

type Conversion={id:string;purchaseOrderId:string;lineId:string;billingInvoiceId:string;quantity:string;reopenedQuantity:string;status:'RESERVED'|'INVOICED'|'REOPENED';createdAt:string};
type MatchLine={lineId:string;itemReference:string;orderedQuantity:string;receivedQuantity:string;invoicedQuantity:string;matchStatus:'MATCHED'|'RECEIVED_UNINVOICED'|'INVOICE_CONFLICT'};
type SupplierConfirmation={id:string;purchaseOrderId:string;supplierId:string;outcome:'CONFIRMED'|'DECLINED';externalReference:string|null;confirmedDeliveryDate:string|null;note:string|null;actorId:string;occurredAt:string};
type Reconciliation={purchaseOrder:{id:string;number:string;status:string;currency?:string};confirmations:SupplierConfirmation[];conversions:Conversion[];lines:MatchLine[]};
const today=()=>new Date().toISOString().slice(0,10);
const msg=(e:unknown)=>e instanceof Error?e.message:'تعذر تحميل المطابقة.';

export function ProcurementReconciliationPanel({purchaseOrderId}:{purchaseOrderId:string}){
 const[data,setData]=useState<Reconciliation|null>(null),[accounting,setAccounting]=useState<AccountingOverview|null>(null),[accountingUnavailable,setAccountingUnavailable]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[target,setTarget]=useState<InvoiceRow|null>(null),[treasuryId,setTreasuryId]=useState(''),[amount,setAmount]=useState(''),[number,setNumber]=useState(''),[postingDate,setPostingDate]=useState(today()),[confirmation,setConfirmation]=useState({outcome:'CONFIRMED' as 'CONFIRMED'|'DECLINED',externalReference:'',confirmedDeliveryDate:'',note:''});
 async function load(){setError('');try{const r=await procurementGet<Reconciliation>('/procurement/purchase-orders/'+encodeURIComponent(purchaseOrderId)+'/reconciliation');setData(r);}catch(e){setError(msg(e));}try{setAccounting(await accountingApi.overview());setAccountingUnavailable(false);}catch{setAccounting(null);setAccountingUnavailable(true);}}
 useEffect(()=>{void load();},[purchaseOrderId]);
 function invoiceFor(c:Conversion){return accounting?.invoices.find(i=>i.id===c.billingInvoiceId)??null;}
 function openPayment(invoice:InvoiceRow){setTarget(invoice);setAmount(invoice.outstanding);setTreasuryId('');setNumber('');setPostingDate(today());}
 async function confirmSupplier(event:FormEvent){event.preventDefault();setNotice('');try{await procurementPost('/procurement/purchase-orders/'+encodeURIComponent(purchaseOrderId)+'/supplier-confirmations',{id:crypto.randomUUID(),outcome:confirmation.outcome,...confirmation.externalReference?{externalReference:confirmation.externalReference}:{},...confirmation.confirmedDeliveryDate?{confirmedDeliveryDate:confirmation.confirmedDeliveryDate}:{},...confirmation.note?{note:confirmation.note}:{}});setConfirmation({outcome:'CONFIRMED',externalReference:'',confirmedDeliveryDate:'',note:''});setNotice('تم تسجيل رد المورد كدليل تشغيلي مستقل.');await load();}catch(e){setNotice(msg(e));}}
 async function pay(event:FormEvent){event.preventDefault();if(!target)return;setNotice('');try{await accountingApi.postSettlement({commandKey:crypto.randomUUID(),invoiceId:target.id,treasuryId,number,postingDate,amount});setNotice('تم تسجيل سداد المورد من خلال Treasury & Settlement وربطه بفاتورة المورد الأصلية.');setTarget(null);await load();}catch(e){setNotice(msg(e));}}
 return <section className="ui-page-stack" aria-label="مطابقة المشتريات والسداد">
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="تأكيد المورد"><p>تسجيل رد المورد لا يغيّر الالتزام أو الفاتورة؛ هو دليل تشغيلي سابق للاستلام.</p><form onSubmit={confirmSupplier}><FormField label="رد المورد"><Select value={confirmation.outcome} onChange={e=>setConfirmation({...confirmation,outcome:e.target.value as 'CONFIRMED'|'DECLINED'})}><option value="CONFIRMED">مؤكد</option><option value="DECLINED">اعتذر / رفض</option></Select></FormField>{confirmation.outcome==='CONFIRMED'?<FormField label="مرجع تأكيد المورد" required><Input required value={confirmation.externalReference} onChange={e=>setConfirmation({...confirmation,externalReference:e.target.value})}/></FormField>:null}<FormField label="موعد التسليم المؤكد"><Input type="date" value={confirmation.confirmedDeliveryDate} onChange={e=>setConfirmation({...confirmation,confirmedDeliveryDate:e.target.value})}/></FormField><FormField label="ملاحظة"><Input value={confirmation.note} onChange={e=>setConfirmation({...confirmation,note:e.target.value})}/></FormField><Button type="submit">تسجيل رد المورد</Button></form>{!data?.confirmations.length?<EmptyState title="لم يتم تسجيل رد المورد بعد"/>:<DataGrid columns={['النتيجة','المرجع','موعد التسليم','الملاحظة','الوقت']}>{data.confirmations.map(row=><tr key={row.id}><td><Badge tone={row.outcome==='CONFIRMED'?'success':'warning'}>{row.outcome==='CONFIRMED'?'مؤكد':'اعتذر / رفض'}</Badge></td><td>{row.externalReference??'—'}</td><td>{row.confirmedDeliveryDate??'—'}</td><td>{row.note??'—'}</td><td>{new Date(row.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>
  <Card title="مطابقة PO / الاستلام / فاتورة المورد"><p>المطابقة تقرأ كميات أمر الشراء والاستلام والفاتورة من أصحابها الأصليين. لا يمكن فوتره كمية أكبر من المستلم أصلًا.</p>{!data?<EmptyState title="جارٍ تحميل المطابقة…"/>:<DataGrid columns={['البند','المطلوب','المستلم','المفوتر','نتيجة المطابقة']}>{data.lines.map(line=><tr key={line.lineId}><td>{line.itemReference}</td><td>{line.orderedQuantity}</td><td>{line.receivedQuantity}</td><td>{line.invoicedQuantity}</td><td><Badge tone={line.matchStatus==='MATCHED'?'success':line.matchStatus==='RECEIVED_UNINVOICED'?'warning':'error'}>{line.matchStatus==='MATCHED'?'مطابق':line.matchStatus==='RECEIVED_UNINVOICED'?'مستلم غير مفوتر':'تعارض'}</Badge></td></tr>)}</DataGrid>}</Card>
  <Card title="فواتير المورد المرتبطة">{!data?.conversions.length?<EmptyState title="لا توجد فواتير مورد مرتبطة بأمر الشراء"/>:<DataGrid columns={['الفاتورة','البند','الكمية','حالة الربط','حالة الفاتورة','المتبقي','الاستحقاق','إجراء']}>{data.conversions.map(c=>{const invoice=invoiceFor(c);return <tr key={c.id}><td>{invoice?.number??c.billingInvoiceId}</td><td>{data.lines.find(l=>l.lineId===c.lineId)?.itemReference??c.lineId}</td><td>{c.quantity}</td><td>{c.status}</td><td>{invoice?.status??(accountingUnavailable?'لا توجد صلاحية محاسبية':'—')}</td><td>{invoice?.outstanding??'—'} {invoice?.currency??''}</td><td>{invoice?.dueDate??'—'}</td><td>{invoice&&invoice.status==='POSTED'&&Number(invoice.outstanding)>0?<Button type="button" onClick={()=>openPayment(invoice)}>سداد المورد</Button>:invoice&&Number(invoice.outstanding)<=0?'مسدد':'—'}</td></tr>;})}</DataGrid>}{accountingUnavailable?<p role="note">المطابقة متاحة، لكن عرض الرصيد والسداد يحتاج صلاحية قراءة/تشغيل المحاسبة.</p>:null}</Card>
  {target&&accounting?<Card title={'سداد فاتورة المورد '+target.number}><form onSubmit={pay}><p>الرصيد المفتوح: <strong>{target.outstanding} {target.currency}</strong></p><FormField label="الخزينة / البنك" required><Select required value={treasuryId} onChange={e=>setTreasuryId(e.target.value)}><option value="">اختر</option>{accounting.treasuries.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.code} — {t.name} — {t.currency}</option>)}</Select></FormField><FormField label="المبلغ" required><Input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></FormField><FormField label="تاريخ السداد" required><Input required type="date" value={postingDate} onChange={e=>setPostingDate(e.target.value)}/></FormField><FormField label="رقم سند الدفع" required><Input required value={number} onChange={e=>setNumber(e.target.value)}/></FormField><ActionBar><Button type="submit">ترحيل السداد</Button><Button type="button" variant="secondary" onClick={()=>setTarget(null)}>إلغاء</Button><Button type="button" variant="secondary" onClick={()=>{window.location.href='/accounting/approvals';}}>مركز الاعتمادات</Button></ActionBar></form></Card>:null}
 </section>;
}
