import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, DataGrid, Dialog, EmptyState, ErrorState, FormField, Input, MetricCard, Select, Textarea } from './ui.js';
import { procurementGet, procurementPost } from './procurement-client.js';

type PoLine={id:string;itemReference:string;description?:string;orderedQuantity:string;receivedQuantity:string;invoicedQuantity:string};
type PurchaseOrder={id:string;supplierId:string;number:string;status:string;orderDate?:string;currency?:string;lines:PoLine[]};
type SupplierView={supplier:{supplierCode:string};party:{id:string;displayName:string}};
type Fulfillment={id:string;kind:string;status:string;lineId:string;requestedQuantity:string;resultingReceivedQuantity?:string;createdAt:string};

const S=10n**18n;
function units(value:string){const text=value.trim();if(!/^\d+(?:\.\d+)?$/.test(text))throw new Error('الكمية يجب أن تكون رقمًا موجبًا.');const[whole,fraction='']=text.split('.');if(fraction.length>18)throw new Error('الكمية تدعم حتى 18 منزلة عشرية.');return BigInt(whole+fraction.padEnd(18,'0'));}
function decimal(value:bigint){const whole=value/S,fraction=value%S;return fraction===0n?whole.toString():whole+'.'+fraction.toString().padStart(18,'0').replace(/0+$/,'');}
function difference(left:string,right:string){return decimal(units(left)-units(right));}
const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';

export function ProcurementReturnsPage(){
 const[orders,setOrders]=useState<PurchaseOrder[]>([]),[suppliers,setSuppliers]=useState<SupplierView[]>([]),[selectedId,setSelectedId]=useState('');
 const[selected,setSelected]=useState<PurchaseOrder|null>(null),[evidence,setEvidence]=useState<Fulfillment[]>([]),[target,setTarget]=useState<PoLine|null>(null);
 const[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);
 async function loadBase(){try{const[poRows,supplierRows]=await Promise.all([procurementGet<PurchaseOrder[]>('/procurement/purchase-orders'),procurementGet<SupplierView[]>('/suppliers')]);setOrders(poRows.filter(po=>po.lines.some(line=>units(line.receivedQuantity)>0n)));setSuppliers(supplierRows);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void loadBase();},[]);
 async function choose(id:string){setSelectedId(id);setSelected(null);setEvidence([]);setNotice('');if(!id)return;setLoading(true);try{const[po,records]=await Promise.all([procurementGet<PurchaseOrder>('/procurement/purchase-orders/'+id),procurementGet<Fulfillment[]>('/procurement/purchase-orders/'+id+'/fulfillments')]);setSelected(po);setEvidence(records);setError('');}catch(e){setError(message(e));}finally{setLoading(false);}}
 const supplierName=useMemo(()=>selected?suppliers.find(row=>row.party.id===selected.supplierId)?.party.displayName:selected,[selected,suppliers]);
 function latestEvidence(lineId:string){return evidence.filter(item=>item.lineId===lineId&&item.status==='APPLIED').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];}
 function available(line:PoLine){try{return difference(line.receivedQuantity,line.invoicedQuantity);}catch{return '0';}}
 function openReturn(line:PoLine){setTarget(line);setQuantity(available(line));setReason('');setNote('');}
 async function submit(event:FormEvent){event.preventDefault();if(!selected||!target)return;try{const latest=latestEvidence(target.id);if(!latest)throw new Error('لا يوجد دليل استلام مطبق يمكن ربط المرتجع به.');const returned=units(quantity),max=units(available(target));if(returned<=0n)throw new Error('كمية المرتجع يجب أن تكون أكبر من صفر.');if(returned>max)throw new Error('لا يمكن إرجاع كمية مفوترة. عالج فاتورة المورد في Billing أولًا.');const resulting=decimal(units(target.receivedQuantity)-returned);await procurementPost('/procurement/purchase-orders/'+selected.id+'/fulfillment-corrections',{id:crypto.randomUUID(),correctionOfId:latest.id,lineId:target.id,targetReceivedQuantity:resulting,reason:'PURCHASE_RETURN: '+reason.trim(),note:note.trim()||undefined});setNotice('تم تسجيل مرتجع المورد كتصحيح استلام موثق مع الاحتفاظ بدليل الاستلام السابق.');setTarget(null);await loadBase();await choose(selected.id);}catch(e){setNotice(message(e));}}
 const totalReturnable=selected?.lines.filter(line=>{try{return units(available(line))>0n}catch{return false}}).length??0;
 return <section aria-label="مرتجعات المشتريات" className="ui-dashboard">
  <div className="ui-metric-grid"><MetricCard label="أوامر قابلة للمراجعة" value={orders.length}/><MetricCard label="بنود متاحة للمرتجع" value={totalReturnable} tone={totalReturnable?'warning':'neutral'}/><MetricCard label="أدلة مرتبطة" value={evidence.length}/></div>
  <Card title="مرتجعات المشتريات"><p>المرتجع غير المفوتر يُسجل كتعديل على دليل الاستلام القائم؛ لا يتم إنشاء جدول مرتجعات أو رصيد موازي.</p><FormField label="أمر الشراء"><Select value={selectedId} onChange={e=>void choose(e.target.value)}><option value="">اختر أمر الشراء</option>{orders.map(po=><option key={po.id} value={po.id}>{po.number} — {suppliers.find(row=>row.party.id===po.supplierId)?.party.displayName??po.supplierId}</option>)}</Select></FormField>{error&&<ErrorState message={error}/>} {notice&&<p role="status">{notice}</p>}</Card>
  {loading&&<Card title="تحميل"><p role="status">جاري تحميل الاستلامات المرتبطة…</p></Card>}
  {selected&&!loading&&<section className="ui-dashboard-grid" aria-label="تفاصيل المرتجع وأدلة الاستلام"><Card title={'أمر الشراء '+selected.number}><p>المورد: {supplierName??selected.supplierId} · الحالة: <Badge tone={selected.status==='CANCELLED'?'error':'neutral'}>{selected.status}</Badge> · العملة: {selected.currency??'—'}</p><DataGrid columns={['البند','المطلوب','المستلم','المفوتر','المتاح للمرتجع','إجراء']}>{selected.lines.map(line=>{const max=available(line),latest=latestEvidence(line.id),canReturn=units(max)>0n&&Boolean(latest)&&selected.status!=='CANCELLED';return <tr key={line.id}><td><strong>{line.itemReference}</strong></td><td>{line.orderedQuantity}</td><td>{line.receivedQuantity}</td><td>{line.invoicedQuantity}</td><td>{max}</td><td><Button disabled={!canReturn} onClick={()=>openReturn(line)}>مرتجع مورد</Button>{!latest&&units(line.receivedQuantity)>0n?<small className="ui-block">لا يوجد دليل مطبق صالح للتصحيح.</small>:null}{units(line.receivedQuantity)>0n&&units(max)===0n?<small className="ui-block">الكمية مفوترة بالكامل؛ عالج الفاتورة أولًا.</small>:null}</td></tr>;})}</DataGrid></Card><Card title="أدلة الاستلام والتصحيح">{evidence.length?<DataGrid columns={['النوع','البند','الكمية/الناتج','الحالة','التاريخ']}>{evidence.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.lineId}</td><td>{item.resultingReceivedQuantity??item.requestedQuantity}</td><td><Badge tone={item.status==='APPLIED'?'success':'neutral'}>{item.status}</Badge></td><td>{item.createdAt}</td></tr>)}</DataGrid>:<EmptyState title="لا توجد أدلة استلام"/>}</Card></section>}
  <Dialog open={Boolean(target)} title="تسجيل مرتجع مورد" onClose={()=>setTarget(null)}><form onSubmit={submit}><p>المستلم: {target?.receivedQuantity??'—'} · المفوتر: {target?.invoicedQuantity??'—'} · الحد الأقصى للمرتجع: {target?available(target):'—'}</p><FormField label="كمية المرتجع" required><Input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></FormField><FormField label="سبب المرتجع" required><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></FormField><FormField label="ملاحظة"><Textarea value={note} onChange={e=>setNote(e.target.value)}/></FormField><Button type="submit" disabled={!quantity.trim()||!reason.trim()}>تسجيل المرتجع</Button></form></Dialog>
 </section>;
}
