import{type FormEvent,useEffect,useMemo,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{ActionBar,Badge,Button,Card,Checkbox,DataGrid,EmptyState,ErrorState,FormField,Input,Select,Tabs,Toast}from'./ui.js';

type ConfigResponse<T>={key:string;value?:T};
type Permission={id:string;name:string};
type RoleTemplate={name:string;permissions:string[]};
type Tab='security'|'communications'|'defaults'|'roles'|'governance';
type PasswordPolicy={minLength:number;requireUpper:boolean;requireLower:boolean;requireNumber:boolean;requireSymbol:boolean};
type NotificationSettings={enabledChannels:string[];defaultLanguage:string};
type CompanyDefaults={locale:string;timezone:string;dateFormat:string};
function message(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}
const initialPassword:PasswordPolicy={minLength:12,requireUpper:false,requireLower:false,requireNumber:false,requireSymbol:false};
const initialNotifications:NotificationSettings={enabledChannels:['IN_APP','EMAIL','WHATSAPP','SMS'],defaultLanguage:'ar'};
const initialDefaults:CompanyDefaults={locale:'ar-EG',timezone:'Africa/Cairo',dateFormat:'YYYY-MM-DD'};

export function ProductSettingsPage(){
 const[tab,setTab]=useState<Tab>('security'),[password,setPassword]=useState(initialPassword),[notifications,setNotifications]=useState(initialNotifications),[defaults,setDefaults]=useState(initialDefaults),[permissions,setPermissions]=useState<Permission[]>([]),[templates,setTemplates]=useState<RoleTemplate[]>([]),[templateName,setTemplateName]=useState(''),[roleName,setRoleName]=useState(''),[selected,setSelected]=useState<string[]>([]),[permissionQuery,setPermissionQuery]=useState(''),[notice,setNotice]=useState<{tone:'success'|'error';text:string}|null>(null),[error,setError]=useState('');
 async function load(){try{const[p,n,d,r,ps]=await Promise.all([crmGet<ConfigResponse<PasswordPolicy>>('/system-administration/configuration/passwordPolicy'),crmGet<ConfigResponse<NotificationSettings>>('/system-administration/configuration/notificationSettings'),crmGet<ConfigResponse<CompanyDefaults>>('/system-administration/configuration/companyDefaults'),crmGet<ConfigResponse<RoleTemplate[]>>('/system-administration/configuration/roleTemplates'),crmGet<Permission[]>('/system-administration/permissions')]);setPassword({...initialPassword,...p.value});setNotifications({...initialNotifications,...n.value});setDefaults({...initialDefaults,...d.value});setTemplates(Array.isArray(r.value)?r.value:[]);setPermissions(ps);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[]);
 async function save<T>(key:string,value:T,success:string){setNotice(null);try{await crmPost('/system-administration/configuration/'+key,{value});setNotice({tone:'success',text:success});}catch(e){setNotice({tone:'error',text:message(e)});}}
 async function passwordSubmit(event:FormEvent){event.preventDefault();if(password.minLength<12||password.minLength>64){setNotice({tone:'error',text:'الحد الأدنى يجب أن يكون بين 12 و64.'});return;}await save('passwordPolicy',password,'تم حفظ سياسة كلمة المرور وستُطبَّق على تغييرات كلمات المرور التالية.');}
 async function notificationSubmit(event:FormEvent){event.preventDefault();if(!notifications.enabledChannels.length){setNotice({tone:'error',text:'يجب إبقاء قناة واحدة على الأقل مفعلة.'});return;}await save('notificationSettings',notifications,'تم حفظ إعدادات القنوات، ومركز الاتصالات سيمنع القنوات المعطلة.');}
 async function defaultsSubmit(event:FormEvent){event.preventDefault();await save('companyDefaults',defaults,'تم حفظ افتراضيات الشركة.');}
 async function addTemplate(event:FormEvent){event.preventDefault();const name=templateName.trim();if(!name||!selected.length)return;const next=[...templates.filter(t=>t.name!==name),{name,permissions:[...selected].sort()}].sort((a,b)=>a.name.localeCompare(b.name));try{await crmPost('/system-administration/configuration/roleTemplates',{value:next});setTemplates(next);setTemplateName('');setSelected([]);setNotice({tone:'success',text:'تم حفظ قالب الدور. يمكن تطبيقه الآن على RBAC الحقيقي.'});}catch(e){setNotice({tone:'error',text:message(e)});}}
 async function applyTemplate(name:string){try{await crmPost('/system-administration/role-templates/'+encodeURIComponent(name)+'/apply',{roleName:roleName.trim()||name});setNotice({tone:'success',text:'تم تطبيق القالب ومنح صلاحياته للدور داخل هذه الشركة فقط.'});setRoleName('');}catch(e){setNotice({tone:'error',text:message(e)});}}
 const filtered=useMemo(()=>permissions.filter(p=>!permissionQuery.trim()||p.name.toLowerCase().includes(permissionQuery.trim().toLowerCase())),[permissions,permissionQuery]);
 function togglePermission(name:string,checked:boolean){setSelected(v=>checked?[...new Set([...v,name])]:v.filter(x=>x!==name));}
 function toggleChannel(channel:string,checked:boolean){setNotifications(v=>({...v,enabledChannels:checked?[...new Set([...v.enabledChannels,channel])]:v.enabledChannels.filter(x=>x!==channel)}));}
 return <section dir="rtl" className="ui-page-stack" aria-label="إعدادات المنتج">
  {notice?<Toast tone={notice.tone}>{notice.text}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="إعدادات المنتج"><p>إعدادات الشركة التي تغيّر سلوك النظام فعليًا، بدون إنشاء مصدر حقيقة موازٍ للمحاسبة أو الموافقات أو الفروع.</p><Tabs tabs={[{id:'security',label:'الأمان'},{id:'communications',label:'الإشعارات'},{id:'defaults',label:'الافتراضيات'},{id:'roles',label:'قوالب الأدوار'},{id:'governance',label:'التحكم والحوكمة'}]} active={tab} onChange={id=>setTab(id as Tab)}/></Card>
  {tab==='security'?<Card title="سياسة كلمة المرور"><form onSubmit={passwordSubmit}><FormField label="الحد الأدنى للطول" required><Input type="number" min="12" max="64" value={password.minLength} onChange={e=>setPassword({...password,minLength:Number(e.target.value)})}/></FormField><label className="ui-checkbox-field"><Checkbox checked={password.requireUpper} onChange={e=>setPassword({...password,requireUpper:e.target.checked})}/><span>حرف إنجليزي كبير</span></label><label className="ui-checkbox-field"><Checkbox checked={password.requireLower} onChange={e=>setPassword({...password,requireLower:e.target.checked})}/><span>حرف إنجليزي صغير</span></label><label className="ui-checkbox-field"><Checkbox checked={password.requireNumber} onChange={e=>setPassword({...password,requireNumber:e.target.checked})}/><span>رقم</span></label><label className="ui-checkbox-field"><Checkbox checked={password.requireSymbol} onChange={e=>setPassword({...password,requireSymbol:e.target.checked})}/><span>رمز خاص</span></label><Button type="submit">حفظ السياسة</Button></form><p role="note">MFA لكل مستخدم يُدار من صفحة «بيانات الدخول»؛ الجلسات وإلغاؤها تُدار من إدارة النظام.</p></Card>:null}
  {tab==='communications'?<Card title="إعدادات قنوات الاتصال"><form onSubmit={notificationSubmit}><FormField label="اللغة الافتراضية"><Input value={notifications.defaultLanguage} onChange={e=>setNotifications({...notifications,defaultLanguage:e.target.value.toLowerCase()})}/></FormField>{['IN_APP','EMAIL','WHATSAPP','SMS'].map(channel=><label key={channel} className="ui-checkbox-field"><Checkbox checked={notifications.enabledChannels.includes(channel)} onChange={e=>toggleChannel(channel,e.target.checked)}/><span>{channel}</span></label>)}<Button type="submit">حفظ القنوات</Button></form><p role="note">أي قناة مغلقة هنا تُرفض قبل إدخال الرسالة إلى طابور مركز الاتصالات.</p></Card>:null}
  {tab==='defaults'?<Card title="افتراضيات الشركة"><form onSubmit={defaultsSubmit}><FormField label="اللغة/المنطقة"><Input value={defaults.locale} onChange={e=>setDefaults({...defaults,locale:e.target.value})}/></FormField><FormField label="المنطقة الزمنية"><Input value={defaults.timezone} onChange={e=>setDefaults({...defaults,timezone:e.target.value})}/></FormField><FormField label="صيغة التاريخ"><Select value={defaults.dateFormat} onChange={e=>setDefaults({...defaults,dateFormat:e.target.value})}><option value="YYYY-MM-DD">YYYY-MM-DD</option><option value="DD/MM/YYYY">DD/MM/YYYY</option><option value="MM/DD/YYYY">MM/DD/YYYY</option></Select></FormField><Button type="submit">حفظ الافتراضيات</Button></form><p role="note">العملة الأساسية لا تُدار هنا لأنها مملوكة لوحدة العملات وأسعار الصرف المحاسبية.</p></Card>:null}
  {tab==='roles'?<><Card title="إنشاء قالب دور"><form onSubmit={addTemplate}><FormField label="اسم القالب" required><Input required value={templateName} onChange={e=>setTemplateName(e.target.value)}/></FormField><FormField label="بحث في الصلاحيات"><Input value={permissionQuery} onChange={e=>setPermissionQuery(e.target.value)} placeholder="crm. أو accounting. أو tourism."/></FormField><div className="ui-permission-grid">{filtered.map(p=><label key={p.id} className="ui-checkbox-field"><Checkbox checked={selected.includes(p.name)} onChange={e=>togglePermission(p.name,e.target.checked)}/><span>{p.name}</span></label>)}</div><p>المحدد: {selected.length}</p><Button type="submit" disabled={!templateName.trim()||!selected.length}>حفظ القالب</Button></form></Card><Card title="قوالب الأدوار">{!templates.length?<EmptyState title="لا توجد قوالب أدوار"/>:<DataGrid columns={['القالب','عدد الصلاحيات','تطبيق على دور']}>{templates.map(t=><tr key={t.name}><td>{t.name}</td><td>{t.permissions.length}</td><td><FormField label="اسم الدور — اختياري"><Input value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder={t.name}/></FormField><Button type="button" onClick={()=>void applyTemplate(t.name)}>تطبيق</Button></td></tr>)}</DataGrid>}</Card></>:null}
  {tab==='governance'?<><Card title="قيود الفروع والبيانات"><p>قيود الفروع والصلاحيات لا تُحفظ كإعداد نصي منفصل؛ يتم تطبيقها فعليًا من إدارة المستخدمين والأدوار والفروع.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>{window.location.href='/system-administration';}}>المستخدمون والأدوار والفروع</Button></ActionBar></Card><Card title="الحقول المطلوبة والمخصصة"><p>إلزام الحقول المخصصة مملوك لموديول الحقول المخصصة نفسه.</p><Button type="button" variant="secondary" onClick={()=>{window.location.href='/system-administration/custom-fields';}}>إدارة الحقول</Button></Card><Card title="مصفوفة الموافقات"><p>الموافقات المالية تظل في Financial Controls، وسير الموافقات العام يتم من محرك الأتمتة. لا يوجد جدول موافقات موازٍ.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>{window.location.href='/accounting/approvals';}}>مركز الاعتمادات</Button><Button type="button" variant="secondary" onClick={()=>{window.location.href='/system-administration/automation';}}>سير العمل والأتمتة</Button></ActionBar></Card><Card title="ترقيم المستندات"><p>سياسات الترقيم مملوكة لوحدة الترقيم المركزية.</p><Button type="button" variant="secondary" onClick={()=>{window.location.href='/system-administration/document-numbering';}}>سياسات الترقيم</Button></Card></>:null}
 </section>;
}
