import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, Checkbox, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, Select, Textarea } from './ui.js';
import { quotationGet, quotationPatch, quotationPost } from './quotation-client.js';
import { accountingApi, type AccountRow } from './accounting-client.js';

type Line={id:string;description:string;quantity:string;unitPrice:string;discount:string;total:string;manualPriceOverride:boolean;discountRequiresApproval:boolean};
type Revision={id:string;number:number;validityDate:string;notes:string|null;terms:string|null;subtotal:string;discountTotal:string;total:string;sentAt:string|null;lines:Line[]};
type Quote={id:string;number:string;status:string;approvalStatus:string;sourceLeadId:string|null;customerId:string|null;customerSnapshot:{displayName:string;phone:string|null;email:string|null};currency:string;currentRevisionId:string;acceptedRevisionId:string|null;billingInvoiceId:string|null;rejectionReason:string|null;revisions:Revision[]};
type Communication={id:string;revisionId:string;channel:'WHATSAPP'|'PDF'|'PRINT'|'SHARE';outcome:string;recipientSnapshot:string|null;actorId:string;externalReference:string|null;occurredAt:string};
type CustomerView={customer:{id:string;number:string;status:string};party:{displayName:string;phone:string|null;email:string|null}};
type Lead={id:string;number:string;displayName:string;phone:string|null;email:string|null;status:string};
type DraftLine={key:string;description:string;quantity:string;unitPrice:string;discount:string;manualPriceOverride:boolean};
const msg=(e:unknown)=>e instanceof Error?e.message:'حدث خطأ غير متوقع';
const queryParam=(name:string)=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(name)??'';
const freshLine=():DraftLine=>({key:crypto.randomUUID(),description:'',quantity:'1',unitPrice:'',discount:'0',manualPriceOverride:false});
const statusLabel:Record<string,string>={DRAFT:'مسودة',SENT:'مرسل',ACCEPTED:'مقبول',REJECTED:'مرفوض',CONVERTED:'محوّل لفاتورة',EXPIRED:'منتهي'};

export function QuotationsPage(){
 const initialCustomer=queryParam('customerId'),initialLead=queryParam('leadId'),initialQuote=queryParam('quotationId');
 const[quotes,setQuotes]=useState<Quote[]>([]),[customers,setCustomers]=useState<CustomerView[]>([]),[leads,setLeads]=useState<Lead[]>([]),[accounts,setAccounts]=useState<AccountRow[]>([]),[selected,setSelected]=useState<Quote|null>(null),[communications,setCommunications]=useState<Communication[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
 const[partyType,setPartyType]=useState<'customer'|'lead'>(initialLead?'lead':'customer'),[partyId,setPartyId]=useState(initialLead||initialCustomer),[currency,setCurrency]=useState('EGP'),[validity,setValidity]=useState(''),[notes,setNotes]=useState(''),[terms,setTerms]=useState(''),[draftLines,setDraftLines]=useState<DraftLine[]>([freshLine()]);
 const[approvalReason,setApprovalReason]=useState(''),[rejectionReason,setRejectionReason]=useState(''),[decisionMode,setDecisionMode]=useState<'approve'|'reject-approval'|'reject-customer'|''>('');
 const[revisionValidity,setRevisionValidity]=useState(''),[revisionNotes,setRevisionNotes]=useState(''),[revisionTerms,setRevisionTerms]=useState(''),[revisionLines,setRevisionLines]=useState<DraftLine[]>([]);
 const[conversion,setConversion]=useState({invoiceNumber:'',postingDate:new Date().toISOString().slice(0,10),controlAccountId:'',revenueAccountId:''}),[showConversion,setShowConversion]=useState(false);
 async function load(){try{const[quoteRows,customerRows,leadRows,accounting]=await Promise.all([quotationGet<Quote[]>(`/crm/quotations?q=${encodeURIComponent(query)}`),quotationGet<CustomerView[]>('/crm/customers?status=ACTIVE'),quotationGet<Lead[]>('/crm/leads?status=QUALIFIED'),accountingApi.overview()]);setQuotes(quoteRows);setCustomers(customerRows);setLeads(leadRows);setAccounts(accounting.accounts.filter(account=>account.active&&account.postable));setError('');if(initialQuote&&!selected){const match=quoteRows.find(item=>item.id===initialQuote);if(match)await selectQuote(match);}}catch(e){setError(msg(e));}}
 useEffect(()=>{void load();},[query]);
 async function loadCommunications(id:string){try{setCommunications(await quotationGet<Communication[]>(`/crm/quotations/${id}/communications`));}catch(e){setNotice(msg(e));}}
 function loadRevisionEditor(q:Quote){const r=q.revisions.find(item=>item.id===q.currentRevisionId);if(!r)return;setRevisionValidity(r.validityDate);setRevisionNotes(r.notes??'');setRevisionTerms(r.terms??'');setRevisionLines(r.lines.map(line=>({key:line.id,description:line.description,quantity:line.quantity,unitPrice:line.unitPrice,discount:line.discount,manualPriceOverride:line.manualPriceOverride})));}
 async function selectQuote(q:Quote){setSelected(q);loadRevisionEditor(q);setDecisionMode('');setShowConversion(false);await loadCommunications(q.id);}
 function addDraftLine(){setDraftLines(lines=>[...lines,freshLine()]);}
 function patchDraftLine(key:string,patch:Partial<DraftLine>){setDraftLines(lines=>lines.map(line=>line.key===key?{...line,...patch}:line));}
 function removeDraftLine(key:string){setDraftLines(lines=>lines.length===1?lines:lines.filter(line=>line.key!==key));}
 async function create(e:FormEvent){e.preventDefault();if(draftLines.some(line=>!line.description.trim()||!line.unitPrice.trim())){setNotice('أكمل وصف وسعر كل بند.');return;}try{const r=await quotationPost<{quotation:Quote;customerResolution:string}>('/crm/quotations',{[partyType==='customer'?'customerId':'sourceLeadId']:partyId,currency,validityDate:validity,notes:notes||undefined,terms:terms||undefined,lines:draftLines.map(line=>({description:line.description,quantity:line.quantity,unitPrice:line.unitPrice,discount:line.discount,manualPriceOverride:line.manualPriceOverride,discountRequiresApproval:Number(line.discount)>0}))});await selectQuote(r.quotation);setNotice(r.customerResolution==='REVIEW_REQUIRED'?'تم حفظ العرض وربطه بالعميل المحتمل، ويلزم حسم تطابق العميل قبل التحويل.':'تم إنشاء عرض السعر.');setDraftLines([freshLine()]);setNotes('');setTerms('');await load();}catch(e){setNotice(msg(e));}}
 async function refresh(q:Quote){const next=await quotationGet<Quote>(`/crm/quotations/${q.id}`);setSelected(next);loadRevisionEditor(next);await loadCommunications(q.id);const list=await quotationGet<Quote[]>(`/crm/quotations?q=${encodeURIComponent(query)}`);setQuotes(list);}
 async function action(path:string,body:unknown={}){if(!selected)return;try{await quotationPost(`/crm/quotations/${selected.id}/${path}`,body);setNotice('تم تنفيذ الإجراء وحفظ الدليل.');await refresh(selected);}catch(e){setNotice(msg(e));}}
 async function saveRevision(e:FormEvent){e.preventDefault();if(!selected)return;try{await quotationPatch(`/crm/quotations/${selected.id}`,{validityDate:revisionValidity,notes:revisionNotes||null,terms:revisionTerms||null,lines:revisionLines.map(line=>({id:line.key,description:line.description,quantity:line.quantity,unitPrice:line.unitPrice,discount:line.discount,manualPriceOverride:line.manualPriceOverride,discountRequiresApproval:Number(line.discount)>0}))});setNotice('تم حفظ مراجعة جديدة للعرض مع الاحتفاظ بتاريخ المراجعات.');await refresh(selected);}catch(e){setNotice(msg(e));}}
 async function decide(e:FormEvent){e.preventDefault();if(!selected||!decisionMode)return;const reason=decisionMode==='reject-customer'?rejectionReason:approvalReason;if(!reason.trim())return;try{if(decisionMode==='reject-customer')await action('reject',{reason});else await action('approval',{approved:decisionMode==='approve',reason});setDecisionMode('');setApprovalReason('');setRejectionReason('');}catch(e){setNotice(msg(e));}}
 async function convert(e:FormEvent){e.preventDefault();if(!selected)return;const r=selected.revisions.find(x=>x.id===selected.acceptedRevisionId);if(!r)return;try{await action('convert',{invoiceId:`quotation-${selected.id}-${r.id}`,invoiceNumber:conversion.invoiceNumber,postingDate:conversion.postingDate,controlAccountId:conversion.controlAccountId,lines:r.lines.map(x=>({quotationLineId:x.id,accountId:conversion.revenueAccountId}))});setShowConversion(false);}catch(e){setNotice(msg(e));}}
 function targetRevision(q:Quote){return q.revisions.find(r=>r.id===(q.acceptedRevisionId??q.currentRevisionId))??q.revisions[0]!;}
 function shareText(q:Quote){const r=targetRevision(q);return `عرض سعر ${q.number}\nالعميل: ${q.customerSnapshot.displayName}\nالإجمالي: ${r.total} ${q.currency}\nصالح حتى: ${r.validityDate}`;}
 async function record(channel:Communication['channel'],recipientSnapshot?:string){if(!selected)return;const r=targetRevision(selected);await quotationPost(`/crm/quotations/${selected.id}/communications`,{channel,revisionId:r.id,...recipientSnapshot?{recipientSnapshot}:{}});await loadCommunications(selected.id);}
 async function print(channel:'PDF'|'PRINT'){if(!selected)return;try{await record(channel);setNotice(channel==='PDF'?'تم تسجيل بدء تصدير PDF. اختر Save as PDF من نافذة الطباعة.':'تم تسجيل بدء الطباعة.');window.print();}catch(e){setNotice(msg(e));}}
 async function whatsapp(){if(!selected)return;const phone=selected.customerSnapshot.phone;if(!phone){setNotice('لا يوجد رقم واتساب أو هاتف في بيانات العرض المحفوظة.');return;}const handoff=window.open('about:blank','_blank');if(handoff)handoff.opener=null;try{const evidence=await quotationPost<Communication>(`/crm/quotations/${selected.id}/communications`,{channel:'WHATSAPP',revisionId:targetRevision(selected).id,recipientSnapshot:phone});await loadCommunications(selected.id);const target=`https://wa.me/${evidence.recipientSnapshot}?text=${encodeURIComponent(shareText(selected))}`;if(handoff)handoff.location.href=target;else window.location.href=target;setNotice('تم فتح واتساب كخطوة تسليم خارجية فقط؛ ولا تُعتبر الرسالة مُسلّمة تلقائيًا.');}catch(e){handoff?.close();setNotice(msg(e));}}
 async function share(){if(!selected)return;try{await record('SHARE');const text=shareText(selected);if(navigator.share)await navigator.share({title:`عرض سعر ${selected.number}`,text});else{await navigator.clipboard.writeText(text);setNotice('تم نسخ نص العرض للمشاركة.');}}catch(e){setNotice(msg(e));}}
 const printable=selected?targetRevision(selected):null;
 const controlAccounts=useMemo(()=>accounts.filter(account=>account.classification==='ASSET'),[accounts]);const revenueAccounts=useMemo(()=>accounts.filter(account=>account.classification==='REVENUE'),[accounts]);
 return <section aria-label="عروض الأسعار" className="ui-page-stack"><style>{`@media print{body *{visibility:hidden!important}.quotation-print,.quotation-print *{visibility:visible!important}.quotation-print{position:absolute;inset:0;padding:24px;direction:rtl;background:white}.quotation-print table{width:100%;border-collapse:collapse}.quotation-print th,.quotation-print td{border:1px solid #999;padding:8px}}`}</style>
  <Card title="عروض الأسعار"><Input aria-label="بحث عروض الأسعار" value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالرقم أو العميل"/></Card>
  <DisclosureCard title="إنشاء عرض سعر" description="اختر العميل أو العميل المحتمل من السجلات الفعلية وأضف كل بنود العرض دون معرفات يدوية." open={Boolean(initialCustomer||initialLead)}><form onSubmit={create}>
   <FormField label="نوع العلاقة"><Select value={partyType} onChange={e=>{setPartyType(e.target.value as 'customer'|'lead');setPartyId('');}}><option value="customer">عميل حالي</option><option value="lead">عميل محتمل مؤهل</option></Select></FormField>
   <FormField label={partyType==='customer'?'العميل':'العميل المحتمل'} required><Select required value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">اختر</option>{partyType==='customer'?customers.map(value=><option key={value.customer.id} value={value.customer.id}>{value.customer.number} — {value.party.displayName}</option>):leads.map(value=><option key={value.id} value={value.id}>{value.number} — {value.displayName}</option>)}</Select></FormField>
   <FormField label="العملة"><Input required value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></FormField><FormField label="صالح حتى"><Input required type="date" value={validity} onChange={e=>setValidity(e.target.value)}/></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></FormField><FormField label="الشروط"><Textarea value={terms} onChange={e=>setTerms(e.target.value)}/></FormField>
   <Card title="بنود العرض">{draftLines.map((line,index)=><div className="ui-filter-grid" key={line.key}><FormField label={`وصف البند ${index+1}`} required><Input required value={line.description} onChange={e=>patchDraftLine(line.key,{description:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={line.quantity} onChange={e=>patchDraftLine(line.key,{quantity:e.target.value})}/></FormField><FormField label="سعر الوحدة" required><Input required inputMode="decimal" value={line.unitPrice} onChange={e=>patchDraftLine(line.key,{unitPrice:e.target.value})}/></FormField><FormField label="الخصم"><Input inputMode="decimal" value={line.discount} onChange={e=>patchDraftLine(line.key,{discount:e.target.value})}/></FormField><label className="ui-checkbox-field"><Checkbox checked={line.manualPriceOverride} onChange={e=>patchDraftLine(line.key,{manualPriceOverride:e.target.checked})}/><span>سعر يدوي</span></label><Button type="button" onClick={()=>removeDraftLine(line.key)} disabled={draftLines.length===1}>حذف البند</Button></div>)}<Button type="button" onClick={addDraftLine}>+ إضافة بند</Button></Card>
   <Button type="submit">إنشاء عرض السعر</Button>
  </form>{notice&&<p role="status">{notice}</p>}</DisclosureCard>
  <Card title="قائمة العروض">{error?<ErrorState message={error}/>:!quotes.length?<EmptyState/>:<DataGrid columns={['الرقم','العميل','الحالة','العملة','القيمة','إجراء']}>{quotes.map(q=><tr key={q.id}><td>{q.number}</td><td>{q.customerSnapshot.displayName}</td><td><Badge tone={q.status==='CONVERTED'?'success':q.status==='REJECTED'||q.status==='EXPIRED'?'warning':'info'}>{statusLabel[q.status]??q.status}</Badge></td><td>{q.currency}</td><td>{targetRevision(q).total}</td><td><Button onClick={()=>void selectQuote(q)}>تفاصيل</Button></td></tr>)}</DataGrid>}</Card>
  <Card title="الإرسال والتصدير">{selected?<><Button onClick={()=>void print('PRINT')}>طباعة</Button><Button onClick={()=>void print('PDF')}>حفظ PDF</Button><Button onClick={()=>void whatsapp()} disabled={!printable?.sentAt}>واتساب</Button><Button onClick={()=>void share()} disabled={!printable?.sentAt}>مشاركة</Button>{!printable?.sentAt&&<small>واتساب والمشاركة يتاحان بعد إرسال مراجعة العرض.</small>}</>:<EmptyState title="اختر عرض سعر لتفعيل أدوات الإرسال والتصدير"/>}</Card>
  <Card title="سجل الإرسال والتصدير">{!selected?<EmptyState title="اختر عرض سعر"/>:!communications.length?<EmptyState/>:<DataGrid columns={['القناة','النتيجة','المراجعة','المستلم','الوقت']}>{communications.map(item=><tr key={item.id}><td>{item.channel}</td><td>{item.outcome}</td><td>{item.revisionId}</td><td>{item.recipientSnapshot??'—'}</td><td>{new Date(item.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>
  {selected?<><Card title={`تفاصيل ${selected.number}`}><p>الحالة: <Badge>{statusLabel[selected.status]??selected.status}</Badge> — الموافقة الداخلية: {selected.approvalStatus}</p><p>العميل: {selected.customerSnapshot.displayName} | عميل حالي: {selected.customerId??'بانتظار الحسم'} | العميل المحتمل: {selected.sourceLeadId??'—'}</p>{selected.revisions.map(r=><article key={r.id}><h3>المراجعة {r.number} {r.id===selected.acceptedRevisionId?'— المقبولة':''}</h3><p>صالح حتى {r.validityDate} | الإجمالي {r.total} {selected.currency} | الخصم {r.discountTotal}</p><DataGrid columns={['الوصف','الكمية','السعر','الخصم','الإجمالي']}>{r.lines.map(x=><tr key={x.id}><td>{x.description}</td><td>{x.quantity}</td><td>{x.unitPrice}</td><td>{x.discount}</td><td>{x.total}</td></tr>)}</DataGrid></article>)}
   {selected.status==='DRAFT'?<><form onSubmit={saveRevision}><FormField label="صلاحية المراجعة"><Input required type="date" value={revisionValidity} onChange={e=>setRevisionValidity(e.target.value)}/></FormField><FormField label="ملاحظات المراجعة"><Textarea value={revisionNotes} onChange={e=>setRevisionNotes(e.target.value)}/></FormField><FormField label="الشروط"><Textarea value={revisionTerms} onChange={e=>setRevisionTerms(e.target.value)}/></FormField>{revisionLines.map((line,index)=><div className="ui-filter-grid" key={line.key}><FormField label={`البند ${index+1}`}><Input value={line.description} onChange={e=>setRevisionLines(lines=>lines.map(v=>v.key===line.key?{...v,description:e.target.value}:v))}/></FormField><FormField label="الكمية"><Input value={line.quantity} onChange={e=>setRevisionLines(lines=>lines.map(v=>v.key===line.key?{...v,quantity:e.target.value}:v))}/></FormField><FormField label="السعر"><Input value={line.unitPrice} onChange={e=>setRevisionLines(lines=>lines.map(v=>v.key===line.key?{...v,unitPrice:e.target.value}:v))}/></FormField><FormField label="الخصم"><Input value={line.discount} onChange={e=>setRevisionLines(lines=>lines.map(v=>v.key===line.key?{...v,discount:e.target.value}:v))}/></FormField></div>)}<Button type="submit">حفظ مراجعة جديدة</Button></form>{selected.approvalStatus==='PENDING'?<><Button onClick={()=>setDecisionMode('approve')}>اعتماد داخلي</Button><Button onClick={()=>setDecisionMode('reject-approval')}>رفض داخلي</Button></>:null}<Button onClick={()=>void action('send')}>إرسال للعميل</Button></>:null}
   {selected.status==='SENT'?<><Button onClick={()=>void action('accept')}>قبول العميل</Button><Button onClick={()=>setDecisionMode('reject-customer')}>رفض العميل</Button></>:null}{selected.status==='ACCEPTED'?<Button onClick={()=>setShowConversion(true)}>تحويل إلى فاتورة</Button>:null}{selected.billingInvoiceId?<p>فاتورة الفوترة: {selected.billingInvoiceId}</p>:null}</Card>
   {decisionMode?<Card title={decisionMode==='reject-customer'?'سبب رفض العميل':decisionMode==='approve'?'اعتماد العرض':'رفض الاعتماد'}><form onSubmit={decide}><FormField label="السبب / الملاحظة" required><Textarea required value={decisionMode==='reject-customer'?rejectionReason:approvalReason} onChange={e=>decisionMode==='reject-customer'?setRejectionReason(e.target.value):setApprovalReason(e.target.value)}/></FormField><Button type="submit">حفظ القرار</Button><Button type="button" onClick={()=>setDecisionMode('')}>إلغاء</Button></form></Card>:null}
   {showConversion?<Card title="تحويل العرض المقبول إلى فاتورة"><form onSubmit={convert}><FormField label="رقم الفاتورة" required><Input required value={conversion.invoiceNumber} onChange={e=>setConversion({...conversion,invoiceNumber:e.target.value})}/></FormField><FormField label="تاريخ القيد" required><Input required type="date" value={conversion.postingDate} onChange={e=>setConversion({...conversion,postingDate:e.target.value})}/></FormField><FormField label="حساب مراقبة العملاء" required><Select required value={conversion.controlAccountId} onChange={e=>setConversion({...conversion,controlAccountId:e.target.value})}><option value="">اختر الحساب</option>{controlAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><FormField label="حساب الإيراد" required><Select required value={conversion.revenueAccountId} onChange={e=>setConversion({...conversion,revenueAccountId:e.target.value})}><option value="">اختر الحساب</option>{revenueAccounts.map(account=><option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</Select></FormField><Button type="submit">تحويل إلى فاتورة</Button><Button type="button" onClick={()=>setShowConversion(false)}>إلغاء</Button></form></Card>:null}
   {printable?<article className="quotation-print" aria-label="نسخة عرض السعر للطباعة"><h1>عرض سعر {selected.number}</h1><p>العميل: {selected.customerSnapshot.displayName}</p><p>المراجعة: {printable.number} | الحالة: {statusLabel[selected.status]??selected.status} | صالح حتى: {printable.validityDate}</p><table><thead><tr><th>الوصف</th><th>الكمية</th><th>سعر الوحدة</th><th>الخصم</th><th>الإجمالي</th></tr></thead><tbody>{printable.lines.map(line=><tr key={line.id}><td>{line.description}</td><td>{line.quantity}</td><td>{line.unitPrice}</td><td>{line.discount}</td><td>{line.total}</td></tr>)}</tbody></table><p>الإجمالي: {printable.total} {selected.currency}</p>{printable.notes?<p>ملاحظات: {printable.notes}</p>:null}{printable.terms?<p>الشروط: {printable.terms}</p>:null}</article>:null}
  </>:null}
 </section>;
}
