import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPost}from'./crm-core-client.js';
import{ActionBar,Button,Card,Checkbox,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,Select,Textarea,Toast}from'./ui.js';

type Line={description:string;quantity:string;unitPrice:string;discount?:string;taxCode?:string|null;manualPriceOverride?:boolean;discountRequiresApproval?:boolean};
type Template={id:string;code:string;name:string;currency:string;defaultValidityDays:number;terms:string|null;notes:string|null;lines:Line[];active:boolean;createdAt:string;updatedAt:string};
type CustomerView={customer:{id:string;number:string;status:string};party:{displayName:string}};
const newLine=():Line=>({description:'',quantity:'1',unitPrice:'0',discount:'0',taxCode:null,manualPriceOverride:false,discountRequiresApproval:false});
function msg(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}

export function QuotationTemplatesPage(){
 const[templates,setTemplates]=useState<Template[]>([]),[customers,setCustomers]=useState<CustomerView[]>([]),[notice,setNotice]=useState<{tone:'success'|'error';text:string}|null>(null),[error,setError]=useState('');
 const[form,setForm]=useState({code:'',name:'',currency:'EGP',defaultValidityDays:'7',terms:'',notes:'',active:true}),[lines,setLines]=useState<Line[]>([newLine()]),[selectedTemplate,setSelectedTemplate]=useState(''),[customerId,setCustomerId]=useState('');
 async function load(){try{const[t,c]=await Promise.all([crmGet<Template[]>('/crm/quotations/templates'),crmGet<CustomerView[]>('/crm/customers?status=ACTIVE')]);setTemplates(t);setCustomers(c);setError('');}catch(e){setError(msg(e));}}
 useEffect(()=>{void load();},[]);
 function patchLine(i:number,p:Partial<Line>){setLines(v=>v.map((x,n)=>n===i?{...x,...p}:x));}
 async function save(event:FormEvent){event.preventDefault();try{await crmPost('/crm/quotations/templates',{code:form.code,name:form.name,currency:form.currency,defaultValidityDays:Number(form.defaultValidityDays),terms:form.terms||null,notes:form.notes||null,active:form.active,lines});setForm({code:'',name:'',currency:'EGP',defaultValidityDays:'7',terms:'',notes:'',active:true});setLines([newLine()]);setNotice({tone:'success',text:'تم حفظ قالب عرض السعر.'});await load();}catch(e){setNotice({tone:'error',text:msg(e)});}}
 async function createQuotation(event:FormEvent){event.preventDefault();try{const q=await crmPost<{id:string;number:string}>('/crm/quotations/templates/'+encodeURIComponent(selectedTemplate)+'/create',{customerId});setNotice({tone:'success',text:'تم إنشاء عرض السعر '+q.number+' من القالب.'});setSelectedTemplate('');setCustomerId('');}catch(e){setNotice({tone:'error',text:msg(e)});}}
 async function expireDue(){try{const rows=await crmPost<unknown[]>('/crm/quotations/expire-due',{});setNotice({tone:'success',text:'تم فحص صلاحية العروض وتحديث '+rows.length+' عرض منتهي.'});}catch(e){setNotice({tone:'error',text:msg(e)});}}
 return <section dir="rtl" className="ui-page-stack" aria-label="قوالب عروض الأسعار">
  {notice?<Toast tone={notice.tone}>{notice.text}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="قوالب عروض الأسعار"><p>قوالب تجارية قابلة لإعادة الاستخدام مع مدة صلاحية وشروط وبنود افتراضية، بدون نسخ يدوي لكل عرض.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>void expireDue()}>فحص العروض المنتهية</Button><Button type="button" variant="secondary" onClick={()=>{window.location.href='/crm/quotations';}}>عروض الأسعار</Button></ActionBar></Card>
  <DisclosureCard title="قالب جديد" description="الخصومات أو تعديل الأسعار يدويًا يمكن أن ترفع احتياج الموافقة عند إنشاء العرض."><form onSubmit={save}><FormField label="الكود" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></FormField><FormField label="اسم القالب" required><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FormField><FormField label="العملة" required><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="مدة الصلاحية بالأيام" required><Input required type="number" min="1" max="365" value={form.defaultValidityDays} onChange={e=>setForm({...form,defaultValidityDays:e.target.value})}/></FormField><FormField label="الشروط"><Textarea value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})}/></FormField><FormField label="ملاحظات"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></FormField><label className="ui-checkbox-field"><Checkbox checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>قالب نشط</span></label><h3>البنود</h3>{lines.map((line,i)=><Card key={i} title={'بند '+(i+1)}><FormField label="الوصف" required><Input required value={line.description} onChange={e=>patchLine(i,{description:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={line.quantity} onChange={e=>patchLine(i,{quantity:e.target.value})}/></FormField><FormField label="سعر الوحدة" required><Input required inputMode="decimal" value={line.unitPrice} onChange={e=>patchLine(i,{unitPrice:e.target.value})}/></FormField><FormField label="الخصم"><Input inputMode="decimal" value={line.discount??'0'} onChange={e=>patchLine(i,{discount:e.target.value})}/></FormField><FormField label="كود الضريبة"><Input value={line.taxCode??''} onChange={e=>patchLine(i,{taxCode:e.target.value||null})}/></FormField><label className="ui-checkbox-field"><Checkbox checked={Boolean(line.manualPriceOverride)} onChange={e=>patchLine(i,{manualPriceOverride:e.target.checked})}/><span>سعر معدل يدويًا</span></label><label className="ui-checkbox-field"><Checkbox checked={Boolean(line.discountRequiresApproval)} onChange={e=>patchLine(i,{discountRequiresApproval:e.target.checked})}/><span>الخصم يحتاج موافقة</span></label>{lines.length>1?<Button type="button" variant="secondary" onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))}>حذف البند</Button>:null}</Card>)}<ActionBar><Button type="button" variant="secondary" onClick={()=>setLines(v=>[...v,newLine()])}>إضافة بند</Button><Button type="submit">حفظ القالب</Button></ActionBar></form></DisclosureCard>
  <Card title="القوالب">{!templates.length?<EmptyState title="لا توجد قوالب"/>:<DataGrid columns={['الكود','القالب','العملة','الصلاحية','البنود','الحالة']}>{templates.map(t=><tr key={t.id}><td>{t.code}</td><td>{t.name}</td><td>{t.currency}</td><td>{t.defaultValidityDays} يوم</td><td>{t.lines.length}</td><td>{t.active?'نشط':'متوقف'}</td></tr>)}</DataGrid>}</Card>
  <DisclosureCard title="إنشاء عرض من قالب" description="يتم تكوين عرض جديد كامل من القالب وربطه بالعميل الحالي."><form onSubmit={createQuotation}><FormField label="القالب" required><Select required value={selectedTemplate} onChange={e=>setSelectedTemplate(e.target.value)}><option value="">اختر</option>{templates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.code} — {t.name}</option>)}</Select></FormField><FormField label="العميل" required><Select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">اختر</option>{customers.map(c=><option key={c.customer.id} value={c.customer.id}>{c.customer.number} — {c.party.displayName}</option>)}</Select></FormField><Button type="submit">إنشاء عرض السعر</Button></form></DisclosureCard>
 </section>;
}
