import{useEffect,useMemo,useState,type FormEvent}from'react';
import{ActionBar,Badge,Button,Card,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select,Tabs,Toast}from'./ui.js';
import{HttpReportingCenterClient,type AgingReport,type CurrencyTotalsReport,type ReportKey,type ReportSchedule,type ReportScopeFilters,type ReportingCenterClient,type ReportingCenterData,type SavedReport,type ScopedStatements}from'./reporting-center-client.js';
import type{ReportRow}from'./accounting-client.js';

type Tab='executive'|'financial'|'operations'|'saved';
type FinancialView='FINANCIAL_STATEMENTS'|'AR_AGING'|'AP_AGING'|'TREASURY'|'TAX';
const reportLabels:Record<ReportKey,string>={EXECUTIVE_OVERVIEW:'الملخص التنفيذي',FINANCIAL_STATEMENTS:'القوائم المالية',AR_AGING:'أعمار ديون العملاء',AP_AGING:'أعمار ديون الموردين',TREASURY:'الخزائن والسيولة',TAX:'الضرائب',CRM_SALES:'العملاء والمبيعات',SUPPLIER_PROCUREMENT:'الموردون والمشتريات',HAJJ_UMRAH:'الحج والعمرة',EXCEPTIONS:'الاستثناءات ومركز العمل'};
const financialLabels:Record<FinancialView,string>={FINANCIAL_STATEMENTS:'القوائم المالية',AR_AGING:'أعمار ديون العملاء',AP_AGING:'أعمار ديون الموردين',TREASURY:'الخزائن والسيولة',TAX:'الضرائب'};
const empty:ReportingCenterData={management:{generatedAt:'',totals:{attention:0,critical:0,high:0},domains:[],summary:{crmSales:{customers:0,agents:0,travelers:0,overdueFollowups:0,leadStages:{},quotationStatuses:{},quotationValueByCurrency:[]},suppliers:{total:0,openDisputes:0,activeHolds:0},hajjUmrah:{activePrograms:0,readinessItems:0,criticalReadinessItems:0},finance:{overduePositions:0,overdueByCurrency:[]}},items:[]},accounting:{fiscalYears:[],periods:[],accounts:[],journals:[],invoices:[],treasuries:[],vouchers:[],taxPolicies:[],approvalPolicies:[],approvalRequests:[],controlIssues:[],reports:{trialBalance:{rows:[]},incomeStatement:{rows:[]},balanceSheet:{rows:[]},treasury:{totals:[]},tax:{totals:[],facts:[]}}},savedReports:[],schedules:[]};
function errorMessage(error:unknown){return error instanceof Error?error.message:'تعذر تنفيذ العملية.';}
function reportRows(rows:readonly ReportRow[]){return rows.map(row=>[row.accountId??row.accountClass??'—',row.currency,row.amount]);}
function csvValue(value:unknown){const text=String(value??'');return /[",\n]/.test(text)?'"'+text.replaceAll('"','""')+'"':text;}
function downloadCsv(name:string,headers:readonly string[],rows:readonly (readonly unknown[])[]){const content='\uFEFF'+[headers,...rows].map(row=>row.map(csvValue).join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name+'.csv';link.click();URL.revokeObjectURL(url);}
function scheduleLabel(schedule:ReportSchedule){if(schedule.cadence==='DAILY')return'يوميًا الساعة '+schedule.hourUtc+':00 UTC';if(schedule.cadence==='WEEKLY')return'أسبوعيًا — يوم '+String(schedule.weekday)+' — '+schedule.hourUtc+':00 UTC';return'شهريًا — يوم '+String(schedule.dayOfMonth)+' — '+schedule.hourUtc+':00 UTC';}
function daysPastDue(dueDate:string|undefined,today=new Date()){if(!dueDate)return null;const due=new Date(dueDate+'T00:00:00Z');if(Number.isNaN(due.getTime()))return null;const current=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate());return Math.floor((current-due.getTime())/86400000);}
function agingBucket(dueDate:string|undefined){const days=daysPastDue(dueDate);if(days===null||days<=0)return'غير مستحق';if(days<=30)return'1-30';if(days<=60)return'31-60';if(days<=90)return'61-90';return'90+';}
function savedScope(filters:Readonly<Record<string,unknown>>):ReportScopeFilters{return{...(typeof filters.from==='string'?{from:filters.from}:{}),...(typeof filters.to==='string'?{to:filters.to}:{}),...(typeof filters.asOf==='string'?{asOf:filters.asOf}:{})};}

export function ReportingCenterPage({client}:{client?:ReportingCenterClient}={}){
 const api=useMemo(()=>client??new HttpReportingCenterClient(),[client]);
 const[data,setData]=useState<ReportingCenterData>(empty),[tab,setTab]=useState<Tab>('executive'),[financialView,setFinancialView]=useState<FinancialView>('FINANCIAL_STATEMENTS'),[loading,setLoading]=useState(false),[reportLoading,setReportLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[scopeDraft,setScopeDraft]=useState({from:'',to:'',asOf:''}),[scope,setScope]=useState<ReportScopeFilters>({}),[statements,setStatements]=useState<ScopedStatements|null>(null),[aging,setAging]=useState<AgingReport|null>(null),[totals,setTotals]=useState<CurrencyTotalsReport|null>(null);
 const[savedForm,setSavedForm]=useState({name:'',reportKey:'EXECUTIVE_OVERVIEW' as ReportKey,visibility:'PRIVATE' as 'PRIVATE'|'COMPANY'});
 const[scheduleForm,setScheduleForm]=useState({savedReportId:'',cadence:'DAILY' as 'DAILY'|'WEEKLY'|'MONTHLY',hourUtc:'8',weekday:'0',dayOfMonth:'1',channel:'IN_APP' as 'IN_APP'|'EMAIL',recipient:''});
 async function load(){setLoading(true);setError('');try{setData(await api.load());}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[api]);
 useEffect(()=>{if(tab!=='financial')return;let active=true;setReportLoading(true);setError('');const task=financialView==='FINANCIAL_STATEMENTS'?api.statements(scope):financialView==='AR_AGING'?api.aging('CUSTOMER',scope):financialView==='AP_AGING'?api.aging('SUPPLIER',scope):financialView==='TREASURY'?api.treasury(scope):api.tax(scope);task.then(value=>{if(!active)return;if(financialView==='FINANCIAL_STATEMENTS')setStatements(value as ScopedStatements);else if(financialView==='AR_AGING'||financialView==='AP_AGING')setAging(value as AgingReport);else setTotals(value as CurrencyTotalsReport);}).catch(e=>active&&setError(errorMessage(e))).finally(()=>active&&setReportLoading(false));return()=>{active=false};},[api,tab,financialView,scope.from,scope.to,scope.asOf]);
 async function perform(success:string,task:()=>Promise<unknown>){setLoading(true);setError('');setNotice('');try{await task();setNotice(success);await load();}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 async function createSaved(event:FormEvent){event.preventDefault();const filters={scope:'CURRENT_COMPANY_BRANCH',...scope};await perform('تم حفظ التقرير.',()=>api.createSavedReport({name:savedForm.name,reportKey:savedForm.reportKey,visibility:savedForm.visibility,filters}));setSavedForm({name:'',reportKey:'EXECUTIVE_OVERVIEW',visibility:'PRIVATE'});}
 async function createSchedule(event:FormEvent){event.preventDefault();const hourUtc=Number(scheduleForm.hourUtc),weekday=Number(scheduleForm.weekday),dayOfMonth=Number(scheduleForm.dayOfMonth);await perform('تم حفظ جدول التقرير. التنفيذ الخارجي يتم عبر قناة التسليم المهيأة.',()=>api.createSchedule({savedReportId:scheduleForm.savedReportId,cadence:scheduleForm.cadence,hourUtc,...(scheduleForm.cadence==='WEEKLY'?{weekday}:{}),...(scheduleForm.cadence==='MONTHLY'?{dayOfMonth}:{}),channel:scheduleForm.channel,...(scheduleForm.channel==='EMAIL'?{recipient:scheduleForm.recipient}:{})}));}
 const activeSaved=useMemo(()=>data.savedReports.filter(row=>row.active),[data.savedReports]);
 const critical=data.management.totals.critical,high=data.management.totals.high;
 function applyScope(){setScope({...(scopeDraft.from?{from:scopeDraft.from}:{}),...(scopeDraft.to?{to:scopeDraft.to}:{}),...(scopeDraft.asOf?{asOf:scopeDraft.asOf}:{})});}
 function openSaved(row:SavedReport){const restored=savedScope(row.filters);setScope(restored);setScopeDraft({from:restored.from??'',to:restored.to??'',asOf:restored.asOf??''});if(row.reportKey==='EXECUTIVE_OVERVIEW'){setTab('executive');return;}if(['FINANCIAL_STATEMENTS','AR_AGING','AP_AGING','TREASURY','TAX'].includes(row.reportKey)){setFinancialView(row.reportKey as FinancialView);setTab('financial');return;}setTab('operations');}
 function exportCurrent(){if(tab==='financial'){if(financialView==='AR_AGING'||financialView==='AP_AGING'){const rows=aging?.positions??[];downloadCsv(financialView==='AR_AGING'?'ar-aging':'ap-aging',['الطرف','نوع المركز','تاريخ الاستحقاق','الأيام','الشريحة','العملة','الرصيد'],rows.map(row=>[row.partyId??'—',row.positionKind??'—',row.dueDate??'—',daysPastDue(row.dueDate)??'—',agingBucket(row.dueDate),row.currency,row.openAmount]));return;}if(financialView==='TREASURY'||financialView==='TAX'){downloadCsv(financialView==='TREASURY'?'treasury-report':'tax-report',['العملة','القيمة'],(totals?.totals??[]).map(row=>[row.currency,row.amount]));return;}const s=statements;downloadCsv('financial-statements',['البند','العملة','القيمة'],s?[...reportRows(s.trialBalance.rows),...reportRows(s.incomeStatement.rows),...reportRows(s.balanceSheet.rows)]:[]);return;}if(tab==='operations'){downloadCsv('operational-exceptions',['المجال','العنوان','التفاصيل','الأولوية','الحالة'],data.management.items.map(row=>[row.sourceDomain,row.title,row.summary,row.severity,row.status]));return;}downloadCsv('executive-summary',['المؤشر','القيمة'],[['الاستثناءات',data.management.totals.attention],['حرج',critical],['مرتفع',high],['عملاء',data.management.summary.crmSales.customers],['موردون',data.management.summary.suppliers.total],['برامج حج وعمرة نشطة',data.management.summary.hajjUmrah.activePrograms],['ذمم عملاء متأخرة',data.management.summary.finance.overduePositions]]);}
 return <section dir="rtl" className="ui-page-stack" aria-label="مركز التقارير">
  <Card title="مركز التقارير"><p>قراءة موحدة للتقارير المالية والتشغيلية من أصحاب البيانات الأصليين، مع حفظ طرق العرض وجدولتها بدون نسخ الحقيقة المحاسبية أو التشغيلية.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>void load()} disabled={loading}>تحديث</Button>{tab!=='saved'?<><Button type="button" variant="secondary" onClick={()=>window.print()}>طباعة / PDF</Button><Button type="button" variant="secondary" onClick={exportCurrent}>تصدير CSV لفتح Excel</Button></>:null}</ActionBar></Card>
  <Tabs tabs={[{id:'executive',label:'ملخص تنفيذي'},{id:'financial',label:'تقارير مالية'},{id:'operations',label:'تقارير تشغيلية'},{id:'saved',label:'التقارير المحفوظة والجدولة'}]} active={tab} onChange={id=>setTab(id as Tab)}/>
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}{loading?<LoadingState/>:null}
  {tab==='executive'?<Executive data={data}/>:null}
  {tab==='financial'?<Financial data={data} view={financialView} onView={setFinancialView} scope={scopeDraft} onScope={setScopeDraft} onApply={applyScope} reportLoading={reportLoading} statements={statements} aging={aging} totals={totals}/>:null}
  {tab==='operations'?<Operations data={data}/>:null}
  {tab==='saved'?<section className="ui-page-stack">
   <DisclosureCard title="حفظ تقرير" description="يحفظ اسم التقرير ونوعه ونطاق التاريخ فقط؛ الأرقام تُقرأ من المصدر عند الفتح."><form onSubmit={createSaved}><FormField label="اسم التقرير" required><Input required value={savedForm.name} onChange={e=>setSavedForm({...savedForm,name:e.target.value})}/></FormField><FormField label="نوع التقرير"><Select value={savedForm.reportKey} onChange={e=>setSavedForm({...savedForm,reportKey:e.target.value as ReportKey})}>{Object.entries(reportLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></FormField><FormField label="الرؤية"><Select value={savedForm.visibility} onChange={e=>setSavedForm({...savedForm,visibility:e.target.value as 'PRIVATE'|'COMPANY'})}><option value="PRIVATE">خاص بي</option><option value="COMPANY">مشترك للشركة</option></Select></FormField><Button type="submit" disabled={loading}>حفظ التقرير</Button></form></DisclosureCard>
   <Card title="التقارير المحفوظة">{!data.savedReports.length?<EmptyState title="لا توجد تقارير محفوظة"/>:<DataGrid columns={['الاسم','النوع','الرؤية','الحالة','آخر تحديث','إجراء']}>{data.savedReports.map(row=><tr key={row.id}><td>{row.name}</td><td>{reportLabels[row.reportKey]}</td><td>{row.visibility==='COMPANY'?'الشركة':'خاص'}</td><td><Badge tone={row.active?'success':'warning'}>{row.active?'نشط':'متوقف'}</Badge></td><td>{new Date(row.updatedAt).toLocaleString('ar-EG')}</td><td><ActionBar><Button type="button" variant="secondary" onClick={()=>openSaved(row)}>فتح</Button><Button type="button" variant="secondary" onClick={()=>void perform(row.active?'تم إيقاف التقرير المحفوظ.':'تم تفعيل التقرير المحفوظ.',()=>api.updateSavedReport(row.id,{active:!row.active}))}>{row.active?'إيقاف':'تفعيل'}</Button></ActionBar></td></tr>)}</DataGrid>}</Card>
   <DisclosureCard title="جدولة تقرير" description="يحفظ موعد وقناة التسليم. التنفيذ الخارجي يظل مسؤولية طبقة التكامل وليس Reporting owner."><form onSubmit={createSchedule}><FormField label="التقرير المحفوظ" required><Select required value={scheduleForm.savedReportId} onChange={e=>setScheduleForm({...scheduleForm,savedReportId:e.target.value})}><option value="">اختر</option>{activeSaved.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></FormField><FormField label="التكرار"><Select value={scheduleForm.cadence} onChange={e=>setScheduleForm({...scheduleForm,cadence:e.target.value as typeof scheduleForm.cadence})}><option value="DAILY">يومي</option><option value="WEEKLY">أسبوعي</option><option value="MONTHLY">شهري</option></Select></FormField><FormField label="الساعة UTC"><Input inputMode="numeric" required value={scheduleForm.hourUtc} onChange={e=>setScheduleForm({...scheduleForm,hourUtc:e.target.value})}/></FormField>{scheduleForm.cadence==='WEEKLY'?<FormField label="يوم الأسبوع (0-6)"><Input inputMode="numeric" required value={scheduleForm.weekday} onChange={e=>setScheduleForm({...scheduleForm,weekday:e.target.value})}/></FormField>:null}{scheduleForm.cadence==='MONTHLY'?<FormField label="يوم الشهر (1-28)"><Input inputMode="numeric" required value={scheduleForm.dayOfMonth} onChange={e=>setScheduleForm({...scheduleForm,dayOfMonth:e.target.value})}/></FormField>:null}<FormField label="قناة التسليم"><Select value={scheduleForm.channel} onChange={e=>setScheduleForm({...scheduleForm,channel:e.target.value as 'IN_APP'|'EMAIL'})}><option value="IN_APP">داخل النظام</option><option value="EMAIL">بريد إلكتروني</option></Select></FormField>{scheduleForm.channel==='EMAIL'?<FormField label="البريد المستلم" required><Input required type="email" value={scheduleForm.recipient} onChange={e=>setScheduleForm({...scheduleForm,recipient:e.target.value})}/></FormField>:null}<Button type="submit" disabled={loading||!activeSaved.length}>حفظ الجدولة</Button></form></DisclosureCard>
   <Card title="الجداول">{!data.schedules.length?<EmptyState title="لا توجد جداول تقارير"/>:<DataGrid columns={['التقرير','الموعد','القناة','المستلم','الحالة','إجراء']}>{data.schedules.map(row=><tr key={row.id}><td>{data.savedReports.find(saved=>saved.id===row.savedReportId)?.name??row.savedReportId}</td><td>{scheduleLabel(row)}</td><td>{row.channel==='EMAIL'?'بريد إلكتروني':'داخل النظام'}</td><td>{row.recipient??'—'}</td><td><Badge tone={row.enabled?'success':'warning'}>{row.enabled?'نشط':'متوقف'}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void perform(row.enabled?'تم إيقاف الجدولة.':'تم تفعيل الجدولة.',()=>api.updateSchedule(row.id,{enabled:!row.enabled}))}>{row.enabled?'إيقاف':'تفعيل'}</Button></td></tr>)}</DataGrid>}</Card>
  </section>:null}
 </section>;
}

function Executive({data}:{data:ReportingCenterData}){const summary=data.management.summary;return <><div className="ui-metric-grid"><MetricCard label="الاستثناءات المفتوحة" value={data.management.totals.attention} tone={data.management.totals.attention?'warning':'success'}/><MetricCard label="حرج" value={data.management.totals.critical} tone={data.management.totals.critical?'warning':'success'}/><MetricCard label="متابعات متأخرة" value={summary.crmSales.overdueFollowups}/><MetricCard label="نزاعات موردين مفتوحة" value={summary.suppliers.openDisputes}/><MetricCard label="عناصر جاهزية الحج والعمرة" value={summary.hajjUmrah.readinessItems}/><MetricCard label="ذمم عملاء متأخرة" value={summary.finance.overduePositions}/></div><Card title="قيمة عروض الأسعار حسب العملة"><DataGrid columns={['العملة','القيمة']}>{summary.crmSales.quotationValueByCurrency.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.total}</td></tr>)}</DataGrid></Card><Card title="الذمم المتأخرة حسب العملة"><DataGrid columns={['العملة','القيمة']}>{summary.finance.overdueByCurrency.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid></Card></>}
function Financial({data,view,onView,scope,onScope,onApply,reportLoading,statements,aging,totals}:{data:ReportingCenterData;view:FinancialView;onView:(value:FinancialView)=>void;scope:{from:string;to:string;asOf:string};onScope:(value:{from:string;to:string;asOf:string})=>void;onApply:()=>void;reportLoading:boolean;statements:ScopedStatements|null;aging:AgingReport|null;totals:CurrencyTotalsReport|null}){const statementData=statements??{trialBalance:data.accounting.reports.trialBalance,incomeStatement:data.accounting.reports.incomeStatement,balanceSheet:data.accounting.reports.balanceSheet};const currencyTotals=totals?.totals??(view==='TREASURY'?data.accounting.reports.treasury.totals:data.accounting.reports.tax.totals);return <section className="ui-page-stack"><Card title="نطاق التقرير"><div className="ui-filter-grid"><FormField label="التقرير المالي"><Select aria-label="التقرير المالي" value={view} onChange={e=>onView(e.target.value as FinancialView)}>{Object.entries(financialLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></FormField><FormField label="من تاريخ"><Input type="date" value={scope.from} onChange={e=>onScope({...scope,from:e.target.value})}/></FormField><FormField label="إلى تاريخ"><Input type="date" value={scope.to} onChange={e=>onScope({...scope,to:e.target.value})}/></FormField><FormField label="كما في"><Input type="date" value={scope.asOf} onChange={e=>onScope({...scope,asOf:e.target.value})}/></FormField></div><ActionBar><Button type="button" onClick={onApply} disabled={reportLoading}>تطبيق النطاق</Button></ActionBar></Card>{reportLoading?<LoadingState/>:null}{view==='FINANCIAL_STATEMENTS'?<div className="ui-grid-md"><ReportCard title="ميزان المراجعة" rows={statementData.trialBalance.rows}/><ReportCard title="قائمة الدخل" rows={statementData.incomeStatement.rows}/><ReportCard title="المركز المالي" rows={statementData.balanceSheet.rows}/></div>:null}{view==='AR_AGING'?<AgingTable title="أعمار ديون العملاء" rows={aging?.side==='CUSTOMER'?aging.positions:[]}/>:null}{view==='AP_AGING'?<AgingTable title="أعمار ديون الموردين" rows={aging?.side==='SUPPLIER'?aging.positions:[]}/>:null}{view==='TREASURY'?<CurrencyTable title="الخزائن والسيولة" rows={currencyTotals}/>:null}{view==='TAX'?<CurrencyTable title="الضرائب" rows={currencyTotals}/>:null}</section>}
function ReportCard({title,rows}:{title:string;rows:readonly ReportRow[]}){return <Card title={title}>{!rows.length?<EmptyState title="لا توجد بيانات في النطاق الحالي"/>:<DataGrid columns={['البند','العملة','القيمة']}>{rows.map((row,index)=><tr key={(row.accountId??row.accountClass??'row')+String(index)}><td>{row.accountId??row.accountClass??'—'}</td><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid>}</Card>}
function AgingTable({title,rows}:{title:string;rows:AgingReport['positions']}){return <Card title={title}>{!rows.length?<EmptyState title="لا توجد أرصدة مفتوحة في النطاق الحالي"/>:<DataGrid columns={['الطرف','نوع المركز','تاريخ الاستحقاق','أيام التأخير','الشريحة','العملة','الرصيد']}>{rows.map(row=><tr key={row.evidenceId}><td>{row.partyId??'—'}</td><td>{row.positionKind??'—'}</td><td>{row.dueDate??'—'}</td><td>{row.dueDate?Math.max(0,daysPastDue(row.dueDate)??0):'—'}</td><td>{agingBucket(row.dueDate)}</td><td>{row.currency}</td><td>{row.openAmount}</td></tr>)}</DataGrid>}</Card>}
function CurrencyTable({title,rows}:{title:string;rows:readonly {currency:string;amount:string}[]}){return <Card title={title}>{!rows.length?<EmptyState title="لا توجد بيانات في النطاق الحالي"/>:<DataGrid columns={['العملة','الإجمالي']}>{rows.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid>}</Card>}
function Operations({data}:{data:ReportingCenterData}){const summary=data.management.summary;return <><div className="ui-metric-grid"><MetricCard label="العملاء" value={summary.crmSales.customers}/><MetricCard label="الموردون" value={summary.suppliers.total}/><MetricCard label="الموردون الموقوفون" value={summary.suppliers.activeHolds}/><MetricCard label="برامج حج وعمرة نشطة" value={summary.hajjUmrah.activePrograms}/><MetricCard label="جاهزية حرجة" value={summary.hajjUmrah.criticalReadinessItems} tone={summary.hajjUmrah.criticalReadinessItems?'warning':'success'}/><MetricCard label="مشكلات رقابية مفتوحة" value={data.accounting.controlIssues.filter(row=>!row.resolvedAt).length} tone={data.accounting.controlIssues.some(row=>!row.resolvedAt)?'warning':'success'}/></div><ActionBar><Button type="button" variant="secondary" onClick={()=>{window.location.href='/management/approvals'}}>مركز الموافقات</Button><Button type="button" variant="secondary" onClick={()=>{window.location.href='/management/exceptions'}}>مركز العمل والاستثناءات</Button><Button type="button" variant="secondary" onClick={()=>{window.location.href='/hajj-umrah/readiness'}}>تقارير وجاهزية الحج والعمرة</Button></ActionBar><Card title="مشكلات الرقابة المالية">{!data.accounting.controlIssues.length?<EmptyState title="لا توجد مشكلات رقابية"/>:<DataGrid columns={['الدليل','المصدر','الدفتر','الفرق','الحالة']}>{data.accounting.controlIssues.map(row=><tr key={row.id}><td>{row.evidenceKey}</td><td>{row.sourceAmount}</td><td>{row.ledgerAmount}</td><td>{row.difference}</td><td><Badge tone={row.resolvedAt?'success':'warning'}>{row.resolvedAt?'تم الحل':'مفتوح'}</Badge></td></tr>)}</DataGrid>}</Card><Card title="الاستثناءات التشغيلية">{!data.management.items.length?<EmptyState title="لا توجد استثناءات تشغيلية"/>:<DataGrid columns={['المجال','العنوان','التفاصيل','الأولوية','الحالة','فتح']}>{data.management.items.map(row=><tr key={row.sourceKey}><td>{row.sourceDomain}</td><td>{row.title}</td><td>{row.summary}</td><td><Badge tone={row.severity==='CRITICAL'||row.severity==='HIGH'?'warning':'info'}>{row.severity}</Badge></td><td>{row.status}</td><td><Button type="button" variant="secondary" onClick={()=>{window.location.href=row.drillDownPath}}>فتح</Button></td></tr>)}</DataGrid>}</Card></>}
