import{useEffect,useMemo,useState,type FormEvent}from'react';
import{ActionBar,Badge,Button,Card,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select,Tabs,Toast}from'./ui.js';
import{HttpReportingCenterClient,type ReportKey,type ReportSchedule,type ReportingCenterClient,type ReportingCenterData}from'./reporting-center-client.js';
import type{ReportRow}from'./accounting-client.js';

type Tab='executive'|'financial'|'operations'|'saved';
const reportLabels:Record<ReportKey,string>={
 EXECUTIVE_OVERVIEW:'الملخص التنفيذي',
 FINANCIAL_STATEMENTS:'القوائم المالية',
 AR_AGING:'أعمار ديون العملاء',
 AP_AGING:'أعمار ديون الموردين',
 TREASURY:'الخزائن والسيولة',
 TAX:'الضرائب',
 CRM_SALES:'العملاء والمبيعات',
 SUPPLIER_PROCUREMENT:'الموردون والمشتريات',
 HAJJ_UMRAH:'الحج والعمرة',
 EXCEPTIONS:'الاستثناءات ومركز العمل',
};
const empty:ReportingCenterData={
 management:{generatedAt:'',totals:{attention:0,critical:0,high:0},domains:[],summary:{crmSales:{customers:0,agents:0,travelers:0,overdueFollowups:0,leadStages:{},quotationStatuses:{},quotationValueByCurrency:[]},suppliers:{total:0,openDisputes:0,activeHolds:0},hajjUmrah:{activePrograms:0,readinessItems:0,criticalReadinessItems:0},finance:{overduePositions:0,overdueByCurrency:[]}},items:[]},
 accounting:{fiscalYears:[],periods:[],accounts:[],journals:[],invoices:[],treasuries:[],vouchers:[],taxPolicies:[],approvalPolicies:[],approvalRequests:[],controlIssues:[],reports:{trialBalance:{rows:[]},incomeStatement:{rows:[]},balanceSheet:{rows:[]},treasury:{totals:[]},tax:{totals:[],facts:[]}}},
 savedReports:[],schedules:[],
};
function errorMessage(error:unknown){return error instanceof Error?error.message:'تعذر تنفيذ العملية.';}
function reportRows(rows:readonly ReportRow[]){return rows.map(row=>[row.accountId??row.accountClass??'—',row.currency,row.amount]);}
function csvValue(value:unknown){const text=String(value??'');return /[",\n]/.test(text)?'"'+text.replaceAll('"','""')+'"':text;}
function downloadCsv(name:string,headers:readonly string[],rows:readonly (readonly unknown[])[]){const content='\uFEFF'+[headers,...rows].map(row=>row.map(csvValue).join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name+'.csv';link.click();URL.revokeObjectURL(url);}
function scheduleLabel(schedule:ReportSchedule){if(schedule.cadence==='DAILY')return'يوميًا الساعة '+schedule.hourUtc+':00 UTC';if(schedule.cadence==='WEEKLY')return'أسبوعيًا — يوم '+String(schedule.weekday)+' — '+schedule.hourUtc+':00 UTC';return'شهريًا — يوم '+String(schedule.dayOfMonth)+' — '+schedule.hourUtc+':00 UTC';}

export function ReportingCenterPage({client=new HttpReportingCenterClient()}:{client?:ReportingCenterClient}={}){
 const[data,setData]=useState<ReportingCenterData>(empty),[tab,setTab]=useState<Tab>('executive'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[savedForm,setSavedForm]=useState({name:'',reportKey:'EXECUTIVE_OVERVIEW' as ReportKey,visibility:'PRIVATE' as 'PRIVATE'|'COMPANY'});
 const[scheduleForm,setScheduleForm]=useState({savedReportId:'',cadence:'DAILY' as 'DAILY'|'WEEKLY'|'MONTHLY',hourUtc:'8',weekday:'0',dayOfMonth:'1',channel:'IN_APP' as 'IN_APP'|'EMAIL',recipient:''});
 async function load(){setLoading(true);setError('');try{setData(await client.load());}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function perform(success:string,task:()=>Promise<unknown>){setLoading(true);setError('');setNotice('');try{await task();setNotice(success);await load();}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 async function createSaved(event:FormEvent){event.preventDefault();await perform('تم حفظ التقرير.',()=>client.createSavedReport({name:savedForm.name,reportKey:savedForm.reportKey,visibility:savedForm.visibility,filters:{scope:'CURRENT_COMPANY_BRANCH'}}));setSavedForm({name:'',reportKey:'EXECUTIVE_OVERVIEW',visibility:'PRIVATE'});}
 async function createSchedule(event:FormEvent){event.preventDefault();const hourUtc=Number(scheduleForm.hourUtc),weekday=Number(scheduleForm.weekday),dayOfMonth=Number(scheduleForm.dayOfMonth);await perform('تم حفظ جدول التقرير. التنفيذ الخارجي يتم عبر قناة التسليم المهيأة.',()=>client.createSchedule({savedReportId:scheduleForm.savedReportId,cadence:scheduleForm.cadence,hourUtc,...(scheduleForm.cadence==='WEEKLY'?{weekday}:{}),...(scheduleForm.cadence==='MONTHLY'?{dayOfMonth}:{}),channel:scheduleForm.channel,...(scheduleForm.channel==='EMAIL'?{recipient:scheduleForm.recipient}:{})}));}
 const activeSaved=useMemo(()=>data.savedReports.filter(row=>row.active),[data.savedReports]);
 const critical=data.management.totals.critical,high=data.management.totals.high;
 function exportCurrent(){if(tab==='financial'){downloadCsv('financial-report',['البند','العملة','القيمة'],reportRows(data.accounting.reports.trialBalance.rows));return;}if(tab==='operations'){downloadCsv('operational-exceptions',['المجال','العنوان','التفاصيل','الأولوية','الحالة'],data.management.items.map(row=>[row.sourceDomain,row.title,row.summary,row.severity,row.status]));return;}downloadCsv('executive-summary',['المؤشر','القيمة'],[['الاستثناءات',data.management.totals.attention],['حرج',critical],['مرتفع',high],['عملاء',data.management.summary.crmSales.customers],['موردون',data.management.summary.suppliers.total],['برامج حج وعمرة نشطة',data.management.summary.hajjUmrah.activePrograms],['ذمم عملاء متأخرة',data.management.summary.finance.overduePositions]]);}
 return <section dir="rtl" className="ui-page-stack" aria-label="مركز التقارير">
  <Card title="مركز التقارير"><p>قراءة موحدة للتقارير المالية والتشغيلية من أصحاب البيانات الأصليين، مع حفظ طرق العرض وجدولتها بدون نسخ الحقيقة المحاسبية أو التشغيلية.</p><ActionBar><Button type="button" variant="secondary" onClick={()=>void load()} disabled={loading}>تحديث</Button>{tab!=='saved'?<><Button type="button" variant="secondary" onClick={()=>window.print()}>طباعة / PDF</Button><Button type="button" variant="secondary" onClick={exportCurrent}>تصدير CSV لفتح Excel</Button></>:null}</ActionBar></Card>
  <Tabs tabs={[{id:'executive',label:'ملخص تنفيذي'},{id:'financial',label:'تقارير مالية'},{id:'operations',label:'تقارير تشغيلية'},{id:'saved',label:'التقارير المحفوظة والجدولة'}]} active={tab} onChange={id=>setTab(id as Tab)}/>
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}{loading?<LoadingState/>:null}
  {tab==='executive'?<Executive data={data}/>:null}
  {tab==='financial'?<Financial data={data}/>:null}
  {tab==='operations'?<Operations data={data}/>:null}
  {tab==='saved'?<section className="ui-page-stack">
   <DisclosureCard title="حفظ تقرير" description="يحفظ اسم التقرير ونوعه والفلاتر فقط؛ الأرقام تُقرأ دائمًا من المصدر عند الفتح."><form onSubmit={createSaved}><FormField label="اسم التقرير" required><Input required value={savedForm.name} onChange={e=>setSavedForm({...savedForm,name:e.target.value})}/></FormField><FormField label="نوع التقرير"><Select value={savedForm.reportKey} onChange={e=>setSavedForm({...savedForm,reportKey:e.target.value as ReportKey})}>{Object.entries(reportLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></FormField><FormField label="الرؤية"><Select value={savedForm.visibility} onChange={e=>setSavedForm({...savedForm,visibility:e.target.value as 'PRIVATE'|'COMPANY'})}><option value="PRIVATE">خاص بي</option><option value="COMPANY">مشترك للشركة</option></Select></FormField><Button type="submit" disabled={loading}>حفظ التقرير</Button></form></DisclosureCard>
   <Card title="التقارير المحفوظة">{!data.savedReports.length?<EmptyState title="لا توجد تقارير محفوظة"/>:<DataGrid columns={['الاسم','النوع','الرؤية','الحالة','آخر تحديث','إجراء']}>{data.savedReports.map(row=><tr key={row.id}><td>{row.name}</td><td>{reportLabels[row.reportKey]}</td><td>{row.visibility==='COMPANY'?'الشركة':'خاص'}</td><td><Badge tone={row.active?'success':'warning'}>{row.active?'نشط':'متوقف'}</Badge></td><td>{new Date(row.updatedAt).toLocaleString('ar-EG')}</td><td><Button type="button" variant="secondary" onClick={()=>void perform(row.active?'تم إيقاف التقرير المحفوظ.':'تم تفعيل التقرير المحفوظ.',()=>client.updateSavedReport(row.id,{active:!row.active}))}>{row.active?'إيقاف':'تفعيل'}</Button></td></tr>)}</DataGrid>}</Card>
   <DisclosureCard title="جدولة تقرير" description="يحفظ موعد وقناة التسليم. البريد يتطلب إعداد قناة Email ضمن مركز التكاملات عند تنفيذها."><form onSubmit={createSchedule}><FormField label="التقرير المحفوظ" required><Select required value={scheduleForm.savedReportId} onChange={e=>setScheduleForm({...scheduleForm,savedReportId:e.target.value})}><option value="">اختر</option>{activeSaved.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</Select></FormField><FormField label="التكرار"><Select value={scheduleForm.cadence} onChange={e=>setScheduleForm({...scheduleForm,cadence:e.target.value as typeof scheduleForm.cadence})}><option value="DAILY">يومي</option><option value="WEEKLY">أسبوعي</option><option value="MONTHLY">شهري</option></Select></FormField><FormField label="الساعة UTC"><Input inputMode="numeric" required value={scheduleForm.hourUtc} onChange={e=>setScheduleForm({...scheduleForm,hourUtc:e.target.value})}/></FormField>{scheduleForm.cadence==='WEEKLY'?<FormField label="يوم الأسبوع (0-6)"><Input inputMode="numeric" required value={scheduleForm.weekday} onChange={e=>setScheduleForm({...scheduleForm,weekday:e.target.value})}/></FormField>:null}{scheduleForm.cadence==='MONTHLY'?<FormField label="يوم الشهر (1-28)"><Input inputMode="numeric" required value={scheduleForm.dayOfMonth} onChange={e=>setScheduleForm({...scheduleForm,dayOfMonth:e.target.value})}/></FormField>:null}<FormField label="قناة التسليم"><Select value={scheduleForm.channel} onChange={e=>setScheduleForm({...scheduleForm,channel:e.target.value as 'IN_APP'|'EMAIL'})}><option value="IN_APP">داخل النظام</option><option value="EMAIL">بريد إلكتروني</option></Select></FormField>{scheduleForm.channel==='EMAIL'?<FormField label="البريد المستلم" required><Input required type="email" value={scheduleForm.recipient} onChange={e=>setScheduleForm({...scheduleForm,recipient:e.target.value})}/></FormField>:null}<Button type="submit" disabled={loading||!activeSaved.length}>حفظ الجدولة</Button></form></DisclosureCard>
   <Card title="الجداول">{!data.schedules.length?<EmptyState title="لا توجد جداول تقارير"/>:<DataGrid columns={['التقرير','الموعد','القناة','المستلم','الحالة','إجراء']}>{data.schedules.map(row=><tr key={row.id}><td>{data.savedReports.find(saved=>saved.id===row.savedReportId)?.name??row.savedReportId}</td><td>{scheduleLabel(row)}</td><td>{row.channel==='EMAIL'?'بريد إلكتروني':'داخل النظام'}</td><td>{row.recipient??'—'}</td><td><Badge tone={row.enabled?'success':'warning'}>{row.enabled?'نشط':'متوقف'}</Badge></td><td><Button type="button" variant="secondary" onClick={()=>void perform(row.enabled?'تم إيقاف الجدولة.':'تم تفعيل الجدولة.',()=>client.updateSchedule(row.id,{enabled:!row.enabled}))}>{row.enabled?'إيقاف':'تفعيل'}</Button></td></tr>)}</DataGrid>}</Card>
  </section>:null}
 </section>;
}

function Executive({data}:{data:ReportingCenterData}){const summary=data.management.summary;return <><div className="ui-metric-grid"><MetricCard label="الاستثناءات المفتوحة" value={data.management.totals.attention} tone={data.management.totals.attention?'warning':'success'}/><MetricCard label="حرج" value={data.management.totals.critical} tone={data.management.totals.critical?'warning':'success'}/><MetricCard label="متابعات متأخرة" value={summary.crmSales.overdueFollowups}/><MetricCard label="نزاعات موردين مفتوحة" value={summary.suppliers.openDisputes}/><MetricCard label="عناصر جاهزية الحج والعمرة" value={summary.hajjUmrah.readinessItems}/><MetricCard label="ذمم عملاء متأخرة" value={summary.finance.overduePositions}/></div><Card title="قيمة عروض الأسعار حسب العملة"><DataGrid columns={['العملة','القيمة']}>{summary.crmSales.quotationValueByCurrency.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.total}</td></tr>)}</DataGrid></Card><Card title="الذمم المتأخرة حسب العملة"><DataGrid columns={['العملة','القيمة']}>{summary.finance.overdueByCurrency.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid></Card></>;}
function Financial({data}:{data:ReportingCenterData}){return <div className="ui-grid-md"><ReportCard title="ميزان المراجعة" rows={data.accounting.reports.trialBalance.rows}/><ReportCard title="قائمة الدخل" rows={data.accounting.reports.incomeStatement.rows}/><ReportCard title="المركز المالي" rows={data.accounting.reports.balanceSheet.rows}/><Card title="الخزائن والسيولة"><DataGrid columns={['العملة','الإجمالي']}>{data.accounting.reports.treasury.totals.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid></Card><Card title="الضرائب"><DataGrid columns={['العملة','الإجمالي']}>{data.accounting.reports.tax.totals.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid></Card></div>;}
function ReportCard({title,rows}:{title:string;rows:readonly ReportRow[]}){return <Card title={title}>{!rows.length?<EmptyState title="لا توجد بيانات في النطاق الحالي"/>:<DataGrid columns={['البند','العملة','القيمة']}>{rows.map((row,index)=><tr key={(row.accountId??row.accountClass??'row')+String(index)}><td>{row.accountId??row.accountClass??'—'}</td><td>{row.currency}</td><td>{row.amount}</td></tr>)}</DataGrid>}</Card>;}
function Operations({data}:{data:ReportingCenterData}){const summary=data.management.summary;return <><div className="ui-metric-grid"><MetricCard label="العملاء" value={summary.crmSales.customers}/><MetricCard label="الموردون" value={summary.suppliers.total}/><MetricCard label="الموردون الموقوفون" value={summary.suppliers.activeHolds}/><MetricCard label="برامج حج وعمرة نشطة" value={summary.hajjUmrah.activePrograms}/><MetricCard label="جاهزية حرجة" value={summary.hajjUmrah.criticalReadinessItems} tone={summary.hajjUmrah.criticalReadinessItems?'warning':'success'}/></div><Card title="الاستثناءات التشغيلية">{!data.management.items.length?<EmptyState title="لا توجد استثناءات تشغيلية"/>:<DataGrid columns={['المجال','العنوان','التفاصيل','الأولوية','الحالة','فتح']}>{data.management.items.map(row=><tr key={row.sourceKey}><td>{row.sourceDomain}</td><td>{row.title}</td><td>{row.summary}</td><td><Badge tone={row.severity==='CRITICAL'||row.severity==='HIGH'?'warning':'info'}>{row.severity}</Badge></td><td>{row.status}</td><td><Button type="button" variant="secondary" onClick={()=>{window.location.href=row.drillDownPath;}}>فتح</Button></td></tr>)}</DataGrid>}</Card></>;}
