import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { ActionBar, Badge, Button, Card, DataGrid, Dialog, DisclosureCard, EmptyState, ErrorState, FormField, Input, LoadingState, MetricCard, Select, Textarea } from './ui.js';
import { supplierGet, supplierPatch, supplierPost } from './supplier-client.js';

type Bank={id:string;bankName:string|null;accountNumber:string|null;iban:string|null;currency:string|null;active:boolean;isDefault:boolean};
type View={supplier:{id:string;supplierCode:string;status:string;approvalStatus:string;defaultCurrency:string;creditDays:number;contactPerson:string|null;notes:string|null};party:{id:string;kind:'PERSON'|'ORGANIZATION';displayName:string;legalName:string|null;phone:string|null;whatsappNumber:string|null;email:string|null;taxIdentity:string|null;address:string|null};categories:string[]};
const message=(error:unknown)=>error instanceof Error?error.message:'حدث خطأ غير متوقع';
const statusLabel=(value:string)=>value==='ACTIVE'?'نشط':value==='INACTIVE'?'غير نشط':value==='ON_HOLD'?'موقوف مؤقتًا':value;
const approvalLabel=(value:string)=>value==='APPROVED'?'معتمد':value==='PENDING'?'بانتظار الاعتماد':value==='REJECTED'?'مرفوض':value;
const categoryLabel=(value:string)=>({HOTEL:'فندق',AIRLINE:'طيران',TRANSPORT:'نقل',VISA:'تأشيرات',OTHER:'أخرى'} as Record<string,string>)[value]??value;
const normalizePhone=(value:string)=>value.replace(/[^\d]/g,'').replace(/^00/,'');

export function SuppliersPage(){
 const[rows,setRows]=useState<View[]>([]),[selected,setSelected]=useState<View|null>(null),[banks,setBanks]=useState<Bank[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true);
 const[statusFilter,setStatusFilter]=useState('ALL'),[approvalFilter,setApprovalFilter]=useState('ALL'),[categoryFilter,setCategoryFilter]=useState('ALL'),[sort,setSort]=useState('CODE_ASC');
 const[name,setName]=useState(''),[legalName,setLegalName]=useState(''),[phone,setPhone]=useState(''),[whatsapp,setWhatsapp]=useState(''),[email,setEmail]=useState(''),[taxIdentity,setTaxIdentity]=useState(''),[address,setAddress]=useState('');
 const[code,setCode]=useState(''),[currency,setCurrency]=useState('EGP'),[creditDays,setCreditDays]=useState('0'),[contact,setContact]=useState(''),[notes,setNotes]=useState(''),[category,setCategory]=useState('OTHER');
 const[bankName,setBankName]=useState(''),[account,setAccount]=useState(''),[iban,setIban]=useState('');
 const[editingBank,setEditingBank]=useState<Bank|null>(null),[editBankName,setEditBankName]=useState(''),[editAccount,setEditAccount]=useState(''),[editIban,setEditIban]=useState(''),[rejectOpen,setRejectOpen]=useState(false),[rejectReason,setRejectReason]=useState('');
 async function load(){setLoading(true);try{setRows(await supplierGet<View[]>(`/suppliers?q=${encodeURIComponent(q)}`));setError('');}catch(e){setError(message(e));}finally{setLoading(false)}}
 useEffect(()=>{void load();},[q]);
 const visibleRows=useMemo(()=>rows.filter(v=>(statusFilter==='ALL'||v.supplier.status===statusFilter)&&(approvalFilter==='ALL'||v.supplier.approvalStatus===approvalFilter)&&(categoryFilter==='ALL'||v.categories.includes(categoryFilter))).sort((a,b)=>sort==='NAME_ASC'?a.party.displayName.localeCompare(b.party.displayName,'ar'):sort==='NAME_DESC'?b.party.displayName.localeCompare(a.party.displayName,'ar'):sort==='CODE_DESC'?b.supplier.supplierCode.localeCompare(a.supplier.supplierCode,undefined,{numeric:true}):a.supplier.supplierCode.localeCompare(b.supplier.supplierCode,undefined,{numeric:true})),[rows,statusFilter,approvalFilter,categoryFilter,sort]);
 function identity(){return{kind:'ORGANIZATION' as const,displayName:name,legalName:legalName||undefined,phone:phone||undefined,whatsappNumber:whatsapp||undefined,email:email||undefined,taxIdentity:taxIdentity||undefined,address:address||undefined};}
 function fill(v:View){setName(v.party.displayName);setLegalName(v.party.legalName??'');setPhone(v.party.phone??'');setWhatsapp(v.party.whatsappNumber??'');setEmail(v.party.email??'');setTaxIdentity(v.party.taxIdentity??'');setAddress(v.party.address??'');setCurrency(v.supplier.defaultCurrency);setCreditDays(String(v.supplier.creditDays));setContact(v.supplier.contactPerson??'');setNotes(v.supplier.notes??'');setCategory(v.categories[0]??'OTHER');}
 async function choose(v:View){try{const detail=await supplierGet<View>(`/suppliers/${v.supplier.id}`);setSelected(detail);fill(detail);setBanks(await supplierGet<Bank[]>(`/suppliers/${v.supplier.id}/bank-accounts`));setError('');}catch(e){setError(message(e));}}
 async function create(e:FormEvent){e.preventDefault();try{const result=await supplierPost<{status:string;value?:View}>('/suppliers',{party:identity(),supplierCode:code,defaultCurrency:currency,creditDays:Number(creditDays),contactPerson:contact,notes,categories:[category]});if(result.value)await choose(result.value);setNotice(result.status==='REVIEW_REQUIRED'?'توجد هوية مشابهة وتلزم المراجعة قبل إنشاء المورد.':'تم إنشاء المورد بحالة انتظار الاعتماد.');await load();}catch(e){setNotice(message(e));}}
 async function action(path:string,body:unknown={}){if(!selected)return;try{await supplierPost(`/suppliers/${selected.supplier.id}/${path}`,body);setNotice('تم تنفيذ الإجراء.');await choose(selected);await load();}catch(e){setNotice(message(e));}}
 async function save(){if(!selected)return;try{await supplierPatch(`/suppliers/${selected.supplier.id}`,{party:identity(),defaultCurrency:currency,creditDays:Number(creditDays),contactPerson:contact,notes,categories:[category]});setNotice('تم حفظ بيانات الهوية والتشغيل.');await choose(selected);await load();}catch(e){setNotice(message(e));}}
 async function addBank(e:FormEvent){e.preventDefault();if(!selected)return;try{await supplierPost(`/suppliers/${selected.supplier.id}/bank-accounts`,{bankName:bankName||null,accountNumber:account||null,iban:iban||null,currency,isDefault:banks.length===0});setNotice('تم حفظ الحساب البنكي.');setBankName('');setAccount('');setIban('');await choose(selected);}catch(e){setNotice(message(e));}}
 async function updateBank(bank:Bank,input:Partial<Bank>){if(!selected)return;try{await supplierPatch(`/suppliers/${selected.supplier.id}/bank-accounts/${bank.id}`,{bankName:bank.bankName,accountNumber:bank.accountNumber,iban:bank.iban,currency:bank.currency,active:bank.active,isDefault:bank.isDefault,...input});setNotice('تم تحديث الحساب البنكي وحفظ دليل التدقيق.');await choose(selected);}catch(e){setNotice(message(e));}}
 function beginBankEdit(bank:Bank){setEditingBank(bank);setEditBankName(bank.bankName??'');setEditAccount(bank.accountNumber??'');setEditIban(bank.iban??'');}
 async function saveBankEdit(){if(!editingBank)return;await updateBank(editingBank,{bankName:editBankName||null,accountNumber:editAccount||null,iban:editIban||null});setEditingBank(null);}
 async function reject(){if(!rejectReason.trim())return;await action('approval',{decision:'REJECTED',reason:rejectReason.trim()});setRejectReason('');setRejectOpen(false);}
 function contactAction(kind:'whatsapp'|'phone'){if(!selected)return;const raw=kind==='whatsapp'?(selected.party.whatsappNumber||selected.party.phone):selected.party.phone;if(!raw){setNotice(kind==='whatsapp'?'لا يوجد رقم واتساب أو هاتف صالح للمورد.':'لا يوجد رقم هاتف للمورد.');return}const number=normalizePhone(raw);if(!number){setNotice('رقم الاتصال غير صالح.');return}if(kind==='whatsapp')window.open(`https://wa.me/${number}`,'_blank','noopener,noreferrer');else window.location.href=`tel:${raw}`;}
 const identityFields=<><FormField label="اسم العرض" required><Input required value={name} onChange={e=>setName(e.target.value)}/></FormField><FormField label="الاسم القانوني"><Input value={legalName} onChange={e=>setLegalName(e.target.value)}/></FormField><FormField label="الهاتف"><Input value={phone} onChange={e=>setPhone(e.target.value)}/></FormField><FormField label="واتساب"><Input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/></FormField><FormField label="البريد الإلكتروني"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></FormField><FormField label="الرقم الضريبي"><Input value={taxIdentity} onChange={e=>setTaxIdentity(e.target.value)}/></FormField><FormField label="العنوان"><Textarea value={address} onChange={e=>setAddress(e.target.value)}/></FormField></>;
 const operationalFields=<><FormField label="التصنيف"><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="HOTEL">فندق</option><option value="AIRLINE">طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرات</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="العملة"><Input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></FormField><FormField label="أيام الائتمان"><Input inputMode="numeric" value={creditDays} onChange={e=>setCreditDays(e.target.value)}/></FormField><FormField label="مسؤول التواصل"><Input value={contact} onChange={e=>setContact(e.target.value)}/></FormField><FormField label="ملاحظات"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></FormField></>;
 const activeCount=rows.filter(v=>v.supplier.status==='ACTIVE').length,pendingCount=rows.filter(v=>v.supplier.approvalStatus==='PENDING').length,heldCount=rows.filter(v=>v.supplier.status==='ON_HOLD').length;
 return <section aria-label="إدارة الموردين" className="ui-dashboard">
  <div className="ui-metric-grid" aria-label="مؤشرات الموردين"><MetricCard label="إجمالي الموردين" value={rows.length}/><MetricCard label="نشط" value={activeCount} tone="success"/><MetricCard label="بانتظار الاعتماد" value={pendingCount} tone={pendingCount?'warning':'neutral'}/><MetricCard label="موقوف مؤقتًا" value={heldCount} tone={heldCount?'warning':'neutral'}/></div>
  <section className="ui-dashboard-grid" aria-label="البحث وإنشاء الموردين">
   <Card title="البحث والتصفية"><div className="ui-filter-grid"><FormField label="بحث"><Input aria-label="بحث الموردين" value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالكود أو الاسم أو الهاتف"/></FormField><FormField label="الحالة"><Select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">كل الحالات</option><option value="ACTIVE">نشط</option><option value="ON_HOLD">موقوف مؤقتًا</option><option value="INACTIVE">غير نشط</option></Select></FormField><FormField label="الاعتماد"><Select value={approvalFilter} onChange={e=>setApprovalFilter(e.target.value)}><option value="ALL">كل حالات الاعتماد</option><option value="APPROVED">معتمد</option><option value="PENDING">بانتظار الاعتماد</option><option value="REJECTED">مرفوض</option></Select></FormField><FormField label="التصنيف"><Select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="ALL">كل التصنيفات</option><option value="HOTEL">فندق</option><option value="AIRLINE">طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرات</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="الترتيب"><Select value={sort} onChange={e=>setSort(e.target.value)}><option value="CODE_ASC">الكود تصاعديًا</option><option value="CODE_DESC">الكود تنازليًا</option><option value="NAME_ASC">الاسم تصاعديًا</option><option value="NAME_DESC">الاسم تنازليًا</option></Select></FormField></div><p className="ui-results-count">المعروض: {visibleRows.length} من {rows.length}</p><ActionBar><Button type="button" variant="secondary" onClick={()=>window.location.assign('/procurement/supplier-intelligence')}>تقييم ومتابعة الموردين 360°</Button></ActionBar></Card>
   <DisclosureCard title="إنشاء مورد" description="افتح النموذج فقط عند إضافة مورد جديد؛ القائمة والفلاتر تظل متاحة في مساحة العمل."><form className="ui-filter-grid" onSubmit={create}>{identityFields}<FormField label="كود المورد" required><Input required value={code} onChange={e=>setCode(e.target.value)}/></FormField>{operationalFields}<Button type="submit">إنشاء المورد</Button></form>{notice&&<p role="status">{notice}</p>}</DisclosureCard>
  </section>
  <Card title="قائمة الموردين">{loading?<LoadingState/>:error?<ErrorState message={error}/>:!visibleRows.length?<EmptyState title={rows.length?'لا توجد نتائج مطابقة':'لا يوجد موردون'}/>:<DataGrid columns={['الكود','الاسم','التصنيف','الحالة','الاعتماد','إجراء']}>{visibleRows.map(v=><tr key={v.supplier.id}><td>{v.supplier.supplierCode}</td><td><strong>{v.party.displayName}</strong></td><td>{v.categories.map(categoryLabel).join('، ')||'—'}</td><td><Badge tone={v.supplier.status==='ACTIVE'?'success':v.supplier.status==='ON_HOLD'?'warning':'neutral'}>{statusLabel(v.supplier.status)}</Badge></td><td><Badge tone={v.supplier.approvalStatus==='APPROVED'?'success':v.supplier.approvalStatus==='REJECTED'?'error':'warning'}>{approvalLabel(v.supplier.approvalStatus)}</Badge></td><td><Button variant="secondary" onClick={()=>void choose(v)}>فتح الملف</Button></td></tr>)}</DataGrid>}</Card>
  {selected&&<section className="ui-dashboard-grid" aria-label="تفاصيل المورد والحسابات البنكية">
   <Card title={`ملف المورد — ${selected.party.displayName}`}><p>{selected.supplier.supplierCode} · {selected.categories.map(categoryLabel).join('، ')||'بدون تصنيف'}</p><p><Badge tone={selected.supplier.status==='ACTIVE'?'success':selected.supplier.status==='ON_HOLD'?'warning':'neutral'}>{statusLabel(selected.supplier.status)}</Badge> <Badge tone={selected.supplier.approvalStatus==='APPROVED'?'success':selected.supplier.approvalStatus==='REJECTED'?'error':'warning'}>{approvalLabel(selected.supplier.approvalStatus)}</Badge></p><ActionBar><Button type="button" variant="secondary" onClick={()=>contactAction('phone')}>اتصال</Button><Button type="button" variant="secondary" onClick={()=>contactAction('whatsapp')}>واتساب</Button></ActionBar><div className="ui-filter-grid">{identityFields}{operationalFields}</div><ActionBar><Button onClick={save}>حفظ بيانات الهوية والتشغيل</Button>{selected.supplier.approvalStatus!=='APPROVED'&&<Button onClick={()=>action('approval',{decision:'APPROVED'})}>اعتماد</Button>}<Button variant="danger" onClick={()=>setRejectOpen(true)}>رفض</Button>{selected.supplier.status==='ACTIVE'?<><Button variant="secondary" onClick={()=>action('deactivate')}>تعطيل</Button><Button variant="secondary" onClick={()=>action('hold')}>إيقاف مؤقت</Button></>:selected.supplier.status==='ON_HOLD'?<Button variant="secondary" onClick={()=>action('release-hold')}>رفع الإيقاف</Button>:<Button variant="secondary" onClick={()=>action('reactivate')}>إعادة تفعيل</Button>}</ActionBar><p role="note">لا يتم تنفيذ حذف مباشر للمورد؛ المورد المرتبط بعمليات يحتفظ بهويته وسجل التدقيق وتُدار حالته بالتعطيل أو إعادة التفعيل.</p></Card>
   <Card title="الحسابات البنكية">{banks.length?<DataGrid columns={['البنك','الحساب','IBAN','الحالة','افتراضي','إجراءات']}>{banks.map(b=><tr key={b.id}><td>{b.bankName??'—'}</td><td>{b.accountNumber??'—'}</td><td>{b.iban??'—'}</td><td>{b.active?'نشط':'غير نشط'}</td><td>{b.isDefault?'نعم':b.active?<Button variant="secondary" onClick={()=>action(`bank-accounts/${b.id}/default`)}>تعيين</Button>:'—'}</td><td><ActionBar><Button variant="secondary" onClick={()=>beginBankEdit(b)}>تعديل</Button><Button variant="secondary" onClick={()=>void updateBank(b,{active:!b.active,isDefault:false})}>{b.active?'تعطيل':'تفعيل'}</Button></ActionBar></td></tr>)}</DataGrid>:<EmptyState title="لا توجد حسابات بنكية"/>}<form className="ui-filter-grid" onSubmit={addBank}><FormField label="البنك"><Input value={bankName} onChange={e=>setBankName(e.target.value)}/></FormField><FormField label="رقم الحساب"><Input value={account} onChange={e=>setAccount(e.target.value)}/></FormField><FormField label="IBAN"><Input value={iban} onChange={e=>setIban(e.target.value)}/></FormField><Button type="submit">إضافة حساب</Button></form></Card>
  </section>}
  {notice&&!selected?<p role="status">{notice}</p>:null}
  <Dialog open={Boolean(editingBank)} title="تعديل الحساب البنكي" onClose={()=>setEditingBank(null)}><div className="ui-filter-grid"><FormField label="اسم البنك"><Input value={editBankName} onChange={e=>setEditBankName(e.target.value)}/></FormField><FormField label="رقم الحساب"><Input value={editAccount} onChange={e=>setEditAccount(e.target.value)}/></FormField><FormField label="IBAN"><Input value={editIban} onChange={e=>setEditIban(e.target.value)}/></FormField></div><ActionBar><Button onClick={()=>void saveBankEdit()}>حفظ التعديل</Button><Button variant="secondary" onClick={()=>setEditingBank(null)}>إلغاء</Button></ActionBar></Dialog>
  <Dialog open={rejectOpen} title="رفض اعتماد المورد" onClose={()=>setRejectOpen(false)}><FormField label="سبب الرفض" required><Textarea required value={rejectReason} onChange={e=>setRejectReason(e.target.value)}/></FormField><ActionBar><Button variant="danger" disabled={!rejectReason.trim()} onClick={()=>void reject()}>تأكيد الرفض</Button><Button variant="secondary" onClick={()=>setRejectOpen(false)}>إلغاء</Button></ActionBar></Dialog>
 </section>;
}
