import {useEffect,useState} from 'react';
import {HttpAdministrationClient,type AdministrationClient,type AdministrationContext} from './system-administration-client.js';
const areas=[['المستخدمون','users'],['الأدوار والصلاحيات','roles'],['الشركات','companies'],['الفروع والوصول','branches'],['الجلسات والأجهزة','sessions'],['سجل النشاط','audit'],['الملفات والمرفقات','files'],['الإشعارات','notifications'],['إعدادات الشركة','configuration/locale'],['استيراد وتصدير البيانات','imports'],['النسخ الاحتياطي والاستعادة','operations/backups'],['صحة النظام والتشخيص','operations/diagnostics']] as const;
const labels:Record<string,string>={id:'المعرّف',name:'الاسم',displayName:'الاسم',email:'البريد',status:'الحالة',active:'نشط',type:'النوع',fileName:'الملف',format:'الصيغة',createdAt:'تاريخ الإنشاء',readAt:'تاريخ القراءة',action:'العملية',resource:'المورد',backupProvider:'موفر النسخ',database:'قاعدة البيانات',schemaCompatibility:'توافق المخطط',runtimeVersion:'إصدار التشغيل',value:'القيمة'};
function valueOf(value:unknown){if(value===null||value===undefined)return'—';if(typeof value==='boolean')return value?'نعم':'لا';if(typeof value==='object')return 'بيانات محفوظة';return String(value)}
export function SystemAdministrationPage({client=new HttpAdministrationClient(),context}:{client?:AdministrationClient;context?:AdministrationContext}={}){
 const [selected,setSelected]=useState('users'),[rows,setRows]=useState<readonly unknown[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState('');const ctx=context??{token:'',companyId:'',branchId:''};
 async function load(path=selected){setSelected(path);if(!ctx.token)return;setLoading(true);setMessage('');setSuccess('');try{setRows(await client.list(path,ctx))}catch(error){setMessage(error instanceof Error?error.message:'تعذر التحميل')}finally{setLoading(false)}}
 async function createBackup(){setLoading(true);setMessage('');try{await client.action('operations/backups',ctx,{});setSuccess('تم إرسال طلب النسخ الاحتياطي.');await load('operations/backups')}catch(error){setMessage(error instanceof Error?error.message:'تعذر تنفيذ العملية')}finally{setLoading(false)}}
 useEffect(()=>{if(ctx.token)void load('users')},[ctx.token,ctx.companyId,ctx.branchId]);
 const records=rows.filter((row):row is Record<string,unknown>=>Boolean(row)&&typeof row==='object'&&!Array.isArray(row));
 return <main dir="rtl" aria-labelledby="admin-title"><header><p>إدارة المنصة</p><h1 id="admin-title">إدارة النظام والعمليات</h1><p>لوحة عربية موحدة وآمنة لإدارة الوصول والبيانات واستمرارية التشغيل.</p></header><nav aria-label="مجالات إدارة النظام" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:'.5rem'}}>{areas.map(([title,path])=><button key={path} type="button" aria-pressed={selected===path} disabled={!ctx.token} onClick={()=>void load(path)}>{title}</button>)}</nav><section aria-live="polite" style={{marginTop:'1rem'}}>{!ctx.token?<p>اختر الشركة والفرع وسجّل الدخول لعرض أدوات الإدارة.</p>:<><div style={{display:'flex',gap:'.5rem',flexWrap:'wrap'}}><button type="button" disabled={loading} onClick={()=>void load()}>تحديث البيانات</button>{selected==='operations/backups'?<button type="button" disabled={loading} onClick={()=>void createBackup()}>إنشاء نسخة احتياطية</button>:null}</div>{loading?<p>جارٍ التحميل…</p>:message?<p role="alert">{message}</p>:success?<p role="status">{success}</p>:records.length===0?<p>لا توجد بيانات متاحة.</p>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:'1rem',marginTop:'1rem'}}>{records.map((record,index)=><article key={String(record.id??index)} style={{border:'1px solid currentColor',borderRadius:'.5rem',padding:'1rem',overflowWrap:'anywhere'}}>{Object.entries(record).filter(([key,value])=>labels[key]&&typeof value!=='object').map(([key,value])=><p key={key}><strong>{labels[key]}: </strong>{valueOf(value)}</p>)}</article>)}</div>}</>}</section></main>
}
