import type{TenantSession,TenantSubscription,TenantBranch}from'./tenant-session.js';
type LoginResponse={token:string;userId:string;username:string;mustChangePassword:boolean;mfaEnabled:boolean;expiresAt:string|Date;companyId:string;companyCode:string;companyName:string;branches:TenantBranch[];defaultBranchId:string;subscription:TenantSubscription};
export class TenantAuthClient{
 constructor(private readonly base='/api'){}
 async login(input:{companyCode:string;username:string;password:string;mfaCode?:string}):Promise<TenantSession>{
  const response=await fetch(this.base+'/saas/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});
  const body=await response.json().catch(()=>({})) as Partial<LoginResponse>&{message?:string};
  if(!response.ok)throw new Error(body.message??'تعذر تسجيل الدخول. تحقق من كود الشركة وبيانات الدخول.');
  if(!body.token||!body.companyId||!body.companyCode||!body.companyName||!body.userId||!body.username||typeof body.mustChangePassword!=='boolean'||typeof body.mfaEnabled!=='boolean'||!body.expiresAt||!body.defaultBranchId||!body.branches||!body.subscription)throw new Error('استجابة تسجيل الدخول غير مكتملة.');
  return{token:body.token,userId:body.userId,username:body.username,mustChangePassword:body.mustChangePassword,mfaEnabled:body.mfaEnabled,expiresAt:new Date(body.expiresAt).toISOString(),companyId:body.companyId,companyCode:body.companyCode,companyName:body.companyName,branches:body.branches,branchId:body.defaultBranchId,subscription:body.subscription};
 }
 async initialPassword(token:string,companyId:string,newPassword:string,newUsername?:string){const response=await fetch(this.base+'/saas/credentials/initial-password',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,'x-company-id':companyId},body:JSON.stringify({newPassword,newUsername})});const body=await response.json().catch(()=>({})) as {username?:string;mustChangePassword?:boolean;message?:string};if(!response.ok)throw new Error(body.message??'تعذر تغيير كلمة المرور.');if(!body.username)throw new Error('استجابة تغيير كلمة المرور غير مكتملة.');return{username:body.username,mustChangePassword:false as const};}
 async updateCredentials(token:string,companyId:string,input:{currentPassword:string;newUsername?:string;newPassword?:string}){const response=await fetch(this.base+'/saas/credentials',{method:'PATCH',headers:{'content-type':'application/json',authorization:'Bearer '+token,'x-company-id':companyId},body:JSON.stringify(input)});const body=await response.json().catch(()=>({})) as {username?:string;mustChangePassword?:boolean;message?:string};if(!response.ok)throw new Error(body.message??'تعذر تحديث بيانات الدخول.');if(!body.username)throw new Error('استجابة تحديث بيانات الدخول غير مكتملة.');return{username:body.username,mustChangePassword:false as const};}
 async mfaStatus(token:string,companyId:string){const response=await fetch(this.base+'/saas/mfa',{headers:{authorization:'Bearer '+token,'x-company-id':companyId}});const body=await response.json().catch(()=>({})) as {enabled?:boolean;message?:string};if(!response.ok)throw new Error(body.message??'تعذر قراءة حالة التحقق الثنائي.');return{enabled:Boolean(body.enabled)};}
 async beginMfa(token:string,companyId:string){const response=await fetch(this.base+'/saas/mfa/enroll',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,'x-company-id':companyId},body:'{}'});const body=await response.json().catch(()=>({})) as {secret?:string;otpauthUri?:string;message?:string};if(!response.ok)throw new Error(body.message??'تعذر بدء إعداد التحقق الثنائي.');if(!body.secret||!body.otpauthUri)throw new Error('استجابة إعداد التحقق الثنائي غير مكتملة.');return{secret:body.secret,otpauthUri:body.otpauthUri};}
 async confirmMfa(token:string,companyId:string,code:string){const response=await fetch(this.base+'/saas/mfa/confirm',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,'x-company-id':companyId},body:JSON.stringify({code})});const body=await response.json().catch(()=>({})) as {enabled?:boolean;message?:string};if(!response.ok)throw new Error(body.message??'رمز التحقق غير صحيح.');return{enabled:Boolean(body.enabled)};}
 async disableMfa(token:string,companyId:string,currentPassword:string,code:string){const response=await fetch(this.base+'/saas/mfa/disable',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,'x-company-id':companyId},body:JSON.stringify({currentPassword,code})});const body=await response.json().catch(()=>({})) as {enabled?:boolean;message?:string};if(!response.ok)throw new Error(body.message??'تعذر إلغاء التحقق الثنائي.');return{enabled:Boolean(body.enabled)};}
 async logout(token:string){await fetch(this.base+'/saas/logout',{method:'POST',headers:{authorization:'Bearer '+token}}).catch(()=>undefined);}
}
