import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { ActionBar, Button, Card, DataGrid, EmptyState, FormField, Input, MetricCard, Select, Textarea, Toast } from './ui.js';
import { tourismContractInventoryApi, type InventoryResult, type TourismInventoryContractOption, type TourismInventoryProgramReference, type TourismInventoryResourceOption, type TourismInventorySupplierReference } from './tourism-contract-inventory-client.js';
import { TourismContractInventoryCorrectiveSection } from './tourism-contract-inventory-corrective-section.js';

type ResourceType='HOTEL'|'FLIGHT_BLOCK'|'TRANSPORT'|'VISA'|'SERVICE';
const today=()=>new Date().toISOString().slice(0,10);
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية.';
const blankTerms={name:'',shortName:'',city:'',currency:'EGP',boardBasis:'',cancellationPolicy:'',airline:'',returnFlightNumber:'',returnOrigin:'',returnDestination:'',returnDepartureAt:'',unit:'UNIT',unitCost:'',ticketingDeadline:'',fareClass:'',baggage:'',singleRate:'',doubleRate:'',tripleRate:'',quadRate:'',quintRate:''};

function Details({title,value}:{title:string;value:InventoryResult|null}){
 if(!value)return null;
 const rows=Object.entries(value).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v));
 return <Card title={title}>{rows.length?<DataGrid columns={['البيان','القيمة']}>{rows.map(([key,value])=><tr key={key}><td>{key}</td><td>{value===null?'—':String(value)}</td></tr>)}</DataGrid>:<p>تم تحميل السجل من المالك المعتمد.</p>}</Card>;
}

function contractLabel(item:TourismInventoryContractOption){return `${item.type} — ${item.effectiveFrom} إلى ${item.effectiveTo}${item.supplierId?' — مورد مرتبط':''}`;}
function evidenceSource(type:'FLIGHT_BLOCK'|'VISA'){return type==='FLIGHT_BLOCK'?'TOURISM_FLIGHT_SEGMENT':'TOURISM_VISA_BATCH';}

export function TourismContractInventoryPage(){
 const[notice,setNotice]=useState(''),[result,setResult]=useState<InventoryResult|null>(null),[versions,setVersions]=useState<InventoryResult[]>([]),[catalog,setCatalog]=useState<TourismInventoryContractOption[]>([]);
 const[contractId,setContractId]=useState(''),[allocationId,setAllocationId]=useState('');
 const[suppliers,setSuppliers]=useState<TourismInventorySupplierReference[]>([]),[programs,setPrograms]=useState<TourismInventoryProgramReference[]>([]);
 const[contract,setContract]=useState({type:'HOTEL' as ResourceType,supplierId:'',effectiveFrom:today(),effectiveTo:today()}),[terms,setTerms]=useState(blankTerms);
 const[resource,setResource]=useState({type:'HOTEL' as ResourceType,resourceId:'',secondary:'',serviceDate:today(),periodEnd:today(),quantity:'1',category:'OTHER',description:'',unit:'UNIT',releaseDeadline:''});
 const[allocation,setAllocation]=useState({contractId:'',resourceId:'',sourceId:'',quantity:'1',evidenceSourceType:'',evidenceSourceId:''});
 const[stop,setStop]=useState({contractId:'',reason:'',effectiveFrom:today(),effectiveTo:today()});

 async function refreshCatalog(){try{setCatalog(await tourismContractInventoryApi.catalog());}catch{setNotice('تعذر تحميل كتالوج العقود والمخزون من المالك المعتمد.');}}
 useEffect(()=>{void(async()=>{const[sv,pv,cv]=await Promise.allSettled([tourismContractInventoryApi.suppliers(),tourismContractInventoryApi.programs(),tourismContractInventoryApi.catalog()]);if(sv.status==='fulfilled')setSuppliers(sv.value);else setNotice('تعذر تحميل الموردين من المالك المعتمد.');if(pv.status==='fulfilled')setPrograms(pv.value);else setNotice('تعذر تحميل البرامج السياحية من المالك المعتمد.');if(cv.status==='fulfilled')setCatalog(cv.value);else setNotice('تعذر تحميل العقود والمخزون من المالك المعتمد.');})();},[]);

 const allocationContract=useMemo(()=>catalog.find(item=>item.id===allocation.contractId),[catalog,allocation.contractId]);
 const allocationResource=useMemo(()=>allocationContract?.resources.find(item=>item.id===allocation.resourceId),[allocationContract,allocation.resourceId]);
 const currentContract=useMemo(()=>catalog.find(item=>item.id===contractId),[catalog,contractId]);

 async function run(label:string,operation:()=>Promise<InventoryResult|null>,reloadCatalog=false){try{const value=await operation();setResult(value??null);setNotice(label);if(reloadCatalog)await refreshCatalog();return value;}catch(error){setNotice(errorMessage(error));return null;}}
 function commercialTerms(){
  const common={name:terms.name.trim()||undefined,shortName:terms.shortName.trim()||undefined,currency:terms.currency.trim().toUpperCase()||undefined,cancellationPolicy:terms.cancellationPolicy.trim()||undefined};
  if(contract.type==='HOTEL')return{commercial:{...common,city:terms.city.trim()||undefined,boardBasis:terms.boardBasis.trim()||undefined,roomRates:{single:terms.singleRate||undefined,double:terms.doubleRate||undefined,triple:terms.tripleRate||undefined,quad:terms.quadRate||undefined,quint:terms.quintRate||undefined}}};
  if(contract.type==='FLIGHT_BLOCK')return{commercial:{...common,airline:terms.airline.trim()||undefined,returnLeg:{flightNumber:terms.returnFlightNumber.trim()||undefined,origin:terms.returnOrigin.trim()||undefined,destination:terms.returnDestination.trim()||undefined,departureAt:terms.returnDepartureAt||undefined},ticketingDeadline:terms.ticketingDeadline||undefined,fareClass:terms.fareClass.trim()||undefined,baggage:terms.baggage.trim()||undefined},...(terms.unitCost.trim()?{standalonePricing:{currency:terms.currency.trim().toUpperCase(),unit:terms.unit.trim()||'SEAT',unitCost:terms.unitCost.trim()}}:{})};
  return{commercial:{...common},...(terms.unitCost.trim()?{standalonePricing:{currency:terms.currency.trim().toUpperCase(),unit:terms.unit.trim()||'UNIT',unitCost:terms.unitCost.trim()}}:{})};
 }
 async function createContract(e:FormEvent){e.preventDefault();const value=await run('تم إنشاء العقد.',()=>tourismContractInventoryApi.createContract({...contract,...(contract.supplierId?{supplierId:contract.supplierId}:{}),commandKey:crypto.randomUUID()}),true);if(!value)return;const id=String(value.id??'');if(!id)return;setContractId(id);setAllocation(v=>({...v,contractId:id,resourceId:''}));setStop(v=>({...v,contractId:id}));const commercial=commercialTerms();if(Object.keys(commercial).length){await run('تم إنشاء العقد وحفظ شروطه التجارية كنسخة عقد.',()=>tourismContractInventoryApi.amendContract(id,{terms:commercial,effectiveFrom:contract.effectiveFrom,effectiveTo:contract.effectiveTo,commandKey:crypto.randomUUID()}),true);}try{setVersions(await tourismContractInventoryApi.versions(id));}catch{setVersions([]);}}
 async function openContract(){if(!contractId)return;await run('تم تحميل العقد.',()=>tourismContractInventoryApi.contract(contractId));try{setVersions(await tourismContractInventoryApi.versions(contractId));}catch{setVersions([]);}}
 async function createResource(e:FormEvent){e.preventDefault();if(!contractId){setNotice('اختر عقدًا أولًا.');return;}const common={contractId,commandKey:crypto.randomUUID()};const op=resource.type==='HOTEL'?()=>tourismContractInventoryApi.createHotel({...common,hotelId:resource.resourceId,...(resource.secondary?{roomId:resource.secondary}:{}),serviceDate:resource.serviceDate,contractedQuantity:resource.quantity}):resource.type==='FLIGHT_BLOCK'?()=>tourismContractInventoryApi.createFlight({...common,flightNumber:resource.resourceId,origin:resource.secondary.split('>')[0]?.trim()||'',destination:resource.secondary.split('>')[1]?.trim()||'',departureDate:resource.serviceDate,totalSeats:resource.quantity}):resource.type==='TRANSPORT'?()=>tourismContractInventoryApi.createTransport({...common,vehicleId:resource.resourceId,capacityUnits:resource.quantity,periodStart:resource.serviceDate,periodEnd:resource.periodEnd}):resource.type==='VISA'?()=>tourismContractInventoryApi.createVisa({...common,visaType:resource.resourceId,...(resource.secondary?{nationality:resource.secondary}:{}),quotaTotal:resource.quantity,effectiveFrom:resource.serviceDate,effectiveTo:resource.periodEnd}):()=>tourismContractInventoryApi.createService({...common,category:resource.category as 'CAMP'|'MEAL'|'VISIT'|'GUIDE'|'RAWDA'|'INSURANCE'|'OTHER',name:resource.resourceId,description:resource.description||undefined,unit:resource.unit,serviceStart:resource.serviceDate,serviceEnd:resource.periodEnd,capacity:resource.quantity,releaseDeadline:resource.releaseDeadline||undefined});await run('تمت إضافة مورد المخزون.',op,true);}
 function chooseAllocationContract(id:string){setAllocation(v=>({...v,contractId:id,resourceId:'',evidenceSourceType:'',evidenceSourceId:''}));}
 function chooseAllocationResource(id:string){setAllocation(v=>({...v,resourceId:id,evidenceSourceType:'',evidenceSourceId:''}));}
 async function checkAvailability(){if(!allocationResource)return;await run('تم فحص الإتاحة.',()=>tourismContractInventoryApi.availability({contractId:allocationResource.contractId,resourceType:allocationResource.resourceType,resourceId:allocationResource.id,serviceDate:allocationResource.serviceDate,...(allocationResource.periodEnd?{periodEnd:allocationResource.periodEnd}:{})}));}
 async function allocate(e:FormEvent){e.preventDefault();if(!allocationResource)return;const needsEvidence=allocationResource.resourceType==='FLIGHT_BLOCK'||allocationResource.resourceType==='VISA';if(needsEvidence&&(!allocation.evidenceSourceType.trim()||!allocation.evidenceSourceId.trim())){setNotice('مرجع التشغيل المعتمد مطلوب لهذا النوع من المخزون.');return;}await run('تم إنشاء التخصيص.',async()=>{const extra=allocationResource.resourceType==='FLIGHT_BLOCK'?{flightSegmentReference:{sourceType:allocation.evidenceSourceType.trim(),sourceId:allocation.evidenceSourceId.trim()}}:allocationResource.resourceType==='VISA'?{visaBatchReference:{sourceType:allocation.evidenceSourceType.trim(),sourceId:allocation.evidenceSourceId.trim()}}:{};const value=await tourismContractInventoryApi.allocate({contractId:allocationResource.contractId,resourceType:allocationResource.resourceType,resourceId:allocationResource.id,program:{sourceType:'TOURISM_PROGRAM',sourceId:allocation.sourceId},serviceDate:allocationResource.serviceDate,...(allocationResource.periodEnd?{periodEnd:allocationResource.periodEnd}:{}),quantity:allocation.quantity,...extra,commandKey:crypto.randomUUID()});const id=String(value.allocationId??(value.allocation&&typeof value.allocation==='object'?(value.allocation as {id?:string}).id:'')??'');if(id)setAllocationId(id);return value;},true);}
 async function openAllocation(){if(allocationId)await run('تم تحميل التخصيص.',()=>tourismContractInventoryApi.allocation(allocationId));}
 async function release(){if(allocationId)await run('تم تنفيذ طلب فك التخصيص.',()=>tourismContractInventoryApi.release(allocationId,{quantity:allocation.quantity,commandKey:crypto.randomUUID()}),true);}
 async function stopSale(e:FormEvent){e.preventDefault();await run('تم تسجيل Stop Sale.',()=>tourismContractInventoryApi.stopSale({...stop,commandKey:crypto.randomUUID()}),true);}

 return <section dir="rtl" className="ui-page-stack" aria-label="التعاقدات والمخزون">
  {notice?<Toast tone={notice.startsWith('تم')?'success':'error'}>{notice}</Toast>:null}
  <Card title="التعاقدات والمخزون"><p>مساحة موحدة لعقود الفنادق والطيران والنقل والتأشيرات والخدمات والسعات والتخصيصات. بيانات العقد التجارية تحفظ كنسخ Versioned، بينما الفواتير والديون والسداد تظل لدى Billing / Accounting / Treasury.</p><Button variant="secondary" onClick={()=>void refreshCatalog()}>تحديث الكتالوج</Button></Card>
  <div className="ui-metric-grid"><MetricCard label="العقود النشطة" value={catalog.length}/><MetricCard label="العقد الحالي" value={contractId||'—'}/><MetricCard label="التخصيص الحالي" value={allocationId||'—'}/><MetricCard label="نسخ العقد" value={versions.length}/></div>
  <div className="ui-grid-md">
   <Card title="إنشاء عقد"><form onSubmit={createContract} className="ui-page-stack"><FormField label="نوع العقد"><Select value={contract.type} onChange={e=>setContract({...contract,type:e.target.value as ResourceType})}><option value="HOTEL">فندق</option><option value="FLIGHT_BLOCK">بلوك طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرات</option><option value="SERVICE">خدمة متعاقد عليها</option></Select></FormField><FormField label="المورد"><Select value={contract.supplierId} onChange={e=>setContract({...contract,supplierId:e.target.value})}><option value="">بدون مورد محدد</option>{suppliers.filter(item=>item.supplier.status==='ACTIVE'&&item.supplier.approvalStatus==='APPROVED').map(item=><option key={item.supplier.id} value={item.supplier.id}>{item.supplier.supplierCode} — {item.party.displayName}</option>)}</Select></FormField><FormField label="من"><Input required type="date" value={contract.effectiveFrom} onChange={e=>setContract({...contract,effectiveFrom:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={contract.effectiveTo} onChange={e=>setContract({...contract,effectiveTo:e.target.value})}/></FormField>
    <FormField label={contract.type==='FLIGHT_BLOCK'?'اسم البلوك / العقد':'اسم العقد'}><Input value={terms.name} onChange={e=>setTerms({...terms,name:e.target.value})}/></FormField><FormField label="الاسم المختصر"><Input value={terms.shortName} onChange={e=>setTerms({...terms,shortName:e.target.value})}/></FormField><FormField label="العملة"><Input value={terms.currency} onChange={e=>setTerms({...terms,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="سياسة الإلغاء"><Textarea value={terms.cancellationPolicy} onChange={e=>setTerms({...terms,cancellationPolicy:e.target.value})}/></FormField>
    {contract.type==='HOTEL'?<><FormField label="المدينة"><Input value={terms.city} onChange={e=>setTerms({...terms,city:e.target.value})}/></FormField><FormField label="نظام الإقامة / الوجبات"><Input value={terms.boardBasis} onChange={e=>setTerms({...terms,boardBasis:e.target.value})}/></FormField><FormField label="سعر Single"><Input inputMode="decimal" value={terms.singleRate} onChange={e=>setTerms({...terms,singleRate:e.target.value})}/></FormField><FormField label="سعر Double"><Input inputMode="decimal" value={terms.doubleRate} onChange={e=>setTerms({...terms,doubleRate:e.target.value})}/></FormField><FormField label="سعر Triple"><Input inputMode="decimal" value={terms.tripleRate} onChange={e=>setTerms({...terms,tripleRate:e.target.value})}/></FormField><FormField label="سعر Quad"><Input inputMode="decimal" value={terms.quadRate} onChange={e=>setTerms({...terms,quadRate:e.target.value})}/></FormField><FormField label="سعر Quint"><Input inputMode="decimal" value={terms.quintRate} onChange={e=>setTerms({...terms,quintRate:e.target.value})}/></FormField></>:null}
    {contract.type==='FLIGHT_BLOCK'?<><FormField label="شركة الطيران"><Input value={terms.airline} onChange={e=>setTerms({...terms,airline:e.target.value})}/></FormField><FormField label="رحلة العودة"><Input value={terms.returnFlightNumber} onChange={e=>setTerms({...terms,returnFlightNumber:e.target.value})}/></FormField><FormField label="من / إلى العودة"><div className="ui-grid-md"><Input value={terms.returnOrigin} onChange={e=>setTerms({...terms,returnOrigin:e.target.value})} placeholder="Origin"/><Input value={terms.returnDestination} onChange={e=>setTerms({...terms,returnDestination:e.target.value})} placeholder="Destination"/></div></FormField><FormField label="موعد العودة"><Input type="datetime-local" value={terms.returnDepartureAt} onChange={e=>setTerms({...terms,returnDepartureAt:e.target.value})}/></FormField><FormField label="تكلفة المقعد التجارية"><Input inputMode="decimal" value={terms.unitCost} onChange={e=>setTerms({...terms,unitCost:e.target.value})}/></FormField><FormField label="آخر موعد للتذاكر"><Input type="date" value={terms.ticketingDeadline} onChange={e=>setTerms({...terms,ticketingDeadline:e.target.value})}/></FormField><FormField label="Fare Class"><Input value={terms.fareClass} onChange={e=>setTerms({...terms,fareClass:e.target.value})}/></FormField><FormField label="الأمتعة"><Input value={terms.baggage} onChange={e=>setTerms({...terms,baggage:e.target.value})}/></FormField></>:null}
    {['TRANSPORT','VISA','SERVICE'].includes(contract.type)?<><FormField label="وحدة التسعير"><Input value={terms.unit} onChange={e=>setTerms({...terms,unit:e.target.value})}/></FormField><FormField label="تكلفة الوحدة التجارية"><Input inputMode="decimal" value={terms.unitCost} onChange={e=>setTerms({...terms,unitCost:e.target.value})}/></FormField></>:null}
    <Button type="submit">إنشاء العقد وحفظ الشروط</Button></form><hr/><FormField label="فتح عقد موجود"><Select value={contractId} onChange={e=>{setContractId(e.target.value);setStop(v=>({...v,contractId:e.target.value}));}}><option value="">اختر عقدًا</option>{catalog.map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><Button variant="secondary" disabled={!contractId} onClick={()=>void openContract()}>فتح العقد ونسخه</Button></Card>
   <Card title="إضافة سعة / مخزون"><p>{currentContract?`العقد: ${contractLabel(currentContract)}`:'اختر عقدًا من القائمة أولًا.'}</p><form onSubmit={createResource}><FormField label="نوع المورد"><Select value={resource.type} onChange={e=>setResource({...resource,type:e.target.value as ResourceType})}><option value="HOTEL">غرف فندق</option><option value="FLIGHT_BLOCK">بلوك طيران</option><option value="TRANSPORT">سعة نقل</option><option value="VISA">حصة تأشيرات</option><option value="SERVICE">خدمة متعاقد عليها</option></Select></FormField><FormField label={resource.type==='HOTEL'?'معرّف الفندق':resource.type==='FLIGHT_BLOCK'?'رقم الرحلة':resource.type==='TRANSPORT'?'معرّف المركبة':resource.type==='VISA'?'نوع التأشيرة':'اسم الخدمة'} required><Input required value={resource.resourceId} onChange={e=>setResource({...resource,resourceId:e.target.value})}/></FormField><FormField label={resource.type==='FLIGHT_BLOCK'?'المسار — مثال CAI > JED':resource.type==='VISA'?'الجنسية':resource.type==='HOTEL'?'نوع/معرّف الغرفة':'تفصيل إضافي'}><Input value={resource.secondary} onChange={e=>setResource({...resource,secondary:e.target.value})}/></FormField>{resource.type==='SERVICE'?<><FormField label="تصنيف الخدمة"><Select value={resource.category} onChange={e=>setResource({...resource,category:e.target.value})}><option value="CAMP">مخيم</option><option value="MEAL">وجبة</option><option value="VISIT">زيارة</option><option value="GUIDE">مرشد</option><option value="RAWDA">روضة</option><option value="INSURANCE">تأمين</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="الوصف"><Textarea value={resource.description} onChange={e=>setResource({...resource,description:e.target.value})}/></FormField><FormField label="الوحدة"><Input required value={resource.unit} onChange={e=>setResource({...resource,unit:e.target.value})}/></FormField><FormField label="Release deadline"><Input type="date" value={resource.releaseDeadline} onChange={e=>setResource({...resource,releaseDeadline:e.target.value})}/></FormField></>:null}<FormField label="تاريخ البداية"><Input required type="date" value={resource.serviceDate} onChange={e=>setResource({...resource,serviceDate:e.target.value})}/></FormField>{['TRANSPORT','VISA','SERVICE'].includes(resource.type)?<FormField label="تاريخ النهاية"><Input required type="date" value={resource.periodEnd} onChange={e=>setResource({...resource,periodEnd:e.target.value})}/></FormField>:null}<FormField label="الكمية / السعة"><Input required inputMode="decimal" value={resource.quantity} onChange={e=>setResource({...resource,quantity:e.target.value})}/></FormField><Button type="submit" disabled={!contractId}>إضافة للمخزون</Button></form></Card>
  </div>
  <div className="ui-grid-md">
   <Card title="الإتاحة والتخصيص"><form onSubmit={allocate}><FormField label="العقد" required><Select required value={allocation.contractId} onChange={e=>chooseAllocationContract(e.target.value)}><option value="">اختر عقدًا نشطًا</option>{catalog.filter(item=>item.resources.length>0).map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><FormField label="المورد / السعة" required><Select required disabled={!allocationContract} value={allocation.resourceId} onChange={e=>chooseAllocationResource(e.target.value)}><option value="">اختر السعة</option>{allocationContract?.resources.map(item=><option key={item.id} value={item.id}>{item.label} — متاح {item.availableQuantity}</option>)}</Select></FormField><FormField label="البرنامج / المصدر" required><Select required value={allocation.sourceId} onChange={e=>setAllocation({...allocation,sourceId:e.target.value})}><option value="">اختر برنامجًا</option>{programs.filter(program=>!['CLOSED','CANCELLED'].includes(program.status)).map(program=><option key={program.id} value={program.id}>{program.code} — {program.nameAr}</option>)}</Select></FormField>{allocationResource?<><FormField label="تاريخ الخدمة"><Input disabled value={allocationResource.serviceDate}/></FormField>{allocationResource.periodEnd?<FormField label="حتى"><Input disabled value={allocationResource.periodEnd}/></FormField>:null}<FormField label="الكمية" required hint={`المتاح: ${allocationResource.availableQuantity}`}><Input required inputMode="decimal" value={allocation.quantity} onChange={e=>setAllocation({...allocation,quantity:e.target.value})}/></FormField></>:null}{allocationResource&&['FLIGHT_BLOCK','VISA'].includes(allocationResource.resourceType)?<><FormField label="نوع مرجع التشغيل" required><Input required value={allocation.evidenceSourceType||evidenceSource(allocationResource.resourceType as 'FLIGHT_BLOCK'|'VISA')} onChange={e=>setAllocation({...allocation,evidenceSourceType:e.target.value})}/></FormField><FormField label={allocationResource.resourceType==='FLIGHT_BLOCK'?'مرجع قطاع الطيران':'مرجع دفعة التأشيرات'} required><Input required value={allocation.evidenceSourceId} onChange={e=>setAllocation({...allocation,evidenceSourceId:e.target.value})}/></FormField></>:null}<ActionBar><Button type="button" variant="secondary" disabled={!allocationResource} onClick={()=>void checkAvailability()}>فحص الإتاحة</Button><Button type="submit" disabled={!allocationResource||!allocation.sourceId}>تخصيص السعة</Button></ActionBar></form><hr/><FormField label="التخصيص الحالي / بحث إداري"><Input value={allocationId} onChange={e=>setAllocationId(e.target.value)} placeholder="يظهر تلقائيًا بعد التخصيص أو أدخل ID للبحث الإداري"/></FormField><ActionBar><Button variant="secondary" disabled={!allocationId} onClick={()=>void openAllocation()}>فتح التخصيص</Button><Button variant="danger" disabled={!allocationId} onClick={()=>void release()}>فك الكمية المحددة</Button></ActionBar></Card>
   <Card title="إيقاف البيع Stop Sale"><form onSubmit={stopSale}><FormField label="العقد" required><Select required value={stop.contractId} onChange={e=>setStop({...stop,contractId:e.target.value})}><option value="">اختر العقد</option>{catalog.map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><FormField label="السبب" required><Input required value={stop.reason} onChange={e=>setStop({...stop,reason:e.target.value})}/></FormField><FormField label="من"><Input required type="date" value={stop.effectiveFrom} onChange={e=>setStop({...stop,effectiveFrom:e.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={stop.effectiveTo} onChange={e=>setStop({...stop,effectiveTo:e.target.value})}/></FormField><Button variant="danger" type="submit">تسجيل إيقاف البيع</Button></form></Card>
  </div>
  {!catalog.length?<EmptyState title="لا توجد عقود نشطة في الكتالوج بعد"/>:null}
  <TourismContractInventoryCorrectiveSection contractId={contractId}/>
  {versions.length?<Card title="نسخ العقد"><DataGrid columns={['الإصدار','من','إلى','الشروط']}>{versions.map((v,index)=><tr key={String(v.id??index)}><td>{String(v.version??index+1)}</td><td>{String(v.effectiveFrom??'—')}</td><td>{String(v.effectiveTo??'—')}</td><td>{v.terms&&typeof v.terms==='object'?JSON.stringify(v.terms):'—'}</td></tr>)}</DataGrid></Card>:null}
  <Details title="آخر نتيجة" value={result}/>
 </section>;
}
