import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { ActionBar, Button, Card, DataGrid, EmptyState, FormField, Input, MetricCard, Select, Textarea, Toast } from './ui.js';
import { tourismContractInventoryApi, type InventoryResult, type TourismInventoryContractOption, type TourismInventoryProgramReference, type TourismInventoryResourceOption, type TourismInventoryResourceType, type TourismInventorySupplierReference } from './tourism-contract-inventory-client.js';
import { TourismContractInventoryCorrectiveSection } from './tourism-contract-inventory-corrective-section.js';

const today=()=>new Date().toISOString().slice(0,10);
const failure=(error:unknown)=>error instanceof Error?error.message:'تعذر تنفيذ العملية.';
const defaultEvidence=(type:TourismInventoryResourceType)=>type==='FLIGHT_BLOCK'?'TOURISM_FLIGHT_SEGMENT':type==='VISA'?'TOURISM_VISA_BATCH':'';
const contractLabel=(item:TourismInventoryContractOption)=>`${item.type} — ${item.effectiveFrom} إلى ${item.effectiveTo}${item.supplierId?' — مورد مرتبط':''}`;
const blankTerms={name:'',shortName:'',city:'',currency:'EGP',boardBasis:'',cancellationPolicy:'',airline:'',returnFlightNumber:'',returnOrigin:'',returnDestination:'',returnDepartureAt:'',unit:'UNIT',unitCost:'',ticketingDeadline:'',fareClass:'',baggage:'',singleRate:'',doubleRate:'',tripleRate:'',quadRate:'',quintRate:''};
const blankResource={resourceId:'',secondary:'',serviceDate:today(),periodEnd:today(),quantity:'1',category:'OTHER',description:'',unit:'UNIT',releaseDeadline:''};

function ResultCard({value}:{value:InventoryResult|null}){
 if(!value)return null;
 const rows=Object.entries(value).filter(([,item])=>item===null||['string','number','boolean'].includes(typeof item));
 return <Card title="آخر نتيجة">{rows.length?<DataGrid columns={['البيان','القيمة']}>{rows.map(([key,item])=><tr key={key}><td>{key}</td><td>{item===null?'—':String(item)}</td></tr>)}</DataGrid>:<p>تم تنفيذ العملية لدى المالك المعتمد.</p>}</Card>;
}

export function TourismContractInventoryPage(){
 const[catalog,setCatalog]=useState<TourismInventoryContractOption[]>([]),[suppliers,setSuppliers]=useState<TourismInventorySupplierReference[]>([]),[programs,setPrograms]=useState<TourismInventoryProgramReference[]>([]);
 const[notice,setNotice]=useState(''),[result,setResult]=useState<InventoryResult|null>(null),[versions,setVersions]=useState<InventoryResult[]>([]);
 const[contract,setContract]=useState({type:'HOTEL' as TourismInventoryResourceType,supplierId:'',effectiveFrom:today(),effectiveTo:today()}),[terms,setTerms]=useState(blankTerms);
 const[contractId,setContractId]=useState(''),[resource,setResource]=useState(blankResource),[allocationId,setAllocationId]=useState('');
 const[allocation,setAllocation]=useState({contractId:'',resourceId:'',sourceId:'',quantity:'1',evidenceSourceType:'',evidenceSourceId:''});
 const[stop,setStop]=useState({contractId:'',reason:'',effectiveFrom:today(),effectiveTo:today()});

 const selectedContract=useMemo(()=>catalog.find(item=>item.id===contractId),[catalog,contractId]);
 const allocationContract=useMemo(()=>catalog.find(item=>item.id===allocation.contractId),[catalog,allocation.contractId]);
 const allocationResource=useMemo(()=>allocationContract?.resources.find(item=>item.id===allocation.resourceId),[allocationContract,allocation.resourceId]);
 const resourceType=selectedContract?.type;

 async function refresh(){try{setCatalog(await tourismContractInventoryApi.catalog());}catch(error){setNotice(failure(error));}}
 useEffect(()=>{void(async()=>{const[sv,pv,cv]=await Promise.allSettled([tourismContractInventoryApi.suppliers(),tourismContractInventoryApi.programs(),tourismContractInventoryApi.catalog()]);if(sv.status==='fulfilled')setSuppliers(sv.value);if(pv.status==='fulfilled')setPrograms(pv.value);if(cv.status==='fulfilled')setCatalog(cv.value);if(sv.status==='rejected'||pv.status==='rejected'||cv.status==='rejected')setNotice('تعذر تحميل بعض القوائم المرجعية من ملاكها المعتمدين.');})();},[]);
 async function run(label:string,operation:()=>Promise<InventoryResult|null>,reload=false){try{const value=await operation();setResult(value??null);setNotice(label);if(reload)await refresh();return value;}catch(error){setNotice(failure(error));return null;}}

 function commercialTerms(){
  const common={name:terms.name.trim()||undefined,shortName:terms.shortName.trim()||undefined,currency:terms.currency.trim().toUpperCase()||undefined,cancellationPolicy:terms.cancellationPolicy.trim()||undefined};
  if(contract.type==='HOTEL')return{commercial:{...common,city:terms.city.trim()||undefined,boardBasis:terms.boardBasis.trim()||undefined,roomRates:{single:terms.singleRate||undefined,double:terms.doubleRate||undefined,triple:terms.tripleRate||undefined,quad:terms.quadRate||undefined,quint:terms.quintRate||undefined}}};
  if(contract.type==='FLIGHT_BLOCK')return{commercial:{...common,airline:terms.airline.trim()||undefined,returnLeg:{flightNumber:terms.returnFlightNumber.trim()||undefined,origin:terms.returnOrigin.trim()||undefined,destination:terms.returnDestination.trim()||undefined,departureAt:terms.returnDepartureAt||undefined},ticketingDeadline:terms.ticketingDeadline||undefined,fareClass:terms.fareClass.trim()||undefined,baggage:terms.baggage.trim()||undefined},...(terms.unitCost.trim()?{standalonePricing:{currency:terms.currency.trim().toUpperCase(),unit:terms.unit.trim()||'SEAT',unitCost:terms.unitCost.trim()}}:{})};
  return{commercial:{...common},...(terms.unitCost.trim()?{standalonePricing:{currency:terms.currency.trim().toUpperCase(),unit:terms.unit.trim()||'UNIT',unitCost:terms.unitCost.trim()}}:{})};
 }

 async function createContract(event:FormEvent){
  event.preventDefault();
  const created=await run('تم إنشاء العقد.',()=>tourismContractInventoryApi.createContract({...contract,...(contract.supplierId?{supplierId:contract.supplierId}:{}),commandKey:crypto.randomUUID()}),true);
  const id=created&&typeof created.id==='string'?created.id:'';if(!id)return;
  setContractId(id);setAllocation(current=>({...current,contractId:id,resourceId:'',evidenceSourceType:'',evidenceSourceId:''}));setStop(current=>({...current,contractId:id}));setResource(blankResource);
  await run('تم إنشاء العقد وحفظ شروطه التجارية كنسخة Versioned.',()=>tourismContractInventoryApi.amendContract(id,{terms:commercialTerms(),effectiveFrom:contract.effectiveFrom,effectiveTo:contract.effectiveTo,commandKey:crypto.randomUUID()}),true);
  try{setVersions(await tourismContractInventoryApi.versions(id));}catch{setVersions([]);}
 }
 async function openContract(){if(!contractId)return;await run('تم تحميل العقد.',()=>tourismContractInventoryApi.contract(contractId));try{setVersions(await tourismContractInventoryApi.versions(contractId));}catch{setVersions([]);}}
 function selectContract(id:string){setContractId(id);setResource(blankResource);setStop(current=>({...current,contractId:id}));}

 async function createResource(event:FormEvent){
  event.preventDefault();if(!selectedContract||!resourceType){setNotice('اختر عقدًا أولًا.');return;}
  const common={contractId:selectedContract.id,commandKey:crypto.randomUUID()};
  const operation=resourceType==='HOTEL'?()=>tourismContractInventoryApi.createHotel({...common,hotelId:resource.resourceId,...(resource.secondary.trim()?{roomId:resource.secondary.trim()}:{}),serviceDate:resource.serviceDate,contractedQuantity:resource.quantity}):resourceType==='FLIGHT_BLOCK'?()=>{const[origin='',destination='']=resource.secondary.split('>');return tourismContractInventoryApi.createFlight({...common,flightNumber:resource.resourceId,origin:origin.trim(),destination:destination.trim(),departureDate:resource.serviceDate,totalSeats:resource.quantity});}:resourceType==='TRANSPORT'?()=>tourismContractInventoryApi.createTransport({...common,vehicleId:resource.resourceId,capacityUnits:resource.quantity,periodStart:resource.serviceDate,periodEnd:resource.periodEnd}):resourceType==='VISA'?()=>tourismContractInventoryApi.createVisa({...common,visaType:resource.resourceId,...(resource.secondary.trim()?{nationality:resource.secondary.trim()}:{}),quotaTotal:resource.quantity,effectiveFrom:resource.serviceDate,effectiveTo:resource.periodEnd}):()=>tourismContractInventoryApi.createService({...common,category:resource.category as 'CAMP'|'MEAL'|'VISIT'|'GUIDE'|'RAWDA'|'INSURANCE'|'OTHER',name:resource.resourceId,description:resource.description.trim()||undefined,unit:resource.unit,serviceStart:resource.serviceDate,serviceEnd:resource.periodEnd,capacity:resource.quantity,releaseDeadline:resource.releaseDeadline||undefined});
  await run('تمت إضافة السعة داخل نوع العقد الصحيح.',operation,true);
 }

 function chooseAllocationContract(id:string){setAllocation(current=>({...current,contractId:id,resourceId:'',evidenceSourceType:'',evidenceSourceId:''}));}
 function chooseAllocationResource(id:string){const option=allocationContract?.resources.find(item=>item.id===id);setAllocation(current=>({...current,resourceId:id,evidenceSourceType:option?defaultEvidence(option.resourceType):'',evidenceSourceId:''}));}
 async function checkAvailability(){if(!allocationResource)return;await run('تم فحص الإتاحة.',()=>tourismContractInventoryApi.availability({contractId:allocationResource.contractId,resourceType:allocationResource.resourceType,resourceId:allocationResource.id,serviceDate:allocationResource.serviceDate,...(allocationResource.periodEnd?{periodEnd:allocationResource.periodEnd}:{})}));}
 async function allocate(event:FormEvent){
  event.preventDefault();if(!allocationResource||!allocation.sourceId)return;
  const sourceType=allocation.evidenceSourceType.trim()||defaultEvidence(allocationResource.resourceType),sourceId=allocation.evidenceSourceId.trim();
  if((allocationResource.resourceType==='FLIGHT_BLOCK'||allocationResource.resourceType==='VISA')&&(!sourceType||!sourceId)){setNotice('مرجع التشغيل المعتمد مطلوب لهذا النوع من المخزون.');return;}
  await run('تم إنشاء التخصيص.',async()=>{
   const evidence=allocationResource.resourceType==='FLIGHT_BLOCK'?{flightSegmentReference:{sourceType,sourceId}}:allocationResource.resourceType==='VISA'?{visaBatchReference:{sourceType,sourceId}}:{};
   const value=await tourismContractInventoryApi.allocate({contractId:allocationResource.contractId,resourceType:allocationResource.resourceType,resourceId:allocationResource.id,program:{sourceType:'TOURISM_PROGRAM',sourceId:allocation.sourceId},serviceDate:allocationResource.serviceDate,...(allocationResource.periodEnd?{periodEnd:allocationResource.periodEnd}:{}),quantity:allocation.quantity,...evidence,commandKey:crypto.randomUUID()});
   const generated=typeof value.allocationId==='string'?value.allocationId:value.allocation&&typeof value.allocation==='object'&&typeof (value.allocation as {id?:unknown}).id==='string'?(value.allocation as {id:string}).id:'';if(generated)setAllocationId(generated);return value;
  },true);
 }
 async function release(){if(allocationId)await run('تم تنفيذ طلب فك التخصيص.',()=>tourismContractInventoryApi.release(allocationId,{quantity:allocation.quantity,commandKey:crypto.randomUUID()}),true);}
 async function stopSale(event:FormEvent){event.preventDefault();if(!stop.contractId)return;await run('تم تسجيل Stop Sale.',()=>tourismContractInventoryApi.stopSale({...stop,commandKey:crypto.randomUUID()}),true);}

 return <section dir="rtl" className="ui-page-stack" aria-label="التعاقدات والمخزون">
  {notice?<Toast tone={notice.startsWith('تم')?'success':'error'}>{notice}</Toast>:null}
  <Card title="التعاقدات والمخزون"><p>العقود والسعات والتخصيصات مملوكة لـ Tourism Contract Inventory. الشروط التجارية Versioned، بينما الفواتير والذمم والمدفوعات لا تُخزن هنا.</p><Button variant="secondary" onClick={()=>void refresh()}>تحديث الكتالوج</Button></Card>
  <div className="ui-metric-grid"><MetricCard label="العقود النشطة" value={catalog.length}/><MetricCard label="العقد الحالي" value={contractId||'—'}/><MetricCard label="التخصيص الحالي" value={allocationId||'—'}/><MetricCard label="نسخ العقد" value={versions.length}/></div>

  <div className="ui-grid-md">
   <Card title="إنشاء عقد"><form onSubmit={createContract} className="ui-page-stack">
    <FormField label="نوع العقد"><Select value={contract.type} onChange={event=>setContract({...contract,type:event.target.value as TourismInventoryResourceType})}><option value="HOTEL">فندق</option><option value="FLIGHT_BLOCK">بلوك طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرات</option><option value="SERVICE">خدمة متعاقد عليها</option></Select></FormField>
    <FormField label="المورد"><Select value={contract.supplierId} onChange={event=>setContract({...contract,supplierId:event.target.value})}><option value="">بدون مورد محدد</option>{suppliers.filter(item=>item.supplier.status==='ACTIVE'&&item.supplier.approvalStatus==='APPROVED').map(item=><option key={item.supplier.id} value={item.supplier.id}>{item.supplier.supplierCode} — {item.party.displayName}</option>)}</Select></FormField>
    <FormField label="من"><Input required type="date" value={contract.effectiveFrom} onChange={event=>setContract({...contract,effectiveFrom:event.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={contract.effectiveTo} onChange={event=>setContract({...contract,effectiveTo:event.target.value})}/></FormField>
    <FormField label="اسم العقد"><Input value={terms.name} onChange={event=>setTerms({...terms,name:event.target.value})}/></FormField><FormField label="الاسم المختصر"><Input value={terms.shortName} onChange={event=>setTerms({...terms,shortName:event.target.value})}/></FormField><FormField label="العملة"><Input value={terms.currency} onChange={event=>setTerms({...terms,currency:event.target.value.toUpperCase()})}/></FormField><FormField label="سياسة الإلغاء"><Textarea value={terms.cancellationPolicy} onChange={event=>setTerms({...terms,cancellationPolicy:event.target.value})}/></FormField>
    {contract.type==='HOTEL'?<><FormField label="المدينة"><Input value={terms.city} onChange={event=>setTerms({...terms,city:event.target.value})}/></FormField><FormField label="نظام الإقامة / الوجبات"><Input value={terms.boardBasis} onChange={event=>setTerms({...terms,boardBasis:event.target.value})}/></FormField><FormField label="أسعار الغرف Single / Double / Triple / Quad / Quint"><div className="ui-filter-grid"><Input inputMode="decimal" placeholder="Single" value={terms.singleRate} onChange={event=>setTerms({...terms,singleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Double" value={terms.doubleRate} onChange={event=>setTerms({...terms,doubleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Triple" value={terms.tripleRate} onChange={event=>setTerms({...terms,tripleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Quad" value={terms.quadRate} onChange={event=>setTerms({...terms,quadRate:event.target.value})}/><Input inputMode="decimal" placeholder="Quint" value={terms.quintRate} onChange={event=>setTerms({...terms,quintRate:event.target.value})}/></div></FormField></>:null}
    {contract.type==='FLIGHT_BLOCK'?<><FormField label="شركة الطيران"><Input value={terms.airline} onChange={event=>setTerms({...terms,airline:event.target.value})}/></FormField><FormField label="رحلة العودة"><Input value={terms.returnFlightNumber} onChange={event=>setTerms({...terms,returnFlightNumber:event.target.value})}/></FormField><FormField label="مسار العودة"><div className="ui-filter-grid"><Input placeholder="Origin" value={terms.returnOrigin} onChange={event=>setTerms({...terms,returnOrigin:event.target.value})}/><Input placeholder="Destination" value={terms.returnDestination} onChange={event=>setTerms({...terms,returnDestination:event.target.value})}/></div></FormField><FormField label="موعد العودة"><Input type="datetime-local" value={terms.returnDepartureAt} onChange={event=>setTerms({...terms,returnDepartureAt:event.target.value})}/></FormField><FormField label="تكلفة المقعد التجارية"><Input inputMode="decimal" value={terms.unitCost} onChange={event=>setTerms({...terms,unitCost:event.target.value})}/></FormField><FormField label="آخر موعد للتذاكر"><Input type="date" value={terms.ticketingDeadline} onChange={event=>setTerms({...terms,ticketingDeadline:event.target.value})}/></FormField><FormField label="Fare Class"><Input value={terms.fareClass} onChange={event=>setTerms({...terms,fareClass:event.target.value})}/></FormField><FormField label="الأمتعة"><Input value={terms.baggage} onChange={event=>setTerms({...terms,baggage:event.target.value})}/></FormField></>:null}
    {['TRANSPORT','VISA','SERVICE'].includes(contract.type)?<><FormField label="وحدة التسعير"><Input value={terms.unit} onChange={event=>setTerms({...terms,unit:event.target.value})}/></FormField><FormField label="تكلفة الوحدة التجارية"><Input inputMode="decimal" value={terms.unitCost} onChange={event=>setTerms({...terms,unitCost:event.target.value})}/></FormField></>:null}
    <Button type="submit">إنشاء العقد وحفظ الشروط</Button>
   </form></Card>

   <Card title="العقد الحالي وإضافة السعة"><FormField label="العقد"><Select value={contractId} onChange={event=>selectContract(event.target.value)}><option value="">اختر عقدًا</option>{catalog.map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><ActionBar><Button variant="secondary" disabled={!contractId} onClick={()=>void openContract()}>فتح العقد ونسخه</Button></ActionBar>{selectedContract?<form onSubmit={createResource} className="ui-page-stack"><p>نوع السعة ثابت من العقد: <strong>{selectedContract.type}</strong></p><FormField label={resourceType==='HOTEL'?'معرّف الفندق':resourceType==='FLIGHT_BLOCK'?'رقم الرحلة':resourceType==='TRANSPORT'?'معرّف المركبة':resourceType==='VISA'?'نوع التأشيرة':'اسم الخدمة'} required><Input required value={resource.resourceId} onChange={event=>setResource({...resource,resourceId:event.target.value})}/></FormField><FormField label={resourceType==='FLIGHT_BLOCK'?'المسار مثال CAI > JED':resourceType==='VISA'?'الجنسية':resourceType==='HOTEL'?'نوع/معرّف الغرفة':'تفصيل إضافي'}><Input value={resource.secondary} onChange={event=>setResource({...resource,secondary:event.target.value})}/></FormField>{resourceType==='SERVICE'?<><FormField label="تصنيف الخدمة"><Select value={resource.category} onChange={event=>setResource({...resource,category:event.target.value})}><option value="CAMP">مخيم</option><option value="MEAL">وجبة</option><option value="VISIT">زيارة</option><option value="GUIDE">مرشد</option><option value="RAWDA">روضة</option><option value="INSURANCE">تأمين</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="الوصف"><Textarea value={resource.description} onChange={event=>setResource({...resource,description:event.target.value})}/></FormField><FormField label="الوحدة"><Input required value={resource.unit} onChange={event=>setResource({...resource,unit:event.target.value})}/></FormField><FormField label="Release deadline"><Input type="date" value={resource.releaseDeadline} onChange={event=>setResource({...resource,releaseDeadline:event.target.value})}/></FormField></>:null}<FormField label="تاريخ البداية"><Input required type="date" value={resource.serviceDate} onChange={event=>setResource({...resource,serviceDate:event.target.value})}/></FormField>{resourceType&&['TRANSPORT','VISA','SERVICE'].includes(resourceType)?<FormField label="تاريخ النهاية"><Input required type="date" value={resource.periodEnd} onChange={event=>setResource({...resource,periodEnd:event.target.value})}/></FormField>:null}<FormField label="الكمية / السعة"><Input required inputMode="decimal" value={resource.quantity} onChange={event=>setResource({...resource,quantity:event.target.value})}/></FormField><Button type="submit">إضافة للمخزون</Button></form>:<EmptyState title="اختر عقدًا لإضافة مخزون مطابق لنوعه"/>}</Card>
  </div>

  <div className="ui-grid-md">
   <Card title="الإتاحة والتخصيص"><form onSubmit={allocate} className="ui-page-stack"><FormField label="العقد" required><Select required value={allocation.contractId} onChange={event=>chooseAllocationContract(event.target.value)}><option value="">اختر عقدًا نشطًا</option>{catalog.filter(item=>item.resources.length>0).map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><FormField label="السعة" required><Select required disabled={!allocationContract} value={allocation.resourceId} onChange={event=>chooseAllocationResource(event.target.value)}><option value="">اختر السعة</option>{allocationContract?.resources.map(item=><option key={item.id} value={item.id}>{item.label} — متاح {item.availableQuantity}</option>)}</Select></FormField><FormField label="البرنامج" required><Select required value={allocation.sourceId} onChange={event=>setAllocation({...allocation,sourceId:event.target.value})}><option value="">اختر برنامجًا</option>{programs.filter(program=>!['CLOSED','CANCELLED'].includes(program.status)).map(program=><option key={program.id} value={program.id}>{program.code} — {program.nameAr}</option>)}</Select></FormField>{allocationResource?<><FormField label="تاريخ الخدمة"><Input disabled value={allocationResource.serviceDate}/></FormField>{allocationResource.periodEnd?<FormField label="حتى"><Input disabled value={allocationResource.periodEnd}/></FormField>:null}<FormField label="الكمية" required hint={`المتاح: ${allocationResource.availableQuantity}`}><Input required inputMode="decimal" value={allocation.quantity} onChange={event=>setAllocation({...allocation,quantity:event.target.value})}/></FormField>{['FLIGHT_BLOCK','VISA'].includes(allocationResource.resourceType)?<><FormField label="نوع مرجع التشغيل" required><Input required value={allocation.evidenceSourceType||defaultEvidence(allocationResource.resourceType)} onChange={event=>setAllocation({...allocation,evidenceSourceType:event.target.value})}/></FormField><FormField label={allocationResource.resourceType==='FLIGHT_BLOCK'?'مرجع قطاع الطيران':'مرجع دفعة التأشيرات'} required><Input required value={allocation.evidenceSourceId} onChange={event=>setAllocation({...allocation,evidenceSourceId:event.target.value})}/></FormField></>:null}</>:null}<ActionBar><Button type="button" variant="secondary" disabled={!allocationResource} onClick={()=>void checkAvailability()}>فحص الإتاحة</Button><Button type="submit" disabled={!allocationResource||!allocation.sourceId}>تخصيص السعة</Button></ActionBar></form><hr/><FormField label="التخصيص الحالي / بحث إداري"><Input value={allocationId} onChange={event=>setAllocationId(event.target.value)} placeholder="يظهر تلقائيًا بعد التخصيص أو أدخل ID للبحث الإداري"/></FormField><Button variant="danger" disabled={!allocationId} onClick={()=>void release()}>فك الكمية المحددة</Button></Card>
   <Card title="إيقاف البيع Stop Sale"><form onSubmit={stopSale} className="ui-page-stack"><FormField label="العقد" required><Select required value={stop.contractId} onChange={event=>setStop({...stop,contractId:event.target.value})}><option value="">اختر العقد</option>{catalog.map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField><FormField label="السبب" required><Input required value={stop.reason} onChange={event=>setStop({...stop,reason:event.target.value})}/></FormField><FormField label="من"><Input required type="date" value={stop.effectiveFrom} onChange={event=>setStop({...stop,effectiveFrom:event.target.value})}/></FormField><FormField label="إلى"><Input required type="date" value={stop.effectiveTo} onChange={event=>setStop({...stop,effectiveTo:event.target.value})}/></FormField><Button variant="danger" type="submit">تسجيل إيقاف البيع</Button></form></Card>
  </div>

  <TourismContractInventoryCorrectiveSection contractId={contractId}/>
  {versions.length?<Card title="نسخ العقد"><DataGrid columns={['الإصدار','من','إلى','الشروط']}>{versions.map((version,index)=><tr key={String(version.id??index)}><td>{String(version.version??index+1)}</td><td>{String(version.effectiveFrom??'—')}</td><td>{String(version.effectiveTo??'—')}</td><td>{version.terms&&typeof version.terms==='object'?JSON.stringify(version.terms):'—'}</td></tr>)}</DataGrid></Card>:null}
  <ResultCard value={result}/>
 </section>;
}
