import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { tourismOperationsApi, type TourismBooking, type TourismBookingConfirm, type TourismCostCenterReference, type TourismCustomerReference, type TourismProgram, type TourismTravelerReference } from './tourism-operations-client.js';
import { tourismContractInventoryApi, type TourismInventoryContractOption, type TourismInventoryResourceOption } from './tourism-contract-inventory-client.js';
import { ActionBar, Badge, Button, Card, Checkbox, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, Select } from './ui.js';

const bookingStatus:Record<string,string>={DRAFT:'مسودة',CONFIRMING:'جارٍ التأكيد',CONFIRMED:'مؤكد',CANCELLING:'جارٍ الإلغاء',CANCELLATION_REQUIRED:'يحتاج تسوية قبل الإلغاء',CANCELLED:'ملغي',COMPLETED:'مكتمل'};
const blankBooking:{code:string;programId:string;customerId:string;travelerIds:string[]}={code:'',programId:'',customerId:'',travelerIds:[]};
const blankConfirm={costCenterId:'',currency:'EGP',grossAmount:'',discountAmount:'0',postingDate:'',dueDate:'',invoiceNumber:'',contractId:'',resourceId:'',quantity:'1',flightSegmentSourceType:'TOURISM_FLIGHT_SEGMENT',flightSegmentSourceId:'',visaBatchSourceType:'TOURISM_VISA_BATCH',visaBatchSourceId:''};
const today=()=>new Date().toISOString().slice(0,10);
const categoryFor=(resource:TourismInventoryResourceOption):TourismBookingConfirm['category']=>resource.resourceType==='HOTEL'?'HOTEL':resource.resourceType==='FLIGHT_BLOCK'?'FLIGHT':resource.resourceType==='TRANSPORT'?'TRANSPORT':resource.resourceType==='VISA'?'VISA':'OTHER';

export function TourismBookingsWorkspace({programs,bookings,done}:{programs:TourismProgram[];bookings:TourismBooking[];done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState(blankBooking),[confirmId,setConfirmId]=useState(''),[confirm,setConfirm]=useState(blankConfirm),[customers,setCustomers]=useState<TourismCustomerReference[]>([]),[travelers,setTravelers]=useState<TourismTravelerReference[]>([]),[catalog,setCatalog]=useState<TourismInventoryContractOption[]>([]),[costCenters,setCostCenters]=useState<TourismCostCenterReference[]>([]),[selectorError,setSelectorError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE');
 useEffect(()=>{void (async()=>{const results=await Promise.allSettled([tourismOperationsApi.customers(),tourismOperationsApi.travelers(),tourismContractInventoryApi.catalog(),tourismOperationsApi.costCenters()]);if(results[0].status==='fulfilled')setCustomers(results[0].value);else setSelectorError('تعذر تحميل قائمة العملاء.');if(results[1].status==='fulfilled')setTravelers(results[1].value);else setSelectorError(value=>value||'تعذر تحميل قائمة المسافرين.');if(results[2].status==='fulfilled')setCatalog(results[2].value);else setSelectorError(value=>value||'تعذر تحميل العقود والمخزون السياحي.');if(results[3].status==='fulfilled')setCostCenters(results[3].value);else setSelectorError(value=>value||'تعذر تحميل مراكز التكلفة من المالك المحاسبي.');})();},[]);
 const customerNames=useMemo(()=>new Map(customers.map(item=>[item.customer.id,item.party.displayName])),[customers]);
 const travelerNames=useMemo(()=>new Map(travelers.map(item=>[item.id,item.fullName])),[travelers]);
 const filtered=useMemo(()=>bookings.filter(booking=>{const q=query.trim().toLowerCase(),program=programs.find(item=>item.id===booking.programId),customer=customerNames.get(booking.customerId)??booking.customerId;const matchesQuery=!q||`${booking.code} ${program?.nameAr??''} ${customer}`.toLowerCase().includes(q);const matchesStatus=status==='ALL'||(status==='ACTIVE'&&!['CANCELLED','COMPLETED'].includes(booking.status))||booking.status===status;return matchesQuery&&matchesStatus;}),[bookings,programs,customerNames,query,status]);
 const selectedContract=useMemo(()=>catalog.find(item=>item.id===confirm.contractId),[catalog,confirm.contractId]);
 const selectedResource=useMemo(()=>selectedContract?.resources.find(item=>item.id===confirm.resourceId),[selectedContract,confirm.resourceId]);
 function toggleTraveler(id:string){setForm(current=>({...current,travelerIds:current.travelerIds.includes(id)?current.travelerIds.filter(value=>value!==id):[...current.travelerIds,id]}));}
 async function create(e:FormEvent){e.preventDefault();await tourismOperationsApi.createBooking({code:form.code,programId:form.programId,customerId:form.customerId,travelerIds:form.travelerIds});setForm(blankBooking);await done('تم إنشاء الحجز كمسودة مرتبطة بالبرنامج والعميل والمسافرين.');}
 async function confirmBooking(e:FormEvent){e.preventDefault();if(!confirmId||!selectedResource)return;const flightSegmentReference=selectedResource.resourceType==='FLIGHT_BLOCK'?{sourceType:confirm.flightSegmentSourceType.trim(),sourceId:confirm.flightSegmentSourceId.trim()}:undefined;const visaBatchReference=selectedResource.resourceType==='VISA'?{sourceType:confirm.visaBatchSourceType.trim(),sourceId:confirm.visaBatchSourceId.trim()}:undefined;await tourismOperationsApi.confirmBooking(confirmId,{commandKey:'tourism-confirm:'+confirmId+':'+confirm.invoiceNumber,category:categoryFor(selectedResource),costCenterId:confirm.costCenterId,currency:confirm.currency,grossAmount:confirm.grossAmount,discountAmount:confirm.discountAmount,postingDate:confirm.postingDate,dueDate:confirm.dueDate,invoiceNumber:confirm.invoiceNumber,inventories:[{contractId:selectedResource.contractId,resourceType:selectedResource.resourceType,resourceId:selectedResource.id,serviceDate:selectedResource.serviceDate,quantity:confirm.quantity,...(selectedResource.periodEnd?{periodEnd:selectedResource.periodEnd}:{}),...(flightSegmentReference?{flightSegmentReference}:{}),...(visaBatchReference?{visaBatchReference}:{})}]});setConfirmId('');setConfirm(blankConfirm);await done('تم تأكيد الحجز عبر المخزون والتمويل المعتمدين.');}
 async function cancel(b:TourismBooking){const date=today(),commandKey=b.pendingCommandKey??'tourism-cancel:'+b.id+':'+date;await tourismOperationsApi.cancelBooking(b.id,{commandKey,postingDate:date});await done(b.status==='CANCELLATION_REQUIRED'?'تمت إعادة فحص التسوية المالية ومحاولة إتمام الإلغاء.':'تم تنفيذ طلب الإلغاء وفق الموانع المالية المسجلة.');}
 function startConfirm(id:string){setConfirmId(id);setConfirm({...blankConfirm,postingDate:today(),dueDate:today()});}
 function chooseContract(contractId:string){setConfirm(current=>({...current,contractId,resourceId:'',flightSegmentSourceId:'',visaBatchSourceId:''}));}
 function chooseResource(resourceId:string){setConfirm(current=>({...current,resourceId,flightSegmentSourceId:'',visaBatchSourceId:''}));}
 const evidenceReady=!selectedResource||(selectedResource.resourceType==='FLIGHT_BLOCK'?Boolean(confirm.flightSegmentSourceType.trim()&&confirm.flightSegmentSourceId.trim()):selectedResource.resourceType==='VISA'?Boolean(confirm.visaBatchSourceType.trim()&&confirm.visaBatchSourceId.trim()):true);
 return <>
  <DisclosureCard title="حجز سياحي جديد" description="العميل والمسافرون يُختارون من السجلات الرئيسية؛ لا تُدخل المعرّفات الداخلية يدويًا."><form className="ui-filter-grid" onSubmit={create}>
   <FormField label="رقم الحجز" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField>
   <FormField label="البرنامج" required><Select required value={form.programId} onChange={e=>setForm({...form,programId:e.target.value})}><option value="">اختر برنامجًا مفتوحًا</option>{programs.filter(p=>p.status==='OPEN').map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr}</option>)}</Select></FormField>
   <FormField label="العميل" required><Select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">اختر العميل</option>{customers.map(item=><option key={item.customer.id} value={item.customer.id}>{item.customer.number} — {item.party.displayName}</option>)}</Select></FormField>
   <FormField label="المسافرون" hint="اختر مسافرًا واحدًا على الأقل من Traveler Management"><div className="ui-page-stack">{travelers.map(traveler=><label className="ui-checkbox-field" key={traveler.id}><Checkbox checked={form.travelerIds.includes(traveler.id)} onChange={()=>toggleTraveler(traveler.id)}/><span>{traveler.fullName}{traveler.customerId&&traveler.customerId===form.customerId?' — مرتبط بالعميل':''}</span></label>)}</div></FormField>
   {selectorError?<ErrorState message={selectorError}/>:null}<Button type="submit" disabled={!form.customerId||form.travelerIds.length===0}>إنشاء الحجز</Button>
  </form></DisclosureCard>
  <Card title="بحث وتصفية الحجوزات"><div className="ui-filter-grid"><FormField label="بحث"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم الحجز أو العميل أو البرنامج"/></FormField><FormField label="الحالة"><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">قيد العمل</option><option value="ALL">الكل</option><option value="DRAFT">مسودة</option><option value="CONFIRMING">جارٍ التأكيد</option><option value="CONFIRMED">مؤكد</option><option value="CANCELLING">جارٍ الإلغاء</option><option value="CANCELLATION_REQUIRED">يحتاج تسوية</option><option value="CANCELLED">ملغي</option><option value="COMPLETED">مكتمل</option></Select></FormField></div></Card>
  {filtered.length?<DataGrid columns={['الحجز','البرنامج','العميل','المسافرون','الحالة','الإجراء']}>{filtered.map(b=>{const canConfirm=b.status==='DRAFT'||b.status==='CONFIRMING',canCancel=b.status==='CONFIRMED'||b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED',tone=b.status==='CONFIRMED'?'success':(b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED')?'warning':b.status==='CANCELLED'?'error':'neutral';return <tr key={b.id}><td>{b.code}</td><td>{programs.find(p=>p.id===b.programId)?.nameAr??b.programId}</td><td>{customerNames.get(b.customerId)??b.customerId}</td><td>{b.travelerIds.map(id=>travelerNames.get(id)??id).join('، ')}</td><td><Badge tone={tone}>{bookingStatus[b.status]??b.status}</Badge></td><td><ActionBar>{canConfirm?<Button onClick={()=>startConfirm(b.id)}>تأكيد مالي</Button>:null}{canCancel?<Button variant={b.status==='CANCELLATION_REQUIRED'?'secondary':'danger'} onClick={()=>void cancel(b)}>{b.status==='CANCELLATION_REQUIRED'?'إعادة فحص الإلغاء':'طلب إلغاء'}</Button>:null}{b.status==='CONFIRMED'?<Button variant="secondary" onClick={()=>void tourismOperationsApi.completeBooking(b.id).then(()=>done('تم إكمال الحجز.'))}>إكمال</Button>:null}</ActionBar></td></tr>;})}</DataGrid>:<EmptyState title="لا توجد حجوزات ضمن الفلتر"/>}
  {confirmId?<Card title="تأكيد الحجز ماليًا"><form className="ui-filter-grid" onSubmit={confirmBooking}>
    <FormField label="مركز التكلفة" required><Select required value={confirm.costCenterId} onChange={e=>setConfirm({...confirm,costCenterId:e.target.value})}><option value="">اختر مركز التكلفة</option>{costCenters.map(center=><option key={center.id} value={center.id}>{center.code} — {center.name}</option>)}</Select></FormField><FormField label="العملة" required><Input required value={confirm.currency} onChange={e=>setConfirm({...confirm,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="الإجمالي" required><Input required inputMode="decimal" value={confirm.grossAmount} onChange={e=>setConfirm({...confirm,grossAmount:e.target.value})}/></FormField><FormField label="الخصم"><Input inputMode="decimal" value={confirm.discountAmount} onChange={e=>setConfirm({...confirm,discountAmount:e.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={confirm.postingDate} onChange={e=>setConfirm({...confirm,postingDate:e.target.value})}/></FormField><FormField label="الاستحقاق" required><Input required type="date" value={confirm.dueDate} onChange={e=>setConfirm({...confirm,dueDate:e.target.value})}/></FormField><FormField label="رقم الفاتورة" required><Input required value={confirm.invoiceNumber} onChange={e=>setConfirm({...confirm,invoiceNumber:e.target.value})}/></FormField>
    <FormField label="العقد" required><Select required value={confirm.contractId} onChange={e=>chooseContract(e.target.value)}><option value="">اختر عقدًا نشطًا</option>{catalog.filter(item=>item.resources.length>0).map(item=><option key={item.id} value={item.id}>{item.type} — {item.effectiveFrom} إلى {item.effectiveTo}</option>)}</Select></FormField>
    <FormField label="المورد / المورد التشغيلي" required><Select required value={confirm.resourceId} onChange={e=>chooseResource(e.target.value)} disabled={!selectedContract}><option value="">اختر موردًا من العقد</option>{selectedContract?.resources.map(item=><option key={item.id} value={item.id}>{item.label} — متاح {item.availableQuantity}</option>)}</Select></FormField>
    {selectedResource?<><FormField label="تاريخ الخدمة"><Input value={selectedResource.serviceDate} disabled/></FormField>{selectedResource.periodEnd?<FormField label="حتى"><Input value={selectedResource.periodEnd} disabled/></FormField>:null}<FormField label="الكمية" required hint={`المتاح: ${selectedResource.availableQuantity}`}><Input required inputMode="decimal" value={confirm.quantity} onChange={e=>setConfirm({...confirm,quantity:e.target.value})}/></FormField></>:null}
    {selectedResource?.resourceType==='FLIGHT_BLOCK'?<><FormField label="نوع مرجع قطاع الطيران" required><Input required value={confirm.flightSegmentSourceType} onChange={e=>setConfirm({...confirm,flightSegmentSourceType:e.target.value})}/></FormField><FormField label="مرجع قطاع الطيران المعتمد" required><Input required value={confirm.flightSegmentSourceId} onChange={e=>setConfirm({...confirm,flightSegmentSourceId:e.target.value})}/></FormField></>:null}
    {selectedResource?.resourceType==='VISA'?<><FormField label="نوع مرجع دفعة التأشيرات" required><Input required value={confirm.visaBatchSourceType} onChange={e=>setConfirm({...confirm,visaBatchSourceType:e.target.value})}/></FormField><FormField label="مرجع دفعة التأشيرات المعتمد" required><Input required value={confirm.visaBatchSourceId} onChange={e=>setConfirm({...confirm,visaBatchSourceId:e.target.value})}/></FormField></>:null}
    <ActionBar><Button type="submit" disabled={!selectedResource||!evidenceReady||!confirm.costCenterId}>تأكيد</Button><Button type="button" variant="secondary" onClick={()=>{setConfirmId('');setConfirm(blankConfirm);}}>إلغاء</Button></ActionBar>
   </form></Card>:null}
 </>;
}