import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Button, Card, EmptyState, FormField, Input, Select, Textarea, Toast } from './ui.js';
import { EntityDocumentsPanel } from './entity-documents-page.js';
import { tourismContractInventoryApi, type TourismInventoryContractOption, type TourismInventorySupplierReference } from './tourism-contract-inventory-client.js';

const blank={route:'',vehicleType:'',vehicleCount:'',capacityPerVehicle:'',serviceName:'',processingDays:'',currency:'EGP',unit:'UNIT',unitCost:'',singleRate:'',doubleRate:'',tripleRate:'',quadRate:'',quintRate:'',notes:''};
const message=(error:unknown)=>error instanceof Error?error.message:'تعذر حفظ التعديل التعاقدي.';
const contractLabel=(item:TourismInventoryContractOption)=>`${item.type} — ${item.effectiveFrom} إلى ${item.effectiveTo}`;

export function TourismContractParityPanels(){
 const[catalog,setCatalog]=useState<TourismInventoryContractOption[]>([]),[suppliers,setSuppliers]=useState<TourismInventorySupplierReference[]>([]),[contractId,setContractId]=useState(''),[effectiveFrom,setEffectiveFrom]=useState(''),[effectiveTo,setEffectiveTo]=useState(''),[fields,setFields]=useState(blank),[notice,setNotice]=useState('');
 const selected=useMemo(()=>catalog.find(item=>item.id===contractId),[catalog,contractId]);
 const supplier=useMemo(()=>selected?.supplierId?suppliers.find(item=>item.supplier.id===selected.supplierId):undefined,[selected,suppliers]);
 useEffect(()=>{void Promise.all([tourismContractInventoryApi.catalog(),tourismContractInventoryApi.suppliers()]).then(([contracts,ownerSuppliers])=>{setCatalog(contracts);setSuppliers(ownerSuppliers);}).catch(error=>setNotice(message(error)));},[]);
 function choose(id:string){const item=catalog.find(value=>value.id===id);setContractId(id);setFields(blank);setEffectiveFrom(item?.effectiveFrom??'');setEffectiveTo(item?.effectiveTo??'');setNotice('');}
 function pricing(unit:string){return fields.unitCost.trim()?{standalonePricing:{currency:fields.currency.trim().toUpperCase()||'EGP',unit,unitCost:fields.unitCost.trim()}}:{};}
 function terms(){
  if(!selected)return{};
  if(selected.type==='HOTEL')return{commercial:{seasonalRoomRates:{single:fields.singleRate||undefined,double:fields.doubleRate||undefined,triple:fields.tripleRate||undefined,quad:fields.quadRate||undefined,quint:fields.quintRate||undefined},notes:fields.notes.trim()||undefined}};
  if(selected.type==='TRANSPORT')return{commercial:{route:fields.route.trim()||undefined,vehicleType:fields.vehicleType.trim()||undefined,vehicleCount:fields.vehicleCount.trim()||undefined,capacityPerVehicle:fields.capacityPerVehicle.trim()||undefined,notes:fields.notes.trim()||undefined},...pricing('TRANSPORT_CONTRACT')};
  if(selected.type==='VISA')return{commercial:{serviceName:fields.serviceName.trim()||undefined,processingDays:fields.processingDays.trim()||undefined,notes:fields.notes.trim()||undefined},...pricing('VISA')};
  if(selected.type==='SERVICE')return{commercial:{notes:fields.notes.trim()||undefined},...pricing(fields.unit.trim()||'UNIT')};
  return{commercial:{notes:fields.notes.trim()||undefined}};
 }
 async function amend(event:FormEvent){event.preventDefault();if(!selected||!effectiveFrom||!effectiveTo)return;if(effectiveTo<effectiveFrom){setNotice('نهاية سريان التعديل يجب ألا تسبق بدايته.');return;}try{await tourismContractInventoryApi.amendContract(selected.id,{terms:terms(),effectiveFrom,effectiveTo,commandKey:crypto.randomUUID()});setNotice('تم حفظ التعديل التجاري كنسخة عقد جديدة دون إنشاء قيد أو مديونية موازية.');}catch(error){setNotice(message(error));}}
 return <section dir="rtl" className="ui-page-stack" aria-label="استكمال بيانات ومرفقات العقود">
  <Card title="استكمال بيانات ومرفقات العقود"><p>هذه المنطقة تكمل الفروق الحرفية المتبقية من النظام القديم فوق نفس مالك العقود. هوية المزود تأتي من المورد المرتبط بالعقد في Supplier Management؛ أسماء الموارد التشغيلية لا تنشئ Party أو Supplier جديدًا، والأسعار هنا شروط تجارية Versioned وليست فواتير أو ذممًا.</p><FormField label="العقد"><Select value={contractId} onChange={event=>choose(event.target.value)}><option value="">اختر عقدًا</option>{catalog.map(item=><option key={item.id} value={item.id}>{contractLabel(item)}</option>)}</Select></FormField>{selected?<p>المورد/المزود المعتمد: <strong>{supplier?`${supplier.supplier.supplierCode} — ${supplier.party.displayName}`:selected.supplierId?'مورد مرتبط بالعقد':'غير محدد'}</strong></p>:null}</Card>
  {notice?<Toast tone={notice.startsWith('تم')?'success':'error'}>{notice}</Toast>:null}
  {!selected?<EmptyState title="اختر عقدًا لاستكمال شروطه ومرفقاته"/>:<>
   <Card title="تعديل تجاري / موسمي Versioned"><form onSubmit={amend} className="ui-page-stack">
    <FormField label="سريان التعديل من"><Input required type="date" value={effectiveFrom} onChange={event=>setEffectiveFrom(event.target.value)}/></FormField><FormField label="حتى"><Input required type="date" value={effectiveTo} onChange={event=>setEffectiveTo(event.target.value)}/></FormField>
    {selected.type==='HOTEL'?<FormField label="أسعار الغرف للفترة"><div className="ui-filter-grid"><Input inputMode="decimal" placeholder="Single" value={fields.singleRate} onChange={event=>setFields({...fields,singleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Double" value={fields.doubleRate} onChange={event=>setFields({...fields,doubleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Triple" value={fields.tripleRate} onChange={event=>setFields({...fields,tripleRate:event.target.value})}/><Input inputMode="decimal" placeholder="Quad" value={fields.quadRate} onChange={event=>setFields({...fields,quadRate:event.target.value})}/><Input inputMode="decimal" placeholder="Quint" value={fields.quintRate} onChange={event=>setFields({...fields,quintRate:event.target.value})}/></div></FormField>:null}
    {selected.type==='TRANSPORT'?<><FormField label="المسار"><Input value={fields.route} onChange={event=>setFields({...fields,route:event.target.value})}/></FormField><FormField label="نوع المركبة"><Input value={fields.vehicleType} onChange={event=>setFields({...fields,vehicleType:event.target.value})}/></FormField><FormField label="عدد المركبات"><Input inputMode="numeric" value={fields.vehicleCount} onChange={event=>setFields({...fields,vehicleCount:event.target.value})}/></FormField><FormField label="سعة المركبة"><Input inputMode="numeric" value={fields.capacityPerVehicle} onChange={event=>setFields({...fields,capacityPerVehicle:event.target.value})}/></FormField><FormField label="التكلفة التجارية الإجمالية / المرجعية"><Input inputMode="decimal" value={fields.unitCost} onChange={event=>setFields({...fields,unitCost:event.target.value})}/></FormField><FormField label="العملة"><Input value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value.toUpperCase()})}/></FormField></>:null}
    {selected.type==='VISA'?<><FormField label="اسم خدمة التأشيرة"><Input value={fields.serviceName} onChange={event=>setFields({...fields,serviceName:event.target.value})}/></FormField><FormField label="مدة التنفيذ المتوقعة — يوم"><Input inputMode="numeric" value={fields.processingDays} onChange={event=>setFields({...fields,processingDays:event.target.value})}/></FormField><FormField label="تكلفة التأشيرة التجارية"><Input inputMode="decimal" value={fields.unitCost} onChange={event=>setFields({...fields,unitCost:event.target.value})}/></FormField><FormField label="العملة"><Input value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value.toUpperCase()})}/></FormField></>:null}
    {selected.type==='SERVICE'?<><FormField label="وحدة التسعير"><Input value={fields.unit} onChange={event=>setFields({...fields,unit:event.target.value})}/></FormField><FormField label="تكلفة الوحدة التجارية"><Input inputMode="decimal" value={fields.unitCost} onChange={event=>setFields({...fields,unitCost:event.target.value})}/></FormField><FormField label="العملة"><Input value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value.toUpperCase()})}/></FormField></>:null}
    <FormField label="ملاحظات التعديل"><Textarea value={fields.notes} onChange={event=>setFields({...fields,notes:event.target.value})}/></FormField><Button type="submit">حفظ نسخة التعديل</Button>
   </form></Card>
   <Card title="مرفقات العقد"><p>الملفات تُخزّن مرة واحدة في Platform Core ويُحفظ هنا رابط الكيان `TOURISM_CONTRACT` فقط.</p></Card>
   <EntityDocumentsPanel entityId={selected.id} basePath={`/tourism/contracts-inventory/contracts/${encodeURIComponent(selected.id)}/files`} emptyTitle="لا توجد مرفقات لهذا العقد" uploadTitle="إضافة مرفق للعقد" listTitle="مرفقات العقد الحالية"/>
  </>}
 </section>;
}
