import { type FormEvent, useEffect, useState } from 'react';
import { Badge, Button, Card, Checkbox, DataGrid, DisclosureCard, EmptyState, ErrorState, FormField, Input, LoadingState, MetricCard, Select, Textarea, Toast } from './ui.js';
import { tourismServicesApi, type DraftInput, type Fulfillment, type PrintableVoucher, type ServiceRecord, type ServiceRow, type ServiceType, type SupplyPlan, type SupplyRequest, type TourismCapabilities, type Voucher } from './tourism-services-client.js';
import{EntityMultiPicker,EntityPicker}from'./entity-picker.js';
const labels:Record<ServiceRow['status'],string>={DRAFT:'مسودة',CONFIRMING:'جارٍ التأكيد',CONFIRMED:'مؤكدة',CANCELLATION_REQUESTED:'إلغاء قيد التسوية',CANCELLED:'ملغاة',COMPLETED:'منفذة'};
const today=()=>new Date().toISOString().slice(0,10);
const fresh=():DraftInput=>({commandKey:crypto.randomUUID(),number:'',serviceTypeId:'',serviceDate:today(),quantity:'1',debtorKind:'CUSTOMER',debtorPartyId:'',customerPartyId:'',beneficiaryPartyIds:[],details:{},currency:'SAR',grossAmount:'0',discountAmount:'0',invoiceNumber:'',postingDate:today(),dueDate:today()});
const initialRequest=(service:ServiceRecord):SupplyRequest=>({requestId:crypto.randomUUID(),contractId:'',resourceType:service.revision.category==='FLIGHT'?'FLIGHT_BLOCK':service.revision.category==='OTHER'?'SERVICE':service.revision.category,resourceId:'',serviceDate:service.revision.serviceDate,quantity:service.revision.quantity,unit:service.revision.category==='HOTEL'?'ROOM':'UNIT',currency:service.revision.commercial.currency,unitCost:'0'});
export function ServiceRecoveryActions({service,capabilities,onConfirm,onCancel}:{service:ServiceRow;capabilities:TourismCapabilities;onConfirm:()=>void;onCancel:()=>void}){
 return <>{capabilities.confirm&&service.status==='CONFIRMING'&&<Button type="button" onClick={onConfirm}>استئناف تأكيد الخدمة</Button>}{capabilities.cancel&&service.status==='CANCELLATION_REQUESTED'&&<Button type="button" onClick={onCancel}>إعادة فحص واستئناف الإلغاء</Button>}</>;
}
export function TourismServicesPage({api=tourismServicesApi}:{api?:typeof tourismServicesApi}={}){
 const [rows,setRows]=useState<ServiceRow[]>([]),[types,setTypes]=useState<ServiceType[]>([]),[selected,setSelected]=useState<ServiceRecord|null>(null);
 const [form,setForm]=useState<DraftInput>(fresh),[typeForm,setTypeForm]=useState({code:'',nameAr:'',category:'OTHER' as ServiceType['category']});
 const [request,setRequest]=useState<SupplyRequest|null>(null),[quote,setQuote]=useState({supplierId:'',unitCost:'',currency:'SAR',quoteReference:''});
 const [plan,setPlan]=useState<SupplyPlan|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [cap,setCap]=useState<TourismCapabilities>({view:false,manage:false,confirm:false,cancel:false,fulfill:false,voucher:false});
 const [fulfillment,setFulfillment]=useState<Fulfillment|null>(null),[vouchers,setVouchers]=useState<Voucher[]>([]);
 const [supplier,setSupplier]=useState({quantity:'1',referenceType:'BOOKING',reference:'',supplierId:'',internalCoverage:false});
 const [delivery,setDelivery]=useState({quantity:'1',unit:'UNIT',note:''}),[voucherForm,setVoucherForm]=useState({number:'',instructions:''});
 async function reload(){setLoading(true);try{const [services,catalog,permissions]=await Promise.all([api.list(),api.types(),api.capabilities()]);setRows(services);setTypes(catalog);setCap(permissions);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الخدمات')}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[api]);
 async function open(id:string){try{const record=await api.get(id);setSelected(record);setPlan(null);setRequest(initialRequest(record));setQuote(q=>({...q,currency:record.revision.commercial.currency}));if(['CONFIRMED','COMPLETED'].includes(record.service.status)){const [f,v]=await Promise.all([api.fulfillment(id),api.vouchers(id)]);setFulfillment(f);setVouchers(v)}else{setFulfillment(null);setVouchers([])}}catch(e){setNotice(e instanceof Error?e.message:'تعذر فتح الخدمة')}}
 async function save(e:FormEvent){e.preventDefault();try{await api.create(form);setForm(fresh());setNotice('حُفظت المسودة. لا يُحجز المخزون قبل مراجعة الخطة والتأكيد.');await reload()}catch(value){setNotice(value instanceof Error?value.message:'تعذر حفظ المسودة')}}
 async function saveType(e:FormEvent){e.preventDefault();try{await api.saveType({...typeForm,id:crypto.randomUUID(),active:true});setTypeForm({code:'',nameAr:'',category:'OTHER'});setNotice('تمت إضافة نوع الخدمة.');await reload()}catch(value){setNotice(value instanceof Error?value.message:'تعذر حفظ النوع')}}
 async function preview(e:FormEvent){e.preventDefault();if(!selected||!request)return;try{const value=await api.plan(selected.service.id,{expectedRevision:selected.service.revision,requests:[request],...(quote.supplierId&&quote.quoteReference&&quote.unitCost?{externalQuotes:[{requestId:request.requestId,...quote}]}:{})});setPlan(value);setNotice('راجع التغطية والتكلفة والجزء الخارجي قبل التأكيد.')}catch(value){setNotice(value instanceof Error?value.message:'تعذرت المعاينة')}}
 async function confirm(){if(!selected)return;const service=selected.service;const planId=service.status==='CONFIRMING'?service.supplyPlanId:plan?.planId;const planVersion=service.status==='CONFIRMING'?service.supplyPlanVersion:plan?.version;const commandKey=service.status==='CONFIRMING'?service.pendingCommandKey:planId?`ts-confirm:${service.id}:${service.revision}:${planId}`:undefined;if(!planId||planVersion===undefined||!commandKey)return;try{await api.confirm(service.id,{commandKey,expectedRevision:service.revision,planId,planVersion});setNotice('تأكدت الخدمة بعد تخصيص المخزون وتنفيذ الآثار المالية.');await open(service.id);await reload()}catch(value){setNotice(value instanceof Error?value.message:'تعذر التأكيد؛ راجع الموانع');await open(service.id)}}
 async function recordSupplier(e:FormEvent){e.preventDefault();if(!selected)return;try{await api.supplierConfirm(selected.service.id,{...supplier,commandKey:crypto.randomUUID(),at:new Date().toISOString()});setNotice('حُفظ إثبات تأكيد المورد أو التغطية الداخلية.');await open(selected.service.id)}catch(value){setNotice(value instanceof Error?value.message:'تعذر حفظ التأكيد')}}
 async function recordDelivery(e:FormEvent){e.preventDefault();if(!selected)return;try{await api.deliver(selected.service.id,{...delivery,commandKey:crypto.randomUUID(),at:new Date().toISOString()});setNotice('حُفظ دليل التسليم والكمية المنفذة.');await open(selected.service.id)}catch(value){setNotice(value instanceof Error?value.message:'تعذر حفظ التسليم')}}
 async function issue(e:FormEvent){e.preventDefault();if(!selected)return;try{await api.issueVoucher(selected.service.id,{...voucherForm,commandKey:crypto.randomUUID()});setNotice('صدرت القسيمة بنسخة ثابتة.');await open(selected.service.id)}catch(value){setNotice(value instanceof Error?value.message:'تعذر إصدار القسيمة')}}
 async function voidVoucher(id:string){if(!selected)return;try{await api.voidVoucher(selected.service.id,id,{commandKey:crypto.randomUUID()});setNotice('أُبطلت القسيمة مع حفظ نسختها.');await open(selected.service.id)}catch(value){setNotice(value instanceof Error?value.message:'تعذر إبطال القسيمة')}}
 function printSnapshot(snapshot:PrintableVoucher){const popup=window.open('about:blank','_blank');if(!popup){setNotice('يرجى السماح بفتح نافذة الطباعة.');return}const doc=popup.document;doc.documentElement.lang='ar';doc.documentElement.dir='rtl';doc.title=`قسيمة ${snapshot.number}`;const style=doc.createElement('style');style.textContent='body{font-family:system-ui;margin:3rem;color:#17202a}h1{border-bottom:2px solid #123c53;padding-bottom:1rem}p{line-height:1.8}';doc.head.append(style);const heading=doc.createElement('h1');heading.textContent=`قسيمة خدمة ${snapshot.number} · نسخة ${snapshot.version}`;doc.body.append(heading);for(const [label,value] of [['الخدمة',snapshot.serviceNumber],['النوع',snapshot.serviceType],['التاريخ',snapshot.serviceDate],['العميل',snapshot.customerPartyId],['المستفيدون',snapshot.beneficiaryPartyIds.join('، ')],['الكمية',snapshot.quantity],['الوصف',snapshot.description],['المورد',snapshot.supplierId??'تغطية داخلية'],['المرجع',snapshot.externalReference??''],['تعليمات',snapshot.instructions]]){const line=doc.createElement('p');line.textContent=`${label}: ${value}`;doc.body.append(line)}popup.print()}
 async function cancel(){if(!selected)return;const service=selected.service;const commandKey=service.status==='CANCELLATION_REQUESTED'?service.pendingCommandKey:crypto.randomUUID();const postingDate=service.status==='CANCELLATION_REQUESTED'?service.cancellationPostingDate:today();if(!commandKey||!postingDate)return;try{await api.cancel(service.id,{commandKey,postingDate});setNotice('أُلغيت الخدمة بعد فحص موانع التنفيذ والماليات.');await open(service.id);await reload()}catch(value){setNotice(value instanceof Error?value.message:'تعذر الإلغاء');await open(service.id)}}
 return <section aria-label="السياحة والخدمات">
  <Card title="الخدمات السياحية المستقلة"><p>تابع الخدمات من المسودة حتى التنفيذ، وافتح نماذج الإنشاء والإعداد فقط عند الحاجة.</p></Card>
  <div className="ui-metric-grid" aria-label="مؤشرات الخدمات السياحية">
   <MetricCard label="إجمالي الخدمات" value={rows.length}/>
   <MetricCard label="مسودات" value={rows.filter(row=>row.status==='DRAFT').length}/>
   <MetricCard label="مؤكدة" value={rows.filter(row=>row.status==='CONFIRMED').length} tone="success"/>
   <MetricCard label="منفذة" value={rows.filter(row=>row.status==='COMPLETED').length} tone="success"/>
  </div>
  {loading?<LoadingState/>:error?<ErrorState message={error}/>:<Card title="ملفات الخدمات">{rows.length?<DataGrid columns={['الرقم','الحالة','النسخة','إجراء']}>{rows.map(row=><tr key={row.id}><td>{row.number}</td><td><Badge tone={row.status==='CONFIRMED'?'success':row.status==='CANCELLED'?'error':'warning'}>{labels[row.status]}</Badge></td><td>{row.revision}</td><td><Button type="button" onClick={()=>void open(row.id)}>فتح الملف</Button></td></tr>)}</DataGrid>:<EmptyState title="لا توجد خدمات بعد"/>}</Card>}
  {cap.manage&&<DisclosureCard title="خدمة جديدة" description="افتح النموذج عند إضافة خدمة جديدة؛ ملفات الخدمات تظل مساحة العمل الأساسية."><form onSubmit={save}>
   <FormField label="رقم الخدمة" required><Input required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></FormField>
   <FormField label="نوع الخدمة" required><Select required value={form.serviceTypeId} onChange={e=>setForm({...form,serviceTypeId:e.target.value})}><option value="">اختر نوعًا</option>{types.filter(type=>type.active).map(type=><option key={type.id} value={type.id}>{type.nameAr}</option>)}</Select></FormField>
   <FormField label="تاريخ الخدمة" required><Input required type="date" value={form.serviceDate} onChange={e=>setForm({...form,serviceDate:e.target.value})}/></FormField>
   <FormField label="نهاية الفترة"><Input type="date" value={form.periodEnd??''} onChange={e=>setForm({...form,periodEnd:e.target.value||undefined})}/></FormField>
   <FormField label="الكمية" required><Input required inputMode="decimal" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></FormField>
   <EntityPicker kind="CUSTOMER_PARTY" label="العميل" required value={form.customerPartyId} onChange={customerPartyId=>setForm({...form,customerPartyId,debtorPartyId:form.debtorKind==='CUSTOMER'?customerPartyId:form.debtorPartyId})}/>
   <FormField label="الفاتورة على"><Select value={form.debtorKind} onChange={e=>setForm({...form,debtorKind:e.target.value as DraftInput['debtorKind'],debtorPartyId:e.target.value==='CUSTOMER'?form.customerPartyId:''})}><option value="CUSTOMER">العميل</option><option value="AGENT">الوكيل</option></Select></FormField>
   {form.debtorKind==='AGENT'&&<EntityPicker kind="AGENT_PARTY" label="الوكيل المسؤول عن السداد" required value={form.debtorPartyId} onChange={debtorPartyId=>setForm({...form,debtorPartyId})}/>}
   <EntityMultiPicker kind="TRAVELER_PARTY" label="المستفيدون / المسافرون" values={form.beneficiaryPartyIds} onChange={beneficiaryPartyIds=>setForm({...form,beneficiaryPartyIds})}/>
   <FormField label="وصف الخدمة"><Textarea value={String(form.details.description??'')} onChange={e=>setForm({...form,details:{description:e.target.value}})}/></FormField>
   <FormField label="العملة"><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField>
   <FormField label="سعر البيع"><Input required inputMode="decimal" value={form.grossAmount} onChange={e=>setForm({...form,grossAmount:e.target.value})}/></FormField>
   <FormField label="الخصم"><Input required inputMode="decimal" value={form.discountAmount} onChange={e=>setForm({...form,discountAmount:e.target.value})}/></FormField>
   <FormField label="رقم الفاتورة"><Input required value={form.invoiceNumber} onChange={e=>setForm({...form,invoiceNumber:e.target.value})}/></FormField>
   <FormField label="تاريخ القيد"><Input required type="date" value={form.postingDate} onChange={e=>setForm({...form,postingDate:e.target.value})}/></FormField>
   <FormField label="تاريخ الاستحقاق"><Input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></FormField>
   <Button type="submit">حفظ المسودة</Button>
  </form></DisclosureCard>}
  {cap.manage&&<DisclosureCard title="إعداد أنواع الخدمات" description="إعداد إداري لأنواع الخدمات وليس جزءًا من التشغيل اليومي."><form onSubmit={saveType}><FormField label="الرمز"><Input required value={typeForm.code} onChange={e=>setTypeForm({...typeForm,code:e.target.value})}/></FormField><FormField label="الاسم"><Input required value={typeForm.nameAr} onChange={e=>setTypeForm({...typeForm,nameAr:e.target.value})}/></FormField><FormField label="الفئة"><Select value={typeForm.category} onChange={e=>setTypeForm({...typeForm,category:e.target.value as ServiceType['category']})}>{(['HOTEL','FLIGHT','VISA','TRANSPORT','OTHER'] as const).map(category=><option key={category} value={category}>{category}</option>)}</Select></FormField><Button type="submit">إضافة نوع</Button></form></DisclosureCard>}
  {selected&&<Card title={`ملف ${selected.service.number}`}><p>{labels[selected.service.status]} · {selected.revision.category} · {selected.revision.serviceDate} · {selected.revision.quantity} وحدة · {selected.revision.commercial.netAmount} {selected.revision.commercial.currency}</p>
   {cap.confirm&&selected.service.status==='DRAFT'&&request&&<form onSubmit={preview}><p>حدّد العقد والمورد/المخزون، ثم راجع التغطية قبل التأكيد. السعر الخارجي يحتاج عرض مورد ومرجعًا صريحًا.</p>
    <FormField label="العقد" required><Input required value={request.contractId} onChange={e=>setRequest({...request,contractId:e.target.value})}/></FormField>
    <FormField label="المخزون/المورد" required><Input required value={request.resourceId} onChange={e=>setRequest({...request,resourceId:e.target.value})}/></FormField>
    <FormField label="وحدة القياس" required><Input required value={request.unit} onChange={e=>setRequest({...request,unit:e.target.value})}/></FormField>
    <FormField label="تكلفة الوحدة بالعقد" required><Input required inputMode="decimal" value={request.unitCost} onChange={e=>setRequest({...request,unitCost:e.target.value})}/></FormField>
    <EntityPicker kind="SUPPLIER" label="المورد الخارجي" value={quote.supplierId} onChange={supplierId=>setQuote({...quote,supplierId})}/>
    <FormField label="سعر وحدة المورد"><Input inputMode="decimal" value={quote.unitCost} onChange={e=>setQuote({...quote,unitCost:e.target.value})}/></FormField>
    <FormField label="مرجع عرض السعر"><Input value={quote.quoteReference} onChange={e=>setQuote({...quote,quoteReference:e.target.value})}/></FormField>
    <Button type="submit">معاينة خطة التوريد</Button></form>}
   {plan&&cap.confirm&&selected.service.status==='DRAFT'&&<Card title="خطة التوريد للمراجعة"><p>صالحة حتى {new Date(plan.expiresAt).toLocaleString('ar-EG')}</p><DataGrid columns={['المخزون','الكمية','التكلفة']}>{plan.lines.map((line,i)=><tr key={i}><td>{line.resourceId}</td><td>{line.allocationQuantity}</td><td>{line.costAmount} {line.currency}</td></tr>)}</DataGrid>{plan.residuals.map((line,i)=><p key={i}>خارجي: {line.quantity} · {line.supplierId??'مورد غير محدد'} · {line.costAmount??'دون تسعير'} {line.currency}</p>)}<Button type="button" onClick={()=>void confirm()}>تأكيد الخدمة والخطة المراجعة</Button></Card>}
   <ServiceRecoveryActions service={selected.service} capabilities={cap} onConfirm={()=>void confirm()} onCancel={()=>void cancel()}/>
   {selected.service.status==='CONFIRMED'&&<>{cap.fulfill&&<Card title="متابعة المورد والتنفيذ"><p>المؤكد: {fulfillment?.case.confirmedQuantity??'0'} · المنفذ: {fulfillment?.case.deliveredQuantity??'0'} من {selected.revision.quantity}</p><form onSubmit={recordSupplier}><FormField label="الكمية المؤكدة"><Input required value={supplier.quantity} onChange={e=>setSupplier({...supplier,quantity:e.target.value})}/></FormField><EntityPicker kind="SUPPLIER" label="المورد الخارجي" value={supplier.supplierId} onChange={supplierId=>setSupplier({...supplier,supplierId})}/><label className="ui-checkbox-field"><Checkbox checked={supplier.internalCoverage} onChange={e=>setSupplier({...supplier,internalCoverage:e.target.checked})}/><span>تغطية من مخزون داخلي</span></label><FormField label="نوع المرجع"><Input required value={supplier.referenceType} onChange={e=>setSupplier({...supplier,referenceType:e.target.value})}/></FormField><FormField label="مرجع الحجز لدى المورد"><Input required value={supplier.reference} onChange={e=>setSupplier({...supplier,reference:e.target.value})}/></FormField><Button type="submit">تسجيل التأكيد</Button></form><form onSubmit={recordDelivery}><FormField label="كمية التسليم"><Input required value={delivery.quantity} onChange={e=>setDelivery({...delivery,quantity:e.target.value})}/></FormField><FormField label="الوحدة"><Input required value={delivery.unit} onChange={e=>setDelivery({...delivery,unit:e.target.value})}/></FormField><FormField label="دليل التسليم"><Textarea required value={delivery.note} onChange={e=>setDelivery({...delivery,note:e.target.value})}/></FormField><Button type="submit">تسجيل تسليم جزئي أو كامل</Button></form></Card>}
   <Card title="قسائم الخدمة">{cap.voucher&&<form onSubmit={issue}><FormField label="رقم القسيمة"><Input required value={voucherForm.number} onChange={e=>setVoucherForm({...voucherForm,number:e.target.value})}/></FormField><FormField label="تعليمات للعميل"><Textarea value={voucherForm.instructions} onChange={e=>setVoucherForm({...voucherForm,instructions:e.target.value})}/></FormField><Button type="submit">إصدار نسخة</Button></form>}{vouchers.map(v=><p key={v.id}>{v.number} · {v.status==='ISSUED'?'سارية':'ملغاة'} · نسخة {v.version} {v.status==='ISSUED'&&<><Button type="button" onClick={()=>void api.printable(selected.service.id,v.id).then(printSnapshot).catch(e=>setNotice(e instanceof Error?e.message:'تعذرت الطباعة'))}>طباعة</Button>{cap.voucher&&<Button type="button" onClick={()=>void voidVoucher(v.id)}>إبطال</Button>}</>}</p>)}</Card>{cap.cancel&&<Button type="button" onClick={()=>void cancel()}>فحص وإلغاء الخدمة</Button>}</>}
   <Card title="سجل الخدمة">{selected.history.map(entry=><p key={`${entry.kind}:${entry.createdAt}`}>{entry.kind} · {new Date(entry.createdAt).toLocaleString('ar-EG')}</p>)}</Card>
  </Card>}
  {notice&&<Toast>{notice}</Toast>}
 </section>;
}
