import{type FormEvent,useEffect,useState}from'react';
import{crmGet,crmPatch,crmPost}from'./crm-core-client.js';
import{ActionBar,Badge,Button,Card,Checkbox,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,Select,Textarea,Toast}from'./ui.js';

type Program={id:string;code:string;nameAr:string;status:'PREPARING'|'OPEN'|'OPERATING'|'CLOSED'|'CANCELLED';currency:string;departureDate:string;returnDate:string};
type Booking={id:string;code:string;programId:string;customerId:string;travelerIds:string[];status:string};
type Tier={code:string;label:string;sellingPrice:string;estimatedCost:string;capacity:number|null;active:boolean};
type Commercial={programId:string;totalCapacity:number|null;waitlistEnabled:boolean;priceTiers:Tier[];addOnServiceIds:string[];discountPolicy:{maxPercent:number;approvalAbovePercent:number};updatedAt:string};
type Extension={bookingId:string;salesState:'BOOKED'|'WAITLISTED';priceTierCode:string|null;specialRequests:string|null;voucherNumber:string|null;travelPackIssuedAt:string|null;updatedAt:string};
type Amendment={id:string;kind:'TRAVELER'|'SERVICE'|'DATE'|'COMMERCIAL'|'OTHER';reason:string;detail:string;financeReference:string|null;actorId:string;occurredAt:string};
type PaymentItem={id:string;dueDate:string;amount:string;status:'PLANNED'|'SATISFIED'|'WAIVED';evidenceReference:string|null;updatedAt:string};
const freshTier=():Tier=>({code:'',label:'',sellingPrice:'0',estimatedCost:'0',capacity:null,active:true});
function msg(e:unknown){return e instanceof Error?e.message:'تعذر تنفيذ العملية.';}

export function TourismCommercialPage(){
 const[programs,setPrograms]=useState<Program[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[programId,setProgramId]=useState(''),[commercial,setCommercial]=useState<Commercial|null>(null),[bookingId,setBookingId]=useState(''),[extension,setExtension]=useState<Extension|null>(null),[amendments,setAmendments]=useState<Amendment[]>([]),[payments,setPayments]=useState<PaymentItem[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[capacity,setCapacity]=useState(''),[waitlist,setWaitlist]=useState(false),[tiers,setTiers]=useState<Tier[]>([]),[addons,setAddons]=useState(''),[maxDiscount,setMaxDiscount]=useState('0'),[approvalDiscount,setApprovalDiscount]=useState('0');
 const[paymentEvidence,setPaymentEvidence]=useState<Record<string,string>>({}),[salesState,setSalesState]=useState<'BOOKED'|'WAITLISTED'>('BOOKED'),[priceTier,setPriceTier]=useState(''),[specialRequests,setSpecialRequests]=useState(''),[amendment,setAmendment]=useState({kind:'OTHER' as Amendment['kind'],reason:'',detail:'',financeReference:''}),[paymentDraft,setPaymentDraft]=useState<Array<{dueDate:string;amount:string}>>([{dueDate:'',amount:''}]),[voucher,setVoucher]=useState('');
 async function load(){try{const[p,b]=await Promise.all([crmGet<Program[]>('/tourism/programs'),crmGet<Booking[]>('/tourism/bookings')]);setPrograms(p);setBookings(b);setError('');}catch(e){setError(msg(e));}}
 useEffect(()=>{void load();},[]);
 async function chooseProgram(id:string){setProgramId(id);setCommercial(null);if(!id)return;try{const c=await crmGet<Commercial>('/tourism/programs/'+id+'/commercial');setCommercial(c);setCapacity(c.totalCapacity===null?'':String(c.totalCapacity));setWaitlist(c.waitlistEnabled);setTiers(c.priceTiers.map(x=>({...x})));setAddons(c.addOnServiceIds.join(', '));setMaxDiscount(String(c.discountPolicy.maxPercent));setApprovalDiscount(String(c.discountPolicy.approvalAbovePercent));}catch(e){setNotice(msg(e));}}
 async function saveCommercial(event:FormEvent){event.preventDefault();if(!programId)return;try{const c=await crmPatch<Commercial>('/tourism/programs/'+programId+'/commercial',{totalCapacity:capacity===''?null:Number(capacity),waitlistEnabled:waitlist,priceTiers:tiers.map(t=>({...t,capacity:t.capacity===null?null:Number(t.capacity)})),addOnServiceIds:addons.split(',').map(x=>x.trim()).filter(Boolean),discountPolicy:{maxPercent:Number(maxDiscount),approvalAbovePercent:Number(approvalDiscount)}});setCommercial(c);setNotice('تم حفظ التسعير والسعة وسياسة الخصم والإضافات للبرنامج.');}catch(e){setNotice(msg(e));}}
 async function chooseBooking(id:string){setBookingId(id);setExtension(null);setAmendments([]);setPayments([]);if(!id)return;try{const[e,a,p]=await Promise.all([crmGet<Extension>('/tourism/bookings/'+id+'/extension'),crmGet<Amendment[]>('/tourism/bookings/'+id+'/amendments'),crmGet<PaymentItem[]>('/tourism/bookings/'+id+'/payment-plan')]);setExtension(e);setSalesState(e.salesState);setPriceTier(e.priceTierCode??'');setSpecialRequests(e.specialRequests??'');setVoucher(e.voucherNumber??'');setAmendments(a);setPayments(p);setPaymentDraft(p.filter(x=>x.status==='PLANNED').map(x=>({dueDate:x.dueDate,amount:x.amount})).length?p.filter(x=>x.status==='PLANNED').map(x=>({dueDate:x.dueDate,amount:x.amount})):[{dueDate:'',amount:''}]);}catch(e){setNotice(msg(e));}}
 async function saveBookingExtension(event:FormEvent){event.preventDefault();if(!bookingId)return;try{const e=await crmPatch<Extension>('/tourism/bookings/'+bookingId+'/extension',{salesState,priceTierCode:priceTier||null,specialRequests:specialRequests||null});setExtension(e);setNotice('تم حفظ الحالة التجارية وطلبات العميل الخاصة.');}catch(e){setNotice(msg(e));}}
 async function addAmendment(event:FormEvent){event.preventDefault();if(!bookingId)return;try{await crmPost('/tourism/bookings/'+bookingId+'/amendments',{kind:amendment.kind,reason:amendment.reason,detail:amendment.detail,...amendment.financeReference?{financeReference:amendment.financeReference}:{}});setAmendment({kind:'OTHER',reason:'',detail:'',financeReference:''});setNotice('تم تسجيل التعديل مع أثره المالي المرجعي إن وجد.');await chooseBooking(bookingId);}catch(e){setNotice(msg(e));}}
 async function savePaymentPlan(event:FormEvent){event.preventDefault();if(!bookingId)return;try{const items=paymentDraft.filter(x=>x.dueDate&&x.amount);await crmPost('/tourism/bookings/'+bookingId+'/payment-plan',{items});setNotice('تم حفظ خطة السداد.');await chooseBooking(bookingId);}catch(e){setNotice(msg(e));}}
 async function satisfy(item:PaymentItem){if(!bookingId)return;const evidence=paymentEvidence[item.id]?.trim();if(!evidence){setNotice('أدخل مرجع السداد المالي أولًا.');return;}try{await crmPost('/tourism/bookings/'+bookingId+'/payment-plan/'+item.id+'/satisfy',{evidenceReference:evidence});setPaymentEvidence(v=>({...v,[item.id]:''}));setNotice('تم ربط بند الخطة بدليل السداد دون إنشاء حركة مالية موازية.');await chooseBooking(bookingId);}catch(e){setNotice(msg(e));}}
 async function issueVoucher(){if(!bookingId||!voucher.trim())return;try{const e=await crmPost<Extension>('/tourism/bookings/'+bookingId+'/voucher',{voucherNumber:voucher});setExtension(e);setNotice('تم إصدار رقم القسيمة للحجز.');}catch(e){setNotice(msg(e));}}
 async function issuePack(){if(!bookingId)return;try{const e=await crmPost<Extension>('/tourism/bookings/'+bookingId+'/travel-pack',{});setExtension(e);setNotice('تم تعليم Travel Pack كمُصدر للحجز.');}catch(e){setNotice(msg(e));}}
 const selectedProgram=programs.find(p=>p.id===programId),selectedBooking=bookings.find(b=>b.id===bookingId),bookingProgram=programs.find(p=>p.id===selectedBooking?.programId);
 return <section dir="rtl" className="ui-page-stack" aria-label="التجارة والتشغيل السياحي">
  {notice?<Toast tone="success">{notice}</Toast>:null}{error?<ErrorState message={error}/>:null}
  <Card title="التسعير والسعة والتشغيل التجاري"><p>إدارة الجانب التجاري لبرامج السياحة والحجوزات دون تكرار حقائق المخزون أو التمويل.</p></Card>
  <Card title="برنامج سياحي"><FormField label="البرنامج"><Select value={programId} onChange={e=>void chooseProgram(e.target.value)}><option value="">اختر البرنامج</option>{programs.map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr} — {p.status}</option>)}</Select></FormField>{selectedProgram?<p>العملة: {selectedProgram.currency} · السفر: {selectedProgram.departureDate} · العودة: {selectedProgram.returnDate}</p>:null}</Card>
  {commercial?<DisclosureCard title="الإعداد التجاري للبرنامج" description="يمكن التعديل أثناء التجهيز أو البيع فقط؛ بعد بدء التشغيل يصبح الإعداد التجاري مقفولًا."><form onSubmit={saveCommercial}><FormField label="السعة الكلية"><Input type="number" min="0" value={capacity} onChange={e=>setCapacity(e.target.value)}/></FormField><label className="ui-checkbox-field"><Checkbox checked={waitlist} onChange={e=>setWaitlist(e.target.checked)}/><span>تفعيل قائمة الانتظار</span></label><FormField label="خدمات إضافية — IDs مفصولة بفاصلة"><Input value={addons} onChange={e=>setAddons(e.target.value)}/></FormField><FormField label="أقصى خصم %"><Input type="number" min="0" max="100" value={maxDiscount} onChange={e=>setMaxDiscount(e.target.value)}/></FormField><FormField label="يحتاج اعتمادًا فوق %"><Input type="number" min="0" max="100" value={approvalDiscount} onChange={e=>setApprovalDiscount(e.target.value)}/></FormField><h3>شرائح السعر</h3>{tiers.map((t,i)=><Card key={i} title={'شريحة '+(i+1)}><FormField label="الكود" required><Input required value={t.code} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,code:e.target.value.toUpperCase()}:x))}/></FormField><FormField label="الاسم" required><Input required value={t.label} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/></FormField><FormField label="سعر البيع" required><Input required inputMode="decimal" value={t.sellingPrice} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,sellingPrice:e.target.value}:x))}/></FormField><FormField label="التكلفة المتوقعة" required><Input required inputMode="decimal" value={t.estimatedCost} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,estimatedCost:e.target.value}:x))}/></FormField><p>الهامش المتوقع: {(Number(t.sellingPrice||0)-Number(t.estimatedCost||0)).toLocaleString('ar-EG')}</p><FormField label="سعة الشريحة"><Input type="number" min="0" value={t.capacity??''} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,capacity:e.target.value===''?null:Number(e.target.value)}:x))}/></FormField><label className="ui-checkbox-field"><Checkbox checked={t.active} onChange={e=>setTiers(v=>v.map((x,n)=>n===i?{...x,active:e.target.checked}:x))}/><span>نشطة</span></label><Button type="button" variant="secondary" onClick={()=>setTiers(v=>v.filter((_,n)=>n!==i))}>حذف</Button></Card>)}<ActionBar><Button type="button" variant="secondary" onClick={()=>setTiers(v=>[...v,freshTier()])}>إضافة شريحة</Button><Button type="submit">حفظ الإعداد التجاري</Button></ActionBar></form></DisclosureCard>:null}
  <Card title="إدارة حجز تجاري"><FormField label="الحجز"><Select value={bookingId} onChange={e=>void chooseBooking(e.target.value)}><option value="">اختر الحجز</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.code} — {programs.find(p=>p.id===b.programId)?.nameAr??b.programId} — {b.status}</option>)}</Select></FormField>{selectedBooking?<p>العميل: {selectedBooking.customerId} · المسافرون: {selectedBooking.travelerIds.length} · البرنامج: {bookingProgram?.nameAr??selectedBooking.programId}</p>:null}</Card>
  {extension?<><Card title="الحالة التجارية والطلبات الخاصة"><form onSubmit={saveBookingExtension}><FormField label="الحالة التجارية"><Select value={salesState} onChange={e=>setSalesState(e.target.value as typeof salesState)}><option value="BOOKED">حجز مؤكد تجاريًا</option><option value="WAITLISTED">قائمة انتظار</option></Select></FormField><FormField label="شريحة السعر"><Select value={priceTier} onChange={e=>setPriceTier(e.target.value)}><option value="">بدون شريحة</option>{(commercial?.priceTiers??[]).filter(t=>t.active).map(t=><option key={t.code} value={t.code}>{t.label} — {t.sellingPrice}</option>)}</Select></FormField><FormField label="طلبات خاصة"><Textarea value={specialRequests} onChange={e=>setSpecialRequests(e.target.value)}/></FormField><Button type="submit">حفظ</Button></form></Card>
  <DisclosureCard title="تعديل على الحجز" description="سجل تعديل العميل أو الخدمة أو التاريخ أو الشروط التجارية؛ المرجع المالي اختياري ويشير إلى أثر موجود في المالك المالي."><form onSubmit={addAmendment}><FormField label="نوع التعديل"><Select value={amendment.kind} onChange={e=>setAmendment({...amendment,kind:e.target.value as Amendment['kind']})}>{['TRAVELER','SERVICE','DATE','COMMERCIAL','OTHER'].map(v=><option key={v} value={v}>{v}</option>)}</Select></FormField><FormField label="السبب" required><Input required value={amendment.reason} onChange={e=>setAmendment({...amendment,reason:e.target.value})}/></FormField><FormField label="التفاصيل" required><Textarea required value={amendment.detail} onChange={e=>setAmendment({...amendment,detail:e.target.value})}/></FormField><FormField label="مرجع مالي — إن وجد"><Input value={amendment.financeReference} onChange={e=>setAmendment({...amendment,financeReference:e.target.value})}/></FormField><Button type="submit">تسجيل التعديل</Button></form></DisclosureCard>
  <Card title="سجل التعديلات">{!amendments.length?<EmptyState/>:<DataGrid columns={['النوع','السبب','التفاصيل','المرجع المالي','الوقت']}>{amendments.map(a=><tr key={a.id}><td>{a.kind}</td><td>{a.reason}</td><td>{a.detail}</td><td>{a.financeReference??'—'}</td><td>{new Date(a.occurredAt).toLocaleString('ar-EG')}</td></tr>)}</DataGrid>}</Card>
  <DisclosureCard title="خطة السداد" description="الخطة تشغيلية فقط؛ تعليم بند كمسدد يتطلب مرجعًا ماليًا حقيقيًا ولا ينشئ قبضًا جديدًا."><form onSubmit={savePaymentPlan}>{paymentDraft.map((p,i)=><div key={i} className="ui-filter-grid"><FormField label="تاريخ الاستحقاق"><Input type="date" value={p.dueDate} onChange={e=>setPaymentDraft(v=>v.map((x,n)=>n===i?{...x,dueDate:e.target.value}:x))}/></FormField><FormField label="المبلغ"><Input inputMode="decimal" value={p.amount} onChange={e=>setPaymentDraft(v=>v.map((x,n)=>n===i?{...x,amount:e.target.value}:x))}/></FormField><Button type="button" variant="secondary" onClick={()=>setPaymentDraft(v=>v.filter((_,n)=>n!==i))}>حذف</Button></div>)}<ActionBar><Button type="button" variant="secondary" onClick={()=>setPaymentDraft(v=>[...v,{dueDate:'',amount:''}])}>إضافة قسط</Button><Button type="submit">حفظ الخطة</Button></ActionBar></form></DisclosureCard>
  <Card title="حالة خطة السداد">{!payments.length?<EmptyState/>:<DataGrid columns={['الاستحقاق','المبلغ','الحالة','الدليل المالي','إجراء']}>{payments.map(p=><tr key={p.id}><td>{p.dueDate}</td><td>{p.amount}</td><td><Badge tone={p.status==='SATISFIED'?'success':'info'}>{p.status}</Badge></td><td>{p.evidenceReference??'—'}</td><td>{p.status==='PLANNED'?<><Input aria-label="مرجع السداد المالي" value={paymentEvidence[p.id]??''} onChange={e=>setPaymentEvidence(v=>({...v,[p.id]:e.target.value}))} placeholder="مرجع القبض/التسوية"/><Button type="button" variant="secondary" onClick={()=>void satisfy(p)}>ربط سداد</Button></>:'—'}</td></tr>)}</DataGrid>}</Card>
  <Card title="القسيمة وTravel Pack"><FormField label="رقم القسيمة"><Input value={voucher} onChange={e=>setVoucher(e.target.value)}/></FormField><ActionBar><Button type="button" disabled={!voucher.trim()} onClick={()=>void issueVoucher()}>إصدار القسيمة</Button><Button type="button" variant="secondary" onClick={()=>void issuePack()}>إصدار Travel Pack</Button></ActionBar><p>القسيمة الحالية: {extension.voucherNumber??'—'} · Travel Pack: {extension.travelPackIssuedAt?new Date(extension.travelPackIssuedAt).toLocaleString('ar-EG'):'لم يصدر'}</p></Card></>:null}
 </section>;
}
