import{type FormEvent,useEffect,useState}from'react';
import{tourismOperationsApi,type ItineraryDay,type TourismBooking,type TourismBookingConfirm,type TourismProgram,type TourismProgramInput}from'./tourism-operations-client.js';
import{ActionBar,Badge,Button,Card,Checkbox,DataGrid,DisclosureCard,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select,Tabs,Textarea,Toast}from'./ui.js';
import{customerReferenceLabel,emptyOperationalReferenceData,loadOperationalReferenceData,travelerReferenceLabel,type OperationalReferenceData}from'./reference-data-client.js';

const programStatus:Record<string,string>={PREPARING:'تحت التجهيز',OPEN:'مفتوح للبيع',OPERATING:'قيد التشغيل',CLOSED:'مغلق',CANCELLED:'ملغي'};
const bookingStatus:Record<string,string>={DRAFT:'مسودة',CONFIRMING:'جارٍ التأكيد',CONFIRMED:'مؤكد',CANCELLING:'جارٍ الإلغاء',CANCELLATION_REQUIRED:'يحتاج تسوية قبل الإلغاء',CANCELLED:'ملغي',COMPLETED:'مكتمل'};
const blankProgram:TourismProgramInput={code:'',nameAr:'',departureDate:'',returnDate:'',salesOpen:'',salesClose:'',currency:'EGP',notes:''};
const blankItinerary={dayNumber:'1',serviceDate:'',title:'',description:'',location:''};
const blankBooking={code:'',programId:'',customerId:'',travelerIds:[] as string[]};
const blankConfirm={category:'HOTEL' as TourismBookingConfirm['category'],costCenterId:'',currency:'EGP',grossAmount:'',discountAmount:'0',postingDate:'',dueDate:'',invoiceNumber:'',allocationId:'',contractId:'',resourceType:'HOTEL',resourceId:'',serviceDate:'',quantity:'1',periodEnd:''};

export function TourismOperationsPage({initialTab='programs'}:{initialTab?:'programs'|'bookings'|'itinerary'}={}){
 const[tab,setTab]=useState(initialTab),[programs,setPrograms]=useState<TourismProgram[]>([]),[bookings,setBookings]=useState<TourismBooking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function reload(){setLoading(true);setError('');try{const[p,b]=await Promise.all([tourismOperationsApi.programs(),tourismOperationsApi.bookings()]);setPrograms(p);setBookings(b);}catch(value){setError(value instanceof Error?value.message:'تعذر تحميل السياحة العامة.');}finally{setLoading(false);}}
 useEffect(()=>{void reload();},[]);
 if(loading)return <LoadingState/>;if(error)return <ErrorState message={error}/>;
 return <section dir="rtl" className="ui-page-stack">
  {notice?<Toast tone="success">{notice}</Toast>:null}
  <Card title="السياحة العامة"><p>مساحة تشغيل موحدة للبرامج والحجوزات والبرنامج اليومي.</p><ActionBar><Button variant="secondary" onClick={()=>void reload()}>تحديث</Button></ActionBar></Card>
  <div className="ui-metric-grid" aria-label="مؤشرات السياحة العامة"><MetricCard label="البرامج" value={programs.length}/><MetricCard label="مفتوح للبيع" value={programs.filter(p=>p.status==='OPEN').length} tone="success"/><MetricCard label="الحجوزات" value={bookings.length}/><MetricCard label="حجوزات مؤكدة" value={bookings.filter(b=>b.status==='CONFIRMED').length} tone="success"/></div>
  <Tabs tabs={[{id:'programs',label:'البرامج السياحية'},{id:'bookings',label:'الحجوزات'},{id:'itinerary',label:'البرنامج اليومي'}]} active={tab} onChange={id=>setTab(id as typeof tab)}/>
  {tab==='programs'?<Programs programs={programs} done={async m=>{setNotice(m);await reload();}}/>:null}
  {tab==='bookings'?<Bookings programs={programs} bookings={bookings} done={async m=>{setNotice(m);await reload();}}/>:null}
  {tab==='itinerary'?<Itinerary programs={programs} done={setNotice}/>:null}
 </section>;
}

function Programs({programs,done}:{programs:TourismProgram[];done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState<TourismProgramInput>(blankProgram);
 async function submit(e:FormEvent){e.preventDefault();await tourismOperationsApi.createProgram(form);setForm(blankProgram);await done('تم إنشاء البرنامج السياحي تحت التجهيز.');}
 async function action(id:string,kind:'open'|'start'|'close'){if(kind==='open')await tourismOperationsApi.openProgram(id);else if(kind==='start')await tourismOperationsApi.startProgram(id);else await tourismOperationsApi.closeProgram(id);await done('تم تحديث دورة البرنامج.');}
 return <><DisclosureCard title="برنامج سياحي جديد" description="افتح النموذج عند إنشاء برنامج جديد؛ قائمة البرامج هي مساحة المتابعة." ><form className="ui-filter-grid" onSubmit={submit}>
  <FormField label="الكود" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField>
  <FormField label="اسم البرنامج" required><Input required value={form.nameAr} onChange={e=>setForm({...form,nameAr:e.target.value})}/></FormField>
  <FormField label="تاريخ السفر" required><Input required type="date" value={form.departureDate} onChange={e=>setForm({...form,departureDate:e.target.value})}/></FormField>
  <FormField label="تاريخ العودة" required><Input required type="date" value={form.returnDate} onChange={e=>setForm({...form,returnDate:e.target.value})}/></FormField>
  <FormField label="فتح البيع" required><Input required type="date" value={form.salesOpen} onChange={e=>setForm({...form,salesOpen:e.target.value})}/></FormField>
  <FormField label="إغلاق البيع" required><Input required type="date" value={form.salesClose} onChange={e=>setForm({...form,salesClose:e.target.value})}/></FormField>
  <FormField label="العملة" required><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField>
  <FormField label="ملاحظات"><Textarea value={form.notes??''} onChange={e=>setForm({...form,notes:e.target.value})}/></FormField>
  <Button type="submit">إنشاء البرنامج</Button>
 </form></DisclosureCard>
 <DataGrid columns={['الكود','البرنامج','السفر','العودة','الحالة','الإجراء']}>{programs.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.nameAr}</td><td>{p.departureDate}</td><td>{p.returnDate}</td><td><Badge tone={p.status==='OPEN'?'success':p.status==='CANCELLED'?'error':'neutral'}>{programStatus[p.status]??p.status}</Badge></td><td><ActionBar>{p.status==='PREPARING'?<Button onClick={()=>void action(p.id,'open')}>فتح للبيع</Button>:null}{p.status==='OPEN'?<Button onClick={()=>void action(p.id,'start')}>بدء التشغيل</Button>:null}{['OPEN','OPERATING'].includes(p.status)?<Button variant="secondary" onClick={()=>void action(p.id,'close')}>إغلاق</Button>:null}</ActionBar></td></tr>)}</DataGrid></>;
}

function Bookings({programs,bookings,done}:{programs:TourismProgram[];bookings:TourismBooking[];done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState(blankBooking),[references,setReferences]=useState<OperationalReferenceData>(emptyOperationalReferenceData),[referenceError,setReferenceError]=useState(''),[confirmId,setConfirmId]=useState(''),[confirm,setConfirm]=useState(blankConfirm);
 useEffect(()=>{loadOperationalReferenceData().then(setReferences).catch(value=>setReferenceError(value instanceof Error?value.message:'تعذر تحميل العملاء والمسافرين.'));},[]);
 async function create(e:FormEvent){e.preventDefault();await tourismOperationsApi.createBooking({code:form.code,programId:form.programId,customerId:form.customerId,travelerIds:form.travelerIds});setForm(blankBooking);await done('تم إنشاء الحجز كمسودة مرتبطة بالبرنامج والعميل والمسافرين.');}
 async function confirmBooking(e:FormEvent){e.preventDefault();if(!confirmId)return;await tourismOperationsApi.confirmBooking(confirmId,{commandKey:'tourism-confirm:'+confirmId+':'+confirm.invoiceNumber,category:confirm.category,costCenterId:confirm.costCenterId,currency:confirm.currency,grossAmount:confirm.grossAmount,discountAmount:confirm.discountAmount,postingDate:confirm.postingDate,dueDate:confirm.dueDate,invoiceNumber:confirm.invoiceNumber,inventories:[{allocationId:confirm.allocationId,contractId:confirm.contractId,resourceType:confirm.resourceType,resourceId:confirm.resourceId,serviceDate:confirm.serviceDate,quantity:confirm.quantity,...(confirm.periodEnd?{periodEnd:confirm.periodEnd}:{})}]});setConfirmId('');setConfirm(blankConfirm);await done('تم تأكيد الحجز عبر مسار المخزون والتمويل المعتمد.');}
 async function cancel(b:TourismBooking){const date=new Date().toISOString().slice(0,10),commandKey=b.pendingCommandKey??'tourism-cancel:'+b.id+':'+date;await tourismOperationsApi.cancelBooking(b.id,{commandKey,postingDate:date});await done('تم تنفيذ طلب الإلغاء وفق الموانع المالية المسجلة.');}
 return <><DisclosureCard title="حجز سياحي جديد" description="افتح النموذج عند تسجيل حجز جديد؛ قائمة الحجوزات تظهر أولًا للمراجعة اليومية."><form className="ui-filter-grid" onSubmit={create}><FormField label="رقم الحجز" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField><FormField label="البرنامج" required><Select required value={form.programId} onChange={e=>setForm({...form,programId:e.target.value})}><option value="">اختر برنامجًا مفتوحًا</option>{programs.filter(p=>p.status==='OPEN').map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr}</option>)}</Select></FormField><FormField label="العميل" required><Select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value,travelerIds:[]})}><option value="">اختر العميل</option>{references.customers.map(customer=><option key={customer.customer.id} value={customer.customer.id}>{customerReferenceLabel(customer)}</option>)}</Select></FormField><FormField label="المسافرون" required hint="اختر المسافرين المرتبطين بالعميل"><div>{references.travelers.filter(traveler=>!form.customerId||traveler.customerId===form.customerId).map(traveler=><label className="ui-checkbox-field" key={traveler.id}><Checkbox checked={form.travelerIds.includes(traveler.id)} onChange={event=>setForm({...form,travelerIds:event.target.checked?[...form.travelerIds,traveler.id]:form.travelerIds.filter(id=>id!==traveler.id)})}/><span>{travelerReferenceLabel(traveler)}</span></label>)}</div></FormField>{referenceError?<ErrorState message={referenceError}/>:null}<Button type="submit">إنشاء الحجز</Button></form></DisclosureCard>
 <DataGrid columns={['الحجز','البرنامج','العميل','المسافرون','الحالة','الإجراء']}>{bookings.map(b=>{
  const canConfirm=b.status==='DRAFT'||b.status==='CONFIRMING';
  const canCancel=b.status==='CONFIRMED'||b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED';
  const tone=b.status==='CONFIRMED'?'success':(b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED')?'warning':b.status==='CANCELLED'?'error':'neutral';
  return <tr key={b.id}>
   <td>{b.code}</td><td>{programs.find(p=>p.id===b.programId)?.nameAr??b.programId}</td><td>{references.customers.find(customer=>customer.customer.id===b.customerId)?.party.displayName??b.customerId}</td><td>{b.travelerIds.length}</td>
   <td><Badge tone={tone}>{bookingStatus[b.status]??b.status}</Badge></td>
   <td><ActionBar>{canConfirm?<Button onClick={()=>setConfirmId(b.id)}>تأكيد مالي</Button>:null}{canCancel?<Button variant="danger" onClick={()=>void cancel(b)}>طلب إلغاء</Button>:null}{b.status==='CONFIRMED'?<Button variant="secondary" onClick={()=>void tourismOperationsApi.completeBooking(b.id).then(()=>done('تم إكمال الحجز.'))}>إكمال</Button>:null}</ActionBar></td>
  </tr>;
 })}</DataGrid>
 {confirmId?<Card title="تأكيد الحجز ماليًا"><form className="ui-filter-grid" onSubmit={confirmBooking}><FormField label="التصنيف"><Select value={confirm.category} onChange={e=>setConfirm({...confirm,category:e.target.value as TourismBookingConfirm['category']})}><option value="HOTEL">فندق</option><option value="FLIGHT">طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرة</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="مركز التكلفة" required><Input required value={confirm.costCenterId} onChange={e=>setConfirm({...confirm,costCenterId:e.target.value})}/></FormField><FormField label="العملة" required><Input required value={confirm.currency} onChange={e=>setConfirm({...confirm,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="الإجمالي" required><Input required inputMode="decimal" value={confirm.grossAmount} onChange={e=>setConfirm({...confirm,grossAmount:e.target.value})}/></FormField><FormField label="الخصم"><Input inputMode="decimal" value={confirm.discountAmount} onChange={e=>setConfirm({...confirm,discountAmount:e.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={confirm.postingDate} onChange={e=>setConfirm({...confirm,postingDate:e.target.value})}/></FormField><FormField label="الاستحقاق" required><Input required type="date" value={confirm.dueDate} onChange={e=>setConfirm({...confirm,dueDate:e.target.value})}/></FormField><FormField label="رقم الفاتورة" required><Input required value={confirm.invoiceNumber} onChange={e=>setConfirm({...confirm,invoiceNumber:e.target.value})}/></FormField><FormField label="Allocation ID" required><Input required value={confirm.allocationId} onChange={e=>setConfirm({...confirm,allocationId:e.target.value})}/></FormField><FormField label="Contract ID" required><Input required value={confirm.contractId} onChange={e=>setConfirm({...confirm,contractId:e.target.value})}/></FormField><FormField label="نوع المورد" required><Input required value={confirm.resourceType} onChange={e=>setConfirm({...confirm,resourceType:e.target.value})}/></FormField><FormField label="Resource ID" required><Input required value={confirm.resourceId} onChange={e=>setConfirm({...confirm,resourceId:e.target.value})}/></FormField><FormField label="تاريخ الخدمة" required><Input required type="date" value={confirm.serviceDate} onChange={e=>setConfirm({...confirm,serviceDate:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={confirm.quantity} onChange={e=>setConfirm({...confirm,quantity:e.target.value})}/></FormField><ActionBar><Button type="submit">تأكيد</Button><Button type="button" variant="secondary" onClick={()=>setConfirmId('')}>إلغاء</Button></ActionBar></form></Card>:null}
 </>;
}

function Itinerary({programs,done}:{programs:TourismProgram[];done:(message:string)=>void}){
 const[programId,setProgramId]=useState(''),[days,setDays]=useState<ItineraryDay[]>([]),[form,setForm]=useState(blankItinerary),[error,setError]=useState('');
 async function load(id:string){setProgramId(id);setError('');if(!id){setDays([]);return}try{setDays(await tourismOperationsApi.itinerary(id));}catch(value){setError(value instanceof Error?value.message:'تعذر تحميل البرنامج اليومي.');}}
 async function submit(e:FormEvent){e.preventDefault();if(!programId)return;try{await tourismOperationsApi.createItinerary(programId,{dayNumber:Number(form.dayNumber),serviceDate:form.serviceDate,title:form.title,description:form.description,location:form.location});setForm(blankItinerary);await load(programId);done('تمت إضافة اليوم إلى البرنامج.');}catch(value){setError(value instanceof Error?value.message:'تعذر الحفظ.');}}
 const selected=programs.find(p=>p.id===programId);
 return <><Card title="البرنامج اليومي"><FormField label="البرنامج"><Select value={programId} onChange={e=>void load(e.target.value)}><option value="">اختر البرنامج</option>{programs.map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr}</option>)}</Select></FormField>{selected?.status==='PREPARING'?<form className="ui-filter-grid" onSubmit={submit}><FormField label="رقم اليوم"><Input required type="number" min="1" value={form.dayNumber} onChange={e=>setForm({...form,dayNumber:e.target.value})}/></FormField><FormField label="التاريخ"><Input required type="date" value={form.serviceDate} onChange={e=>setForm({...form,serviceDate:e.target.value})}/></FormField><FormField label="العنوان"><Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></FormField><FormField label="المكان"><Input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></FormField><FormField label="التفاصيل"><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></FormField><Button type="submit">إضافة اليوم</Button></form>:selected?<p>يصبح البرنامج اليومي للقراءة فقط بعد فتح البرنامج للبيع.</p>:null}</Card>{error?<ErrorState message={error}/>:programId&&days.length===0?<EmptyState title="لا يوجد برنامج يومي بعد"/>:<DataGrid columns={['اليوم','التاريخ','العنوان','المكان']}>{days.map(d=><tr key={d.id}><td>{d.dayNumber}</td><td>{d.serviceDate}</td><td>{d.title}</td><td>{d.location??'—'}</td></tr>)}</DataGrid>}</>;
}
