import{type FormEvent,useEffect,useMemo,useState}from'react';
import{tourismOperationsApi,type ItineraryDay,type TourismBooking,type TourismBookingConfirm,type TourismCustomerReference,type TourismProgram,type TourismProgramInput,type TourismTravelerReference}from'./tourism-operations-client.js';
import{ActionBar,Badge,Button,Card,DataGrid,Dialog,DisclosureCard,EmptyState,ErrorState,FormField,Input,LoadingState,MetricCard,Select,Tabs,Textarea,Toast}from'./ui.js';

const programStatus:Record<string,string>={PREPARING:'تحت التجهيز',OPEN:'مفتوح للبيع',OPERATING:'قيد التشغيل',CLOSED:'مغلق',CANCELLED:'ملغي'};
const bookingStatus:Record<string,string>={DRAFT:'مسودة',CONFIRMING:'جارٍ التأكيد',CONFIRMED:'مؤكد',CANCELLING:'جارٍ الإلغاء',CANCELLATION_REQUIRED:'يحتاج تسوية قبل الإلغاء',CANCELLED:'ملغي',COMPLETED:'مكتمل'};
const blankProgram:TourismProgramInput={code:'',nameAr:'',departureDate:'',returnDate:'',salesOpen:'',salesClose:'',currency:'EGP',notes:''};
const blankItinerary={dayNumber:'1',serviceDate:'',title:'',description:'',location:''};
const blankBooking:{code:string;programId:string;customerId:string;travelerIds:string[]}={code:'',programId:'',customerId:'',travelerIds:[]};
const blankConfirm={category:'HOTEL' as TourismBookingConfirm['category'],costCenterId:'',currency:'EGP',grossAmount:'',discountAmount:'0',postingDate:'',dueDate:'',invoiceNumber:'',allocationId:'',contractId:'',resourceType:'HOTEL',resourceId:'',serviceDate:'',quantity:'1',periodEnd:''};
const today=()=>new Date().toISOString().slice(0,10);

export function TourismOperationsPage({initialTab='programs'}:{initialTab?:'programs'|'bookings'|'itinerary'}={}){
 const[tab,setTab]=useState(initialTab),[programs,setPrograms]=useState<TourismProgram[]>([]),[bookings,setBookings]=useState<TourismBooking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function reload(){setLoading(true);setError('');try{const[p,b]=await Promise.all([tourismOperationsApi.programs(),tourismOperationsApi.bookings()]);setPrograms(p);setBookings(b);}catch(value){setError(value instanceof Error?value.message:'تعذر تحميل السياحة العامة.');}finally{setLoading(false);}}
 useEffect(()=>{void reload();},[]);
 if(loading)return <LoadingState/>;if(error)return <ErrorState message={error}/>;
 return <section dir="rtl" className="ui-page-stack">
  {notice?<Toast tone="success">{notice}</Toast>:null}
  <Card title="السياحة العامة"><p>مساحة تشغيل موحدة للبرامج والحجوزات والبرنامج اليومي.</p><ActionBar><Button variant="secondary" onClick={()=>void reload()}>تحديث</Button></ActionBar></Card>
  <div className="ui-metric-grid" aria-label="مؤشرات السياحة العامة"><MetricCard label="البرامج" value={programs.length}/><MetricCard label="مفتوح للبيع" value={programs.filter(p=>p.status==='OPEN').length} tone="success"/><MetricCard label="الحجوزات" value={bookings.length}/><MetricCard label="حجوزات مؤكدة" value={bookings.filter(b=>b.status==='CONFIRMED').length} tone="success"/></div>
  <Tabs tabs={[{id:'programs',label:'البرامج السياحية'},{id:'bookings',label:'الحجوزات'},{id:'itinerary',label:'البرنامج اليومي'}]} active={tab} onChange={id=>setTab(id as typeof tab)}/>
  {tab==='programs'?<Programs programs={programs} done={async m=>{setNotice(m);await reload();}}/>:null}
  {tab==='bookings'?<Bookings programs={programs} bookings={bookings} done={async m=>{setNotice(m);await reload();}}/>:null}
  {tab==='itinerary'?<Itinerary programs={programs} done={setNotice}/>:null}
 </section>;
}

function ProgramFields({form,setForm}:{form:TourismProgramInput;setForm:(value:TourismProgramInput)=>void}){
 return <>
  <FormField label="الكود" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField>
  <FormField label="اسم البرنامج" required><Input required value={form.nameAr} onChange={e=>setForm({...form,nameAr:e.target.value})}/></FormField>
  <FormField label="الاسم بالإنجليزية"><Input value={form.nameEn??''} onChange={e=>setForm({...form,nameEn:e.target.value})}/></FormField>
  <FormField label="تاريخ السفر" required><Input required type="date" value={form.departureDate} onChange={e=>setForm({...form,departureDate:e.target.value})}/></FormField>
  <FormField label="تاريخ العودة" required><Input required type="date" value={form.returnDate} onChange={e=>setForm({...form,returnDate:e.target.value})}/></FormField>
  <FormField label="فتح البيع" required><Input required type="date" value={form.salesOpen} onChange={e=>setForm({...form,salesOpen:e.target.value})}/></FormField>
  <FormField label="إغلاق البيع" required><Input required type="date" value={form.salesClose} onChange={e=>setForm({...form,salesClose:e.target.value})}/></FormField>
  <FormField label="العملة" required><Input required value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></FormField>
  <FormField label="ملاحظات"><Textarea value={form.notes??''} onChange={e=>setForm({...form,notes:e.target.value})}/></FormField>
 </>;
}

function Programs({programs,done}:{programs:TourismProgram[];done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState<TourismProgramInput>(blankProgram),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE');
 const[editing,setEditing]=useState<TourismProgram|null>(null),[editForm,setEditForm]=useState<TourismProgramInput>(blankProgram),[cancelling,setCancelling]=useState<TourismProgram|null>(null),[cancelReason,setCancelReason]=useState('');
 const filtered=useMemo(()=>programs.filter(program=>{
  const q=query.trim().toLowerCase(),matchesQuery=!q||`${program.code} ${program.nameAr} ${program.nameEn??''}`.toLowerCase().includes(q);
  const matchesStatus=status==='ALL'||(status==='ACTIVE'&&!['CLOSED','CANCELLED'].includes(program.status))||program.status===status;
  return matchesQuery&&matchesStatus;
 }).sort((a,b)=>a.departureDate.localeCompare(b.departureDate)),[programs,query,status]);
 async function submit(e:FormEvent){e.preventDefault();await tourismOperationsApi.createProgram(form);setForm(blankProgram);await done('تم إنشاء البرنامج السياحي تحت التجهيز.');}
 async function action(id:string,kind:'open'|'start'|'close'){if(kind==='open')await tourismOperationsApi.openProgram(id);else if(kind==='start')await tourismOperationsApi.startProgram(id);else await tourismOperationsApi.closeProgram(id);await done('تم تحديث دورة البرنامج.');}
 function beginEdit(program:TourismProgram){setEditing(program);setEditForm({code:program.code,nameAr:program.nameAr,nameEn:program.nameEn,departureDate:program.departureDate,returnDate:program.returnDate,salesOpen:program.salesOpen,salesClose:program.salesClose,currency:program.currency,notes:program.notes});}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!editing)return;await tourismOperationsApi.updateProgram(editing.id,editForm);setEditing(null);await done('تم تعديل البرنامج قبل فتحه للبيع.');}
 async function cancelProgram(e:FormEvent){e.preventDefault();if(!cancelling||!cancelReason.trim())return;const postingDate=today();await tourismOperationsApi.cancelProgram(cancelling.id,{reason:cancelReason.trim(),commandKey:`tourism-program-cancel:${cancelling.id}:${postingDate}`,postingDate});setCancelling(null);setCancelReason('');await done('تم إلغاء البرنامج بعد اجتياز فحص التسوية المالية.');}
 return <>
  <DisclosureCard title="برنامج سياحي جديد" description="افتح النموذج عند إنشاء برنامج جديد؛ قائمة البرامج هي مساحة المتابعة."><form className="ui-filter-grid" onSubmit={submit}><ProgramFields form={form} setForm={setForm}/><Button type="submit">إنشاء البرنامج</Button></form></DisclosureCard>
  <Card title="بحث وتصفية البرامج"><div className="ui-filter-grid"><FormField label="بحث"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="الكود أو اسم البرنامج"/></FormField><FormField label="الحالة"><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">الحالية</option><option value="ALL">الكل</option><option value="PREPARING">تحت التجهيز</option><option value="OPEN">مفتوح للبيع</option><option value="OPERATING">قيد التشغيل</option><option value="CLOSED">مغلق</option><option value="CANCELLED">ملغي</option></Select></FormField></div></Card>
  {filtered.length?<DataGrid columns={['الكود','البرنامج','السفر','العودة','فترة البيع','الحالة','الإجراء']}>{filtered.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.nameAr}</td><td>{p.departureDate}</td><td>{p.returnDate}</td><td>{p.salesOpen} → {p.salesClose}</td><td><Badge tone={p.status==='OPEN'?'success':p.status==='CANCELLED'?'error':p.status==='OPERATING'?'warning':'neutral'}>{programStatus[p.status]??p.status}</Badge></td><td><ActionBar>
   {p.status==='PREPARING'?<Button variant="secondary" onClick={()=>beginEdit(p)}>تعديل</Button>:null}
   {p.status==='PREPARING'?<Button onClick={()=>void action(p.id,'open')}>فتح للبيع</Button>:null}
   {p.status==='OPEN'?<Button onClick={()=>void action(p.id,'start')}>بدء التشغيل</Button>:null}
   {['OPEN','OPERATING'].includes(p.status)?<Button variant="secondary" onClick={()=>void action(p.id,'close')}>إغلاق</Button>:null}
   {['PREPARING','OPEN'].includes(p.status)?<Button variant="danger" onClick={()=>{setCancelling(p);setCancelReason('');}}>إلغاء البرنامج</Button>:null}
  </ActionBar></td></tr>)}</DataGrid>:<EmptyState title="لا توجد برامج ضمن الفلتر"/>}
  <Dialog open={Boolean(editing)} title="تعديل البرنامج" onClose={()=>setEditing(null)}><form className="ui-filter-grid" onSubmit={saveEdit}><ProgramFields form={editForm} setForm={setEditForm}/><ActionBar><Button type="submit">حفظ التعديل</Button><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>إغلاق</Button></ActionBar></form></Dialog>
  <Dialog open={Boolean(cancelling)} title="إلغاء البرنامج" onClose={()=>setCancelling(null)}><form onSubmit={cancelProgram}><p>الإلغاء يمر عبر فحص المالية؛ لن يتم إلغاء برنامج عليه مانع تسوية.</p><FormField label="سبب الإلغاء" required><Textarea required value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/></FormField><Button type="submit" variant="danger" disabled={!cancelReason.trim()}>تأكيد الإلغاء</Button></form></Dialog>
 </>;
}

function Bookings({programs,bookings,done}:{programs:TourismProgram[];bookings:TourismBooking[];done:(message:string)=>Promise<void>}){
 const[form,setForm]=useState(blankBooking),[confirmId,setConfirmId]=useState(''),[confirm,setConfirm]=useState(blankConfirm),[customers,setCustomers]=useState<TourismCustomerReference[]>([]),[travelers,setTravelers]=useState<TourismTravelerReference[]>([]),[selectorError,setSelectorError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE');
 useEffect(()=>{void (async()=>{const results=await Promise.allSettled([tourismOperationsApi.customers(),tourismOperationsApi.travelers()]);if(results[0].status==='fulfilled')setCustomers(results[0].value);else setSelectorError('تعذر تحميل قائمة العملاء.');if(results[1].status==='fulfilled')setTravelers(results[1].value);else setSelectorError(value=>value||'تعذر تحميل قائمة المسافرين.');})();},[]);
 const customerNames=useMemo(()=>new Map(customers.map(item=>[item.customer.id,item.party.displayName])),[customers]);
 const travelerNames=useMemo(()=>new Map(travelers.map(item=>[item.id,item.fullName])),[travelers]);
 const filtered=useMemo(()=>bookings.filter(booking=>{
  const q=query.trim().toLowerCase(),program=programs.find(item=>item.id===booking.programId),customer=customerNames.get(booking.customerId)??booking.customerId;
  const matchesQuery=!q||`${booking.code} ${program?.nameAr??''} ${customer}`.toLowerCase().includes(q);
  const matchesStatus=status==='ALL'||(status==='ACTIVE'&&!['CANCELLED','COMPLETED'].includes(booking.status))||booking.status===status;
  return matchesQuery&&matchesStatus;
 }),[bookings,programs,customerNames,query,status]);
 function toggleTraveler(id:string){setForm(current=>({...current,travelerIds:current.travelerIds.includes(id)?current.travelerIds.filter(value=>value!==id):[...current.travelerIds,id]}));}
 async function create(e:FormEvent){e.preventDefault();await tourismOperationsApi.createBooking({code:form.code,programId:form.programId,customerId:form.customerId,travelerIds:form.travelerIds});setForm(blankBooking);await done('تم إنشاء الحجز كمسودة مرتبطة بالبرنامج والعميل والمسافرين.');}
 async function confirmBooking(e:FormEvent){e.preventDefault();if(!confirmId)return;await tourismOperationsApi.confirmBooking(confirmId,{commandKey:'tourism-confirm:'+confirmId+':'+confirm.invoiceNumber,category:confirm.category,costCenterId:confirm.costCenterId,currency:confirm.currency,grossAmount:confirm.grossAmount,discountAmount:confirm.discountAmount,postingDate:confirm.postingDate,dueDate:confirm.dueDate,invoiceNumber:confirm.invoiceNumber,inventories:[{allocationId:confirm.allocationId,contractId:confirm.contractId,resourceType:confirm.resourceType,resourceId:confirm.resourceId,serviceDate:confirm.serviceDate,quantity:confirm.quantity,...(confirm.periodEnd?{periodEnd:confirm.periodEnd}:{})}]});setConfirmId('');setConfirm(blankConfirm);await done('تم تأكيد الحجز عبر مسار المخزون والتمويل المعتمد.');}
 async function cancel(b:TourismBooking){const date=today(),commandKey=b.pendingCommandKey??'tourism-cancel:'+b.id+':'+date;await tourismOperationsApi.cancelBooking(b.id,{commandKey,postingDate:date});await done(b.status==='CANCELLATION_REQUIRED'?'تمت إعادة فحص التسوية المالية ومحاولة إتمام الإلغاء.':'تم تنفيذ طلب الإلغاء وفق الموانع المالية المسجلة.');}
 return <>
  <DisclosureCard title="حجز سياحي جديد" description="العميل والمسافرون يُختارون من السجلات الرئيسية؛ لا تُدخل المعرّفات يدويًا."><form className="ui-filter-grid" onSubmit={create}>
   <FormField label="رقم الحجز" required><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></FormField>
   <FormField label="البرنامج" required><Select required value={form.programId} onChange={e=>setForm({...form,programId:e.target.value})}><option value="">اختر برنامجًا مفتوحًا</option>{programs.filter(p=>p.status==='OPEN').map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr}</option>)}</Select></FormField>
   <FormField label="العميل" required><Select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">اختر العميل</option>{customers.map(item=><option key={item.customer.id} value={item.customer.id}>{item.customer.number} — {item.party.displayName}</option>)}</Select></FormField>
   <FormField label="المسافرون" hint="اختر مسافرًا واحدًا على الأقل من Traveler Management"><div className="ui-page-stack">{travelers.map(traveler=><label key={traveler.id}><input type="checkbox" checked={form.travelerIds.includes(traveler.id)} onChange={()=>toggleTraveler(traveler.id)}/> {traveler.fullName}{traveler.customerId&&traveler.customerId===form.customerId?' — مرتبط بالعميل':''}</label>)}</div></FormField>
   {selectorError?<ErrorState message={selectorError}/>:null}
   <Button type="submit" disabled={!form.customerId||form.travelerIds.length===0}>إنشاء الحجز</Button>
  </form></DisclosureCard>
  <Card title="بحث وتصفية الحجوزات"><div className="ui-filter-grid"><FormField label="بحث"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم الحجز أو العميل أو البرنامج"/></FormField><FormField label="الحالة"><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">قيد العمل</option><option value="ALL">الكل</option><option value="DRAFT">مسودة</option><option value="CONFIRMING">جارٍ التأكيد</option><option value="CONFIRMED">مؤكد</option><option value="CANCELLING">جارٍ الإلغاء</option><option value="CANCELLATION_REQUIRED">يحتاج تسوية</option><option value="CANCELLED">ملغي</option><option value="COMPLETED">مكتمل</option></Select></FormField></div></Card>
  {filtered.length?<DataGrid columns={['الحجز','البرنامج','العميل','المسافرون','الحالة','الإجراء']}>{filtered.map(b=>{
   const canConfirm=b.status==='DRAFT'||b.status==='CONFIRMING';
   const canCancel=b.status==='CONFIRMED'||b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED';
   const tone=b.status==='CONFIRMED'?'success':(b.status==='CANCELLING'||b.status==='CANCELLATION_REQUIRED')?'warning':b.status==='CANCELLED'?'error':'neutral';
   return <tr key={b.id}><td>{b.code}</td><td>{programs.find(p=>p.id===b.programId)?.nameAr??b.programId}</td><td>{customerNames.get(b.customerId)??b.customerId}</td><td>{b.travelerIds.map(id=>travelerNames.get(id)??id).join('، ')}</td><td><Badge tone={tone}>{bookingStatus[b.status]??b.status}</Badge></td><td><ActionBar>{canConfirm?<Button onClick={()=>setConfirmId(b.id)}>تأكيد مالي</Button>:null}{canCancel?<Button variant={b.status==='CANCELLATION_REQUIRED'?'secondary':'danger'} onClick={()=>void cancel(b)}>{b.status==='CANCELLATION_REQUIRED'?'إعادة فحص الإلغاء':'طلب إلغاء'}</Button>:null}{b.status==='CONFIRMED'?<Button variant="secondary" onClick={()=>void tourismOperationsApi.completeBooking(b.id).then(()=>done('تم إكمال الحجز.'))}>إكمال</Button>:null}</ActionBar></td></tr>;
  })}</DataGrid>:<EmptyState title="لا توجد حجوزات ضمن الفلتر"/>}
  {confirmId?<Card title="تأكيد الحجز ماليًا"><form className="ui-filter-grid" onSubmit={confirmBooking}><FormField label="التصنيف"><Select value={confirm.category} onChange={e=>setConfirm({...confirm,category:e.target.value as TourismBookingConfirm['category']})}><option value="HOTEL">فندق</option><option value="FLIGHT">طيران</option><option value="TRANSPORT">نقل</option><option value="VISA">تأشيرة</option><option value="OTHER">أخرى</option></Select></FormField><FormField label="مركز التكلفة" required><Input required value={confirm.costCenterId} onChange={e=>setConfirm({...confirm,costCenterId:e.target.value})}/></FormField><FormField label="العملة" required><Input required value={confirm.currency} onChange={e=>setConfirm({...confirm,currency:e.target.value.toUpperCase()})}/></FormField><FormField label="الإجمالي" required><Input required inputMode="decimal" value={confirm.grossAmount} onChange={e=>setConfirm({...confirm,grossAmount:e.target.value})}/></FormField><FormField label="الخصم"><Input inputMode="decimal" value={confirm.discountAmount} onChange={e=>setConfirm({...confirm,discountAmount:e.target.value})}/></FormField><FormField label="تاريخ الترحيل" required><Input required type="date" value={confirm.postingDate} onChange={e=>setConfirm({...confirm,postingDate:e.target.value})}/></FormField><FormField label="الاستحقاق" required><Input required type="date" value={confirm.dueDate} onChange={e=>setConfirm({...confirm,dueDate:e.target.value})}/></FormField><FormField label="رقم الفاتورة" required><Input required value={confirm.invoiceNumber} onChange={e=>setConfirm({...confirm,invoiceNumber:e.target.value})}/></FormField><FormField label="Allocation ID" required><Input required value={confirm.allocationId} onChange={e=>setConfirm({...confirm,allocationId:e.target.value})}/></FormField><FormField label="Contract ID" required><Input required value={confirm.contractId} onChange={e=>setConfirm({...confirm,contractId:e.target.value})}/></FormField><FormField label="نوع المورد" required><Input required value={confirm.resourceType} onChange={e=>setConfirm({...confirm,resourceType:e.target.value})}/></FormField><FormField label="Resource ID" required><Input required value={confirm.resourceId} onChange={e=>setConfirm({...confirm,resourceId:e.target.value})}/></FormField><FormField label="تاريخ الخدمة" required><Input required type="date" value={confirm.serviceDate} onChange={e=>setConfirm({...confirm,serviceDate:e.target.value})}/></FormField><FormField label="الكمية" required><Input required inputMode="decimal" value={confirm.quantity} onChange={e=>setConfirm({...confirm,quantity:e.target.value})}/></FormField><ActionBar><Button type="submit">تأكيد</Button><Button type="button" variant="secondary" onClick={()=>setConfirmId('')}>إلغاء</Button></ActionBar></form></Card>:null}
 </>;
}

function Itinerary({programs,done}:{programs:TourismProgram[];done:(message:string)=>void}){
 const[programId,setProgramId]=useState(''),[days,setDays]=useState<ItineraryDay[]>([]),[form,setForm]=useState(blankItinerary),[error,setError]=useState(''),[editing,setEditing]=useState<ItineraryDay|null>(null),[editForm,setEditForm]=useState(blankItinerary);
 async function load(id:string){setProgramId(id);setError('');if(!id){setDays([]);return}try{setDays(await tourismOperationsApi.itinerary(id));}catch(value){setError(value instanceof Error?value.message:'تعذر تحميل البرنامج اليومي.');}}
 async function submit(e:FormEvent){e.preventDefault();if(!programId)return;try{await tourismOperationsApi.createItinerary(programId,{dayNumber:Number(form.dayNumber),serviceDate:form.serviceDate,title:form.title,description:form.description,location:form.location});setForm(blankItinerary);await load(programId);done('تمت إضافة اليوم إلى البرنامج.');}catch(value){setError(value instanceof Error?value.message:'تعذر الحفظ.');}}
 function beginEdit(day:ItineraryDay){setEditing(day);setEditForm({dayNumber:String(day.dayNumber),serviceDate:day.serviceDate,title:day.title,description:day.description??'',location:day.location??''});}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!programId||!editing)return;try{await tourismOperationsApi.updateItinerary(programId,editing.id,{dayNumber:Number(editForm.dayNumber),serviceDate:editForm.serviceDate,title:editForm.title,description:editForm.description,location:editForm.location,expectedRevision:editing.revision});setEditing(null);await load(programId);done('تم تعديل يوم البرنامج.');}catch(value){setError(value instanceof Error?value.message:'تعذر تعديل اليوم.');}}
 const selected=programs.find(p=>p.id===programId);
 return <>
  <Card title="البرنامج اليومي"><FormField label="البرنامج"><Select value={programId} onChange={e=>void load(e.target.value)}><option value="">اختر البرنامج</option>{programs.map(p=><option key={p.id} value={p.id}>{p.code} — {p.nameAr}</option>)}</Select></FormField>{selected?.status==='PREPARING'?<form className="ui-filter-grid" onSubmit={submit}><FormField label="رقم اليوم"><Input required type="number" min="1" value={form.dayNumber} onChange={e=>setForm({...form,dayNumber:e.target.value})}/></FormField><FormField label="التاريخ"><Input required type="date" value={form.serviceDate} onChange={e=>setForm({...form,serviceDate:e.target.value})}/></FormField><FormField label="العنوان"><Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></FormField><FormField label="المكان"><Input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></FormField><FormField label="التفاصيل"><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></FormField><Button type="submit">إضافة اليوم</Button></form>:selected?<p>يصبح البرنامج اليومي للقراءة فقط بعد فتح البرنامج للبيع.</p>:null}</Card>
  {error?<ErrorState message={error}/>:programId&&days.length===0?<EmptyState title="لا يوجد برنامج يومي بعد"/>:<DataGrid columns={['اليوم','التاريخ','العنوان','المكان','إجراء']}>{days.map(d=><tr key={d.id}><td>{d.dayNumber}</td><td>{d.serviceDate}</td><td>{d.title}</td><td>{d.location??'—'}</td><td>{selected?.status==='PREPARING'?<Button variant="secondary" onClick={()=>beginEdit(d)}>تعديل</Button>:null}</td></tr>)}</DataGrid>}
  <Dialog open={Boolean(editing)} title="تعديل يوم البرنامج" onClose={()=>setEditing(null)}><form className="ui-filter-grid" onSubmit={saveEdit}><FormField label="رقم اليوم"><Input required type="number" min="1" value={editForm.dayNumber} onChange={e=>setEditForm({...editForm,dayNumber:e.target.value})}/></FormField><FormField label="التاريخ"><Input required type="date" value={editForm.serviceDate} onChange={e=>setEditForm({...editForm,serviceDate:e.target.value})}/></FormField><FormField label="العنوان"><Input required value={editForm.title} onChange={e=>setEditForm({...editForm,title:e.target.value})}/></FormField><FormField label="المكان"><Input value={editForm.location} onChange={e=>setEditForm({...editForm,location:e.target.value})}/></FormField><FormField label="التفاصيل"><Textarea value={editForm.description} onChange={e=>setEditForm({...editForm,description:e.target.value})}/></FormField><ActionBar><Button type="submit">حفظ</Button><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>إغلاق</Button></ActionBar></form></Dialog>
 </>;
}
