import assert from'node:assert/strict';
import test from'node:test';
import{companyId,decimalAmount,type CompanyId}from'@elhafez/contracts';
import type{CreateInvoiceInput,Invoice}from'@elhafez/billing-subledgers';
import{ProcurementFinanceApplicationService}from'./application/procurement-finance.application-service.js';
import{InMemoryProcurementRepository}from'./infrastructure/in-memory-procurement.repository.js';

const company=companyId('company-a');

class BillingHarness{
 readonly invoices=new Map<string,Invoice>();lastDraft?:CreateInvoiceInput;
 async createDraft(input:CreateInvoiceInput){this.lastDraft=input;const old=this.invoices.get(input.id);if(old)return old;const invoice={...input,status:'DRAFT',requestHash:'h',baseTotal:decimalAmount('0'),outstanding:decimalAmount('0'),createdAt:new Date().toISOString()}as Invoice;this.invoices.set(input.id,invoice);return invoice;}
 async postInvoice(_company:CompanyId,id:string){const invoice=this.invoices.get(id);if(!invoice)throw new Error('invoice not found');if(invoice.status==='POSTED')return invoice;const total=invoice.lines.reduce((sum,line)=>decimalAmount(String(Number(sum)+Number(line.amount))),decimalAmount('0'));const posted={...invoice,status:'POSTED' as const,baseTotal:total,outstanding:total,journalId:`j:${id}`};this.invoices.set(id,posted);return posted;}
 async getOpenPosition(_company:CompanyId,id:string){const invoice=this.invoices.get(id);if(!invoice)throw new Error('invoice not found');return{invoiceId:id,companyId:invoice.companyId,partyKind:'SUPPLIER' as const,partyId:invoice.partyId,invoiceType:invoice.type,currency:invoice.currency,documentTotal:decimalAmount('0'),outstanding:invoice.outstanding,baseTotal:invoice.baseTotal,controlAccountId:invoice.controlAccountId,status:invoice.status,postingDate:invoice.postingDate,deferred:false};}
}
class SupplierGuard{usable=true;calls:string[]=[];async assertSupplierReferenceUsableForProcurementForIntegration(_c:CompanyId,partyId:string){this.calls.push(partyId);if(!this.usable)throw new Error('supplier party is not approved and active for procurement');return{partyId};}}
function setup(){const repo=new InMemoryProcurementRepository(),billing=new BillingHarness(),supplier=new SupplierGuard(),service=new ProcurementFinanceApplicationService(repo,billing,supplier as never);return{repo,billing,supplier,service};}
async function draft(s:ReturnType<typeof setup>){return s.service.createPurchaseOrder({id:'po-1',companyId:company,branchId:'branch-a',supplierId:'supplier-party',origin:'MANUAL',orderDate:'2026-09-20',currency:'EGP',lines:[{id:'line-1',itemReference:'hotel',orderedQuantity:decimalAmount('10'),unitPrice:decimalAmount('100')}]});}
async function approved(s:ReturnType<typeof setup>){await s.service.setPolicy({companyId:company,commitmentTiming:'ON_PO_APPROVAL',version:1,effectiveFrom:'2026-09-20'});await draft(s);return s.service.approvePurchaseOrder(company,'po-1');}

test('new purchase orders require authoritative branch and approved supplier',async()=>{const s=setup();await assert.rejects(()=>s.service.createPurchaseOrder({id:'x',companyId:company,branchId:undefined as never,supplierId:'supplier-party',origin:'MANUAL',orderDate:'2026-09-20',currency:'EGP',lines:[{id:'l',itemReference:'x',orderedQuantity:decimalAmount('1'),unitPrice:decimalAmount('1')}]}),/branchId/);s.supplier.usable=false;await assert.rejects(()=>draft(s),/not approved/);assert.deepEqual(s.supplier.calls,['supplier-party']);});

test('draft commercial edit is command-idempotent and blocked after approval',async()=>{const s=setup();await draft(s);const command={companyId:company,branchId:'branch-a',purchaseOrderId:'po-1',commandId:'edit-1',supplierId:'supplier-party',orderDate:'2026-09-21',currency:'USD',expectedDate:'2026-09-25',notes:'changed',lines:[{id:'line-2',itemReference:'transport',orderedQuantity:decimalAmount('2'),unitPrice:decimalAmount('50')}]};const first=await s.service.updateDraftPurchaseOrder(command),replay=await s.service.updateDraftPurchaseOrder(command);assert.equal(first.currency,'USD');assert.equal(replay.lines[0]?.id,'line-2');await s.service.setPolicy({companyId:company,commitmentTiming:'ON_PO_APPROVAL',version:1,effectiveFrom:'2026-09-20'});await s.service.approvePurchaseOrder(company,'po-1');await assert.rejects(()=>s.service.updateDraftPurchaseOrder({...command,commandId:'edit-2'}),/only draft/);});

test('receipt correction cannot reduce below already invoiced quantity',async()=>{const s=setup();await approved(s);await s.service.receivePurchaseOrder({companyId:company,purchaseOrderId:'po-1',lineId:'line-1',quantity:decimalAmount('6'),commandId:'r1'});await s.service.convertToSupplierInvoice({id:'conv-1',companyId:company,purchaseOrderId:'po-1',lineId:'line-1',quantity:decimalAmount('4'),billing:{invoiceId:'inv-1',number:'INV-1',externalInvoiceNumber:'EXT-1',postingDate:'2026-09-20',currency:'EGP',controlAccountId:'ap',accountId:'expense',amount:decimalAmount('400')}});await assert.rejects(()=>s.service.adjustReceivedPurchaseOrder({companyId:company,purchaseOrderId:'po-1',lineId:'line-1',newReceivedQuantity:decimalAmount('3'),commandId:'adj-1',reason:'correction'}),/below invoiced/);const corrected=await s.service.adjustReceivedPurchaseOrder({companyId:company,purchaseOrderId:'po-1',lineId:'line-1',newReceivedQuantity:decimalAmount('5'),commandId:'adj-2',reason:'confirmed'});assert.equal(corrected.lines[0]?.receivedQuantity,'5');});

test('PO supplier invoice and direct purchase preserve branch into Billing',async()=>{const s=setup();await approved(s);await s.service.receivePurchaseOrder({companyId:company,purchaseOrderId:'po-1',lineId:'line-1',quantity:decimalAmount('1'),commandId:'r1'});await s.service.convertToSupplierInvoice({id:'conv',companyId:company,purchaseOrderId:'po-1',lineId:'line-1',quantity:decimalAmount('1'),billing:{invoiceId:'po-inv',number:'PO-INV',externalInvoiceNumber:'PO-EXT',postingDate:'2026-09-20',currency:'EGP',controlAccountId:'ap',accountId:'expense',amount:decimalAmount('100')}});assert.equal(s.billing.lastDraft?.branchId,'branch-a');const direct=await s.service.createDirectPurchase({id:'direct-1',companyId:company,branchId:'branch-a',supplierId:'supplier-party',invoiceId:'direct-inv',number:'D-1',externalInvoiceNumber:'D-EXT',postingDate:'2026-09-20',currency:'EGP',controlAccountId:'ap',lines:[{id:'d1',accountId:'expense',amount:decimalAmount('50')}]});assert.equal(direct.status,'POSTED');assert.equal(s.billing.lastDraft?.branchId,'branch-a');assert.equal(s.billing.lastDraft?.sourceType,'PROCUREMENT_DIRECT');});

test('manual PO numbering is owner-generated per branch and year',async()=>{const s=setup();const first=await draft(s);assert.equal(first.number,'PO-2026-000001');const second=await s.service.createPurchaseOrder({id:'po-2',companyId:company,branchId:'branch-a',supplierId:'supplier-party',origin:'MANUAL',orderDate:'2026-09-21',currency:'EGP',lines:[{id:'line-2',itemReference:'visa',orderedQuantity:decimalAmount('1'),unitPrice:decimalAmount('20')}]});assert.equal(second.number,'PO-2026-000002');const otherBranch=await s.service.createPurchaseOrder({id:'po-3',companyId:company,branchId:'branch-b',supplierId:'supplier-party',origin:'MANUAL',orderDate:'2026-09-21',currency:'EGP',lines:[{id:'line-3',itemReference:'transport',orderedQuantity:decimalAmount('1'),unitPrice:decimalAmount('20')}]});assert.equal(otherBranch.number,'PO-2026-000001');const replay=await draft(s);assert.equal(replay.number,first.number);await assert.rejects(()=>s.service.createPurchaseOrder({id:'manual-number',companyId:company,branchId:'branch-a',supplierId:'supplier-party',number:'MANUAL-OVERRIDE',origin:'MANUAL',orderDate:'2026-09-21',currency:'EGP',lines:[{id:'line-x',itemReference:'x',orderedQuantity:decimalAmount('1'),unitPrice:decimalAmount('1')}]}),/owner-generated/);});
