import assert from'node:assert/strict';import test from'node:test';import{executionContext,type ExecutionContext}from'@elhafez/contracts';import{HajjUmrahRoomingApplicationService}from'./application/hajj-umrah-rooming.application-service.js';import type{RoomingRepository}from'./application/rooming.repository.js';import type{RoomingAccess}from'./application/rooming.ports.js';import type{RoomAssignment,RoomingHistory}from'./domain/rooming.js';
class R implements RoomingRepository{rows=new Map<string,RoomAssignment>();logs:RoomingHistory[]=[];async create(v:RoomAssignment,h:RoomingHistory){this.rows.set(v.id,v);this.logs.push(h);return v}async save(v:RoomAssignment,h:RoomingHistory){this.rows.set(v.id,v);this.logs.push(h);return v}async swap(a:RoomAssignment,ha:RoomingHistory,b:RoomAssignment,hb:RoomingHistory){this.rows.set(a.id,a);this.rows.set(b.id,b);this.logs.push(ha,hb)}async get(c:string,b:string,id:string){const v=this.rows.get(id);return v?.companyId===c&&v.branchId===b?v:null}async list(c:string,b:string,p?:string){return[...this.rows.values()].filter(v=>v.companyId===c&&v.branchId===b&&(!p||v.programId===p))}async history(c:string,b:string,id:string){return this.logs.filter(v=>v.companyId===c&&v.branchId===b&&v.assignmentId===id)}async overlappingTraveler(c:string,b:string,t:string,s:string,e:string,x?:string){return[...this.rows.values()].find(v=>v.companyId===c&&v.branchId===b&&v.travelerId===t&&v.status==='ASSIGNED'&&v.id!==x&&v.startDate<=e&&v.endDate>=s)??null}async activeAllocationCount(c:string,b:string,a:string,s:string,e:string,x?:string){return[...this.rows.values()].filter(v=>v.companyId===c&&v.branchId===b&&v.allocationId===a&&v.status==='ASSIGNED'&&v.id!==x&&v.startDate<=e&&v.endDate>=s).length}}
class A implements RoomingAccess{async requireBranch(c:ExecutionContext){if(c.companyId!=='c1'||c.branchId!=='b1')throw Error('branch denied')}async requirePermission(){}async audit(){}}
const c=executionContext('c1','b1','u1');function f(q='2'){const repo=new R();let n=0;const service=new HajjUmrahRoomingApplicationService(repo,new A(),{async requireTraveler(_c,b,t){return{id:b,companyId:'c1' as any,branchId:'b1',code:'B',programId:'p1',customerId:'c',customerPartyId:'party',travelerIds:[t],status:'CONFIRMED',financialState:'CONFIRMED',allocationIds:['a1'],createdAt:'',updatedAt:''}}},{async require(){return{id:'p1',companyId:'c1' as any,branchId:'b1',code:'P',type:'UMRAH',seasonId:'s',arabicName:'P',snapshot:{departureDate:'2027-01-01',returnDate:'2027-01-20',salesStart:'',salesClose:'',capacity:'2',currency:'SAR',prices:{},requirements:[],components:[]},temporaryHoldMinutes:15,status:'BOOKABLE',bookingOpen:true,currentVersion:1,currentVersionId:'v',createdAt:'',updatedAt:''}}},{async requireActive(_c,id){return{id:id as any,companyId:'c1' as any,fullName:id,dateOfBirth:null,gender:null,nationality:null,partyId:null,customerId:null,status:'ACTIVE',createdAt:'',updatedAt:''}}},{async allocation(_c,id){return{id,companyId:'c1' as any,contractId:'hc',contractVersionId:'v',resourceType:'HOTEL',resourceId:'h1',program:{sourceType:'HAJJ_UMRAH_PROGRAM',sourceId:'p1'},serviceDate:'2027-01-01T00:00:00.000Z',periodEnd:'2027-01-20T00:00:00.000Z',quantity:q as any,status:'CONFIRMED',createdAt:''}}},()=>new Date('2026-09-22T00:00:00Z'),()=>`id-${++n}`);return{repo,service}}
const input={bookingId:'b1',travelerId:'t1',allocationId:'a1',roomKey:'R1',startDate:'2027-01-02',endDate:'2027-01-10'};
test('valid assignment is persisted from canonical hotel evidence',async()=>{const x=f();const a=await x.service.assign(c,input);assert.equal(a.status,'ASSIGNED');assert.equal((await x.service.list(c)).length,1)});
test('overlapping assignment for same traveler is rejected',async()=>{const x=f();await x.service.assign(c,input);await assert.rejects(()=>x.service.assign(c,{...input,roomKey:'R2'}),/overlapping/)});
test('allocation capacity is enforced',async()=>{const x=f('1');await x.service.assign(c,input);await assert.rejects(()=>x.service.assign(c,{...input,bookingId:'b2',travelerId:'t2',roomKey:'R2'}),/capacity/)});
test('reassignment and unassignment retain history',async()=>{const x=f();const a=await x.service.assign(c,input);await x.service.reassign(c,a.id,{allocationId:'a1',roomKey:'R2',startDate:'2027-01-03',endDate:'2027-01-09'});await x.service.unassign(c,a.id);assert.deepEqual((await x.service.historyFor(c,a.id)).map(h=>h.action),['ASSIGNED','REASSIGNED','UNASSIGNED'])});
test('company and branch isolation are mandatory',async()=>{const x=f();const a=await x.service.assign(c,input);await assert.rejects(()=>x.service.historyFor(executionContext('c1','other','u1'),a.id),/branch denied/)});
