import{Prisma,type TbkBooking,type PrismaClient}from'@prisma/client';
import{companyId}from'@elhafez/contracts';
import type{BookingFinancialEvidence,TourismBooking,TourismBookingAmendment,TourismBookingExtension,TourismBookingHistory,TourismBookingPaymentPlanItem,TourismBookingStatus}from'../domain/booking.js';
import type{TourismBookingRepository}from'../application/booking.repository.js';

function status(value:string):TourismBookingStatus{switch(value){case'DRAFT':case'CONFIRMING':case'CONFIRMED':case'CANCELLING':case'CANCELLATION_REQUIRED':case'CANCELLED':case'COMPLETED':return value;default:throw new Error('invalid persisted tourism booking status');}}
function travelerIds(value:Prisma.JsonValue):string[]{if(!Array.isArray(value))throw new Error('invalid persisted tourism booking travelers');const result:string[]=[];for(const item of value){if(typeof item!=='string'||!item.trim())throw new Error('invalid persisted tourism booking travelers');result.push(item);}return result;}
function financialEvidence(value:Prisma.JsonValue|null):BookingFinancialEvidence|undefined{
 if(value===null)return undefined;if(typeof value!=='object'||Array.isArray(value))throw new Error('invalid persisted tourism booking financial evidence');
 const workflowId=value.workflowId,invoiceId=value.invoiceId,allocationIds=value.allocationIds,commissionClaimId=value.commissionClaimId;
 if(typeof workflowId!=='string'||!workflowId||!Array.isArray(allocationIds)||!allocationIds.every(item=>typeof item==='string'))throw new Error('invalid persisted tourism booking financial evidence');
 if(invoiceId!==undefined&&invoiceId!==null&&typeof invoiceId!=='string')throw new Error('invalid persisted tourism booking invoice reference');
 if(commissionClaimId!==undefined&&commissionClaimId!==null&&typeof commissionClaimId!=='string')throw new Error('invalid persisted tourism booking commission reference');
 return{workflowId,...(typeof invoiceId==='string'?{invoiceId}:{}),allocationIds:[...allocationIds],...(typeof commissionClaimId==='string'?{commissionClaimId}:{})};
}
function evidenceJson(value:BookingFinancialEvidence|undefined):Prisma.InputJsonValue|typeof Prisma.JsonNull{
 return value?{workflowId:value.workflowId,...(value.invoiceId?{invoiceId:value.invoiceId}:{}),allocationIds:[...value.allocationIds],...(value.commissionClaimId?{commissionClaimId:value.commissionClaimId}:{})}:Prisma.JsonNull;
}
function map(x:TbkBooking):TourismBooking{const evidence=financialEvidence(x.financialEvidence);return{id:x.id,companyId:companyId(x.companyId),branchId:x.branchId,code:x.code,programId:x.programId,customerId:x.customerId,customerPartyId:x.customerPartyId,travelerIds:travelerIds(x.travelerIds),status:status(x.status),...(x.pendingCommandKey?{pendingCommandKey:x.pendingCommandKey}:{}),...(evidence?{financialEvidence:evidence}:{}),revision:x.revision,createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString()};}
export class PrismaTourismBookingRepository implements TourismBookingRepository{
 constructor(private readonly db:PrismaClient){}
 private data(v:TourismBooking){return{companyId:v.companyId,branchId:v.branchId,code:v.code,programId:v.programId,customerId:v.customerId,customerPartyId:v.customerPartyId,travelerIds:[...v.travelerIds],status:v.status,pendingCommandKey:v.pendingCommandKey??null,financialEvidence:evidenceJson(v.financialEvidence),revision:v.revision,createdAt:new Date(v.createdAt),updatedAt:new Date(v.updatedAt)}}
 private h(v:TourismBookingHistory){return{id:v.id,companyId:v.companyId,branchId:v.branchId,bookingId:v.bookingId,action:v.action,actorId:v.actorId,occurredAt:new Date(v.occurredAt)}}
 async create(v:TourismBooking,h:TourismBookingHistory){await this.db.$transaction([this.db.tbkBooking.create({data:{id:v.id,...this.data(v)}}),this.db.tbkBookingHistory.create({data:this.h(h)})]);return v}
 async save(v:TourismBooking,h:TourismBookingHistory){await this.db.$transaction(async tx=>{const updated=await tx.tbkBooking.updateMany({where:{id:v.id,companyId:v.companyId,branchId:v.branchId,revision:v.revision-1},data:this.data(v)});if(updated.count!==1)throw new Error('booking revision changed');await tx.tbkBookingHistory.create({data:this.h(h)});});return v}
 async get(c:string,b:string,id:string){const x=await this.db.tbkBooking.findFirst({where:{id,companyId:c,branchId:b}});return x?map(x):null}
 async list(c:string,b:string,s?:TourismBookingStatus){return(await this.db.tbkBooking.findMany({where:{companyId:c,branchId:b,...(s?{status:s}:{})},orderBy:{createdAt:'desc'}})).map(map)}
 async listForProgram(c:string,b:string,p:string){return(await this.db.tbkBooking.findMany({where:{companyId:c,branchId:b,programId:p},orderBy:{createdAt:'desc'}})).map(map)}
 async extension(c:string,b:string,id:string){const x=await this.db.tbkBookingExtension.findUnique({where:{companyId_branchId_bookingId:{companyId:c,branchId:b,bookingId:id}}});return x?{companyId:companyId(x.companyId),branchId:x.branchId,bookingId:x.bookingId,salesState:x.salesState as TourismBookingExtension['salesState'],priceTierCode:x.priceTierCode,specialRequests:x.specialRequests,voucherNumber:x.voucherNumber,travelPackIssuedAt:x.travelPackIssuedAt?.toISOString()??null,updatedAt:x.updatedAt.toISOString()}:null}
 async saveExtension(v:TourismBookingExtension){const x=await this.db.tbkBookingExtension.upsert({where:{companyId_branchId_bookingId:{companyId:v.companyId,branchId:v.branchId,bookingId:v.bookingId}},create:{companyId:v.companyId,branchId:v.branchId,bookingId:v.bookingId,salesState:v.salesState,priceTierCode:v.priceTierCode,specialRequests:v.specialRequests,voucherNumber:v.voucherNumber,travelPackIssuedAt:v.travelPackIssuedAt?new Date(v.travelPackIssuedAt):null,updatedAt:new Date(v.updatedAt)},update:{salesState:v.salesState,priceTierCode:v.priceTierCode,specialRequests:v.specialRequests,voucherNumber:v.voucherNumber,travelPackIssuedAt:v.travelPackIssuedAt?new Date(v.travelPackIssuedAt):null,updatedAt:new Date(v.updatedAt)}});return{...v,updatedAt:x.updatedAt.toISOString()}}
 async addAmendment(v:TourismBookingAmendment){await this.db.tbkBookingAmendment.create({data:{...v,occurredAt:new Date(v.occurredAt)}});return v}
 async amendments(c:string,b:string,id:string){return(await this.db.tbkBookingAmendment.findMany({where:{companyId:c,branchId:b,bookingId:id},orderBy:{occurredAt:'asc'}})).map(x=>({...x,companyId:companyId(x.companyId),kind:x.kind as TourismBookingAmendment['kind'],financeReference:x.financeReference,occurredAt:x.occurredAt.toISOString()}))}
 async savePaymentPlan(items:readonly TourismBookingPaymentPlanItem[]){if(!items.length)return[];const first=items[0]!;await this.db.$transaction(async tx=>{await tx.tbkPaymentPlanItem.deleteMany({where:{companyId:first.companyId,branchId:first.branchId,bookingId:first.bookingId}});await tx.tbkPaymentPlanItem.createMany({data:items.map(x=>({id:x.id,companyId:x.companyId,branchId:x.branchId,bookingId:x.bookingId,dueDate:new Date(x.dueDate),amount:x.amount,status:x.status,evidenceReference:x.evidenceReference,updatedAt:new Date(x.updatedAt)}))})});return[...items]}
 async paymentPlan(c:string,b:string,id:string){return(await this.db.tbkPaymentPlanItem.findMany({where:{companyId:c,branchId:b,bookingId:id},orderBy:{dueDate:'asc'}})).map(x=>({id:x.id,companyId:companyId(x.companyId),branchId:x.branchId,bookingId:x.bookingId,dueDate:x.dueDate.toISOString().slice(0,10),amount:String(x.amount),status:x.status as TourismBookingPaymentPlanItem['status'],evidenceReference:x.evidenceReference,updatedAt:x.updatedAt.toISOString()}))}
}
