import test from 'node:test';
import assert from 'node:assert/strict';
import { branchId, companyId, currencyCode, decimalAmount, sourceReference } from '@elhafez/contracts';
import { FinancialReportingApplicationService } from './application/financial-reporting.application-service.js';
import type { ReportingEvidence } from './domain/reporting.js';
import { InMemoryReportingProjectionRepository } from './infrastructure/in-memory-reporting-projection.repository.js';

const c1 = companyId('company-1'); const c2 = companyId('company-2'); const b1 = branchId('branch-1'); const b2 = branchId('branch-2');
const ref = (type: string, id: string) => sourceReference(type, id);
function fact(overrides: Partial<ReportingEvidence> = {}): ReportingEvidence { return { evidenceId: 'e-1', companyId: c1, branchId: b1, occurredAt: '2026-09-01T00:00:00.000Z', postingDate: '2026-09-01', currency: currencyCode('USD'), kind: 'GL_LINE', source: ref('JOURNAL', 'j-1'), authoritativeReference: ref('JOURNAL_LINE', 'jl-1'), amount: decimalAmount('0.1'), accountId: 'revenue', accountClass: 'REVENUE', ...overrides }; }
function fixture() { return new FinancialReportingApplicationService(new InMemoryReportingProjectionRepository()); }
const scope = { companyId: c1, branchIds: [b1] } as const;

test('duplicate immutable evidence is idempotent and a conflicting payload is rejected', async () => { const service = fixture(); assert.equal((await service.ingest(fact())).status, 'INGESTED'); assert.equal((await service.ingest(fact())).status, 'DUPLICATE'); await assert.rejects(service.ingest(fact({ amount: decimalAmount('0.2') })), /conflicting immutable reporting evidence/); assert.equal((await service.trialBalance(scope)).rows[0]?.amount, '0.1'); });
test('trial balance, ledger and statements use exact decimals from posted GL evidence', async () => { const service = fixture(); await service.ingest(fact()); await service.ingest(fact({ evidenceId: 'e-2', source: ref('JOURNAL', 'j-2'), authoritativeReference: ref('JOURNAL_LINE', 'jl-2'), amount: decimalAmount('0.2') })); const trial = await service.trialBalance(scope); assert.equal(trial.rows[0]?.amount, '0.3'); assert.equal((await service.accountLedger(scope, 'revenue')).entries.length, 2); assert.equal((await service.incomeStatement(scope)).totals[0]?.amount, '0.3'); assert.equal((await service.balanceSheet(scope)).totals.length, 0); });
test('company and branch scopes are isolated and company-wide access must be explicit', async () => { const service = fixture(); await service.ingest(fact()); await service.ingest(fact({ evidenceId: 'e-b2', branchId: b2 })); await service.ingest(fact({ evidenceId: 'e-c2', companyId: c2 })); assert.equal((await service.trialBalance(scope)).metadata.evidenceIds.length, 1); assert.equal((await service.trialBalance({ companyId: c1, branchIds: [b2] })).metadata.evidenceIds.length, 1); assert.equal((await service.trialBalance({ companyId: c2, branchIds: [b1] })).metadata.evidenceIds.length, 1); assert.equal((await service.trialBalance({ companyId: c1, companyWide: true })).metadata.evidenceIds.length, 2); await assert.rejects(service.trialBalance({ companyId: c1 }), /explicit branch scope/); await assert.rejects(service.trialBalance({ companyId: c1, companyWide: true, branchIds: [b1] }), /choose explicit branch/); });
test('Billing-owned aging preserves open positions and advances without recalculation', async () => { const service = fixture(); await service.ingest(fact({ kind: 'BILLING_POSITION', accountId: undefined, accountClass: undefined, partyId: 'customer-1', positionKind: 'RECEIVABLE', dueDate: '2026-08-01', openAmount: decimalAmount('10.01'), amount: decimalAmount('999'), authoritativeReference: ref('BILLING_POSITION', 'ar-1') })); await service.ingest(fact({ evidenceId: 'advance', kind: 'BILLING_POSITION', accountId: undefined, accountClass: undefined, partyId: 'customer-1', positionKind: 'CUSTOMER_ADVANCE', openAmount: decimalAmount('2'), amount: decimalAmount('2'), authoritativeReference: ref('BILLING_ADVANCE', 'adv-1') })); const report = await service.aging(scope, 'CUSTOMER'); assert.deepEqual(report.positions.map((x) => x.openAmount), ['2', '10.01']); assert.deepEqual(report.positions.map((x) => x.authoritativeReference.sourceId).sort(), ['adv-1', 'ar-1']); });
test('Treasury activity retains voucher and owner allocation references without inventing allocation truth', async () => { const service = fixture(); await service.ingest(fact({ kind: 'TREASURY_ACTIVITY', accountId: undefined, accountClass: undefined, voucherId: 'voucher-1', amount: decimalAmount('25'), authoritativeReference: ref('TREASURY_VOUCHER', 'voucher-1'), allocationReferences: [ref('BILLING_ALLOCATION', 'allocation-1')] })); const report = await service.treasury(scope); assert.equal(report.activity[0]?.allocationReferences[0]?.sourceId, 'allocation-1'); assert.equal(report.activity[0]?.voucherId, 'voucher-1'); });
test('program accounting snapshot derives actual revenue, cost and profit only from accounting evidence', async () => { const service = fixture(); await service.ingest(fact({ kind: 'PROGRAM_ACCOUNTING', accountId: undefined, accountClass: undefined, evidenceId: 'program-revenue', programId: 'program-1', costCenterId: 'cc-1', programDimension: 'REVENUE', amount: decimalAmount('100.25'), operationalEstimate: decimalAmount('1000'), authoritativeReference: ref('JOURNAL_LINE', 'revenue-line') })); await service.ingest(fact({ kind: 'PROGRAM_ACCOUNTING', accountId: undefined, accountClass: undefined, evidenceId: 'program-cost', programId: 'program-1', costCenterId: 'cc-1', programDimension: 'COST', amount: decimalAmount('40.05'), operationalEstimate: decimalAmount('1'), authoritativeReference: ref('JOURNAL_LINE', 'cost-line') })); const result = await service.getProgramAccountingSnapshot(scope, 'program-1'); assert.deepEqual(result.byCurrency.map((x) => [x.revenue, x.cost, x.profit]), [['100.25', '40.05', '60.2']]); assert.equal('operationalEstimate' in result.byCurrency[0]!, false); });
test('currencies are never silently aggregated and tax facts require frozen owner evidence', async () => { const service = fixture(); await service.ingest(fact({ kind: 'TAX_FACT', accountId: undefined, accountClass: undefined, taxCode: 'VAT', taxSnapshotReference: ref('TAX_SNAPSHOT', 'vat-1'), amount: decimalAmount('1') })); await service.ingest(fact({ evidenceId: 'tax-egp', kind: 'TAX_FACT', accountId: undefined, accountClass: undefined, currency: currencyCode('EGP'), taxCode: 'VAT', taxSnapshotReference: ref('TAX_SNAPSHOT', 'vat-2'), amount: decimalAmount('50') })); assert.deepEqual((await service.tax(scope)).totals.map((x) => x.currency), ['EGP', 'USD']); await assert.rejects(service.ingest(fact({ evidenceId: 'bad-tax', kind: 'TAX_FACT', accountId: undefined, accountClass: undefined })), /frozen tax snapshot/); });
test('reversal changes current reports while preserving immutable reversal provenance', async () => { const service = fixture(); const original = fact({ amount: decimalAmount('7') }); const reversal = fact({ evidenceId: 'e-reversal', amount: decimalAmount('-7'), source: ref('JOURNAL', 'j-reversal'), authoritativeReference: ref('JOURNAL_LINE', 'jl-reversal'), reversesEvidenceId: original.evidenceId }); await service.ingest(original); await service.ingest(reversal); const report = await service.trialBalance(scope); assert.equal(report.rows[0]?.amount, '0'); assert.deepEqual(report.metadata.evidenceIds, ['e-1', 'e-reversal']); assert.deepEqual(report.rows[0]?.evidenceIds, ['e-1', 'e-reversal']); });
test('rebuild is deterministic, de-duplicates identical evidence, and rejects cross-company input', async () => { const service = fixture(); const values = [fact({ evidenceId: 'b', amount: decimalAmount('0.2') }), fact({ evidenceId: 'a' }), fact({ evidenceId: 'a' })]; await service.rebuild(c1, values); const first = await service.trialBalance(scope); await service.rebuild(c1, [...values].reverse()); assert.deepEqual(await service.trialBalance(scope), first); await assert.rejects(service.rebuild(c1, [fact({ companyId: c2 })]), /crosses company scope/); });
test('supplier reports expose immutable procurement evidence and structured export is deterministic', async () => { const service = fixture(); await service.ingest(fact({ kind: 'PROCUREMENT_FINANCIAL', accountId: undefined, accountClass: undefined, supplierId: 'supplier-1', authoritativeReference: ref('PURCHASE_ORDER', 'po-1'), amount: decimalAmount('5') })); const report = await service.supplier(scope); assert.equal(report.facts[0]?.authoritativeReference.sourceId, 'po-1'); assert.deepEqual(service.exportRows(report.metadata, ['supplier', 'amount'], [['supplier-1', '5']]), service.exportRows(report.metadata, ['supplier', 'amount'], [['supplier-1', '5']])); });
test('Reporting public service has no accounting command capability', () => { const service = fixture(); for (const forbidden of ['post', 'approve', 'allocate', 'repair', 'delete']) assert.equal(forbidden in service, false); });
