import{Prisma,type PrismaClient}from'@prisma/client';
import{ContractValidationError}from'@elhafez/contracts';
import type{CreateCustomFieldDefinitionRecord,CustomFieldsRepository,UpdateCustomFieldDefinitionRecord}from'../application/custom-fields.repository.js';
import type{CustomFieldDefinition,CustomFieldScalar,CustomFieldValue}from'../domain/custom-fields.js';

function scalar(value:Prisma.JsonValue):CustomFieldScalar{if(typeof value==='string'||typeof value==='number'||typeof value==='boolean')return value;throw new Error('invalid custom-field scalar persisted');}
export class PrismaCustomFieldsRepository implements CustomFieldsRepository{
 constructor(private readonly db:PrismaClient){}
 private definition(row:{id:string;companyId:string;entityType:string;key:string;label:string;fieldType:string;required:boolean;options:Prisma.JsonValue;active:boolean;createdAt:Date;updatedAt:Date}):CustomFieldDefinition{return{id:row.id,companyId:row.companyId,entityType:row.entityType,key:row.key,label:row.label,fieldType:row.fieldType as CustomFieldDefinition['fieldType'],required:row.required,options:Array.isArray(row.options)?row.options.filter((v):v is string=>typeof v==='string'):[],active:row.active,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
 private value(row:{id:string;companyId:string;definitionId:string;entityType:string;entityId:string;valueJson:Prisma.JsonValue;updatedBy:string;updatedAt:Date}):CustomFieldValue{return{id:row.id,companyId:row.companyId,definitionId:row.definitionId,entityType:row.entityType,entityId:row.entityId,value:scalar(row.valueJson),updatedBy:row.updatedBy,updatedAt:row.updatedAt.toISOString()};}
 async createDefinition(input:CreateCustomFieldDefinitionRecord){try{return this.definition(await this.db.cufFieldDefinition.create({data:{...input,options:[...input.options],createdAt:new Date(input.createdAt),updatedAt:new Date(input.updatedAt)}}));}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ContractValidationError('key','custom field key already exists for entity type');throw error;}}
 async updateDefinition(companyId:string,id:string,input:UpdateCustomFieldDefinitionRecord){const current=await this.db.cufFieldDefinition.findFirst({where:{companyId,id}});if(!current)throw new ContractValidationError('definitionId','custom field definition was not found');return this.definition(await this.db.cufFieldDefinition.update({where:{id},data:{label:input.label,required:input.required,options:[...input.options],active:input.active,updatedAt:new Date(input.updatedAt)}}));}
 async findDefinition(companyId:string,id:string){const row=await this.db.cufFieldDefinition.findFirst({where:{companyId,id}});return row?this.definition(row):undefined;}
 async listDefinitions(companyId:string,entityType?:string){return(await this.db.cufFieldDefinition.findMany({where:{companyId,...(entityType?{entityType}: {})},orderBy:[{entityType:'asc'},{label:'asc'}]})).map(row=>this.definition(row));}
 async hasValues(companyId:string,definitionId:string){return(await this.db.cufFieldValue.count({where:{companyId,definitionId}}))>0;}
 async upsertValue(input:{id:string;companyId:string;definitionId:string;entityType:string;entityId:string;value:CustomFieldScalar;updatedBy:string;updatedAt:string}){const row=await this.db.cufFieldValue.upsert({where:{companyId_definitionId_entityId:{companyId:input.companyId,definitionId:input.definitionId,entityId:input.entityId}},create:{id:input.id,companyId:input.companyId,definitionId:input.definitionId,entityType:input.entityType,entityId:input.entityId,valueJson:input.value,updatedBy:input.updatedBy,updatedAt:new Date(input.updatedAt)},update:{entityType:input.entityType,valueJson:input.value,updatedBy:input.updatedBy,updatedAt:new Date(input.updatedAt)}});return this.value(row);}
 async deleteValue(companyId:string,definitionId:string,entityId:string){await this.db.cufFieldValue.deleteMany({where:{companyId,definitionId,entityId}});}
 async listValues(companyId:string,entityType:string,entityId:string){return(await this.db.cufFieldValue.findMany({where:{companyId,entityType,entityId},orderBy:{updatedAt:'asc'}})).map(row=>this.value(row));}
}
