import{ContractValidationError,type BranchId,type CompanyId,type DecimalAmount}from'@elhafez/contracts';
export interface Employee{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly employeeNumber:string;readonly displayName:string;readonly status:'ACTIVE'|'SUSPENDED'|'TERMINATED';readonly hireDate:string;readonly terminationDate:string|null;readonly department:string|null;readonly costCenterId:string|null;readonly currency:string;readonly baseSalary:DecimalAmount;readonly netPayableAccountId:string;readonly createdAt:string;readonly updatedAt:string}
export interface AttendanceRecord{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly employeeId:string;readonly workDate:string;readonly status:'PRESENT'|'ABSENT'|'LEAVE'|'REMOTE';readonly workedMinutes:number;readonly overtimeMinutes:number;readonly note:string|null}
export interface LeaveRequest{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly employeeId:string;readonly type:string;readonly startDate:string;readonly endDate:string;readonly status:'PENDING'|'APPROVED'|'REJECTED'|'CANCELLED';readonly reason:string|null;readonly decidedBy:string|null;readonly decidedAt:string|null}
export interface PayComponent{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly employeeId:string;readonly code:string;readonly kind:'EARNING'|'DEDUCTION';readonly amount:DecimalAmount;readonly liabilityAccountId:string|null;readonly active:boolean}
export interface PayrollLineDetail{readonly code:string;readonly kind:'BASE'|'EARNING'|'DEDUCTION';readonly amount:DecimalAmount;readonly liabilityAccountId:string|null}
export interface PayrollLine{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly runId:string;readonly employeeId:string;readonly gross:DecimalAmount;readonly deductions:DecimalAmount;readonly net:DecimalAmount;readonly details:readonly PayrollLineDetail[]}
export interface PayrollRun{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly period:string;readonly postingDate:string;readonly currency:string;readonly status:'DRAFT'|'CALCULATED'|'APPROVED'|'ACCRUED'|'PAID'|'CANCELLED';readonly expenseAccountId:string;readonly netPayableAccountId:string;readonly totalGross:DecimalAmount;readonly totalDeductions:DecimalAmount;readonly totalNet:DecimalAmount;readonly accountingRunId:string|null;readonly createdAt:string;readonly updatedAt:string}
export const req=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x};export const day=(v:string,f:string)=>{const x=req(v,f);if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw new ContractValidationError(f,'must be YYYY-MM-DD');return x};export const money=(v:string,f:string):DecimalAmount=>{const x=v.trim();if(!/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(x))throw new ContractValidationError(f,'must be non-negative decimal');return x as DecimalAmount};export const scaled=(v:DecimalAmount)=>{const[w,f='']=String(v).split('.');return BigInt(w)*1000000n+BigInt(f.padEnd(6,'0'))};export const amount=(v:bigint):DecimalAmount=>{const w=v/1000000n,f=v%1000000n;return(w+(f?'.'+f.toString().padStart(6,'0').replace(/0+$/,''):'')).toString() as DecimalAmount};
