import { Prisma, type HubBooking, type HubBookingHistory, type PrismaClient } from '@prisma/client';
import { companyId } from '@elhafez/contracts';
import type { Booking, BookingHistory } from '../domain/booking.js';
import type { BookingRepository } from '../application/booking.repository.js';

const json=(v:unknown)=>v as Prisma.InputJsonValue;
const map=(x:HubBooking):Booking=>({id:x.id,companyId:companyId(x.companyId),branchId:x.branchId,code:x.code,programId:x.programId,customerId:x.customerId,customerPartyId:x.customerPartyId,...(x.agentId?{agentId:x.agentId}:{}),...(x.agentPartyId?{agentPartyId:x.agentPartyId}:{}),travelerIds:x.travelerIds as unknown as string[],status:x.status as Booking['status'],financialState:x.financialState as Booking['financialState'],allocationIds:x.allocationIds as unknown as string[],...(x.confirmationCommandKey?{confirmationCommandKey:x.confirmationCommandKey}:{}),...(x.confirmationPayloadHash?{confirmationPayloadHash:x.confirmationPayloadHash}:{}),...(x.financialEvidence!==null?{financialEvidence:x.financialEvidence}:{}),...(x.cancellationEvidence!==null?{cancellationEvidence:x.cancellationEvidence}:{}),...(x.sourceReference!==null?{sourceReference:x.sourceReference as unknown as NonNullable<Booking['sourceReference']>}:{}),createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString()});
const history=(x:HubBookingHistory):BookingHistory=>({id:x.id,companyId:companyId(x.companyId),branchId:x.branchId,bookingId:x.bookingId,action:x.action,...(x.fromStatus?{fromStatus:x.fromStatus as NonNullable<BookingHistory['fromStatus']>}:{}),...(x.toStatus?{toStatus:x.toStatus as NonNullable<BookingHistory['toStatus']>}:{}),...(x.reason?{reason:x.reason}:{}),...(x.evidence!==null?{evidence:x.evidence}:{}),actorId:x.actorId,occurredAt:x.occurredAt.toISOString()});

export class PrismaBookingRepository implements BookingRepository {
  constructor(private readonly db:PrismaClient){}
  private data(v:Booking){return{id:v.id,companyId:v.companyId,branchId:v.branchId,code:v.code,programId:v.programId,customerId:v.customerId,customerPartyId:v.customerPartyId,agentId:v.agentId??null,agentPartyId:v.agentPartyId??null,travelerIds:json(v.travelerIds),status:v.status,financialState:v.financialState,allocationIds:json(v.allocationIds),confirmationCommandKey:v.confirmationCommandKey??null,confirmationPayloadHash:v.confirmationPayloadHash??null,financialEvidence:v.financialEvidence===undefined?Prisma.JsonNull:json(v.financialEvidence),cancellationEvidence:v.cancellationEvidence===undefined?Prisma.JsonNull:json(v.cancellationEvidence),sourceReference:v.sourceReference?json(v.sourceReference):Prisma.JsonNull,createdAt:new Date(v.createdAt),updatedAt:new Date(v.updatedAt)};}
  private hd(h:BookingHistory){return{id:h.id,companyId:h.companyId,branchId:h.branchId,bookingId:h.bookingId,action:h.action,fromStatus:h.fromStatus??null,toStatus:h.toStatus??null,reason:h.reason??null,evidence:h.evidence===undefined?Prisma.JsonNull:json(h.evidence),actorId:h.actorId,occurredAt:new Date(h.occurredAt)};}
  async create(v:Booking,h:BookingHistory){await this.db.$transaction([this.db.hubBooking.create({data:this.data(v)}),this.db.hubBookingHistory.create({data:this.hd(h)})]);return v;}
  async save(v:Booking,h:BookingHistory){await this.db.$transaction([this.db.hubBooking.update({where:{id_companyId_branchId:{id:v.id,companyId:v.companyId,branchId:v.branchId}},data:this.data(v)}),this.db.hubBookingHistory.create({data:this.hd(h)})]);return v;}
  async get(companyId:string,branchId:string,id:string){const x=await this.db.hubBooking.findUnique({where:{id_companyId_branchId:{id,companyId,branchId}}});return x?map(x):null;}
  async list(companyId:string,branchId:string){return (await this.db.hubBooking.findMany({where:{companyId,branchId},orderBy:{createdAt:'desc'}})).map(map);}
  async history(companyId:string,branchId:string,bookingId:string){return (await this.db.hubBookingHistory.findMany({where:{companyId,branchId,bookingId},orderBy:{occurredAt:'asc'}})).map(history);}
}
