import {createHash,createHmac,randomBytes,randomUUID,scrypt as nodeScrypt,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import type {BootstrapTokenVerifier,MfaSecretProtector,OwnerRecoveryTokenVerifier} from './saas.security.js';
import type {SaasRepository} from './saas.repository.js';
import {SaasError,type OwnerTenantProjection,type SaasControlEvent,type SaasOwnerAccount,type SaasOwnerSession,type SaasPayment,type SaasPlan,type SaasSubscription,type SaasSubscriptionEvent,type SaasTenant,type TenantAccessProjection} from '../domain/saas.types.js';

const scrypt=async(password:string,salt:string):Promise<Buffer>=>(await promisify(nodeScrypt)(password,salt,64)) as Buffer;
const hash=(value:string)=>createHash('sha256').update(value).digest('base64url');
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const id=()=>randomUUID();
const required=(value:string,name:string)=>{const v=value.trim();if(!v)throw new SaasError('VALIDATION_ERROR',name+' is required');return v;};
const validEmail=(value:string)=>{const v=required(value,'email').toLowerCase();if(!/^\S+@\S+\.\S+$/.test(v))throw new SaasError('VALIDATION_ERROR','email is invalid');return v;};
const validCurrency=(value:string)=>{const v=required(value,'currency').toUpperCase();if(!/^[A-Z]{3}$/.test(v))throw new SaasError('VALIDATION_ERROR','currency must be a 3-letter code');return v;};
const validMinor=(value:number,name:string)=>{if(!Number.isSafeInteger(value)||value<0)throw new SaasError('VALIDATION_ERROR',name+' must be a non-negative safe integer');return value;};
const safeEqual=(a:string,b:string)=>{const left=Buffer.from(a),right=Buffer.from(b);return left.length===right.length&&timingSafeEqual(left,right);};
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function b32e(input:Buffer){let bits=0,value=0,out='';for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits>0)out+=alphabet[(value<<(5-bits))&31];return out;}
function b32d(input:string){let bits=0,value=0;const bytes:number[]=[];for(const char of input.toUpperCase().replace(/=+$/,'')){const index=alphabet.indexOf(char);if(index<0)throw new SaasError('SECURITY_CONFIGURATION','invalid MFA secret');value=(value<<5)|index;bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(bytes);}
function totp(secret:string,at:Date){const counter=Math.floor(at.getTime()/30_000),buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',b32d(secret)).update(buf).digest(),offset=digest[digest.length-1]!&15;const binary=((digest[offset]!&127)<<24)|(digest[offset+1]!<<16)|(digest[offset+2]!<<8)|digest[offset+3]!;return String(binary%1_000_000).padStart(6,'0');}
function validTotp(secret:string,value:string,now:Date){if(!/^\d{6}$/.test(value))return false;for(const shift of[-30_000,0,30_000])if(safeEqual(totp(secret,new Date(now.getTime()+shift)),value))return true;return false;}
function addMonths(date:Date,months:number){const first=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+months,1,date.getUTCHours(),date.getUTCMinutes(),date.getUTCSeconds(),date.getUTCMilliseconds())),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();first.setUTCDate(Math.min(date.getUTCDate(),last));return first;}
function entitlements(values:readonly string[]){const out=[...new Set(values.map(v=>v.trim().toUpperCase()).filter(Boolean))];if(!out.length)throw new SaasError('VALIDATION_ERROR','at least one entitlement is required');return Object.freeze(out);}

export class SaasControlPlaneApplicationService{
 constructor(private readonly repo:SaasRepository,private readonly protector:MfaSecretProtector,private readonly bootstrap:BootstrapTokenVerifier,private readonly recovery:OwnerRecoveryTokenVerifier,private readonly now:()=>Date=()=>new Date()){}
 private control(ownerId:string|null,action:string,targetType:string,targetId:string|null,companyId:string|null,metadata:Record<string,unknown>={}):SaasControlEvent{return{id:id(),ownerId,action,targetType,targetId,companyId,metadata,occurredAt:this.now()};}
 private async passwordHash(password:string){if(password.length<16)throw new SaasError('VALIDATION_ERROR','owner password must have at least 16 characters');const salt=randomBytes(16).toString('base64url');return 'v1:'+salt+':'+(await scrypt(password,salt)).toString('base64url');}
 private async passwordValid(password:string,stored:string){const [v,salt,expected]=stored.split(':');if(v!=='v1'||!salt||!expected)return false;return safeEqual((await scrypt(password,salt)).toString('base64url'),expected);}
 private async ownerFromSession(token:string){const session=await this.repo.findOwnerSessionByHash(hash(required(token,'owner session'))),now=this.now();if(!session||session.revokedAt||session.expiresAt<=now)throw new SaasError('AUTH_REQUIRED','valid owner session required');const owner=await this.repo.findOwnerById(session.ownerId);if(!owner||owner.status!=='ACTIVE')throw new SaasError('AUTH_REQUIRED','valid owner session required');if(owner.lockedUntil&&owner.lockedUntil>now)throw new SaasError('OWNER_LOCKED','owner account is temporarily locked');return owner;}
 async requireOwner(token:string){const owner=await this.ownerFromSession(token);return{id:owner.id,email:owner.email};}
 private async sensitiveOwner(token:string,mfa:string){const owner=await this.ownerFromSession(token);if(!validTotp(this.protector.open(owner.mfaSecretCipher),mfa,this.now()))throw new SaasError('MFA_REQUIRED','valid owner MFA code required');return owner;}

 async ownerBootstrapStatus(){return{available:(await this.repo.countOwners())===0};}
 async bootstrapOwner(input:{email:string;password:string;bootstrapToken:string}){if(await this.repo.countOwners())throw new SaasError('BOOTSTRAP_CLOSED','owner bootstrap is permanently closed');if(!this.bootstrap.verify(required(input.bootstrapToken,'bootstrap token')))throw new SaasError('AUTH_REQUIRED','invalid bootstrap credential');const now=this.now(),secret=b32e(randomBytes(20));const owner:SaasOwnerAccount={id:id(),email:validEmail(input.email),passwordHash:await this.passwordHash(input.password),mfaSecretCipher:this.protector.seal(secret),status:'ACTIVE',failedAttempts:0,lockedUntil:null,createdAt:now,updatedAt:now};await this.repo.createOwner(owner,this.control(owner.id,'owner.bootstrap','OWNER',owner.id,null));return{ownerId:owner.id,email:owner.email,mfaSecret:secret,otpauthUri:'otpauth://totp/'+encodeURIComponent('Elhafez SaaS:'+owner.email)+'?secret='+secret+'&issuer='+encodeURIComponent('Elhafez SaaS')+'&digits=6&period=30'};}
 async recoverOwnerPassword(input:{email:string;newPassword:string;recoveryToken:string}){if(!this.recovery.verify(required(input.recoveryToken,'recovery token')))throw new SaasError('AUTH_REQUIRED','invalid recovery credential');const email=validEmail(input.email),passwordHash=await this.passwordHash(input.newPassword),owner=await this.repo.findOwnerByEmail(email),now=this.now();if(!owner||owner.status!=='ACTIVE')throw new SaasError('INVALID_OWNER_CREDENTIALS','invalid owner credentials');const revokedSessions=await this.repo.recoverOwnerPassword({ownerId:owner.id,passwordHash,updatedAt:now,event:this.control(owner.id,'owner.password.recovered','OWNER',owner.id,null,{})});return{ownerId:owner.id,email:owner.email,revokedSessions};}
 async recoverOwnerMfa(input:{email:string;password:string;recoveryToken:string}){if(!this.recovery.verify(required(input.recoveryToken,'recovery token')))throw new SaasError('AUTH_REQUIRED','invalid recovery credential');const email=validEmail(input.email),owner=await this.repo.findOwnerByEmail(email),now=this.now();if(!owner){await scrypt(input.password,'elhafez-invalid-owner');throw new SaasError('INVALID_OWNER_CREDENTIALS','invalid owner credentials');}const pass=await this.passwordValid(input.password,owner.passwordHash);if(!pass||owner.status!=='ACTIVE'){await this.repo.recordOwnerFailure(owner.id,now,this.control(owner.id,'owner.mfa.recovery.failed','OWNER',owner.id,null,{}));throw new SaasError('INVALID_OWNER_CREDENTIALS','invalid owner credentials');}const secret=b32e(randomBytes(20)),revokedSessions=await this.repo.recoverOwnerMfa({ownerId:owner.id,mfaSecretCipher:this.protector.seal(secret),updatedAt:now,event:this.control(owner.id,'owner.mfa.recovered','OWNER',owner.id,null,{})});return{ownerId:owner.id,email:owner.email,mfaSecret:secret,otpauthUri:'otpauth://totp/'+encodeURIComponent('Elhafez SaaS:'+owner.email)+'?secret='+secret+'&issuer='+encodeURIComponent('Elhafez SaaS')+'&digits=6&period=30',revokedSessions};}
 async loginOwner(input:{email:string;password:string;mfaCode:string}){const owner=await this.repo.findOwnerByEmail(validEmail(input.email));if(!owner){await scrypt(input.password,'elhafez-invalid-owner');throw new SaasError('INVALID_OWNER_CREDENTIALS','invalid owner credentials');}const now=this.now();if(owner.lockedUntil&&owner.lockedUntil>now)throw new SaasError('OWNER_LOCKED','owner account is temporarily locked');const pass=await this.passwordValid(input.password,owner.passwordHash);let mfa=false;if(pass&&owner.status==='ACTIVE')mfa=validTotp(this.protector.open(owner.mfaSecretCipher),input.mfaCode,now);if(!pass||!mfa||owner.status!=='ACTIVE'){await this.repo.recordOwnerFailure(owner.id,now,this.control(owner.id,'owner.login.failed','OWNER',owner.id,null,{}));throw new SaasError('INVALID_OWNER_CREDENTIALS','invalid owner credentials');}await this.repo.resetOwnerFailures(owner.id,now);const token=randomBytes(32).toString('base64url'),session:SaasOwnerSession={id:id(),ownerId:owner.id,tokenHash:hash(token),authenticatedAt:now,expiresAt:new Date(now.getTime()+4*60*60_000),revokedAt:null,createdAt:now};await this.repo.createOwnerSession(session,this.control(owner.id,'owner.login.succeeded','OWNER_SESSION',session.id,null));return{token,expiresAt:session.expiresAt,owner:{id:owner.id,email:owner.email}};}
 async logoutOwner(token:string){const session=await this.repo.findOwnerSessionByHash(hash(required(token,'owner session')));if(session&&!session.revokedAt)await this.repo.revokeOwnerSession(session.id,this.now(),this.control(session.ownerId,'owner.logout','OWNER_SESSION',session.id,null));}
 async revokeAllOwnerSessionsForRecovery(){return this.repo.revokeAllOwnerSessions(this.now(),this.control(null,'owner.sessions.revoked.recovery','OWNER_SESSION',null,null,{reason:'DATABASE_RESTORE'}));}

 async requireSensitiveOwner(token:string,mfa:string){const owner=await this.sensitiveOwner(token,mfa);return{id:owner.id,email:owner.email};}
 async beginCompanyProvisioning(token:string,mfa:string,metadata:{name:string;administratorUsername:string}){const owner=await this.sensitiveOwner(token,mfa);await this.repo.recordControlEvent(this.control(owner.id,'company.provision.requested','COMPANY',null,null,{name:required(metadata.name,'name'),administratorUsername:required(metadata.administratorUsername,'administratorUsername').normalize('NFKC').toLowerCase()}));return{id:owner.id,email:owner.email};}
 async createPlan(token:string,mfa:string,input:{code:string;name:string;intervalMonths:number;priceMinor:number;currency:string;entitlements:readonly string[]}){const owner=await this.sensitiveOwner(token,mfa);if(!Number.isInteger(input.intervalMonths)||input.intervalMonths<1||input.intervalMonths>24)throw new SaasError('VALIDATION_ERROR','intervalMonths must be between 1 and 24');const normalizedCode=required(input.code,'code').toUpperCase().replace(/[^A-Z0-9_-]/g,'');if(!normalizedCode)throw new SaasError('VALIDATION_ERROR','code must contain letters or numbers');const plan:SaasPlan={id:id(),code:normalizedCode,name:required(input.name,'name'),intervalMonths:input.intervalMonths,priceMinor:validMinor(input.priceMinor,'priceMinor'),currency:validCurrency(input.currency),entitlements:entitlements(input.entitlements),active:true,createdAt:this.now()};return this.repo.createPlan(plan,this.control(owner.id,'plan.created','PLAN',plan.id,null,{code:plan.code}));}
 async listPlansForOwner(token:string){await this.ownerFromSession(token);return this.repo.listPlans();}
 private async companyCode(){for(let n=0;n<8;n++){const value='ELH-'+randomBytes(8).toString('hex').toUpperCase();if(!await this.repo.findTenantByCode(value))return value;}throw new SaasError('CONFLICT','could not allocate company code');}
 private payment(input:{companyId:string;subscriptionId:string;reference:string;amountMinor:number;currency:string;idempotencyKey:string},requestHash:string):SaasPayment{return{id:id(),companyId:input.companyId,subscriptionId:input.subscriptionId,provider:'MANUAL',reference:required(input.reference,'payment reference'),amountMinor:validMinor(input.amountMinor,'amountMinor'),currency:validCurrency(input.currency),idempotencyKey:required(input.idempotencyKey,'idempotencyKey'),payloadHash:requestHash,paidAt:this.now(),createdAt:this.now()};}
 private paymentMatch(plan:SaasPlan,months:number,amount:number,currencyCode:string){if(!Number.isInteger(months)||months<1||months>120)throw new SaasError('VALIDATION_ERROR','months must be between 1 and 120');if(months%plan.intervalMonths!==0)throw new SaasError('VALIDATION_ERROR','duration must be a whole number of plan billing intervals');const billingPeriods=months/plan.intervalMonths,expected=plan.priceMinor*billingPeriods;if(!Number.isSafeInteger(expected))throw new SaasError('VALIDATION_ERROR','payment exceeds supported range');if(amount!==expected||validCurrency(currencyCode)!==plan.currency)throw new SaasError('PAYMENT_MISMATCH','payment must exactly match the plan and duration');}
 private customPaymentMatch(plan:SaasPlan,amount:number,currencyCode:string){validMinor(amount,'amountMinor');if(validCurrency(currencyCode)!==plan.currency)throw new SaasError('PAYMENT_MISMATCH','payment currency must match the selected plan');}
 private customPeriodEnd(value:string,base:Date){const raw=required(value,'periodEnd');if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(raw))throw new SaasError('VALIDATION_ERROR','periodEnd must use YYYY-MM-DD');const end=new Date(raw+'T23:59:59.999Z');if(Number.isNaN(end.getTime())||end.toISOString().slice(0,10)!==raw)throw new SaasError('VALIDATION_ERROR','periodEnd is not a valid calendar date');if(end<=base)throw new SaasError('VALIDATION_ERROR','periodEnd must be after the current subscription boundary');return end;}
 private subscriptionPeriod(plan:SaasPlan,base:Date,input:{months?:number;periodEnd?:string},amount:number,currencyCode:string){if(input.periodEnd!==undefined){if(input.months!==undefined)throw new SaasError('VALIDATION_ERROR','use either months or periodEnd, not both');this.customPaymentMatch(plan,amount,currencyCode);const end=this.customPeriodEnd(input.periodEnd,base);return{end,metadata:{periodMode:'CUSTOM_END_DATE',periodEnd:end.toISOString()}};}if(input.months===undefined)throw new SaasError('VALIDATION_ERROR','subscription period is required');this.paymentMatch(plan,input.months,amount,currencyCode);return{end:addMonths(base,input.months),metadata:{periodMode:'PLAN_INTERVAL',months:input.months}};}

 async activateSubscription(token:string,mfa:string,input:{companyId:string;planId:string;months?:number;periodEnd?:string;paymentReference:string;amountMinor:number;currency:string;idempotencyKey:string}){const owner=await this.sensitiveOwner(token,mfa),companyId=required(input.companyId,'companyId'),plan=await this.repo.findPlan(required(input.planId,'planId'));if(!plan||!plan.active)throw new SaasError('NOT_FOUND','active plan was not found');const now=this.now(),period=this.subscriptionPeriod(plan,now,input,input.amountMinor,input.currency),end=period.end,request=fingerprint({kind:'activate',companyId,planId:plan.id,periodEnd:end.toISOString(),periodMode:period.metadata.periodMode,paymentReference:input.paymentReference,amountMinor:input.amountMinor,currency:validCurrency(input.currency)}),prior=await this.repo.findPaymentByIdempotencyKey(required(input.idempotencyKey,'idempotencyKey'));if(prior){if(prior.payloadHash!==request)throw new SaasError('IDEMPOTENCY_CONFLICT','idempotency key belongs to another request');const replay=await this.repo.findSubscription(companyId);if(!replay)throw new SaasError('CONFLICT','activation replay is incomplete');return replay;}const existing=await this.repo.findTenant(companyId),tenant:SaasTenant=existing?{...existing,mode:'SUBSCRIPTION',updatedAt:now}:{companyId,companyCode:await this.companyCode(),mode:'SUBSCRIPTION',createdAt:now,updatedAt:now},subscription:SaasSubscription={id:id(),companyId,planId:plan.id,status:'ACTIVE',currentPeriodStart:now,currentPeriodEnd:end,gracePeriodEnd:null,entitlements:plan.entitlements,version:1,createdAt:now,updatedAt:now},payment=this.payment({companyId,subscriptionId:subscription.id,reference:input.paymentReference,amountMinor:input.amountMinor,currency:input.currency,idempotencyKey:input.idempotencyKey},request),event:SaasSubscriptionEvent={id:id(),companyId,subscriptionId:subscription.id,kind:'ACTIVATED',fromStatus:null,toStatus:'ACTIVE',ownerId:owner.id,paymentId:payment.id,periodStart:now,periodEnd:end,metadata:{planId:plan.id,...period.metadata},occurredAt:now};return this.repo.activate({tenant,subscription,payment,event,controlEvent:this.control(owner.id,'subscription.activated','SUBSCRIPTION',subscription.id,companyId,{planId:plan.id,...period.metadata})});}
 async renewSubscription(token:string,mfa:string,input:{companyId:string;months?:number;periodEnd?:string;paymentReference:string;amountMinor:number;currency:string;idempotencyKey:string}){const owner=await this.sensitiveOwner(token,mfa),companyId=required(input.companyId,'companyId'),current=await this.repo.findSubscription(companyId);if(!current)throw new SaasError('NOT_FOUND','subscription was not found');if(current.status==='CANCELLED')throw new SaasError('CONFLICT','cancelled subscription is terminal');const plan=await this.repo.findPlan(current.planId);if(!plan||!plan.active)throw new SaasError('NOT_FOUND','active plan was not found');const now=this.now(),base=current.currentPeriodEnd>now?current.currentPeriodEnd:now,period=this.subscriptionPeriod(plan,base,input,input.amountMinor,input.currency),end=period.end,request=fingerprint({kind:'renew',companyId,periodEnd:end.toISOString(),periodMode:period.metadata.periodMode,paymentReference:input.paymentReference,amountMinor:input.amountMinor,currency:validCurrency(input.currency),planId:plan.id}),prior=await this.repo.findPaymentByIdempotencyKey(required(input.idempotencyKey,'idempotencyKey'));if(prior){if(prior.payloadHash!==request)throw new SaasError('IDEMPOTENCY_CONFLICT','idempotency key belongs to another request');const replay=await this.repo.findSubscription(companyId);if(!replay)throw new SaasError('CONFLICT','renewal replay is incomplete');return replay;}const next:SaasSubscription={...current,status:'ACTIVE',currentPeriodStart:current.currentPeriodEnd>now?current.currentPeriodStart:now,currentPeriodEnd:end,gracePeriodEnd:null,entitlements:plan.entitlements,version:current.version+1,updatedAt:now},payment=this.payment({companyId,subscriptionId:current.id,reference:input.paymentReference,amountMinor:input.amountMinor,currency:input.currency,idempotencyKey:input.idempotencyKey},request),event:SaasSubscriptionEvent={id:id(),companyId,subscriptionId:current.id,kind:'RENEWED',fromStatus:current.status,toStatus:'ACTIVE',ownerId:owner.id,paymentId:payment.id,periodStart:next.currentPeriodStart,periodEnd:end,metadata:{previousPeriodEnd:current.currentPeriodEnd.toISOString(),...period.metadata},occurredAt:now};return this.repo.renew({expectedVersion:current.version,subscription:next,payment,event,controlEvent:this.control(owner.id,'subscription.renewed','SUBSCRIPTION',current.id,companyId,{...period.metadata})});}
 private async change(token:string,mfa:string,companyIdInput:string,target:'SUSPENDED'|'ACTIVE'|'CANCELLED'){const owner=await this.sensitiveOwner(token,mfa),companyId=required(companyIdInput,'companyId'),current=await this.repo.findSubscription(companyId);if(!current)throw new SaasError('NOT_FOUND','subscription was not found');if(current.status===target)return current;if(current.status==='CANCELLED')throw new SaasError('CONFLICT','cancelled subscription is terminal');const now=this.now();if(target==='ACTIVE'&&current.currentPeriodEnd<=now)throw new SaasError('SUBSCRIPTION_EXPIRED','expired subscription must be renewed');const next:SaasSubscription={...current,status:target,version:current.version+1,updatedAt:now},kind=target==='SUSPENDED'?'SUSPENDED':target==='CANCELLED'?'CANCELLED':'RESUMED',event:SaasSubscriptionEvent={id:id(),companyId,subscriptionId:current.id,kind,fromStatus:current.status,toStatus:target,ownerId:owner.id,paymentId:null,periodStart:current.currentPeriodStart,periodEnd:current.currentPeriodEnd,metadata:{},occurredAt:now};return this.repo.changeStatus({expectedVersion:current.version,subscription:next,event,controlEvent:this.control(owner.id,'subscription.'+kind.toLowerCase(),'SUBSCRIPTION',current.id,companyId)});}
 suspendSubscription(t:string,m:string,c:string){return this.change(t,m,c,'SUSPENDED');}resumeSubscription(t:string,m:string,c:string){return this.change(t,m,c,'ACTIVE');}cancelSubscription(t:string,m:string,c:string){return this.change(t,m,c,'CANCELLED');}

 private effective(tenant:SaasTenant|null,sub:SaasSubscription|null,requested?:string):TenantAccessProjection{if(!tenant)return{companyId:'',companyCode:null,mode:null,status:'SUBSCRIPTION_REQUIRED',allowed:false,planId:null,currentPeriodEnd:null,gracePeriodEnd:null,entitlements:[],reason:'SUBSCRIPTION_REQUIRED'};if(tenant.mode==='INTERNAL')return{companyId:tenant.companyId,companyCode:tenant.companyCode,mode:tenant.mode,status:'ACTIVE',allowed:true,planId:null,currentPeriodEnd:null,gracePeriodEnd:null,entitlements:['*'],reason:null};if(!sub)return{companyId:tenant.companyId,companyCode:tenant.companyCode,mode:tenant.mode,status:'SUBSCRIPTION_REQUIRED',allowed:false,planId:null,currentPeriodEnd:null,gracePeriodEnd:null,entitlements:[],reason:'SUBSCRIPTION_REQUIRED'};const now=this.now();let status:TenantAccessProjection['status']=sub.status,allowed=false,reason:string|null=null;if(sub.status==='SUSPENDED')reason='SUBSCRIPTION_SUSPENDED';else if(sub.status==='CANCELLED')reason='SUBSCRIPTION_CANCELLED';else if(sub.currentPeriodEnd>now)allowed=true;else if(sub.status==='PAST_DUE'&&sub.gracePeriodEnd&&sub.gracePeriodEnd>now)allowed=true;else{status='EXPIRED';reason='SUBSCRIPTION_EXPIRED';}if(allowed&&requested&&requested!=='*'&&!sub.entitlements.includes('*')&&!sub.entitlements.includes(requested.toUpperCase())){allowed=false;reason='ENTITLEMENT_REQUIRED';}return{companyId:tenant.companyId,companyCode:tenant.companyCode,mode:tenant.mode,status,allowed,planId:sub.planId,currentPeriodEnd:sub.currentPeriodEnd,gracePeriodEnd:sub.gracePeriodEnd,entitlements:sub.entitlements,reason};}
 async subscriptionStatus(companyIdInput:string,requested?:string){const companyId=required(companyIdInput,'companyId'),result=this.effective(await this.repo.findTenant(companyId),await this.repo.findSubscription(companyId),requested);return result.companyId?result:{...result,companyId};}
 async assertTenantAccess(companyId:string,requested?:string){const result=await this.subscriptionStatus(companyId,requested);if(!result.allowed)throw new SaasError(result.reason??'SUBSCRIPTION_REQUIRED','tenant subscription does not permit access');return result;}
 async resolveCompanyCode(value:string){const code=required(value,'companyCode').toUpperCase(),tenant=await this.repo.findTenantByCode(code);if(!tenant)throw new SaasError('NOT_FOUND','company code was not found');return{companyId:tenant.companyId,companyCode:tenant.companyCode};}
 async listTenantsForOwner(token:string):Promise<readonly OwnerTenantProjection[]>{await this.ownerFromSession(token);const tenants=await this.repo.listTenants();return Promise.all(tenants.map(async tenant=>{const sub=await this.repo.findSubscription(tenant.companyId),access=this.effective(tenant,sub);return{...access,subscriptionId:sub?.id??null,subscriptionVersion:sub?.version??null};}));}
}
