import{randomUUID}from'node:crypto';import{ContractValidationError,currencyCode,type CompanyId,type ExecutionContext}from'@elhafez/contracts';import type{TourismProgram,TourismProgramCommercial,TourismProgramHistory,TourismProgramStatus}from'../domain/program.js';import type{TourismProgramAccess}from'./program.access.js';import type{TourismProgramRepository}from'./program.repository.js';import type{TourismProgramFinancePort}from'./program.finance.js';
export const TOURISM_PROGRAM_PERMISSIONS=Object.freeze({view:'tourism.programs.view',manage:'tourism.programs.manage',lifecycle:'tourism.programs.lifecycle',commercial:'tourism.programs.commercial.manage'});
export interface TourismProgramInput{code:string;nameAr:string;nameEn?:string;departureDate:string;returnDate:string;salesOpen:string;salesClose:string;currency:string;notes?:string}
const req=(value:string,field:string)=>{const v=value.trim();if(!v)throw new ContractValidationError(field,'is required');return v};
const date=(value:string,field:string)=>{const v=req(value,field);if(!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new ContractValidationError(field,'must be YYYY-MM-DD');const parsed=new Date(v+'T00:00:00.000Z');if(Number.isNaN(parsed.valueOf())||parsed.toISOString().slice(0,10)!==v)throw new ContractValidationError(field,'must be a valid calendar date');return v};
function validate(input:TourismProgramInput){date(input.departureDate,'departureDate');date(input.returnDate,'returnDate');date(input.salesOpen,'salesOpen');date(input.salesClose,'salesClose');if(input.returnDate<input.departureDate)throw new ContractValidationError('returnDate','must be on or after departureDate');if(input.salesClose<input.salesOpen)throw new ContractValidationError('salesClose','must be on or after salesOpen');if(input.salesClose>input.departureDate)throw new ContractValidationError('salesClose','must not be after departureDate');}
export class TourismProgramsApplicationService{
 constructor(private readonly repo:TourismProgramRepository,private readonly access:TourismProgramAccess,private readonly finance:TourismProgramFinancePort,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async permitted(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p);}
 private history(c:ExecutionContext,id:string,action:TourismProgramHistory['action'],reason?:string):TourismProgramHistory{return{id:this.newId(),companyId:c.companyId,branchId:c.branchId,programId:id,action,actorId:c.actorId,...(reason?{reason}:{}),occurredAt:this.now().toISOString()}}
 async create(c:ExecutionContext,input:TourismProgramInput){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.manage);validate(input);const at=this.now().toISOString();const value:TourismProgram={id:this.newId(),companyId:c.companyId,branchId:c.branchId,code:req(input.code,'code'),nameAr:req(input.nameAr,'nameAr'),...(input.nameEn?.trim()?{nameEn:input.nameEn.trim()}:{}),departureDate:input.departureDate,returnDate:input.returnDate,salesOpen:input.salesOpen,salesClose:input.salesClose,currency:currencyCode(req(input.currency,'currency').toUpperCase()),...(input.notes?.trim()?{notes:input.notes.trim()}:{}),status:'PREPARING',revision:1,createdAt:at,updatedAt:at};const result=await this.repo.create(value,this.history(c,value.id,'CREATED'));await this.access.audit(c,'tourism.program.created',result.id);return result;}
 async update(c:ExecutionContext,id:string,input:TourismProgramInput){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.manage);validate(input);const old=await this.required(c.companyId,c.branchId,id);if(old.status!=='PREPARING')throw new ContractValidationError('status','only PREPARING program can be edited');const value:TourismProgram={...old,code:req(input.code,'code'),nameAr:req(input.nameAr,'nameAr'),nameEn:input.nameEn?.trim()||undefined,departureDate:input.departureDate,returnDate:input.returnDate,salesOpen:input.salesOpen,salesClose:input.salesClose,currency:currencyCode(req(input.currency,'currency').toUpperCase()),notes:input.notes?.trim()||undefined,revision:old.revision+1,updatedAt:this.now().toISOString()};return this.repo.save(value,this.history(c,id,'UPDATED'));}
 async get(c:ExecutionContext,id:string){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.view);return this.required(c.companyId,c.branchId,id)}
 async list(c:ExecutionContext,status?:TourismProgramStatus){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.view);return this.repo.list(c.companyId,c.branchId,status)}
 async open(c:ExecutionContext,id:string){return this.transition(c,id,'OPEN','OPENED',['PREPARING']);}
 async start(c:ExecutionContext,id:string){return this.transition(c,id,'OPERATING','STARTED',['OPEN']);}
 async close(c:ExecutionContext,id:string){return this.transition(c,id,'CLOSED','CLOSED',['OPEN','OPERATING']);}
 async cancel(c:ExecutionContext,id:string,input:{reason:string;commandKey:string;postingDate:string}){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.lifecycle);const old=await this.required(c.companyId,c.branchId,id);if(!['PREPARING','OPEN'].includes(old.status))throw new ContractValidationError('status',old.status+' cannot transition to CANCELLED');const reason=req(input.reason,'reason'),commandKey=req(input.commandKey,'commandKey'),postingDate=date(input.postingDate,'postingDate');const today=this.now().toISOString().slice(0,10),travelStarted=old.status==='OPERATING'||old.status==='CLOSED'||today>=old.departureDate;const evidence='PROGRAM_STATUS:'+old.status+';DEPARTURE:'+old.departureDate+';SERVER_DATE:'+today;const financial=await this.finance.cancel({companyId:c.companyId,branchId:c.branchId,commandKey,programId:id,travelStarted,travelEvidence:evidence,postingDate});if(!financial.cancelled){const detail=financial.blockers.map(blocker=>blocker.type+':'+blocker.reference).join(', ')||'financial cancellation blocked';throw new ContractValidationError('finance',detail);}const value={...old,status:'CANCELLED' as const,revision:old.revision+1,updatedAt:this.now().toISOString()};const result=await this.repo.save(value,this.history(c,id,'CANCELLED',reason));await this.access.audit(c,'tourism.program.cancelled',id,{reason,financeCommandKey:commandKey});return result;}
 async commercial(c:ExecutionContext,id:string){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.view);await this.required(c.companyId,c.branchId,id);return await this.repo.commercial(c.companyId,c.branchId,id)??{companyId:c.companyId,branchId:c.branchId,programId:id,totalCapacity:null,waitlistEnabled:false,priceTiers:[],addOnServiceIds:[],discountPolicy:{maxPercent:0,approvalAbovePercent:0},updatedAt:this.now().toISOString()};}
 async configureCommercial(c:ExecutionContext,id:string,input:{totalCapacity?:number|null;waitlistEnabled?:boolean;priceTiers?:readonly{code:string;label:string;sellingPrice:string;estimatedCost:string;capacity?:number|null;active?:boolean}[];addOnServiceIds?:readonly string[];discountPolicy?:{maxPercent:number;approvalAbovePercent:number}}){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.commercial);const program=await this.required(c.companyId,c.branchId,id);if(!['PREPARING','OPEN'].includes(program.status))throw new ContractValidationError('status','commercial configuration is locked after operation starts');const capacity=input.totalCapacity??null;if(capacity!==null&&(!Number.isInteger(capacity)||capacity<0))throw new ContractValidationError('totalCapacity','must be a non-negative integer');const current=await this.repo.commercial(c.companyId,c.branchId,id),policy=input.discountPolicy??current?.discountPolicy??{maxPercent:0,approvalAbovePercent:0};if(policy.maxPercent<0||policy.maxPercent>100||policy.approvalAbovePercent<0||policy.approvalAbovePercent>policy.maxPercent)throw new ContractValidationError('discountPolicy','invalid percentages');const tiers=(input.priceTiers??current?.priceTiers??[]).map((x,index)=>{const code=req(x.code,'priceTiers.'+index+'.code'),label=req(x.label,'priceTiers.'+index+'.label'),selling=x.sellingPrice.trim(),cost=x.estimatedCost.trim();if(!/^\d+(?:\.\d{1,6})?$/.test(selling)||!/^\d+(?:\.\d{1,6})?$/.test(cost))throw new ContractValidationError('priceTiers','prices must be non-negative decimal');const tierCapacity=x.capacity??null;if(tierCapacity!==null&&(!Number.isInteger(tierCapacity)||tierCapacity<0))throw new ContractValidationError('priceTiers.capacity','invalid');return{code,label,sellingPrice:selling,estimatedCost:cost,capacity:tierCapacity,active:x.active??true}});if(new Set(tiers.map(x=>x.code)).size!==tiers.length)throw new ContractValidationError('priceTiers','duplicate tier code');const value:TourismProgramCommercial={companyId:c.companyId,branchId:c.branchId,programId:id,totalCapacity:capacity,waitlistEnabled:input.waitlistEnabled??current?.waitlistEnabled??false,priceTiers:tiers,addOnServiceIds:[...new Set((input.addOnServiceIds??current?.addOnServiceIds??[]).map(x=>req(x,'addOnServiceId')))],discountPolicy:policy,updatedAt:this.now().toISOString()};const saved=await this.repo.saveCommercial(value);await this.access.audit(c,'tourism.program.commercial.updated',id,{tierCount:saved.priceTiers.length,totalCapacity:saved.totalCapacity});return saved;}
 async commercialForIntegration(companyId:CompanyId,branchId:string,id:string){await this.required(companyId,branchId,id);return this.repo.commercial(companyId,branchId,id)}
 async getForIntegration(companyId:CompanyId,branchId:string,id:string){return this.required(companyId,branchId,id)}
 async requireEditableForIntegration(companyId:CompanyId,branchId:string,id:string){const value=await this.required(companyId,branchId,id);if(value.status!=='PREPARING')throw new ContractValidationError('program','program is not editable');return value}
 private async transition(c:ExecutionContext,id:string,status:TourismProgramStatus,action:TourismProgramHistory['action'],allowed:TourismProgramStatus[],reason?:string){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.lifecycle);const old=await this.required(c.companyId,c.branchId,id);if(!allowed.includes(old.status))throw new ContractValidationError('status',old.status+' cannot transition to '+status);const value={...old,status,revision:old.revision+1,updatedAt:this.now().toISOString()};const result=await this.repo.save(value,this.history(c,id,action,reason));await this.access.audit(c,'tourism.program.'+status.toLowerCase(),id,{reason});return result}
 private async required(companyId:CompanyId,branchId:string,id:string){const value=await this.repo.get(companyId,branchId,id);if(!value)throw new ContractValidationError('programId','program not found');return value}
}
