import{randomUUID}from'node:crypto';import{ContractValidationError,type CompanyId,type ExecutionContext}from'@elhafez/contracts';import type{TourismProgram,TourismProgramHistory,TourismProgramStatus}from'../domain/program.js';import type{TourismProgramAccess}from'./program.access.js';import type{TourismProgramRepository}from'./program.repository.js';
export const TOURISM_PROGRAM_PERMISSIONS=Object.freeze({view:'tourism.programs.view',manage:'tourism.programs.manage',lifecycle:'tourism.programs.lifecycle'});
export interface TourismProgramInput{code:string;nameAr:string;nameEn?:string;departureDate:string;returnDate:string;salesOpen:string;salesClose:string;currency:string;notes?:string}
const req=(value:string,field:string)=>{const v=value.trim();if(!v)throw new ContractValidationError(field,'is required');return v};
function validate(input:TourismProgramInput){if(input.returnDate<input.departureDate)throw new ContractValidationError('returnDate','must be on or after departureDate');if(input.salesClose<input.salesOpen)throw new ContractValidationError('salesClose','must be on or after salesOpen');if(input.salesClose>input.departureDate)throw new ContractValidationError('salesClose','must not be after departureDate');}
export class TourismProgramsApplicationService{
 constructor(private readonly repo:TourismProgramRepository,private readonly access:TourismProgramAccess,private readonly now=()=>new Date(),private readonly newId=()=>randomUUID()){}
 private async permitted(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p);}
 private history(c:ExecutionContext,id:string,action:TourismProgramHistory['action'],reason?:string):TourismProgramHistory{return{id:this.newId(),companyId:c.companyId,branchId:c.branchId,programId:id,action,actorId:c.actorId,...(reason?{reason}:{}),occurredAt:this.now().toISOString()}}
 async create(c:ExecutionContext,input:TourismProgramInput){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.manage);validate(input);const at=this.now().toISOString();const value:TourismProgram={id:this.newId(),companyId:c.companyId,branchId:c.branchId,code:req(input.code,'code'),nameAr:req(input.nameAr,'nameAr'),...(input.nameEn?.trim()?{nameEn:input.nameEn.trim()}:{}),departureDate:input.departureDate,returnDate:input.returnDate,salesOpen:input.salesOpen,salesClose:input.salesClose,currency:req(input.currency,'currency').toUpperCase(),...(input.notes?.trim()?{notes:input.notes.trim()}:{}),status:'PREPARING',revision:1,createdAt:at,updatedAt:at};const result=await this.repo.create(value,this.history(c,value.id,'CREATED'));await this.access.audit(c,'tourism.program.created',result.id);return result;}
 async update(c:ExecutionContext,id:string,input:TourismProgramInput){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.manage);validate(input);const old=await this.required(c.companyId,c.branchId,id);if(old.status!=='PREPARING')throw new ContractValidationError('status','only PREPARING program can be edited');const value:TourismProgram={...old,code:req(input.code,'code'),nameAr:req(input.nameAr,'nameAr'),nameEn:input.nameEn?.trim()||undefined,departureDate:input.departureDate,returnDate:input.returnDate,salesOpen:input.salesOpen,salesClose:input.salesClose,currency:req(input.currency,'currency').toUpperCase(),notes:input.notes?.trim()||undefined,revision:old.revision+1,updatedAt:this.now().toISOString()};return this.repo.save(value,this.history(c,id,'UPDATED'));}
 async get(c:ExecutionContext,id:string){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.view);return this.required(c.companyId,c.branchId,id)}
 async list(c:ExecutionContext,status?:TourismProgramStatus){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.view);return this.repo.list(c.companyId,c.branchId,status)}
 async open(c:ExecutionContext,id:string){return this.transition(c,id,'OPEN','OPENED',['PREPARING']);}
 async start(c:ExecutionContext,id:string){return this.transition(c,id,'OPERATING','STARTED',['OPEN']);}
 async close(c:ExecutionContext,id:string){return this.transition(c,id,'CLOSED','CLOSED',['OPEN','OPERATING']);}
 async cancel(c:ExecutionContext,id:string,reason:string){reason=req(reason,'reason');return this.transition(c,id,'CANCELLED','CANCELLED',['PREPARING','OPEN'],reason);}
 async getForIntegration(companyId:CompanyId,branchId:string,id:string){return this.required(companyId,branchId,id)}
 async requireEditableForIntegration(companyId:CompanyId,branchId:string,id:string){const value=await this.required(companyId,branchId,id);if(value.status!=='PREPARING')throw new ContractValidationError('program','program is not editable');return value}
 private async transition(c:ExecutionContext,id:string,status:TourismProgramStatus,action:TourismProgramHistory['action'],allowed:TourismProgramStatus[],reason?:string){await this.permitted(c,TOURISM_PROGRAM_PERMISSIONS.lifecycle);const old=await this.required(c.companyId,c.branchId,id);if(!allowed.includes(old.status))throw new ContractValidationError('status',old.status+' cannot transition to '+status);const value={...old,status,revision:old.revision+1,updatedAt:this.now().toISOString()};const result=await this.repo.save(value,this.history(c,id,action,reason));await this.access.audit(c,'tourism.program.'+status.toLowerCase(),id,{reason});return result}
 private async required(companyId:CompanyId,branchId:string,id:string){const value=await this.repo.get(companyId,branchId,id);if(!value)throw new ContractValidationError('programId','program not found');return value}
}
