import{createHash,randomBytes,randomUUID}from'node:crypto';import{ContractValidationError,type CompanyId,type ExecutionContext}from'@elhafez/contracts';import type{IntegrationAccess,IntegrationTransport}from'./integration-hub.ports.js';import type{IntegrationHubRepository}from'./integration-hub.repository.js';import{publicHttpsUrl,req,type ApiKeyRecord,type IntegrationConnection,type IntegrationKind,type WebhookDelivery,type WebhookSubscription}from'../domain/integration.js';
export const INTEGRATION_PERMISSIONS=Object.freeze({read:'integrations.read',manage:'integrations.manage',apiKeys:'integrations.api-keys.manage',webhooks:'integrations.webhooks.manage'});
const digest=(v:string)=>createHash('sha256').update(v).digest('base64url');
export class IntegrationHubApplicationService{constructor(private readonly repo:IntegrationHubRepository,private readonly transport:IntegrationTransport,private readonly access:IntegrationAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async perm(c:ExecutionContext,p:string){await this.access.requirePermission(c,p)}
 async saveConnection(c:ExecutionContext,input:{id?:string;kind:IntegrationKind;name:string;enabled?:boolean;endpoint?:string;credentialRef?:string;config?:Record<string,unknown>}){await this.perm(c,INTEGRATION_PERMISSIONS.manage);const prior=input.id?await this.repo.getConnection(c.companyId,input.id):null,at=this.now().toISOString(),value:IntegrationConnection={id:input.id?.trim()||this.newId(),companyId:c.companyId,kind:input.kind,name:req(input.name,'name'),enabled:input.enabled??true,endpoint:input.endpoint?.trim()?publicHttpsUrl(input.endpoint,'endpoint'):null,credentialRef:input.credentialRef?.trim()||null,config:Object.freeze({...input.config}),createdAt:prior?.createdAt??at,updatedAt:at};const out=await this.repo.saveConnection(value);await this.access.audit(c,'integration.connection.saved',out.id,{kind:out.kind,enabled:out.enabled});return out}
 async connections(c:ExecutionContext){await this.perm(c,INTEGRATION_PERMISSIONS.read);return this.repo.listConnections(c.companyId)}
 async testConnection(c:ExecutionContext,id:string){await this.perm(c,INTEGRATION_PERMISSIONS.manage);const value=await this.repo.getConnection(c.companyId,id);if(!value)throw new ContractValidationError('connectionId','not found');if(!value.enabled)throw new ContractValidationError('connection','connection is disabled');return this.transport.test(value)}
 async dispatchToConnection(companyId:CompanyId,kind:IntegrationKind,payload:Readonly<Record<string,unknown>>){const connections=(await this.repo.listConnections(companyId)).filter(x=>x.enabled&&x.kind===kind);if(connections.length!==1)throw new ContractValidationError('integration',connections.length?'multiple active '+kind+' connections require explicit provider selection':'no active '+kind+' connection');const result=await this.transport.send(connections[0]!,payload);if(result.statusCode<200||result.statusCode>=300)throw new ContractValidationError('integration','provider returned HTTP '+result.statusCode);return result}
 async dispatchMessage(companyId:CompanyId,kind:'EMAIL'|'WHATSAPP'|'SMS',payload:Readonly<Record<string,unknown>>){return this.dispatchToConnection(companyId,kind,payload)}
 async issueApiKey(c:ExecutionContext,input:{name:string;scopes:readonly string[];rateLimitPerMinute?:number;expiresAt?:string}){await this.perm(c,INTEGRATION_PERMISSIONS.apiKeys);const limit=input.rateLimitPerMinute??60;if(!Number.isInteger(limit)||limit<1||limit>10000)throw new ContractValidationError('rateLimitPerMinute','must be 1..10000');const raw='elh_'+randomBytes(32).toString('base64url'),at=this.now().toISOString(),exp=input.expiresAt?new Date(input.expiresAt):null;if(exp&&Number.isNaN(exp.valueOf()))throw new ContractValidationError('expiresAt','invalid');const record:ApiKeyRecord={id:this.newId(),companyId:c.companyId,name:req(input.name,'name'),keyPrefix:raw.slice(0,12),secretHash:digest(raw),scopes:[...new Set(input.scopes.map(x=>req(x,'scope')))].sort(),rateLimitPerMinute:limit,windowStartedAt:at,windowCount:0,expiresAt:exp?.toISOString()??null,revokedAt:null,createdAt:at};await this.repo.saveApiKey(record);await this.access.audit(c,'integration.api-key.issued',record.id,{scopes:record.scopes});return{record,secret:raw}}
 async revokeApiKey(c:ExecutionContext,id:string){await this.perm(c,INTEGRATION_PERMISSIONS.apiKeys);const old=await this.repo.getApiKey(c.companyId,id);if(!old)throw new ContractValidationError('apiKeyId','not found');if(old.revokedAt)return old;return this.repo.saveApiKey({...old,revokedAt:this.now().toISOString()})}
 async apiKeys(c:ExecutionContext){await this.perm(c,INTEGRATION_PERMISSIONS.apiKeys);return this.repo.listApiKeys(c.companyId)}
 async authenticateApiKey(secret:string,scope:string){const record=await this.repo.findApiKeyByHash(digest(req(secret,'apiKey')));if(!record||record.revokedAt||record.expiresAt&&record.expiresAt<=this.now().toISOString())throw new ContractValidationError('apiKey','invalid or expired');if(!record.scopes.includes('*')&&!record.scopes.includes(scope))throw new ContractValidationError('scope','api key lacks required scope');const window=new Date(Math.floor(this.now().getTime()/60000)*60000).toISOString(),ok=await this.repo.consumeQuota(record.id,window,record.rateLimitPerMinute);if(!ok)throw new ContractValidationError('rateLimit','API key rate limit exceeded');return{companyId:record.companyId,keyId:record.id,scopes:record.scopes}}
 async saveWebhook(c:ExecutionContext,input:{id?:string;event:string;url:string;secretRef?:string;active?:boolean}){await this.perm(c,INTEGRATION_PERMISSIONS.webhooks);const prior=input.id?await this.repo.getWebhook(c.companyId,input.id):null,at=this.now().toISOString(),value:WebhookSubscription={id:input.id?.trim()||this.newId(),companyId:c.companyId,event:req(input.event,'event'),url:publicHttpsUrl(input.url,'url'),secretRef:input.secretRef?.trim()||null,active:input.active??true,createdAt:prior?.createdAt??at,updatedAt:at};return this.repo.saveWebhook(value)}
 async webhooks(c:ExecutionContext){await this.perm(c,INTEGRATION_PERMISSIONS.read);return this.repo.listWebhooks(c.companyId)}
 async enqueueEvent(companyId:CompanyId,event:string,payload:Readonly<Record<string,unknown>>){const subscriptions=(await this.repo.listWebhooks(companyId)).filter(x=>x.active&&(x.event===event||x.event==='*')),at=this.now().toISOString(),out:WebhookDelivery[]=[];for(const s of subscriptions){const v:WebhookDelivery={id:this.newId(),companyId,subscriptionId:s.id,event,payload:Object.freeze({...payload}),status:'PENDING',attempt:0,maxAttempts:5,nextAttemptAt:at,responseCode:null,lastError:null,createdAt:at,updatedAt:at};out.push(await this.repo.createDelivery(v))}return out}
 async processDue(limit=50){const due=await this.repo.dueDeliveries(this.now().toISOString(),limit),result:WebhookDelivery[]=[];for(const d of due){const sub=await this.repo.getWebhook(d.companyId,d.subscriptionId);if(!sub?.active){result.push(await this.repo.saveDelivery({...d,status:'DEAD_LETTER',lastError:'webhook subscription unavailable',updatedAt:this.now().toISOString()}));continue}const sending=await this.repo.saveDelivery({...d,status:'SENDING',attempt:d.attempt+1,updatedAt:this.now().toISOString()});try{const r=await this.transport.postWebhook(sub,d.event,d.payload);result.push(await this.repo.saveDelivery({...sending,status:r.statusCode>=200&&r.statusCode<300?'DELIVERED':sending.attempt>=sending.maxAttempts?'DEAD_LETTER':'RETRY',responseCode:r.statusCode,lastError:r.statusCode>=200&&r.statusCode<300?null:'HTTP '+r.statusCode,nextAttemptAt:new Date(this.now().getTime()+Math.min(3600,30*2**Math.max(0,sending.attempt-1))*1000).toISOString(),updatedAt:this.now().toISOString()}))}catch(error){result.push(await this.repo.saveDelivery({...sending,status:sending.attempt>=sending.maxAttempts?'DEAD_LETTER':'RETRY',lastError:error instanceof Error?error.message:'transport failure',nextAttemptAt:new Date(this.now().getTime()+Math.min(3600,30*2**Math.max(0,sending.attempt-1))*1000).toISOString(),updatedAt:this.now().toISOString()}))}}return result}
 async deliveries(c:ExecutionContext,subscriptionId?:string){await this.perm(c,INTEGRATION_PERMISSIONS.read);return this.repo.listDeliveries(c.companyId,subscriptionId)}
}
