import type { CompanyId, DecimalAmount, SourceReference } from '@elhafez/contracts';
export type ServiceCategory='HOTEL'|'FLIGHT'|'TRANSPORT'|'VISA'|'OTHER';
export type WorkflowKind='BOOKING_CONFIRMATION'|'BOOKING_DEPOSIT'|'BOOKING_SETTLEMENT'|'BOOKING_CANCELLATION'|'PROGRAM_CANCELLATION'|'PROGRAM_CLOSE'|'MILESTONE_ACTUALIZATION'|'STANDALONE_CONFIRMATION'|'STANDALONE_CANCELLATION';
export type WorkflowStatus='RUNNING'|'BLOCKED'|'SETTLEMENT_REQUIRED'|'COMPLETED';
export interface Workflow {id:string;companyId:CompanyId;branchId?:string;kind:WorkflowKind;commandKey:string;payloadHash:string;sourceType:string;sourceId:string;status:WorkflowStatus;payload:unknown;result?:unknown;createdAt:string;updatedAt:string}
export interface WorkflowStep {id:string;companyId:CompanyId;workflowId:string;name:string;effectKey:string;status:'PENDING'|'COMPLETED';ownerReference?:string;result?:unknown;createdAt:string;completedAt?:string}
export interface FinancialSetup {id:string;companyId:CompanyId;category:ServiceCategory;receivableAccountId:string;customerAdvanceAccountId:string;revenueAccountId:string;costAccountId:string;commissionExpenseAccountId?:string;commissionLiabilityAccountId?:string;active:boolean}
export interface BookingAllocationReference {id:string;quantity:DecimalAmount}
export interface BookingReference {id:string;companyId:CompanyId;branchId?:string;booking:SourceReference;program:SourceReference;customerPartyId:string;confirmationPayloadHash:string;status:'CONFIRMING'|'ACTIVE'|'CANCELLED';invoiceId?:string;allocations:BookingAllocationReference[];approvalRequestId?:string;procurementReference?:{purchaseOrderId?:string;commitmentId?:string};procurementReferences?:readonly {purchaseOrderId?:string;commitmentId?:string}[];commissionClaimId?:string;depositVoucherIds:string[];workflowId:string;financialSetup:{receivableAccountId:string;customerAdvanceAccountId:string;revenueAccountId:string;commissionExpenseAccountId?:string;commissionLiabilityAccountId?:string}}
export interface ServiceFinancialSnapshot {id:string;companyId:CompanyId;service:SourceReference;version:number;category:ServiceCategory;currency:string;saleAmount:DecimalAmount;costAmount:DecimalAmount;status:'CONFIRMED'|'AMENDED';supersedesId?:string;evidence:unknown;requestHash:string;createdAt:string}
export interface StandaloneFinancialReference {id:string;companyId:CompanyId;branchId:string;service:SourceReference;revision:number;confirmationPayloadHash:string;confirmationWorkflowId:string;status:'CONFIRMING'|'ACTIVE'|'CANCELLED';debtorPartyId:string;invoiceId?:string;allocationIds:readonly string[];purchaseOrderIds:readonly string[];commissionClaimId?:string;financialSetup:{receivableAccountId:string;revenueAccountId:string;commissionExpenseAccountId?:string;commissionLiabilityAccountId?:string}}
export interface ProgramHistory {id:string;companyId:CompanyId;program:SourceReference;kind:'CANCELLED'|'CLOSED';workflowId:string;evidence:unknown;createdAt:string}
export interface CancellationBlocker {type:'TRAVEL_STARTED'|'CUSTOMER_SETTLEMENT_REQUIRED'|'PAID_COMMISSION'|'INVENTORY'|'SUPPLIER_EXECUTION'|'SUPPLIER_INVOICE';reference:string;detail?:string}
