import {createHash,randomUUID} from 'node:crypto';
export type BackupStatus='CREATING'|'CREATED'|'VERIFIED'|'FAILED'; export type RestoreStatus='PREFLIGHT'|'RESTORING'|'COMPLETED'|'FAILED';
export interface BackupJob{readonly id:string;readonly actorId:string;readonly companyId:string|null;readonly createdAt:Date;status:BackupStatus;manifest:Readonly<Record<string,unknown>>;checksum:string|null;providerRef:string|null;pinned:boolean;error?:string}
export interface RestoreJob{readonly id:string;readonly backupId:string;readonly actorId:string;status:RestoreStatus;createdAt:Date;error?:string}
export interface BackupProvider{health():Promise<boolean>;create(input:{backupId:string;companyId:string|null}):Promise<{providerRef:string;bytes:Uint8Array;manifest:Readonly<Record<string,unknown>>}>;verify(providerRef:string,checksum:string):Promise<boolean>;restore(providerRef:string):Promise<void>}
export interface OperationsRepository{saveBackup(x:BackupJob):Promise<void>;findBackup(id:string):Promise<BackupJob|undefined>;listBackups(companyId:string|null):Promise<readonly BackupJob[]>;saveRestore(x:RestoreJob):Promise<void>;findRestore(id:string):Promise<RestoreJob|undefined>}
export interface SessionInvalidator{revokeScope(companyId:string|null):Promise<void>}
export class PlatformOperationsError extends Error{}
export class PlatformOperationsApplicationService{constructor(private readonly repository:OperationsRepository,private readonly provider:BackupProvider,private readonly sessions:SessionInvalidator,private readonly now=()=>new Date()){}
 async createBackup(input:{actorId:string;companyId?:string;pin?:boolean}){if(!await this.provider.health())throw new PlatformOperationsError('backup provider is unavailable');const job:BackupJob={id:randomUUID(),actorId:input.actorId,companyId:input.companyId??null,createdAt:this.now(),status:'CREATING',manifest:{},checksum:null,providerRef:null,pinned:input.pin??false};await this.repository.saveBackup(job);try{const result=await this.provider.create({backupId:job.id,companyId:job.companyId});job.providerRef=result.providerRef;job.manifest=result.manifest;job.checksum=createHash('sha256').update(result.bytes).digest('hex');job.status='CREATED';await this.repository.saveBackup(job);if(!await this.provider.verify(result.providerRef,job.checksum))throw new PlatformOperationsError('backup integrity verification failed');job.status='VERIFIED';await this.repository.saveBackup(job);return job}catch(error){job.status='FAILED';job.error=error instanceof Error?error.message:'backup failed';await this.repository.saveBackup(job);return job}}
 async restore(input:{backupId:string;actorId:string;expectedCompanyId?:string}){const backup=await this.repository.findBackup(input.backupId);if(!backup||backup.status!=='VERIFIED'||!backup.providerRef||!backup.checksum)throw new PlatformOperationsError('verified backup required');if(input.expectedCompanyId!==undefined&&backup.companyId!==input.expectedCompanyId)throw new PlatformOperationsError('backup scope is incompatible');if(!await this.provider.verify(backup.providerRef,backup.checksum))throw new PlatformOperationsError('backup is corrupted');const job:RestoreJob={id:randomUUID(),backupId:backup.id,actorId:input.actorId,status:'PREFLIGHT',createdAt:this.now()};await this.repository.saveRestore(job);try{job.status='RESTORING';await this.repository.saveRestore(job);await this.provider.restore(backup.providerRef);await this.sessions.revokeScope(backup.companyId);job.status='COMPLETED';await this.repository.saveRestore(job);return job}catch(error){job.status='FAILED';job.error=error instanceof Error?error.message:'restore failed';await this.repository.saveRestore(job);return job}}
 async listBackups(companyId:string|null){return this.repository.listBackups(companyId)}
 async diagnostics(){const database=await this.repository.listBackups(null).then(()=>true,()=>false);return{database:database?'AVAILABLE' as const:'UNAVAILABLE' as const,backupProvider:await this.provider.health()?'AVAILABLE' as const:'UNAVAILABLE' as const,schemaCompatibility:database?'UNKNOWN' as const:'UNAVAILABLE' as const,runtimeVersion:process.version}}
}
export class InMemoryOperationsRepository implements OperationsRepository{backups=new Map<string,BackupJob>();restores=new Map<string,RestoreJob>();async saveBackup(x:BackupJob){this.backups.set(x.id,structuredClone(x))}async findBackup(id:string){const x=this.backups.get(id);return x&&structuredClone(x)}async listBackups(companyId:string|null){return [...this.backups.values()].filter(x=>x.companyId===companyId).map(x=>structuredClone(x))}async saveRestore(x:RestoreJob){this.restores.set(x.id,structuredClone(x))}async findRestore(id:string){const x=this.restores.get(id);return x&&structuredClone(x)}}
