import {type FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {amountToMinor,formatMinor,type OwnerBackup,type OwnerCompany,type OwnerOperationsDiagnostics,type OwnerPlan,OwnerApiClient} from './owner-client.js';

export interface OwnerControlAppProps { readonly client:OwnerApiClient; readonly initialCompanies?:readonly OwnerCompany[]; readonly initialPlans?:readonly OwnerPlan[]; readonly preview?:boolean }
export function OwnerControlApp({client,initialCompanies=[],initialPlans=[],preview=false}:OwnerControlAppProps){
 const[authenticated,setAuthenticated]=useState(preview||client.hasSession()),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loginOtp,setLoginOtp]=useState('');
 const[setupMode,setSetupMode]=useState(false),[bootstrapToken,setBootstrapToken]=useState(''),[enrollment,setEnrollment]=useState<{mfaSecret:string;otpauthUri:string}|null>(null);
 const[companies,setCompanies]=useState<OwnerCompany[]>([...initialCompanies]),[plans,setPlans]=useState<OwnerPlan[]>([...initialPlans]),[backups,setBackups]=useState<OwnerBackup[]>([]),[ops,setOps]=useState<OwnerOperationsDiagnostics|null>(null),[backupOtp,setBackupOtp]=useState(''),[restoreId,setRestoreId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const[selectedCompany,setSelectedCompany]=useState(''),[selectedPlan,setSelectedPlan]=useState(''),[months,setMonths]=useState('1'),[paymentRef,setPaymentRef]=useState(''),[amount,setAmount]=useState(''),[currency,setCurrency]=useState('EGP'),[actionOtp,setActionOtp]=useState('');
 const[planCode,setPlanCode]=useState('MONTHLY'),[planName,setPlanName]=useState('الاشتراك الشهري'),[planPrice,setPlanPrice]=useState(''),[planOtp,setPlanOtp]=useState('');
 const[companyName,setCompanyName]=useState(''),[adminEmail,setAdminEmail]=useState(''),[adminName,setAdminName]=useState(''),[companyOtp,setCompanyOtp]=useState('');
 const load=useCallback(async()=>{const[c,p,b,o]=await Promise.all([client.companies(),client.plans(),client.backups(),client.operationsDiagnostics()]);setCompanies(c);setPlans(p);setBackups(b);setOps(o);setSelectedCompany(value=>value||c[0]?.company.id||'');setSelectedPlan(value=>value||p[0]?.id||'');},[client]);
 useEffect(()=>{if(authenticated&&!preview)void load().catch(e=>setError(e instanceof Error?e.message:String(e)));},[authenticated,load,preview]);
 const selected=useMemo(()=>companies.find(value=>value.company.id===selectedCompany)??null,[companies,selectedCompany]);
 async function login(event:FormEvent){event.preventDefault();setBusy(true);setError(null);try{await client.login(email,password,loginOtp);setPassword('');setLoginOtp('');setAuthenticated(true);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function enroll(event:FormEvent){event.preventDefault();setBusy(true);setError(null);try{const result=await client.bootstrapOwner(bootstrapToken,email,password);setEnrollment({mfaSecret:result.mfaSecret,otpauthUri:result.otpauthUri});setBootstrapToken('');setPassword('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await client.logout();setAuthenticated(false);setCompanies([]);setPlans([]);}finally{setBusy(false);}}
 async function createCompany(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setMessage(null);try{const result=await client.createCompany(companyOtp,{name:companyName,administratorEmail:adminEmail,administratorDisplayName:adminName});setCompanyOtp('');setCompanyName('');setAdminEmail('');setAdminName('');await load();setSelectedCompany(result.company.id);setMessage(result.invitationStatus==='DELIVERY_UNAVAILABLE'?'تم إنشاء الشركة بأمان، لكن إرسال دعوة كلمة المرور يحتاج إعادة محاولة.':'تم إنشاء الشركة وتجهيز حساب المدير. فعّل الاشتراك بعد تسجيل الدفعة.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function createPlan(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setMessage(null);try{await client.createPlan(planOtp,{code:planCode,name:planName,intervalMonths:1,priceMinor:amountToMinor(planPrice),currency,entitlements:['*']});setPlanOtp('');setPlanPrice('');await load();setMessage('تم إنشاء الباقة بنجاح.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function subscriptionAction(kind:'activate'|'renew'|'suspend'|'resume'){
  if(!selectedCompany) return;setBusy(true);setError(null);setMessage(null);
  try{
   if(kind==='activate'){if(!selectedPlan)throw new Error('اختر الباقة');await client.activate(actionOtp,selectedCompany,{planId:selectedPlan,months:Number(months),paymentReference:paymentRef,amountMinor:amountToMinor(amount),currency,idempotencyKey:globalThis.crypto.randomUUID()});}
   else if(kind==='renew'){await client.renew(actionOtp,selectedCompany,{months:Number(months),paymentReference:paymentRef,amountMinor:amountToMinor(amount),currency,idempotencyKey:globalThis.crypto.randomUUID()});}
   else if(kind==='suspend')await client.suspend(actionOtp,selectedCompany);
   else await client.resume(actionOtp,selectedCompany);
   setActionOtp('');setPaymentRef('');setAmount('');await load();setMessage(kind==='activate'?'تم تفعيل الاشتراك.':kind==='renew'?'تم تجديد الاشتراك.':kind==='suspend'?'تم إيقاف الاشتراك.':'تم استئناف الاشتراك.');
  }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}
 }
 async function backupAction(kind:'create'|'verify'|'pin'|'preflight'|'restore',id?:string){
  setBusy(true);setError(null);setMessage(null);
  try{
   if(backupOtp.length!==6)throw new Error('أدخل رمز MFA');
   if(kind==='create')await client.createBackup(backupOtp,true);
   else{if(!id)throw new Error('اختر نسخة احتياطية');if(kind==='verify')await client.verifyBackup(backupOtp,id);else if(kind==='pin')await client.pinBackup(backupOtp,id,true);else if(kind==='preflight')await client.preflightBackup(backupOtp,id);else{const result=await client.restoreBackup(backupOtp,id);setRestoreId(result.id);}}
   setBackupOtp('');await load();setMessage(kind==='create'?'تم إنشاء النسخة والتحقق منها.':kind==='restore'?'تم تنفيذ الاستعادة وإلغاء الجلسات القديمة.':kind==='preflight'?'نجح فحص الاستعادة.':'تم تحديث النسخة الاحتياطية.');
  }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}
 }
 async function platformAction(active:boolean){
  if(!selectedCompany)return;setBusy(true);setError(null);setMessage(null);
  try{if(active)await client.platformResume(actionOtp,selectedCompany);else await client.platformSuspend(actionOtp,selectedCompany);setActionOtp('');await load();setMessage(active?'تمت إعادة التفعيل الإداري للشركة.':'تم الإيقاف الأمني للشركة وإلغاء جلساتها الحالية.');}
  catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}
 }
 if(!authenticated)return <main className="owner-login-shell" dir="rtl">
  {setupMode?<form className="owner-login-card" onSubmit={enroll}><div className="owner-brand">ELHAFEZ TECHNOLOGY</div><h1>تهيئة مالك المنصة لأول مرة</h1><p>تعمل هذه الخطوة مرة واحدة فقط. استخدم Bootstrap Token الموجود في إعدادات السيرفر.</p><label>Bootstrap Token<input type="password" autoComplete="off" minLength={32} required value={bootstrapToken} onChange={e=>setBootstrapToken(e.target.value)}/></label><label>البريد الإلكتروني<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>كلمة مرور المالك<input type="password" autoComplete="new-password" minLength={16} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="owner-error" role="alert">{error}</div>}{enrollment?<div className="owner-enrollment" role="status"><strong>أضف هذا الحساب إلى تطبيق المصادقة الآن</strong><code>{enrollment.mfaSecret}</code><small>{enrollment.otpauthUri}</small><p>هذه البيانات تظهر في الذاكرة الحالية فقط. بعد إضافتها للمصادقة احذف Bootstrap Token من إعدادات السيرفر.</p></div>:<button type="submit" disabled={busy}>{busy?'جارٍ التهيئة…':'إنشاء حساب المالك'}</button>}<button type="button" className="secondary" onClick={()=>{setSetupMode(false);setEnrollment(null);setError(null);}}>العودة لتسجيل الدخول</button></form>
  :<form className="owner-login-card" onSubmit={login}><div className="owner-brand">ELHAFEZ TECHNOLOGY</div><h1>مركز تحكم مالك المنصة</h1><p>دخول منفصل عن حسابات الشركات. كلمة المرور ورمز التحقق مطلوبان معًا.</p><label>البريد الإلكتروني<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>كلمة المرور<input type="password" autoComplete="current-password" minLength={16} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>رمز المصادقة الثنائية<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={loginOtp} onChange={e=>setLoginOtp(e.target.value.replace(/\D/g,''))}/></label>{error&&<div className="owner-error" role="alert">{error}</div>}<button type="submit" disabled={busy}>{busy?'جارٍ التحقق…':'دخول آمن'}</button><button type="button" className="secondary" onClick={()=>{setSetupMode(true);setError(null);}}>تهيئة المالك لأول مرة</button></form>}
 </main>;
 return <main className="owner-app" dir="rtl">
  <header className="owner-topbar"><div><span className="owner-brand">ELHAFEZ TECHNOLOGY</span><h1>Owner Control Center</h1><p>الاشتراكات والتشغيل التجاري للشركات</p>{preview&&<span className="owner-preview-badge">وضع المعاينة — بيانات تجريبية</span>}</div><button className="secondary" onClick={()=>void logout()} disabled={busy}>تسجيل الخروج</button></header>
  {error&&<div className="owner-error" role="alert">{error}</div>}{message&&<div className="owner-success" role="status">{message}</div>}
  <section className="owner-metrics"><article><span>الشركات</span><strong>{companies.length}</strong></article><article><span>اشتراكات فعالة</span><strong>{companies.filter(v=>v.allowed&&v.mode==='SUBSCRIPTION').length}</strong></article><article><span>منتهية / متوقفة</span><strong>{companies.filter(v=>v.mode==='SUBSCRIPTION'&&!v.allowed).length}</strong></article><article><span>بيئات داخلية</span><strong>{companies.filter(v=>v.mode==='INTERNAL').length}</strong></article></section>
  <section className="owner-panel"><div className="owner-section-heading"><div><h2>الشركات والاشتراكات</h2><p>حالة الاشتراك محسوبة من السيرفر، وليست من جهاز العميل.</p></div><button className="secondary" onClick={()=>void load()} disabled={busy}>تحديث</button></div>
   <div className="owner-table-wrap"><table><thead><tr><th>الشركة</th><th>Company Code</th><th>الاشتراك</th><th>تشغيل المنصة</th><th>الباقة</th><th>ينتهي في</th></tr></thead><tbody>{companies.map(value=><tr key={value.company.id} className={value.company.id===selectedCompany?'selected':''} onClick={()=>setSelectedCompany(value.company.id)}><td><strong>{value.company.name}</strong><small>{value.company.id}</small></td><td>{value.companyCode??'—'}</td><td><span className={'owner-status '+(value.allowed?'ok':'blocked')}>{value.mode==='INTERNAL'?'داخلي':value.status}</span></td><td><span className={'owner-status '+(value.company.active?'ok':'blocked')}>{value.company.active?'مفعلة':'موقوفة أمنيًا'}</span></td><td>{plans.find(p=>p.id===value.planId)?.name??'—'}</td><td>{value.currentPeriodEnd?new Date(value.currentPeriodEnd).toLocaleDateString('ar-EG'):'—'}</td></tr>)}</tbody></table></div>
  </section>
  <form className="owner-panel" onSubmit={createCompany}><div className="owner-section-heading"><div><h2>إضافة شركة عميلة</h2><p>يتم إنشاء الشركة مقفولة تجاريًا أولًا؛ لا تعمل قبل تفعيل اشتراكها من هذه اللوحة.</p></div></div><div className="owner-three"><label>اسم الشركة<input required value={companyName} onChange={e=>setCompanyName(e.target.value)}/></label><label>بريد المدير<input type="email" required value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/></label><label>اسم المدير<input required value={adminName} onChange={e=>setAdminName(e.target.value)}/></label></div><div className="owner-provision-row"><label>رمز MFA الخاص بك<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={companyOtp} onChange={e=>setCompanyOtp(e.target.value.replace(/\D/g,''))}/></label><button type="submit" disabled={busy||companyOtp.length!==6}>إنشاء الشركة</button></div><p className="owner-note">كلمة مرور مؤقتة قوية تتولد على السيرفر ولا تظهر لك أو للعميل. المدير يحدد كلمة مروره من مسار الاستعادة الآمن.</p></form>
  <section className="owner-panel"><div className="owner-section-heading"><div><h2>النسخ الاحتياطي والاستعادة</h2><p>نسخ PostgreSQL على مستوى المنصة بالكامل. الاستعادة إجراء حساس وتلغي الجلسات النشطة بعد نجاحها.</p></div><span className={'owner-status '+(ops?.backupProvider==='AVAILABLE'?'ok':'blocked')}>{ops?.backupProvider==='AVAILABLE'?'مزود النسخ متاح':'مزود النسخ غير متاح'}</span></div>
   <div className="owner-provision-row"><label>رمز MFA<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={backupOtp} onChange={e=>setBackupOtp(e.target.value.replace(/\D/g,''))}/></label><button type="button" onClick={()=>void backupAction('create')} disabled={busy||backupOtp.length!==6||ops?.backupProvider!=='AVAILABLE'}>إنشاء نسخة موثقة</button></div>
   <div className="owner-table-wrap"><table><thead><tr><th>التاريخ</th><th>الحالة</th><th>المرجع</th><th>مثبتة</th><th>الإجراءات</th></tr></thead><tbody>{backups.map(value=><tr key={value.id}><td>{new Date(value.createdAt).toLocaleString('ar-EG')}</td><td><span className={'owner-status '+(value.status==='VERIFIED'?'ok':'blocked')}>{value.status}</span></td><td>{value.providerRef??'—'}</td><td>{value.pinned?'نعم':'لا'}</td><td><div className="owner-actions"><button type="button" className="secondary" onClick={()=>void backupAction('verify',value.id)} disabled={busy||backupOtp.length!==6}>تحقق</button><button type="button" className="secondary" onClick={()=>void backupAction('preflight',value.id)} disabled={busy||backupOtp.length!==6||value.status!=='VERIFIED'}>فحص الاستعادة</button><button type="button" className="danger" onClick={()=>void backupAction('restore',value.id)} disabled={busy||backupOtp.length!==6||value.status!=='VERIFIED'}>استعادة</button></div></td></tr>)}</tbody></table></div>
   {restoreId?<p className="owner-note">آخر عملية استعادة: {restoreId}</p>:null}<p className="owner-note">قاعدة البيانات: {ops?.database??'—'} — Node: {ops?.runtimeVersion??'—'}</p>
  </section>
  <div className="owner-grid">
   <section className="owner-panel"><h2>إدارة اشتراك الشركة</h2><label>الشركة<select value={selectedCompany} onChange={e=>setSelectedCompany(e.target.value)}>{companies.map(v=><option key={v.company.id} value={v.company.id}>{v.company.name}</option>)}</select></label><label>الباقة<select value={selectedPlan} onChange={e=>setSelectedPlan(e.target.value)}>{plans.map(v=><option key={v.id} value={v.id}>{v.name} — {formatMinor(v.priceMinor,v.currency)}</option>)}</select></label><div className="owner-two"><label>عدد الشهور<input inputMode="numeric" value={months} onChange={e=>setMonths(e.target.value.replace(/\D/g,''))}/></label><label>العملة<input maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label></div><label>مرجع الدفع<input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder="تحويل بنكي / إيصال"/></label><label>المبلغ<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="12800.00"/></label><label>رمز MFA الخاص بك<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={actionOtp} onChange={e=>setActionOtp(e.target.value.replace(/\D/g,''))}/></label><div className="owner-actions"><button onClick={()=>void subscriptionAction(selected?.subscriptionId?'renew':'activate')} disabled={busy||!actionOtp}>{selected?.subscriptionId?'تجديد الاشتراك':'تفعيل الاشتراك'}</button><button className="danger" onClick={()=>void subscriptionAction('suspend')} disabled={busy||!selected?.subscriptionId||!actionOtp}>إيقاف الاشتراك</button><button className="secondary" onClick={()=>void subscriptionAction('resume')} disabled={busy||!selected?.subscriptionId||!actionOtp}>استئناف الاشتراك</button></div><div className="owner-security-actions"><strong>التحكم الأمني في الشركة</strong><p className="owner-note">مستقل عن الدفع. الإيقاف الأمني يعطل الشركة ويلغي جلساتها حتى لو كان الاشتراك مدفوعًا.</p><div className="owner-actions">{selected?.company.active?<button className="danger" type="button" onClick={()=>void platformAction(false)} disabled={busy||!actionOtp}>إيقاف أمني للشركة</button>:<button type="button" onClick={()=>void platformAction(true)} disabled={busy||!actionOtp}>إعادة التفعيل الإداري</button>}</div></div><p className="owner-note">كل عملية حساسة تحتاج رمز MFA جديد، ولا يتم حفظ الرمز أو Session المالك في Local Storage.</p></section>
   <form className="owner-panel" onSubmit={createPlan}><h2>إنشاء باقة</h2><label>كود الباقة<input required value={planCode} onChange={e=>setPlanCode(e.target.value.toUpperCase())}/></label><label>اسم الباقة<input required value={planName} onChange={e=>setPlanName(e.target.value)}/></label><label>السعر لكل شهر<input inputMode="decimal" required value={planPrice} onChange={e=>setPlanPrice(e.target.value)} placeholder="12800.00"/></label><label>العملة<input required maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>رمز MFA<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={planOtp} onChange={e=>setPlanOtp(e.target.value.replace(/\D/g,''))}/></label><button type="submit" disabled={busy}>حفظ الباقة</button><p className="owner-note">الباقات الحالية تبدأ بصلاحية جميع الأقسام. يمكن لاحقًا تقييد الأقسام عبر Entitlements بدون تغيير بنية الاشتراك.</p></form>
  </div>
 </main>;
}
