import assert from'node:assert/strict';
import test from'node:test';
import type{CustomFieldsAccess}from'./application/custom-fields.access.js';
import{CustomFieldsApplicationService}from'./application/custom-fields.application-service.js';
import{InMemoryCustomFieldsRepository}from'./infrastructure/in-memory-custom-fields.repository.js';

class Access implements CustomFieldsAccess{deny='';audits:string[]=[];async requirePermission(_context:{companyId:string;actorId:string},permission:string){if(permission===this.deny)throw new Error('permission denied');}async auditOnce(_context:{companyId:string;actorId:string},key:string){this.audits.push(key);}}
const context={companyId:'company-a',actorId:'actor-a'};
function setup(){let id=0;const repo=new InMemoryCustomFieldsRepository(),access=new Access(),service=new CustomFieldsApplicationService(repo,access,()=>new Date('2026-09-27T18:00:00Z'),()=>('id-'+(++id)));return{repo,access,service};}

test('definition keys are scoped by company and entity type',async()=>{const s=setup();const first=await s.service.createDefinition(context,{entityType:'customer',key:'vip_level',label:'مستوى العميل',fieldType:'SELECT',options:['VIP','STANDARD']});assert.equal(first.key,'vip_level');await assert.rejects(()=>s.service.createDefinition(context,{entityType:'customer',key:'vip_level',label:'آخر',fieldType:'TEXT'}),/already exists/);const other=await s.service.createDefinition({...context,companyId:'company-b'},{entityType:'customer',key:'vip_level',label:'آخر',fieldType:'TEXT'});assert.notEqual(other.id,first.id);});
test('values are validated against the canonical definition',async()=>{const s=setup();const select=await s.service.createDefinition(context,{entityType:'customer',key:'segment',label:'الشريحة',fieldType:'SELECT',required:true,options:['VIP','RETAIL']});await assert.rejects(()=>s.service.setValue(context,select.id,'customer-1','OTHER'),/configured options/);const stored=await s.service.setValue(context,select.id,'customer-1','VIP');assert.equal(stored.value,'VIP');assert.equal((await s.service.listEntityValues(context,'customer','customer-1')).length,1);await assert.rejects(()=>s.service.clearValue(context,select.id,'customer-1'),/required/);});
test('optional values can be cleared and inactive definitions reject writes',async()=>{const s=setup();const field=await s.service.createDefinition(context,{entityType:'booking',key:'internal_note',label:'ملاحظة',fieldType:'TEXT'});await s.service.setValue(context,field.id,'booking-1','x');await s.service.clearValue(context,field.id,'booking-1');assert.equal((await s.service.listEntityValues(context,'booking','booking-1')).length,0);await s.service.updateDefinition(context,field.id,{active:false});await assert.rejects(()=>s.service.setValue(context,field.id,'booking-1','y'),/inactive/);});
test('company isolation and permissions fail closed',async()=>{const s=setup();const field=await s.service.createDefinition(context,{entityType:'customer',key:'note',label:'ملاحظة',fieldType:'TEXT'});assert.equal((await s.service.listDefinitions({...context,companyId:'company-b'})).length,0);await assert.rejects(()=>s.service.setValue({...context,companyId:'company-b'},field.id,'customer-1','x'),/not found/);s.access.deny='platform.custom_fields.manage';await assert.rejects(()=>s.service.createDefinition(context,{entityType:'customer',key:'blocked',label:'محظور',fieldType:'TEXT'}),/permission denied/);});
