import test from'node:test';import assert from'node:assert/strict';import{executionContext,type ExecutionContext}from'@elhafez/contracts';import{QuotationsApplicationService,QUOTATION_PERMISSIONS}from'./application/quotations.application-service.js';import type{QuotationBillingPort,QuotationCustomerPort,QuotationLeadPort}from'./application/quotations-dependencies.port.js';import type{QuotationsAccess}from'./application/quotations-access.js';import type{Quotation}from'./domain/quotation.js';import{InMemoryQuotationsRepository}from'./infrastructure/in-memory-quotations.repository.js';
const c=executionContext('company-1','branch-1','actor-1');
class Access implements QuotationsAccess{denied:string|null=null;seen:string[]=[];async requireBranch(x:ExecutionContext){if(x.companyId!=='company-1'||x.branchId!=='branch-1')throw Error('branch denied');}async requirePermission(_c:ExecutionContext,p:string){this.seen.push(p);if(this.denied===p)throw Error('permission denied');}async audit(){}}
class Leads implements QuotationLeadPort{status='QUALIFIED';quotationReference:string|null=null;convertedCustomerId:string|null=null;marked:string[]=[];failConvertOnce=false;result:{status:string;customerId?:string}={status:'CONVERTED',customerId:'customer-lead'};async get(){return{id:'lead-1',status:this.status,displayName:'Lead Name',phone:'010',whatsappNumber:'+201001234567',email:'lead@test',convertedCustomerId:this.convertedCustomerId,quotationReference:this.quotationReference};}async markQuoted(_c:ExecutionContext,_id:string,r:string){if(this.status==='QUALIFIED'){this.status='QUOTED';this.quotationReference=r;}else if(this.status==='QUOTED'&&this.quotationReference!==r)throw Error('different quotation reference');this.marked.push(r);}async convertCustomer(){if(this.failConvertOnce){this.failConvertOnce=false;throw Error('transient customer conversion failure');}if(this.result.customerId){this.convertedCustomerId=this.result.customerId;this.status='WON';}return this.result;}}
class Customers implements QuotationCustomerPort{active=true;registered:string[]=[];async requireActive(_c:ExecutionContext,id:string){if(!this.active)throw Error('customer suspended');return{id};}async getSnapshot(){return{displayName:'عميل مباشر',phone:'+201001234567',email:'c@test'};}async register(_c:ExecutionContext,_id:string,q:string){this.registered.push(q);}}
class Billing implements QuotationBillingPort{calls=0;fail=false;async createAndPost(v:Parameters<QuotationBillingPort['createAndPost']>[0]){this.calls++;if(this.fail)throw Error('billing down');return{id:v.id};}}
function fixture(){const repo=new InMemoryQuotationsRepository(),leads=new Leads(),customers=new Customers(),billing=new Billing(),access=new Access();let n=0;const service=new QuotationsApplicationService(repo,leads,customers,billing,access,()=>new Date('2026-09-20T12:00:00Z'),()=>`id-${++n}`);return{service,repo,leads,customers,billing,access};}
const input={customerId:'customer-1',currency:'EGP',validityDate:'2026-09-30',lines:[{id:'line-1',description:'خدمة',quantity:'2.5',unitPrice:'10.20',discount:'0'}]};
test('direct customer quotation validates, snapshots, totals exactly and numbers stably',async()=>{const f=fixture(),a=await f.service.create(c,input),b=await f.service.create(c,input);assert.equal(a.quotation.number,'QUO-000001');assert.equal(b.quotation.number,'QUO-000002');assert.equal(a.quotation.revisions[0]?.subtotal,'25.5');assert.equal(a.quotation.revisions[0]?.total,'25.5');assert.equal(a.quotation.customerSnapshot.displayName,'عميل مباشر');assert.deepEqual(f.customers.registered,[a.quotation.id,b.quotation.id]);});
test('company, branch and permission isolation are enforced',async()=>{const f=fixture();await assert.rejects(()=>f.service.list(executionContext('other','branch-1','actor-1')),/branch denied/);await assert.rejects(()=>f.service.list(executionContext('company-1','other','actor-1')),/branch denied/);f.access.denied=QUOTATION_PERMISSIONS.manage;await assert.rejects(()=>f.service.create(c,input),/permission denied/);assert.ok(f.access.seen.includes(QUOTATION_PERMISSIONS.manage));});
test('lead origin validates eligibility, marks quoted and resolves customer',async()=>{const f=fixture(),r=await f.service.create(c,{...input,customerId:undefined,sourceLeadId:'lead-1'});assert.equal(r.customerResolution,'RESOLVED');assert.equal(r.quotation.customerId,'customer-lead');assert.deepEqual(f.leads.marked,[r.quotation.id]);assert.equal(r.quotation.sourceLeadId,'lead-1');});
test('invalid lead state is rejected before persistence',async()=>{const f=fixture();f.leads.status='NEW';await assert.rejects(()=>f.service.create(c,{...input,customerId:undefined,sourceLeadId:'lead-1'}),/QUALIFIED/);assert.equal(f.repo.values.size,0);});
test('duplicate or suspended customer review keeps lead quotation unresolved',async()=>{for(const status of['REVIEW_REQUIRED','SUSPENDED'] as const){const f=fixture();f.leads.result={status};const r=await f.service.create(c,{...input,customerId:undefined,sourceLeadId:'lead-1'});assert.equal(r.customerResolution,'REVIEW_REQUIRED');assert.equal(r.quotation.customerId,null);assert.equal(f.repo.values.size,1);}});
test('invalid quantities, prices and discounts are rejected without floating point',async()=>{for(const line of[{description:'x',quantity:'-1',unitPrice:'1'},{description:'x',quantity:'0',unitPrice:'1'},{description:'x',quantity:'1',unitPrice:'-1'},{description:'x',quantity:'1',unitPrice:'2',discount:'3'},{description:'x',quantity:'1.0000001',unitPrice:'2'}]){const f=fixture();await assert.rejects(()=>f.service.create(c,{...input,lines:[line]}));}});
test('draft edit stays revision one; edit after send preserves immutable sent revision',async()=>{const f=fixture();let q=(await f.service.create(c,input)).quotation;q=await f.service.edit(c,q.id,{validityDate:'2026-10-01',lines:[{id:'line-1',description:'تعديل',quantity:'1',unitPrice:'9'}]});assert.equal(q.revisions.length,1);q=await f.service.send(c,q.id);const sent=q.revisions[0];q=await f.service.edit(c,q.id,{validityDate:'2026-10-02',lines:[{id:'line-1',description:'جديد',quantity:'1',unitPrice:'8'}]});assert.equal(q.status,'DRAFT');assert.equal(q.revisions.length,2);assert.deepEqual(q.revisions[0],sent);assert.equal(q.revisions[1]?.number,2);});
test('positive discount requires server-side approval even when the caller clears the flag',async()=>{const f=fixture();const q=(await f.service.create(c,{...input,lines:[{...input.lines[0]!,discount:'0.50',discountRequiresApproval:false}]})).quotation;assert.equal(q.approvalStatus,'PENDING');assert.equal(q.revisions[0]?.lines[0]?.discountRequiresApproval,true);await assert.rejects(()=>f.service.send(c,q.id),/approval/);});
test('lead quotation creation resumes the same persisted quotation after a partial integration failure',async()=>{const f=fixture();f.leads.failConvertOnce=true;const leadInput={...input,customerId:undefined,sourceLeadId:'lead-1'};await assert.rejects(()=>f.service.create(c,leadInput),/transient customer conversion failure/);assert.equal(f.repo.values.size,1);const first=[...f.repo.values.values()][0]!;assert.equal(f.leads.quotationReference,first.id);const retried=await f.service.create(c,leadInput);assert.equal(f.repo.values.size,1);assert.equal(retried.quotation.id,first.id);assert.equal(retried.quotation.customerId,'customer-lead');assert.equal(retried.customerResolution,'RESOLVED');});
test('commercial overrides require dedicated approval and evidence before send',async()=>{const f=fixture();let q=(await f.service.create(c,{...input,lines:[{...input.lines[0]!,manualPriceOverride:true}]})).quotation;assert.equal(q.approvalStatus,'PENDING');await assert.rejects(()=>f.service.send(c,q.id),/approval/);q=await f.service.decideApproval(c,q.id,true,'مدير المبيعات');assert.equal(q.approvalActorId,'actor-1');assert.equal(q.approvalReason,'مدير المبيعات');assert.ok(f.access.seen.includes(QUOTATION_PERMISSIONS.approve));assert.equal((await f.service.send(c,q.id)).status,'SENT');});
test('rejection needs reason and acceptance pins the exact sent revision',async()=>{const f=fixture();let q=(await f.service.create(c,input)).quotation;q=await f.service.send(c,q.id);await assert.rejects(()=>f.service.reject(c,q.id,' '),/required/);const rejected=await f.service.reject(c,q.id,'السعر');assert.equal(rejected.rejectedRevisionId,q.currentRevisionId);const g=fixture();let accepted=(await g.service.create(c,input)).quotation;accepted=await g.service.send(c,accepted.id);accepted=await g.service.accept(c,accepted.id);assert.equal(accepted.acceptedRevisionId,accepted.currentRevisionId);await assert.rejects(()=>g.service.edit(c,accepted.id,{validityDate:'2026-10-01',lines:input.lines}),/cannot be edited/);});
test('invalid transitions and deterministic expiry are blocked or recorded',async()=>{const f=fixture();let q=(await f.service.create(c,{...input,validityDate:'2026-09-19'})).quotation;await assert.rejects(()=>f.service.accept(c,q.id),/sent/);q=await f.service.expire(c,q.id,new Date('2026-09-20T00:00:00Z'));assert.equal(q.status,'EXPIRED');const g=fixture(),future=(await g.service.create(c,input)).quotation;await assert.rejects(()=>g.service.expire(c,future.id),/has not expired/);});
test('Billing conversion requires acceptance and active resolved customer',async()=>{const f=fixture(),q=(await f.service.create(c,input)).quotation;await assert.rejects(()=>f.service.convert(c,q.id,{invoiceId:'i',invoiceNumber:'INV',postingDate:'2026-09-20',controlAccountId:'ar',lines:[{quotationLineId:'line-1',accountId:'rev'}]}),/accepted/);let accepted:Quotation=await f.service.send(c,q.id);accepted=await f.service.accept(c,accepted.id);f.customers.active=false;await assert.rejects(()=>f.service.convert(c,accepted.id,{invoiceId:'i',invoiceNumber:'INV',postingDate:'2026-09-20',controlAccountId:'ar',lines:[{quotationLineId:'line-1',accountId:'rev'}]}),/suspended/);});
test('Billing success is idempotent and failure leaves quotation accepted',async()=>{const f=fixture();let q:Quotation=(await f.service.create(c,input)).quotation;q=await f.service.send(c,q.id);q=await f.service.accept(c,q.id);const command={invoiceId:'invoice-1',invoiceNumber:'INV-1',postingDate:'2026-09-20',controlAccountId:'ar',lines:[{quotationLineId:'line-1',accountId:'revenue'}]};f.billing.fail=true;await assert.rejects(()=>f.service.convert(c,q.id,command),/billing down/);assert.equal((await f.service.get(c,q.id)).status,'ACCEPTED');f.billing.fail=false;q=await f.service.convert(c,q.id,command);assert.equal(q.billingInvoiceId,'invoice-1');const again=await f.service.convert(c,q.id,command);assert.equal(again.billingInvoiceId,'invoice-1');assert.equal(f.billing.calls,2);});
test('quotation communication evidence is append-only, revision-pinned and server-owned',async()=>{const f=fixture();let q=(await f.service.create(c,input)).quotation;const pdf=await f.service.recordCommunication(c,q.id,{channel:'PDF',revisionId:q.currentRevisionId});assert.equal(pdf.outcome,'EXPORT_INITIATED');assert.equal(pdf.revisionId,q.currentRevisionId);await assert.rejects(()=>f.service.recordCommunication(c,q.id,{channel:'WHATSAPP'}),/sent quotation revision/);q=await f.service.send(c,q.id);const wa=await f.service.recordCommunication(c,q.id,{channel:'WHATSAPP',recipientSnapshot:'+20 100-123-4567'});assert.equal(wa.outcome,'HANDOFF_INITIATED');assert.equal(wa.recipientSnapshot,'201001234567');const history=await f.service.communications(c,q.id);assert.deepEqual(history.map(x=>x.channel),['PDF','WHATSAPP']);assert.ok(history.every(x=>x.actorId==='actor-1'));});
test('communication permission and recipient validation are enforced',async()=>{const f=fixture();let q=(await f.service.create(c,input)).quotation;q=await f.service.send(c,q.id);f.access.denied=QUOTATION_PERMISSIONS.communicate;await assert.rejects(()=>f.service.recordCommunication(c,q.id,{channel:'PRINT'}),/permission denied/);f.access.denied=null;await assert.rejects(()=>f.service.recordCommunication(c,q.id,{channel:'WHATSAPP',recipientSnapshot:'12'}),/WhatsApp number/);});
