import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import type{ManifestAssignment,TransportHistory,TransportRun}from'../domain/transport.js';import type{TransportRepository}from'./transport.repository.js';import type{TransportAccess,TransportBookingPort,TransportInventoryPort,TransportTravelerPort}from'./transport.ports.js';
export const TRANSPORT_PERMISSIONS=Object.freeze({view:'hajj_umrah.transport.view',manage:'hajj_umrah.transport.manage',dispatch:'hajj_umrah.transport.dispatch'});
export interface CreateTransportRunInput{programId:string;allocationId:string;code:string;route:string;startsAt:string;endsAt:string;vehicleReference?:string;driverReference?:string;}
const req=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x;};const iso=(v:string,f:string)=>{const x=req(v,f),d=new Date(x);if(Number.isNaN(d.valueOf()))throw new ContractValidationError(f,'must be an ISO datetime');return d.toISOString();};
export class HajjUmrahTransportOperationsApplicationService{
 constructor(private readonly repo:TransportRepository,private readonly access:TransportAccess,private readonly bookings:TransportBookingPort,private readonly travelers:TransportTravelerPort,private readonly inventory:TransportInventoryPort,private readonly now:()=>Date=()=>new Date(),private readonly id:()=>string=()=>randomUUID()){}
 private async perm(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p)}private hist(c:ExecutionContext,type:'RUN'|'MANIFEST',id:string,action:string,evidence?:unknown):TransportHistory{return{id:this.id(),companyId:c.companyId,branchId:c.branchId,aggregateType:type,aggregateId:id,action,...(evidence===undefined?{}:{evidence}),actorId:c.actorId,occurredAt:this.now().toISOString()}}private async run(c:ExecutionContext,id:string){const v=await this.repo.getRun(c.companyId,c.branchId,id);if(!v)throw new ContractValidationError('runId','transport run not found');return v}
 private async allocation(c:ExecutionContext,id:string,programId:string,start:string,end:string){const a=await this.inventory.allocation(c.companyId,req(id,'allocationId'));if(!a||a.resourceType!=='TRANSPORT'||a.program.sourceId!==programId||!['CONFIRMED','PARTIALLY_RELEASED','CONSUMED'].includes(a.status))throw new ContractValidationError('allocationId','canonical TRANSPORT allocation evidence is required');const from=a.serviceDate.slice(0,10),to=(a.periodEnd??a.serviceDate).slice(0,10);if(start.slice(0,10)<from||end.slice(0,10)>to)throw new ContractValidationError('schedule','run is outside transport allocation window');return a}
 async createRun(c:ExecutionContext,input:CreateTransportRunInput){await this.perm(c,TRANSPORT_PERMISSIONS.manage);const start=iso(input.startsAt,'startsAt'),end=iso(input.endsAt,'endsAt');if(end<=start)throw new ContractValidationError('endsAt','must be after startsAt');await this.allocation(c,input.allocationId,req(input.programId,'programId'),start,end);const at=this.now().toISOString();const v:TransportRun={id:this.id(),companyId:c.companyId,branchId:c.branchId,programId:input.programId,allocationId:input.allocationId,code:req(input.code,'code'),route:req(input.route,'route'),startsAt:start,endsAt:end,...(input.vehicleReference?.trim()?{vehicleReference:input.vehicleReference.trim()}:{}),...(input.driverReference?.trim()?{driverReference:input.driverReference.trim()}:{}),status:'SCHEDULED',createdAt:at,updatedAt:at};return this.repo.createRun(v,this.hist(c,'RUN',v.id,'CREATED'))}
 async assignTraveler(c:ExecutionContext,runId:string,bookingId:string,travelerId:string){await this.perm(c,TRANSPORT_PERMISSIONS.manage);const run=await this.run(c,runId);if(run.status!=='SCHEDULED')throw new ContractValidationError('status','manifest can only change before dispatch');const booking=await this.bookings.requireTraveler(c,bookingId,travelerId);if(booking.programId!==run.programId)throw new ContractValidationError('bookingId','booking belongs to a different program');await this.travelers.requireActive(c,travelerId);const conflict=await this.repo.conflictingTraveler(c.companyId,c.branchId,travelerId,run.startsAt,run.endsAt,run.id);if(conflict)throw new ContractValidationError('travelerId','traveler already has a conflicting transport run');const a=await this.allocation(c,run.allocationId,run.programId,run.startsAt,run.endsAt);const capacity=Math.floor(Number(a.quantity));if(!Number.isFinite(capacity)||capacity<1)throw new ContractValidationError('allocationId','transport allocation has no usable capacity');if(await this.repo.activeManifestCount(c.companyId,c.branchId,run.id)>=capacity)throw new ContractValidationError('capacity','transport allocation capacity exceeded');const at=this.now().toISOString(),v:ManifestAssignment={id:this.id(),companyId:c.companyId,branchId:c.branchId,runId:run.id,bookingId,travelerId,status:'ASSIGNED',createdAt:at,updatedAt:at};return this.repo.assign(v,this.hist(c,'MANIFEST',v.id,'ASSIGNED',{runId:run.id,travelerId}))}
 async removeTraveler(c:ExecutionContext,assignmentId:string,runId:string){await this.perm(c,TRANSPORT_PERMISSIONS.manage);const run=await this.run(c,runId);if(run.status!=='SCHEDULED')throw new ContractValidationError('status','manifest can only change before dispatch');const row=(await this.repo.manifest(c.companyId,c.branchId,runId)).find(v=>v.id===assignmentId);if(!row)throw new ContractValidationError('assignmentId','manifest assignment not found');if(row.status==='REMOVED')return row;const next={...row,status:'REMOVED' as const,updatedAt:this.now().toISOString()};return this.repo.saveAssignment(next,this.hist(c,'MANIFEST',row.id,'REMOVED',{runId}))}
 async dispatch(c:ExecutionContext,id:string){await this.perm(c,TRANSPORT_PERMISSIONS.dispatch);const old=await this.run(c,id);if(old.status==='DISPATCHED')return old;if(old.status!=='SCHEDULED')throw new ContractValidationError('status','only scheduled run can dispatch');await this.allocation(c,old.allocationId,old.programId,old.startsAt,old.endsAt);const next={...old,status:'DISPATCHED' as const,updatedAt:this.now().toISOString()};const saved=await this.repo.saveRun(next,this.hist(c,'RUN',id,'DISPATCHED'));await this.access.audit(c,'hajj-umrah.transport.dispatched',id,{manifestCount:await this.repo.activeManifestCount(c.companyId,c.branchId,id)});return saved}
 async complete(c:ExecutionContext,id:string){await this.perm(c,TRANSPORT_PERMISSIONS.dispatch);const old=await this.run(c,id);if(old.status==='COMPLETED')return old;if(old.status!=='DISPATCHED')throw new ContractValidationError('status','only dispatched run can complete');const next={...old,status:'COMPLETED' as const,updatedAt:this.now().toISOString()};return this.repo.saveRun(next,this.hist(c,'RUN',id,'COMPLETED'))}
 async cancel(c:ExecutionContext,id:string,reason:string){await this.perm(c,TRANSPORT_PERMISSIONS.manage);const old=await this.run(c,id);if(old.status==='CANCELLED')return old;if(old.status!=='SCHEDULED')throw new ContractValidationError('status','dispatched run cannot be cancelled');const next={...old,status:'CANCELLED' as const,updatedAt:this.now().toISOString()};return this.repo.saveRun(next,this.hist(c,'RUN',id,'CANCELLED',{reason:req(reason,'reason')}))}
 async listRuns(c:ExecutionContext,p?:string){await this.perm(c,TRANSPORT_PERMISSIONS.view);return this.repo.listRuns(c.companyId,c.branchId,p)}async manifest(c:ExecutionContext,id:string){await this.perm(c,TRANSPORT_PERMISSIONS.view);await this.run(c,id);return this.repo.manifest(c.companyId,c.branchId,id)}async historyFor(c:ExecutionContext,type:'RUN'|'MANIFEST',id:string){await this.perm(c,TRANSPORT_PERMISSIONS.view);return this.repo.history(c.companyId,c.branchId,type,id)}
}
