import { createHash } from 'node:crypto';
import type { Prisma, PrismaClient } from '@prisma/client';
import type { HistoricalEquivalence, HistoricalImportRecord } from '../application/historical-import.application-service.js';
import type { HistoricalImportRepository } from '../application/historical-import.repository.js';
const s=(v:unknown,f='')=>typeof v==='string'&&v?v:f; const n=(v:unknown,f='0')=>typeof v==='string'&&/^-?\d+(?:\.\d+)?$/.test(v)?v:f; const d=(v:unknown)=>new Date(s(v,'1970-01-01')); const o=(v:unknown)=>typeof v==='string'&&v?v:undefined;
const add=(a:string,b:string)=>{const z=Math.max((a.split('.')[1]??'').length,(b.split('.')[1]??'').length),u=10n**BigInt(z),p=(v:string)=>{const q=v.startsWith('-'),[w='0',f='']=(q?v.slice(1):v).split('.'),x=BigInt(w)*u+BigInt(f.padEnd(z,'0'));return q?-x:x},x=p(a)+p(b),q=x<0n,y=q?-x:x,t=y.toString().padStart(z+1,'0');return `${q?'-':''}${z?`${t.slice(0,-z)}.${t.slice(-z)}`:t}`};
export class PrismaHistoricalImportRepository implements HistoricalImportRepository {
 constructor(private readonly db:PrismaClient){}
 async find(runId:string,collection:string,sourceId:string){const v=await this.db.procurementFinanceHistoricalImport.findUnique({where:{runId_collection_sourceId:{runId,collection,sourceId}}});return v?{...v,owner:'Procurement',payload:v.payload as Record<string,unknown>,branchId:v.branchId??undefined,debit:v.debit.toString(),credit:v.credit.toString(),amount:v.amount.toString()} as HistoricalImportRecord:undefined}
 async create(r:HistoricalImportRecord){await this.db.$transaction(async tx=>{await this.restore(tx,r);await tx.procurementFinanceHistoricalImport.create({data:{id:r.id,runId:r.runId,collection:r.collection,sourceId:r.sourceId,sourcePayloadHash:r.sourcePayloadHash,companyId:r.companyId,branchId:r.branchId,payload:r.payload as object,payloadJson:r.payloadJson,debit:r.debit,credit:r.credit,amount:r.amount}})})}
 private async restore(tx:Prisma.TransactionClient,r:HistoricalImportRecord){const p=r.payload,c=r.collection;
if(c==='supplierCommitments')await tx.procSupplierCommitment.create({data:{id:r.sourceId,companyId:r.companyId,supplierId:s(p.supplierId),sourceType:s(p.sourceType,'HISTORICAL'),sourceId:s(p.sourceId,r.sourceId),status:s(p.status,'ACTIVE'),effectiveDate:d(p.effectiveDate??p.date),cancelledAt:p.cancelledAt?d(p.cancelledAt):null,cancelReason:o(p.cancelReason),requestHash:r.sourcePayloadHash,createdAt:d(p.createdAt??p.date)}});else if(c==='purchaseOrders'){if(!r.branchId)throw new Error('historical purchase order requires authoritative branchId');await tx.procPurchaseOrder.create({data:{id:r.sourceId,companyId:r.companyId,branchId:r.branchId,commitmentId:o(p.commitmentId),supplierId:s(p.supplierId),number:s(p.number,r.sourceId),origin:s(p.origin,'HISTORICAL'),status:s(p.status,'OPEN'),orderDate:p.date?d(p.date):null,expectedDate:p.expectedDate?d(p.expectedDate):null,currency:o(p.currency),externalReference:o(p.externalRef),notes:o(p.notes),requestHash:r.sourcePayloadHash,createdAt:d(p.createdAt??p.date)}});const lines=Array.isArray(p.lines)?p.lines:[];if(lines.length)await tx.procPurchaseOrderLine.createMany({data:lines.map((raw,index)=>{const l=raw as Record<string,unknown>;return{id:s(l.id,`${r.sourceId}:line:${index+1}`),companyId:r.companyId,purchaseOrderId:r.sourceId,itemReference:s(l.itemReference,`line-${index+1}`),orderedQuantity:n(l.orderedQuantity??l.quantity),receivedQuantity:n(l.receivedQuantity),invoicedQuantity:n(l.invoicedQuantity)}})})}else throw new Error(`unsupported Procurement historical collection ${c}`)}
 async equivalence(runId:string,companyId:string):Promise<HistoricalEquivalence>{const provenance=await this.db.procurementFinanceHistoricalImport.findMany({where:{runId,companyId},orderBy:[{collection:'asc'},{sourceId:'asc'}]});const ids=(c:string)=>provenance.filter(x=>x.collection===c).map(x=>x.sourceId);const [commitments,orders]=await Promise.all([this.db.procSupplierCommitment.findMany({where:{companyId,id:{in:ids('supplierCommitments')}}}),this.db.procPurchaseOrder.findMany({where:{companyId,id:{in:ids('purchaseOrders')}}})]);const rows=[...commitments.map(x=>({value:x,amount:'0'})),...orders.map(x=>({value:x,amount:'0'}))];return{records:String(rows.length),payloadDigest:createHash('sha256').update(rows.map(x=>JSON.stringify(x,(_,v)=>typeof v==='object'&&v?.constructor?.name==='Decimal'?v.toString():v)).join('\n')).digest('hex'),debit: "0", credit: "0", amount:rows.reduce((a,x)=>add(a,x.amount),'0')}}
}
