import test from 'node:test';
import assert from 'node:assert/strict';
import { FinancialControlsApplicationService, type TrustedAuthorizationPort } from './application/financial-controls.application-service.js';
import { InMemoryFinancialControlsRepository } from './infrastructure/in-memory-financial-controls.repository.js';

class Authorization implements TrustedAuthorizationPort { async canApprove(actor: string) { return actor === 'approver'; } async canAccessBranch(actor: string, _company: string, branch: string) { return actor === 'regional' && branch === 'branch-2'; } }
function fixture() { const repository = new InMemoryFinancialControlsRepository(); return { repository, service: new FinancialControlsApplicationService(repository, new Authorization()) }; }
async function policyAndRequest() { const f = fixture(); await f.service.configureApprovalPolicy({ id: 'policy-1', companyId: 'company-1', action: 'PAYMENT', threshold: '100', active: true, forbidSelfApproval: true, requiredAuthority: 'approve.payment' }); const request = await f.service.requestApproval({ id: 'request-1', companyId: 'company-1', branchId: 'branch-1', action: 'PAYMENT', sourceType: 'PAYMENT', sourceId: 'external-1', requesterActorId: 'requester', amount: '100', requestedAt: '2026-09-18T00:00:00.000Z' }); return { ...f, request }; }

test('BR-031 uses inclusive exact threshold for PAYMENT and PAID_EXPENSE', async () => { const { service } = fixture(); for (const action of ['PAYMENT', 'PAID_EXPENSE'] as const) await service.configureApprovalPolicy({ id: `p-${action}`, companyId: 'c', action, threshold: '100.000000000000000001', active: true, forbidSelfApproval: true, requiredAuthority: 'approve' }); assert.equal((await service.evaluateApprovalRequirement({ companyId: 'c', action: 'PAYMENT', amount: '100' })).decision, 'APPROVAL_NOT_REQUIRED'); assert.equal((await service.evaluateApprovalRequirement({ companyId: 'c', action: 'PAYMENT', amount: '100.000000000000000001' })).decision, 'APPROVAL_REQUIRED'); assert.equal((await service.evaluateApprovalRequirement({ companyId: 'c', action: 'PAID_EXPENSE', amount: '100.000000000000000002' })).decision, 'APPROVAL_REQUIRED'); });
test('BR-030 rejects self approval without decision and accepts authorized other actor', async () => { const { service, repository } = await policyAndRequest(); await assert.rejects(service.decideApproval({ companyId: 'company-1', requestId: 'request-1', decisionId: 'd-self', actorId: 'requester', outcome: 'APPROVED' }), /self approval/); assert.equal(await service.getApprovalDecision('company-1', 'request-1'), undefined); assert.equal(repository.requests.get('company-1:request-1')?.status, 'PENDING'); const decision = await service.decideApproval({ companyId: 'company-1', requestId: 'request-1', decisionId: 'd-1', actorId: 'approver', outcome: 'APPROVED', decidedAt: '2026-09-18T01:00:00.000Z' }); assert.equal(decision.outcome, 'APPROVED'); });
test('final decision replay is idempotent and conflicting decision is rejected', async () => { const { service, repository } = await policyAndRequest(); const command = { companyId: 'company-1', requestId: 'request-1', decisionId: 'd-1', actorId: 'approver', outcome: 'APPROVED' as const, reason: 'reviewed' }; await service.decideApproval(command); await service.decideApproval({ ...command, decisionId: 'ignored-replay' }); assert.equal(repository.decisions.size, 1); await assert.rejects(service.decideApproval({ ...command, outcome: 'REJECTED' }), /conflicting/); });

test('BR-072/073/074 mutation guard enforces scope and permanence without mutating source', async () => { const { service } = fixture(); const base = { executionCompanyId: 'c', executionBranchId: 'b1', actorId: 'actor', sourceReference: 'opaque:1', targetCompanyId: 'c', targetBranchId: 'b1', lifecycle: 'PERMANENT' as const, collection: false };
  assert.deepEqual((await service.evaluateFinancialMutation({ ...base, lifecycle: 'DRAFT', mutation: 'UPDATE' })).decision, 'ALLOWED');
  assert.equal((await service.evaluateFinancialMutation({ ...base, mutation: 'UPDATE' })).reason, 'PERMANENT_FINANCIAL_RECORD_IMMUTABLE'); assert.equal((await service.evaluateFinancialMutation({ ...base, mutation: 'DELETE' })).decision, 'DENIED'); assert.equal((await service.evaluateFinancialMutation({ ...base, mutation: 'REVERSE' })).decision, 'ALLOWED');
  assert.equal((await service.evaluateFinancialMutation({ ...base, collection: true, mutation: 'DELETE' })).reason, 'PERMANENT_COLLECTION_DELETE_DENIED'); assert.equal((await service.evaluateFinancialMutation({ ...base, targetBranchId: 'b2', mutation: 'CREATE' })).reason, 'BRANCH_SCOPE_DENIED'); assert.equal((await service.evaluateFinancialMutation({ ...base, targetCompanyId: 'other', mutation: 'CREATE' })).reason, 'COMPANY_SCOPE_MISMATCH');
});

test('GS-040 exact integrity clean gate is deterministic and company isolated', async () => { const { service, repository } = fixture(); const clean = await service.evaluateIntegrity({ id: 'run-clean', companyId: 'c', correlationId: 'clean', comparisons: [{ key: 'balance', sourceAmount: '0.3', ledgerAmount: '0.3' }] }); assert.equal(clean.run.clean, true); const input = { id: 'run-bad', companyId: 'c', correlationId: 'bad', comparisons: [{ key: 'balance', sourceAmount: '9007199254740993.000000000000000001', ledgerAmount: '9007199254740993' }] }; const bad = await service.evaluateIntegrity(input); assert.equal(bad.run.clean, false); assert.equal(bad.issues[0]?.difference, '0.000000000000000001'); const replay = await service.evaluateIntegrity(input); assert.equal(replay.issues[0]?.id, bad.issues[0]?.id); assert.equal(repository.issues.size, 1); await assert.rejects(service.evaluateIntegrity({ ...input, comparisons: [{ key: 'balance', sourceAmount: '1', ledgerAmount: '2' }] }), /conflicting/); const other = await service.evaluateIntegrity({ ...input, id: 'other-run', companyId: 'other' }); assert.equal(other.run.companyId, 'other'); });

test('GS-021 blockers remain separate from warnings and resolved evidence becomes ready', async () => { const { service } = fixture(); const blocked = await service.evaluateCloseReadiness({ id: 'close-1', companyId: 'c', correlationId: 'close-1', checks: [{ key: 'integrity', passed: false, severity: 'BLOCKER', detail: 'mismatch' }, { key: 'fx', passed: false, severity: 'WARNING', detail: 'rate review recommended' }] }); assert.equal(blocked.ready, false); assert.equal(blocked.blockers.length, 1); assert.equal(blocked.warnings.length, 1); const ready = await service.evaluateCloseReadiness({ id: 'close-2', companyId: 'c', correlationId: 'close-2', checks: [{ key: 'integrity', passed: true, severity: 'BLOCKER', detail: 'clean' }, { key: 'fx', passed: true, severity: 'WARNING', detail: 'ready' }] }); assert.equal(ready.ready, true); assert.deepEqual(ready.blockers, []); });
test('BR-075 denies auto-fix and resolution requires immutable owner evidence', async () => { const { service } = fixture(); assert.equal(service.evaluateAutoFix().decision, 'DENIED'); const result = await service.evaluateIntegrity({ id: 'r', companyId: 'c', correlationId: 'r', comparisons: [{ key: 'x', sourceAmount: '1', ledgerAmount: '0' }] }); const issueId = result.issues[0]!.id; await assert.rejects(service.resolveControlIssue({ companyId: 'c', issueId, actorId: 'supervisor', resolutionMode: 'SUPERVISED' }), /evidence is required/); const resolved = await service.resolveControlIssue({ companyId: 'c', issueId, actorId: 'supervisor', resolutionMode: 'OWNER_CONFIRMED', ownerReference: 'owner-reversal:77' }); assert.equal(resolved.resolutionReference, 'owner-reversal:77'); });
