import { createHash } from 'node:crypto';
import type { Prisma, PrismaClient } from '@prisma/client';
import type { HistoricalEquivalence, HistoricalImportRecord } from '../application/historical-import.application-service.js';
import type { HistoricalImportRepository } from '../application/historical-import.repository.js';
const s=(v:unknown,f='')=>typeof v==='string'&&v?v:f; const n=(v:unknown,f='0')=>typeof v==='string'&&/^-?\d+(?:\.\d+)?$/.test(v)?v:f; const d=(v:unknown)=>new Date(s(v,'1970-01-01'));
const add=(a:string,b:string)=>{const z=Math.max((a.split('.')[1]??'').length,(b.split('.')[1]??'').length),u=10n**BigInt(z),p=(v:string)=>{const q=v.startsWith('-'),[w='0',f='']=(q?v.slice(1):v).split('.'),x=BigInt(w)*u+BigInt(f.padEnd(z,'0'));return q?-x:x},x=p(a)+p(b),q=x<0n,y=q?-x:x,t=y.toString().padStart(z+1,'0');return `${q?'-':''}${z?`${t.slice(0,-z)}.${t.slice(-z)}`:t}`};
export class PrismaHistoricalImportRepository implements HistoricalImportRepository {
 constructor(private readonly db:PrismaClient){}
 async find(runId:string,collection:string,sourceId:string){const v=await this.db.financialControlsHistoricalImport.findUnique({where:{runId_collection_sourceId:{runId,collection,sourceId}}});return v?{...v,owner:'FinancialControls',payload:v.payload as Record<string,unknown>,branchId:v.branchId??undefined,debit:v.debit.toString(),credit:v.credit.toString(),amount:v.amount.toString()} as HistoricalImportRecord:undefined}
 async create(r:HistoricalImportRecord){await this.db.$transaction(async tx=>{await this.restore(tx,r);await tx.financialControlsHistoricalImport.create({data:{id:r.id,runId:r.runId,collection:r.collection,sourceId:r.sourceId,sourcePayloadHash:r.sourcePayloadHash,companyId:r.companyId,branchId:r.branchId,payload:r.payload as object,payloadJson:r.payloadJson,debit:r.debit,credit:r.credit,amount:r.amount}})})}
 private async restore(tx:Prisma.TransactionClient,r:HistoricalImportRecord){const p=r.payload,c=r.collection;
if(c==='approvals')await tx.fcApprovalRequest.create({data:{id:r.sourceId,companyId:r.companyId,branchId:r.branchId,action:s(p.action,'HISTORICAL'),sourceType:s(p.sourceType,'HISTORICAL'),sourceId:s(p.sourceId,r.sourceId),requesterActorId:s(p.requesterActorId,'historical'),amount:n(p.amount),status:s(p.status,'APPROVED'),policyId:s(p.policyId),policyThresholdSnapshot:n(p.policyThresholdSnapshot),policyForbidSelfApprovalSnapshot:p.policyForbidSelfApprovalSnapshot===true,policyRequiredAuthoritySnapshot:s(p.policyRequiredAuthoritySnapshot,'HISTORICAL'),requestedAt:d(p.requestedAt??p.date)}});else if(c==='reconciliations')await tx.fcReconciliationRun.create({data:{id:r.sourceId,companyId:r.companyId,branchId:r.branchId,type:s(p.type,'HISTORICAL'),correlationId:s(p.correlationId,r.sourceId),fingerprint:s(p.fingerprint,r.sourcePayloadHash),clean:p.clean!==false,runAt:d(p.runAt??p.date)}});else throw new Error(`unsupported FinancialControls historical collection ${c}`)}
 async equivalence(runId:string,companyId:string):Promise<HistoricalEquivalence>{const provenance=await this.db.financialControlsHistoricalImport.findMany({where:{runId,companyId},orderBy:[{collection:'asc'},{sourceId:'asc'}]});const ids=(c:string)=>provenance.filter(x=>x.collection===c).map(x=>x.sourceId);const [approvals,reconciliations]=await Promise.all([this.db.fcApprovalRequest.findMany({where:{companyId,id:{in:ids('approvals')}}}),this.db.fcReconciliationRun.findMany({where:{companyId,id:{in:ids('reconciliations')}}})]);const rows=[...approvals.map(x=>({value:x,amount:x.amount.toString()})),...reconciliations.map(x=>({value:x,amount:'0'}))];return{records:String(rows.length),payloadDigest:createHash('sha256').update(rows.map(x=>JSON.stringify(x,(_,v)=>typeof v==='object'&&v?.constructor?.name==='Decimal'?v.toString():v)).join('\n')).digest('hex'),debit:provenance.reduce((a,x)=>add(a,x.debit.toString()),'0'),credit:provenance.reduce((a,x)=>add(a,x.credit.toString()),'0'),amount:rows.reduce((a,x)=>add(a,x.amount),'0')}}
}
