import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import type{ItineraryDay,ItineraryHistory}from'../domain/itinerary.js';import type{ItineraryAccess,ItineraryProgramPort}from'./itinerary.ports.js';import type{ItineraryRepository}from'./itinerary.repository.js';
export const TOURISM_ITINERARY_PERMISSIONS=Object.freeze({view:'tourism.itineraries.view',manage:'tourism.itineraries.manage'});
export interface ItineraryDayInput{programId:string;dayNumber:number;serviceDate:string;title:string;description?:string;location?:string}
const req=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x};
const date=(value:string,field:string)=>{const v=req(value,field);if(!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new ContractValidationError(field,'must be YYYY-MM-DD');const parsed=new Date(v+'T00:00:00.000Z');if(Number.isNaN(parsed.valueOf())||parsed.toISOString().slice(0,10)!==v)throw new ContractValidationError(field,'must be a valid calendar date');return v};
export class TourismItinerariesApplicationService{
 constructor(private readonly repo:ItineraryRepository,private readonly access:ItineraryAccess,private readonly programs:ItineraryProgramPort,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async permitted(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p)}
 private history(c:ExecutionContext,v:ItineraryDay,action:ItineraryHistory['action']):ItineraryHistory{return{id:this.newId(),companyId:c.companyId,branchId:c.branchId,programId:v.programId,itineraryDayId:v.id,action,actorId:c.actorId,occurredAt:this.now().toISOString()}}
 private async editable(c:ExecutionContext,programId:string){const p=await this.programs.require(c.companyId,c.branchId,programId);if(p.status!=='PREPARING')throw new ContractValidationError('programId','itinerary can be edited only while program is PREPARING');return p}
 async create(c:ExecutionContext,input:ItineraryDayInput){await this.permitted(c,TOURISM_ITINERARY_PERMISSIONS.manage);const p=await this.editable(c,input.programId);if(!Number.isInteger(input.dayNumber)||input.dayNumber<1)throw new ContractValidationError('dayNumber','positive integer required');date(input.serviceDate,'serviceDate');if(input.serviceDate<p.departureDate||input.serviceDate>p.returnDate)throw new ContractValidationError('serviceDate','must be inside program dates');const at=this.now().toISOString();const value:ItineraryDay={id:this.newId(),companyId:c.companyId,branchId:c.branchId,programId:p.id,dayNumber:input.dayNumber,serviceDate:input.serviceDate,title:req(input.title,'title'),...(input.description?.trim()?{description:input.description.trim()}:{}),...(input.location?.trim()?{location:input.location.trim()}:{}),revision:1,createdAt:at,updatedAt:at};const result=await this.repo.create(value,this.history(c,value,'CREATED'));await this.access.audit(c,'tourism.itinerary.created',result.id,{programId:p.id});return result}
 async update(c:ExecutionContext,id:string,input:ItineraryDayInput,expectedRevision:number){await this.permitted(c,TOURISM_ITINERARY_PERMISSIONS.manage);const old=await this.required(c,id);if(old.programId!==input.programId)throw new ContractValidationError('programId','cannot move itinerary day to another program');const p=await this.editable(c,old.programId);if(expectedRevision!==old.revision)throw new ContractValidationError('revision','itinerary changed');if(!Number.isInteger(input.dayNumber)||input.dayNumber<1)throw new ContractValidationError('dayNumber','positive integer required');date(input.serviceDate,'serviceDate');if(input.serviceDate<p.departureDate||input.serviceDate>p.returnDate)throw new ContractValidationError('serviceDate','must be inside program dates');const value:ItineraryDay={...old,dayNumber:input.dayNumber,serviceDate:input.serviceDate,title:req(input.title,'title'),...(input.description?.trim()?{description:input.description.trim()}:{description:undefined}),...(input.location?.trim()?{location:input.location.trim()}:{location:undefined}),revision:old.revision+1,updatedAt:this.now().toISOString()};return this.repo.save(value,this.history(c,value,'UPDATED'))}
 async list(c:ExecutionContext,programId:string){await this.permitted(c,TOURISM_ITINERARY_PERMISSIONS.view);await this.programs.require(c.companyId,c.branchId,programId);return this.repo.list(c.companyId,c.branchId,programId)}
 async get(c:ExecutionContext,id:string){await this.permitted(c,TOURISM_ITINERARY_PERMISSIONS.view);return this.required(c,id)}
 private async required(c:ExecutionContext,id:string){const value=await this.repo.get(c.companyId,c.branchId,id);if(!value)throw new ContractValidationError('itineraryId','not found');return value}
}
