import type { PlatformCoreRepository } from '../application/platform-core.repository.js';
import type { AuditEntry, Branch, Company, Id, Notification, Session, StoredFile, User } from '../domain/platform.types.js';
/** Test adapter only. It is deliberately not registered by PlatformCoreModule. */
export class InMemoryPlatformRepository implements PlatformCoreRepository {
  users=new Map<Id,User>(); companies=new Map<Id,Company>(); branches=new Map<Id,Branch>(); roles=new Map<Id,string>(); permissions=new Map<Id,string>(); userRoles=new Map<string,Set<Id>>(); recovery=new Map<string,{userId:Id;expiresAt:Date;used:boolean}>(); rolePermissions=new Map<Id,Set<Id>>(); branchAccess=new Map<Id,Set<Id>>(); sessions=new Map<Id,Session>(); audits:AuditEntry[]=[]; files=new Map<Id,StoredFile>(); notifications=new Map<Id,Notification>(); config=new Map<string,unknown>();
  async transaction<T>(work:()=>Promise<T>):Promise<T>{return work()} async findUserById(id:Id){return this.users.get(id)} async findUserByEmail(email:string){return [...this.users.values()].find(x=>x.email===email)} async createUser(x:User){this.users.set(x.id,x);return x} async updateUser(x:User){this.users.set(x.id,x);return x}
  async createSession(x:Session){this.sessions.set(x.id,x)} async findSessionByTokenHash(x:string){return [...this.sessions.values()].find(s=>s.tokenHash===x)} async revokeSession(id:Id,at:Date){const s=this.sessions.get(id);if(s)s.revokedAt=at} async revokeUserSessions(userId:Id,at:Date){for(const s of this.sessions.values())if(s.userId===userId)s.revokedAt=at} async revokeCompanySessions(companyId:Id,at:Date){for(const s of this.sessions.values())if([...(this.branchAccess.get(s.userId)??[])].some(branchId=>this.branches.get(branchId)?.companyId===companyId))s.revokedAt=at} async listSessions(userId:Id){return [...this.sessions.values()].filter(s=>s.userId===userId)}
  async createRole(id:Id,n:string){this.roles.set(id,n)} async findRoleByName(n:string){return [...this.roles].find(([,x])=>x===n)?.[0]} async createPermission(id:Id,n:string){this.permissions.set(id,n)} async assignRole(u:Id,c:Id,r:Id){const k=`${u}:${c}`;(this.userRoles.get(k)??this.userRoles.set(k,new Set()).get(k)!).add(r)} async grantPermission(r:Id,p:Id){(this.rolePermissions.get(r)??this.rolePermissions.set(r,new Set()).get(r)!).add(p)} async hasPermission(u:Id,c:Id,p:string){return [...(this.userRoles.get(`${u}:${c}`)??[])].some(r=>[...(this.rolePermissions.get(r)??[])].some(x=>this.permissions.get(x)===p))}
  async saveRecoveryToken(userId:Id,tokenHash:string,expiresAt:Date){this.recovery.set(tokenHash,{userId,expiresAt,used:false})} async consumeRecoveryToken(tokenHash:string,now:Date){const x=this.recovery.get(tokenHash);if(!x||x.used||x.expiresAt<=now)return undefined;x.used=true;return x.userId} async updatePassword(userId:Id,passwordHash:string,updatedAt:Date){const u=this.users.get(userId);if(u){u.passwordHash=passwordHash;u.updatedAt=updatedAt}}
  async createCompany(x:Company){this.companies.set(x.id,x);return x} async findCompany(id:Id){return this.companies.get(id)} async createBranch(x:Branch){this.branches.set(x.id,x);return x} async findBranch(id:Id){return this.branches.get(id)} async grantBranchAccess(u:Id,b:Id){(this.branchAccess.get(u)??this.branchAccess.set(u,new Set()).get(u)!).add(b)} async hasBranchAccess(u:Id,b:Id){return this.branchAccess.get(u)?.has(b)??false}
  async recordAudit(x:AuditEntry){this.audits.push(x)} async recordAuditOnce(x:AuditEntry){if(!this.audits.some(a=>a.id===x.id))this.audits.push(x)} async listAudit(companyId?:Id){return companyId?this.audits.filter(x=>x.companyId===companyId):this.audits} async userHasCompanyAccess(userId:Id,companyId:Id){return this.userRoles.has(`${userId}:${companyId}`)||[...(this.branchAccess.get(userId)??[])].some(id=>this.branches.get(id)?.companyId===companyId)} async registerFile(x:StoredFile){this.files.set(x.id,x);return x} async notify(x:Notification){this.notifications.set(x.id,x);return x} async setConfiguration(k:string,v:unknown){this.config.set(k,v)} async getConfiguration(k:string){return this.config.get(k)}
}
