import type { PrismaClient } from '@prisma/client';
import type { PlatformCoreRepository } from '../application/platform-core.repository.js';
import type { AuditEntry, Branch, Company, Id, Notification, Session, StoredFile, User } from '../domain/platform.types.js';
const user=(x:{id:string;email:string;passwordHash:string;displayName:string;status:string;createdAt:Date;updatedAt:Date}):User=>({...x,status:x.status as User['status']});
/** PostgreSQL adapter; this is the only repository registered for production. */
export class PrismaPlatformRepository implements PlatformCoreRepository {
  constructor(private readonly prisma:PrismaClient) {}
  transaction<T>(work:()=>Promise<T>):Promise<T>{return this.prisma.$transaction(work)}
  async findUserById(id:Id){const x=await this.prisma.pcUser.findUnique({where:{id}});return x?user(x):undefined} async findUserByEmail(email:string){const x=await this.prisma.pcUser.findUnique({where:{email}});return x?user(x):undefined} async createUser(x:User){return user(await this.prisma.pcUser.create({data:x}))} async updateUser(x:User){return user(await this.prisma.pcUser.update({where:{id:x.id},data:{email:x.email,displayName:x.displayName,status:x.status,updatedAt:x.updatedAt}}))}
  async createSession(x:Session){await this.prisma.pcSession.create({data:x})} async findSessionByTokenHash(tokenHash:string){return await this.prisma.pcSession.findUnique({where:{tokenHash}})??undefined} async revokeSession(id:Id,revokedAt:Date){await this.prisma.pcSession.update({where:{id},data:{revokedAt}})}
  async createRole(id:Id,name:string){await this.prisma.pcRole.create({data:{id,name}})} async findRoleByName(name:string){return (await this.prisma.pcRole.findUnique({where:{name}}))?.id} async createPermission(id:Id,name:string){await this.prisma.pcPermission.create({data:{id,name}})} async assignRole(userId:Id,roleId:Id){await this.prisma.pcUserRole.upsert({where:{userId_roleId:{userId,roleId}},create:{userId,roleId},update:{}})} async grantPermission(roleId:Id,permissionId:Id){await this.prisma.pcRolePermission.upsert({where:{roleId_permissionId:{roleId,permissionId}},create:{roleId,permissionId},update:{}})} async hasPermission(userId:Id,permission:string){return (await this.prisma.pcUserRole.count({where:{userId,role:{permissions:{some:{permission:{name:permission}}}}}}))>0}
  async createCompany(x:Company){return await this.prisma.pcCompany.create({data:x})} async findCompany(id:Id){return await this.prisma.pcCompany.findUnique({where:{id}})??undefined} async createBranch(x:Branch){return await this.prisma.pcBranch.create({data:x})} async findBranch(id:Id){return await this.prisma.pcBranch.findUnique({where:{id}})??undefined} async grantBranchAccess(userId:Id,branchId:Id){await this.prisma.pcUserBranchAccess.upsert({where:{userId_branchId:{userId,branchId}},create:{userId,branchId},update:{}})} async hasBranchAccess(userId:Id,branchId:Id){return !!await this.prisma.pcUserBranchAccess.findUnique({where:{userId_branchId:{userId,branchId}}})}
  async recordAudit(x:AuditEntry){await this.prisma.pcAuditLog.create({data:{...x,metadata:x.metadata as never}})} async listAudit():Promise<readonly AuditEntry[]>{return (await this.prisma.pcAuditLog.findMany({orderBy:{occurredAt:'asc'}})).map((x:{id:string;actorId:string|null;action:string;resource:string;entityId:string|null;companyId:string|null;branchId:string|null;metadata:unknown;occurredAt:Date})=>({...x,metadata:x.metadata as Record<string,unknown>}))} async registerFile(x:StoredFile){await this.prisma.pcFile.create({data:{id:x.id,companyId:x.companyId,storageKey:x.key,contentType:x.contentType,size:x.size,createdBy:x.createdBy,createdAt:x.createdAt}});return x} async notify(x:Notification){await this.prisma.pcNotification.create({data:{...x,payload:x.payload as never}});return x} async setConfiguration(key:string,value:unknown){await this.prisma.pcConfiguration.upsert({where:{key},create:{key,value:value as never},update:{value:value as never}})} async getConfiguration(key:string){return (await this.prisma.pcConfiguration.findUnique({where:{key}}))?.value}
}
