import {createHash} from 'node:crypto'; import {ContractValidationError,decimalAmount,type CompanyId,type DecimalAmount} from '@elhafez/contracts'; import type {PeriodControlApplicationService,FiscalCloseInstruction} from '@elhafez/period-control'; import type {CurrencyFxApplicationService,FxRateSnapshot} from '@elhafez/currency-fx'; import {sum,type Account,type Journal,type JournalKind,type JournalLine} from '../domain/ledger.js'; import type {LedgerRepository} from './ledger.repository.js';
export interface PostingLine{accountId:string;debit?:DecimalAmount;credit?:DecimalAmount;partyId?:string;foreignAmount?:DecimalAmount;foreignCurrency?:string}
export interface PostingInstruction{id:string;companyId:CompanyId;number:string;postingDate:string;kind?:JournalKind;sourceType:string;sourceId:string;correlationId?:string;lines:readonly PostingLine[]}
export class GeneralLedgerApplicationService{
 constructor(private repo:LedgerRepository,private period:Pick<PeriodControlApplicationService,'authorizePosting'|'authorizeFiscalCloseReversal'>,private fx?:Pick<CurrencyFxApplicationService,'resolveRate'>){}
 async createAccount(a:Account){if(await this.repo.accountByCode(a.companyId,a.code))throw new ContractValidationError('code','already used');if(a.parentId&&!await this.repo.account(a.companyId,a.parentId))throw new ContractValidationError('parentId','parent must belong to same company');await this.repo.saveAccount(a);return a}
 async updateAccount(companyId:CompanyId,id:string,change:Partial<Omit<Account,'id'|'companyId'>>){const a=await this.repo.account(companyId,id);if(!a)throw new ContractValidationError('account','not found');if(await this.repo.hasHistory(companyId,id)){for(const k of ['code','classification','controlType','parentId'] as const)if(change[k]!==undefined&&change[k]!==a[k])throw new ContractValidationError(k,'historical financial semantics are immutable')}const next={...a,...change};if(next.parentId&&!await this.repo.account(companyId,next.parentId))throw new ContractValidationError('parentId','parent must belong to same company');await this.repo.saveAccount(next);return next}
 async post(i:PostingInstruction):Promise<Journal>{const auth=await this.period.authorizePosting(i.companyId,i.postingDate);return this.postAuthorized(i,auth.fiscalYearId)}
 private async postAuthorized(i:PostingInstruction,authorizedFiscalYearId?:string):Promise<Journal>{const payload=JSON.stringify(i);const hash=createHash('sha256').update(payload).digest('hex');const prior=await this.repo.journalBySource(i.companyId,i.sourceType,i.sourceId);if(prior){if(prior.requestHash!==hash)throw new ContractValidationError('source','conflicting duplicate source posting');return prior}if(i.lines.length<2)throw new ContractValidationError('lines','at least two lines required');const debits:string[]=[],credits:string[]=[];const lines:JournalLine[]=[];for(const [n,l] of i.lines.entries()){const d=l.debit?decimalAmount(l.debit):undefined,c=l.credit?decimalAmount(l.credit):undefined;const dp=!!d&&sum([d])>0n,cp=!!c&&sum([c])>0n;if(dp===cp)throw new ContractValidationError('line','exactly one positive economic side required');const a=await this.repo.account(i.companyId,l.accountId);if(!a||!a.active||!a.postable)throw new ContractValidationError('account','not active and postable for company');if(a.controlType&&!l.partyId)throw new ContractValidationError('partyId','control account requires party identity');if(!a.controlType&&l.partyId)throw new ContractValidationError('partyId','party identity is only valid on control accounts');if(i.kind==='OPENING'&&(a.classification==='REVENUE'||a.classification==='EXPENSE'))throw new ContractValidationError('opening','BR-024 permits balance-sheet accounts only');let snapshot:FxRateSnapshot|undefined;if(l.foreignCurrency){if(!this.fx)throw new ContractValidationError('fx','FX service required');snapshot=await this.fx.resolveRate(i.companyId,l.foreignCurrency as never,'USD' as never,i.postingDate+'T23:59:59.999Z')}if(d)debits.push(d);if(c)credits.push(c);lines.push({...l,id:`${i.id}:${n+1}`,fxRateId:snapshot?.rateId,fxRate:snapshot?.rate})}if(sum(debits)!==sum(credits))throw new ContractValidationError('journal','BR-001 base currency debits and credits must balance');const j:object={...i,kind:i.kind??'STANDARD',requestHash:hash,fiscalYearId:authorizedFiscalYearId,lines};await this.repo.saveJournal(j as Journal);return Object.freeze(j) as Journal}
 async reverse(companyId:CompanyId,journalId:string,postingDate:string,number:string){const original=await this.repo.journal(companyId,journalId);if(!original)throw new ContractValidationError('journal','not found');const existing=(await this.repo.journals(companyId)).find(x=>x.reversalOfId===journalId);if(existing)return existing;if(original.kind==='FISCAL_CLOSE')await this.period.authorizeFiscalCloseReversal(companyId,postingDate,journalId);return this.postAuthorized({id:`reversal:${journalId}`,companyId,number,postingDate,kind:'REVERSAL',sourceType:'JOURNAL_REVERSAL',sourceId:journalId,correlationId:original.correlationId,lines:original.lines.map(x=>({accountId:x.accountId,debit:x.credit,credit:x.debit,partyId:x.partyId,foreignAmount:x.foreignAmount,foreignCurrency:x.foreignCurrency}))}).then(async j=>{const linked={...j,reversalOfId:journalId};await this.repo.saveJournal(linked);return linked})}
 async closeFiscalYear(i:FiscalCloseInstruction,retainedEarningsAccountId:string,number:string){const existing=await this.repo.journalBySource(i.companyId,'FISCAL_CLOSE',i.fiscalYearId);if(existing)return existing;const accounts=new Map<string,Account>();const balances=new Map<string,bigint>();for(const j of await this.repo.journals(i.companyId))if(j.postingDate>=i.startDate&&j.postingDate<=i.endDate)for(const l of j.lines){const a=await this.repo.account(i.companyId,l.accountId);if(a&&(a.classification==='REVENUE'||a.classification==='EXPENSE')){accounts.set(a.id,a);balances.set(a.id,(balances.get(a.id)??0n)+sum(l.debit?[l.debit]:[])-sum(l.credit?[l.credit]:[]))}}const lines:PostingLine[]=[];let net=0n;for(const [id,b] of balances){if(b===0n)continue;net+=b;lines.push({accountId:id,...(b>0n?{credit:decimalAmount(b.toString())}:{debit:decimalAmount((-b).toString())})})}if(net!==0n)lines.push({accountId:retainedEarningsAccountId,...(net>0n?{debit:decimalAmount(net.toString())}:{credit:decimalAmount((-net).toString())})});if(!lines.length)throw new ContractValidationError('close','no P&L balance to close');return this.post({id:`close:${i.fiscalYearId}`,companyId:i.companyId,number,postingDate:i.endDate,kind:'FISCAL_CLOSE',sourceType:'FISCAL_CLOSE',sourceId:i.fiscalYearId,lines})}
 async getJournal(c:CompanyId,id:string){return this.repo.journal(c,id)} async activity(c:CompanyId){return this.repo.journals(c)}
}
