import type {PrismaClient} from '@prisma/client';
import type {DataExchangeRepository,ExchangeJob,ExchangeRow,ExchangeStatus} from '../application/data-exchange.application-service.js';

type StoredJob={id:string;companyId:string;branchId:string|null;direction:string;status:string;fileName:string;format:string;mapping:unknown;idempotencyKey:string;resultKey:string|null;createdAt:Date;updatedAt:Date;rows:Array<{rowNumber:number;source:unknown;outcome:string;error:string|null}>};
const hydrate=(x:StoredJob):ExchangeJob=>({id:x.id,companyId:x.companyId,branchId:x.branchId,direction:x.direction as ExchangeJob['direction'],status:x.status as ExchangeStatus,fileName:x.fileName,format:x.format as ExchangeJob['format'],mapping:x.mapping as Record<string,string>,idempotencyKey:x.idempotencyKey,resultKey:x.resultKey??undefined,createdAt:x.createdAt,updatedAt:x.updatedAt,rows:x.rows.map(r=>({rowNumber:r.rowNumber,source:r.source as Record<string,string>,outcome:r.outcome as ExchangeRow['outcome'],error:r.error??undefined}))});
export class PrismaDataExchangeRepository implements DataExchangeRepository{
 constructor(private readonly prisma:PrismaClient){}
 async save(job:ExchangeJob){await this.prisma.$transaction(async tx=>{await tx.dexJob.upsert({where:{id:job.id},create:{id:job.id,companyId:job.companyId,branchId:job.branchId,direction:job.direction,status:job.status,fileName:job.fileName,format:job.format,mapping:job.mapping as never,idempotencyKey:job.idempotencyKey,resultKey:job.resultKey,createdAt:job.createdAt,updatedAt:job.updatedAt},update:{status:job.status,resultKey:job.resultKey,mapping:job.mapping as never,updatedAt:job.updatedAt}});for(const row of job.rows)await tx.dexRow.upsert({where:{jobId_rowNumber:{jobId:job.id,rowNumber:row.rowNumber}},create:{jobId:job.id,rowNumber:row.rowNumber,source:row.source as never,outcome:row.outcome,error:row.error},update:{source:row.source as never,outcome:row.outcome,error:row.error}})})}
 async find(companyId:string,id:string){const x=await this.prisma.dexJob.findFirst({where:{id,companyId},include:{rows:{orderBy:{rowNumber:'asc'}}}});return x?hydrate(x):undefined}
 async findByKey(companyId:string,key:string){const x=await this.prisma.dexJob.findUnique({where:{companyId_idempotencyKey:{companyId,idempotencyKey:key}},include:{rows:{orderBy:{rowNumber:'asc'}}}});return x?hydrate(x):undefined}
 async list(companyId:string){return (await this.prisma.dexJob.findMany({where:{companyId},include:{rows:{orderBy:{rowNumber:'asc'}}},orderBy:{createdAt:'desc'}})).map(hydrate)}
}
