import type { CompanyId, DecimalAmount } from '@elhafez/contracts';

export interface Asset { id:string; companyId:CompanyId; code:string; name:string; description?:string; acquisitionValue:DecimalAmount; baseValue:DecimalAmount; currency:string; acquisitionDate:string; capitalizationDate:string; inServiceDate:string; residualValue:DecimalAmount; usefulLifeMonths:number; method:'STRAIGHT_LINE'; assetAccountId:string; accumulatedDepreciationAccountId:string; depreciationExpenseAccountId:string; disposalGainAccountId?:string; disposalLossAccountId?:string; status:'ACTIVE'|'DISPOSED'; accumulatedDepreciation:DecimalAmount; capitalizationJournalId:string; requestHash:string }
export interface AssetDepreciation { id:string; companyId:CompanyId; assetId:string; period:number; postingDate:string; amount:DecimalAmount; status:'PENDING'|'POSTING'|'POSTED'; requestHash:string; journalId?:string }
export interface AssetDisposal { id:string; companyId:CompanyId; assetId:string; postingDate:string; proceeds:DecimalAmount; requestHash:string; journalId:string }
export interface LoanInstallment { id:string; companyId:CompanyId; loanId:string; sequence:number; dueDate:string; principal:DecimalAmount; interest:DecimalAmount; status:'DUE'|'PAYING'|'PAID'; requestHash?:string; treasuryVoucherId?:string; journalId?:string }
export interface Loan { id:string; companyId:CompanyId; lenderId:string; reference:string; principal:DecimalAmount; outstandingPrincipal:DecimalAmount; currency:string; baseAmount:DecimalAmount; liabilityAccountId:string; interestExpenseAccountId:string; fundingAccountId:string; status:'ORIGINATED'|'COMPLETED'; requestHash:string; originationJournalId:string; installments:LoanInstallment[] }
export type ProvisionMovementKind='RECOGNIZE'|'INCREASE'|'USE'|'RELEASE';
export interface ProvisionMovement { id:string; companyId:CompanyId; provisionId:string; kind:ProvisionMovementKind; amount:DecimalAmount; sourceType:string; sourceId:string; requestHash:string; journalId:string; createdAt:string }
export interface Provision { id:string; companyId:CompanyId; name:string; provisionAccountId:string; expenseAccountId:string; available:DecimalAmount; movements:ProvisionMovement[] }
export interface AllowanceMovement { id:string; companyId:CompanyId; allowanceId:string; kind:'RECOGNIZE'|'USE'|'RELEASE'; amount:DecimalAmount; sourceId:string; requestHash:string; journalId?:string; billingAdjustmentId?:string; createdAt:string }
export interface Allowance { id:string; companyId:CompanyId; customerId?:string; sourceReference:string; allowanceAccountId:string; expenseAccountId:string; amount:DecimalAmount; used:DecimalAmount; available:DecimalAmount; movements:AllowanceMovement[] }
export interface AllowanceWriteOff { id:string; companyId:CompanyId; allowanceId:string; invoiceId:string; amount:DecimalAmount; postingDate:string; requestHash:string; status:'RESERVED'|'COMPLETED'; billingAdjustmentId?:string }
export interface PayrollLiability { id:string; accountId:string; amount:DecimalAmount; label:string }
export interface PayrollRun { id:string; companyId:CompanyId; sourceId:string; payrollPeriod:string; postingDate:string; expenseTotal:DecimalAmount; expenseAccountId:string; liabilities:PayrollLiability[]; status:'ACCRUING'|'ACCRUED'|'PAYING'|'PAID'; requestHash:string; journalId?:string; treasuryVoucherId?:string }
