import{createServer}from'node:http';import{readFile,stat}from'node:fs/promises';import{extname,join,normalize,resolve}from'node:path';

const port=Number(process.env.PORT??4178);
const root=resolve(process.env.ELHAFEZ_STATIC_ROOT??'apps/web/dist');
const ownerRoot=process.env.ELHAFEZ_OWNER_ROOT?resolve(process.env.ELHAFEZ_OWNER_ROOT):null;
const apiBase=(process.env.ELHAFEZ_API_BASE_URL??'').replace(/\/$/,'');
const maxBody=2*1024*1024;
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.map':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};

async function body(request){if(request.method==='GET'||request.method==='HEAD')return undefined;const chunks=[];let size=0;for await(const chunk of request){const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=value.length;if(size>maxBody)throw new Error('REQUEST_TOO_LARGE');chunks.push(value);}return Buffer.concat(chunks);}
async function proxy(request,response){if(!apiBase){response.writeHead(503,{'content-type':'application/json'});response.end(JSON.stringify({error:'API_NOT_CONFIGURED'}));return;}const raw=request.url??'/api',suffix=raw.startsWith('/api')?raw.slice(4):raw,url=apiBase+(suffix||'/');try{const headers=new Headers();for(const[name,value]of Object.entries(request.headers)){if(value===undefined||name==='host'||name==='connection'||name==='content-length')continue;if(Array.isArray(value))for(const item of value)headers.append(name,item);else headers.set(name,value);}const payload=await body(request);const upstream=await fetch(url,{method:request.method,headers,body:payload});const out={};upstream.headers.forEach((value,name)=>{if(!['connection','transfer-encoding','content-length'].includes(name))out[name]=value;});const bytes=Buffer.from(await upstream.arrayBuffer());response.writeHead(upstream.status,{...out,'content-length':String(bytes.length)});response.end(bytes);}catch(error){const large=error instanceof Error&&error.message==='REQUEST_TOO_LARGE';response.writeHead(large?413:502,{'content-type':'application/json'});response.end(JSON.stringify({error:large?'REQUEST_TOO_LARGE':'API_PROXY_FAILED'}));}}
async function staticFile(request,response){const raw=(request.url??'/').split('?')[0]??'/';if(raw==='/healthz'){response.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});response.end(JSON.stringify({status:'ok'}));return;}const owner=ownerRoot&&(raw==='/owner'||raw.startsWith('/owner/'));const base=owner?ownerRoot:root;const logical=owner?(raw.slice('/owner'.length)||'/'):raw;const clean=normalize(logical).replace(/^(\.\.(\/|\\|$))+/,'').replace(/^[/\\]+/,'');const candidate=join(base,clean||'index.html');let path=candidate;try{if(!(await stat(path)).isFile())path=join(base,'index.html');}catch{path=join(base,'index.html');}const bytes=await readFile(path),ext=extname(path);response.writeHead(200,{'content-type':types[ext]??'application/octet-stream','cache-control':ext==='.html'?'no-store':'public, max-age=31536000, immutable','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'same-origin','content-security-policy':"default-src 'self'; connect-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; base-uri 'self'; frame-ancestors 'none'"});response.end(bytes);}
createServer((request,response)=>{const url=request.url??'';if(url==='/api'||url.startsWith('/api/')||url.startsWith('/api?')){void proxy(request,response);return;}void staticFile(request,response).catch(error=>{response.writeHead(500,{'content-type':'text/plain; charset=utf-8'});response.end(error instanceof Error?error.message:'server error');});}).listen(port,'0.0.0.0',()=>process.stdout.write('ELHAFEZ static proxy listening on '+port+'\n'));
