import { ContractValidationError,type CompanyId,type SourceReference } from '@elhafez/contracts'; import { createCostCenter,type CostCenter,type CostCenterId,type ProgramCostCenterAssociation } from '../domain/cost-center.js'; import type { CostCenterRepository } from './cost-center.repository.js';
export class CostBudgetAccountingApplicationService { constructor(private readonly repository:CostCenterRepository){}
 async create(input:CostCenter):Promise<CostCenter>{const value=createCostCenter(input);if(await this.repository.findByCode(value.companyId,value.code))throw new ContractValidationError('code','already exists for company');if(value.parentId)await this.validateActive(value.companyId,value.parentId);await this.repository.save(value);return value;}
 async get(companyId:CompanyId,id:CostCenterId):Promise<CostCenter>{const value=await this.repository.find(companyId,id);if(!value)throw new ContractValidationError('costCenterId','not found for company');return value;}
 async validateActive(companyId:CompanyId,id:CostCenterId):Promise<CostCenter>{const value=await this.get(companyId,id);if(value.status!=='ACTIVE')throw new ContractValidationError('costCenterId','cost center is inactive');return value;}
 async deactivate(companyId:CompanyId,id:CostCenterId):Promise<CostCenter>{const value=await this.get(companyId,id);const changed=Object.freeze({...value,status:'INACTIVE' as const});await this.repository.save(changed);return changed;}
 async ensureProgramCostCenter(companyId:CompanyId,program:SourceReference,costCenterId:CostCenterId):Promise<ProgramCostCenterAssociation>{await this.validateActive(companyId,costCenterId);const existing=await this.repository.findAssociation(companyId,program);if(existing){if(existing.costCenterId!==costCenterId)throw new ContractValidationError('program','already mapped to a different cost center');return existing;}const value=Object.freeze({companyId,program,costCenterId});await this.repository.saveAssociation(value);return value;}
 async resolveProgramCostCenter(companyId:CompanyId,program:SourceReference):Promise<CostCenter>{const association=await this.repository.findAssociation(companyId,program);if(!association)throw new ContractValidationError('program','has no cost center association');return this.validateActive(companyId,association.costCenterId);}
}
