export type {
  TourismContractInventoryApplicationService,
  CreateTourismContractInput,
  AmendContractInput,
  CreateHotelInventoryInput,
  CreateFlightBlockInput,
  CreateTransportCapacityInput,
  CreateVisaQuotaInput,
  CreateGenericServiceInput,
  CreateStopSaleInput,
  AllocateCapacityInput,
  ReleaseAllocationInput,
  AdjustAllocationInput,
  ConsumeFlightBlockInput,
  InternalFirstFulfillmentInput,
  CheckAvailabilityInput,
  ProgramSupplyEvidenceInput,
  ProgramSupplyEvidence,
  RegisterAllocationEconomicEvidenceInput,
  ProtectAllocationCoverageInput,
  ReleaseAllocationCoverageInput,
  AvailabilityResult,
  AllocationResult,
  StandaloneSupplyRequest,
  StandaloneSupplyPlanLine,
  StandaloneSupplyResidual,
  StandaloneSupplyPlan,
  PlanStandaloneSupplyInput,
  CommitStandaloneSupplyPlanInput,
  StandaloneSupplyCommit,
  ReleaseResult,
} from '../application/inventory.application-service.js';
export { TourismContractInventoryReadApplicationService } from '../application/tourism-contract-inventory-read.application-service.js';
export type { TourismInventoryContractOption, TourismInventoryResourceOption } from '../application/inventory-read.repository.js';
export type {
  TourismContract,
  ContractVersion,
  HotelInventory,
  FlightBlock,
  FlightBlockConsumption,
  TransportCapacity,
  VisaQuota,
  GenericServiceInventory,
  ServiceCategory,
  StopSale,
  Allocation,
  AllocationRelease,
  ProcurementRequest,
  AllocationEconomicEvidence,
  AllocationCoverageRequirement,
  ReleaseBlocker,
  ContractType,
  ContractStatus,
  AllocationStatus,
  ResourceType,
} from '../domain/inventory.js';

export { HistoricalImportApplicationService } from '../application/historical-import.application-service.js';
export type { HistoricalImportCommand, HistoricalImportResult, HistoricalEquivalence } from '../application/historical-import.application-service.js';
