import{ContractValidationError,type BranchId,type CompanyId,type DecimalAmount}from'@elhafez/contracts';
export type CollectionStage='REMINDER'|'COLLECTOR'|'SUPERVISOR'|'CREDIT_HOLD'|'LEGAL_REVIEW'|'RESOLVED';
export type CollectionCaseStatus='OPEN'|'DISPUTED'|'PROMISE_TO_PAY'|'RESOLVED'|'CLOSED';
export interface CollectionPolicy{readonly id:string;readonly companyId:CompanyId;readonly reminderDaysBeforeDue:number;readonly collectorDaysOverdue:number;readonly supervisorDaysOverdue:number;readonly creditHoldDaysOverdue:number;readonly legalDaysOverdue:number;readonly active:boolean}
export interface CollectionCase{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly invoiceId:string;readonly customerPartyId:string;readonly currency:string;readonly dueDate:string|null;readonly collectorUserId:string|null;readonly status:CollectionCaseStatus;readonly stage:CollectionStage;readonly openedAt:string;readonly resolvedAt:string|null;readonly lastOutstanding:DecimalAmount;readonly lastRefreshedAt:string;readonly disputeReason:string|null}
export interface PromiseToPay{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly caseId:string;readonly promisedDate:string;readonly amount:DecimalAmount;readonly status:'OPEN'|'KEPT'|'BROKEN'|'CANCELLED';readonly note:string|null;readonly actorId:string;readonly createdAt:string;readonly resolvedAt:string|null}
export interface CollectionActivity{readonly id:string;readonly companyId:CompanyId;readonly branchId:BranchId;readonly caseId:string;readonly kind:'CALL'|'EMAIL'|'WHATSAPP'|'NOTE'|'ESCALATION'|'SYSTEM';readonly detail:string;readonly actorId:string;readonly occurredAt:string}
export const req=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x};
export const day=(v:string,f:string)=>{const x=req(v,f);if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw new ContractValidationError(f,'must be YYYY-MM-DD');return x};
