import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import type{DocumentAccess,DocumentFilePort}from'./document-management.ports.js';import type{DocumentManagementRepository}from'./document-management.repository.js';import{date,req,type BusinessDocument,type DocumentRequirement,type DocumentVersion}from'../domain/document-management.js';
export const DOCUMENT_PERMISSIONS=Object.freeze({read:'documents.read',manage:'documents.manage',requirements:'documents.requirements.manage'});
export class DocumentManagementApplicationService{constructor(private readonly repo:DocumentManagementRepository,private readonly files:DocumentFilePort,private readonly access:DocumentAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async perm(c:ExecutionContext,p:string){await this.access.requirePermission(c,p)}private async required(c:ExecutionContext,id:string){const v=await this.repo.get(c.companyId,id);if(!v)throw new ContractValidationError('documentId','document not found');return v}
 async configureRequirement(c:ExecutionContext,input:{id?:string;entityType:string;documentType:string;label:string;required:boolean;expiryRequired:boolean;warningDays?:number;active?:boolean}){await this.perm(c,DOCUMENT_PERMISSIONS.requirements);const warningDays=input.warningDays??30;if(!Number.isInteger(warningDays)||warningDays<0||warningDays>3650)throw new ContractValidationError('warningDays','must be an integer between 0 and 3650');const value:DocumentRequirement={id:input.id?.trim()||this.newId(),companyId:c.companyId,entityType:req(input.entityType,'entityType'),documentType:req(input.documentType,'documentType'),label:req(input.label,'label'),required:input.required,expiryRequired:input.expiryRequired,warningDays,active:input.active??true};return this.repo.saveRequirement(value)}
 async requirements(c:ExecutionContext,entityType?:string){await this.perm(c,DOCUMENT_PERMISSIONS.read);return this.repo.listRequirements(c.companyId,entityType?.trim())}
 async attach(c:ExecutionContext,input:{entityType:string;entityId:string;documentType:string;title:string;fileId:string;ownerUserId?:string;issueDate?:string;expiryDate?:string;tags?:readonly string[];required?:boolean;note?:string}){await this.perm(c,DOCUMENT_PERMISSIONS.manage);await this.files.requireFile(c.companyId,req(input.fileId,'fileId'));const issue=date(input.issueDate,'issueDate'),expiry=date(input.expiryDate,'expiryDate');if(issue&&expiry&&expiry<issue)throw new ContractValidationError('expiryDate','must be on or after issue date');const at=this.now().toISOString(),id=this.newId(),doc:BusinessDocument={id,companyId:c.companyId,entityType:req(input.entityType,'entityType'),entityId:req(input.entityId,'entityId'),documentType:req(input.documentType,'documentType'),title:req(input.title,'title'),ownerUserId:input.ownerUserId?.trim()||null,issueDate:issue,expiryDate:expiry,tags:[...new Set((input.tags??[]).map(x=>x.trim()).filter(Boolean))],required:input.required??false,currentVersion:1,status:expiry&&expiry<this.now().toISOString().slice(0,10)?'EXPIRED':'ACTIVE',createdAt:at,updatedAt:at},version:DocumentVersion={id:this.newId(),companyId:c.companyId,documentId:id,version:1,fileId:input.fileId.trim(),note:input.note?.trim()||null,actorId:c.actorId,createdAt:at};const out=await this.repo.create(doc,version);await this.access.audit(c,'document.attached',out.id,{entityType:out.entityType,entityId:out.entityId,fileId:version.fileId});return out}
 async addVersion(c:ExecutionContext,id:string,input:{fileId:string;note?:string}){await this.perm(c,DOCUMENT_PERMISSIONS.manage);const doc=await this.required(c,id);if(doc.status==='RETIRED')throw new ContractValidationError('status','retired document is immutable');await this.files.requireFile(c.companyId,req(input.fileId,'fileId'));const version:DocumentVersion={id:this.newId(),companyId:c.companyId,documentId:doc.id,version:doc.currentVersion+1,fileId:input.fileId.trim(),note:input.note?.trim()||null,actorId:c.actorId,createdAt:this.now().toISOString()};await this.repo.addVersion(version);const out=await this.repo.save({...doc,currentVersion:version.version,updatedAt:this.now().toISOString()});await this.access.audit(c,'document.version.added',id,{version:version.version,fileId:version.fileId});return out}
 async retire(c:ExecutionContext,id:string){await this.perm(c,DOCUMENT_PERMISSIONS.manage);const doc=await this.required(c,id);if(doc.status==='RETIRED')return doc;return this.repo.save({...doc,status:'RETIRED',updatedAt:this.now().toISOString()})}
 async listForRecord(c:ExecutionContext,entityType:string,entityId:string){await this.perm(c,DOCUMENT_PERMISSIONS.read);return this.repo.listForRecord(c.companyId,req(entityType,'entityType'),req(entityId,'entityId'))}
 async versions(c:ExecutionContext,id:string){await this.perm(c,DOCUMENT_PERMISSIONS.read);await this.required(c,id);return this.repo.versions(c.companyId,id)}
 async expiring(c:ExecutionContext,days=30){await this.perm(c,DOCUMENT_PERMISSIONS.read);if(!Number.isInteger(days)||days<0||days>3650)throw new ContractValidationError('days','invalid');return this.repo.listExpiring(c.companyId,new Date(this.now().getTime()+days*86400000).toISOString().slice(0,10))}
}
