import assert from 'node:assert/strict';
import test from 'node:test';
import { executionContext, type ExecutionContext } from '@elhafez/contracts';
import { TravelerManagementApplicationService, TRAVELER_PERMISSIONS } from './application/traveler-management.application-service.js';
import type { TravelerManagementAccess } from './application/traveler-management-access.js';
import type { TravelerLinkagePort } from './application/traveler-management-dependencies.port.js';
import { InMemoryTravelerManagementRepository } from './infrastructure/in-memory-traveler-management.repository.js';

class Access implements TravelerManagementAccess {
  denied:string|null=null;
  async requireBranch(c:ExecutionContext){if(c.companyId!=='company-1'||!['branch-1','branch-2'].includes(c.branchId))throw Error('branch denied');}
  async requirePermission(_c:ExecutionContext,p:string){if(this.denied===p)throw Error('permission denied');}
  async audit():Promise<void>{}
}
class Linkage implements TravelerLinkagePort {
  customers=new Map([['cust-1','party-1'],['cust-2','party-2']]);
  parties=new Set(['party-1','party-2','party-3']);
  async customerPartyId(_c:ExecutionContext,id:string){return this.customers.get(id)??null;}
  async isResolvableParty(_c:ExecutionContext,id:string){return this.parties.has(id);}
}
const c=executionContext('company-1','branch-1','actor-1');
function fixture(){const repo=new InMemoryTravelerManagementRepository(),access=new Access(),linkage=new Linkage();let n=0;const service=new TravelerManagementApplicationService(repo,access,linkage,()=>new Date('2026-09-20T12:00:00Z'),()=>`id-${++n}`);return{service,repo,access,linkage};}

test('traveler identity is company-scoped while branch remains execution context',async()=>{const f=fixture();const t=await f.service.createTraveler(c,{fullName:'Ahmed Ali',customerId:'cust-1'});assert.equal(t.companyId,'company-1');assert.equal(t.partyId,'party-1');const otherBranch=await f.service.get(executionContext('company-1','branch-2','actor-1'),t.id);assert.equal(otherBranch.id,t.id);await assert.rejects(()=>f.service.get(executionContext('other','branch-1','actor-1'),t.id),/branch denied/);});
test('permissions are enforced server-side',async()=>{const f=fixture();f.access.denied=TRAVELER_PERMISSIONS.manage;await assert.rejects(()=>f.service.createTraveler(c,{fullName:'A'}),/permission denied/);});
test('customer and party linkage must resolve consistently',async()=>{const f=fixture();await assert.rejects(()=>f.service.createTraveler(c,{fullName:'A',customerId:'ghost'}),/customerId/);await assert.rejects(()=>f.service.createTraveler(c,{fullName:'A',partyId:'ghost'}),/partyId/);await assert.rejects(()=>f.service.createTraveler(c,{fullName:'A',customerId:'cust-1',partyId:'party-2'}),/does not match/);});
test('passport validation and company-scoped duplicate protection are deterministic',async()=>{const f=fixture();const a=await f.service.createTraveler(c,{fullName:'One'}),b=await f.service.createTraveler(c,{fullName:'Two'});await assert.rejects(()=>f.service.addDocument(c,a.id,{documentNumber:'??'}));await f.service.addDocument(c,a.id,{documentNumber:'ab-1234'});await assert.rejects(()=>f.service.addDocument(c,b.id,{documentNumber:'AB1234'}),/another traveler/);});
test('document renewal preserves immutable historical evidence',async()=>{const f=fixture();const t=await f.service.createTraveler(c,{fullName:'Traveler'});const old=await f.service.addDocument(c,t.id,{documentNumber:'A1111111',expiryDate:'2026-12-01'});const current=await f.service.addDocument(c,t.id,{documentNumber:'B2222222',expiryDate:'2031-12-01'});const docs=await f.service.listDocuments(c,t.id);assert.equal(docs.length,2);assert.equal(docs.find(x=>x.id===old.id)?.isCurrent,false);assert.equal(docs.find(x=>x.id===old.id)?.supersededByDocumentId,current.id);assert.equal(docs.find(x=>x.id===current.id)?.isCurrent,true);await assert.rejects(()=>f.service.addDocument(c,t.id,{documentNumber:'A1111111'}),/historical passport/);});
test('archived traveler cannot receive a new document',async()=>{const f=fixture();const t=await f.service.createTraveler(c,{fullName:'Traveler'});await f.service.archive(c,t.id);await assert.rejects(()=>f.service.addDocument(c,t.id,{documentNumber:'A1234567'}),/archived traveler/);});
test('legacy import is idempotent and preserves the same canonical result',async()=>{const f=fixture();const input={legacySourceSystem:'LEGACY',legacySourceReference:'C-1',companyId:c.companyId,branchId:c.branchId,fullName:'Legacy Traveler',customerId:'cust-1',documentNumber:'C3333333'};const first=await f.service.importLegacyPassport(c,input),second=await f.service.importLegacyPassport(c,input);assert.equal(first.status,'IMPORTED');assert.equal(second.status,'ALREADY_IMPORTED');if(first.status==='IMPORTED'&&second.status==='ALREADY_IMPORTED'){assert.equal(first.travelerId,second.travelerId);assert.equal(first.travelDocumentId,second.travelDocumentId);}});
test('conflicting legacy replay is reported and never overwritten',async()=>{const f=fixture();const input={legacySourceSystem:'LEGACY',legacySourceReference:'C-2',companyId:c.companyId,branchId:c.branchId,fullName:'Legacy Traveler',customerId:'cust-1',documentNumber:'D4444444'};await f.service.importLegacyPassport(c,input);const replay=await f.service.importLegacyPassport(c,{...input,fullName:'Changed'});assert.equal(replay.status,'CONFLICT');});
test('unresolved or ambiguous legacy linkage produces explicit review outcome',async()=>{const f=fixture();const noLink=await f.service.importLegacyPassport(c,{legacySourceSystem:'LEGACY',legacySourceReference:'C-3',companyId:c.companyId,branchId:c.branchId,fullName:'Unknown',documentNumber:'E5555555'});assert.equal(noLink.status,'UNRESOLVED_LINKAGE');await f.service.createTraveler(c,{fullName:'One',customerId:'cust-1'});await f.service.createTraveler(c,{fullName:'Two',customerId:'cust-1'});const ambiguous=await f.service.importLegacyPassport(c,{legacySourceSystem:'LEGACY',legacySourceReference:'C-4',companyId:c.companyId,branchId:c.branchId,fullName:'Ambiguous',customerId:'cust-1',documentNumber:'F6666666'});assert.equal(ambiguous.status,'UNRESOLVED_LINKAGE');});
test('legacy passport collision with another traveler is conflict, not duplicate creation',async()=>{const f=fixture();const existing=await f.service.createTraveler(c,{fullName:'Existing',customerId:'cust-2'});await f.service.addDocument(c,existing.id,{documentNumber:'G7777777'});const outcome=await f.service.importLegacyPassport(c,{legacySourceSystem:'LEGACY',legacySourceReference:'C-5',companyId:c.companyId,branchId:c.branchId,fullName:'Legacy',customerId:'cust-1',documentNumber:'G7777777'});assert.equal(outcome.status,'CONFLICT');});
test('legacy import refuses archived or conflicting existing traveler linkage',async()=>{const f=fixture();const archived=await f.service.createTraveler(c,{fullName:'Archived',customerId:'cust-1'});await f.service.archive(c,archived.id);const blocked=await f.service.importLegacyPassport(c,{legacySourceSystem:'LEGACY',legacySourceReference:'C-6',companyId:c.companyId,branchId:c.branchId,fullName:'Archived',customerId:'cust-1',documentNumber:'H8888888'});assert.equal(blocked.status,'UNRESOLVED_LINKAGE');const g=fixture();await g.service.createTraveler(c,{fullName:'Party-linked',partyId:'party-1'});const conflict=await g.service.importLegacyPassport(c,{legacySourceSystem:'LEGACY',legacySourceReference:'C-7',companyId:c.companyId,branchId:c.branchId,fullName:'Party-linked',customerId:'cust-2',partyId:'party-2',documentNumber:'J9999999'});assert.equal(conflict.status,'CONFLICT');});
