import test from 'node:test';
import assert from 'node:assert/strict';
import { companyId, decimalAmount } from '@elhafez/contracts';
import { FinancialControlsApplicationService, type ApprovalDecision, type ApprovalPolicy, type ApprovalRequest, type TrustedAuthorizationPort } from '@elhafez/financial-controls';
import type { PostingInstruction } from '@elhafez/general-ledger';
import { FinancialReportingApplicationService, FinancialReportingModule, type ReportingEvidence } from '@elhafez/financial-reporting';
import { branchId } from '@elhafez/contracts';
import { FinancialReportingEvidenceAdapter } from './financial-reporting-evidence.adapter.js';
import { TreasurySettlementApplicationService, type BankLine, type BankMatch, type CashCount, type Cheque, type Transfer, type Treasury, type TreasuryPolicy, type Voucher } from '@elhafez/treasury-settlement';
import { AppModule } from './app.module.js';

type Issue = { readonly id: string; readonly companyId: string; readonly runId: string; readonly evidenceKey: string; readonly sourceAmount: string; readonly ledgerAmount: string; readonly difference: string; readonly detail: string; readonly resolvedAt?: string; readonly resolutionReference?: string };
type Run = { readonly id: string; readonly companyId: string; readonly branchId?: string; readonly type: 'SUBLEDGER_TO_GL' | 'TAX_TO_GL' | 'INTEGRITY' | 'CLOSE_READINESS'; readonly correlationId: string; readonly fingerprint: string; readonly clean: boolean; readonly runAt: string };
type CloseRun = { readonly id: string; readonly companyId: string; readonly branchId?: string; readonly correlationId: string; readonly fingerprint: string; readonly ready: boolean; readonly blockers: readonly string[]; readonly warnings: readonly string[]; readonly evaluatedAt: string };
type Evidence = { readonly id: string; readonly companyId: string; readonly kind: string; readonly subjectId: string; readonly detail: string; readonly occurredAt: string };
class ControlsRepository {
  policies = new Map<string, ApprovalPolicy>(); requests = new Map<string, ApprovalRequest>(); decisions = new Map<string, ApprovalDecision>(); runs = new Map<string, { run: Run; issues: readonly Issue[] }>(); issues = new Map<string, Issue>(); closes = new Map<string, CloseRun>(); evidence: Evidence[] = [];
  async savePolicy(v: ApprovalPolicy) { this.policies.set(`${v.companyId}:${v.action}`, v); } async findPolicy(c: string, a: string) { return this.policies.get(`${c}:${a}`); }
  async saveRequest(v: ApprovalRequest) { this.requests.set(`${v.companyId}:${v.id}`, v); } async findRequest(c: string, id: string) { return this.requests.get(`${c}:${id}`); }
  async saveDecision(v: ApprovalDecision) { this.decisions.set(`${v.companyId}:${v.requestId}`, v); } async findDecision(c: string, id: string) { return this.decisions.get(`${c}:${id}`); }
  async saveRun(v: Run, issues: readonly Issue[]) { this.runs.set(`${v.companyId}:${v.correlationId}`, { run: v, issues }); for (const issue of issues) this.issues.set(`${issue.companyId}:${issue.id}`, issue); }
  async findRun(c: string, id: string) { return this.runs.get(`${c}:${id}`); } async findIssue(c: string, id: string) { return this.issues.get(`${c}:${id}`); }
  async resolveIssue(c: string, id: string, at: string, reference: string) { const old = this.issues.get(`${c}:${id}`); if (!old) throw new Error('missing issue'); const value = { ...old, resolvedAt: at, resolutionReference: reference }; this.issues.set(`${c}:${id}`, value); return value; }
  async saveCloseRun(v: CloseRun) { this.closes.set(`${v.companyId}:${v.correlationId}`, v); return v; } async findCloseRun(c: string, id: string) { return this.closes.get(`${c}:${id}`); } async saveEvidence(v: Evidence) { this.evidence.push(v); }
}
class Authorization implements TrustedAuthorizationPort { async canApprove() { return false; } async canAccessBranch(actor: string, company: string, branch: string) { return actor === 'operator' && company === 'company-1' && branch === 'branch-1'; } async canResolveControlIssue(actor: string) { return actor === 'supervisor'; } }
class TreasuryRepository {
  treasuryRows = new Map<string, Treasury>(); voucherRows = new Map<string, Voucher>(); policies = new Map<string, TreasuryPolicy>();
  key(c: string, id: string) { return `${c}:${id}`; } async treasury(c: string, id: string) { return this.treasuryRows.get(this.key(c, id)); } async treasuries(c: string) { return [...this.treasuryRows.values()].filter((x) => x.companyId === c); } async saveTreasury(v: Treasury) { this.treasuryRows.set(this.key(v.companyId, v.id), v); } async deactivateTreasury(v: Treasury) { await this.saveTreasury(v); return v; }
  async policy(c: string) { return this.policies.get(c); } async savePolicy(v: TreasuryPolicy) { this.policies.set(v.companyId, v); }
  async voucher(c: string, id: string) { return this.voucherRows.get(this.key(c, id)); } async voucherBySource(c: string, type: string, id: string) { return [...this.voucherRows.values()].find((x) => x.companyId === c && x.sourceType === type && x.sourceId === id); } async vouchers(c: string, treasuryId?: string) { return [...this.voucherRows.values()].filter((x) => x.companyId === c && (!treasuryId || x.treasuryId === treasuryId)); } async reserveVoucher(v: Voucher) { await this.saveVoucher(v); return v; } async saveVoucher(v: Voucher) { this.voucherRows.set(this.key(v.companyId, v.id), v); }
  async transferBySource(): Promise<Transfer | undefined> { return undefined; } async transfers(): Promise<Transfer[]> { return []; } async reserveTransfer(v: Transfer) { return v; } async saveTransfer() {} async createCheque() {} async saveCheque() {} async cheque(): Promise<Cheque | undefined> { return undefined; } async cashCount(): Promise<CashCount | undefined> { return undefined; } async cashCounts(): Promise<CashCount[]> { return []; } async saveCashCount() {} async saveBankLine() {} async bankLine(): Promise<BankLine | undefined> { return undefined; } async bankLines(): Promise<BankLine[]> { return []; } async saveBankMatchEffect() {} async bankMatch(): Promise<BankMatch | undefined> { return undefined; }
}
function fixture() {
  const controlsRepository = new ControlsRepository(); const controls = new FinancialControlsApplicationService(controlsRepository, new Authorization()); const treasuryRepository = new TreasuryRepository();
  const billing = { async settle(input: { id: string }) { return { settlementId: input.id, allocations: [{ id: 'allocation-1', companyId: companyId('company-1'), partyKind: 'CUSTOMER' as const, partyId: 'customer-1', amount: decimalAmount('10'), appliedAmount: decimalAmount('10'), advanceAmount: decimalAmount('0'), sourceType: 'TREASURY_SETTLEMENT', sourceId: input.id, requestHash: 'hash' }], carryingBaseAmount: decimalAmount('10'), prefundingBaseAmount: decimalAmount('0'), advanceBaseAmount: decimalAmount('0'), settlementBaseAmount: decimalAmount('10'), realizedFx: decimalAmount('0') }; }, async reverseSettlement() { return []; } };
  const gl = { async post(input: PostingInstruction) { return { ...input, kind: input.kind ?? 'STANDARD' as const, requestHash: 'hash', lines: input.lines.map((line, index) => ({ id: `${input.id}:${index}`, ...line })) }; }, async reverse(company: ReturnType<typeof companyId>, id: string, postingDate: string, number: string) { return { id: `reversal:${id}`, companyId: company, number, postingDate, kind: 'REVERSAL' as const, sourceType: 'JOURNAL_REVERSAL', sourceId: id, requestHash: 'hash', reversalOfId: id, lines: [] }; } };
  const approval = { async evaluateApprovalRequirement() { return { decision: 'APPROVAL_NOT_REQUIRED' as const }; }, async getApprovalRequest() { return undefined; }, async getApprovalDecision() { return undefined; } };
  const treasury = new TreasurySettlementApplicationService(treasuryRepository, billing, gl, approval); return { controls, controlsRepository, treasury, treasuryRepository };
}
async function mutateThroughGuard(f: ReturnType<typeof fixture>, targetBranchId: string, targetCompanyId = 'company-1') {
  const guard = await f.controls.evaluateFinancialMutation({ executionCompanyId: 'company-1', executionBranchId: 'branch-1', actorId: 'operator', sourceReference: 'TREASURY_VOUCHER:voucher-1', targetCompanyId, targetBranchId, lifecycle: 'DRAFT', collection: true, mutation: 'CREATE' });
  if (guard.decision === 'DENIED') return guard;
  return f.treasury.postVoucher({ id: `voucher-${targetBranchId}`, companyId: companyId(targetCompanyId), branchId: targetBranchId, treasuryId: 'cash', kind: 'RECEIPT', partyKind: 'CUSTOMER', partyId: 'customer-1', number: 'R-1', postingDate: '2026-09-20', amount: decimalAmount('10'), sourceType: 'CUSTOMER_RECEIPT', sourceId: `receipt-${targetBranchId}`, controlAccountId: 'ar' });
}

test('AC-13 Financial Reporting is registered through its public boundary', () => { const imports = Reflect.getMetadata('imports', AppModule) as readonly unknown[]; assert.ok(imports.includes(FinancialReportingModule)); });
test('BR-072/073 real Treasury record remains immutable, direct deletion is denied, and owner void retains history', async () => { const f = fixture(); await f.treasury.createTreasury({ id: 'cash', companyId: companyId('company-1'), code: 'CASH', name: 'Cash', type: 'CASH', currency: 'USD', glAccountId: 'cash-account' }); const posted = await mutateThroughGuard(f, 'branch-1'); assert.equal('status' in posted && posted.status, 'POSTED'); const before = await f.treasuryRepository.voucher('company-1', 'voucher-branch-1'); const update = await f.controls.evaluateFinancialMutation({ executionCompanyId: 'company-1', executionBranchId: 'branch-1', actorId: 'operator', sourceReference: 'TREASURY_VOUCHER:voucher-branch-1', targetCompanyId: 'company-1', targetBranchId: 'branch-1', lifecycle: 'POSTED', collection: true, mutation: 'UPDATE' }); assert.equal(update.reason, 'PERMANENT_FINANCIAL_RECORD_IMMUTABLE'); assert.deepEqual(await f.treasuryRepository.voucher('company-1', 'voucher-branch-1'), before); const deletion = await f.controls.evaluateFinancialMutation({ executionCompanyId: 'company-1', executionBranchId: 'branch-1', actorId: 'operator', sourceReference: 'TREASURY_VOUCHER:voucher-branch-1', targetCompanyId: 'company-1', targetBranchId: 'branch-1', lifecycle: 'PERMANENT', collection: true, mutation: 'DELETE' }); assert.equal(deletion.reason, 'PERMANENT_COLLECTION_DELETE_DENIED'); const reversed = await f.treasury.voidVoucher(companyId('company-1'), 'voucher-branch-1', '2026-09-21', 'VOID-1'); assert.equal(reversed.status, 'REVERSED'); assert.equal((await f.treasuryRepository.vouchers('company-1')).length, 1); assert.ok(reversed.reversalJournalId); });
test('BR-074 permitted branch succeeds while cross-branch and cross-company attempts leave owner state unchanged', async () => { const f = fixture(); await f.treasury.createTreasury({ id: 'cash', companyId: companyId('company-1'), code: 'CASH', name: 'Cash', type: 'CASH', currency: 'USD', glAccountId: 'cash-account' }); assert.equal('status' in await mutateThroughGuard(f, 'branch-1'), true); const count = (await f.treasuryRepository.vouchers('company-1')).length; const deniedBranch = await mutateThroughGuard(f, 'branch-2'); assert.ok('reason' in deniedBranch); assert.equal(deniedBranch.reason, 'BRANCH_SCOPE_DENIED'); const deniedCompany = await mutateThroughGuard(f, 'branch-1', 'company-2'); assert.ok('reason' in deniedCompany); assert.equal(deniedCompany.reason, 'COMPANY_SCOPE_MISMATCH'); assert.equal((await f.treasuryRepository.vouchers('company-1')).length, count); });
test('BR-075 Controls denies generic repair and records only a supervised owner reversal reference', async () => { const f = fixture(); await f.treasury.createTreasury({ id: 'cash', companyId: companyId('company-1'), code: 'CASH', name: 'Cash', type: 'CASH', currency: 'USD', glAccountId: 'cash-account' }); await mutateThroughGuard(f, 'branch-1'); const result = await f.controls.evaluateIntegrity({ id: 'integrity-1', companyId: 'company-1', correlationId: 'integrity-1', comparisons: [{ key: 'TREASURY_VOUCHER:voucher-branch-1', sourceAmount: '10', ledgerAmount: '9' }] }); const issueId = result.issues[0]!.id; assert.equal(f.controls.evaluateAutoFix().decision, 'DENIED'); await assert.rejects(f.controls.resolveControlIssue({ companyId: 'company-1', issueId, actorId: 'supervisor', resolutionMode: 'SUPERVISED' }), /evidence is required/); await assert.rejects(f.controls.resolveControlIssue({ companyId: 'company-1', issueId, actorId: 'intruder', resolutionMode: 'SUPERVISED', ownerReference: 'TREASURY_REVERSAL:pending' }), /authority/); const owner = await f.treasury.voidVoucher(companyId('company-1'), 'voucher-branch-1', '2026-09-21', 'VOID-1'); const reference = `TREASURY_REVERSAL:${owner.reversalJournalId}`; const resolved = await f.controls.resolveControlIssue({ companyId: 'company-1', issueId, actorId: 'supervisor', resolutionMode: 'SUPERVISED', ownerReference: reference }); assert.equal(resolved.resolutionReference, reference); assert.equal((await f.treasuryRepository.voucher('company-1', 'voucher-branch-1'))?.status, 'REVERSED'); });

test('trusted composition adapter projects owner public evidence without recomputing owner truth', async () => {
  const owner = fixture();
  await owner.treasury.createTreasury({ id: 'cash', companyId: companyId('company-1'), code: 'CASH', name: 'Cash', type: 'CASH', currency: 'USD', glAccountId: 'cash-account' });
  const posted = await mutateThroughGuard(owner, 'branch-1');
  assert.ok('status' in posted);
  const rows = new Map<string, ReportingEvidence>();
  const projection = { async find(c: ReturnType<typeof companyId>, id: string) { return rows.get(`${c}:${id}`); }, async save(value: ReportingEvidence) { rows.set(`${value.companyId}:${value.evidenceId}`, value); }, async list(c: ReturnType<typeof companyId>) { return [...rows.values()].filter((value) => value.companyId === c); }, async replaceCompany(c: ReturnType<typeof companyId>, values: readonly ReportingEvidence[]) { for (const [key, value] of rows) if (value.companyId === c) rows.delete(key); for (const value of values) rows.set(`${value.companyId}:${value.evidenceId}`, value); } };
  const reporting = new FinancialReportingApplicationService(projection);
  const adapter = new FinancialReportingEvidenceAdapter(reporting);
  await adapter.consumeVoucher(posted);
  const report = await reporting.treasury({ companyId: companyId('company-1'), branchIds: [branchId('branch-1')] });
  assert.equal(report.activity[0]?.voucherId, posted.id);
  assert.equal(report.activity[0]?.allocationReferences[0]?.sourceId, 'allocation-1');
});
