export const LEGACY_ADMIN_SOURCE={repository:'mhafez300300-byte/Elhafez-Tourism-Offline',commit:'e97fa6d9cb52acb22b676e1b975c1b2332bc9a13',version:'v32.5.66'} as const;
export type LegacyCoverageDisposition='PROCESS'|'UNSUPPORTED'|'NON_APPLICABLE'|'AMBIGUOUS'|'NEEDS_EVIDENCE';
type Rule={sourceCollection:string;shape:'object'|'array';owner:string;targetKind:string;strategy:string;disposition:LegacyCoverageDisposition};
const processRules:readonly Rule[]=[
 {sourceCollection:'company',shape:'object',owner:'platform-core',targetKind:'company',strategy:'map-profile',disposition:'PROCESS'},
 {sourceCollection:'settings',shape:'object',owner:'platform-core',targetKind:'configuration',strategy:'explicit-generic-allowlist',disposition:'PROCESS'},
 {sourceCollection:'branches',shape:'array',owner:'platform-core',targetKind:'branch',strategy:'map-company-branch',disposition:'PROCESS'},
 {sourceCollection:'notificationPrefs',shape:'object',owner:'platform-core',targetKind:'notification-preference',strategy:'map-preference',disposition:'PROCESS'},
 {sourceCollection:'attachments',shape:'array',owner:'platform-core',targetKind:'file-metadata',strategy:'metadata-only-binary-unverified',disposition:'PROCESS'},
 {sourceCollection:'users',shape:'array',owner:'platform-core',targetKind:'user',strategy:'create-disabled-and-recover',disposition:'PROCESS'},
 {sourceCollection:'auditLog',shape:'array',owner:'platform-core',targetKind:'historical-audit-evidence',strategy:'preserve-history',disposition:'PROCESS'},
 {sourceCollection:'dataImports',shape:'array',owner:'data-exchange',targetKind:'historical-import-evidence',strategy:'preserve-history',disposition:'PROCESS'},
];
/** Frozen v32.5.66 roots owned by Accounting, CRM, Tourism, Hajj/Umrah or other phases. */
export const LEGACY_NON_APPLICABLE_SOURCES=Object.freeze([
 'accounts','accountingPeriods','agents','bookings','buses','busTypes','cashboxes','categories','cheques','clients','commissions','contracts','costCenters','currencies','customerPayments','customers','dailyTasks','employees','expenses','financialEntries','flightBookings','flights','groups','hajjBookings','hajjPrograms','hotels','hotelBookings','invoices','journalEntries','leads','nationalities','packages','passports','payments','priceLists','programs','purchaseOrders','quotations','receipts','reservations','roomingLists','rooms','sales','seasons','services','suppliers','supplierPayments','tasks','tours','transactions','transportations','travelers','treasuryTransactions','trips','umrahBookings','umrahPrograms','visaApplications','visas','vouchers'
]);
const nonApplicableRules:readonly Rule[]=LEGACY_NON_APPLICABLE_SOURCES.map(sourceCollection=>({sourceCollection,shape:'array',owner:'other-module',targetKind:'none',strategy:'classified-only',disposition:'NON_APPLICABLE'}));
export const LEGACY_ADMIN_COVERAGE=Object.freeze([...processRules,...nonApplicableRules]);
export const PLATFORM_SETTINGS_ALLOWLIST=Object.freeze(['locale','timezone','dateFormat','theme','companyName','companyLogo','address','phone','email'] as const);
export const PLATFORM_SETTINGS_EXCLUSIONS=Object.freeze(['baseCurrency','preventNegativeTreasury','fiscalYearStartMonth','approvalPayments','allowSelfApproval','expenseCategories','prefixes'] as const);
export function assertLegacyAdminCoverage(discovered:readonly string[]){const known=new Set(LEGACY_ADMIN_COVERAGE.map(x=>x.sourceCollection));const omitted=discovered.filter(x=>!known.has(x));if(omitted.length)throw new Error(`Unclassified legacy administration sources: ${omitted.join(', ')}`)}
export interface LegacyAdminSink{write(owner:string,kind:string,record:Readonly<Record<string,unknown>>):Promise<void>}
function recordsFor(rule:Rule,value:unknown):ReadonlyArray<Record<string,unknown>>{if(rule.shape==='array'){if(!Array.isArray(value))throw new Error(`Invalid ${rule.sourceCollection} shape: expected array`);return value.map(raw=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error(`Invalid ${rule.sourceCollection} record`);return raw as Record<string,unknown>})}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`Invalid ${rule.sourceCollection} shape: expected object`);return[value as Record<string,unknown>]}
/** Maps only administration-owned evidence. It never invents credentials, bytes, checksums or storage keys. */
export async function migrateLegacyAdministration(source:Readonly<Record<string,unknown>>,sink:LegacyAdminSink){assertLegacyAdminCoverage(Object.keys(source));let processed=0;for(const rule of processRules){const value=source[rule.sourceCollection];if(value===undefined)continue;for(const raw of recordsFor(rule,value)){let record={...raw};delete record.password;delete record.passwordHash;delete record.token;if(rule.sourceCollection==='settings')record=Object.fromEntries(PLATFORM_SETTINGS_ALLOWLIST.filter(key=>Object.hasOwn(raw,key)).map(key=>[key,raw[key]]));if(rule.sourceCollection==='attachments'){delete record.bytes;delete record.content;delete record.data;delete record.storageKey;record={...record,metadataMigrated:true,binaryVerified:false,binaryStatus:'UNAVAILABLE_OR_UNVERIFIED'}}await sink.write(rule.owner,rule.targetKind,{...record,legacySource:rule.sourceCollection,credentialResetRequired:rule.sourceCollection==='users'||undefined,historical:rule.sourceCollection==='auditLog'||rule.sourceCollection==='dataImports'||undefined});processed++}}return{processed,source:LEGACY_ADMIN_SOURCE}}
