import assert from'node:assert/strict';
import test from'node:test';
import{ReportDeliveryController}from'./report-delivery.controller.js';

function fixture(channel:'IN_APP'|'EMAIL'='IN_APP',enabled=true){const seen:{notify?:readonly unknown[];authorized?:readonly unknown[];branch?:readonly unknown[]}={};const reporting={listSchedules:async()=>[{id:'schedule-1',companyId:'company-a',savedReportId:'report-1',cadence:'DAILY',hourUtc:8,weekday:null,dayOfMonth:null,channel,recipient:channel==='EMAIL'?'finance@example.test':null,enabled,createdBy:'owner-a',createdAt:'2026-09-29T00:00:00Z',updatedAt:'2026-09-29T00:00:00Z'}],listSavedReports:async()=>[{id:'report-1',companyId:'company-a',ownerActorId:'owner-a',name:'كشف عميل',reportKey:'CUSTOMER_STATEMENT',filters:{scope:'CURRENT_COMPANY_BRANCH',partyId:'customer-a'},visibility:'COMPANY',active:true,createdAt:'2026-09-29T00:00:00Z',updatedAt:'2026-09-29T00:00:00Z'}]};const platform={currentUser:async()=>({id:'runner-a'}),requireBranchAccess:async(...args:unknown[])=>{seen.branch=args;},authorize:async(...args:unknown[])=>{seen.authorized=args;},notify:async(...args:unknown[])=>{seen.notify=args;return{id:'notification-1'};}};return{controller:new ReportDeliveryController(reporting as never,platform as never),seen};}

test('run-now delivers an enabled IN_APP schedule through platform notifications with branch context',async()=>{const{controller,seen}=fixture();const result=await controller.runNow('Bearer token','company-a','branch-a','schedule-1');assert.deepEqual(result,{status:'DELIVERED',channel:'IN_APP',notificationId:'notification-1'});assert.deepEqual(seen.branch,['runner-a','company-a','branch-a']);assert.equal(seen.authorized?.[2],'platform.configuration.manage');assert.equal(seen.notify?.[0],'owner-a');assert.equal(seen.notify?.[1],'REPORT_SCHEDULE_READY');assert.equal(seen.notify?.[3],'company-a');const payload=seen.notify?.[2] as Record<string,unknown>;assert.equal(payload.route,'/management/reports');assert.equal(payload.deliveryBranchId,'branch-a');assert.equal(payload.reportKey,'CUSTOMER_STATEMENT');});

test('run-now refuses EMAIL schedules until a real email delivery integration exists',async()=>{const{controller,seen}=fixture('EMAIL');await assert.rejects(()=>controller.runNow('Bearer token','company-a','branch-a','schedule-1'),/email delivery integration is not configured/);assert.equal(seen.notify,undefined);});

test('run-now refuses disabled schedules',async()=>{const{controller}=fixture('IN_APP',false);await assert.rejects(()=>controller.runNow('Bearer token','company-a','branch-a','schedule-1'),/schedule is disabled/);});