import {Body,Controller,Delete,Get,Headers,Inject,Optional,Param,Patch,Post,UnauthorizedException} from '@nestjs/common';
import {executionContext,type ExecutionContext} from '@elhafez/contracts';
import {PlatformCoreApplicationService} from '@elhafez/platform-core';
import {DataExchangeApplicationService,type ExportSource,type ExportStorage,type ImportTarget} from '@elhafez/data-exchange';
import {PlatformOperationsApplicationService} from '@elhafez/platform-operations';
export const SYSTEM_ADMIN_EXCHANGE_TARGET=Symbol('SYSTEM_ADMIN_EXCHANGE_TARGET');
export const SYSTEM_ADMIN_EXPORT_SOURCE=Symbol('SYSTEM_ADMIN_EXPORT_SOURCE');
export const SYSTEM_ADMIN_EXPORT_STORAGE=Symbol('SYSTEM_ADMIN_EXPORT_STORAGE');
export const SYSTEM_ADMIN_PERMISSIONS={usersRead:'platform.users.read',usersManage:'platform.users.manage',rolesRead:'platform.roles.read',rolesManage:'platform.roles.manage',companiesRead:'platform.companies.read',companiesManage:'platform.companies.manage',branchesRead:'platform.branches.read',branchesManage:'platform.branches.manage',auditRead:'platform.audit.read',sessionsRead:'platform.sessions.read',sessionsManage:'platform.sessions.manage',notificationsRead:'platform.notifications.read',filesRead:'platform.files.read',filesManage:'platform.files.manage',configurationRead:'platform.configuration.read',configurationManage:'platform.configuration.manage',dataExchangeRead:'data_exchange.read',dataExchangeManage:'data_exchange.manage',operationsRead:'platform_operations.read',backupCreate:'platform_operations.backup.create',restoreCreate:'platform_operations.restore.create'} as const;
type Headers3={a:string|undefined;c:string|undefined;b:string|undefined};
@Controller('system-administration')
export class SystemAdministrationController{
 constructor(@Inject(PlatformCoreApplicationService) private readonly platform:PlatformCoreApplicationService,@Inject(DataExchangeApplicationService) private readonly exchange:DataExchangeApplicationService,@Inject(PlatformOperationsApplicationService) private readonly operations:PlatformOperationsApplicationService,@Optional() @Inject(SYSTEM_ADMIN_EXCHANGE_TARGET) private readonly importTarget?:ImportTarget,@Optional() @Inject(SYSTEM_ADMIN_EXPORT_SOURCE) private readonly exportSource?:ExportSource,@Optional() @Inject(SYSTEM_ADMIN_EXPORT_STORAGE) private readonly exportStorage?:ExportStorage){}
 @Post('recovery/request') async requestRecovery(@Body()body:{email:string}){try{await this.platform.requestPasswordRecovery(body.email)}catch(error){void error}return{accepted:true}}
 @Post('recovery/reset') async resetPassword(@Body()body:{token:string;password:string}){await this.platform.resetPassword(body.token,body.password);return{reset:true}}
 private h(a:string|undefined,c:string|undefined,b:string|undefined):Headers3{return{a,c,b}}
 @Get('users') async users(@Headers('authorization') a:string|undefined,@Headers('x-company-id') c:string|undefined,@Headers('x-branch-id') b:string|undefined):Promise<unknown>{const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.usersRead);return this.platform.listUsers(x.companyId)}
 @Get('users/:id') async user(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string):Promise<unknown>{const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.usersRead);return this.platform.getUser(x.companyId,id)}
 @Post('users') async createUser(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{email:string;password:string;displayName:string;roleId?:string}):Promise<unknown>{const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.usersManage);const user=await this.platform.createUser({...body,actorId:x.actorId});if(body.roleId)await this.platform.assignRole(user.id,x.companyId,body.roleId);return user}
 @Patch('users/:id') async updateUser(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Body()body:{email?:string;displayName?:string;active?:boolean}):Promise<unknown>{const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.usersManage);await this.platform.requireUserCompanyAccess(id,x.companyId);if(body.active!==undefined)await this.platform.setUserActive(x.actorId,id,body.active);return this.platform.updateUser(x.actorId,id,body)}
 @Post('users/:id/roles/:roleId') async assignRole(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Param('roleId')roleId:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesManage);await this.platform.assignRole(id,x.companyId,roleId);return{assigned:true}}
 @Delete('users/:id/roles/:roleId') async revokeRole(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Param('roleId')roleId:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesManage);await this.platform.revokeRole(id,x.companyId,roleId);return{revoked:true}}
 @Get('roles') async roles(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesRead);return this.platform.listRoles()}
 @Get('roles/:id') async role(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesRead);const role=(await this.platform.listRoles()).find(x=>x.id===id);if(!role)throw new Error('role not found');return role}
 @Get('permissions') async permissions(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesRead);return this.platform.listPermissions()}
 @Post('roles') async createRole(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{name:string}){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesManage);return{id:await this.platform.createRole(body.name)}}
 @Post('roles/:roleId/permissions/:permissionId') async grantPermission(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('roleId')r:string,@Param('permissionId')p:string){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesManage);await this.platform.grantPermission(r,p);return{granted:true}}
 @Delete('roles/:roleId/permissions/:permissionId') async revokePermission(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('roleId')r:string,@Param('permissionId')p:string){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.rolesManage);await this.platform.revokePermission(r,p);return{revoked:true}}
 @Get('companies') async companies(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.companiesRead);return this.platform.listCompanies(x.actorId)}
 @Get('companies/:id') async company(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.companiesRead);return this.platform.getCompany(x.actorId,id)}
 @Post('companies') async createCompany(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{name:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.companiesManage);return this.platform.createCompany(x.actorId,body.name)}
 @Patch('companies/:id') async updateCompany(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Body()body:{name?:string;active?:boolean}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.companiesManage);if(id!==x.companyId)throw new UnauthorizedException('company context mismatch');return this.platform.updateCompany(x.actorId,id,body)}
 @Get('branches') async branches(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesRead);return this.platform.listBranches(x.companyId)}
 @Get('branches/:id') async branch(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesRead);return this.platform.getBranch(x.companyId,id)}
 @Post('branches') async createBranch(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{name:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesManage);return this.platform.createBranch(x.actorId,x.companyId,body.name)}
 @Patch('branches/:id') async updateBranch(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Body()body:{name?:string;active?:boolean}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesManage);return this.platform.updateBranch(x.actorId,x.companyId,id,body)}
 @Post('branches/:id/access/:userId') async grantBranch(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Param('userId')u:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesManage);await this.platform.getBranch(x.companyId,id);await this.platform.requireUserCompanyAccess(u,x.companyId);await this.platform.grantBranchAccess(u,id);return{granted:true}}
 @Delete('branches/:id/access/:userId') async revokeBranch(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Param('userId')u:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.branchesManage);await this.platform.getBranch(x.companyId,id);await this.platform.revokeBranchAccess(u,id);return{revoked:true}}
 @Get('audit') async audit(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.auditRead);return this.platform.listAudit(x.companyId)}
 @Get('sessions/:userId') async sessions(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('userId')u:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.sessionsRead);await this.platform.requireUserCompanyAccess(u,x.companyId);return this.platform.listSessions(u)}
 @Get('sessions') async ownSessions(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.sessionsRead);return this.platform.listSessions(x.actorId)}
 @Post('sessions/:id/revoke') async revokeSession(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.sessionsManage);await this.platform.revokeSession(x.actorId,x.companyId,id);return{revoked:true}}
 @Post('users/:id/sessions/revoke') async revokeUserSessions(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.sessionsManage);await this.platform.requireUserCompanyAccess(id,x.companyId);await this.platform.revokeUserSessions(x.actorId,id);return{revoked:true}}
 @Get('notifications') async notifications(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.notificationsRead);return this.platform.listNotifications(x.actorId)}
 @Post('notifications/:id/read') async readNotification(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.notificationsRead);return this.platform.markNotificationRead(x.actorId,id)}
 @Get('files') async files(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.filesRead);return this.platform.listFiles(x.companyId)}
 @Get('files/:id') async file(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.filesRead);return this.platform.getFile(x.companyId,id,true)}
 @Post('files') async uploadFile(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{contentType:string;contentBase64:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.filesManage);if(!body.contentBase64)throw new Error('file content is required');return this.platform.uploadFile({contentType:body.contentType,content:Buffer.from(body.contentBase64,'base64'),companyId:x.companyId,createdBy:x.actorId})}
 @Delete('files/:id') async retireFile(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.filesManage);await this.platform.retireFile(x.companyId,id);return{retired:true}}
 @Get('configuration/:key') async configuration(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('key')key:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.configurationRead);return{key,value:await this.platform.getConfiguration(key,x.companyId)}}
 @Post('configuration/:key') async configure(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('key')key:string,@Body()body:{value:unknown}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.configurationManage);await this.platform.setConfiguration(key,body.value,x.companyId);return{key,value:body.value}}
 @Get('imports') async imports(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeRead);return this.exchange.list(x.companyId)}
 @Get('imports/:id') async importJob(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeRead);return this.exchange.get(x.companyId,id)}
 @Post('imports') async uploadImport(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{fileName:string;format:'CSV'|'XLSX';contentBase64:string;mapping:Record<string,string>;idempotencyKey:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeManage);if(!body.contentBase64)throw new Error('import content is required');return this.exchange.ingest({fileName:body.fileName,format:body.format,content:Buffer.from(body.contentBase64,'base64'),mapping:body.mapping,idempotencyKey:body.idempotencyKey,companyId:x.companyId,branchId:x.branchId})}
 @Post('imports/:id/preview') async preview(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Body()body:{required:string[]}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeManage);return this.exchange.preview(x.companyId,id,body.required)}
 @Post('imports/:id/execute') async execute(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeManage);if(!this.importTarget)throw new Error('import target is unavailable');return this.exchange.execute(x.companyId,id,this.importTarget)}
 @Post('exports') async exportData(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{fileName:string;format:'CSV'|'XLSX';idempotencyKey:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.dataExchangeManage);if(!this.exportSource||!this.exportStorage)throw new Error('export boundary is unavailable');return this.exchange.createExport({...body,companyId:x.companyId,branchId:x.branchId},this.exportSource,this.exportStorage)}
 @Get('operations/diagnostics') async diagnostics(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.operationsRead);return this.operations.diagnostics()}
 @Get('operations/backups') async backups(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.operationsRead);return this.operations.listBackups(x.companyId)}
 @Get('operations/backups/:id') async backupById(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.operationsRead);return this.operations.getBackup(x.companyId,id)}
 @Post('operations/backups') async backup(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{pin?:boolean}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.backupCreate);return this.operations.createBackup({actorId:x.actorId,companyId:x.companyId,pin:body.pin})}
 @Post('operations/backups/:id/verify') async verify(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.backupCreate);return this.operations.verifyBackup(x.companyId,id)}
 @Post('operations/backups/:id/pin') async pin(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string,@Body()body:{pinned:boolean}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.backupCreate);return this.operations.setPinned(x.companyId,id,body.pinned)}
 @Post('operations/restores') async restore(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{backupId:string}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.restoreCreate);return this.operations.restore({backupId:body.backupId,actorId:x.actorId,expectedCompanyId:x.companyId})}
 @Post('operations/restores/:id/preflight') async restorePreflight(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.restoreCreate);return this.operations.preflight({backupId:id,expectedCompanyId:x.companyId})}
 @Post('operations/backups/retention') async retention(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Body()body:{retain:number}){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.backupCreate);return this.operations.cleanup(x.companyId,body.retain)}
 @Get('operations/restores/:id') async restoreStatus(@Headers('authorization')a:string|undefined,@Headers('x-company-id')c:string|undefined,@Headers('x-branch-id')b:string|undefined,@Param('id')id:string){const x=await this.ctx(this.h(a,c,b),SYSTEM_ADMIN_PERMISSIONS.operationsRead);return this.operations.getRestore(x.companyId,id)}
 private async ctx(headers:Headers3,permission:string):Promise<ExecutionContext>{if(!headers.a?.startsWith('Bearer ')||!headers.c||!headers.b)throw new UnauthorizedException('authenticated company and branch context required');const user=await this.platform.currentUser(headers.a.slice(7));const context=executionContext(headers.c,headers.b,user.id);await this.platform.requireBranchAccess(context.actorId,context.companyId,context.branchId);await this.platform.authorize(context.actorId,context.companyId,permission);return context}
}
