import{Body,Controller,Get,Headers,Inject,Param,Patch,Post,Query,UnauthorizedException}from'@nestjs/common';
import{executionContext,type ExecutionContext}from'@elhafez/contracts';
import{PlatformCoreApplicationService}from'@elhafez/platform-core';
import{TourismProgramsApplicationService,type TourismProgramInput,type TourismProgramStatus}from'@elhafez/tourism-programs';
import{TourismItinerariesApplicationService,type ItineraryDayInput}from'@elhafez/tourism-itineraries';
import{TourismBookingsApplicationService,type BookingFinanceConfirmInput,type CreateTourismBookingInput,type TourismBookingStatus}from'@elhafez/tourism-bookings';

@Controller('tourism')
export class TourismOperationsController{
 constructor(@Inject(PlatformCoreApplicationService) private readonly platform:PlatformCoreApplicationService,@Inject(TourismProgramsApplicationService) private readonly programs:TourismProgramsApplicationService,@Inject(TourismItinerariesApplicationService) private readonly itineraries:TourismItinerariesApplicationService,@Inject(TourismBookingsApplicationService) private readonly bookings:TourismBookingsApplicationService){}
 private async context(auth?:string,companyId?:string,branchId?:string):Promise<ExecutionContext>{if(!auth?.startsWith('Bearer ')||!companyId||!branchId)throw new UnauthorizedException('authenticated company and branch context required');const user=await this.platform.currentUser(auth.slice(7));return executionContext(companyId,branchId,user.id)}
 @Get('programs')async listPrograms(@Headers('authorization')a?:string,@Headers('x-company-id')c?:string,@Headers('x-branch-id')b?:string,@Query('status')status?:TourismProgramStatus){return this.programs.list(await this.context(a,c,b),status)}
 @Post('programs')async createProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Body()input:TourismProgramInput){return this.programs.create(await this.context(a,c,b),input)}
 @Patch('programs/:id')async updateProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:TourismProgramInput){return this.programs.update(await this.context(a,c,b),id,input)}
 @Get('programs/:id/commercial')async commercial(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.programs.commercial(await this.context(a,c,b),id)}
 @Patch('programs/:id/commercial')async configureCommercial(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{totalCapacity?:number|null;waitlistEnabled?:boolean;priceTiers?:readonly{code:string;label:string;sellingPrice:string;estimatedCost:string;capacity?:number|null;active?:boolean}[];addOnServiceIds?:readonly string[];discountPolicy?:{maxPercent:number;approvalAbovePercent:number}}){return this.programs.configureCommercial(await this.context(a,c,b),id,input)}
 @Post('programs/:id/open')async openProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.programs.open(await this.context(a,c,b),id)}
 @Post('programs/:id/start')async startProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.programs.start(await this.context(a,c,b),id)}
 @Post('programs/:id/close')async closeProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.programs.close(await this.context(a,c,b),id)}
 @Post('programs/:id/cancel')async cancelProgram(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{reason:string;commandKey:string;postingDate:string}){return this.programs.cancel(await this.context(a,c,b),id,input)}
 @Get('programs/:id/itinerary')async itinerary(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.itineraries.list(await this.context(a,c,b),id)}
 @Post('programs/:id/itinerary')async createItinerary(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')programId:string,@Body()input:Omit<ItineraryDayInput,'programId'>){return this.itineraries.create(await this.context(a,c,b),{...input,programId})}
 @Patch('programs/:programId/itinerary/:id')async updateItinerary(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('programId')programId:string,@Param('id')id:string,@Body()input:Omit<ItineraryDayInput,'programId'>&{expectedRevision:number}){return this.itineraries.update(await this.context(a,c,b),id,{...input,programId},input.expectedRevision)}
 @Get('bookings')async listBookings(@Headers('authorization')a?:string,@Headers('x-company-id')c?:string,@Headers('x-branch-id')b?:string,@Query('status')status?:TourismBookingStatus){return this.bookings.list(await this.context(a,c,b),status)}
 @Post('bookings')async createBooking(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Body()input:CreateTourismBookingInput){return this.bookings.create(await this.context(a,c,b),input)}
 @Get('bookings/:id/extension')async bookingExtension(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.bookings.extension(await this.context(a,c,b),id)}
 @Patch('bookings/:id/extension')async updateBookingExtension(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{salesState?:'BOOKED'|'WAITLISTED';priceTierCode?:string|null;specialRequests?:string|null}){return this.bookings.updateExtension(await this.context(a,c,b),id,input)}
 @Get('bookings/:id/amendments')async amendments(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.bookings.amendments(await this.context(a,c,b),id)}
 @Post('bookings/:id/amendments')async amendment(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{kind:'TRAVELER'|'SERVICE'|'DATE'|'COMMERCIAL'|'OTHER';reason:string;detail:string;financeReference?:string}){return this.bookings.recordAmendment(await this.context(a,c,b),id,input)}
 @Get('bookings/:id/payment-plan')async paymentPlan(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.bookings.paymentPlan(await this.context(a,c,b),id)}
 @Post('bookings/:id/payment-plan')async setPaymentPlan(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{items:readonly{dueDate:string;amount:string}[]}){return this.bookings.setPaymentPlan(await this.context(a,c,b),id,input.items)}
 @Post('bookings/:id/payment-plan/:itemId/satisfy')async satisfyPayment(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Param('itemId')itemId:string,@Body()input:{evidenceReference:string}){return this.bookings.satisfyPaymentPlanItem(await this.context(a,c,b),id,itemId,input.evidenceReference)}
 @Post('bookings/:id/voucher')async issueVoucher(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{voucherNumber:string}){return this.bookings.issueVoucher(await this.context(a,c,b),id,input.voucherNumber)}
 @Post('bookings/:id/travel-pack')async issueTravelPack(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.bookings.issueTravelPack(await this.context(a,c,b),id)}
 @Post('bookings/:id/confirm')async confirmBooking(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:Omit<BookingFinanceConfirmInput,'companyId'|'branchId'|'bookingId'|'programId'|'programEvidence'|'customerPartyId'>){return this.bookings.confirm(await this.context(a,c,b),id,input)}
 @Post('bookings/:id/cancel')async cancelBooking(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string,@Body()input:{commandKey:string;postingDate:string}){return this.bookings.cancel(await this.context(a,c,b),id,input)}
 @Post('bookings/:id/complete')async completeBooking(@Headers('authorization')a:string,@Headers('x-company-id')c:string,@Headers('x-branch-id')b:string,@Param('id')id:string){return this.bookings.complete(await this.context(a,c,b),id)}
}
