import { ContractValidationError } from '@elhafez/contracts';
import type { CompanyId } from '@elhafez/contracts';
import type { EcrRepository } from '../application/ecr.repository.js';
import type { Expense, RecognitionSchedule, SchedulePart, CommissionClaim, CommissionPayment, Accrual, SupplierAdvanceSettlement } from '../domain/ecr.js';
const S=10n**18n;function n(v:string){const [w,f='']=v.split('.');return BigInt(w+f.padEnd(18,'0'))}function d(v:bigint){const neg=v<0n,a=neg?-v:v,w=a/S,f=a%S,t=f?w+'.'+f.toString().padStart(18,'0').replace(/0+$/,''):w.toString();return (neg?'-':'')+t}
export class InMemoryEcrRepository implements EcrRepository {
 expenses:Expense[]=[]; schedules:RecognitionSchedule[]=[]; claims:CommissionClaim[]=[]; accruals:Accrual[]=[]; supplierSettlements:SupplierAdvanceSettlement[]=[];
 private put<T extends{id:string;companyId:CompanyId}>(a:T[],v:T){const collision=a.find(x=>x.id===v.id&&x.companyId!==v.companyId);if(collision)throw new ContractValidationError('companyId','ID belongs to another company');const i=a.findIndex(x=>x.id===v.id&&x.companyId===v.companyId);if(i<0)a.push(v);else a[i]=v}
 async expense(c:CompanyId,id:string){return this.expenses.find(x=>x.companyId===c&&x.id===id)} async saveExpense(v:Expense){this.put(this.expenses,v)}
 async schedule(c:CompanyId,id:string){return this.schedules.find(x=>x.companyId===c&&x.id===id)}
 async scheduleByInvoice(c:CompanyId,invoiceId:string,kind:string){return this.schedules.find(x=>x.companyId===c&&x.sourceInvoiceId===invoiceId&&x.kind===kind)}
 async saveSchedule(v:RecognitionSchedule){const sourceCollision=this.schedules.find(x=>x.companyId===v.companyId&&x.id!==v.id&&x.kind===v.kind&&x.sourceType===v.sourceType&&x.sourceId===v.sourceId);const invoiceCollision=v.sourceInvoiceId?this.schedules.find(x=>x.companyId===v.companyId&&x.id!==v.id&&x.kind===v.kind&&x.sourceInvoiceId===v.sourceInvoiceId):undefined;if(sourceCollision||invoiceCollision)throw new ContractValidationError('schedule','duplicate economic schedule');this.put(this.schedules,v)}
 async setInitialJournalId(c:CompanyId,id:string,journalId:string){const s=this.schedules.find(x=>x.companyId===c&&x.id===id);if(!s)throw new ContractValidationError('schedule','not found');if(s.initialJournalId&&s.initialJournalId!==journalId)throw new ContractValidationError('journalId','conflicting initial deferral journal');this.put(this.schedules,{...s,initialJournalId:journalId})}
 async transitionRecognitionPart(c:CompanyId,scheduleId:string,partId:string,expectedStatus:SchedulePart['status'],expectedCycle:number,next:SchedulePart){const s=this.schedules.find(x=>x.companyId===c&&x.id===scheduleId);if(!s)throw new ContractValidationError('schedule','not found');const i=s.parts.findIndex(x=>x.id===partId);if(i<0)throw new ContractValidationError('part','not found');const current=s.parts[i]!;if(current.status===next.status&&current.cycle===next.cycle&&current.journalId===next.journalId&&current.reversalJournalId===next.reversalJournalId)return current;if(current.status!==expectedStatus||current.cycle!==expectedCycle)throw new ContractValidationError('part','changed while posting recognition');const parts=s.parts.map((x,index)=>index===i?next:x);this.put(this.schedules,{...s,parts});return next}
 async claim(c:CompanyId,id:string){return this.claims.find(x=>x.companyId===c&&x.id===id)} async saveClaim(v:CommissionClaim){this.put(this.claims,v)}
 async reserveCommissionPayment(c:CompanyId,id:string,p:CommissionPayment){const claim=this.claims.find(x=>x.companyId===c&&x.id===id);if(!claim)throw new ContractValidationError('claim','not found');if(claim.status!=='APPROVED'&&claim.status!=='PARTIALLY_PAID')throw new ContractValidationError('claim','approved claim required');const prior=claim.payments.find(x=>x.id===p.id);if(prior){if(prior.requestHash!==p.requestHash)throw new ContractValidationError('paymentId','conflicting replay');return{claim,payment:prior}}const appliedBefore=claim.payments.reduce((t,x)=>t+n(x.claimAmountApplied),0n),applied=n(p.claimAmountApplied),claimTotal=n(claim.amount);if(appliedBefore+applied>claimTotal)throw new ContractValidationError('amount','commission overpayment');const carryingBefore=claim.payments.reduce((t,x)=>t+n(x.carryingBaseAmount),0n),baseTotal=n(claim.baseCarryingAmount),isFinal=appliedBefore+applied===claimTotal,carrying=isFinal?baseTotal-carryingBefore:baseTotal*applied/claimTotal;if(carrying<=0n)throw new ContractValidationError('carryingBaseAmount','must remain positive');const normalized={...p,carryingBaseAmount:d(carrying) as CommissionPayment['carryingBaseAmount'],realizedFx:d(n(p.settlementBaseAmount)-carrying) as CommissionPayment['realizedFx']};const next={...claim,payments:[...claim.payments,normalized]};this.put(this.claims,next);return{claim:next,payment:normalized}}
 async finalizeCommissionPayment(c:CompanyId,id:string,p:CommissionPayment){const claim=this.claims.find(x=>x.companyId===c&&x.id===id);if(!claim)throw new ContractValidationError('claim','not found');const nextPayments=claim.payments.map(x=>x.id===p.id?p:x);const paid=nextPayments.filter(x=>x.status==='POSTED').reduce((t,x)=>t+n(x.claimAmountApplied),0n);const next={...claim,payments:nextPayments,status:(paid===n(claim.amount)?'PAID':'PARTIALLY_PAID') as CommissionClaim['status']};this.put(this.claims,next);return next}
 async accrual(c:CompanyId,id:string){return this.accruals.find(x=>x.companyId===c&&x.id===id)} async saveAccrual(v:Accrual){this.put(this.accruals,v)}
 async supplierSettlement(c:CompanyId,id:string){return this.supplierSettlements.find(x=>x.companyId===c&&x.id===id)} async saveSupplierSettlement(v:SupplierAdvanceSettlement){this.put(this.supplierSettlements,v)}
}
