import { ContractValidationError, decimalAmount } from '@elhafez/contracts';
import type { PrismaClient } from '@prisma/client';
import type { CompanyId } from '@elhafez/contracts';
import type { EcrRepository } from '../application/ecr.repository.js';
import type { Expense,ExpenseForm,RecognitionSchedule,RecognitionKind,SchedulePart,CommissionClaim,CommissionPayment,Accrual,SupplierAdvanceSettlement } from '../domain/ecr.js';
const S=10n**18n;function n(value:string){const [w,f='']=value.split('.');return BigInt(w+f.padEnd(18,'0'))}function d(v:bigint){const neg=v<0n,a=neg?-v:v,w=a/S,f=a%S,t=f?w+'.'+f.toString().padStart(18,'0').replace(/0+$/,''):w.toString();return decimalAmount((neg?'-':'')+t)}
export class PrismaEcrRepository implements EcrRepository {
 constructor(private readonly p:PrismaClient){}
 private async assertOwner(model:{findUnique(args:{where:{id:string}}):Promise<{companyId:string}|null>},id:string,companyId:string){const old=await model.findUnique({where:{id}});if(old&&old.companyId!==companyId)throw new ContractValidationError('companyId','ID belongs to another company')}
 async expense(companyId:CompanyId,id:string):Promise<Expense|undefined>{const x=await this.p.ecrExpense.findFirst({where:{companyId,id}});return x?{id:x.id,companyId:x.companyId as CompanyId,...(x.branchId?{branchId:x.branchId}:{}),form:x.form as ExpenseForm,sourceType:x.sourceType,sourceId:x.sourceId,currency:x.currency,amount:decimalAmount(x.amount.toString()),baseAmount:decimalAmount(x.baseAmount.toString()),status:x.status as Expense['status'],requestHash:x.requestHash,...(x.expenseAccountId?{expenseAccountId:x.expenseAccountId}:{}),...(x.prepaidAccountId?{prepaidAccountId:x.prepaidAccountId}:{}),...(x.billingInvoiceId?{billingInvoiceId:x.billingInvoiceId}:{}),...(x.treasuryVoucherId?{treasuryVoucherId:x.treasuryVoucherId}:{}),...(x.journalId?{journalId:x.journalId}:{}),...(x.approvalRequestId?{approvalRequestId:x.approvalRequestId}:{})}:undefined}
 async saveExpense(v:Expense){await this.assertOwner(this.p.ecrExpense,v.id,v.companyId);await this.p.ecrExpense.upsert({where:{id:v.id},create:v,update:{status:v.status,treasuryVoucherId:v.treasuryVoucherId,journalId:v.journalId}})}
 private mapSchedule(x:(Awaited<ReturnType<PrismaClient['ecrRecognitionSchedule']['findFirst']>>) & {parts?:Array<{id:string;serviceDate:Date;amount:{toString():string};status:string;journalId:string|null;reversalJournalId:string|null}>} | null):RecognitionSchedule|undefined{return x?{id:x.id,companyId:x.companyId as CompanyId,kind:x.kind as RecognitionKind,sourceType:x.sourceType,sourceId:x.sourceId,...(x.sourceInvoiceId?{sourceInvoiceId:x.sourceInvoiceId}:{}),currency:x.currency,sourceAmount:decimalAmount(x.sourceAmount.toString()),baseAmount:decimalAmount(x.baseAmount.toString()),deferredAccountId:x.deferredAccountId,recognitionAccountId:x.recognitionAccountId,requestHash:x.requestHash,...(x.initialJournalId?{initialJournalId:x.initialJournalId}:{}),parts:(x.parts??[]).map(q=>({id:q.id,serviceDate:q.serviceDate.toISOString().slice(0,10),amount:decimalAmount(q.amount.toString()),status:q.status,...(q.journalId?{journalId:q.journalId}:{}),...(q.reversalJournalId?{reversalJournalId:q.reversalJournalId}:{})} as SchedulePart))}:undefined}
 async schedule(companyId:CompanyId,id:string){return this.mapSchedule(await this.p.ecrRecognitionSchedule.findFirst({where:{companyId,id},include:{parts:true}}))}
 async scheduleByInvoice(companyId:CompanyId,sourceInvoiceId:string,kind:string){return this.mapSchedule(await this.p.ecrRecognitionSchedule.findFirst({where:{companyId,sourceInvoiceId,kind},include:{parts:true}}))}
 async saveSchedule(v:RecognitionSchedule){await this.assertOwner(this.p.ecrRecognitionSchedule,v.id,v.companyId);await this.p.$transaction(async tx=>{await tx.ecrRecognitionSchedule.upsert({where:{id:v.id},create:{id:v.id,companyId:v.companyId,kind:v.kind,sourceType:v.sourceType,sourceId:v.sourceId,sourceInvoiceId:v.sourceInvoiceId,currency:v.currency,sourceAmount:v.sourceAmount,baseAmount:v.baseAmount,deferredAccountId:v.deferredAccountId,recognitionAccountId:v.recognitionAccountId,requestHash:v.requestHash,initialJournalId:v.initialJournalId},update:{initialJournalId:v.initialJournalId}});for(const q of v.parts){const old=await tx.ecrRecognitionPart.findUnique({where:{id:q.id}});if(old&&old.companyId!==v.companyId)throw new ContractValidationError('companyId','part ID belongs to another company');await tx.ecrRecognitionPart.upsert({where:{id:q.id},create:{id:q.id,companyId:v.companyId,scheduleId:v.id,serviceDate:new Date(q.serviceDate+'T00:00:00.000Z'),amount:q.amount,status:q.status,journalId:q.journalId,reversalJournalId:q.reversalJournalId},update:{status:q.status,journalId:q.journalId,reversalJournalId:q.reversalJournalId}})}})}
 private mapPayment(q:{id:string;requestHash:string;status:string;amount:{toString():string};paymentCurrency:string;claimAmountApplied:{toString():string};settlementBaseAmount:{toString():string};carryingBaseAmount:{toString():string};realizedFx:{toString():string};fxRateId:string|null;treasuryVoucherId:string|null}):CommissionPayment{return{id:q.id,requestHash:q.requestHash,status:q.status as CommissionPayment['status'],amount:decimalAmount(q.amount.toString()),paymentCurrency:q.paymentCurrency,claimAmountApplied:decimalAmount(q.claimAmountApplied.toString()),settlementBaseAmount:decimalAmount(q.settlementBaseAmount.toString()),carryingBaseAmount:decimalAmount(q.carryingBaseAmount.toString()),realizedFx:decimalAmount(q.realizedFx.toString()),...(q.fxRateId?{fxRateId:q.fxRateId}:{}),...(q.treasuryVoucherId?{treasuryVoucherId:q.treasuryVoucherId}:{})}}
 async claim(companyId:CompanyId,id:string):Promise<CommissionClaim|undefined>{const x=await this.p.ecrCommissionClaim.findFirst({where:{companyId,id},include:{payments:true}});return x?{id:x.id,companyId:x.companyId as CompanyId,...(x.branchId?{branchId:x.branchId}:{}),agentPartyId:x.agentPartyId,sourceType:x.sourceType,sourceId:x.sourceId,currency:x.currency,amount:decimalAmount(x.amount.toString()),baseCarryingAmount:decimalAmount(x.baseCarryingAmount.toString()),status:x.status as CommissionClaim['status'],requestHash:x.requestHash,...(x.approvalRequestId?{approvalRequestId:x.approvalRequestId}:{}),...(x.requesterActorId?{requesterActorId:x.requesterActorId}:{}),...(x.recognitionJournalId?{recognitionJournalId:x.recognitionJournalId}:{}),...(x.reversalJournalId?{reversalJournalId:x.reversalJournalId}:{}),expenseAccountId:x.expenseAccountId,liabilityAccountId:x.liabilityAccountId,payments:x.payments.map(q=>this.mapPayment(q))}:undefined}
 async saveClaim(v:CommissionClaim){await this.assertOwner(this.p.ecrCommissionClaim,v.id,v.companyId);await this.p.ecrCommissionClaim.upsert({where:{id:v.id},create:{id:v.id,companyId:v.companyId,branchId:v.branchId,agentPartyId:v.agentPartyId,sourceType:v.sourceType,sourceId:v.sourceId,currency:v.currency,amount:v.amount,baseCarryingAmount:v.baseCarryingAmount,status:v.status,requestHash:v.requestHash,approvalRequestId:v.approvalRequestId,requesterActorId:v.requesterActorId,recognitionJournalId:v.recognitionJournalId,reversalJournalId:v.reversalJournalId,expenseAccountId:v.expenseAccountId,liabilityAccountId:v.liabilityAccountId},update:{status:v.status,baseCarryingAmount:v.baseCarryingAmount,recognitionJournalId:v.recognitionJournalId,reversalJournalId:v.reversalJournalId}})}
 async reserveCommissionPayment(companyId:CompanyId,claimId:string,payment:CommissionPayment){const reserved=await this.p.$transaction(async tx=>{const claim=await tx.ecrCommissionClaim.findFirst({where:{companyId,id:claimId},include:{payments:true}});if(!claim)throw new ContractValidationError('claim','not found');if(!['APPROVED','PARTIALLY_PAID'].includes(claim.status))throw new ContractValidationError('claim','approved claim required');const prior=claim.payments.find(x=>x.id===payment.id);if(prior){if(prior.requestHash!==payment.requestHash)throw new ContractValidationError('paymentId','conflicting replay');return this.mapPayment(prior)}const appliedBefore=claim.payments.reduce((t,x)=>t+n(x.claimAmountApplied.toString()),0n),applied=n(payment.claimAmountApplied),claimTotal=n(claim.amount.toString());if(appliedBefore+applied>claimTotal)throw new ContractValidationError('amount','commission overpayment');const carryingBefore=claim.payments.reduce((t,x)=>t+n(x.carryingBaseAmount.toString()),0n),baseTotal=n(claim.baseCarryingAmount.toString()),isFinal=appliedBefore+applied===claimTotal,carrying=isFinal?baseTotal-carryingBefore:baseTotal*applied/claimTotal;if(carrying<=0n)throw new ContractValidationError('carryingBaseAmount','must remain positive');const normalized:CommissionPayment={...payment,carryingBaseAmount:d(carrying),realizedFx:d(n(payment.settlementBaseAmount)-carrying)};await tx.ecrCommissionPayment.create({data:{...normalized,companyId,claimId}});return normalized},{isolationLevel:'Serializable'});const claim=await this.claim(companyId,claimId);if(!claim)throw new ContractValidationError('claim','not found');return{claim,payment:reserved}}
 async finalizeCommissionPayment(companyId:CompanyId,claimId:string,payment:CommissionPayment){await this.p.$transaction(async tx=>{const row=await tx.ecrCommissionPayment.findFirst({where:{companyId,id:payment.id,claimId}});if(!row||row.requestHash!==payment.requestHash)throw new ContractValidationError('payment','reservation missing');await tx.ecrCommissionPayment.update({where:{id:payment.id},data:{status:'POSTED',treasuryVoucherId:payment.treasuryVoucherId}});const claim=await tx.ecrCommissionClaim.findFirstOrThrow({where:{companyId,id:claimId},include:{payments:true}});const paid=claim.payments.filter(x=>x.status==='POSTED'||x.id===payment.id).reduce((t,x)=>t+n(decimalAmount(x.claimAmountApplied.toString())),0n);await tx.ecrCommissionClaim.update({where:{id:claimId},data:{status:paid===n(claim.amount.toString())?'PAID':'PARTIALLY_PAID'}})},{isolationLevel:'Serializable'});return (await this.claim(companyId,claimId))!}
 async accrual(companyId:CompanyId,id:string):Promise<Accrual|undefined>{const x=await this.p.ecrAccrual.findFirst({where:{companyId,id}});return x?{id:x.id,companyId:x.companyId as CompanyId,sourceType:x.sourceType,sourceId:x.sourceId,amount:decimalAmount(x.amount.toString()),serviceDate:x.serviceDate.toISOString().slice(0,10),status:x.status as Accrual['status'],journalId:x.journalId,requestHash:x.requestHash,accruedRevenueAccountId:x.accruedRevenueAccountId,revenueAccountId:x.revenueAccountId,...(x.billingInvoiceId?{billingInvoiceId:x.billingInvoiceId}:{}),...(x.clearingJournalId?{clearingJournalId:x.clearingJournalId}:{})}:undefined}
 async saveAccrual(v:Accrual){await this.assertOwner(this.p.ecrAccrual,v.id,v.companyId);await this.p.ecrAccrual.upsert({where:{id:v.id},create:{...v,serviceDate:new Date(v.serviceDate+'T00:00:00.000Z')},update:{status:v.status,billingInvoiceId:v.billingInvoiceId,clearingJournalId:v.clearingJournalId}})}
 async supplierSettlement(companyId:CompanyId,id:string):Promise<SupplierAdvanceSettlement|undefined>{const x=await this.p.ecrSupplierAdvanceSettlement.findFirst({where:{companyId,id}});return x?{id:x.id,companyId:x.companyId as CompanyId,kind:x.kind as SupplierAdvanceSettlement['kind'],advanceId:x.advanceId,supplierPartyId:x.supplierPartyId,amount:decimalAmount(x.amount.toString()),requestHash:x.requestHash,status:x.status as SupplierAdvanceSettlement['status'],...(x.treasuryVoucherId?{treasuryVoucherId:x.treasuryVoucherId}:{}),...(x.journalId?{journalId:x.journalId}:{}),...(x.failureReason?{failureReason:x.failureReason}:{})}:undefined}
 async saveSupplierSettlement(v:SupplierAdvanceSettlement){await this.assertOwner(this.p.ecrSupplierAdvanceSettlement,v.id,v.companyId);await this.p.ecrSupplierAdvanceSettlement.upsert({where:{id:v.id},create:v,update:{status:v.status,treasuryVoucherId:v.treasuryVoucherId,journalId:v.journalId,failureReason:v.failureReason}})}
}
