/** Stable execution order only; accounting truth remains with the named owner. */
export const AC14_STAGES = [
  ['source-preflight', null, []],
  ['currencies', 'CurrencyFx', ['currencies']],
  ['historical-fx-rates', 'CurrencyFx', ['fxRates', 'exchangeRates']],
  ['cost-centers', 'CostBudget', ['costCenters', 'programCostCenters']],
  ['fiscal-years', 'PeriodControl', ['fiscalYears']],
  ['accounting-periods', 'PeriodControl', ['accountingPeriods', 'periods']],
  ['chart-of-accounts', 'GeneralLedger', ['accounts']],
  ['general-ledger-journals', 'GeneralLedger', ['journals']],
  ['tax-history', 'Tax', ['taxSnapshots', 'taxFacts']],
  ['billing-invoices', 'Billing', ['invoices']],
  ['billing-adjustments', 'Billing', ['invoiceAdjustments', 'adjustments']],
  ['billing-settlements', 'Billing', ['advances', 'allocations', 'settlements']],
  ['treasuries', 'Treasury', ['treasuries']],
  ['treasury-vouchers', 'Treasury', ['receipts', 'payments', 'vouchers']],
  ['treasury-transfers', 'Treasury', ['transfers']],
  ['treasury-cheques', 'Treasury', ['cheques']],
  ['treasury-reconciliation', 'Treasury', ['cashCounts', 'bankStatementLines', 'bankMatches', 'bankReconciliations']],
  ['party-accounting', 'PartyAccounting', ['partyGroups', 'nettings']],
  ['expenses', 'ExpenseRecognition', ['expenses']],
  ['prepayments', 'ExpenseRecognition', ['prepayments']],
  ['commissions', 'ExpenseRecognition', ['commissions', 'commissionPayments']],
  ['deferred-revenue-cost', 'ExpenseRecognition', ['recognitionSchedules', 'deferredRevenue', 'deferredCost']],
  ['accruals', 'ExpenseRecognition', ['accruals']],
  ['fixed-assets', 'AssetsFinancing', ['assets', 'depreciationEvents', 'assetDisposals']],
  ['loans', 'AssetsFinancing', ['loans', 'loanInstallments']],
  ['provisions-allowances', 'AssetsFinancing', ['provisions', 'allowances', 'allowanceWriteoffs']],
  ['payroll-accounting', 'AssetsFinancing', ['payrollAccounting']],
  ['budgets', 'CostBudget', ['budgets']],
  ['procurement', 'Procurement', ['purchaseOrders', 'supplierCommitments']],
  ['controls-evidence', 'FinancialControls', ['approvals', 'reconciliations']],
  ['tourism-contract-inventory', 'TourismContractInventory', ['tourismContracts', 'hotelInventory', 'flightBlocks', 'transportCapacity', 'visaQuotas', 'allotments', 'inventoryAllocations', 'stopSales']],
  ['tourism-finance', 'TourismFinance', ['bookingFinancialSetups', 'bookingFinancialWorkflows', 'programFinancialWorkflows']],
  ['reporting-rebuild', 'FinancialReporting', []],
  ['equivalence', null, []],
  ['golden-scenarios', null, []],
  ['cutover-readiness', null, []],
] as const;

export type Ac14Stage = (typeof AC14_STAGES)[number];
