export{ProcurementFulfillmentApplicationService,PROCUREMENT_OPERATIONS_PERMISSIONS}from'../application/procurement-fulfillment.application-service.js';
export type{CreateManualPurchaseOrderInput,UpdateManualPurchaseOrderInput,CreateDirectPurchaseOperationalInput,ConvertPurchaseOrderLineToSupplierInvoiceInput,RecordFulfillmentInput,CorrectFulfillmentInput,SupplierFulfillmentTimingMetrics}from'../application/procurement-fulfillment.application-service.js';
export type{ProcurementFulfillmentRecord,FulfillmentKind,FulfillmentStatus}from'../domain/fulfillment.js';
