import { createHash } from 'node:crypto';
import { ContractValidationError, currencyCode, decimalAmount, type CompanyId, type DecimalAmount } from '@elhafez/contracts';
import type { BillingSubledgersApplicationService } from '@elhafez/billing-subledgers';
import type { CurrencyFxApplicationService } from '@elhafez/currency-fx';
import type { GeneralLedgerApplicationService, PostingLine } from '@elhafez/general-ledger';
import type { TreasurySettlementApplicationService } from '@elhafez/treasury-settlement';
import type { AssetsFinancingRepository } from './assets-financing.repository.js';
import type { Asset,PayrollLiability,Provision,ProvisionMovementKind } from '../domain/assets-financing.js';
const SCALE=10n**18n, ZERO=decimalAmount('0');
function scaled(value:DecimalAmount|string):bigint { const normalized=decimalAmount(value),negative=normalized.startsWith('-'),unsigned=negative?normalized.slice(1):normalized,[whole='0',fraction='']=unsigned.split('.');if(fraction.length>18)throw new ContractValidationError('amount','supports at most 18 fractional digits');const result=BigInt(whole+fraction.padEnd(18,'0'));return negative?-result:result; }
function decimal(value:bigint):DecimalAmount {const negative=value<0n,absolute=negative?-value:value,whole=absolute/SCALE,fraction=absolute%SCALE,text=fraction?`${whole}.${fraction.toString().padStart(18,'0').replace(/0+$/,'')}`:whole.toString();return decimalAmount((negative?'-':'')+text);}
function positive(value:DecimalAmount,field='amount'){const result=decimalAmount(value);if(scaled(result)<=0n)throw new ContractValidationError(field,'must be positive');return result;}
function nonnegative(value:DecimalAmount,field='amount'){const result=decimalAmount(value);if(scaled(result)<0n)throw new ContractValidationError(field,'must not be negative');return result;}
function fingerprint(value:unknown){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
export interface RegisterAssetInput extends Omit<Asset,'status'|'accumulatedDepreciation'|'capitalizationJournalId'|'requestHash'|'method'>{method?:'STRAIGHT_LINE';number:string}
export class AssetsFinancingApplicationService {
 constructor(private readonly repo:AssetsFinancingRepository,private readonly gl:Pick<GeneralLedgerApplicationService,'post'>,private readonly billing:Pick<BillingSubledgersApplicationService,'getOpenPosition'|'createAdjustment'>,private readonly treasury:Pick<TreasurySettlementApplicationService,'postAccountingMovement'>,private readonly fx:Pick<CurrencyFxApplicationService,'getBaseCurrency'>){}
 private async requireBaseCurrency(companyId:CompanyId,currency:string){const base=await this.fx.getBaseCurrency(companyId),normalized=currencyCode(currency);if(normalized!==base.code)throw new ContractValidationError('currency','foreign-currency AC-09 workflow requires approved settlement/carrying policy; unsupported');return base.code;}
 async listAssets(companyId:CompanyId){return this.repo.listAssets(companyId)}
 async listLoans(companyId:CompanyId){return this.repo.listLoans(companyId)}
 async listProvisions(companyId:CompanyId){return this.repo.listProvisions(companyId)}
 async listAllowances(companyId:CompanyId){return this.repo.listAllowances(companyId)}
 async listPayrollRuns(companyId:CompanyId){return this.repo.listPayrollRuns(companyId)}
 async registerAsset(input:RegisterAssetInput):Promise<Asset>{
  if(!input.code.trim()||!input.name.trim())throw new ContractValidationError('asset','code and name required');if(input.method&&input.method!=='STRAIGHT_LINE')throw new ContractValidationError('method','unsupported');positive(input.acquisitionValue);positive(input.baseValue);nonnegative(input.residualValue);if(scaled(input.residualValue)>scaled(input.baseValue)||!Number.isInteger(input.usefulLifeMonths)||input.usefulLifeMonths<1)throw new ContractValidationError('asset','invalid residual value or useful life');await this.requireBaseCurrency(input.companyId,input.currency);
  const normalized={...input,currency:currencyCode(input.currency),method:'STRAIGHT_LINE' as const},requestHash=fingerprint(normalized);let asset=await this.repo.asset(input.companyId,input.id);
  if(asset&&asset.requestHash!==requestHash)throw new ContractValidationError('asset','conflicting replay');
  if(!asset){asset=await this.repo.reserveAsset({...normalized,status:'REGISTERING',accumulatedDepreciation:ZERO,requestHash});}
  if(asset.status!=='REGISTERING')return asset;
  const journal=await this.gl.post({id:`af-asset-cap:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.capitalizationDate,sourceType:'AF_ASSET_CAPITALIZATION',sourceId:input.id,lines:[{accountId:input.assetAccountId,debit:input.baseValue},{accountId:input.capitalizationOffsetAccountId,credit:input.baseValue}]});
  return this.repo.finalizeAssetCapitalization(input.companyId,input.id,journal.id);
 }
 depreciationSchedule(asset:Asset){const depreciable=scaled(asset.baseValue)-scaled(asset.residualValue),base=depreciable/BigInt(asset.usefulLifeMonths),remainder=depreciable%BigInt(asset.usefulLifeMonths);return Array.from({length:asset.usefulLifeMonths},(_,index)=>decimal(base+(BigInt(index)<remainder?1n:0n)));}
 async postDepreciation(input:{id:string;companyId:CompanyId;assetId:string;period:number;postingDate:string;number:string}){
  const asset=await this.requiredAsset(input.companyId,input.assetId);if(asset.status!=='ACTIVE')throw new ContractValidationError('asset','only active asset can depreciate');const amount=this.depreciationSchedule(asset)[input.period-1];if(!amount)throw new ContractValidationError('period','outside useful life');const requestHash=fingerprint(input);let movement=await this.repo.depreciation(input.companyId,input.id);if(movement){if(movement.requestHash!==requestHash)throw new ContractValidationError('depreciation','conflicting replay');if(movement.status==='POSTED')return movement;}else movement=await this.repo.reserveDepreciation({...input,amount,status:'POSTING',requestHash});
  const journal=await this.gl.post({id:`af-dep:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_ASSET_DEPRECIATION',sourceId:input.id,lines:[{accountId:asset.depreciationExpenseAccountId,debit:amount},{accountId:asset.accumulatedDepreciationAccountId,credit:amount}]});return this.repo.finalizeDepreciation({...movement,status:'POSTED',journalId:journal.id});
 }
 async disposeAsset(input:{id:string;companyId:CompanyId;assetId:string;postingDate:string;proceeds:DecimalAmount;proceedsMode:'TREASURY'|'NON_CASH';treasuryId?:string;proceedsClearingAccountId?:string;number:string}){
  const proceeds=nonnegative(input.proceeds,'proceeds');if(scaled(proceeds)>0n&&!input.proceedsClearingAccountId)throw new ContractValidationError('proceedsClearingAccountId','required for disposal proceeds');if(input.proceedsMode==='TREASURY'&&!input.treasuryId)throw new ContractValidationError('treasuryId','required');const requestHash=fingerprint({...input,proceeds});let workflow=await this.repo.disposal(input.companyId,input.id);if(workflow&&workflow.requestHash!==requestHash)throw new ContractValidationError('disposal','conflicting replay');if(!workflow)workflow=await this.repo.reserveDisposal({...input,proceeds,requestHash,status:'RESERVED'});if(workflow.status==='COMPLETED')return workflow;
  const asset=await this.requiredAsset(input.companyId,input.assetId);let treasuryVoucherId=workflow.treasuryVoucherId;if(input.proceedsMode==='TREASURY'&&scaled(proceeds)>0n&&!treasuryVoucherId){const receipt=await this.treasury.postAccountingMovement({id:`af-disposal-receipt:${input.id}`,companyId:input.companyId,treasuryId:input.treasuryId!,partyId:'ASSET_DISPOSAL',kind:'RECEIPT',number:input.number,postingDate:input.postingDate,currency:asset.currency,amount:proceeds,sourceType:'AF_ASSET_DISPOSAL_RECEIPT',sourceId:input.id,offsetLines:[{accountId:input.proceedsClearingAccountId!,amount:proceeds}]});treasuryVoucherId=receipt.id;}
  let journalId=workflow.journalId;if(!journalId){const carrying=scaled(asset.baseValue)-scaled(asset.accumulatedDepreciation),gainLoss=scaled(proceeds)-carrying,lines:PostingLine[]=[{accountId:asset.assetAccountId,credit:asset.baseValue}];if(scaled(asset.accumulatedDepreciation)>0n)lines.unshift({accountId:asset.accumulatedDepreciationAccountId,debit:asset.accumulatedDepreciation});if(scaled(proceeds)>0n)lines.push({accountId:input.proceedsClearingAccountId!,debit:proceeds});if(gainLoss>0n){if(!asset.disposalGainAccountId)throw new ContractValidationError('disposalGainAccountId','required');lines.push({accountId:asset.disposalGainAccountId,credit:decimal(gainLoss)});}else if(gainLoss<0n){if(!asset.disposalLossAccountId)throw new ContractValidationError('disposalLossAccountId','required');lines.push({accountId:asset.disposalLossAccountId,debit:decimal(-gainLoss)});}const journal=await this.gl.post({id:`af-disposal:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_ASSET_DISPOSAL',sourceId:input.id,lines});journalId=journal.id;}
  await this.repo.recordDisposalEffects({...workflow,status:'EFFECTS_POSTED',treasuryVoucherId,journalId});return this.repo.finalizeDisposal(input.companyId,input.id);
 }
 async originateLoan(input:{id:string;companyId:CompanyId;lenderId:string;reference:string;principal:DecimalAmount;currency:string;baseAmount:DecimalAmount;liabilityAccountId:string;interestExpenseAccountId:string;fundingTreasuryId:string;postingDate:string;number:string;installments:{id:string;dueDate:string;principal:DecimalAmount;interest:DecimalAmount}[]}){
  const principal=positive(input.principal,'principal'),baseAmount=positive(input.baseAmount,'baseAmount'),baseCurrency=await this.requireBaseCurrency(input.companyId,input.currency);if(scaled(principal)!==scaled(baseAmount))throw new ContractValidationError('baseAmount','must equal principal for supported base-currency loans');if(input.installments.reduce((total,item)=>total+scaled(positive(item.principal,'installment.principal')),0n)!==scaled(principal))throw new ContractValidationError('installments','principal schedule must equal loan principal');const normalized={...input,principal,baseAmount,currency:currencyCode(input.currency),baseCurrency},requestHash=fingerprint(normalized);let loan=await this.repo.loan(input.companyId,input.id);if(loan&&loan.requestHash!==requestHash)throw new ContractValidationError('loan','conflicting replay');if(!loan)loan=await this.repo.reserveLoan({...normalized,outstandingPrincipal:principal,status:'ORIGINATING',requestHash,installments:input.installments.map((item,index)=>({...item,companyId:input.companyId,loanId:input.id,sequence:index+1,principal:positive(item.principal),interest:nonnegative(item.interest),status:'DUE'}))});if(loan.status!=='ORIGINATING')return loan;
  const voucher=await this.treasury.postAccountingMovement({id:`af-loan-funding:${loan.id}`,companyId:loan.companyId,treasuryId:loan.fundingTreasuryId,partyId:loan.lenderId,kind:'RECEIPT',number:input.number,postingDate:input.postingDate,currency:loan.baseCurrency,amount:loan.baseAmount,sourceType:'AF_LOAN_FUNDING',sourceId:loan.id,offsetLines:[{accountId:loan.liabilityAccountId,amount:loan.baseAmount}]});return this.repo.finalizeLoanOrigination(loan.companyId,loan.id,voucher.id);
 }
 async payLoanInstallment(input:{companyId:CompanyId;loanId:string;installmentId:string;treasuryId:string;postingDate:string;number:string}){
  const requestHash=fingerprint(input),reservation=await this.repo.reserveInstallment(input.companyId,input.loanId,input.installmentId,requestHash),loan=reservation.loan,installment=loan.installments[reservation.installmentIndex]!;if(installment.status==='PAID')return installment;let voucherId=installment.treasuryVoucherId,journalId=installment.journalId;if(!voucherId){const voucher=await this.treasury.postAccountingMovement({id:`af-loan-payment:${installment.id}`,companyId:input.companyId,treasuryId:input.treasuryId,partyId:loan.lenderId,kind:'PAYMENT',number:input.number,postingDate:input.postingDate,currency:loan.baseCurrency,amount:decimal(scaled(installment.principal)+scaled(installment.interest)),sourceType:'AF_LOAN_INSTALLMENT',sourceId:installment.id,offsetLines:[{accountId:loan.liabilityAccountId,amount:installment.principal},{accountId:loan.interestExpenseAccountId,amount:installment.interest}]});voucherId=voucher.id;journalId=voucher.journalId;await this.repo.recordInstallmentVoucher(input.companyId,input.loanId,input.installmentId,voucherId,journalId);}const completed=await this.repo.finalizeInstallment(input.companyId,input.loanId,input.installmentId);return completed.installments.find(item=>item.id===input.installmentId)!;
 }
 async createProvision(input:{id:string;companyId:CompanyId;name:string;provisionAccountId:string;expenseAccountId:string;releaseAccountId:string}){const requestHash=fingerprint(input),value:Provision={...input,available:ZERO,requestHash,movements:[]};return this.repo.reserveProvision(value);}
 async moveProvision(input:{id:string;companyId:CompanyId;provisionId:string;kind:ProvisionMovementKind;amount:DecimalAmount;sourceType:string;sourceId:string;postingDate:string;number:string;useOffsetAccountId?:string}){
  const amount=positive(input.amount),provision=await this.requiredProvision(input.companyId,input.provisionId);if(input.kind==='USE'&&!input.useOffsetAccountId)throw new ContractValidationError('useOffsetAccountId','explicit settlement/offset account required');const offsetAccountId=input.kind==='USE'?input.useOffsetAccountId!:input.kind==='RELEASE'?provision.releaseAccountId:provision.expenseAccountId,requestHash=fingerprint({...input,amount,offsetAccountId});let movement=provision.movements.find(item=>item.sourceType===input.sourceType&&item.sourceId===input.sourceId);if(movement&&movement.requestHash!==requestHash)throw new ContractValidationError('source','conflicting replay');if(!movement)movement=await this.repo.reserveProvisionMovement({...input,amount,offsetAccountId,requestHash,status:'RESERVED',createdAt:new Date().toISOString()});if(movement.status==='POSTED')return this.requiredProvision(input.companyId,input.provisionId);const increase=input.kind==='RECOGNIZE'||input.kind==='INCREASE',lines:PostingLine[]=increase?[{accountId:offsetAccountId,debit:amount},{accountId:provision.provisionAccountId,credit:amount}]:[{accountId:provision.provisionAccountId,debit:amount},{accountId:offsetAccountId,credit:amount}];const journal=await this.gl.post({id:`af-provision:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_PROVISION_MOVEMENT',sourceId:`${input.sourceType}:${input.sourceId}`,lines});return this.repo.finalizeProvisionMovement(input.companyId,movement.id,journal.id);
 }
 async recognizeAllowance(input:{id:string;companyId:CompanyId;customerId?:string;sourceReference:string;allowanceAccountId:string;expenseAccountId:string;releaseAccountId:string;amount:DecimalAmount;postingDate:string;number:string}){
  const amount=positive(input.amount),requestHash=fingerprint({...input,amount});let allowance=await this.repo.allowance(input.companyId,input.id);if(allowance&&allowance.requestHash!==requestHash)throw new ContractValidationError('allowance','conflicting replay');if(!allowance)allowance=await this.repo.reserveAllowance({...input,amount,used:ZERO,available:amount,requestHash,movements:[{id:`${input.id}:recognition`,companyId:input.companyId,allowanceId:input.id,kind:'RECOGNIZE',amount,sourceId:input.sourceReference,requestHash,status:'RESERVED',createdAt:new Date().toISOString()}]});const recognition=allowance.movements[0]!;if(recognition.status==='POSTED')return allowance;const journal=await this.gl.post({id:`af-allowance:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_ALLOWANCE_RECOGNITION',sourceId:input.id,lines:[{accountId:input.expenseAccountId,debit:amount},{accountId:input.allowanceAccountId,credit:amount}]});return this.repo.finalizeAllowanceRecognition(input.companyId,input.id,journal.id);
 }
 async releaseAllowance(input:{id:string;companyId:CompanyId;allowanceId:string;amount:DecimalAmount;postingDate:string;number:string}){const amount=positive(input.amount),allowance=await this.requiredAllowance(input.companyId,input.allowanceId),requestHash=fingerprint({...input,amount});let movement=allowance.movements.find(item=>item.id===input.id);if(movement&&movement.requestHash!==requestHash)throw new ContractValidationError('allowanceRelease','conflicting replay');if(!movement)movement=await this.repo.reserveAllowanceRelease({id:input.id,companyId:input.companyId,allowanceId:input.allowanceId,kind:'RELEASE',amount,sourceId:input.id,requestHash,status:'RESERVED',createdAt:new Date().toISOString()});if(movement.status==='POSTED')return this.requiredAllowance(input.companyId,input.allowanceId);const journal=await this.gl.post({id:`af-allowance-release:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_ALLOWANCE_RELEASE',sourceId:input.id,lines:[{accountId:allowance.allowanceAccountId,debit:amount},{accountId:allowance.releaseAccountId,credit:amount}]});return this.repo.finalizeAllowanceRelease(input.companyId,input.id,journal.id);}
 async writeOffReceivable(input:{id:string;companyId:CompanyId;allowanceId:string;invoiceId:string;amount:DecimalAmount;postingDate:string;number:string}){
  const amount=positive(input.amount),requestHash=fingerprint({...input,amount});let workflow=await this.repo.writeOff(input.companyId,input.id);if(workflow&&workflow.requestHash!==requestHash)throw new ContractValidationError('writeOff','conflicting replay');if(workflow?.status==='COMPLETED')return workflow;const position=await this.billing.getOpenPosition(input.companyId,input.invoiceId),allowance=await this.requiredAllowance(input.companyId,input.allowanceId);if(allowance.customerId&&allowance.customerId!==position.partyId)throw new ContractValidationError('customerId','allowance customer does not own receivable');if(!workflow||workflow.status==='RELEASED'){if(scaled(amount)>scaled(position.outstanding))throw new ContractValidationError('amount','BR-023 receivable cap exceeded');if(scaled(amount)>scaled(allowance.available))throw new ContractValidationError('amount','BR-023 allowance cap exceeded');workflow=await this.repo.reserveWriteOff({...input,amount,requestHash,status:'RESERVED'});}await this.repo.markWriteOffProcessing(input.companyId,input.id);
  let adjustment:Awaited<ReturnType<BillingSubledgersApplicationService['createAdjustment']>>;try{adjustment=await this.billing.createAdjustment({id:`af-writeoff:${input.id}`,companyId:input.companyId,invoiceId:input.invoiceId,kind:'WRITE_OFF',amount,sourceType:'AF_ALLOWANCE_WRITEOFF',sourceId:input.id,postingDate:input.postingDate,number:input.number,offsetAccountId:allowance.allowanceAccountId});}catch(error){await this.repo.releaseWriteOff(input.companyId,input.id,error instanceof Error?error.message:'Billing rejected write-off');throw error;}const completed={...workflow,status:'COMPLETED' as const,billingAdjustmentId:adjustment.id};await this.repo.finalizeWriteOff(completed);return completed;
 }
 async accruePayroll(input:{id:string;companyId:CompanyId;sourceId:string;payrollPeriod:string;postingDate:string;currency:string;expenseTotal:DecimalAmount;expenseAccountId:string;liabilities:PayrollLiability[];number:string}){await this.requireBaseCurrency(input.companyId,input.currency);const expenseTotal=positive(input.expenseTotal,'expenseTotal'),liabilities=input.liabilities.map(item=>({...item,amount:positive(item.amount,'liability')}));if(liabilities.reduce((total,item)=>total+scaled(item.amount),0n)!==scaled(expenseTotal))throw new ContractValidationError('payroll','supplied liabilities must equal expense total');const normalized={...input,currency:currencyCode(input.currency),expenseTotal,liabilities},requestHash=fingerprint(normalized);let run=await this.repo.payrollBySource(input.companyId,input.sourceId);if(run&&run.requestHash!==requestHash)throw new ContractValidationError('payroll','conflicting replay');if(!run)run=await this.repo.reservePayroll({...normalized,status:'ACCRUING',requestHash});if(run.status!=='ACCRUING')return run;const journal=await this.gl.post({id:`af-payroll:${input.id}`,companyId:input.companyId,number:input.number,postingDate:input.postingDate,sourceType:'AF_PAYROLL_ACCRUAL',sourceId:input.sourceId,lines:[{accountId:input.expenseAccountId,debit:expenseTotal},...liabilities.map(item=>({accountId:item.accountId,credit:item.amount}))]});await this.repo.recordPayrollAccrual(input.companyId,run.id,journal.id);return (await this.repo.payroll(input.companyId,run.id))!;}
 async payPayroll(input:{companyId:CompanyId;runId:string;treasuryId:string;postingDate:string;number:string}){let run=await this.repo.payroll(input.companyId,input.runId);if(!run)throw new ContractValidationError('payroll','not found');if(run.status==='PAID')return run;if(run.status!=='ACCRUED'&&run.status!=='PAYING')throw new ContractValidationError('payroll','must be accrued');await this.repo.markPayrollPaying(input.companyId,run.id);run=(await this.repo.payroll(input.companyId,run.id))!;const voucher=await this.treasury.postAccountingMovement({id:`af-payroll-payment:${run.id}`,companyId:input.companyId,treasuryId:input.treasuryId,partyId:'PAYROLL',kind:'PAYMENT',number:input.number,postingDate:input.postingDate,currency:run.currency,amount:run.expenseTotal,sourceType:'AF_PAYROLL_PAYMENT',sourceId:run.id,offsetLines:run.liabilities.map(item=>({accountId:item.accountId,amount:item.amount}))});return this.repo.finalizePayrollPayment(input.companyId,run.id,voucher.id);}
 private async requiredAsset(c:CompanyId,id:string){const value=await this.repo.asset(c,id);if(!value)throw new ContractValidationError('asset','not found');return value;}private async requiredProvision(c:CompanyId,id:string){const value=await this.repo.provision(c,id);if(!value)throw new ContractValidationError('provision','not found');return value;}private async requiredAllowance(c:CompanyId,id:string){const value=await this.repo.allowance(c,id);if(!value)throw new ContractValidationError('allowance','not found');return value;}
}
