import type { CompanyId } from '@elhafez/contracts';
import type { Allowance,AllowanceMovement,AllowanceWriteOff,Asset,AssetDepreciation,AssetDisposal,Loan,PayrollRun,Provision,ProvisionMovement } from '../domain/assets-financing.js';
export const ASSETS_FINANCING_REPOSITORY=Symbol('ASSETS_FINANCING_REPOSITORY');
export interface AssetsFinancingRepository {
 asset(c:CompanyId,id:string):Promise<Asset|undefined>; assetByCode(c:CompanyId,code:string):Promise<Asset|undefined>; reserveAsset(v:Asset):Promise<Asset>; finalizeAssetCapitalization(c:CompanyId,id:string,journalId:string):Promise<Asset>;
 depreciation(c:CompanyId,id:string):Promise<AssetDepreciation|undefined>; reserveDepreciation(v:AssetDepreciation):Promise<AssetDepreciation>; finalizeDepreciation(v:AssetDepreciation):Promise<AssetDepreciation>;
 disposal(c:CompanyId,id:string):Promise<AssetDisposal|undefined>; reserveDisposal(v:AssetDisposal):Promise<AssetDisposal>; recordDisposalEffects(v:AssetDisposal):Promise<void>; finalizeDisposal(c:CompanyId,id:string):Promise<AssetDisposal>;
 loan(c:CompanyId,id:string):Promise<Loan|undefined>; reserveLoan(v:Loan):Promise<Loan>; finalizeLoanOrigination(c:CompanyId,id:string,voucherId:string):Promise<Loan>; reserveInstallment(c:CompanyId,loanId:string,installmentId:string,hash:string):Promise<{loan:Loan;installmentIndex:number}>; recordInstallmentVoucher(c:CompanyId,loanId:string,installmentId:string,voucherId:string,journalId?:string):Promise<void>; finalizeInstallment(c:CompanyId,loanId:string,installmentId:string):Promise<Loan>;
 provision(c:CompanyId,id:string):Promise<Provision|undefined>; reserveProvision(v:Provision):Promise<Provision>; reserveProvisionMovement(v:ProvisionMovement):Promise<ProvisionMovement>; finalizeProvisionMovement(c:CompanyId,id:string,journalId:string):Promise<Provision>;
 allowance(c:CompanyId,id:string):Promise<Allowance|undefined>; reserveAllowance(v:Allowance):Promise<Allowance>; finalizeAllowanceRecognition(c:CompanyId,id:string,journalId:string):Promise<Allowance>; reserveAllowanceRelease(v:AllowanceMovement):Promise<AllowanceMovement>; finalizeAllowanceRelease(c:CompanyId,id:string,journalId:string):Promise<Allowance>;
 writeOff(c:CompanyId,id:string):Promise<AllowanceWriteOff|undefined>; reserveWriteOff(v:AllowanceWriteOff):Promise<AllowanceWriteOff>; markWriteOffProcessing(c:CompanyId,id:string):Promise<void>; finalizeWriteOff(v:AllowanceWriteOff):Promise<void>; releaseWriteOff(c:CompanyId,id:string,reason:string):Promise<void>;
 payroll(c:CompanyId,id:string):Promise<PayrollRun|undefined>; payrollBySource(c:CompanyId,sourceId:string):Promise<PayrollRun|undefined>; reservePayroll(v:PayrollRun):Promise<PayrollRun>; recordPayrollAccrual(c:CompanyId,id:string,journalId:string):Promise<void>; markPayrollPaying(c:CompanyId,id:string):Promise<void>; finalizePayrollPayment(c:CompanyId,id:string,voucherId:string):Promise<PayrollRun>;
}
