import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import{agentId,type AgentId}from'@elhafez/agent-management';import{partyId,type DuplicateCandidate,type Party,type PartyDraft}from'@elhafez/party-registry';import type{CustomerAccess}from'./customer-access.js';import type{CustomerAgentPort,CustomerPartyRegistryPort}from'./customer-dependencies.port.js';import type{CustomerManagementRepository}from'./customer-management.repository.js';import{customerId,type Customer,type CustomerId,type CustomerStatus}from'../domain/customer.js';
export const CUSTOMER_PERMISSIONS=Object.freeze({read:'crm.customer.read',manage:'crm.customer.manage',lifecycle:'crm.customer.lifecycle',delete:'crm.customer.delete',convert:'crm.customer.convert'});
export interface CreateCustomerInput{readonly party:PartyDraft;readonly assignedAgentId?:string|null;readonly commercialNotes?:string;}
export interface UpdateCustomerInput{readonly party?:PartyDraft;readonly assignedAgentId?:string|null;readonly commercialNotes?:string|null;}
export interface CustomerView{readonly customer:Customer;readonly party:Party;}
export type CustomerResolveResult=|{readonly status:'CREATED'|'EXISTING';readonly value:CustomerView}|{readonly status:'EXISTING_SUSPENDED';readonly value:CustomerView}|{readonly status:'REVIEW_REQUIRED';readonly candidates:readonly DuplicateCandidate[]};
export class CustomerManagementApplicationService{constructor(private readonly repository:CustomerManagementRepository,private readonly parties:CustomerPartyRegistryPort,private readonly agents:CustomerAgentPort,private readonly access:CustomerAccess,private readonly now:()=>Date=()=>new Date(),private readonly newId:()=>string=()=>randomUUID()){}
 private async branch(c:ExecutionContext){await this.access.requireBranch(c);}private async perm(c:ExecutionContext,p:string){await this.branch(c);await this.access.requirePermission(c,p);}
 async create(c:ExecutionContext,input:CreateCustomerInput):Promise<CustomerResolveResult>{await this.perm(c,CUSTOMER_PERMISSIONS.manage);return this.resolveOrCreateForIntegration(c,input);}
 async resolveOrCreateForLead(c:ExecutionContext,input:CreateCustomerInput):Promise<CustomerResolveResult>{await this.perm(c,CUSTOMER_PERMISSIONS.convert);return this.resolveOrCreateForIntegration(c,input);}
 async resolveOrCreateForIntegration(c:ExecutionContext,input:CreateCustomerInput):Promise<CustomerResolveResult>{await this.branch(c);const assigned=await this.activeAgent(c,input.assignedAgentId);const resolved=await this.parties.resolveOrCreateForIntegration(c,input.party);if(resolved.status==='REVIEW_REQUIRED')return resolved;const existing=await this.repository.findByParty(c.companyId,resolved.party.id);if(existing)return{status:existing.status==='ACTIVE'?'EXISTING':'EXISTING_SUSPENDED',value:{customer:existing,party:resolved.party}};const at=this.now().toISOString(),seq=await this.repository.nextNumber(c.companyId);const value:Customer={id:customerId(this.newId()),companyId:c.companyId,partyId:resolved.party.id,number:'CUS-'+String(seq).padStart(6,'0'),status:'ACTIVE',assignedAgentId:assigned,commercialNotes:input.commercialNotes?.trim()||null,createdAt:at,updatedAt:at};try{await this.repository.create(value);}catch(error){const concurrent=await this.repository.findByParty(c.companyId,resolved.party.id);if(concurrent)return{status:concurrent.status==='ACTIVE'?'EXISTING':'EXISTING_SUSPENDED',value:{customer:concurrent,party:resolved.party}};throw error;}await this.parties.ensureRoleForIntegration(c,resolved.party.id,'CUSTOMER');if(assigned)await this.agents.registerReferenceForIntegration(c,assigned,'CUSTOMER_PROFILE',value.id);await this.access.audit(c,'customer.created','customer',value.id,{number:value.number});return{status:'CREATED',value:{customer:value,party:resolved.party}};}
 async get(c:ExecutionContext,id:CustomerId):Promise<CustomerView>{await this.perm(c,CUSTOMER_PERMISSIONS.read);const customer=await this.require(c,id,false);return{customer,party:await this.parties.getForIntegration(c,partyId(customer.partyId))};}
 async list(c:ExecutionContext,status?:CustomerStatus,query?:string):Promise<CustomerView[]>{await this.perm(c,CUSTOMER_PERMISSIONS.read);const rows=await this.repository.list(c.companyId,status,query);const views=await Promise.all(rows.map(async customer=>({customer,party:await this.parties.getForIntegration(c,customer.partyId)})));if(!query?.trim())return views;const q=query.toLowerCase();return views.filter(v=>[v.customer.number,v.customer.commercialNotes,v.party.displayName,v.party.phone,v.party.email].some(x=>x?.toLowerCase().includes(q)));}
 async update(c:ExecutionContext,id:CustomerId,input:UpdateCustomerInput):Promise<CustomerView>{await this.perm(c,CUSTOMER_PERMISSIONS.manage);const current=await this.require(c,id,false);if(input.party)await this.parties.updateForIntegration(c,partyId(current.partyId),input.party);let assigned=current.assignedAgentId;if(input.assignedAgentId!==undefined){const next=await this.activeAgent(c,input.assignedAgentId);if(current.assignedAgentId&&current.assignedAgentId!==next)await this.agents.releaseReferenceForIntegration(c,agentId(current.assignedAgentId),'CUSTOMER_PROFILE',current.id);if(next&&next!==current.assignedAgentId)await this.agents.registerReferenceForIntegration(c,next,'CUSTOMER_PROFILE',current.id);assigned=next;}const updated:Customer={...current,assignedAgentId:assigned,commercialNotes:input.commercialNotes===undefined?current.commercialNotes:input.commercialNotes?.trim()||null,updatedAt:this.now().toISOString()};await this.repository.update(updated);await this.access.audit(c,'customer.updated','customer',id,{});return{customer:updated,party:await this.parties.getForIntegration(c,partyId(current.partyId))};}
 async suspend(c:ExecutionContext,id:CustomerId){await this.perm(c,CUSTOMER_PERMISSIONS.lifecycle);const v=await this.require(c,id,false);if(v.status==='SUSPENDED')return v;const u={...v,status:'SUSPENDED' as const,updatedAt:this.now().toISOString()};await this.repository.update(u);await this.access.audit(c,'customer.suspended','customer',id,{});return u;}
 async reactivate(c:ExecutionContext,id:CustomerId){await this.perm(c,CUSTOMER_PERMISSIONS.lifecycle);const v=await this.require(c,id,false);if(v.status==='ACTIVE')return v;const u={...v,status:'ACTIVE' as const,updatedAt:this.now().toISOString()};await this.repository.update(u);await this.access.audit(c,'customer.reactivated','customer',id,{});return u;}
 async hardDelete(c:ExecutionContext,id:CustomerId):Promise<void>{await this.perm(c,CUSTOMER_PERMISSIONS.delete);const v=await this.require(c,id,false);if(v.status==='ACTIVE')throw new ContractValidationError('customer','active customer must be suspended before hard delete');if(await this.repository.referenceCount(c.companyId,id)>0)throw new ContractValidationError('customer','referenced customer cannot be hard deleted');try{await this.repository.delete(c.companyId,id);}catch{throw new ContractValidationError('customer','referenced customer cannot be hard deleted');}if(v.assignedAgentId)await this.agents.releaseReferenceForIntegration(c,agentId(v.assignedAgentId),'CUSTOMER_PROFILE',v.id);await this.parties.removeRoleForIntegration(c,partyId(v.partyId),'CUSTOMER');await this.access.audit(c,'customer.deleted','customer',id,{});}
 async requireActiveForIntegration(c:ExecutionContext,id:CustomerId):Promise<Customer>{await this.branch(c);return this.require(c,id,true);}
 async registerReferenceForIntegration(c:ExecutionContext,id:CustomerId,sourceType:string,sourceId:string):Promise<void>{await this.branch(c);await this.require(c,id,true);await this.repository.addReference({companyId:c.companyId,customerId:id,sourceType:req(sourceType,'sourceType'),sourceId:req(sourceId,'sourceId'),createdAt:this.now().toISOString()});}
 async releaseReferenceForIntegration(c:ExecutionContext,id:CustomerId,sourceType:string,sourceId:string):Promise<void>{await this.branch(c);await this.repository.removeReference(c.companyId,id,sourceType,sourceId);}
 private async require(c:ExecutionContext,id:CustomerId,active:boolean):Promise<Customer>{const v=await this.repository.find(c.companyId,id);if(!v)throw new ContractValidationError('customerId','customer was not found in this company');if(active&&v.status!=='ACTIVE')throw new ContractValidationError('customerId','customer is suspended');return v;}
 private async activeAgent(c:ExecutionContext,value:string|null|undefined):Promise<AgentId|null>{if(!value?.trim())return null;const id=agentId(value);await this.agents.requireActiveForIntegration(c,id);return id;}
}
function req(v:string,f:string){const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x;}
