import{Prisma,type PrismaClient}from'@prisma/client';
import{ContractValidationError}from'@elhafez/contracts';
import type{AutomationWorkflowRepository}from'../application/automation-workflow.repository.js';
import type{ClaimedWorkflowRun,WorkflowExecutionEvidence}from'../application/automation-workflow.ports.js';
import type{WorkflowDefinition,WorkflowEvent,WorkflowExecutionLog,WorkflowRun,WorkflowSpec}from'../domain/automation-workflow.js';

function record(value:Prisma.JsonValue):Readonly<Record<string,unknown>>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Readonly<Record<string,unknown>>:{};}
export class PrismaAutomationWorkflowRepository implements AutomationWorkflowRepository,WorkflowExecutionEvidence{
 constructor(private readonly db:PrismaClient){}
 private definition(row:{id:string;companyId:string;code:string;name:string;triggerEvent:string;status:string;version:number;specJson:Prisma.JsonValue;createdBy:string;createdAt:Date;updatedAt:Date}):WorkflowDefinition{return{id:row.id,companyId:row.companyId,code:row.code,name:row.name,triggerEvent:row.triggerEvent,status:row.status as WorkflowDefinition['status'],version:row.version,spec:row.specJson as unknown as WorkflowSpec,createdBy:row.createdBy,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
 private run(row:{id:string;companyId:string;branchId:string|null;workflowId:string;workflowVersion:number;triggerEvent:string;correlationKey:string;payloadJson:Prisma.JsonValue;status:string;currentStep:number;attemptCount:number;nextRunAt:Date|null;waitingSignal:string|null;lastError:string|null;leaseToken:string|null;leaseExpiresAt:Date|null;createdAt:Date;updatedAt:Date;completedAt:Date|null}):WorkflowRun{return{id:row.id,companyId:row.companyId,branchId:row.branchId,workflowId:row.workflowId,workflowVersion:row.workflowVersion,triggerEvent:row.triggerEvent,correlationKey:row.correlationKey,payload:record(row.payloadJson),status:row.status as WorkflowRun['status'],currentStep:row.currentStep,attemptCount:row.attemptCount,nextRunAt:row.nextRunAt?.toISOString()??null,waitingSignal:row.waitingSignal,lastError:row.lastError,leaseToken:row.leaseToken,leaseExpiresAt:row.leaseExpiresAt?.toISOString()??null,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString(),completedAt:row.completedAt?.toISOString()??null};}
 async createDefinition(input:WorkflowDefinition){try{return this.definition(await this.db.awWorkflowDefinition.create({data:{...input,specJson:input.spec as unknown as Prisma.InputJsonValue,createdAt:new Date(input.createdAt),updatedAt:new Date(input.updatedAt)}}));}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ContractValidationError('code','workflow code already exists');throw error;}}
 async updateDefinition(companyId:string,id:string,input:Pick<WorkflowDefinition,'name'|'triggerEvent'|'status'|'version'|'spec'|'updatedAt'>){const current=await this.db.awWorkflowDefinition.findFirst({where:{companyId,id}});if(!current)throw new ContractValidationError('workflowId','workflow definition was not found');return this.definition(await this.db.awWorkflowDefinition.update({where:{id},data:{name:input.name,triggerEvent:input.triggerEvent,status:input.status,version:input.version,specJson:input.spec as unknown as Prisma.InputJsonValue,updatedAt:new Date(input.updatedAt)}}));}
 async findDefinition(companyId:string,id:string){const row=await this.db.awWorkflowDefinition.findFirst({where:{companyId,id}});return row?this.definition(row):undefined;}
 async listDefinitions(companyId:string){return(await this.db.awWorkflowDefinition.findMany({where:{companyId},orderBy:{code:'asc'}})).map(row=>this.definition(row));}
 async listActiveByEvent(companyId:string,eventName:string){return(await this.db.awWorkflowDefinition.findMany({where:{companyId,triggerEvent:eventName,status:'ACTIVE'},orderBy:{code:'asc'}})).map(row=>this.definition(row));}
 async createRunIdempotent(input:{id:string;event:WorkflowEvent;workflow:WorkflowDefinition;now:string}){try{return this.run(await this.db.awWorkflowRun.create({data:{id:input.id,companyId:input.event.companyId,branchId:input.event.branchId,workflowId:input.workflow.id,workflowVersion:input.workflow.version,triggerEvent:input.event.name,correlationKey:input.event.correlationKey,payloadJson:input.event.payload as Prisma.InputJsonValue,status:'PENDING',currentStep:0,attemptCount:0,nextRunAt:new Date(input.now),createdAt:new Date(input.now),updatedAt:new Date(input.now)}}));}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const prior=await this.db.awWorkflowRun.findUnique({where:{companyId_workflowId_correlationKey:{companyId:input.event.companyId,workflowId:input.workflow.id,correlationKey:input.event.correlationKey}}});if(prior)return this.run(prior);}throw error;}}
 async findRun(companyId:string,id:string){const row=await this.db.awWorkflowRun.findFirst({where:{companyId,id}});return row?this.run(row):undefined;}
 async listRuns(companyId:string,status?:WorkflowRun['status']){return(await this.db.awWorkflowRun.findMany({where:{companyId,...(status?{status}: {})},orderBy:{createdAt:'desc'}})).map(row=>this.run(row));}
 async saveRun(run:WorkflowRun){const result=await this.db.awWorkflowRun.updateMany({where:{id:run.id,companyId:run.companyId},data:{status:run.status,currentStep:run.currentStep,attemptCount:run.attemptCount,nextRunAt:run.nextRunAt?new Date(run.nextRunAt):null,waitingSignal:run.waitingSignal,lastError:run.lastError,leaseToken:run.leaseToken,leaseExpiresAt:run.leaseExpiresAt?new Date(run.leaseExpiresAt):null,updatedAt:new Date(run.updatedAt),completedAt:run.completedAt?new Date(run.completedAt):null}});if(result.count!==1)throw new ContractValidationError('runId','workflow run was not found');return this.findRun(run.companyId,run.id).then(value=>value??Promise.reject(new ContractValidationError('runId','workflow run was not found')));}
 async claimDue(now:string,limit:number,leaseToken:string,leaseExpiresAt:string){for(let attempt=0;attempt<4;attempt++){try{return await this.db.$transaction(async tx=>{const due=await tx.awWorkflowRun.findMany({where:{status:{in:['PENDING','WAITING']},nextRunAt:{lte:new Date(now)},OR:[{leaseExpiresAt:null},{leaseExpiresAt:{lte:new Date(now)}}]},orderBy:{nextRunAt:'asc'},take:limit,select:{id:true}});if(!due.length)return[];const ids=due.map(value=>value.id);await tx.awWorkflowRun.updateMany({where:{id:{in:ids},status:{in:['PENDING','WAITING']},OR:[{leaseExpiresAt:null},{leaseExpiresAt:{lte:new Date(now)}}]},data:{leaseToken,leaseExpiresAt:new Date(leaseExpiresAt)}});return(await tx.awWorkflowRun.findMany({where:{id:{in:ids},leaseToken}})).map(value=>this.run(value) as ClaimedWorkflowRun);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2034'&&attempt<3)continue;throw error;}}return[];}
 async append(log:WorkflowExecutionLog){await this.db.awWorkflowExecutionLog.create({data:{id:log.id,companyId:log.companyId,runId:log.runId,stepIndex:log.stepIndex,kind:log.kind,status:log.status,detailJson:log.detail as Prisma.InputJsonValue,occurredAt:new Date(log.occurredAt)}});}
 async list(companyId:string,runId:string){return(await this.db.awWorkflowExecutionLog.findMany({where:{companyId,runId},orderBy:{occurredAt:'asc'}})).map(row=>({id:row.id,companyId:row.companyId,runId:row.runId,stepIndex:row.stepIndex,kind:row.kind,status:row.status,detail:record(row.detailJson),occurredAt:row.occurredAt.toISOString()}));}
}
