import * as React from 'react';
import { useCallback } from 'react';
import type { AccountRow, VoucherRow } from '../../accounting-client.js';
import {
  AccountingHeader,
  AccountingPage,
  ActionBar,
  Badge,
  Button,
  Card,
  DataGrid,
  EmptyRow,
  KpiStrip,
  ListToolbar,
  Status,
  UnsupportedAction,
  money,
  useListControls,
  type AccountingPresentationProps,
} from './accounting-page-shared.js';

export type { AccountingPresentationProps } from './accounting-page-shared.js';
export { InvoicesPage } from './accounting-invoices-page.js';
export { TreasuryPage } from './accounting-treasury-page.js';

export function AccountingLandingPage(props: AccountingPresentationProps) {
  const links = [
    ['الفواتير', '/accounting/invoices'], ['سندات القبض', '/accounting/receipts'],
    ['سندات الصرف', '/accounting/payments'], ['المصروفات', '/accounting/expenses'],
    ['التسويات', '/accounting/settlements'], ['الاستحقاقات', '/accounting/accruals'],
    ['الشيكات', '/accounting/cheques'], ['الخزينة والبنوك', '/accounting/treasury'],
    ['العملات وأسعار الصرف', '/accounting/currencies'], ['الضرائب', '/accounting/taxes'],
    ['الفترات المالية', '/accounting/periods'], ['القيود اليومية', '/accounting/journal'],
    ['دليل الحسابات', '/accounting/accounts'], ['ميزان المراجعة', '/accounting/trial'],
    ['مراكز التكلفة', '/accounting/costcenters'], ['الأصول الثابتة', '/accounting/assets'],
    ['القروض والتمويل', '/accounting/loans'], ['الموازنات التقديرية', '/accounting/budgets'],
  ] as const;
  return <AccountingPage accent="green"><AccountingHeader title="المحاسبة والمالية" reload={props.reload} notice={props.notice} /><KpiStrip items={[["الفواتير", props.data.invoices.length], ["سندات الخزينة", props.data.vouchers.length], ["القيود", props.data.journals.length], ["مشكلات الرقابة", props.data.controlIssues.filter((row) => !row.resolvedAt).length]]} /><section className="accounting-launchpad" aria-label="أقسام المحاسبة">{links.map(([label, href], index) => <a key={href} href={href}><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong><small>فتح الشاشة</small></a>)}</section></AccountingPage>;
}

function VoucherPage({ props, kind }: { readonly props: AccountingPresentationProps; readonly kind: 'RECEIPT' | 'PAYMENT' }) {
  const receipt = kind === 'RECEIPT';
  const rows = props.data.vouchers.filter((row) => row.kind === kind);
  const searchable = useCallback((row: VoucherRow) => [row.number, row.partyId, row.postingDate, row.sourceId, row.status], []);
  const sortable = useCallback((row: VoucherRow) => `${row.postingDate}-${row.number}`, []);
  const { controls, setControls, visibleRows } = useListControls(rows, searchable, sortable);
  return <AccountingPage accent={receipt ? 'emerald' : 'red'}><AccountingHeader title={receipt ? 'سندات القبض' : 'سندات الصرف'} reload={props.reload} notice={props.notice}><UnsupportedAction reason="يتطلب نموذج تسوية موجّهًا بفاتورة؛ استخدم إجراء التحصيل/السداد من الفواتير">{receipt ? '+ سند قبض' : '+ سند صرف'}</UnsupportedAction></AccountingHeader><KpiStrip items={[[receipt ? 'كل المقبوضات' : 'كل المدفوعات', rows.length], ['سارية', rows.filter((row) => row.status !== 'REVERSED').length], ['مخصصة', rows.filter((row) => row.allocationIds.length > 0).length], ['معكوسة', rows.filter((row) => row.status === 'REVERSED').length]]} /><Card><ListToolbar controls={controls} onChange={setControls} placeholder="رقم السند أو الطرف أو التاريخ أو المرجع أو البيان" /><DataGrid columns={['السند', receipt ? 'من' : 'إلى', 'المبلغ', 'الطريقة', 'الحالة', 'إجراء']}>{visibleRows.length ? visibleRows.map((row) => <tr key={row.id}><td>{row.number}</td><td>{row.partyKind} · {row.partyId}</td><td>{money(row.amount, row.currency)}</td><td>{row.treasuryId}</td><td><Status value={row.status} /> {row.allocationIds.length ? <Badge tone="info">مخصص</Badge> : <Badge>مقدم/غير مخصص</Badge>}</td><td><ActionBar><Button variant="ghost" onClick={() => window.print()}>طباعة</Button>{row.status !== 'REVERSED' ? <UnsupportedAction reason="العكس يحتاج تاريخًا ورقم مستند؛ لا يوجد نموذج route-level بعد">عكس</UnsupportedAction> : null}</ActionBar></td></tr>) : <EmptyRow columns={6} />}</DataGrid></Card></AccountingPage>;
}
export function ReceiptsPage(props: AccountingPresentationProps) { return <VoucherPage props={props} kind="RECEIPT" />; }
export function PaymentsPage(props: AccountingPresentationProps) { return <VoucherPage props={props} kind="PAYMENT" />; }

const SimpleTable = ({ title, accent, actions, sections, props }: { readonly title: string; readonly accent: string; readonly actions?: React.ReactNode; readonly sections: readonly { title?: string; columns: readonly string[]; message?: string }[]; readonly props: AccountingPresentationProps }) => <AccountingPage accent={accent}><AccountingHeader title={title} reload={props.reload} notice={props.notice}>{actions}</AccountingHeader>{sections.map((section, index) => <Card key={`${section.title ?? title}-${index}`} title={section.title}><DataGrid columns={section.columns}><EmptyRow columns={section.columns.length} label={section.message} /></DataGrid></Card>)}</AccountingPage>;

export function ExpensesPage(props: AccountingPresentationProps) { return <AccountingPage accent="red"><AccountingHeader title="المصروفات" reload={props.reload} notice={props.notice}><UnsupportedAction>إدارة التصنيفات</UnsupportedAction><UnsupportedAction>+ مصروف</UnsupportedAction></AccountingHeader><KpiStrip items={[["كل المصروفات", '—'], ["مسودات", '—'], ["مرحلة", '—'], ["مقدمة", '—']]} /><Card><DataGrid columns={['المصروف', 'التصنيف', 'المبلغ', 'المعالجة', 'الحالة', 'إجراء']}><EmptyRow columns={6} label="BLOCKED-BY-BACKEND: لا يوجد عقد قائمة مصروفات" /></DataGrid></Card></AccountingPage>; }
export function SettlementsPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="التسويات والإلغاءات" accent="plum" actions={<><UnsupportedAction>تكوين مخصص ديون</UnsupportedAction><UnsupportedAction>شطب من المخصص</UnsupportedAction><UnsupportedAction>شطب مباشر</UnsupportedAction><UnsupportedAction>رسوم إلغاء عميل</UnsupportedAction><UnsupportedAction>+ تسوية إلغاء مورد</UnsupportedAction></>} sections={[{ title: 'تسويات الموردين', columns: ['الرقم', 'التاريخ', 'النوع', 'المورد', 'البرنامج', 'القيمة', 'الحساب', 'الحالة', 'إجراء'] }, { title: 'تسويات العملاء', columns: ['الرقم', 'التاريخ', 'النوع', 'العميل', 'البرنامج', 'القيمة', 'الحساب', 'الحالة', 'إجراء'] }]} />; }
export function AccrualsPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="الاستحقاقات والإيراد المؤجل" accent="sky" actions={<><UnsupportedAction>استحقاق رواتب</UnsupportedAction><UnsupportedAction>إيراد مستحق</UnsupportedAction><UnsupportedAction>تأجيل تكلفة مورد</UnsupportedAction><UnsupportedAction>+ تأجيل إيراد فاتورة</UnsupportedAction></>} sections={[{ title: 'الإيرادات المؤجلة', columns: ['الرقم', 'الفاتورة', 'العميل', 'الإجمالي', 'المعترف', 'دفعات متبقية', 'الحالة', 'إجراء/الجدول'] }, { title: 'تكاليف الموردين المؤجلة', columns: ['الرقم', 'الفاتورة', 'المورد', 'الإجمالي', 'المحمّل', 'دفعات متبقية', 'الحالة', 'إجراء/الجدول'] }, { title: 'الإيرادات المستحقة', columns: ['الرقم', 'التاريخ', 'العميل', 'القيمة', 'حساب الإيراد', 'الحالة', 'إجراء'] }, { title: 'مسيرات الرواتب', columns: ['الرقم', 'الفترة', 'الإجمالي', 'الاستقطاعات', 'الصافي', 'الحالة', 'إجراء'] }]} />; }
export function ChequesPage(props: AccountingPresentationProps) { return <AccountingPage accent="brown"><AccountingHeader title="الشيكات" reload={props.reload} notice={props.notice}><UnsupportedAction>+ شيك</UnsupportedAction></AccountingHeader><KpiStrip items={[["كل الشيكات", '—'], ["واردة", '—'], ["صادرة", '—'], ["قيد التحصيل / الصرف", '—'], ["تمت", '—'], ["مرتدة", '—']]} /><Card><DataGrid columns={['رقم الشيك', 'الاتجاه', 'البنك', 'الاستحقاق', 'القيمة', 'الحالة', 'حساب البنك', 'إجراءات']}><EmptyRow columns={8} label="BLOCKED-BY-BACKEND: الشيكات ليست ضمن Accounting overview" /></DataGrid></Card></AccountingPage>; }
export function CurrenciesPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="العملات وأسعار الصرف" accent="gold" actions={<><UnsupportedAction>إعادة تقييم العملات</UnsupportedAction><UnsupportedAction>+ عملة</UnsupportedAction></>} sections={[{ columns: ['الكود', 'العملة', 'الرمز', 'السعر الحالي', 'المصدر', 'عدد الأسعار', 'الحالة', 'إجراءات'], message: 'BLOCKED-BY-BACKEND: لا يوجد عقد قائمة عملات في الملخص' }, { title: 'إعادات التقييم', columns: ['الرقم', 'التاريخ', 'عدد المراكز', 'الحالة'] }]} />; }

export function TaxesPage(props: AccountingPresentationProps) { return <AccountingPage accent="brown"><AccountingHeader title="الضرائب" reload={props.reload} notice={props.notice}><Button disabled={!props.capabilities.operate}>+ كود ضريبة</Button><UnsupportedAction>تقرير الضرائب</UnsupportedAction></AccountingHeader><Card><DataGrid columns={['الكود', 'الاسم', 'النسبة', 'الاستخدام', 'مدخلات', 'مخرجات', 'الحالة', 'إجراءات']}>{props.data.taxPolicies.length ? props.data.taxPolicies.map((row) => <tr key={row.id}><td>{row.code}</td><td>{row.code}</td><td>{row.rate}</td><td>فواتير</td><td>{row.inputAccountId}</td><td>{row.outputAccountId}</td><td><Status value="ACTIVE" /></td><td><UnsupportedAction>تعديل</UnsupportedAction></td></tr>) : <EmptyRow columns={8} />}</DataGrid></Card></AccountingPage>; }
export function PeriodsPage(props: AccountingPresentationProps) { return <AccountingPage accent="slate"><AccountingHeader title="الفترات المالية" reload={props.reload} notice={props.notice} /><Card title="السنوات المالية"><DataGrid columns={['السنة', 'من', 'إلى', 'الحالة', 'إجراء']}>{props.data.fiscalYears.length ? props.data.fiscalYears.map((row) => <tr key={row.id}><td>{row.startDate.slice(0, 4)}</td><td>{row.startDate}</td><td>{row.endDate}</td><td><Status value={row.status} /></td><td><UnsupportedAction>{row.status === 'OPEN' ? 'إقفال السنة' : 'إعادة فتح'}</UnsupportedAction></td></tr>) : <EmptyRow columns={5} />}</DataGrid></Card><Card title="فترات السنة الحالية"><DataGrid columns={['الفترة', 'من', 'إلى', 'الحالة', 'إجراء']}>{props.data.periods.length ? props.data.periods.map((row) => <tr key={row.id}><td>{row.id}</td><td>{row.startDate}</td><td>{row.endDate}</td><td><Status value={row.status} /></td><td><ActionBar><UnsupportedAction>فحص الإقفال</UnsupportedAction><UnsupportedAction>{row.status === 'OPEN' ? 'إغلاق' : 'إعادة فتح'}</UnsupportedAction></ActionBar></td></tr>) : <EmptyRow columns={5} />}</DataGrid></Card></AccountingPage>; }
export function JournalPage(props: AccountingPresentationProps) { return <AccountingPage accent="navy"><AccountingHeader title="القيود اليومية" reload={props.reload} notice={props.notice}><UnsupportedAction>+ قيد يدوي</UnsupportedAction></AccountingHeader><KpiStrip items={[["كل القيود المرحلة", props.data.journals.length], ["سارية", props.data.journals.filter((row) => !row.reversalOfId).length], ["معكوسة", props.data.journals.filter((row) => Boolean(row.reversalOfId)).length]]} /><Card title="مسودات القيود اليدوية"><DataGrid columns={['الرقم', 'التاريخ', 'البيان', 'الحالة', 'إجراءات']}><EmptyRow columns={5} /></DataGrid></Card><Card title="القيود المرحلة"><DataGrid columns={['رقم القيد', 'التاريخ', 'البيان', 'المرجع', 'مدين', 'دائن', 'الحالة', 'إجراءات']}>{props.data.journals.length ? props.data.journals.map((row) => <tr key={row.id}><td>{row.number}</td><td>{row.postingDate}</td><td>{row.kind}</td><td>{row.sourceType} · {row.sourceId}</td><td>من تفاصيل القيد</td><td>من تفاصيل القيد</td><td><Status value={row.reversalOfId ? 'REVERSED' : 'POSTED'} /></td><td><ActionBar><Button variant="ghost" onClick={() => window.print()}>عرض / طباعة</Button></ActionBar></td></tr>) : <EmptyRow columns={8} />}</DataGrid></Card><Card title="القوالب المتكررة"><DataGrid columns={['القالب', 'التكرار', 'الموعد القادم', 'الحالة', 'إجراء']}><EmptyRow columns={5} /></DataGrid></Card></AccountingPage>; }

export function AccountsPage(props: AccountingPresentationProps) {
  const byId = new Map(props.data.accounts.map((row) => [row.id, row]));
  const searchable = useCallback((row: AccountRow) => [row.code, row.name, row.classification, row.controlType], []);
  const sortable = useCallback((row: AccountRow) => row.code, []);
  const { controls, setControls, visibleRows } = useListControls(props.data.accounts, searchable, sortable);
  return <AccountingPage accent="steel"><AccountingHeader title="دليل الحسابات" reload={props.reload} notice={props.notice}><UnsupportedAction>رصيد افتتاحي</UnsupportedAction><UnsupportedAction>+ حساب / مجموعة</UnsupportedAction></AccountingHeader><Card><ListToolbar controls={controls} onChange={setControls} placeholder="بحث بالكود أو اسم الحساب" /><DataGrid columns={['الكود', 'الحساب', 'التصنيف', 'الطبيعة', 'مدين', 'دائن', 'الصافي', 'الحالة', 'إجراءات']}>{visibleRows.length ? visibleRows.map((row) => <tr key={row.id}><td>{row.code}</td><td className={row.parentId ? 'accounting-tree-child' : ''}>{row.name}{row.parentId ? <small>تحت {byId.get(row.parentId)?.name ?? row.parentId}</small> : null}</td><td>{row.classification}</td><td>{row.postable ? 'حساب ترحيل' : 'مجموعة'}</td><td>—</td><td>—</td><td>—</td><td>{row.active ? 'نشط' : 'متوقف'}</td><td><ActionBar><UnsupportedAction>كشف</UnsupportedAction><UnsupportedAction>تعديل</UnsupportedAction><UnsupportedAction>تشغيل/إيقاف</UnsupportedAction></ActionBar></td></tr>) : <EmptyRow columns={9} />}</DataGrid></Card></AccountingPage>;
}
export function TrialPage(props: AccountingPresentationProps) { const rows = props.data.reports.trialBalance.rows; return <AccountingPage accent="purple"><AccountingHeader title="ميزان المراجعة" reload={props.reload} notice={props.notice}><Button variant="secondary" onClick={() => window.print()}>طباعة</Button></AccountingHeader><section className="accounting-health" role="status"><strong>حالة الاتزان</strong><span>القيم معروضة من تقرير المالك المالي؛ الفرق يحتاج مراجعة عند عدم التطابق.</span></section><KpiStrip items={[["إجمالي المدين", 'من التقرير'], ["إجمالي الدائن", 'من التقرير'], ["الفرق", 'من التقرير'], ["حسابات الترحيل", rows.length]]} /><Card><DataGrid columns={['الكود', 'الحساب', 'إجمالي مدين', 'إجمالي دائن', 'رصيد مدين', 'رصيد دائن']}>{rows.length ? rows.map((row, index) => <tr key={`${row.accountId ?? row.accountClass}-${index}`}><td>{row.accountId ?? '—'}</td><td>{row.accountClass ?? row.accountId ?? '—'}</td><td>{row.amount}</td><td>—</td><td>{row.amount}</td><td>—</td></tr>) : <EmptyRow columns={6} />}</DataGrid></Card></AccountingPage>; }
export function CostCentersPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="مراكز التكلفة" accent="teal" actions={<UnsupportedAction>+ مركز تكلفة</UnsupportedAction>} sections={[{ columns: ['الكود', 'المركز', 'الأب', 'المسؤول', 'الموازنة', 'الإيراد', 'التكلفة', 'النتيجة', 'الانحراف', 'الحالة', 'إجراءات'] }]} />; }
export function AssetsPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="الأصول الثابتة" accent="gray" actions={<UnsupportedAction>+ أصل ثابت</UnsupportedAction>} sections={[{ columns: ['الرقم', 'الأصل', 'الاقتناء', 'التكلفة', 'مجمع الإهلاك', 'صافي القيمة', 'العمر', 'الحالة', 'إجراءات'] }]} />; }
export function LoansPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="القروض والمخصصات" accent="gray" actions={<><UnsupportedAction>تكوين مخصص</UnsupportedAction><UnsupportedAction>+ قرض / تمويل</UnsupportedAction></>} sections={[{ title: 'القروض والتمويلات', columns: ['الرقم', 'الممول', 'الأصل', 'الفائدة', 'مسدد أصل', 'القسط القادم', 'الحالة', 'إجراء'] }, { title: 'المخصصات', columns: ['الرقم', 'المخصص', 'التاريخ', 'المكوّن', 'المستخدم', 'المتبقي', 'الحالة', 'إجراء'] }]} />; }
export function BudgetsPage(props: AccountingPresentationProps) { return <SimpleTable props={props} title="الموازنات التقديرية" accent="teal" actions={<UnsupportedAction>+ بند موازنة</UnsupportedAction>} sections={[{ columns: ['السنة', 'الحساب', 'مركز التكلفة', 'الموازنة', 'الفعلي', 'الانحراف'] }]} />; }
