import{Module}from'@nestjs/common';import{PrismaClient}from'@prisma/client';import{decimalAmount,sourceReference}from'@elhafez/contracts';import{PlatformCoreApplicationService,PlatformCoreModule}from'@elhafez/platform-core';import{TourismProgramsApplicationService}from'@elhafez/tourism-programs';import{TourismProgramsModule}from'@elhafez/tourism-programs/nest';import{TravelerManagementApplicationService,travelerId}from'@elhafez/traveler-management';import{TravelerManagementModule}from'@elhafez/traveler-management/nest';import{CustomerManagementApplicationService,customerId}from'@elhafez/customer-management';import{CustomerManagementModule}from'@elhafez/customer-management/nest';import{TourismFinanceOrchestrationApplicationService}from'@elhafez/tourism-finance-orchestration';import{TourismFinanceOrchestrationModule}from'@elhafez/tourism-finance-orchestration/nest';import{TourismBookingsApplicationService}from'./application/tourism-bookings.application-service.js';import{TOURISM_BOOKING_ACCESS,TOURISM_BOOKING_CUSTOMER_PORT,TOURISM_BOOKING_FINANCE_PORT,TOURISM_BOOKING_PROGRAM_PORT,TOURISM_BOOKING_TRAVELER_PORT,type TourismBookingAccess,type TourismBookingCustomerPort,type TourismBookingFinancePort,type TourismBookingProgramPort,type TourismBookingTravelerPort}from'./application/booking.ports.js';import{TOURISM_BOOKING_REPOSITORY,type TourismBookingRepository}from'./application/booking.repository.js';import{PlatformTourismBookingAccess}from'./infrastructure/platform-booking.access.js';import{PrismaTourismBookingRepository}from'./infrastructure/prisma-booking.repository.js';
function financialEvidence(value:unknown){if(!value||typeof value!=='object')throw new Error('tourism finance confirmation returned invalid evidence');const workflowId=Reflect.get(value,'workflowId'),invoiceId=Reflect.get(value,'invoiceId'),commissionClaimId=Reflect.get(value,'commissionClaimId'),allocations=Reflect.get(value,'allocations');if(typeof workflowId!=='string'||!workflowId||!Array.isArray(allocations))throw new Error('tourism finance confirmation returned incomplete evidence');const allocationIds:string[]=[];for(const allocation of allocations){if(!allocation||typeof allocation!=='object')throw new Error('tourism finance confirmation returned invalid allocation evidence');const allocationId=Reflect.get(allocation,'id');if(typeof allocationId!=='string'||!allocationId)throw new Error('tourism finance confirmation returned invalid allocation evidence');allocationIds.push(allocationId);}if(invoiceId!==undefined&&typeof invoiceId!=='string')throw new Error('tourism finance confirmation returned invalid invoice evidence');if(commissionClaimId!==undefined&&typeof commissionClaimId!=='string')throw new Error('tourism finance confirmation returned invalid commission evidence');return{workflowId,...(typeof invoiceId==='string'?{invoiceId}:{}),allocationIds,...(typeof commissionClaimId==='string'?{commissionClaimId}:{})};}
function cancellationEvidence(value:unknown){if(!value||typeof value!=='object')throw new Error('tourism finance cancellation returned invalid evidence');if(Reflect.get(value,'cancelled')===true)return{cancelled:true,blockers:[]};const raw=Reflect.get(value,'blockers');if(!Array.isArray(raw))throw new Error('tourism finance cancellation returned incomplete blocker evidence');const blockers=raw.map(item=>{if(!item||typeof item!=='object')throw new Error('tourism finance cancellation returned invalid blocker evidence');const type=Reflect.get(item,'type'),reference=Reflect.get(item,'reference'),detail=Reflect.get(item,'detail');if(typeof type!=='string'||typeof reference!=='string')throw new Error('tourism finance cancellation returned invalid blocker evidence');if(detail!==undefined&&typeof detail!=='string')throw new Error('tourism finance cancellation returned invalid blocker detail');return{type,reference,...(typeof detail==='string'?{detail}:{})};});return{cancelled:false,blockers};}
@Module({imports:[PlatformCoreModule,TourismProgramsModule,TravelerManagementModule,CustomerManagementModule,TourismFinanceOrchestrationModule],providers:[PrismaClient,
 {provide:TOURISM_BOOKING_REPOSITORY,useFactory:(db:PrismaClient)=>new PrismaTourismBookingRepository(db),inject:[PrismaClient]},
 {provide:TOURISM_BOOKING_ACCESS,useFactory:(p:PlatformCoreApplicationService)=>new PlatformTourismBookingAccess(p),inject:[PlatformCoreApplicationService]},
 {provide:TOURISM_BOOKING_PROGRAM_PORT,useFactory:(p:TourismProgramsApplicationService):TourismBookingProgramPort=>({require:(c,b,id)=>p.getForIntegration(c,b,id)}),inject:[TourismProgramsApplicationService]},
 {provide:TOURISM_BOOKING_CUSTOMER_PORT,useFactory:(s:CustomerManagementApplicationService):TourismBookingCustomerPort=>({requireActive:async(c,id)=>{const customer=await s.requireActiveForIntegration(c,customerId(id));return{partyId:customer.partyId}},register:(c,id,b)=>s.registerReferenceForIntegration(c,customerId(id),'TOURISM_BOOKING',b)}),inject:[CustomerManagementApplicationService]},
 {provide:TOURISM_BOOKING_TRAVELER_PORT,useFactory:(s:TravelerManagementApplicationService):TourismBookingTravelerPort=>({requireActive:async(c,id)=>{await s.requireActiveForIntegration(c,travelerId(id));}}),inject:[TravelerManagementApplicationService]},
 {provide:TOURISM_BOOKING_FINANCE_PORT,useFactory:(s:TourismFinanceOrchestrationApplicationService):TourismBookingFinancePort=>({
  confirm:async i=>financialEvidence(await s.confirmBooking({companyId:i.companyId,branchId:i.branchId,commandKey:i.commandKey,booking:sourceReference('TOURISM_BOOKING',i.bookingId),program:sourceReference('TOURISM_PROGRAM',i.programId),programState:'OPEN',programStateEvidence:i.programEvidence,category:i.category,costCenterId:i.costCenterId,customerPartyId:i.customerPartyId,currency:i.currency,grossAmount:decimalAmount(i.grossAmount),discountAmount:decimalAmount(i.discountAmount),...(i.approvalRequestId?{approvalRequestId:i.approvalRequestId}:{}),postingDate:i.postingDate,dueDate:i.dueDate,invoiceNumber:i.invoiceNumber,inventories:i.inventories.map(v=>({...v,quantity:decimalAmount(v.quantity)}))})),
  cancel:async i=>cancellationEvidence(await s.cancelBooking({companyId:i.companyId,branchId:i.branchId,commandKey:i.commandKey,booking:sourceReference('TOURISM_BOOKING',i.bookingId),travelStarted:i.travelStarted,travelEvidence:i.travelEvidence,postingDate:i.postingDate}))
 }),inject:[TourismFinanceOrchestrationApplicationService]},
 {provide:TourismBookingsApplicationService,useFactory:(r:TourismBookingRepository,a:TourismBookingAccess,p:TourismBookingProgramPort,c:TourismBookingCustomerPort,t:TourismBookingTravelerPort,f:TourismBookingFinancePort)=>new TourismBookingsApplicationService(r,a,p,c,t,f),inject:[TOURISM_BOOKING_REPOSITORY,TOURISM_BOOKING_ACCESS,TOURISM_BOOKING_PROGRAM_PORT,TOURISM_BOOKING_CUSTOMER_PORT,TOURISM_BOOKING_TRAVELER_PORT,TOURISM_BOOKING_FINANCE_PORT]}
],exports:[TourismBookingsApplicationService]})export class TourismBookingsModule{}
