import {createHash} from 'node:crypto';
import {ContractValidationError,decimalAmount,type CompanyId,type DecimalAmount,type SourceReference} from '@elhafez/contracts';
import type {TourismFinanceRepository} from './orchestration.repository.js';
import type {BillingPort,CommissionPort,ControlsPort,CostPort,InventoryPort,ProcurementPort,TreasuryPort} from './ports.js';
import type {BookingReference,CancellationBlocker,FinancialSetup,ServiceCategory,ServiceFinancialSnapshot,Workflow,WorkflowKind} from '../domain/orchestration.js';
function stable(value:unknown):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stable).join(',')+']';return '{'+Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+stable(v)).join(',')+'}'}
function hash(value:unknown){return createHash('sha256').update(stable(value)).digest('hex')}
function refKey(value:SourceReference){return `${value.sourceType}:${value.sourceId}`}
function text(value:string,field:string){if(!value?.trim())throw new ContractValidationError(field,'is required')}
function nonNegative(value:DecimalAmount,field:string){const result=decimalAmount(value);if(result.startsWith('-'))throw new ContractValidationError(field,'must not be negative');return result}
function units(value:DecimalAmount){const [whole,fraction='']=value.split('.');return BigInt(whole!+fraction.padEnd(18,'0'))}
function fromUnits(value:bigint){const negative=value<0n,absolute=negative?-value:value,whole=absolute/10n**18n,fraction=absolute%10n**18n;return decimalAmount(`${negative?'-':''}${whole}${fraction?'.'+fraction.toString().padStart(18,'0').replace(/0+$/,''):''}`)}
export interface ConfirmBookingInput {companyId:CompanyId;branchId?:string;commandKey:string;booking:SourceReference;program:SourceReference;programState:'OPEN'|'CLOSED'|'CANCELLED';programStateEvidence:string;category:ServiceCategory;costCenterId:string;customerPartyId:string;currency:string;grossAmount:DecimalAmount;discountAmount:DecimalAmount;approvalRequestId?:string;postingDate:string;invoiceNumber:string;inventory:{allocationId:string;contractId:string;resourceType:string;resourceId:string;serviceDate:string;quantity:DecimalAmount;flightSegmentReference?:SourceReference;visaBatchReference?:SourceReference};commission?:{agentPartyId:string;amount:DecimalAmount}}
export interface CancelBookingInput {companyId:CompanyId;branchId?:string;commandKey:string;booking:SourceReference;travelStarted:boolean;travelEvidence:string;postingDate:string;allocationQuantities:Record<string,DecimalAmount>}
export class TourismFinanceOrchestrationApplicationService {
 constructor(private readonly repo:TourismFinanceRepository,private readonly billing:BillingPort,private readonly treasury:TreasuryPort,private readonly commission:CommissionPort,private readonly cost:CostPort,private readonly inventory:InventoryPort,private readonly procurement:ProcurementPort,private readonly controls:ControlsPort){}
 async configureFinancialSetup(input:FinancialSetup){text(input.id,'id');const value={...input,active:true};await this.repo.saveSetup(value);return value}
 private async workflow(kind:WorkflowKind,input:{companyId:CompanyId;branchId?:string;commandKey:string},source:SourceReference,payload:unknown){text(input.commandKey,'commandKey');const payloadHash=hash(payload),old=await this.repo.workflow(input.companyId,input.commandKey);if(old){if(old.payloadHash!==payloadHash||old.kind!==kind)throw new ContractValidationError('commandKey','conflicting replay');return old}const now=new Date().toISOString(),value:Workflow={id:hash([input.companyId,input.commandKey]).slice(0,32),companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),kind,commandKey:input.commandKey,payloadHash,sourceType:source.sourceType,sourceId:source.sourceId,status:'RUNNING',payload,createdAt:now,updatedAt:now};const reserved=await this.repo.reserveWorkflow(value);if(reserved.payloadHash!==payloadHash)throw new ContractValidationError('commandKey','conflicting replay');return reserved}
 private async effect<T>(workflow:Workflow,name:string,call:(key:string)=>Promise<T>,reference:(result:T)=>string|undefined):Promise<T>{const prior=await this.repo.step(workflow.companyId,workflow.id,name);if(prior?.status==='COMPLETED')return prior.result as T;const step=prior??await this.repo.reserveStep({id:hash([workflow.id,name]).slice(0,32),companyId:workflow.companyId,workflowId:workflow.id,name,effectKey:`TFO:${workflow.id}:${name}`,status:'PENDING',createdAt:new Date().toISOString()});const result=await call(step.effectKey);await this.repo.completeStep(workflow.companyId,step.id,reference(result),result);return result}
 private async complete(workflow:Workflow,result:unknown,status:Workflow['status']='COMPLETED'){const value={...workflow,status,result,updatedAt:new Date().toISOString()};await this.repo.saveWorkflow(value);return value}
 async confirmBooking(input:ConfirmBookingInput){
  text(input.booking.sourceId,'booking.sourceId');text(input.program.sourceId,'program.sourceId');text(input.programStateEvidence,'programStateEvidence');if(input.programState!=='OPEN')throw new ContractValidationError('programState','selling requires OPEN program');
  const gross=nonNegative(input.grossAmount,'grossAmount'),discount=nonNegative(input.discountAmount,'discountAmount');if(units(discount)>units(gross))throw new ContractValidationError('discountAmount','cannot exceed gross');const net=fromUnits(units(gross)-units(discount));const workflow=await this.workflow('BOOKING_CONFIRMATION',input,input.booking,{...input,grossAmount:gross,discountAmount:discount});if(workflow.status==='COMPLETED')return workflow.result;
  const setup=await this.repo.setup(input.companyId,input.category);if(!setup?.active)throw new ContractValidationError('financialSetup',`missing ${input.category} setup`);if(setup.customerPartyId!==input.customerPartyId)throw new ContractValidationError('customerPartyId','does not match financial setup');
  if(discount!=='0')await this.controls.authorizeDiscount({companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),booking:input.booking,amount:discount,...(input.approvalRequestId?{approvalRequestId:input.approvalRequestId}:{})});
  await this.effect(workflow,'COST_CENTER',()=>this.cost.ensureProgram(input.companyId,input.program,input.costCenterId),x=>x.costCenterId);
  const allocation=await this.effect(workflow,'INVENTORY',key=>this.inventory.allocate({companyId:input.companyId,...input.inventory,program:input.program},key),x=>x.allocationId??x.procurementReference);
  const invoiceId=`tfo-invoice:${workflow.id}`;const invoice=await this.effect(workflow,'BILLING',()=>this.billing.createBookingInvoice({id:invoiceId,companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),partyId:input.customerPartyId,number:input.invoiceNumber,postingDate:input.postingDate,currency:input.currency,sourceId:workflow.id,receivableAccountId:setup.receivableAccountId,revenueAccountId:setup.revenueAccountId,amount:net}),x=>x.id);
  let commissionClaimId:string|undefined;if(input.commission){if(!setup.commissionExpenseAccountId||!setup.commissionLiabilityAccountId)throw new ContractValidationError('financialSetup','commission accounts required');const claim=await this.effect(workflow,'COMMISSION',()=>this.commission.create({id:`tfo-commission:${workflow.id}`,companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),agentPartyId:input.commission!.agentPartyId,sourceId:workflow.id,currency:input.currency,amount:input.commission!.amount,expenseAccountId:setup.commissionExpenseAccountId!,liabilityAccountId:setup.commissionLiabilityAccountId!}),x=>x.id);commissionClaimId=claim.id}
  const booking:BookingReference={id:hash([input.companyId,refKey(input.booking)]).slice(0,32),companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),booking:input.booking,program:input.program,invoiceId:invoice.id,allocationIds:allocation.allocationId?[allocation.allocationId]:[],...(commissionClaimId?{commissionClaimId}:{}),workflowId:workflow.id};await this.repo.saveBooking(booking);return (await this.complete(workflow,{...booking})).result;
 }
 async recordBookingDeposit(input:{companyId:CompanyId;branchId?:string;commandKey:string;booking:SourceReference;treasuryId:string;partyId:string;number:string;postingDate:string;amount:DecimalAmount;controlAccountId:string;advanceAccountId:string}){const booking=await this.repo.booking(input.companyId,input.booking);if(!booking)throw new ContractValidationError('booking','financial reference not found');const amount=nonNegative(input.amount,'amount');if(amount==='0')throw new ContractValidationError('amount','must be positive');const workflow=await this.workflow('BOOKING_DEPOSIT',input,input.booking,{...input,amount});if(workflow.status==='COMPLETED')return workflow.result;const voucher=await this.effect(workflow,'TREASURY_DEPOSIT',()=>this.treasury.postDeposit({id:`tfo-deposit:${workflow.id}`,companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),treasuryId:input.treasuryId,partyId:input.partyId,invoiceId:booking.invoiceId,number:input.number,postingDate:input.postingDate,amount,controlAccountId:input.controlAccountId,advanceAccountId:input.advanceAccountId}),x=>x.id);return (await this.complete(workflow,{workflowId:workflow.id,voucherId:voucher.id,invoiceId:booking.invoiceId})).result}
 async getBookingCancellationBlockers(input:{companyId:CompanyId;booking:SourceReference;travelStarted:boolean;travelEvidence:string;procurement?:{purchaseOrderId?:string;commitmentId?:string}}){const booking=await this.repo.booking(input.companyId,input.booking);if(!booking)throw new ContractValidationError('booking','financial reference not found');const blockers:CancellationBlocker[]=[];if(input.travelStarted)blockers.push({type:'TRAVEL_STARTED',reference:input.travelEvidence});const bill=await this.billing.cancellationEvidence(input.companyId,booking.invoiceId);if(bill.hasEconomicAllocationHistory||bill.hasAvailableAdvance)blockers.push({type:'CUSTOMER_SETTLEMENT_REQUIRED',reference:booking.invoiceId});if(booking.commissionClaimId&&(await this.commission.evidence(input.companyId,booking.commissionClaimId)).hasPostedPaymentHistory)blockers.push({type:'PAID_COMMISSION',reference:booking.commissionClaimId});for(const id of booking.allocationIds)for(const item of await this.inventory.blockers(input.companyId,id))blockers.push({type:'INVENTORY',reference:id,detail:item.type});if(input.procurement)for(const item of await this.procurement.blockers(input.companyId,input.procurement))blockers.push({type:item.type,reference:item.purchaseOrderId,detail:item.lineId});return {booking,blockers}}
 async cancelBooking(input:CancelBookingInput){const workflow=await this.workflow('BOOKING_CANCELLATION',input,input.booking,input);if(workflow.status==='COMPLETED')return workflow.result;const evidence=await this.getBookingCancellationBlockers(input);if(evidence.blockers.length){const settlement=evidence.blockers.some(x=>x.type==='CUSTOMER_SETTLEMENT_REQUIRED');return (await this.complete(workflow,{workflowId:workflow.id,blockers:evidence.blockers},settlement?'SETTLEMENT_REQUIRED':'BLOCKED')).result}const booking=evidence.booking;if(booking.commissionClaimId)await this.effect(workflow,'REVERSE_COMMISSION',()=>this.commission.reverse(input.companyId,booking.commissionClaimId!,input.postingDate,`C-${workflow.id}`),x=>x.id);await this.effect(workflow,'CANCEL_INVOICE',()=>this.billing.cancelInvoice(input.companyId,booking.invoiceId,input.postingDate,`C-${workflow.id}`),x=>x.id);for(const allocationId of booking.allocationIds)await this.effect(workflow,`RELEASE:${allocationId}`,key=>this.inventory.release(input.companyId,allocationId,input.allocationQuantities[allocationId]!,key),()=>allocationId);return (await this.complete(workflow,{workflowId:workflow.id,cancelled:true})).result}
 async cancelProgram(input:{companyId:CompanyId;branchId?:string;commandKey:string;program:SourceReference;bookings:readonly {booking:SourceReference;travelStarted:boolean;travelEvidence:string;allocationQuantities:Record<string,DecimalAmount>;procurement?:{purchaseOrderId?:string;commitmentId?:string}}[];postingDate:string}){const workflow=await this.workflow('PROGRAM_CANCELLATION',input,input.program,input);if(workflow.status==='COMPLETED')return workflow.result;const all=await Promise.all(input.bookings.map(x=>this.getBookingCancellationBlockers({companyId:input.companyId,...x})));const blockers=all.flatMap(x=>x.blockers);if(blockers.length)return (await this.complete(workflow,{workflowId:workflow.id,blockers},blockers.some(x=>x.type==='CUSTOMER_SETTLEMENT_REQUIRED')?'SETTLEMENT_REQUIRED':'BLOCKED')).result;for(const item of input.bookings)await this.effect(workflow,`BOOKING:${refKey(item.booking)}`,()=>this.cancelBooking({companyId:input.companyId,...(input.branchId?{branchId:input.branchId}:{}),commandKey:`${input.commandKey}:${refKey(item.booking)}`,booking:item.booking,travelStarted:false,travelEvidence:item.travelEvidence,postingDate:input.postingDate,allocationQuantities:item.allocationQuantities}),()=>refKey(item.booking));await this.repo.saveProgramHistory({id:hash([workflow.id,'CANCELLED']).slice(0,32),companyId:input.companyId,program:input.program,kind:'CANCELLED',workflowId:workflow.id,evidence:{bookings:input.bookings.map(x=>x.booking)},createdAt:new Date().toISOString()});return (await this.complete(workflow,{workflowId:workflow.id,cancelled:true})).result}
 async closeProgram(input:{companyId:CompanyId;branchId?:string;commandKey:string;program:SourceReference;operationalEvidence:string}){const workflow=await this.workflow('PROGRAM_CLOSE',input,input.program,input);if(workflow.status==='COMPLETED')return workflow.result;await this.repo.saveProgramHistory({id:hash([workflow.id,'CLOSED']).slice(0,32),companyId:input.companyId,program:input.program,kind:'CLOSED',workflowId:workflow.id,evidence:{operationalEvidence:input.operationalEvidence},createdAt:new Date().toISOString()});return (await this.complete(workflow,{workflowId:workflow.id,closed:true})).result}
 async getProgramDeletionEligibility(companyId:CompanyId,program:SourceReference){const history=await this.repo.programHistory(companyId,program),bookings=await this.repo.bookingsForProgram(companyId,program),cancelled=history.some(x=>x.kind==='CANCELLED');return {deletable:cancelled&&bookings.length===0,retainFinancialReferences:history.length>0||bookings.length>0,evidenceReferences:[...history.map(x=>x.id),...bookings.map(x=>x.invoiceId)]}}
 async evaluateFinancialReadiness(input:{companyId:CompanyId;program:SourceReference;requiredCategories:readonly ServiceCategory[];costCenterLinked:boolean;approvalResolved:boolean;inventoryBlockers?:readonly string[];procurementBlockers?:readonly string[]}){const blockers:string[]=[];for(const category of input.requiredCategories)if(!(await this.repo.setup(input.companyId,category))?.active)blockers.push(`MISSING_SETUP:${category}`);if(!input.costCenterLinked)blockers.push('MISSING_PROGRAM_COST_CENTER');if(!input.approvalResolved)blockers.push('APPROVAL_UNRESOLVED');blockers.push(...(input.inventoryBlockers??[]).map(x=>`INVENTORY:${x}`),...(input.procurementBlockers??[]).map(x=>`PROCUREMENT:${x}`));return {ready:blockers.length===0,blockers,warnings:[],evidenceReferences:[refKey(input.program)]}}
 async confirmServiceFinancials(input:{id:string;companyId:CompanyId;service:SourceReference;category:ServiceCategory;currency:string;saleAmount:DecimalAmount;costAmount:DecimalAmount;evidence:unknown}){const old=await this.repo.latestSnapshot(input.companyId,input.service),normalized={...input,saleAmount:nonNegative(input.saleAmount,'saleAmount'),costAmount:nonNegative(input.costAmount,'costAmount')};if(old){if(hash({category:old.category,currency:old.currency,saleAmount:old.saleAmount,costAmount:old.costAmount,evidence:old.evidence})!==hash({category:normalized.category,currency:normalized.currency,saleAmount:normalized.saleAmount,costAmount:normalized.costAmount,evidence:normalized.evidence}))throw new ContractValidationError('serviceFinancials','confirmed fields are immutable; use amendment');return old}const value:ServiceFinancialSnapshot={...normalized,version:1,status:'CONFIRMED',createdAt:new Date().toISOString()};await this.repo.saveSnapshot(value);return value}
 async amendServiceFinancials(input:{id:string;companyId:CompanyId;service:SourceReference;category:ServiceCategory;currency:string;saleAmount:DecimalAmount;costAmount:DecimalAmount;evidence:unknown}){const old=await this.repo.latestSnapshot(input.companyId,input.service);if(!old)throw new ContractValidationError('service','no confirmed financial snapshot');const value:ServiceFinancialSnapshot={...input,saleAmount:nonNegative(input.saleAmount,'saleAmount'),costAmount:nonNegative(input.costAmount,'costAmount'),version:old.version+1,status:'AMENDED',supersedesId:old.id,createdAt:new Date().toISOString()};await this.repo.saveSnapshot(value);return value}
 async actualizeIssuance(input:{companyId:CompanyId;branchId?:string;commandKey:string;program:SourceReference;service:SourceReference;kind:'TICKET'|'VISA';amount:DecimalAmount;postingDate:string;flightSegmentReference?:SourceReference;visaAllocationReference?:SourceReference}){if(input.kind==='TICKET'&&!input.flightSegmentReference)throw new ContractValidationError('flightSegmentReference','real flight segment required');if(input.kind==='VISA'&&!input.visaAllocationReference)throw new ContractValidationError('visaAllocationReference','real visa allocation required');const amount=nonNegative(input.amount,'amount');const workflow=await this.workflow('MILESTONE_ACTUALIZATION',input,input.service,{...input,amount});if(workflow.status==='COMPLETED')return workflow.result;const result=await this.effect(workflow,'COST_ACTUALIZATION',()=>this.cost.actualize({id:`tfo-cost:${workflow.id}`,companyId:input.companyId,program:input.program,serviceId:refKey(input.service),amount,postingDate:input.postingDate}),x=>x.id);return (await this.complete(workflow,{workflowId:workflow.id,costEffectId:result.id})).result}
}
