import{randomUUID}from'node:crypto';import{ContractValidationError,type ExecutionContext}from'@elhafez/contracts';import type{TicketHistory,TicketRecord,TicketStatus}from'../domain/ticket.js';import type{TicketRepository}from'./ticket.repository.js';import type{TicketAccess,TicketBookingPort,TicketFinancePort,TicketInventoryPort,TicketTravelerPort}from'./ticket.ports.js';
export const TICKET_PERMISSIONS=Object.freeze({view:'hajj_umrah.ticketing.view',manage:'hajj_umrah.ticketing.manage',issue:'hajj_umrah.ticketing.issue'});
export interface ReserveTicketInput{bookingId:string;travelerId:string;allocationId:string;pnr:string;seat?:string;baggage?:string;fareClass?:string;}
export interface TicketIssueInput{commandKey:string;ticketNumber:string;amount:string;postingDate:string;pnr?:string;seat?:string;baggage?:string;fareClass?:string;}
const req=(v:string,f:string)=>{const x=v.trim();if(!x)throw new ContractValidationError(f,'is required');return x;};const opt=(v?:string)=>v?.trim()||undefined;
export class HajjUmrahTicketingApplicationService{
 constructor(private readonly repo:TicketRepository,private readonly access:TicketAccess,private readonly bookings:TicketBookingPort,private readonly travelers:TicketTravelerPort,private readonly inventory:TicketInventoryPort,private readonly finance:TicketFinancePort,private readonly now:()=>Date=()=>new Date(),private readonly id:()=>string=()=>randomUUID()){}
 private async perm(c:ExecutionContext,p:string){await this.access.requireBranch(c);await this.access.requirePermission(c,p)}
 private async required(c:ExecutionContext,id:string){const v=await this.repo.get(c.companyId,c.branchId,id);if(!v)throw new ContractValidationError('ticketId','ticket not found');return v}
 private hist(c:ExecutionContext,v:TicketRecord,a:TicketHistory['action'],from?:TicketStatus,e?:unknown):TicketHistory{return{id:this.id(),companyId:c.companyId,branchId:c.branchId,ticketId:v.id,action:a,...(from?{fromStatus:from}:{}),toStatus:v.status,revision:v.revision,...(e===undefined?{}:{evidence:e}),actorId:c.actorId,occurredAt:this.now().toISOString()}}
 private async evidence(c:ExecutionContext,bookingId:string,travelerId:string,allocationId:string){const booking=await this.bookings.requireTraveler(c,bookingId,travelerId);await this.travelers.requireActive(c,travelerId);const allocation=await this.inventory.allocation(c.companyId,req(allocationId,'allocationId'));if(!allocation||allocation.resourceType!=='FLIGHT_BLOCK'||allocation.program.sourceId!==booking.programId||!['CONFIRMED','PARTIALLY_RELEASED','CONSUMED'].includes(allocation.status))throw new ContractValidationError('allocationId','real FLIGHT_BLOCK allocation evidence is required');if(!allocation.flightSegmentReference)throw new ContractValidationError('allocationId','persisted real flight-segment evidence is required');return{booking,allocation}}
 async reserve(c:ExecutionContext,input:ReserveTicketInput){await this.perm(c,TICKET_PERMISSIONS.manage);const e=await this.evidence(c,input.bookingId,input.travelerId,input.allocationId);const at=this.now().toISOString();const v:TicketRecord={id:this.id(),companyId:c.companyId,branchId:c.branchId,bookingId:input.bookingId,programId:e.booking.programId,travelerId:input.travelerId,allocationId:e.allocation.id,flightBlockId:e.allocation.resourceId,flightSegmentReference:e.allocation.flightSegmentReference!,pnr:req(input.pnr,'pnr'),...(opt(input.seat)?{seat:opt(input.seat)!}:{}),...(opt(input.baggage)?{baggage:opt(input.baggage)!}:{}),...(opt(input.fareClass)?{fareClass:opt(input.fareClass)!}:{}),status:'RESERVED',revision:1,createdAt:at,updatedAt:at};return this.repo.create(v,this.hist(c,v,'RESERVED'))}
 async issue(c:ExecutionContext,id:string,input:TicketIssueInput){await this.perm(c,TICKET_PERMISSIONS.issue);const old=await this.required(c,id);if(['ISSUED','REISSUED'].includes(old.status)&&old.ticketNumber===input.ticketNumber)return old;if(old.status!=='RESERVED')throw new ContractValidationError('status','only reserved ticket can be issued');await this.evidence(c,old.bookingId,old.travelerId,old.allocationId);const actualization=await this.actualize(c,old,input);const next=this.issued(old,input,'ISSUED',old.revision,actualization);const saved=await this.repo.save(next,this.hist(c,next,'ISSUED',old.status,{ticketNumber:next.ticketNumber,actualization}));await this.access.audit(c,'hajj-umrah.ticket.issued',id,{ticketNumber:next.ticketNumber!});return saved}
 async reissue(c:ExecutionContext,id:string,input:TicketIssueInput){await this.perm(c,TICKET_PERMISSIONS.issue);const old=await this.required(c,id);if(!['ISSUED','REISSUED'].includes(old.status))throw new ContractValidationError('status','only issued ticket can be reissued');await this.evidence(c,old.bookingId,old.travelerId,old.allocationId);const actualization=await this.actualize(c,old,input);const next=this.issued(old,input,'REISSUED',old.revision+1,actualization);return this.repo.save(next,this.hist(c,next,'REISSUED',old.status,{previousTicketNumber:old.ticketNumber,ticketNumber:next.ticketNumber,actualization}))}
 async voidTicket(c:ExecutionContext,id:string,reason:string){await this.perm(c,TICKET_PERMISSIONS.manage);const old=await this.required(c,id);if(old.status==='VOIDED')return old;if(!['ISSUED','REISSUED'].includes(old.status))throw new ContractValidationError('status','only issued ticket can be voided');const next={...old,status:'VOIDED' as const,updatedAt:this.now().toISOString()};return this.repo.save(next,this.hist(c,next,'VOIDED',old.status,{reason:req(reason,'reason')}))}
 async cancel(c:ExecutionContext,id:string,reason:string){await this.perm(c,TICKET_PERMISSIONS.manage);const old=await this.required(c,id);if(old.status==='CANCELLED')return old;if(old.status!=='RESERVED')throw new ContractValidationError('status','only reservation can be cancelled; issued ticket must be voided');const next={...old,status:'CANCELLED' as const,updatedAt:this.now().toISOString()};return this.repo.save(next,this.hist(c,next,'CANCELLED',old.status,{reason:req(reason,'reason')}))}
 async listForIntegration(c:ExecutionContext,programId:string){await this.access.requireBranch(c);return this.repo.list(c.companyId,c.branchId,programId)}
 async list(c:ExecutionContext,p?:string){await this.perm(c,TICKET_PERMISSIONS.view);return this.repo.list(c.companyId,c.branchId,p)}
 async historyFor(c:ExecutionContext,id:string){await this.perm(c,TICKET_PERMISSIONS.view);await this.required(c,id);return this.repo.history(c.companyId,c.branchId,id)}
 private actualize(c:ExecutionContext,v:TicketRecord,input:TicketIssueInput){return this.finance.actualize({companyId:c.companyId,branchId:c.branchId,commandKey:req(input.commandKey,'commandKey'),programId:v.programId,ticketId:v.id,amount:input.amount,postingDate:req(input.postingDate,'postingDate'),flightSegmentReference:v.flightSegmentReference})}
 private issued(old:TicketRecord,input:TicketIssueInput,status:'ISSUED'|'REISSUED',revision:number,evidence:unknown):TicketRecord{return{...old,pnr:opt(input.pnr)??old.pnr,ticketNumber:req(input.ticketNumber,'ticketNumber'),...(input.seat!==undefined?{seat:opt(input.seat)}:{}),...(input.baggage!==undefined?{baggage:opt(input.baggage)}:{}),...(input.fareClass!==undefined?{fareClass:opt(input.fareClass)}:{}),status,revision,issuanceEvidence:evidence,updatedAt:this.now().toISOString()}}
}
