/* eslint-disable @typescript-eslint/no-explicit-any */
import test from'node:test';import assert from'node:assert/strict';import{companyId,decimalAmount}from'@elhafez/contracts';import{BillingSubledgersApplicationService,type CreateInvoiceInput}from'./application/billing-subledgers.application-service.js';import{InMemoryBillingRepository}from'./infrastructure/in-memory-billing.repository.js';
const c=companyId('11111111-1111-4111-8111-111111111111');const money=(x:string)=>decimalAmount(x);function fixture(){const repo=new InMemoryBillingRepository();const journals:any[]=[];const tax={snapshotInvoiceLine:async(i:any)=>({id:'snap:'+i.sourceId,companyId:i.companyId,policyId:'policy',code:i.code,effectiveAt:i.effectiveAt,rate:money('0.1'),taxableAmount:i.taxableAmount,taxAmount:money('10'),outputAccountId:'tax-out',inputAccountId:'tax-in',createdAt:new Date().toISOString()})};const gl={post:async(i:any)=>{journals.push(i);return{...i,lines:i.lines}},reverse:async(_c:any,id:string)=>({id:'reverse:'+id})};return{repo,journals,service:new BillingSubledgersApplicationService(repo,tax as any,gl as any)}}function invoice(overrides:Partial<CreateInvoiceInput>={}):CreateInvoiceInput{return{id:'i1',companyId:c,type:'CUSTOMER',partyId:'party',number:'INV-1',postingDate:'2026-09-01',currency:'EGP',sourceType:'ORDER',sourceId:'o1',controlAccountId:'ar',lines:[{id:'l1',accountId:'revenue',amount:money('100')}],...overrides}}
test('GS-001 customer invoice balances and BR-004 supplies party dimension',async()=>{const f=fixture(),draft=await f.service.createDraft(invoice());const posted=await f.service.postInvoice(c,draft.id);assert.equal(posted.outstanding,'100');assert.deepEqual(f.journals[0].lines,[{accountId:'ar',debit:'100',partyId:'party'},{accountId:'revenue',credit:'100'}])});
test('GS-002 supplier VAT uses frozen snapshot and balanced AP',async()=>{const f=fixture();await f.service.createDraft(invoice({type:'SUPPLIER',externalInvoiceNumber:'EXT',controlAccountId:'ap',lines:[{id:'l1',accountId:'expense',amount:money('100'),taxCode:'VAT'}]}));const p=await f.service.postInvoice(c,'i1');assert.equal(p.baseTotal,'110');assert.equal(p.lines[0]?.taxSnapshotId,'snap:i1:l1');assert.equal(f.journals[0].lines.at(-1).partyId,'party')});
test('BR-007 supplier external number and conflicting replay are rejected',async()=>{const f=fixture();await f.service.createDraft(invoice({type:'SUPPLIER',externalInvoiceNumber:'X'}));await assert.rejects(f.service.createDraft(invoice({id:'i2',sourceId:'o2',type:'SUPPLIER',externalInvoiceNumber:'X'})));await assert.rejects(f.service.createDraft(invoice({number:'changed'})))});
test('BR-008 exact credit boundary passes and excess is blocked',async()=>{const f=fixture();await f.service.setCreditLimit(c,'party',money('100'));await f.service.createDraft(invoice());await f.service.postInvoice(c,'i1');await f.service.createDraft(invoice({id:'i2',sourceId:'o2',number:'2',lines:[{id:'l2',accountId:'revenue',amount:money('0.1')}]}));await assert.rejects(f.service.postInvoice(c,'i2'),/creditLimit/i)});
test('BR-012/013 prefunding applies once and excess becomes advance',async()=>{const f=fixture();await f.service.createDraft(invoice());await f.service.applyAllocation({id:'a1',companyId:c,partyKind:'CUSTOMER',partyId:'party',invoiceId:'i1',amount:money('120'),sourceType:'SETTLEMENT',sourceId:'s1'});const p=await f.service.postInvoice(c,'i1');assert.equal(p.outstanding,'0');assert.equal((await f.service.availableAdvances(c,'CUSTOMER','party'))[0]?.available,'20')});
test('BR-014 restricted supplier advance cannot cross source',async()=>{const f=fixture();await f.service.applyAllocation({id:'a',companyId:c,partyKind:'SUPPLIER',partyId:'s',amount:money('50'),sourceType:'PAY',sourceId:'1',restrictionSourceType:'CONTRACT',restrictionSourceId:'c1'});await assert.rejects(f.service.consumeAdvance({companyId:c,advanceId:'advance:a',amount:money('1'),sourceType:'SUPPLIER_CANCELLATION_CHARGE',sourceId:'x',invoiceSourceType:'CONTRACT',invoiceSourceId:'c2'}))});
test('BR-015 cancellation is linked, immutable and idempotent',async()=>{const f=fixture();await f.service.createDraft(invoice());await f.service.postInvoice(c,'i1');const a=await f.service.cancelInvoice(c,'i1','2026-09-02','R1'),b=await f.service.cancelInvoice(c,'i1','2026-09-02','R1');assert.equal(a.reversalJournalId,b.reversalJournalId);assert.equal(f.repo.invoiceValues.length,1)});
test('GS-009 credit note excess creates advance and consumed downstream blocks reversal',async()=>{const f=fixture();await f.service.createDraft(invoice());await f.service.postInvoice(c,'i1');const a=await f.service.createAdjustment({id:'cn',companyId:c,invoiceId:'i1',kind:'CREDIT_NOTE',amount:money('120'),sourceType:'CN',sourceId:'1',postingDate:'2026-09-02',number:'CN1',offsetAccountId:'returns'});assert.ok(a.advanceId);await f.service.consumeAdvance({companyId:c,advanceId:a.advanceId!,amount:money('1'),sourceType:'CUSTOMER_CANCELLATION_FEE',sourceId:'fee'});await assert.rejects(f.service.reverseAdjustment(c,'cn','2026-09-03','RCN'),/BLOCKED/)});
test('BR-018 recognition blocks deferred adjustment',async()=>{const f=fixture();await f.service.createDraft(invoice({deferred:true}));await f.service.postInvoice(c,'i1');await f.service.recordRecognitionStarted(c,'i1','schedule');await assert.rejects(f.service.createAdjustment({id:'cn',companyId:c,invoiceId:'i1',kind:'CREDIT_NOTE',amount:money('1'),sourceType:'CN',sourceId:'1',postingDate:'2026-09-02',number:'CN',offsetAccountId:'x'}),/recognition/)});
test('BR-020/021 advance charge consumption and BR-022 write-off cap',async()=>{const f=fixture();await f.service.applyAllocation({id:'a',companyId:c,partyKind:'CUSTOMER',partyId:'party',amount:money('20'),sourceType:'PAY',sourceId:'1'});assert.equal((await f.service.consumeAdvance({companyId:c,advanceId:'advance:a',amount:money('5'),sourceType:'CUSTOMER_CANCELLATION_FEE',sourceId:'fee'})).available,'15');await f.service.createDraft(invoice());await f.service.postInvoice(c,'i1');await assert.rejects(f.service.createAdjustment({id:'w',companyId:c,invoiceId:'i1',kind:'WRITE_OFF',amount:money('101'),sourceType:'WO',sourceId:'1',postingDate:'2026-09-02',number:'WO',offsetAccountId:'bad-debt'}),/exceed/)});
test('GS-019 opening customer balance uses OPENING journal semantics',async()=>{const f=fixture();await f.service.createDraft(invoice({type:'OPENING_CUSTOMER_BALANCE',lines:[{id:'l',accountId:'opening-equity',amount:money('50')}]}));await f.service.postInvoice(c,'i1');assert.equal(f.journals[0].kind,'OPENING')});
