import { ContractValidationError,type CompanyId } from '@elhafez/contracts'; import { dateOnly,type AccountingPeriod,type CloseHistory,type FiscalYear } from '../domain/period.js'; import type { PeriodRepository } from './period.repository.js';
export interface PostingAuthorization { companyId:CompanyId; fiscalYearId:string; periodId:string; postingDate:string }
export interface FiscalCloseInstruction { companyId:CompanyId; fiscalYearId:string; startDate:string; endDate:string }
export class PeriodControlApplicationService {
 constructor(private readonly repo:PeriodRepository){}
 async createFiscalYear(input:FiscalYear){ dateOnly(input.startDate); dateOnly(input.endDate); if(input.startDate>input.endDate) throw new ContractValidationError('fiscalYear','invalid range'); if((await this.repo.years(input.companyId)).some(x=>input.startDate<=x.endDate&&input.endDate>=x.startDate)) throw new ContractValidationError('fiscalYear','overlapping fiscal year'); await this.repo.saveYear({...input,status:'OPEN'}); return input; }
 async createPeriod(input:AccountingPeriod){ dateOnly(input.startDate); dateOnly(input.endDate); const y=(await this.repo.years(input.companyId)).find(x=>x.id===input.fiscalYearId); if(!y) throw new ContractValidationError('fiscalYearId','not found for company'); if(input.startDate<y.startDate||input.endDate>y.endDate||input.startDate>input.endDate) throw new ContractValidationError('period','must stay inside fiscal year'); if((await this.repo.periods(input.companyId,input.fiscalYearId)).some(x=>input.startDate<=x.endDate&&input.endDate>=x.startDate)) throw new ContractValidationError('period','overlapping period'); await this.repo.savePeriod({...input,status:'OPEN'}); return input; }
 async setPeriodStatus(companyId:CompanyId,id:string,status:'OPEN'|'CLOSED'){ const p=(await this.repo.periods(companyId)).find(x=>x.id===id); if(!p) throw new ContractValidationError('period','not found'); await this.repo.savePeriod({...p,status}); }
 async authorizePosting(companyId:CompanyId,postingDate:string):Promise<PostingAuthorization>{ dateOnly(postingDate); const year=(await this.repo.years(companyId)).find(x=>postingDate>=x.startDate&&postingDate<=x.endDate); if(!year) throw new ContractValidationError('postingDate','no valid fiscal period exists'); if(year.status==='CLOSED') throw new ContractValidationError('postingDate','fiscal year is closed'); const period=(await this.repo.periods(companyId,year.id)).find(x=>postingDate>=x.startDate&&postingDate<=x.endDate); if(!period) throw new ContractValidationError('postingDate','no valid fiscal period exists'); if(period.status==='CLOSED') throw new ContractValidationError('postingDate','accounting period is closed'); return Object.freeze({companyId,fiscalYearId:year.id,periodId:period.id,postingDate}); }
 async authorizeFiscalCloseReversal(companyId:CompanyId,postingDate:string,closeJournalId:string):Promise<PostingAuthorization>{ dateOnly(postingDate); const year=(await this.repo.years(companyId)).find(x=>postingDate>=x.startDate&&postingDate<=x.endDate); const history=year&&(await this.repo.closeHistory(companyId,year.id)).find(x=>x.closeJournalId===closeJournalId); if(!year||year.status!=='CLOSED'||!history) throw new ContractValidationError('reversal','authorized closed-year close reference required'); const period=(await this.repo.periods(companyId,year.id)).find(x=>postingDate>=x.startDate&&postingDate<=x.endDate); if(!period) throw new ContractValidationError('postingDate','no valid fiscal period exists'); return Object.freeze({companyId,fiscalYearId:year.id,periodId:period.id,postingDate}); }
 async prepareFiscalClose(companyId:CompanyId,fiscalYearId:string):Promise<FiscalCloseInstruction>{ const y=(await this.repo.years(companyId)).find(x=>x.id===fiscalYearId); if(!y||y.status==='CLOSED') throw new ContractValidationError('fiscalYear','must be open'); return Object.freeze({companyId,fiscalYearId,startDate:y.startDate,endDate:y.endDate}); }
 async completeFiscalClose(i:FiscalCloseInstruction,result:{journalId:string},at=new Date().toISOString()){ const y=(await this.repo.years(i.companyId)).find(x=>x.id===i.fiscalYearId); if(!y||y.status!=='OPEN') throw new ContractValidationError('fiscalYear','must be open'); const existing=(await this.repo.closeHistory(i.companyId,i.fiscalYearId)).find(x=>x.closeJournalId===result.journalId); if(existing) return existing; const h:CloseHistory={id:`close:${i.fiscalYearId}:${result.journalId}`,companyId:i.companyId,fiscalYearId:i.fiscalYearId,closeJournalId:result.journalId,closedAt:at}; await this.repo.saveClose(h); await this.repo.saveYear({...y,status:'CLOSED'}); return h; }
 async prepareReopen(companyId:CompanyId,fiscalYearId:string){ const y=(await this.repo.years(companyId)).find(x=>x.id===fiscalYearId); const h=(await this.repo.closeHistory(companyId,fiscalYearId)).at(-1); if(!y||y.status!=='CLOSED'||!h) throw new ContractValidationError('fiscalYear','closed year history required'); return Object.freeze({companyId,fiscalYearId,closeJournalId:h.closeJournalId}); }
 async completeReopen(input:{companyId:CompanyId;fiscalYearId:string;closeJournalId:string},result:{journalId:string},at=new Date().toISOString()){ const y=(await this.repo.years(input.companyId)).find(x=>x.id===input.fiscalYearId); const h=(await this.repo.closeHistory(input.companyId,input.fiscalYearId)).find(x=>x.closeJournalId===input.closeJournalId); if(!y||!h) throw new ContractValidationError('reopen','history missing'); if(h.reversalJournalId){ if(h.reversalJournalId!==result.journalId) throw new ContractValidationError('reopen','conflicting reversal'); return h; } const updated={...h,reversalJournalId:result.journalId,reopenedAt:at}; await this.repo.saveClose(updated); await this.repo.saveYear({...y,status:'OPEN'}); return updated; }
}
