import type{CompanyId,ExecutionContext,SourceReference}from'@elhafez/contracts';import type{TourismProgram}from'@elhafez/tourism-programs';import type{BookingFinancialEvidence}from'../domain/booking.js';
export interface TourismBookingAccess{requireBranch(c:ExecutionContext):Promise<void>;requirePermission(c:ExecutionContext,p:string):Promise<void>;audit(c:ExecutionContext,action:string,id:string,metadata?:Record<string,unknown>):Promise<void>}
export interface TourismBookingProgramPort{require(companyId:CompanyId,branchId:string,id:string):Promise<TourismProgram>}
export interface TourismBookingCustomerPort{requireActive(c:ExecutionContext,id:string):Promise<{partyId:string}>;register(c:ExecutionContext,id:string,bookingId:string):Promise<void>}
export interface TourismBookingTravelerPort{requireActive(c:ExecutionContext,id:string):Promise<void>}
export interface BookingInventorySelectionInput{contractId:string;resourceType:string;resourceId:string;serviceDate:string;quantity:string;periodEnd?:string;flightSegmentReference?:SourceReference;visaBatchReference?:SourceReference}
export interface BookingInventoryInput extends BookingInventorySelectionInput{allocationId:string}
export interface BookingFinanceConfirmInput{companyId:CompanyId;branchId:string;commandKey:string;bookingId:string;programId:string;programEvidence:string;category:'HOTEL'|'FLIGHT'|'TRANSPORT'|'VISA'|'OTHER';costCenterId:string;customerPartyId:string;currency:string;grossAmount:string;discountAmount:string;postingDate:string;dueDate:string;invoiceNumber:string;inventories:readonly BookingInventoryInput[];approvalRequestId?:string}
export type TourismBookingConfirmInput=Omit<BookingFinanceConfirmInput,'companyId'|'branchId'|'bookingId'|'programId'|'programEvidence'|'customerPartyId'|'inventories'>&{inventories:readonly BookingInventorySelectionInput[]}
export interface BookingFinanceCancelResult{cancelled:boolean;blockers:readonly {type:string;reference:string;detail?:string}[]}
export interface TourismBookingFinancePort{confirm(input:BookingFinanceConfirmInput):Promise<BookingFinancialEvidence>;cancel(input:{companyId:CompanyId;branchId:string;commandKey:string;bookingId:string;travelStarted:boolean;travelEvidence:string;postingDate:string}):Promise<BookingFinanceCancelResult>}
export const TOURISM_BOOKING_ACCESS=Symbol('TOURISM_BOOKING_ACCESS'),TOURISM_BOOKING_PROGRAM_PORT=Symbol('TOURISM_BOOKING_PROGRAM_PORT'),TOURISM_BOOKING_CUSTOMER_PORT=Symbol('TOURISM_BOOKING_CUSTOMER_PORT'),TOURISM_BOOKING_TRAVELER_PORT=Symbol('TOURISM_BOOKING_TRAVELER_PORT'),TOURISM_BOOKING_FINANCE_PORT=Symbol('TOURISM_BOOKING_FINANCE_PORT');
